### ISSUE TITLE
Can't build server on ARM64 Odroid C2

### ISSUE THREAD

**Issue by b3n3w** [Genymobile/scrcpy#1021]
Hi there,

i would like to build to current server version of scrcpy on my odroid C2 Ubuntu 18.04 Mate LTS. 
Currently i am getting an error message while executing this command:

odroid@odroid:~/Downloads/scrcpy-master$ meson x --buildtype release --strip -Db_lto=true     -Dprebuilt_server=/path/to/scrcpy-server.jar

"OSError: [Errno 8] Exec format error: 'ninja'"

Full message: 

odroid@odroid:~/Downloads/scrcpy-master$ meson x --buildtype release --strip -Db_lto=true     -Dprebuilt_server=/path/to/scrcpy-server.jar
The Meson build system
Version: 0.45.1
Source dir: /home/odroid/Downloads/scrcpy-master
Build dir: /home/odroid/Downloads/scrcpy-master/x
Build type: native build
Project name: scrcpy
Native C compiler: cc (gcc 7.4.0 "cc (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1) 7.4.0")
Build machine cpu family: aarch64
Build machine cpu: aarch64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libavformat found: YES 57.83.100
Native dependency libavcodec found: YES 57.107.100
Native dependency libavutil found: YES 55.78.100
Native dependency sdl2 found: YES 2.0.8
Configuring config.h using configuration
Build targets in project: 3
Traceback (most recent call last):
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 361, in run
    app.generate()
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 150, in generate
    self._generate(env)
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 207, in _generate
    g.generate(intr)
  File "/usr/share/meson/mesonbuild/backend/ninjabackend.py", line 203, in generate
    self.ninja_command = environment.detect_ninja(log=True)
  File "/usr/share/meson/mesonbuild/environment.py", line 96, in detect_ninja
    p, found = Popen_safe([n, '--version'])[0:2]
  File "/usr/share/meson/mesonbuild/mesonlib.py", line 721, in Popen_safe
    stderr=stderr, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'ninja'

**Comment by rom1v** [comment]
Is `ninja` / `ninja-build` installed?

Also see https://stackoverflow.com/questions/27606653/oserror-errno-8-exec-format-error for clues.

**Comment by b3n3w** [comment]
yes i have installed the latest version of ninja build

**Comment by rom1v** [comment]
> Some googling says that it is caused by trying to run a binary with the wrong architecture (e.g. 64 bit exe on 32 bit os). Can you verify that the binary it finds is the correct one and runnable and that if it is a script that its shebang line is correct?

https://github.com/mesonbuild/meson/issues/91#issuecomment-87127226

**Comment by b3n3w** [comment]
Checked the shebang .. 
getting this message:

cannot execute binary file: Exec format error
odroid@odroid:~/scrcpy$ sudo ninja -Cx install
/usr/local/bin/ninja: 1: /usr/local/bin/ninja: ELF: not found
/usr/local/bin/ninja: 2: /usr/local/bin/ninja: �: not found
/usr/local/bin/ninja: 3: /usr/local/bin/ninja: Syntax error: ")" unexpected


also tried to reinstall ninja build

**Comment by rom1v** [comment]
How did you install `ninja`?

It seems it's not the binary for your architecture.

**Comment by Biswa96** [comment]
I have successfully compiled the PC part of scrcpy in Raspberry Pi 4B ArchLinux ARM. Here is the command I have used:

```sh
meson \
--buildtype release \
--strip \
-Db_lto=true \
-Dprebuilt_server="scrcpy-server-$VER" \
build
ninja -C build
```
