### ISSUE TITLE
CTRL + O Crashes - OP 7T Pro - Android 10

### ISSUE THREAD

**Issue by iiasceri** [Genymobile/scrcpy#1053]
Hi,
      You already know the issue, feel free to contact me if u want.
      I searched this issue found "fixed on dev branch, will be in next release 5 Nov"
      So u know

INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
C:\aDev\scrcpy\scrcpy-server.jar: 1 fi...shed. 3.0 MB/s (22546 bytes in 0.007s)
INFO: Initial texture: 1440x3120
[server] ERROR: Exception on thread Thread[Thread-1,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:96)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:165)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:113)
        at com.genymobile.scrcpy.Controller.control(Controller.java:73)
        at com.genymobile.scrcpy.Server$1.run(Server.java:45)
        at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:94)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:1523)
        ... 7 more

**Comment by rom1v** [comment]
> INFO: scrcpy 1.10

Just use the latest version.

**Comment by iiasceri** [comment]
Yeah sorry I just realized that when was looking at FPS :)
