### ISSUE TITLE
Nexus 7 on win 10 won't start

### ISSUE THREAD

**Issue by hylke94** [Genymobile/scrcpy#1058]
```
..\scrcpy-win64-v1.12.1> .\scrcpy.exe
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
..\scrcpy-win64-v1.12.1\scrcpy-server: 1 file pushed. 2.4 MB/s (26202 bytes in 0.010s)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1778)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:167)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:68)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
        at com.genymobile.scrcpy.Server.main(Server.java:163)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
INFO: Initial texture: 1200x1920
WARN: Device disconnected
Press any key to continue...
```

With the suggested extra option, it runs perfectly.
```
..\scrcpy-win64-v1.12.1> .\scrcpy.exe -m 1024
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
..\scrcpy-win64-v1.12.1\scrcpy-server: 1 file pushed. 2.5 MB/s (26202 bytes in 0.010s)
INFO: Initial texture: 640x1024
```

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream

**Comment by hylke94** [comment]
That's what I said. The suggested option `-m 1024` works. But is there not an auto-detect system, where this exception can be mapped in?

**Comment by rom1v** [comment]
> That's what I said.

Yes, but there was no question, so I just linked to the explanation.

> But is there not an auto-detect system, where this exception can be mapped in?

That's what 8a694a97855333849976bea5e558eaa45add0168 does to suggest a fix. It does not use `-m 1024` automatically in that case, because it's up to the user to use the value they want (`-m 1280`, etc.) until the hardware decoder refuses.

**Comment by hylke94** [comment]
Ahh, I see. My fault indeed.

Ah, but is it an option to try the different definitions for, let's say, two or three steps down? I did run it by hand (as a developer myself) to see the error and suggestion. But not every user is gonna try this.
