### ISSUE TITLE
a Exception

### ISSUE THREAD

**Issue by acai2046** [Genymobile/scrcpy#1070]
C:\Users\Administrator>scrcpy
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
E:\works\scrcpy\scrcpy-server: 1 file ...shed. 0.6 MB/s (26202 bytes in 0.039s)
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml
 (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibili
tyLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(Theme
CompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibili
tyLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:
31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility
.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java
:40)
        at android.content.res.Resources.<init>(Resources.java:267)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
        at android.content.res.Resources.getSystem(Resources.java:190)
        at android.app.LoadedApk.<init>(LoadedApk.java:211)
        at android.app.ContextImpl.createSystemContext(ContextImpl.java:2331)
        at android.app.ActivityThread.getSystemContext(ActivityThread.java:2191)

        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:5
6)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
        at com.genymobile.scrcpy.Server.main(Server.java:163)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)
CRITICAL: Could not create renderer: Couldn't find matching render driver
Press any key to continue...

**Comment by acai2046** [comment]
C:\Users\Administrator>adb shell
chiron:/ $ ls /data/
ls: /data/: Permission denied
1|chiron:/ $ ls /
ls: //vndservice_contexts: Permission denied
ls: //verity_key: Permission denied
ls: //vendor_service_contexts: Permission denied
ls: //vendor_hwservice_contexts: Permission denied
ls: //ueventd.rc: Permission denied
ls: //plat_hwservice_contexts: Permission denied
ls: //init.zygote64_32.rc: Permission denied
ls: //init.zygote32.rc: Permission denied
ls: //init.usb.rc: Permission denied
ls: //init.usb.configfs.rc: Permission denied
ls: //init.recovery.qcom.rc: Permission denied
ls: //init.recovery.hardware.rc: Permission denied
ls: //init.rc: Permission denied
ls: //init.miui.rc: Permission denied
ls: //init.miui.post_boot.sh: Permission denied
ls: //init.miui.nativedebug.rc: Permission denied
ls: //init.miui.google_revenue_share_v2.rc: Permission denied
ls: //init.miui.google_revenue_share.rc: Permission denied
ls: //init.miui.early_boot.sh: Permission denied
ls: //init.miui.cust.rc: Permission denied
ls: //init.environ.rc: Permission denied
ls: //init.batteryd.rc: Permission denied
ls: //init: Permission denied
ls: //default.prop: Permission denied
ls: //cn.prop: Permission denied
acct        data     plat_file_contexts     sdcard
bin         dev      plat_property_contexts sepolicy
bt_firmware dsp      plat_seapp_contexts    storage
bugreports  etc      plat_service_contexts  sys
cache       firmware proc                   system
charger     mnt      product                vendor
config      odm      res                    vendor_file_contexts
cust        oem      root                   vendor_property_contexts
d           persist  sbin                   vendor_seapp_contexts

**Comment by acai2046** [comment]
![Uploading 图片.png…]()
![Uploading 图片.png…]()
