### ISSUE TITLE
Crostini for chrome os - no touch

### ISSUE THREAD

**Issue by Lucaacer** [Genymobile/scrcpy#1107]
Hello, I spent some time in building scrcpy for my chromebook. Most of the time was required to set the build environment, since I had to install Java jdk and Android studio. It's a small and not powerful device, so I had never used it to compile.

Btw, the first build failed because I hadn't previously accepted a bunch or Android studio licenses... Well, I prefer the shell but, since Android studio has got a well deployed GUI, why don't they put a big button asking you to accept their licenses? It took me 10 mins to find a command line solution:(

Anyway, everything works very well both via USB and via tcip, but touch input does not work. Obviously my lenovo thinpad  yoga 11e 4th has got a touchscreen.

This is the output
```
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
[100%] /data/local/tmp/scrcpy-server.jar
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.Resources.<init>(Resources.java:267)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
        at android.content.res.Resources.getSystem(Resources.java:190)
        at android.app.LoadedApk.<init>(LoadedApk.java:211)
        at android.app.ContextImpl.createSystemContext(ContextImpl.java:2331)
        at android.app.ActivityThread.getSystemContext(ActivityThread.java:2168)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
        at com.genymobile.scrcpy.Server.main(Server.java:163)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)
INFO: Initial texture: 1080x2280
```

The phone is a xiaomi mi 8 lite and touch works with a windows pc. It sports android 9.

It is not the first world issue, but just to report, mainly because I like your work and I am a curious guy:)

**Comment by rom1v** [comment]
The `FileNotFoundException` is not really a bug (but on `dev` it is not printed anymore). See #994.

> touch input does not work

It does not work from Crostini on Chrome OS but works on Windows? Do keyboard and mouse work?

You could check what events you receive from SDL:
https://github.com/Genymobile/scrcpy/blob/0fb22c3e98caed6d7b07f8e53caa9da2ed6334d7/app/src/scrcpy.c#L130

**Comment by Lucaacer** [comment]
Thanks for the response.
It does not work from Crostini on Chrome OS and it works on Windows. Keyboard and touchpad work flawlessly.
Sorry, where can I find the log files referring to line 130?

**Comment by Lucaacer** [comment]
When I start scrcpy with a lower res scrcpy -m 500 it recognizes swipes in the lock screen, but not when the device is unlocked or, at least, that how it looks

**Comment by Lucaacer** [comment]
Same issue with a Redmi 7, still with android 9 and miui 11 and something, which works in windows as well.

Here is enclosed the adb logcat for my phone. I actually can't see where the issue is.

Good work.

[logcat.txt](https://github.com/Genymobile/scrcpy/files/4102628/logcat.txt)

**Comment by Lucaacer** [comment]
Just an update, touch does not work with a samsung s9 too. It could be something on the crostini side.

I will test everything with a real linux touch screen laptop

**Comment by Lucaacer** [comment]
It was very likely due to some issue in compiling. Anyway, there's no reason to keep it still open
