### ISSUE TITLE
can you invent custom frame cap for less usage of mobile

### ISSUE THREAD

**Issue by StylishBoyGaming** [Genymobile/scrcpy#1108]

**Comment by rom1v** [comment]
> custom frame cap

:question:

**Comment by StylishBoyGaming** [comment]
example: i want use device encoder to record  only 30 frame

**Comment by rom1v** [comment]
30 frames then stop? Or 30 frames per second? (`--max-fps 30`)

**Comment by StylishBoyGaming** [comment]
30 frame per second ---max-fps 30 ..is this available in scrcpy ???

**Comment by rom1v** [comment]
Yes, #488.

**Comment by StylishBoyGaming** [comment]
this thong is showing 
 at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.Resources.<init>(Resources.java:267)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
        at android.content.res.Resources.getSystem(Resources.java:190)
        at android.app.LoadedApk.<init>(LoadedApk.java:211)
        at android.app.ContextImpl.createSystemContext(ContextImpl.java:2332)
        at android.app.ActivityThread.getSystemContext(ActivityThread.java:2199)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
        at com.genymobile.scrcpy.Server.main(Server.java:163)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)
[server] WARN: Max FPS is only supported since Android 10, the option has been ignored

**Comment by rom1v** [comment]
In scrcpy 12.1, it works only for Android 10 devices.
In `dev` branch (not released yet), it also works on earlier devices.

https://github.com/Genymobile/scrcpy/issues/488#issuecomment-554787689
