### ISSUE TITLE
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml (No such file or directory)

### ISSUE THREAD

**Issue by d3dbit** [Genymobile/scrcpy#1116]
Hi,
I am getting the next error when I run scrcpy.exe (on Windows 10).
How can I resolve this issue?
Thanks & Regards.

```
>{...}\scrcpy-win64-v1.12.1\scrcpy.exe
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
{...}\scrcpy-win64-v1....py-server: 1 file pushed. 1.3 MB/s (26202 bytes in 0.019s)
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:40)
        at android.content.res.Resources.<init>(Resources.java:267)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
        at android.content.res.Resources.getSystem(Resources.java:190)
        at android.app.LoadedApk.<init>(LoadedApk.java:211)
        at android.app.ContextImpl.createSystemContext(ContextImpl.java:2331)
        at android.app.ActivityThread.getSystemContext(ActivityThread.java:2168)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
        at com.genymobile.scrcpy.Server.main(Server.java:163)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)
INFO: Initial texture: 1080x2160
```

**Comment by rom1v** [comment]
This error is harmless, see #994. It is not printed anymore (on the development branch).

Besides this, does scrcpy work normally? (If not, it is probably unrelated.)

**Comment by d3dbit** [comment]
@rom1v OK. Thanks for your support.
Yes. I confirm that scrcpy works normally.

**Comment by d3dbit** [comment]
> This error is harmless, see #994. It is not printed anymore (on the development branch).
@rom1v OK. Thanks for your support.

> Besides this, does scrcpy work normally? (If not, it is probably unrelated.)
Yes. I confirm that scrcpy works normally.
