### ISSUE TITLE
Tons of Error with my Xiaomi 9T Pro (K20 Pro)

### ISSUE THREAD

**Issue by jasonisaddicted** [Genymobile/scrcpy#1123]
Bunch of errors pop out.

Everything works fine with my old Note 8 (Exynos) until I got this new phone.

These are the codes.

C:\Users\Jason Lim\Desktop>cd c:\Mirror

c:\Mirror>adb devices
List of devices attached
192.168.0.161:5555      device

I can still mirror but It's very laggy, drop frames

c:\Mirror>adb connect 192.168.0.161
already connected to 192.168.0.161:5555

c:\Mirror>scrcpy -b 16M --always-on-top
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
c:\Mirror\scrcpy-server: 1 file pushed. 0.7 MB/s (26202 bytes in 0.034s)
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:40)
        at android.content.res.Resources.<init>(Resources.java:283)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
        at android.content.res.Resources.getSystem(Resources.java:204)
        at android.app.LoadedApk.<init>(LoadedApk.java:235)
        at android.app.ContextImpl.createSystemContext(ContextImpl.java:2430)
        at android.app.ActivityThread.getSystemContext(ActivityThread.java:2427)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
        at com.genymobile.scrcpy.Server.main(Server.java:163)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        ... 22 more
INFO: Initial texture: 2336x1080

**Comment by rom1v** [comment]
The error backtrace is harmless (see #994).

If it's laggy, try to reduce the definition (for example `scrcpy -m1024`). Either your device is not able to encode in real time at this definition, or your computer is not able to decode fast enough.

**Comment by jasonisaddicted** [comment]
> The error backtrace is harmless (see #994).
> 
> If it's laggy, try to reduce the definition (for example `scrcpy -m1024`). Either your device is not able to encode in real time at this definition, or your computer is not able to decode fast enough.

Hm... It works fine with my Note 8 (Exynos version), no drop frames, no problem at all...

Got this new Xiaomi 9T Pro for better gaming experience, and stream some games with my friends and turned out unable to decode fast enough? That's a shame..

**Comment by jasonisaddicted** [comment]
Tested on ApowerMirror App (paid version), wireless, it is running smoothly.

Will try to tweak the settings and see how it goes.

For reference of my PC rig:
Intel i7 8700K
32GB RAM
Samsung Evo 970 500GB
GIGABYTE Z390 M
Aorus GTX1080ti 11GB

**Comment by jasonisaddicted** [comment]
Ok, tested with this setting and the performance is the same.

cd c:\Mirror
adb devices
adb connect 192.168.0.161
scrcpy -b 1M -m720 --always-on-top

For my previous setting for my Galaxy Note 8:
cd c:\Mirror
adb devices
adb connect 192.168.0.118
scrcpy -b 32M --always-on-top

No clue why a better phone, and it's snapdragon, could perform so poorly, or maybe it's because of Android 10? I seriously got no idea. I really enjoy using this, hope there will be a solution with this...

**Comment by rom1v** [comment]
OK. Several tests to figure out the problem.

Could you test over USB (instead of wifi)?

Enable framerate stats (Ctrl+i in the scrcpy window, logs are printed in the console).

Record the file: `scrcpy -r file.mkv`, then play it with VLC. Is it laggy too?
