### ISSUE TITLE
error: failed to get feature set: more than one device/emulator

### ISSUE THREAD

**Issue by kouronan** [Genymobile/scrcpy#1137]
how to deal with this problem

**Comment by rom1v** [comment]
What is the result of `adb devices`?

**Comment by pimisen** [comment]
I have the same error and it show only one device listed

**Comment by pimisen** [comment]
`INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
C:\Users\michi\Desktop\scrcpy-win64\sc...shed. 1.4 MB/s (26202 bytes in 0.018s)
adb.exe: error: more than one device and emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
27183
INFO: Initial texture: 1920x1080
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:599)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:167)

        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:6
8)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
        at com.genymobile.scrcpy.Server.main(Server.java:163)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:256)
WARN: Device disconnected
Press any key to continue...`

**Comment by rom1v** [comment]
The `adb reverse` warning is expected over tcpip.

Your real error is:
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream

**Comment by pimisen** [comment]
> 
> 
> The `adb reverse` warning is expected over tcpip.
> 
> Your real error is:
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream

Cool, thanks! It works with lower resultion! Great!
