### ISSUE TITLE
exception with vanilla install's run

### ISSUE THREAD

**Issue by abhinavm24** [Genymobile/scrcpy#1153]
2020-02-17 21:24:54.753 scrcpy[85810:706851] INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.12.1/share/scrcpy/scrcpy-server: 1 file pushed. 3.5 MB/s (26202 bytes in 0.007s)
2020-02-17 21:24:56.788 scrcpy[85810:706851] INFO: Initial texture: 1080x2240
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at java.io.FileReader.<init>(FileReader.java:58)
	at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
	at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
	at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
	at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
	at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
	at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
	at android.content.res.Resources.<init>(Resources.java:283)
	at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
	at android.content.res.Resources.getSystem(Resources.java:204)
	at android.app.LoadedApk.<init>(LoadedApk.java:235)
	at android.app.ContextImpl.createSystemContext(ContextImpl.java:2430)
	at android.app.ActivityThread.getSystemContext(ActivityThread.java:2427)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 22 more

**Comment by rom1v** [comment]
This is harmless (and "fixed" on `dev`): #994
