### ISSUE TITLE
Phone always freezes as a result of ./scrcpy .

### ISSUE THREAD

**Issue by StacktraceException** [Genymobile/scrcpy#1154]
adb -s 192.168.1.117:5555 shell screenrecord /sdcard/file.mp4
`ERROR: unable to start codec (err=-12)

WARNING: failed at 480x800, retrying at 720x1280

ERROR: unable to start codec (err=-12)
`

---------

 ./scrcpy -s 192.168.1.117:5555 --no-display --record file.mkv
```
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
C:\Users\Loombard\Downloads\scrcpy-win64-v1.12.1\scrcpy-server: 1 file pushed. 0.8 MB/s (26202 bytes in 0.033s)
adb.exe: error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
27183
INFO: Recording started to matroska file: file.mkv
INFO: Finishing recording...
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: start failedERROR: Recording failed to file.mkv

        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2018)
WARN: Device disconnected
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:71)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)Press any key to continue...

```

S3 Mini i8190 , Resurrection Remix ROM, Android 7.1.2. Windows 10.

**Comment by Destro-** [comment]
Same problem ROM Resurrection Remix 6.0.1...
