### ISSUE TITLE
set x11 server on mac and use ssh -X to ubutun device can't start scrcpy

### ISSUE THREAD

**Issue by chaooe** [Genymobile/scrcpy#1155]
Mac Os: 10.14.6 (18G3020)
My android device connect to Ubuntu. And i setup scrcpy on ubuntu. It's ok to use on ubuntu. 

When i use ssh -X user@IP to remote login Ubuntu on Mac OS. Then i type scrcpy to start, it can't start normally. Error as below:
`scrcpy -s 192.168.111.11:5555
/usr/local/share/scrcpy/scrcpy-server....shed. 2.4 MB/s (22587 bytes in 0.009s)
adb: error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
[server] ERROR: Exception on thread Thread[main,5,main]
java.io.IOException: Address already in use
	at android.net.LocalSocketImpl.bindLocal(Native Method)
	at android.net.LocalSocketImpl.bind(LocalSocketImpl.java:308)
	at android.net.LocalServerSocket.<init>(LocalServerSocket.java:48)
	at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:48)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:19)
	at com.genymobile.scrcpy.Server.main(Server.java:133)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  98
  Current serial number in output stream:  
`

**Comment by rom1v** [comment]
Use this for SSH tunnel: https://github.com/Genymobile/scrcpy/blob/master/README.md#ssh-tunnel

**Comment by chaooe** [comment]
Thanks. I will have a try.
