### ISSUE TITLE
Missing file when start

### ISSUE THREAD

**Issue by Samega7Cattac** [Genymobile/scrcpy#1192]
I'm getting an error of a missing file every time I run `scrcpy`.
```
$ scrcpy -b 4M
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 0.5 MB/s (26202 bytes in 0.050s)
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:487)
        at java.io.FileInputStream.<init>(FileInputStream.java:76)
        at java.io.FileInputStream.<init>(FileInputStream.java:103)
        at java.io.FileReader.<init>(FileReader.java:66)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java)
        at android.content.res.MiuiResources.<clinit>(MiuiResources.java)
        at android.content.res.Resources.getSystem(Resources.java)
        at android.app.LoadedApk.<init>(LoadedApk.java)
        at android.app.ContextImpl.createSystemContext(ContextImpl.java)
        at android.app.ActivityThread.getSystemContext(ActivityThread.java)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
        at com.genymobile.scrcpy.Server.main(Server.java:163)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at libcore.io.IoBridge.open(IoBridge.java:473)
        ... 20 more
INFO: Initial texture: 1080x1920
WARN: Device disconnected
```
Installed from [AUR](https://aur.archlinux.org/packages/scrcpy/)

**Comment by pfpoujol** [comment]
Same issue for me, trying to run scrcpy-win64 on Windows with a Xiaomi MI 9.

**Comment by rom1v** [comment]
Just ignore, this is harmless and "fixed" on dev. See #994.
