### ISSUE TITLE
scrcpy shutoff by it self after some second

### ISSUE THREAD

**Issue by youngmufeng** [Genymobile/scrcpy#1194]
Hello,I use scrcpy in win7 with android 5.it was worked

but when I use in win10,it always failed.

C:\Users\Administrator>D:\My_tools\scrcpy\scrcpy.exe
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
D:\My_tools\scrcpy\scrcpy-server: 1 file pushed. 3.3 MB/s (26202 bytes in 0.008s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:92)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
        at com.genymobile.scrcpy.Server.main(Server.java:163)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
INFO: Initial texture: 1080x2280
WARN: Device disconnected
Press any key to continue...

**Comment by rom1v** [comment]
scrcpy -m 1024

?

**Comment by youngmufeng** [comment]
OK I have try it ,it worked ,Thanks
