### ISSUE TITLE
When I paste with Ctrl + Shift + V, an error is reported.

### ISSUE THREAD

**Issue by MrReN** [Genymobile/scrcpy#1254]
INFO: Initial texture: 1080x1920
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: setPrimaryClip [class android.content.ClipData, class java.lang.String]
        at java.lang.Class.getMethod(Class.java:1981)
        at java.lang.Class.getMethod(Class.java:1637)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getSetPrimaryClipMethod(ClipboardManager.java:39)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.setText(ClipboardManager.java:79)
        at com.genymobile.scrcpy.Device.setClipboardText(Device.java:157)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:104)
        at com.genymobile.scrcpy.Controller.control(Controller.java:67)
        at com.genymobile.scrcpy.Server$1.run(Server.java:47)
        at java.lang.Thread.run(Thread.java:761)
[server] INFO: Device clipboard set

### Is there a solution？

**Comment by rom1v** [comment]
Which scrcpy version?

**Comment by MrReN** [comment]
scrcpy-win64-v1.12.1

**Comment by rom1v** [comment]
Please take this server: [`scrcpy-server`](https://tmp.rom1v.com/issue1254/1/scrcpy-server)
_SHA256: d5b2c3e0b34834c2fb902a47be399f6b3551cc77267b67ea6251810ed1e3bb31_

Replace it in your v1.12.1 release, run scrcpy, and press Ctrl+Shift+v once.

It should print thing in the console, paste the output there.

<details>
<summary>diff</summary>

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java b/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java
index 592bdf6..026c789 100644
--- a/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java
+++ b/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java
@@ -20,6 +20,9 @@ public class ClipboardManager {
 
     public ClipboardManager(IInterface manager) {
         this.manager = manager;
+        for (Method m : manager.getClass().getMethods()) {
+            Ln.d(m.toString());
+        }
     }
 
     private Method getGetPrimaryClipMethod() throws NoSuchMethodException {
```

</details>

**Comment by MrReN** [comment]
[server] DEBUG: public void android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener(android.content.IOnPrimaryClipChangedListener,java.lang.String) throws android.os.RemoteException
[server] DEBUG: public android.os.IBinder android.content.IClipboard$Stub$Proxy.asBinder()
[server] DEBUG: public void android.content.IClipboard$Stub$Proxy.clearCopyHistory() throws android.os.RemoteException
[server] DEBUG: public void android.content.IClipboard$Stub$Proxy.delete(android.content.CopyHistoryItem) throws android.os.RemoteException
[server] DEBUG: public boolean java.lang.Object.equals(java.lang.Object)
[server] DEBUG: public final java.lang.Class java.lang.Object.getClass()
[server] DEBUG: public java.util.List android.content.IClipboard$Stub$Proxy.getCopyHistory() throws android.os.RemoteException
[server] DEBUG: public java.lang.String android.content.IClipboard$Stub$Proxy.getInterfaceDescriptor()
[server] DEBUG: public android.content.ClipData android.content.IClipboard$Stub$Proxy.getPrimaryClip(java.lang.String) throws android.os.RemoteException
[server] DEBUG: public android.content.ClipDescription android.content.IClipboard$Stub$Proxy.getPrimaryClipDescription(java.lang.String) throws android.os.RemoteException
[server] DEBUG: public boolean android.content.IClipboard$Stub$Proxy.hasClipboardText(java.lang.String) throws android.os.RemoteException
[server] DEBUG: public boolean android.content.IClipboard$Stub$Proxy.hasPrimaryClip(java.lang.String) throws android.os.RemoteException
[server] DEBUG: public int java.lang.Object.hashCode()
[server] DEBUG: public void android.content.IClipboard$Stub$Proxy.insert(java.util.List) throws android.os.RemoteException
[server] DEBUG: public final native void java.lang.Object.notify()
[server] DEBUG: public final native void java.lang.Object.notifyAll()
[server] DEBUG: public void android.content.IClipboard$Stub$Proxy.registerListener(android.content.IClipboardListener) throws android.os.RemoteException
[server] DEBUG: public void android.content.IClipboard$Stub$Proxy.removePrimaryClipChangedListener(android.content.IOnPrimaryClipChangedListener) throws android.os.RemoteException
[server] DEBUG: public void android.content.IClipboard$Stub$Proxy.setPrimaryClip(android.content.ClipData,boolean,java.lang.String) throws android.os.RemoteException
[server] DEBUG: public java.lang.String java.lang.Object.toString()
[server] DEBUG: public final native void java.lang.Object.wait() throws java.lang.InterruptedException
[server] DEBUG: public final void java.lang.Object.wait(long) throws java.lang.InterruptedException
[server] DEBUG: public final native void java.lang.Object.wait(long,int) throws java.lang.InterruptedException
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: setPrimaryClip [class android.content.ClipData, class java.lang.String]
        at java.lang.Class.getMethod(Class.java:1981)
        at java.lang.Class.getMethod(Class.java:1637)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getSetPrimaryClipMethod(ClipboardManager.java:42)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.setText(ClipboardManager.java:82)
        at com.genymobile.scrcpy.Device.setClipboardText(Device.java:157)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:104)
        at com.genymobile.scrcpy.Controller.control(Controller.java:67)
        at com.genymobile.scrcpy.Server$1.run(Server.java:47)
        at java.lang.Thread.run(Thread.java:761)
[server] INFO: Device clipboard set

**Comment by rom1v** [comment]
>     public void android.content.IClipboard$Stub$Proxy.setPrimaryClip(android.content.ClipData,boolean,java.lang.String) throws android.os.RemoteException

The constructor modified the method signature to add a boolean.

On AOSP, there has never been such a parameter:
 - https://github.com/aosp-mirror/platform_frameworks_base/commit/efcc1a23a1f731390ef8506b3536b9562d18ed78#diff-549179a861430b7a2a6cc41837607799R29
 - https://github.com/aosp-mirror/platform_frameworks_base/commit/33f56060d57a0aca3693caedbc37b5dc94a11ef3#diff-549179a861430b7a2a6cc41837607799R29

Which device is it? Which ROM?

**Comment by MrReN** [comment]
Smartisan OS

**Comment by rom1v** [comment]
So, I don't know what this boolean means. Let's try with both possibles values:
 - `true`: [`scrcpy-server`](https://tmp.rom1v.com/issue1254/2/true/scrcpy-server)
  _SHA256: 047bab19d5e978488f0f8f96502e90b3c4f30a30fa0f60a8501fd5198d963cbe_
 - `false`: [`scrcpy-server`](https://tmp.rom1v.com/issue1254/2/false/scrcpy-server)
  _SHA256: 281bc30b8bbc1570031b252f16e39f031dfb92ae68fad26648c471239d893afb_

Please tell me whether each one works on your device.

<details>
<summary>diff</summary>

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java b/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java
index 592bdf6..1bd0668 100644
--- a/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java
+++ b/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java
@@ -36,7 +36,7 @@ public class ClipboardManager {
     private Method getSetPrimaryClipMethod() throws NoSuchMethodException {
         if (setPrimaryClipMethod == null) {
             if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
-                setPrimaryClipMethod = manager.getClass().getMethod("setPrimaryClip", ClipData.class, String.class);
+                setPrimaryClipMethod = manager.getClass().getMethod("setPrimaryClip", ClipData.class, boolean.class, String.class);
             } else {
                 setPrimaryClipMethod = manager.getClass().getMethod("setPrimaryClip", ClipData.class, String.class, int.class);
             }
@@ -54,7 +54,7 @@ public class ClipboardManager {
     private static void setPrimaryClip(Method method, IInterface manager, ClipData clipData)
             throws InvocationTargetException, IllegalAccessException {
         if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
-            method.invoke(manager, clipData, PACKAGE_NAME);
+            method.invoke(manager, clipData, true, PACKAGE_NAME);
         } else {
             method.invoke(manager, clipData, PACKAGE_NAME, USER_ID);
         }
```
</details>

**Comment by MrReN** [comment]
true: scrcpy-server is work

**Comment by MrReN** [comment]
Both of them are OK。
