### ISSUE TITLE
White screen then crash.

### ISSUE THREAD

**Issue by xreic** [Genymobile/scrcpy#1276]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.12.1
 - installation method: [Windows release
 - device model: XiaoMi Mi 9 Lite
 - Android version: MIUI Global 11.0.1 / Android 10

**Describe the bug**
Open cmd prompt (both as non-admin and admin) and direct to where I extracted the contents to
Run scrcpy
It executes and a white window pops up, then it closes a second later or so

```sh
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
F:\scrcpy-win64-v1.12.1\scrcpy-server: 1 file pushed. 7.1 MB/s (26202 bytes in 0.004s)
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.Resources.<init>(Resources.java:283)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
        at android.content.res.Resources.getSystem(Resources.java:204)
        at android.app.LoadedApk.<init>(LoadedApk.java:235)
        at android.app.ContextImpl.createSystemContext(ContextImpl.java:2430)
        at android.app.ActivityThread.getSystemContext(ActivityThread.java:2427)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
        at com.genymobile.scrcpy.Server.main(Server.java:163)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        ... 22 more
INFO: Initial texture: 1080x2336
```

**Comment by rom1v** [comment]
The exception is not a bug (see #994).

> It executes and a white window pops up, then it closes a second later or so

Try with a lower definition:

```
scrcpy -m1024
```

If it still does not work, please provide the output of `adb logcat`.

**Comment by xreic** [comment]
adb logcat generates a 7 MB file. Do you have a preferred host for me to upload it to?

**Comment by rom1v** [comment]
Could you do some more tests to find the cause.

1. Run `adb logcat` in a terminal, and start `scrcpy` in another. When `scrcpy` stops, does `adb logcat` also terminate?
2. Try to record without display (`scrcpy --record file.mkv --no-display -m 800`). Is the recorded file ok?
3. Try to record with `adb shell screenrecord /sdcard/file.mp4` (then `adb pull /sdcard/file.mp4`). Is the recorded file ok?

**Comment by xreic** [comment]
1. `adb logcat` keep going even when `scrcpy` stops.
2/3. Recording is good.

**Comment by rom1v** [comment]
Oh, might be a driver issue on the computer then. Could you test on another computer/system?

> a white window pops up

Could you post a screenshot?

**Comment by xreic** [comment]
![Untitled](https://user-images.githubusercontent.com/32492656/78844810-b920c800-79bb-11ea-8adf-c0d5a8271cad.png)
This is the window.
I'll test on another machine now.

**Comment by rom1v** [comment]
> while still showing that error

This is not an error (this is expected on some devices, the message will not be shown in future versions of scrcpy): #994

**Comment by xreic** [comment]
Yea I read that recently, but I'm still trying to figure out of how fix the "crashing" so I can use this on my main machine.

**Comment by rom1v** [comment]
Out of curiousity, could you test v1.9? (it uses a different SDL version)

**Comment by xreic** [comment]
No error, but it still opens then closes.

**Comment by xreic** [comment]
I didn't know why I didn't try it before, but the 32-bit version of v1.12 works (I was using the 64-bit version before). It still shows that false error, but it works. If you want me to run some more tests, then just ask. 

Thanks for all your time and effort.

**Comment by rom1v** [comment]
OK good to know that this kind of problem can occur only on 32 or 64 bits :+1:
