### ISSUE TITLE
cmd works but doesnt appear anything on the screen

### ISSUE THREAD

**Issue by Flight-X** [Genymobile/scrcpy#1290]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [linux mint.]
 - scrcpy version: [1.12]
 - installation method: [Snap]
 - device model:redmi note 8pro
 - Android version: [9]

**Describe the bug**
 `the adb is working device is authorized ...
This is scrcpy info
summary: Display and control your Android device
publisher: sisco311
store-url: https://snapcraft.io/scrcpy
contact: https://github.com/sisco311/scrcpy-snap/issues
license: Apache-2.0
description: |
This application provides display and control of Android devices connected on USB (or over
TCP/IP). It does not require any root access. It works on GNU/Linux, Windows and MacOS.

This is an unofficial snap. The code of scrcpy can be found at:
https://github.com/Genymobile/scrcpy
commands:

    scrcpy.adb
    scrcpy
    snap-id: M7yvgnqOvyQj64bolfpawIAEwHv7dQ5G
    tracking: latest/stable
    refresh-date: today at 20:46 IST
    channels:
    latest/stable: v1.12 2020-03-26 (211) 85MB -
    latest/candidate: ^
    latest/beta: v1.12.1-10-g7bb9163 2020-03-27 (214) 85MB -
    latest/edge: v1.12-1-g71df317 2019-12-10 (202) 81MB -
    installed: v1.12 (211) 85MB -
    **_When i run the cmd scrcpy i got this and nothing appers on the screen_**
    2020/04/14 22:55:21.816933 cmd_run.go:893: WARNING: cannot start document portal: write unix @->@/tmp/dbus-JrtrgGH41M: write: broken pipe
    INFO: scrcpy 1.12 https://github.com/Genymobile/scrcpy
    /usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 5.8 MB/s (26196 bytes in 0.004s)
    No protocol specified
    Segmentation fault
    root@Flight-X:/home/stelph# java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:231)
    at java.io.FileInputStream.(FileInputStream.java:165)
    at java.io.FileInputStream.(FileInputStream.java:112)
    at java.io.FileReader.(FileReader.java:58)
    at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
    at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
    at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
    at miui.content.res.ThemeCompatibility.(ThemeCompatibility.java:31)
    at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
    at android.content.res.MiuiResourcesImpl.(MiuiResourcesImpl.java:41)
    at android.content.res.Resources.(Resources.java:267)
    at android.content.res.MiuiResources.(MiuiResources.java:49)
    at android.content.res.Resources.getSystem(Resources.java:190)
    at android.app.LoadedApk.(LoadedApk.java:211)
    at android.app.ContextImpl.createSystemContext(ContextImpl.java:2332)
    at android.app.ActivityThread.getSystemContext(ActivityThread.java:2199)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
    at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
    at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
    at com.genymobile.scrcpy.Server.main(Server.java:163)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at `com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)`

**Comment by Flight-X** [comment]
`Now It Giving me this 
2020/04/15 00:57:20.557499 cmd_run.go:893: WARNING: cannot start document portal: write unix @->@/tmp/dbus-JrtrgGH41M: write: broken pipe
INFO: scrcpy 1.12 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 5.7 MB/s (26196 bytes in 0.004s)
bind: Address already in use
ERROR: Could not listen on port 27183
`
Wht should i do

**Comment by rom1v** [comment]
>     WARNING: cannot start document portal: write unix

Looks like a snap problem.

Please try the manual installation :/

**Comment by Flight-X** [comment]
sir, When i tried to execute cmd 
ninja -Cx install i Got an error
`ninja: Entering directory `x'
[1/2] Generating scrcpy-server with a custom command.
(not invoking gradle, since we are root)
[1/2] Installing files.
Installing app/scrcpy to /usr/local/bin/scrcpy
Stripping target 'app/scrcpy'
Installing server/scrcpy-server to /usr/local/share/scrcpy/scrcpy-server
Traceback (most recent call last):
  File "/usr/bin/meson", line 26, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 318, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 274, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 393, in run
    do_install(datafilename)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 212, in do_install
    install_targets(d)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 332, in install_targets
    raise RuntimeError('File {!r} could not be found'.format(fname))
RuntimeError: File 'server/scrcpy-server' could not be found
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_meson_meson.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/meson", line 26, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 318, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 274, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 393, in run
    do_install(datafilename)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 212, in do_install
    install_targets(d)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 332, in install_targets
    raise RuntimeError('File {!r} could not be found'.format(fname))
RuntimeError: File 'server/scrcpy-server' could not be found
FAILED: meson-install 
/usr/bin/python3 /usr/bin/meson --internal install /home/stelph/Downloads/scrcpyFiles/scrcpy/x/meson-private/install.dat
ninja: build stopped: subcommand failed.
`

**Comment by Flight-X** [comment]
Sir,
**i got this **
`ollecting guiscrcpy
  Downloading https://files.pythonhosted.org/packages/e3/1b/1a323892550b3c1914fa6bd4f16419b6c17e8c325243dfe445e42a998285/guiscrcpy-3.5-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 252kB/s 
Collecting gitpython (from guiscrcpy)
  Downloading https://files.pythonhosted.org/packages/19/1a/0df85d2bddbca33665d2148173d3281b290ac054b5f50163ea735740ac7b/GitPython-3.1.1-py3-none-any.whl (450kB)
    100% |████████████████████████████████| 460kB 192kB/s 
Collecting fonttools (from guiscrcpy)
  Downloading https://files.pythonhosted.org/packages/c9/81/1b00432d8f5536c09dca00f6f5306be26c477d1c0390a0fb993f8ebf1c64/fonttools-4.7.0-py3-none-any.whl (749kB)
    100% |████████████████████████████████| 757kB 187kB/s 
Collecting PyQt5==5.14.1 (from guiscrcpy)
  Downloading https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz (3.2MB)
    100% |████████████████████████████████| 3.2MB 225kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-756abdaf/PyQt5/
`

**Comment by rom1v** [comment]
> (not invoking gradle, since we are root)

You must execute `ninja -Cx` as non-root, and `sudo ninja -Cx install` as root: 4c49b27e9f6be02b8e63b508b60535426bd0291a

Remove your `x` directory and retry.

**Comment by Flight-X** [comment]
@rom1v 
it says permission error 
all the previos step  i did it all as root 
ninja -Cx
ninja: Entering directory `x'
ninja: error: opening build log: Permission denied

**Comment by rom1v** [comment]
That's why I said you must remove your `x` directory:

```bash
sudo rm -rf x
meson x …
ninja -Cx
sudo ninja -Cx install
```

**Comment by Flight-X** [comment]
@rom1v 
sir tried all over again 
in the step of ninja -Cx
i got this 
`ninja: Entering directory `x'
[26/26] Generating scrcpy-server with a custom command.
FAILED: server/scrcpy-server 
/home/stelph/project/scrcpy/server/./scripts/build-wrapper.sh /home/stelph/project/scrcpy/server server/scrcpy-server release
Downloading https://services.gradle.org/distributions/gradle-5.5.1-all.zip
..................................................................................................................................

Welcome to Gradle 5.5.1!

Here are the highlights of this release:
 - Kickstart Gradle plugin development with gradle init
 - Distribute organization-wide Gradle properties in custom Gradle distributions
 - Transform dependency artifacts on resolution

For more details see https://docs.gradle.org/5.5.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':server'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/home/stelph/project/scrcpy/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 32s
ninja: build stopped: subcommand failed.
`

**Comment by srevinsaju** [comment]
@Flight-X you may try the second method of installing scrcpy from source, aka using the prebuilt server.
https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server
