### ISSUE TITLE
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed:

### ISSUE THREAD

**Issue by ziyouxiaozi** [Genymobile/scrcpy#1336]
```
INFO: Device: Xiaomi MI 9 (Android 10)
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.Resources.<init>(Resources.java:283)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
        at android.content.res.Resources.getSystem(Resources.java:204)
        at android.app.LoadedApk.<init>(LoadedApk.java:235)
        at android.app.ContextImpl.createSystemContext(ContextImpl.java:2430)
        at android.app.ActivityThread.getSystemContext(ActivityThread.java:2427)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:50)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:35)
        at com.genymobile.scrcpy.Server.main(Server.java:177)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        ... 22 more
INFO: Renderer: direct3d
WARN: Trilinear filtering disabled (not an OpenGL renderer)
INFO: Initial texture: 1080x2336
```

**Comment by rom1v** [comment]
The "error" is harmless, but is expected to not be shown in v1.13 (#994). :confused:

I don't understand why it is printed.

The failing statement is here:

https://github.com/Genymobile/scrcpy/blob/4e9e712312c9726824d28bed4fc85721e3a2b203/server/src/main/java/com/genymobile/scrcpy/Workarounds.java#L66

The whole thing is in a try-catch-Throwable block, which logs only in debug mode. (and you don't have the message `Could not fill app info:`, so this specific log is not printed in your case).

So I guess some method in the callstack catch the exception and call `printStackTrace()` before rethrowing… :disappointed:

**Comment by rom1v** [comment]
I'm reopening #994 and closing this one.

**Comment by ziyouxiaozi** [comment]
Clicking with the mouse does not respond.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#control-issues

**Comment by ziyouxiaozi** [comment]
thanks

**Comment by rom1v** [comment]
Could you please take scrcpy v1.13 and replace this file:

[`scrcpy-server`](https://tmp.rom1v.com/scrcpy/issue994/1/scrcpy-server)
_SHA256: b64e6672eeb2b7c00c6f83673783bd8839ba65ea2ac7edcdeeca44676047328b_

and confirm that it works without the error message.

Thank you.
