### ISSUE TITLE
Running scrcpy issues

### ISSUE THREAD

**Issue by JehudaRajasa** [Genymobile/scrcpy#1356]
OS: Debian Buster on Raspberry Pi

Phone: Xiaomi Redmi 5 Plus

Issue:

```
pi@raspberrypi:~ $ scrcpy
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
/usr/local/share/scrcpy/scrcpy-server:...shed. 0.7 MB/s (27694 bytes in 0.040s)
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
dbus[9301]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted
pi@raspberrypi:~ $ [server] INFO: Device: Xiaomi Redmi 5 Plus (Android 7.1.2)
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileInputStream.<init>(FileInputStream.java:99)
	at java.io.FileReader.<init>(FileReader.java:58)
	at miui.content.res.ThemeCompatibilityLoader.getVersion(SourceFile:108)
	at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(SourceFile:126)
	at miui.content.res.ThemeCompatibilityLoader.loadConfig(SourceFile:59)
	at miui.content.res.ThemeCompatibility.<clinit>(SourceFile:31)
	at miui.content.res.ThemeCompatibility.isThemeEnabled(SourceFile:111)
	at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:39)
	at android.content.res.Resources.<init>(Resources.java:257)
	at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
	at android.content.res.Resources.getSystem(Resources.java:182)
	at android.app.LoadedApk.<init>(LoadedApk.java:205)
	at android.app.ContextImpl.createSystemContext(ContextImpl.java:2010)
	at android.app.ActivityThread.getSystemContext(ActivityThread.java:2131)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:50)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:35)
	at com.genymobile.scrcpy.Server.main(Server.java:177)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

Thank you in advance

**Comment by rom1v** [comment]
How did you install it?

**Comment by rom1v** [comment]
https://forum.odroid.com/viewtopic.php?t=30652 ?

**Comment by JehudaRajasa** [comment]
> https://forum.odroid.com/viewtopic.php?t=30652 ?

Thanks for the tip. The code worked for me. I was able to run scrcpy but very sluggishly. Is there a way I can fix the lag?

**Comment by rom1v** [comment]
On raspi 3, there will not be hardware acceleration. On raspi 4 I think it works better. Which raspi do you use?

Ref #273.

**Comment by JehudaRajasa** [comment]
Oh, I see. I use raspi

**Comment by JehudaRajasa** [comment]
Oh, I see. I use raspi 3
