### ISSUE TITLE
java.lang.AssertionError on Lenovo VR-1541F

### ISSUE THREAD

**Issue by MarcoWilli** [Genymobile/scrcpy#1372]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 64 bit
 - scrcpy version: 1.13
 - installation method: Windows release
 - device model: Lenovo Mirage Solo
 - Android version: 8

**Describe the bug**
Getting the mentioned error and then "Warn: Device disconnected" on USB and WiFi connection.

`java.lang.AssertionError: java.lang.NoSuchMethodException: createDisplay [class java.lang.String, boolean]
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
        at com.genymobile.scrcpy.ScreenEncoder.createDisplay(ScreenEncoder.java:162)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:58)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:35)
        at com.genymobile.scrcpy.Server.main(Server.java:177)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)
Caused by: java.lang.NoSuchMethodException: createDisplay [class java.lang.String, boolean]
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getMethod(Class.java:1690)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:81)
        ... 6 more
INFO: Renderer: direct3d
WARN: Trilinear filtering disabled (not an OpenGL renderer)
INFO: Initial texture: 2560x1440
WARN: Device disconnected`

**Comment by rom1v** [comment]
The vendor modified the ROM so the method is not available :(

Could you execute this modified server (on v1.13) that will print all the available methods, please? (and copy-paste the output here)

[`scrcpy-server`](https://tmp.rom1v.com/scrcpy/issue1372/1/scrcpy-server)
_SHA256: 358c47dfa58bbd85fa6da76718f006904d527a3b21fff2351128bd277bf311d0_

<details>
<summary>diff</summary>

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java b/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java
index 8fbb860..a446c12 100644
--- a/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java
+++ b/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java
@@ -77,6 +77,9 @@ public final class SurfaceControl {
     }
 
     public static IBinder createDisplay(String name, boolean secure) {
+        for (Method method : CLASS.getMethods()) {
+            Ln.i("### " + method);
+        }
         try {
             return (IBinder) CLASS.getMethod("createDisplay", String.class, boolean.class).invoke(null, name, secure);
         } catch (Exception e) {
```
</summary>

**Comment by MarcoWilli** [comment]
Sure I can =)

`[server] INFO: Device: Lenovo VR-1541F (Android 8.0.0)
[server] INFO: ### public static boolean android.view.SurfaceControl.clearAnimationFrameStats()
[server] INFO: ### public boolean android.view.SurfaceControl.clearContentFrameStats()
[server] INFO: ### public static void android.view.SurfaceControl.closeTransaction()
[server] INFO: ### public static void android.view.SurfaceControl.closeTransactionSync()
[server] INFO: ### public static android.os.IBinder android.view.SurfaceControl.createDisplay(java.lang.String,java.lang.String,boolean)
[server] INFO: ### public void android.view.SurfaceControl.deferTransactionUntil(android.os.IBinder,long)
[server] INFO: ### public void android.view.SurfaceControl.deferTransactionUntil(android.view.Surface,long)
[server] INFO: ### public void android.view.SurfaceControl.destroy()
[server] INFO: ### public static void android.view.SurfaceControl.destroyDisplay(android.os.IBinder)
[server] INFO: ### public void android.view.SurfaceControl.detachChildren()
[server] INFO: ### public void android.view.SurfaceControl.disconnect()
[server] INFO: ### public boolean java.lang.Object.equals(java.lang.Object)
[server] INFO: ### public static int android.view.SurfaceControl.getActiveColorMode(android.os.IBinder)
[server] INFO: ### public static int android.view.SurfaceControl.getActiveConfig(android.os.IBinder)
[server] INFO: ### public static boolean android.view.SurfaceControl.getAnimationFrameStats(android.view.WindowAnimationFrameStats)
[server] INFO: ### public static android.os.IBinder android.view.SurfaceControl.getBuiltInDisplay(int)
[server] INFO: ### public final java.lang.Class java.lang.Object.getClass()
[server] INFO: ### public boolean android.view.SurfaceControl.getContentFrameStats(android.view.WindowContentFrameStats)
[server] INFO: ### public static int[] android.view.SurfaceControl.getDisplayColorModes(android.os.IBinder)
[server] INFO: ### public static android.view.SurfaceControl$PhysicalDisplayInfo[] android.view.SurfaceControl.getDisplayConfigs(android.os.IBinder)
[server] INFO: ### public android.os.IBinder android.view.SurfaceControl.getHandle()
[server] INFO: ### public static android.view.Display$HdrCapabilities android.view.SurfaceControl.getHdrCapabilities(android.os.IBinder)
[server] INFO: ### public int java.lang.Object.hashCode()
[server] INFO: ### public void android.view.SurfaceControl.hide()
[server] INFO: ### public final native void java.lang.Object.notify()
[server] INFO: ### public final native void java.lang.Object.notifyAll()
[server] INFO: ### public static void android.view.SurfaceControl.openTransaction()
[server] INFO: ### public void android.view.SurfaceControl.release()
[server] INFO: ### public void android.view.SurfaceControl.reparentChildren(android.os.IBinder)
[server] INFO: ### public static android.graphics.Bitmap android.view.SurfaceControl.screenshot(int,int)
[server] INFO: ### public static void android.view.SurfaceControl.screenshot(android.os.IBinder,android.view.Surface)
[server] INFO: ### public static void android.view.SurfaceControl.screenshot(android.os.IBinder,android.view.Surface,int,int)
[server] INFO: ### public static android.graphics.Bitmap android.view.SurfaceControl.screenshot(android.graphics.Rect,int,int,int,int,boolean,int)
[server] INFO: ### public static void android.view.SurfaceControl.screenshot(android.os.IBinder,android.view.Surface,int,int,int,int,boolean)
[server] INFO: ### public static android.graphics.GraphicBuffer android.view.SurfaceControl.screenshotToBuffer(android.graphics.Rect,int,int,int,int,boolean,int)
[server] INFO: ### public static android.graphics.Bitmap android.view.SurfaceControl.screenshotVr(android.graphics.Rect,int,int,int,int,boolean,int)
[server] INFO: ### public static boolean android.view.SurfaceControl.setActiveColorMode(android.os.IBinder,int)
[server] INFO: ### public static boolean android.view.SurfaceControl.setActiveConfig(android.os.IBinder,int)
[server] INFO: ### public void android.view.SurfaceControl.setAlpha(float)
[server] INFO: ### public static void android.view.SurfaceControl.setAnimationTransaction()
[server] INFO: ### public static void android.view.SurfaceControl.setDisplayLayerStack(android.os.IBinder,int)
[server] INFO: ### public static void android.view.SurfaceControl.setDisplayPowerMode(android.os.IBinder,int)
[server] INFO: ### public static void android.view.SurfaceControl.setDisplayProjection(android.os.IBinder,int,android.graphics.Rect,android.graphics.Rect)
[server] INFO: ### public static void android.view.SurfaceControl.setDisplaySize(android.os.IBinder,int,int)
[server] INFO: ### public static void android.view.SurfaceControl.setDisplaySurface(android.os.IBinder,android.view.Surface)
[server] INFO: ### public void android.view.SurfaceControl.setFinalCrop(android.graphics.Rect)
[server] INFO: ### public void android.view.SurfaceControl.setGeometryAppliesWithResize()
[server] INFO: ### public void android.view.SurfaceControl.setLayer(int)
[server] INFO: ### public void android.view.SurfaceControl.setLayerStack(int)
[server] INFO: ### public void android.view.SurfaceControl.setMatrix(float,float,float,float)
[server] INFO: ### public void android.view.SurfaceControl.setOpaque(boolean)
[server] INFO: ### public void android.view.SurfaceControl.setOverrideScalingMode(int)
[server] INFO: ### public void android.view.SurfaceControl.setPosition(float,float)
[server] INFO: ### public void android.view.SurfaceControl.setRelativeLayer(android.os.IBinder,int)
[server] INFO: ### public void android.view.SurfaceControl.setSecure(boolean)
[server] INFO: ### public void android.view.SurfaceControl.setSize(int,int)
[server] INFO: ### public void android.view.SurfaceControl.setTransparentRegionHint(android.graphics.Region)
[server] INFO: ### public void android.view.SurfaceControl.setWindowCrop(android.graphics.Rect)
[server] INFO: ### public void android.view.SurfaceControl.show()
[server] INFO: ### public java.lang.String android.view.SurfaceControl.toString()
[server] INFO: ### public final native void java.lang.Object.wait() throws java.lang.InterruptedException
[server] INFO: ### public final void java.lang.Object.wait(long) throws java.lang.InterruptedException
[server] INFO: ### public final native void java.lang.Object.wait(long,int) throws java.lang.InterruptedException
[server] DEBUG: Controller stopped
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: createDisplay [class java.lang.String, boolean]
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:86)
        at com.genymobile.scrcpy.ScreenEncoder.createDisplay(ScreenEncoder.java:162)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:58)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:35)
        at com.genymobile.scrcpy.Server.main(Server.java:177)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)
Caused by: java.lang.NoSuchMethodException: createDisplay [class java.lang.String, boolean]
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getMethod(Class.java:1690)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:84)
        ... 6 more
INFO: Renderer: direct3d
WARN: Trilinear filtering disabled (not an OpenGL renderer)
INFO: Initial texture: 2560x1440
WARN: Device disconnected`

**Comment by rom1v** [comment]
They added an additonal `String` parameter:
```
android.view.SurfaceControl.createDisplay(java.lang.String,java.lang.String,boolean)
```

instead of

```
android.view.SurfaceControl.createDisplay(java.lang.String,boolean)
```

You could try to pass `name` twice:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java b/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java
index 8fbb860..ab7ed41 100644
--- a/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java
+++ b/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java
@@ -78,7 +78,7 @@ public final class SurfaceControl {
 
     public static IBinder createDisplay(String name, boolean secure) {
         try {
-            return (IBinder) CLASS.getMethod("createDisplay", String.class, boolean.class).invoke(null, name, secure);
+            return (IBinder) CLASS.getMethod("createDisplay", String.class, String.class, boolean.class).invoke(null, name, name, secure);
         } catch (Exception e) {
             throw new AssertionError(e);
         }
```

**Comment by MarcoWilli** [comment]
How to do this?

**Comment by MarcoWilli** [comment]
I´m sorry, but this exceeds my skills.
I installed Android SDK, scoop (used it year ago) to git clone and then installed msi w64 installer of meson/ninja.
But I can not build the server as there are more errors which I can not handle:

`PS C:\Users\Marco\Desktop\scrcpy> meson x --buildtype release --strip -Db_lto=true
The Meson build system
Version: 0.54.1
Source dir: C:\Users\Marco\Desktop\scrcpy
Build dir: C:\Users\Marco\Desktop\scrcpy\x
Build type: native build
Project name: scrcpy
Project version: 1.13

meson.build:1:0: ERROR: Unknown compiler(s): ['icl', 'cl', 'cc', 'gcc', 'clang', 'clang-cl', 'pgcc']
The follow exceptions were encountered:
Running "icl " gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
Running "cl /?" gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
Running "cc --version" gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
Running "gcc --version" gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
Running "clang --version" gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
Running "clang-cl /?" gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
Running "pgcc --version" gave "[WinError 2] Das System kann die angegebene Datei nicht finden"

A full log can be found at C:\Users\Marco\Desktop\scrcpy\x\meson-logs\meson-log.txt
PS C:\Users\Marco\Desktop\scrcpy> cd .\server\
PS C:\Users\Marco\Desktop\scrcpy\server> meson setup builddir
The Meson build system
Version: 0.54.1
Source dir: C:\Users\Marco\Desktop\scrcpy\server
Build dir: C:\Users\Marco\Desktop\scrcpy\server\builddir
Build type: native build

ERROR: First statement must be a call to project

A full log can be found at C:\Users\Marco\Desktop\scrcpy\server\builddir\meson-logs\meson-log.txt
PS C:\Users\Marco\Desktop\scrcpy\server> cd .\src\
PS C:\Users\Marco\Desktop\scrcpy\server\src> meson setup builddir

ERROR: Neither directory contains a build file meson.build.
PS C:\Users\Marco\Desktop\scrcpy\server\src> cd ..
PS C:\Users\Marco\Desktop\scrcpy\server> meson x --buildtype release --strip -Db_lto=true
The Meson build system
Version: 0.54.1
Source dir: C:\Users\Marco\Desktop\scrcpy\server
Build dir: C:\Users\Marco\Desktop\scrcpy\server\x
Build type: native build

ERROR: First statement must be a call to project

A full log can be found at C:\Users\Marco\Desktop\scrcpy\server\x\meson-logs\meson-log.txt
PS C:\Users\Marco\Desktop\scrcpy\server> run x
run : Die Benennung "run" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei
oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob
der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ run x
+ ~~~
    + CategoryInfo          : ObjectNotFound: (run:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Marco\Desktop\scrcpy\server>`

**Comment by TomAvecLeVdsl** [comment]
Hi, any news on this ?

**Comment by TomAvecLeVdsl** [comment]
Hi, some news about this, i managed to compile the server with the modified line of code in it ... only problem ... it doesen't display anything :( any ideas ?
