### ISSUE TITLE
Low FPS and High Latency provided by device | Connected by USB-C

### ISSUE THREAD

**Issue by Antoxxx** [Genymobile/scrcpy#1390]
- [√] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [√] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 x64
 - scrcpy version: 1.13
 - installation method: Windows release
 - device model: Mi 8
 - Android version: Android 10 (MIUI 12)

**Describe the bug**
The FPS is about 10fps  when I use scrcpy with no program/gaming running background. The latency is about 0.5ms. 

I've tried with scrcpy -m800 and fps didn't change.
I use the USB-C for connection.

Console output (scrcpy -m800):
```java
[server] INFO: Device: Xiaomi MI 8 (Android 10)
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(Unknown Source:11)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(Unknown Source:2)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(Unknown Source:12)
        at miui.content.res.ThemeCompatibility.<clinit>(Unknown Source:40)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(Unknown Source:0)
        at android.content.res.MiuiResourcesImpl.<clinit>(Unknown Source:0)
        at android.content.res.Resources.<init>(Unknown Source:20)
        at android.content.res.MiuiResources.<init>(Unknown Source:0)
        at android.content.res.Resources.getSystem(Unknown Source:9)
        at android.app.LoadedApk.<init>(Unknown Source:88)
        at android.app.ContextImpl.createSystemContext(Unknown Source:2)
        at android.app.ActivityThread.getSystemContext(Unknown Source:5)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:50)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:35)
        at com.genymobile.scrcpy.Server.main(Server.java:177)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(Unknown Source:24)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        ... 22 more
INFO: Renderer: direct3d
WARN: Trilinear filtering disabled (not an OpenGL renderer)
INFO: Initial texture: 384x800
INFO: FPS counter started
INFO: 12 fps
INFO: 10 fps
INFO: 9 fps (+3 frames skipped)
INFO: 12 fps
INFO: 13 fps
INFO: 11 fps
INFO: 13 fps
INFO: 14 fps
INFO: 13 fps
INFO: 12 fps
INFO: 12 fps
INFO: 12 fps
INFO: 13 fps
INFO: 12 fps (+1 frames skipped)
INFO: 12 fps
INFO: 12 fps
INFO: 11 fps
INFO: 13 fps
INFO: 12 fps
INFO: 12 fps
INFO: 13 fps
INFO: 11 fps (+1 frames skipped)
INFO: 11 fps
INFO: 14 fps
INFO: 13 fps
INFO: 13 fps
INFO: 12 fps
INFO: 12 fps
INFO: 13 fps
INFO: 12 fps
INFO: 12 fps
INFO: 13 fps
INFO: 13 fps
INFO: 12 fps
INFO: 12 fps
INFO: 11 fps
INFO: 11 fps
INFO: 10 fps
INFO: 11 fps
INFO: 11 fps
INFO: 11 fps
INFO: 10 fps
INFO: 10 fps
INFO: 11 fps
INFO: 11 fps
INFO: 10 fps
INFO: 10 fps
INFO: 10 fps
INFO: 10 fps
INFO: 10 fps
INFO: 11 fps
INFO: 11 fps
INFO: 13 fps
```

**Comment by rom1v** [comment]
> The FPS is about 10fps when I use scrcpy with no program/gaming running background.

If you move things on your screen, does the framerate increase?

(a new frame is generated only if the device surface has been modified, for example, a static screen produces 0 fps)

> 0.5ms

I guess you mean 500ms. How did you measure that?

**Comment by Antoxxx** [comment]
> I guess you mean 500ms. How did you measure that?

Oh yes It's 500ms

> If you move things on your screen, does the framerate increase?

That's the data when I move the screen. It actually got worse, decreased from about 15fps to 10fps.

**Comment by rom1v** [comment]
This framerate is what your device hardware is encoding. Does it lag on the device itself? What if you play a 25 fps video on your device?

I guess your device encoder is not able to encode the screen surface faster :/

Is it better with `scrcpy -m 200`?

**Comment by Antoxxx** [comment]
> Is it better with scrcpy -m 200?

Same with about 12fps in average.

> Does it lag on the device itself? What if you play a 25 fps video on your device?

Very smooth, but still with 10fps on PC screen

**Comment by Antoxxx** [comment]
Just now I tried Ctrl+O and the fps suddently changed to 45fps in average. 
It turned back to 10fps after I reboot the device.
