### ISSUE TITLE
Copying text to computer, solved

### ISSUE THREAD

**Issue by hcet14** [Genymobile/scrcpy#1411]
Thank you very much for this wonderful tool.  I just want to inform you. I found out why copying from device to computer doesn't work on my Redmi Note 4.

When I press CTRL+C in scrcpy with Redmi Note 4 connected I get this message in the Windows console:[server] ERROR: Could not invoke methodjava.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)        at com.genymobile.scrcpy.wrappers.ClipboardManager.getPrimaryClip(ClipboardManager.java:49)        at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:66)        at com.genymobile.scrcpy.Device.getClipboardText(Device.java:153)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:109)        at com.genymobile.scrcpy.Controller.control(Controller.java:66)
        at com.genymobile.scrcpy.Server$1.run(Server.java:48)        at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.SecurityException: Calling uid 0 does not own package com.android.shell
        at android.os.Parcel.readException(Parcel.java:2013)        at android.os.Parcel.readException(Parcel.java:1959)
        at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:187)        ... 8 more

So it's the missing package com.android.shell on my device!

When I press CTRL+C in scrcpy with Oneplus 7 Pro connected I get this message in the Windows console:INFO: Device clipboard copied

So copying from Oneplus 7 Pro to computer works.

**Comment by SunicYosen** [comment]
Maybe I have the same error with you on Redmi Note 4. How do you solve this problem? 

Thanks a lot!
