### ISSUE TITLE
Ctrl+shift+v cause Buffer full

### ISSUE THREAD

**Issue by x1y9** [Genymobile/scrcpy#1425]
**Environment**
 - OS: windows 10
 - scrcpy version: 1.13
 - installation method:  Windows release
 - device model: huawei honor v10
 - Android version: 10

**Describe the bug**
when do ctrl-shift-v to copy a large text (about 400 utf-8 characters) to device clipboard, get 
java.lang.IllegalStateException: Buffer full, call next() to consume

```
java.lang.IllegalStateException: Buffer full, call next() to consume
        at com.genymobile.scrcpy.ControlMessageReader.readFrom(ControlMessageReader.java:36)
        at com.genymobile.scrcpy.DesktopConnection.receiveControlMessage(DesktopConnection.java:110)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:76)
        at com.genymobile.scrcpy.Controller.control(Controller.java:67)
        at com.genymobile.scrcpy.Server$1.run(Server.java:47)
        at java.lang.Thread.run(Thread.java:929)
```

**Comment by rom1v** [comment]
Thank you for your report. :+1:

Fixed by 517dbd9c85842797ec8bf21ced2ddc4040a87230, tested by c7155a1954bd26e09195d8f2c2d582598d5b67dd.
