### ISSUE TITLE
scrcpy can't run with my phone

### ISSUE THREAD

**Issue by imklww** [Genymobile/scrcpy#1430]
I'm sorry about these grammatical errors beacuse my english's kind of sucks
it can't start when my phone running 1080x2312 

```
INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
.\scrcpy-server: 1 file pushed. 3.5 MB/s (27694 bytes in 0.008s)
[server] INFO: Device: HUAWEI MAR-LX2 (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:166)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:69)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:35)
        at com.genymobile.scrcpy.Server.main(Server.java:177)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
INFO: Renderer: direct3d
WARN: Trilinear filtering disabled (not an OpenGL renderer)
INFO: Initial texture: 1080x2312
WARN: Device disconnected
```

but it does work when I turn it to 810x1734,I tired to turn it back to 1080x2312 when I running 810x1734 but there's some parts can't show.I think the problem is the screen of my phone is a weird shape(Huawei p30 lite).Is there any solution to solve it or I should just go to buy a new one.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

Try `scrcpy -m 1600`.

**Comment by imklww** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception
> 
> Try `scrcpy -m 1600`.

it starts as 744x1600,The highest number  I can run is 808x1728
