### ISSUE TITLE
Android 11: could not set settings value

### ISSUE THREAD

**Issue by rom1v** [Genymobile/scrcpy#1468]
_(this issue has been reported to me privately)_

**Environment**
 - OS: any
 - scrcpy version: 1.14
 - installation method: manual
 - device model: Google Pixel 3
 - Android version: 11 preview

**Describe the bug**

```
$ scrcpy --show-touches
[server] INFO: Device: Google Pixel 3 (Android 10)  // note: it is in fact Android 11 preview
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:69)
	at com.genymobile.scrcpy.wrappers.ContentProvider.getValue(ContentProvider.java:110)
	at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:126)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:31)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:396)
Caused by: java.lang.SecurityException: The authority unknown does not match the one of the contentProvider: settings
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2285)
	at android.os.Parcel.createException(Parcel.java:2269)
	at android.os.Parcel.readException(Parcel.java:2252)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
	at android.content.IContentProvider.call(IContentProvider.java:115)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.content.ContentProvider.validateIncomingAuthority(ContentProvider.java:2505)
	at android.content.ContentProvider.access$200(ContentProvider.java:115)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:511)
	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:295)
	at android.os.Binder.execTransactInternal(Binder.java:1159)

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:69)
	at com.genymobile.scrcpy.wrappers.ContentProvider.putValue(ContentProvider.java:122)
	at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:128)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:31)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:396)
Caused by: java.lang.SecurityException: The authority unknown does not match the one of the contentProvider: settings
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2285)
	at android.os.Parcel.createException(Parcel.java:2269)
	at android.os.Parcel.readException(Parcel.java:2252)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
	at android.content.IContentProvider.call(IContentProvider.java:115)
	... 8 more
```

**Comment by hrvojesolc** [comment]
I can confirm this on Google Pixel 4a as well.

**Comment by rom1v** [comment]
Thank you for the reminder. I have no device with Android 11 to test, but now the AOSP sources are available, so I think this commit fixes it: bb760be58ba0d41ad9ef320a0c61623198bf4221

Here is the server with the fix:
- [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/1468/1/scrcpy-server)
  _SHA256: d5737014d433b26209eeb68b99ad718fc9dc251afac0a68dd6a691fbebd56c5b_

(to replace in v1.16 release)

**Comment by hrvojesolc** [comment]
Thank you so much for this!

I'm on snap beta channel, and unfortunately have no idea how to easily update `scrcpy-server` to do a test, since all snap apps are protected via SquashFS. I've checked this (https://askubuntu.com/questions/1035127/cannot-modify-files-installed-by-snap), but not comfortable to hack away for a test.

The following are read-only:
```
/snap/scrcpy/251/usr/local/share/scrcpy/scrcpy-server
/snap/scrcpy/249/usr/local/share/scrcpy/scrcpy-server
```

I'm on beta channel:
```
channels:
  latest/stable:    v1.16            2020-09-03 (254) 86MB -
  latest/candidate: ↑                                      
  latest/beta:      v1.16-4-g0be766e 2020-09-03 (251) 86MB -
  latest/edge:      v1.12-1-g71df317 2019-12-10 (202) 81MB -
installed:          v1.16-4-g0be766e            (251) 86MB -
```

If it isn't too hard to push your change to `edge` channel I could do tests. Thanks again!

**Comment by rom1v** [comment]
You could provide an alternative path to the server:

```bash
SCRCPY_SERVER_PATH=scrcpy-server scrcpy
```

**Comment by tdassonville** [comment]
:heavy_check_mark: Ok on Pixel 3 Android 11 Release

**Comment by hrvojesolc** [comment]
✔️ Ok on Pixel 4a Android 11 Release (both `--show-touches` and `--stay-awake` checked).

Thank you for resolving this promptly!!!

**Comment by rom1v** [comment]
Thank you for your tests :+1:

**Comment by rom1v** [comment]
Rectification: the commit message ae758f99d6af81123bb6b74d307d798c2c17acf3 says:

> This commit in AOSP framework_base added a parameter "attributionTag" to
> the call() method:
> https://android.googlesource.com/platform/frameworks/base.git/+/12ac3f406fed87cb9cd3a28b9947e7202a2d14bd%5E%21/#F17

In fact, the referenced commit renames `featureId` to `attributionTag`, but the commit introducing the parameter change is:
https://android.googlesource.com/platform/frameworks/base.git/+/128b70364ee9ea9bd588908d8002ffa610d3794e%5E%21/
