### ISSUE TITLE
Scrapy on LG GPAD 8.3

### ISSUE THREAD

**Issue by unmanagedtn** [Genymobile/scrcpy#1513]
Does not seem to like a older android device
```
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
C:\Users\Gavin Groce\Downloads\scrcpy-win64-v1.14\scrcpy-s... file pushed, 0 skipped. 23.4 MB/s (33142 bytes in 0.001s)
[server] INFO: Device: LGE VK810 4G (Android 5.0.2)
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 1200x1920
ERROR: SDL failed to get a vertex buffer for this Direct3D 9 rendering batch!
ERROR: Dropping back to a slower method.
ERROR: This might be a brief hiccup, but if performance is bad, this is probably why.
ERROR: This error will not be logged again for this renderer.
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:577)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:256)
Press any key to continue...

```

**Comment by unmanagedtn** [comment]
```
Just try with a lower definition:

scrcpy -m 1920
scrcpy -m 1024
scrcpy -m 800
```
