### ISSUE TITLE
Exception on thread?

### ISSUE THREAD

**Issue by ShyLex** [Genymobile/scrcpy#1520]
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
C:\Users\firea\OneDrive\Desktop\scrcpy-win64-v1.14\scrcpy-... file pushed, 0 skipped. 17.5 MB/s (33142 bytes in 0.002s)
[server] INFO: Device: BLU BOLD N1 (Android 9)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
WARN: Device disconnected
Press any key to continue...

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception
