### ISSUE TITLE
WARN: Device disconnected

### ISSUE THREAD

**Issue by Eduardo499** [Genymobile/scrcpy#1528]
Enable open and now it appears WARNING: Device disconnected
```
[server] INFO: Device: samsung SM-A305GT (Android 10)
INFO: OpenGL shaders: ENABLED
INFO: Created renderer: opengl
INFO: Renderer: opengl
INFO: OpenGL version: 3.1.0 - Build 9.17.10.4459
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2336
WARN: Device disconnected
Press any key to continue...
```

**Comment by rom1v** [comment]
Use another cable/USB port (#281 #283).

**Comment by chesteralan** [comment]
Change the output resolution (INFO: Initial texture: 1080x2336). Must be equal or lower than your desktop resolution. 
use this command: `scrcpy -m1024` (or -m1366)

**Comment by rom1v** [comment]
> Must be equal or lower than your desktop resolution.

(not necessarily, but your device hardware encoder must be able to encode at the requested definition)

**Comment by Aditya9576** [comment]
https://github.com/Genymobile/scrcpy/issues/1528#issuecomment-748616472
this worked thanks

**Comment by Themaddog791** [comment]
[sudo] password for oscar:       
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 362.8 MB/s (41650 bytes in 0.000s)
[server] INFO: Device: samsung SM-S918U (Android 16)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2940)
	at java.lang.Class.getMethod(Class.java:2440)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:128)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:138)
	at com.genymobile.scrcpy.Device.<init>(Device.java:100)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
	at com.genymobile.scrcpy.Server.main(Server.java:334)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:410)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
	at com.genymobile.scrcpy.ScreenEncoder.createDisplay(ScreenEncoder.java:278)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
	at com.genymobile.scrcpy.Server.main(Server.java:334)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:410)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at java.lang.Class.getMethod(Class.java:2940)
	at java.lang.Class.getMethod(Class.java:2440)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:81)
	... 7 more
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 580.95.05
INFO: Trilinear filtering enabled
INFO: Initial texture: 1440x3088
WARN: Device disconnected
WARN: Killing the server...


I have no idea what I'm doing, can someone please help?

**Comment by rom1v** [comment]
> scrcpy 1.25

Uninstall the package, this version is 5 years old, and install the latest version.
