### ISSUE TITLE
在Android5.1.1系统报错

### ISSUE THREAD

**Issue by lixiong4111** [Genymobile/scrcpy#1554]
E:\development_tools\scrcpy-win64-v1.9\scrcpy-win64>scrcpy.exe
E:\development_tools\scrcpy-win64-v1.9\scrcpy-win64\scrcpy...erver.jar: 1 file pushed. 0.7 MB/s (22470 bytes in 0.029s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:72)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
        at com.genymobile.scrcpy.Server.main(Server.java:133)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
ERROR: Could not open video stream
INFO: Initial texture: 1080x1920
Press any key to continue...

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

> E:\development_tools\scrcpy-win64-v1.9\scrcpy-win64

Btw, v1.9 is old. Any reason not to use the latest version?

**Comment by lixiong4111** [comment]
E:\development_tools\scrcpy-win64-v1.14>scrcpy -m 800
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
E:\development_tools\scrcpy-win64-v1.14\scrcpy-server: 1 file pushed, 0 skipped. 0.5 MB/s (33142 bytes in 0.063s)
[server] INFO: Device: unknown Android SDK built for x86 (Android 5.1.1)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 448x800
WARN: Device disconnected
Press any key to continue...

**Comment by rom1v** [comment]
```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

Does it work?

**Comment by lixiong4111** [comment]
adb shell screenrecord /sdcard/file.mp4
Unable to get output buffers (err=-38)
Encoder failed (err=-38)

**Comment by lixiong4111** [comment]
Any idea on how to resolve this problem?

**Comment by rom1v** [comment]
If it does not work with `screenrecord`, it's a problem on the device/ROM. Sorry.

**Comment by act262** [comment]
What's your device info

**Comment by lixiong4111** [comment]
emulators
