### ISSUE TITLE
Crash for Startup

### ISSUE THREAD

**Issue by oatsuper** [Genymobile/scrcpy#1614]
020-07-22 20:54:54.774 scrcpy[29447:603048] INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
[100%] /data/local/tmp/scrcpy-server.jar
[server] INFO: Device: QUALCOMM iQIYI-A3 (Android 7.1.2)
2020-07-22 20:54:55.362 scrcpy[29447:603048] INFO: Created renderer: metal
2020-07-22 20:54:55.362 scrcpy[29447:603048] INFO: Renderer: metal
2020-07-22 20:54:55.365 scrcpy[29447:603048] INFO: Initial texture: 1920x1080
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2570)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
2020-07-22 20:54:55.727 scrcpy[29447:603048] WARN: Device disconnected

The device is a standalone VR headset, just list Oculus Quest ， Scrcpy mirror Quest just very well on my Mac Pro； 

by the way，Scrcpy is so great～～

**Comment by rom1v** [comment]
Reduce the definition: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by oatsuper** [comment]
scrcpy -m 1920
scrcpy -m 1024
scrcpy -m 800

I all had tried，but crash still。。

**Comment by smyang10** [comment]
same issue here. smaller resolution did not help all the way down to 240
