### ISSUE TITLE
How to execute adb commands as fast as your code ? [SIMILAR TO #231]

### ISSUE THREAD

**Issue by rxydenxd** [Genymobile/scrcpy#1625]
[ SIMILAR TO #231 ]

I made a program which executes adb touchscreen commands according to my cursor position. As mentioned in #231 the adb commands are very slow. How can i use YOUR server to execute my commands?

**Comment by Helaer** [comment]
I also need to implement this feature, which is what I am looking forward to.

**Comment by rom1v** [comment]
#129 #613 #1016 #1249

**Comment by rxydenxd** [comment]
```
adb push scrcpy-server.jar /data/local/tmp/scrcpy-server.jar
adb forward tcp:8080 localabstract:scrcpy
adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 0 800000 true - true true
```

used these three commands but got stuck after the last command. There's no response until I `CTRL+C`

**Comment by rom1v** [comment]
That's expected, it gives control back once the server is terminated.

So you must execute this command in a separate process, then connect to `localhost` on port 8080 (according to your `adb forward` command) twice (once for the video socket, once for the control socket).

**Comment by rxydenxd** [comment]
1st CMD PROMPT:
```
C:\Users\rxydenxd\Desktop\scrcpy-win64>adb push scrcpy-server.jar /data/local/tmp/scrcpy-server.jar
scrcpy-server.jar: 1 file pushed. 3.7 MB/s (19342 bytes in 0.005s)

C:\Users\rxydenxd\Desktop\scrcpy-win64>adb forward tcp:8080 localabstract:scrcpy

C:\Users\rxydenxd\Desktop\scrcpy-win64>adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 0 800000 true - true true
```
2nd CMD PROMPT:
```
C:\Users\rxydenxd\Desktop\scrcpy-win64>adb push scrcpy-server.jar /data/local/tmp/scrcpy-server.jar
scrcpy-server.jar: 1 file pushed. 3.2 MB/s (19342 bytes in 0.006s)

C:\Users\rxydenxd\Desktop\scrcpy-win64>adb forward tcp:8080 localabstract:scrcpy

C:\Users\rxydenxd\Desktop\scrcpy-win64>adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 0 800000 true - true true
ERROR: Exception on thread Thread[main,5,main]
java.io.IOException: Address already in use
        at android.net.LocalSocketImpl.bindLocal(Native Method)
        at android.net.LocalSocketImpl.bind(LocalSocketImpl.java:312)
        at android.net.LocalServerSocket.<init>(LocalServerSocket.java:49)
        at com.genymobile.scrcpy.DesktopConnection.listenAndAccept(DesktopConnection.java:38)
        at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:49)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:14)
        at com.genymobile.scrcpy.Server.main(Server.java:78)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
```
