### ISSUE TITLE
scrcpy v1.14 crash on Emulator

### ISSUE THREAD

**Issue by QGB** [Genymobile/scrcpy#1629]
```
>scrcpy

INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
C:\QGB\software\scrcpy-win64-v1.14\scrcpy-server: 1 file pushed, 0 skipped. 4.8 MB/s (33142 bytes in 0.007s)
[server] INFO: Device: samsung SM-N960F (Android 5.1.1)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0x80001001
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:577)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:264)
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 1280x720
WARN: Device disconnected
Press any key to continue...
```

**Environment**
 - OS:   Windows10 x64
 - scrcpy version: v1.14
 - installation method:  Windows release...
 - device model: 
 - Android version: 
![image](https://user-images.githubusercontent.com/8005654/88647774-ef17c280-d0f8-11ea-8911-29d9e318a51b.png)

**Describe the bug**
can not start scrcpy

**Comment by QGB** [comment]
NOX Android7.1  does not crash，but black screen，still not working

![image](https://user-images.githubusercontent.com/8005654/88676670-f4880380-d11e-11ea-84b5-d50fdbf1691e.png)

**Comment by QGB** [comment]
![image](https://user-images.githubusercontent.com/8005654/88676813-1ed9c100-d11f-11ea-8d48-ac19f1ae2ec5.png)

**Comment by rom1v** [comment]
I guess the emulator does not support hardware acceleration for encoding in H.264.

**Comment by QGB** [comment]
```
Assertion Failed 
Assertion failure at get mouse point(/app/src/input manager. c: 26), triggered 1 time: x≥=0&&x<0×10000&&y≥=0&&y<0×10000
Always I AbortBreak Retry
```

![image](https://user-images.githubusercontent.com/8005654/89660132-7cca8d80-d903-11ea-8913-3566e825cb42.png)

**Comment by rom1v** [comment]
This assertion does not exist since v1.6, so I guess you run a very old version of scrcpy (#357).
