### ISSUE TITLE
getting video stream only from server

### ISSUE THREAD

**Issue by jhachandan1994** [Genymobile/scrcpy#1640]
i am trying to get video stream from server using prebuilt server after pushing the scrcpy-server.jar file to device i am getting error as The server version (1.14) does not match the client (0). i am using below commands.

1.    adb push scrcpy-server.jar /data/local/tmp/scrcpy-server.jar
2.    adb forward tcp:8080 localabstract:scrcpy
3.    adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 0 800000 true - true true

getting error as:

[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: The server version (1.14) does not match the client (0)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:119)
	at com.genymobile.scrcpy.Server.main(Server.java:221)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)

how can i get only the video stream from server without building the client.

**Comment by jhachandan1994** [comment]
using:

adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.14 800000 true - true true

i am not getting server version error but i am getting below error:

[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Expecting 14 parameters
	at com.genymobile.scrcpy.Server.createOptions(Server.java:125)
	at com.genymobile.scrcpy.Server.main(Server.java:221)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)

**Comment by xgh8925570** [comment]
@jhachandan1994 Have you solved it？

**Comment by jhachandan1994** [comment]
@xgh8925570  No
