### ISSUE TITLE
crashing on 1.16, had to roll back to 1.14

### ISSUE THREAD

**Issue by garfieldbanks** [Genymobile/scrcpy#1683]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.16
 - installation method: Windows release
 - device model: Nexus 5
 - Android version: 6.0.1

**Describe the bug**
I used 1.14 for a long time without any issue. I noticed there had been several updates so I got the latest version (1.16). After I updated I started getting lots of crashes. I went back to 1.14 and the crashes stopped. Let me know if there is anything specific I can do to get you more information on how to diagnose this.

**Comment by rom1v** [comment]
I need more details.

What do you mean by "crash"? What is the output in the console?

**Comment by garfieldbanks** [comment]
I was using the no-console version. I have switched back to 1.16 and am using the console version now. I will report back once it starts crashing again. Hopefully the console window stays open when it crashes.

**Comment by x93008** [comment]
whatis' error?


INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 61.3 MB/s (33622 bytes in 0.001s)
[server] INFO: Device: Hisilicon L86FA-BO5011A-B (Android 8.0.0)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2043)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:87)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)
ERROR: Could not retrieve device information

**Comment by rom1v** [comment]
@garfieldbanks Did you reproduce with the console open?

@x93008 This is a separate problem, I guess it's not even related to the version (v1.14 or v1.16), just reboot your device.

**Comment by garfieldbanks** [comment]
Still haven't re-encountered the problem. I'll let you know as soon as it happens again.

**Comment by garfieldbanks** [comment]
OK. It crashed but the console didn't show anything except:
`WARN: Device Disconnected`
Is there anything else I can do to provide more info?

**Comment by garfieldbanks** [comment]
Crashed again. Same warning:
`WARN: Device Disconnected`

**Comment by garfieldbanks** [comment]
Third crash, same warning.

**Comment by garfieldbanks** [comment]
OK, now it crashes as soon as I run it.

**Comment by garfieldbanks** [comment]
Crashing on 1.14 now as well. But still no error message in the console...
Anything else I can turn on to get more info on what is happening when it crashes?

**Comment by rom1v** [comment]
Oh ok, it's not a crash then, it's just that the device gets disconnected from `adb` (as if you unplugged it).

If you run `adb logcat` in parallel, you will notice that it also terminates at the same time.

Try with another cable or USB port (see #281 #283).
