### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Status1e2r** [Genymobile/scrcpy#1698]
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
C:\Users\stas-\Desktop\scrcpy-win64-v1.16\scrcpy-server: 1 file pushed, 0 skipped. 23.1 MB/s (33622 bytes in 0.001s)
[server] INFO: Device: HUAWEI JSN-L21 (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
WARN: Device disconnected
Press any key to continue...

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception
