### ISSUE TITLE
Android Studio Emulator Pixel 2 API 30 scrcpy crashes on rotation.

### ISSUE THREAD

**Issue by tzah4748** [Genymobile/scrcpy#1700]
**Environment**
 - OS: Windows 10
 - scrcpy version: 1.16
 - installation method: Windows release
 - device model: Android Studio Emulator - Pixel 2 API 30
 - Android version: 10+

**Describe the bug**
1. Open Pixel 2 (API 30) emulator from Android Studio.
2. Open scrcpy when device is on portrait/landscape -> scrcpy will start normally.
3. Rotate the device -> scrcpy will crash.
```
C:\Users\Tzah\Downloads\scrcpy-win64-v1.16\scrcpy-server: 1 file pushed, 0 skipped. 5.7 MB/s (33622 bytes in 0.006s)
[server] INFO: Device: Google sdk_gphone_x86 (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0x80000002
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2251)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)WARN: Device disconnected

        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Press any key to continue...
```

**NOTES:** Lowering the screen max size to 600 will cause this issue to appear less but with enough rotation requests scrcpy will eventually crash.

**Comment by rom1v** [comment]
On rotation, the current encoding is stopped and a new one is strted with different dimensions. It seems this "device" does not support starting a new encoding immediately.
