### ISSUE TITLE
scrcpy 1.14 crash on Xiaomi MI PAD 3

### ISSUE THREAD

**Issue by joychic** [Genymobile/scrcpy#1703]
[server] INFO: Device: Xiaomi MI PAD 3 (Android 7.0)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2568)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by joychic** [comment]
@rom1v thanks,  It works well now  with a lower definition  scrcpy -m
