### ISSUE TITLE
Fails to build on :server:checkstyle

### ISSUE THREAD

**Issue by dylanmtaylor** [Genymobile/scrcpy#1710]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 20.04
 - scrcpy version: git
 - installation method: manual build
 - device model: OnePlus 7T Pro
 - Android version: 10

**Describe the bug**
checkstyle stage of gradle build fails with this stacktrace:
```
* What went wrong:
Execution failed for task ':server:checkstyle'.
> Unable to process files: [/scrcpy/server/src/main/java/com/genymobile/scrcpy/CleanUp.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/CodecOption.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/ControlMessage.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/ControlMessageReader.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Controller.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/DesktopConnection.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Device.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/DeviceMessage.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/DeviceMessageSender.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/DeviceMessageWriter.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/DisplayInfo.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/IO.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/InvalidDisplayIdException.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/KeyComposition.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Ln.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Options.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Point.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Pointer.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/PointersState.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Position.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/ScreenInfo.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Server.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Size.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/StringUtils.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Workarounds.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/ActivityManager.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/ContentProvider.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayManager.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/InputManager.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/PowerManager.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/ServiceManager.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/StatusBarManager.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/WindowManager.java, /scrcpy/server/src/test/java/com/genymobile/scrcpy/CodecOptionsTest.java, /scrcpy/server/src/test/java/com/genymobile/scrcpy/ControlMessageReaderTest.java, /scrcpy/server/src/test/java/com/genymobile/scrcpy/DeviceMessageWriterTest.java, /scrcpy/server/src/test/java/com/genymobile/scrcpy/StringUtilsTest.java]

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':server:checkstyle'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: : Unable to process files: [/scrcpy/server/src/main/java/com/genymobile/scrcpy/CleanUp.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/CodecOption.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/ControlMessage.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/ControlMessageReader.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Controller.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/DesktopConnection.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Device.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/DeviceMessage.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/DeviceMessageSender.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/DeviceMessageWriter.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/DisplayInfo.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/IO.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/InvalidDisplayIdException.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/KeyComposition.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Ln.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Options.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Point.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Pointer.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/PointersState.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Position.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/ScreenInfo.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Server.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Size.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/StringUtils.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/Workarounds.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/ActivityManager.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/ContentProvider.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayManager.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/InputManager.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/PowerManager.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/ServiceManager.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/StatusBarManager.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java, /scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/WindowManager.java, /scrcpy/server/src/test/java/com/genymobile/scrcpy/CodecOptionsTest.java, /scrcpy/server/src/test/java/com/genymobile/scrcpy/ControlMessageReaderTest.java, /scrcpy/server/src/test/java/com/genymobile/scrcpy/DeviceMessageWriterTest.java, /scrcpy/server/src/test/java/com/genymobile/scrcpy/StringUtilsTest.java]
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.processFiles(CheckstyleAntTask.java:377)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.realExecute(CheckstyleAntTask.java:331)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.execute(CheckstyleAntTask.java:303)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:80)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:483)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:195)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
        at org.gradle.api.internal.project.antbuilder.AntBuilderDelegate.nodeCompleted(AntBuilderDelegate.java:124)
        at org.gradle.api.plugins.quality.internal.CheckstyleInvoker$_invoke_closure1.doCall(CheckstyleInvoker.groovy:58)
        at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:52)
        at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$2.execute(DefaultIsolatedAntBuilder.java:154)
        at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$2.execute(DefaultIsolatedAntBuilder.java:136)
        at org.gradle.api.internal.project.antbuilder.ClassPathToClassLoaderCache.withCachedClassLoader(ClassPathToClassLoaderCache.java:135)
        at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder.execute(DefaultIsolatedAntBuilder.java:130)
        at org.gradle.api.internal.project.IsolatedAntBuilder$execute$0.call(Unknown Source)
        at org.gradle.api.plugins.quality.internal.CheckstyleInvoker.invoke(CheckstyleInvoker.groovy:51)
        at org.gradle.api.plugins.quality.Checkstyle.run(Checkstyle.java:151)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:727)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:568)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:553)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:536)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:276)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:265)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
        ... 30 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /scrcpy/server/src/main/java/com/genymobile/scrcpy/KeyComposition.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:281)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:196)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.processFiles(CheckstyleAntTask.java:371)
        ... 111 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: TokenStreamRecognitionException occurred during the analysis of file /scrcpy/server/src/main/java/com/genymobile/scrcpy/KeyComposition.java.
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:188)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:301)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:271)
        ... 113 more
Caused by: /scrcpy/server/src/main/java/com/genymobile/scrcpy/KeyComposition.java:56:19: expecting ''', found '?'
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:405)
        at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
        at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:134)
        at antlr.TokenBuffer.fill(TokenBuffer.java:69)
        at antlr.TokenBuffer.LA(TokenBuffer.java:80)
        at antlr.LLkParser.LA(LLkParser.java:52)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classOrInterfaceType(GeneratedJavaRecognizer.java:977)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classTypeSpec(GeneratedJavaRecognizer.java:818)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeSpec(GeneratedJavaRecognizer.java:780)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.declaration(GeneratedJavaRecognizer.java:1532)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.traditionalStatement(GeneratedJavaRecognizer.java:5314)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.statement(GeneratedJavaRecognizer.java:4251)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compoundStatement(GeneratedJavaRecognizer.java:3917)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3319)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:2541)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:634)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:556)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:389)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:202)
        at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:440)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:175)
        ... 116 more
```
seems to be related to the fact that /scrcpy/server/src/main/java/com/genymobile/scrcpy/KeyComposition.java contains non-ASCII characters based on the searching that I've done.

**Comment by rom1v** [comment]
Weird, it works locally on my machine :confused:

**Comment by dylanmtaylor** [comment]
> Weird, it works locally on my machine

You can try the build I'm doing via Actions (without the workaround) and it will fail on the checkstyle step of Gradle. Maybe it is something I configured wrong?
