### ISSUE TITLE
RPi crash at startup

### ISSUE THREAD

**Issue by M2112** [Genymobile/scrcpy#1724]
- [x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Raspbian buster 32bit
 - scrcpy version: 1.16
 - installation method: manual build
 - device model: Raspberry Pi 3 B+
 - Android version: 8.0

I've seen similar problems about this but none with the RPi, after building the server and installing it on Raspbian with a little trouble I tried using my Asus smartphone via USB-C but the console returned ERROR: Exception on thread Thread[main,5,main] as it shows:

```
pi@raspberrypi:~/scrcpy $ scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server:...ushed. 0.1 MB/s (2003 bytes in 0.013s)
ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Expecting 5 parameters
	at com.genymobile.scrcpy.Server.createOptions(Server.java:53)
	at com.genymobile.scrcpy.Server.main(Server.java:109)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)

```
I don't know where to start so I can make it work, also I tried to downgrade the resolution with "-m" parameter and "-b", even with fps rate but got no different results, so I don't think thats the real source of this problem. I've installed scrcpy on my Windows 10 Laptop and my Asus phone worked flawlessly, so I discard the phone as the problem. I assume it has to do with the Java version for RPi but i don't know which changes I could try to have different results or make it work, I would really appreciate any help to solve this issue guys, been trying to mirror my phone through RPi but I only got it wirelessly with other apps (stability/lag issues). Thanks!

Ps. Tried a Huawei P10 Lite on the Pi but srcpy only starts the connection and immediately aborts.

**Comment by rom1v** [comment]
You don't use the right scrcpy-server, but an old one.

**Comment by M2112** [comment]
So you mean that I have to re-build a latest version of scrpcy?
Thanks for helping :)

**Comment by M2112** [comment]
Okay so I downloaded again the source, build it using the pre-build of the server v1.8 and started scrcpy but get the exact same error I posted first, still says scrcpy 1.16, I'm using "git clone" to get the files. Any idea what's wrong?

**Comment by M2112** [comment]
> You don't use the right scrcpy-server, but an old one (the server version must match the client version).

I checked the version and try it out again, here's the output:

```
pi@raspberrypi:~/scrcpy $ scrcpy -v                                       scrcpy 1.16

dependencies:
 - SDL 2.0.9
 - libavcodec 58.35.100
 - libavformat 58.20.100
 - libavutil 56.22.100
pi@raspberrypi:~/scrcpy $ scrcpy                                          INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-serv...ed. 0.2 MB/s (2048 bytes in 0.012s) ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Expecting 5 parameters
at com.genymobile.scrcpy.Server.createOptions(Server.java:53)
at com.genymobile.scrcpy.Server.main(Server.java:109)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)
```

**Comment by M2112** [comment]
@rom1v thank you so much for the hint!! Apparently the "git clone"  download was downloading another version (v1.8 ¿?) and you were right, incompatibility between the server and client caused this problem. Had to uninstall everything and then double check that the pre-built server and client were the same version before I downloaded them, then everything was straightforward and the built was done, once installed everything worked correctly. I don't know if it changes anything but I have both Java 11 and 8 installed on the RPi so since this project was made with Java 8 I made it my default version, don't know if that matters.
Thank you so much for that hint! I really appreciate your help and the work you guys are making for this project, really really useful. Much love <3 :)

I will close this as soon as I get an answer from you rom1v or tomorrow evening, whatever happens first. THANK YOU.

**Comment by rom1v** [comment]
> using the pre-build of the server v1.8

Take prebuilt server v1.16.

https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server
