### ISSUE TITLE
exception at start

### ISSUE THREAD

**Issue by cognitus** [Genymobile/scrcpy#1728]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: fedora 32
 - scrcpy version:  v1.16
 - installation method: COPR

**Describe the bug**
since recently, i cannot start scrcpy for exception

```
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 1.5 MB/s (18802 bytes in 0.012s)
27183
WARN: Could not disable minimize on focus loss
ERROR: Exception on thread Thread[main,5,main]
java.lang.NumberFormatException: For input string: "1.16"
        at java.lang.Integer.parseInt(Integer.java:615)
        at java.lang.Integer.parseInt(Integer.java:650)
        at com.genymobile.scrcpy.Server.createOptions(Server.java:52)
        at com.genymobile.scrcpy.Server.main(Server.java:101)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
```

**Comment by rom1v** [comment]
You don't use the right version of the scrcpy-server.

**Comment by cognitus** [comment]
@rom1v thanks!
I replace scrcpy-server in the system and works
