### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by eyyubi** [Genymobile/scrcpy#1744]
**Environment**
 - OS: [Arch Linux]
 - scrcpy version: [16.0]
 - installation method: [Manual build without server build]
 - device model:General mobile Etap5
 - Android version: [5.1]

**Describe the bug**

```
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 69.1 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: General Mobile Etab5 (Android 5.1)
INFO: Renderer: opengl
INFO: OpenGL version: 4.5 (Compatibility Profile) Mesa 20.1.7
INFO: Trilinear filtering enabled
INFO: Initial texture: 1920x1200
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1046)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:250)

```

***logcat***
```
W/ADB_SERVICES( 4735): create_local_service_socket() name=reverse:forward:localabstract:scrcpy;tcp:27183
W/ADB_SERVICES( 4735): service_to_fd() name=reverse:forward:localabstract:scrcpy;tcp:27183
W/ADB_SERVICES( 4735): LS(81): bound to 'reverse:forward:localabstract:scrcpy;tcp:27183' via 14
D/ADB_SERVICES( 4735): install_listener('localabstract:scrcpy','tcp:27183')
W/ADB_SERVICES( 4735): create_local_service_socket() name=shell:CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.16 info 0 8000000 0 -1 false - true true 0 false false -
W/ADB_SERVICES( 4735): service_to_fd() name=shell:CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.16 info 0 8000000 0 -1 false - true true 0 false false -
W/ADB_SERVICES( 4735): LS(82): bound to 'shell:CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.16 info 0 8000000 0 -1 false - true true 0 false false -' via 14
D/AndroidRuntime(14580): Calling main entry com.genymobile.scrcpy.Server
I/scrcpy  (14580): Device: General Mobile Etab5 (Android 5.1)
I/BufferQueueConsumer(  203): [VDS: scrcpy](this:0xb5c55000,id:257,api:0,p:-1,c:203) setConsumerName: VDS: scrcpy
I/BufferQueueConsumer(  203): [VDS: scrcpy](this:0xb5c55000,id:257,api:0,p:-1,c:203) setDefaultBufferSize: width=1920 height=1200
W/SurfaceFlinger(  203): [scrcpy] Unexpected dequeueBuffer() in IDLE state
W/SurfaceFlinger(  203): [scrcpy] EGL called dequeueBuffer with !async despite eglSwapInterval(0)
E/SurfaceFlinger(  203): [scrcpy] dequeueBuffer: no buffer, bailing out
W/SurfaceFlinger(  203): [scrcpy] Unexpected beginFrame() in GLES state
W/BufferQueueProducer(  203): [VDS: scrcpy](this:0xb5c55000,id:257,api:0,p:-1,c:203) dequeueBuffer() in a disconnected state
I/BufferQueueProducer(  203): [VDS: scrcpy](this:0xb5c55000,id:257,api:0,p:-1,c:203) new GraphicBuffer needed
W/BufferQueueProducer(  203): [VDS: scrcpy](this:0xb5c55000,id:257,api:0,p:-1,c:203) queueBuffer() in a disconnected state
W/ADB_SERVICES( 4735): create_local_service_socket() name=reverse:killforward:localabstract:scrcpy
W/ADB_SERVICES( 4735): service_to_fd() name=reverse:killforward:localabstract:scrcpy
W/ADB_SERVICES( 4735): LS(85): bound to 'reverse:killforward:localabstract:scrcpy' via 25
I/BufferQueueConsumer(  203): [VDS: scrcpy](this:0xb5c55000,id:257,api:0,p:-1,c:-1) disconnect(C)
I/BufferQueue(  203): [VDS: scrcpy](this:0xb5c55000,id:257,api:0,p:-1,c:-1) ~BufferQueueCore
D/AndroidRuntime(14597): Calling main entry com.genymobile.scrcpy.CleanUp
I/scrcpy  (14597): Cleaning up
I/scrcpy  (14597): Restoring normal power mode
```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by eyyubi** [comment]
Thanks, that's the problem
