### ISSUE TITLE
Screen size bigger than phone encode capability cause scrcpy server crash

### ISSUE THREAD

**Issue by huarui1q** [Genymobile/scrcpy#1749]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows]
 - scrcpy version: [1.15.1]
 - installation method: [Windows release]
 - device model:
 - Android version: [10]

**Describe the bug**
Screen size bigger than phone encode capability will cause scrcpy server crash. This phone support 1080*1920 encode.

```
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2304
```

**Comment by rom1v** [comment]
Yes: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

But AFAIK you cannot know **reliably** the encoding size capabilities.
