### ISSUE TITLE
More than one device and emulator

### ISSUE THREAD

**Issue by 7wells** [Genymobile/scrcpy#1759]
**Environment**
 - OS: Windows 10 Pro 64bit
 - scrcpy version: 1.16
 - installation method: scoop install scrcpy
 - scrcpy execution: via Windows Powershell 7.0.3 (64bit)
 - target device model: Amazon Fire TV box
 - Android version: Fire OS 5.2.7.4 (Android Level 22 = Android 5.1)

**Describe the bug**
It says 'more than one device and emulator', despite only one is shown:
```
PS C:\Users\user> adb connect 192.168.178.34
* daemon not running; starting now at tcp:5037
* daemon started successfully
connected to 192.168.178.34:5555
PS C:\Users\user> adb devices
List of devices attached
192.168.178.34:5555     device

PS C:\Users\master> scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
C:\Users\user\scoop\apps\scrcpy\current\scrcpy-server: 1 file pushed, 0 skipped. 17.1 MB/s (33622 bytes in 0.002s)
adb.exe: error: more than one device and emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
27183
[server] INFO: Device: Amazon AFTB (Android 5.1.1)
INFO: Renderer: direct3d
INFO: Initial texture: 1920x1080
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:599)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrWARN: Device disconnected
cpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:256)
Press any key to continue...
```

**Comment by 7wells** [comment]
`PS C:\Users\master> scrcpy -s 192.168.178.34:5555` shows the same error message.

**Comment by rom1v** [comment]
> `PS C:\Users\user> scrcpy -s 192.168.178.34:5555` shows the same error message.

That's expected:
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#several-devices-connected

**Comment by 7wells** [comment]
Oh, I did to realize that the part about more than... also applies to adb over TCPIP. Thank you! 👍
