### ISSUE TITLE
stay-awake causes java error

### ISSUE THREAD

**Issue by Mathew-D** [Genymobile/scrcpy#1777]
**Environment**
 - OS: Manjaro Linux 5.8 kernal
 - scrcpy version: 1.16
 - installation method: AUR
 - device model:Google Pixel 2 XL
 - Android version: 11

**Describe the bug**
When adding the -w or the --stay-awake with scrcpy I get the following errors.  If I take the -w off it works great. Any idea how this can be fixxed.  I don't want to have to keep turning the screen locking timer off every time I am screen sharing.

Here is the output:
```
scrcpy --bit-rate 30M -w
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 232.5 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: Google Pixel 2 XL (Android 11)
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:69)
        at com.genymobile.scrcpy.wrappers.ContentProvider.getValue(ContentProvider.java:110)
        at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:126)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:38)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Caused by: java.lang.SecurityException: The authority unknown does not match the one of the contentProvider: settings
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
        at android.content.IContentProvider.call(IContentProvider.java:115)
        ... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
        at android.content.ContentProvider.validateIncomingAuthority(ContentProvider.java:2505)
        at android.content.ContentProvider.access$200(ContentProvider.java:115)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:511)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:295)
        at android.os.Binder.execTransactInternal(Binder.java:1154)

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:69)
        at com.genymobile.scrcpy.wrappers.ContentProvider.putValue(ContentProvider.java:122)
        at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:128)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:38)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Caused by: java.lang.SecurityException: The authority unknown does not match the one of the contentProvider: settings
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
        at android.content.IContentProvider.call(IContentProvider.java:115)
        ... 8 more
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 20.1.7
INFO: Trilinear filtering enabled
INFO: Initial texture: 1440x2880
INFO: New texture: 2880x1440
INFO: New texture: 1440x2880

```

**Comment by rom1v** [comment]
Hi,

Thank you for your report.

It's due to a change in Android 11, and is fixed on `dev` branch. see #1468.
