### ISSUE TITLE
ERROR: Could not invoke method: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by jpage4500** [Genymobile/scrcpy#1788]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS
 - scrcpy version: 1.16
 - installation method: brew
 - device model: Google Pixel 4a
 - Android version: 11

**Describe the bug**

Using a Pixel 4a / Android 11 -- scrcpy seems to work fine but I get this in the logs. So, not really a bug per-ce but something I figured would be worth posting

```
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:69)
	at com.genymobile.scrcpy.wrappers.ContentProvider.getValue(ContentProvider.java:110)
	at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:126)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:31)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Caused by: java.lang.SecurityException: The authority unknown does not match the one of the contentProvider: settings
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
	at android.content.IContentProvider.call(IContentProvider.java:115)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.content.ContentProvider.validateIncomingAuthority(ContentProvider.java:2505)
	at android.content.ContentProvider.access$200(ContentProvider.java:115)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:511)
	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:295)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
```

**Comment by rom1v** [comment]
Hi,

Thank you for your report.

It's due to a change in Android 11, and is fixed on `dev` branch. see #1468.
