### ISSUE TITLE
Cannot createDisplay on the latest Android master build

### ISSUE THREAD

**Issue by wjf3121** [Genymobile/scrcpy#1791]

**Comment by wjf3121** [comment]
This is the exception thrown from scrcpy, I've modified the code a bit so the code location is a little off:

[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:384)
        at com.genymobile.scrcpy.ScreenEncoder.setupStreamScreenWithoutEncoding(ScreenEncoder.java:122)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:82)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:81)
        at com.genymobile.scrcpy.Server.main(Server.java:292)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3070)
        at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2170)
        ... 9 more

**Comment by rom1v** [comment]
Why did you remove the content knstead of explaining what the problem was?

**Comment by wjf3121** [comment]
I just realized that the Android code that causes the issue is not merged into the public repo yet so deleting it in case of any violation. I will recreate the issue once the change is visible publicly or I can confirm that discussing unreleased code won’t violating any policy.

Sorry for causing the confusion.

On Sep 25, 2020, at 14:02, Romain Vimont <notifications@github.com> wrote:

﻿

Why did you remove the content knstead of explaining what the problem was?
