### ISSUE TITLE
Looks like doesn't work on Chromebooks

### ISSUE THREAD

**Issue by bhaskarnn9** [Genymobile/scrcpy#180]
Works fine on emulator and also on phone via USB. No luck with ChromeBook
My ChromeBook is connected via ethernet... Running on ARC 7.1.1

user$ scrcpy -s 100.107.191.140:5555
/usr/local/share/scrcpy/scrcpy-server.jar: 1 file pushed. 0.3 MB/s (19342 bytes in 0.060s)
ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1884)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:135)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:62)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:22)
	at com.genymobile.scrcpy.Server.main(Server.java:78)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:269)
2018-06-21 12:07:33.962 scrcpy[98264:3038667] ERROR: Could not retrieve device information

**Comment by KeronCyst** [comment]
I, too, am interested in Chromebook compatibility.

**Comment by rom1v** [comment]
What if you reduce the definition:

    scrcpy -m 1280
    scrcpy -m 800

?

**Comment by lid** [comment]
Just built https://github.com/Genymobile/scrcpy/commit/1144f642144103a3b0bbd017998d75edd9d2a8b8 on my Chromebook/Crostini (cros-termina - Version: 12607.32.1) and it works fine via USB.

**Comment by michaelcadilhac** [comment]
Just to clarify what "working fine" means: scrcpy can only record Android apps, and not the whole (ChromeOS) desktop, correct?  If I understand this correctly, Android (and adb) are sublayers in ChromeOS, and scrcpy uses adb to fetch the stream (a la screenrecord), so has no access to native ChromeOS apps (or Crostini apps for that matter).  Thanks!
