### ISSUE TITLE
Only screen is visible but no control

### ISSUE THREAD

**Issue by LucaGabi** [Genymobile/scrcpy#1813]
- [x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows 10
 - scrcpy version: 1.12.1
 - installation method:  windows release
 - device model: Redmi 7A
 - Android version: 9 PKQ1,190319,001

**Describe the bug**
- Only screen is visible but no control at all
- works great with samsung device

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
C:\Work\tools\droid-remote\scrcpy-server: 1 file pushed. 0.6 MB/s (26202 bytes in 0.041s)
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.Resources.<init>(Resources.java:267)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
        at android.content.res.Resources.getSystem(Resources.java:190)
        at android.app.LoadedApk.<init>(LoadedApk.java:211)
        at android.app.ContextImpl.createSystemContext(ContextImpl.java:2331)
        at android.app.ActivityThread.getSystemContext(ActivityThread.java:2190)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
        at com.genymobile.scrcpy.Server.main(Server.java:163)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)
INFO: Initial texture: 720x1440
```

**Comment by rom1v** [comment]
> Only screen is visible but no control at all

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

> scrcpy version: 1.12.1

That's an old version. Latest is 1.16.
