### ISSUE TITLE
[server] ERROR: Exception on thread Thread[main,5,main]

### ISSUE THREAD

**Issue by Vishesh987** [Genymobile/scrcpy#1818]
C:\scrcpy>scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 13.9 MB/s (33622 bytes in 0.002s)
[server] INFO: Device: LENOVO Lenovo K33a42 (Android 7.0)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:30)
        at com.genymobile.scrcpy.Device.<init>(Device.java:57)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:23)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:17)
        ... 5 more
Press any key to continue...

**Comment by rom1v** [comment]
Ref #932
