### ISSUE TITLE
Fire Tablet 2020

### ISSUE THREAD

**Issue by genifycom** [Genymobile/scrcpy#1844]
Getting this with the Fire Tablet but not other devices.

WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by wasantosfi** [comment]
> Getting this with the Fire Tablet but not other devices. Note: INFO: Initial texture: 800x1280
> 
> WARN: Device disconnected [server] ERROR: Exception on thread Thread[main,5,main] java.lang.IllegalStateException at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method) at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698) at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108) at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89) at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55) at com.genymobile.scrcpy.Server.scrcpy(Server.java:76) at com.genymobile.scrcpy.Server.main(Server.java:225) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)

Hi, I can confirm **scrcpy -m 1280** works on the Fire HD 10 2021 (Brazil) version
Using an old ASUS notebook (S56CB with 240gb SSD and 8gb RAM) with screen as 1366x768 with Elementary OS 6.1
Looks stable and no delay noticed for now.
I tried using **scrcpy -m 1366** but it started the sync but soon (+/- 1 sec) got disconnected
