### ISSUE TITLE
Exception thrown with --stay-awake

### ISSUE THREAD

**Issue by thangktran** [Genymobile/scrcpy#1845]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: ubuntu 20.04
 - scrcpy version: 1.16
 - installation method: snap
 - device model: pixel 4
 - Android version: 11

**Describe the bug**
The device is connected via WIFI. 
Everything works as expected, however when the flag `-w` is invoked, the following exception is thrown.

edit: this seems to duplicate https://github.com/Genymobile/scrcpy/issues/1468 and https://github.com/Genymobile/scrcpy/issues/1761
```
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:69)
	at com.genymobile.scrcpy.wrappers.ContentProvider.getValue(ContentProvider.java:110)
	at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:126)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:38)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Caused by: java.lang.SecurityException: The authority unknown does not match the one of the contentProvider: settings
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
	at android.content.IContentProvider.call(IContentProvider.java:115)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.content.ContentProvider.validateIncomingAuthority(ContentProvider.java:2505)
	at android.content.ContentProvider.access$200(ContentProvider.java:115)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:511)
	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:295)
	at android.os.Binder.execTransactInternal(Binder.java:1154)

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:69)
	at com.genymobile.scrcpy.wrappers.ContentProvider.putValue(ContentProvider.java:122)
	at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:128)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:38)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Caused by: java.lang.SecurityException: The authority unknown does not match the one of the contentProvider: settings
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
	at android.content.IContentProvider.call(IContentProvider.java:115)
	... 8 more
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 20.0.8
INFO: Trilinear filtering enabled
INFO: Initial texture: 496x1024
```

**Comment by rom1v** [comment]
> edit: this seems to duplicate #1468 and #1761

Yes, this is fixed on `dev`.
