### ISSUE TITLE
Not Good with scrcpy -m 1024

### ISSUE THREAD

**Issue by tony8077616** [Genymobile/scrcpy#1885]
- [ Y ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ Y ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Win10
 - scrcpy version: 1.16
 - installation method: Windows
 - device model: OnePlus 5T
 - Android version: CrDroid 6.11(Android 10)

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

Logcat is here [123.txt](https://github.com/Genymobile/scrcpy/files/5495345/123.txt)

PS D:\scrcpy-win64-v1.16> .\adb connect 192.168.111.23:5555
adb server version (32) doesn't match this client (41); killing...
* daemon started successfully
connected to 192.168.111.23:5555
PS D:\scrcpy-win64-v1.16> .\scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
D:\scrcpy-win64-v1.16\scrcpy-server: 1 file pushed, 0 skipped. 44.4 MB/s (33622 bytes in 0.001s)
[server] INFO: Device: OnePlus ONEPLUS A5010 (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2792)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:342)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2160
WARN: Device disconnected
Press any key to continue...

PS D:\scrcpy-win64-v1.16> .\scrcpy -m 1024
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
D:\scrcpy-win64-v1.16\scrcpy-server: 1 file pushed, 0 skipped. 53.0 MB/s (33622 bytes in 0.001s)
[server] INFO: Device: OnePlus ONEPLUS A5010 (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2792)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:342)
INFO: Renderer: direct3d
INFO: Initial texture: 512x1024
WARN: Device disconnected
Press any key to continue...

PS D:\scrcpy-win64-v1.16>

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Probably an encoder crash (like some comments in #465).

Please provide the logcat:
```bash
adb logcat -c  # clear logs
scrcpy
adb logcat -d > logcat.txt
```

**Comment by tony8077616** [comment]
[https://github.com/Genymobile/scrcpy/files/5495345/123.txt](url)

**Comment by tony8077616** [comment]
`11-05 23:33:01.973  1169 23001 E C2DColorConvert: FATAL ERROR: could not dlopen libc2d2.so: dlopen failed: cannot locate symbol "atrace_get_enabled_tags" referenced by "/vendor/lib/libC2D2.so"...
11-05 23:33:01.973   865 23030 I mm-camera: <CPP   >< INFO> 368: cpp_hardware_set_clock: Set clock 576000000 BW avg 62208000 BW inst 62208000
11-05 23:33:01.973   865 23014 I mm-camera: <CPP   >< INFO> 4466: cpp_module_handle_streamon_event: identity=0x50003, stream-on done
11-05 23:33:01.974   865 23014 I mm-camera: <IFACE >< INFO> 1806: iface_streamon_to_thread: iface_streamon_to_thread: X, session id = 5, user stream id = 3
11-05 23:33:01.974   865 23014 E mm-camera: <SENSOR><ERROR> 828: sensor_util_set_stream_on: [DEBUG] identy 50003: stream on
11-05 23:33:01.974   865 23014 I mm-camera: <MCT   >< INFO> 4324: mct_pipeline_process_set:  STREAM-ON success for stream 0x50003, stream type=5
11-05 23:33:01.974   865 23043 I QCamera : <MCI><INFO> mm_channel_start: 1942: start stream at idx(3) stream_type(11)
11-05 23:33:01.974   865 23014 I mm-camera: <MCT   >< INFO> 4163: mct_pipeline_process_set: command=8000008
11-05 23:33:01.974   865 23014 I mm-camera: <MCT   >< INFO> 4308: mct_pipeline_process_set:  STREAM-ON on stream 0x50004 stream type=11
11-05 23:33:01.974   865 23014 I mm-camera: <SENSOR>< INFO> 6692: module_sensor_module_process_event: [DEBUG] ide 50003 stream type 5 MCT_EVENT_CONTROL_STREAMON
11-05 23:33:01.974   865 23014 I mm-camera: <SENSOR>< INFO> 3737: module_sensor_stream_on: [DEBUG] sensor imx371 stream type 11: NO STREAM_ON
11-05 23:33:01.974   865 23014 I mm-camera: <SENSOR>< INFO> 3770: module_sensor_stream_on: Sensor imx371 torch mode 0 last torch mode 0
11-05 23:33:01.974   865 23014 I mm-camera: <IFACE >< INFO> 1777: iface_streamon_to_thread: iface_streamon_to_thread: E, session id = 5, user stream id = 4
11-05 23:33:01.974   865 23023 I mm-camera: <IFACE >< INFO> 2124: iface_streamon: E, session_id 5 mct_stream_id = 4
11-05 23:33:01.974   865 23023 I mm-camera: <IFACE >< INFO> 12128: iface_util_get_user_streams_by_bundle: streamon, got all bundled streamon!
11-05 23:33:01.976  1169 23001 E C2DColorConvert: C2D library initialization failed
11-05 23:33:01.976  1169 23001 E OMX-VENC: Color Conversion failed
11-05 23:33:01.976  1169 23001 E OMX-VENC: ERROR: ETBProxy() failed!
11-05 23:33:01.976  1169 23001 E OMX-VENC: ERROR: send OMX_ErrorHardware to Client
11-05 23:33:01.976 22981 22999 E ACodec  : [OMX.qcom.video.encoder.avc] ERROR(0x80001009)
11-05 23:33:01.976 22981 22999 E ACodec  : signalError(omxError 0x80001009, internalError -2147483648)
11-05 23:33:01.976  1437  1580 I DisplayPowerController: Unblocked screen on after 121 ms
11-05 23:33:01.976 22981 22998 E MediaCodec: Codec reported err 0x80001009, actionCode 0, while in state 6
11-05 23:33:01.978  1169 23001 E C2DColorConvert: C2D library initialization failed
11-05 23:33:01.978  1169 23001 E OMX-VENC: Color Conversion failed
11-05 23:33:01.978  1169 23001 E OMX-VENC: ERROR: ETBProxy() failed!`

Maybe is crashed

**Comment by rom1v** [comment]
Looks like a hardware encoder / ROM issue.

Does it work with `screenrecord`?

```bash
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```
