### ISSUE TITLE
Dead Screen Error Thrown

### ISSUE THREAD

**Issue by lakshaytalkstocomputer** [Genymobile/scrcpy#1892]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 18.04
 - scrcpy version: 116
 - installation method: apt
 - device model: POCO F1
 - Android version: 10

**Describe the bug**

When the screen is dead, the following error occurs!

On errors, please provide the output of the console (and `adb logcat` if relevant).
```
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server:...shed. 3.9 MB/s (33622 bytes in 0.008s)
[server] INFO: Device: Xiaomi POCO F1 (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.WindowManager.registerRotationWatcher(WindowManager.java:108)
	at com.genymobile.scrcpy.Device.<init>(Device.java:68)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:23)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.WindowManager.registerRotationWatcher(WindowManager.java:102)
	... 5 more
Caused by: android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:511)
	at android.view.IWindowManager$Stub$Proxy.watchRotation(IWindowManager.java:3621)
	... 7 more
```

**Comment by rom1v** [comment]
Looks like #932.
