### ISSUE TITLE
Stuck at INFO: Initial Textures

### ISSUE THREAD

**Issue by zYFanzY** [Genymobile/scrcpy#1898]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by zYFanzY** [comment]
@rom1v please help me!!

**Comment by Aliend95** [comment]
Hi,

I have the same issue "stuck at INFO: Initial texture: 1080x2216". I got a rectangular window simulating the smartphone screen, but full green, then nothing else. My phone lights up during that moment. I reviewed  almost all FAQ related to this subject, but main comments are out of date (2019). I do not know if they are still valid.

Environment
    OS: Windows 10
    scrcpy version: scrcpy-win64-v1.17. I tried also v1.16 without success
    installation method: [e.g. manual build, apt, snap, brew, Windows release...]
    device model: Galaxy Note8 
    Android version: 9

Please clarify how to generate the dump file "logcat" with adb.
1) open a DOS instance with CMD?
2) change directory to the folder containing Srccpy?
3) enter "adb logcat -c" to clera the uffer?
4) enter "adb logcat" to run the dump But when and what i should copy. How to stop this dump?
Should launch "Srccpy.exe" before the dump?

Thanks for your assistance.

**Comment by rom1v** [comment]
Before anything else:
 - try with a lower definition (`scrcpy -m800`) 
 - try with another [encoder](https://github.com/Genymobile/scrcpy#encoder)

> enter "adb logcat -c" to clera the uffer?
> enter "adb logcat" to run the dump But when and what i should copy. How to stop this dump?
> Should launch "Srccpy.exe" before the dump?

1. `adb logcat -c` to clear the buffer
2. run scrcpy (and close it)
3. run `adb logcat -d > logcat.txt` (it will dump the whole logcat content to a file and exit)

**Comment by Aliend95** [comment]
Hi Rom1v,

I attached two logcat files : 
•	logcat 09h52 _scrcpy_ .txt  …..edited after the run of “scrcopy”
•	logcat 09h55 _scrcpy -m800_ . txt  …..edited after the run of “scrcopy –m800”

Regarding the test with another encoder, I listed the encoder available , by command “scrcpy --encoder _” and got this list:
com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:176)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:77)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:341)
[server] ERROR: Try to use one of the available encoders:
[server] ERROR:     scrcpy --encoder-name 'OMX.Exynos.AVC.Encoder'
[server] ERROR:     scrcpy --encoder-name 'OMX.google.h264.encoder'

I try to find this encoder file 'OMX.Exynos.AVC.Encoder' and I pick up this encoder file “scrcpy-server SHA256: 93eaf623d15f8101b96c395e520a3f5d38b7968e37cdefff9f1ab94bcc255b97”
Result: logcat file “logcat 10h392 _scrcpy_ another encoder .txt” …. Here attached

Should I try another encoder? 

attachments:
[logcat 09h52 _scrcpy_ .txt](https://github.com/Genymobile/scrcpy/files/6122023/logcat.09h52._scrcpy_.txt)
[logcat 09h55 _scrcpy -m800_ .txt](https://github.com/Genymobile/scrcpy/files/6122025/logcat.09h55._scrcpy.-m800_.txt)
[logcat 10h392 _scrcpy_ another encoder .txt](https://github.com/Genymobile/scrcpy/files/6122026/logcat.10h392._scrcpy_.another.encoder.txt)

**Comment by rom1v** [comment]
> I try to find this encoder file 'OMX.Exynos.AVC.Encoder' and I pick up this encoder file 

The encoder is not the file, it's just a name.
So to try:

```
 scrcpy --encoder 'OMX.Exynos.AVC.Encoder'
```

Btw, the option name in the error message was incorrect: 429fdef04fbc40da9050f4b008a438feb56d3450
