### ISSUE TITLE
After switching Pixel 3a to Android 11

### ISSUE THREAD

**Issue by genifycom** [Genymobile/scrcpy#1901]
When I run scrcpy for the Pixel 3a with Android 11 (it was working fine with Android 10), on using command:

scrcpy -s {device} -w

I get this error:

java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:69)
	at com.genymobile.scrcpy.wrappers.ContentProvider.getValue(ContentProvider.java:110)
	at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:126)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:38)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Caused by: java.lang.SecurityException: The authority unknown does not match the one of the contentProvider: settings
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
	at android.content.IContentProvider.call(IContentProvider.java:115)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.content.ContentProvider.validateIncomingAuthority(ContentProvider.java:2505)
	at android.content.ContentProvider.access$200(ContentProvider.java:115)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:511)
	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:295)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:69)
[server] ERROR: Could not invoke method
	at com.genymobile.scrcpy.wrappers.ContentProvider.putValue(ContentProvider.java:122)
	at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:128)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:38)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Caused by: java.lang.SecurityException: The authority unknown does not match the one of the contentProvider: settings
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
	at android.content.IContentProvider.call(IContentProvider.java:115)

**Comment by rom1v** [comment]
Already fixed in `dev`. See #1468.
