### ISSUE TITLE
Cant start up SCRCPY on a windows device.

### ISSUE THREAD

**Issue by OlekFXOfficial** [Genymobile/scrcpy#1905]
### Ack gotta love it when you find something cool, but it does not work, LOL

```
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
C:\Mirror\scrcpy-server: 1 file pushed, 0 skipped. 29.5 MB/s (33622 bytes in 0.001s)
[server] INFO: Device: HUAWEI MAR-LX1A (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2312
WARN: Device disconnected
```

**Running a HUAWEI P30 LITE device, From 2019, If you need all my pc specs or phone specs then go on**

_Quote of the day_
`If you lose a connection, You can always retrieve it back.`

**Comment by rom1v** [comment]
Just read the error message and the suggestion.

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by OlekFXOfficial** [comment]
> Just read the error message and the suggestion.
> 
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

what about this? [server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:157)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:67)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
        at com.genymobile.scrcpy.Server.main(Server.java:133)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
INFO: Initial texture: 1080x2312
WARN: Could not terminate server

**Comment by rom1v** [comment]
```
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
```

Try `scrcpy -m 1024`.
