### ISSUE TITLE
scrcpy don't connect android 11 device

### ISSUE THREAD

**Issue by SlienceJoker** [Genymobile/scrcpy#1950]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: ArchLinux
 - scrcpy version: 1.16
 - installation method: pacman -S scrcpy
 - device model: xiaomi mi 6 (sagit)
 - device rom: sbwml AOSP GMS 11
 - Android version: 11

**Describe the bug**
 use scrcpy connected my device,throw IllegalStateException.

On errors, please provide the output of the console (and `adb logcat` if relevant).
12-03 11:58:26.931  9644  9644 E APM_AudioPolicyManager: onNewAudioModulesAvailableInt: Input device list is empty!

Please paste terminal output in a code block.
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 1.5 MB/s (33622 bytes in 0.021s)
[server] INFO: Device: Xiaomi MI 6 (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 20.2.3
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x1920
WARN: Device disconnected

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by SlienceJoker** [comment]
when I use the command,the bug still not resolved;
my terminal output :
~ >>> scrcpy -m 1920                                                                          
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed... 0 skipped. 190.6 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: Xiaomi MI 6 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 20.2.3
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x1920
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
~ >>> scrcpy -m 1920                                                                       [1]
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed... 0 skipped. 145.4 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: Xiaomi MI 6 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 20.2.3
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x1920
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
~ >>> scrcpy -m 1024                                                                       [1]
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed... 0 skipped. 206.1 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: Xiaomi MI 6 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 20.2.3
INFO: Trilinear filtering enabled
INFO: Initial texture: 576x1024
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
~ >>> scrcpy -m 800                                                                        [1]
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed... 0 skipped. 203.7 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: Xiaomi MI 6 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 20.2.3
INFO: Trilinear filtering enabled
INFO: Initial texture: 448x800
WARN: Device disconnected

**Comment by rom1v** [comment]
So the problem is with your device encoder. Try with another encoder if possible: https://github.com/Genymobile/scrcpy/pull/1827#issuecomment-725933512

**Comment by nalakawula** [comment]
```
┌─[sumar][x240][~]
└─▪ SCRCPY_SERVER_PATH=/home/sumar/Downloads/scrcpy-server scrcpy --encoder _
scrcpy: unrecognized option '--encoder'
┌─[sumar][x240][~]
└─▪ SCRCPY_SERVER_PATH=/home/sumar/Downloads/scrcpy-server scrcpy -v
scrcpy 1.16

dependencies:
 - SDL 2.0.12
 - libavcodec 58.91.100
 - libavformat 58.45.100
 - libavutil 56.51.100
```

**Comment by SlienceJoker** [comment]
thanks
I‘ll try and feedback later。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sumarsono"<notifications@github.com&gt;; 
发送时间: 2020年12月11日(星期五) 上午9:17
收件人: "Genymobile/scrcpy"<scrcpy@noreply.github.com&gt;; 
抄送: "贾志楷"<2036736521@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Genymobile/scrcpy] scrcpy don&#39;t connect android 11 device (#1950)





 ┌─[sumar][x240][~] └─▪ SCRCPY_SERVER_PATH=/home/sumar/Downloads/scrcpy-server scrcpy --encoder _ scrcpy: unrecognized option '--encoder' ┌─[sumar][x240][~] └─▪ SCRCPY_SERVER_PATH=/home/sumar/Downloads/scrcpy-server scrcpy -v scrcpy 1.16 dependencies:  - SDL 2.0.12  - libavcodec 58.91.100  - libavformat 58.45.100  - libavutil 56.51.100

**Comment by imzf** [comment]
scrcpy --encoder _
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...ped. 98.3 MB/s (34482 bytes in 0.000s)
[server] INFO: Device: Xiaomi MI 6 (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
	at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:176)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:77)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:78)
	at com.genymobile.scrcpy.Server.main(Server.java:239)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
[server] ERROR: Try to use one of the available encoders:
[server] ERROR:     scrcpy --encoder-name 'OMX.qcom.video.encoder.avc'
[server] ERROR:     scrcpy --encoder-name 'c2.android.avc.encoder'
[server] ERROR:     scrcpy --encoder-name 'OMX.google.h264.encoder'
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 455.45.01
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x1920
WARN: Device disconnected
scrcpy --encoder OMX.qcom.video.encoder.avc
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...ed. 100.7 MB/s (34482 bytes in 0.000s)
[server] INFO: Device: Xiaomi MI 6 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 455.45.01
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x1920
WARN: Device disconnected
scrcpy --encoder c2.android.avc.encoder
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...ped. 89.5 MB/s (34482 bytes in 0.000s)
[server] INFO: Device: Xiaomi MI 6 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 455.45.01
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x1920
WARN: Device disconnected
scrcpy --encoder OMX.google.h264.encoder
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...ed. 100.4 MB/s (34482 bytes in 0.000s)
[server] INFO: Device: Xiaomi MI 6 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 455.45.01
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x1920

then get stuck

**Comment by rom1v** [comment]
Does recording work with:

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```
?

Also, could you test scrcpy v1.13 (or earlier version), please? (ref #240)

**Comment by imzf** [comment]
> Does recording work with:
> 
> ```
> adb shell screenrecord /sdcard/file.mp4
> adb pull /sdcard/file.mp4
> ```
> 
> ?
work fine
> ```
> adb shell screenrecord /sdcard/file.mp4
> adb pull /sdcard/file.mp4
> /sdcard/file.mp4: 1 file pulled, 0 ski... 13.1 MB/s (111244296 bytes in 8.116s)
> ```
> 
> Also, could you test scrcpy v1.13 (or earlier version), please? (ref #240)


`scrcpy -v`

scrcpy 1.13

dependencies:
 - SDL 2.0.12
 - libavcodec 58.91.100
 - libavformat 58.45.100
 - libavutil 56.51.100

`scrcpy`

INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...ped. 84.4 MB/s (27694 bytes in 0.000s)
[server] INFO: Device: Xiaomi MI 6 (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:93)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:35)
	at com.genymobile.scrcpy.Server.main(Server.java:177)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 455.45.01
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x1920
WARN: Device disconnected

**Comment by rom1v** [comment]
I guess you'll get the same error with v1.13 and `scrcpy -m800`?

I don't know, it's probably an encoder parameter passed by scrcpy which is not correctly supported by your hardware encoder:

https://github.com/Genymobile/scrcpy/blob/d6078cf20244e6651aea5832e6b78b3aa3459766/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L175-L189

**Comment by SlienceJoker** [comment]
Recently I no longer use the archlinux operating system, but I think your guess is correct. After all, my mobile phone ROM is not official, it is produced by a third-party author sbwml, and he also pointed out a bug in the upstream source code of aosp in his blog.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Romain Vimont"<notifications@github.com&gt;; 
发送时间: 2020年12月16日(星期三) 晚上6:19
收件人: "Genymobile/scrcpy"<scrcpy@noreply.github.com&gt;; 
抄送: "贾志楷"<2036736521@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Genymobile/scrcpy] scrcpy don&#39;t connect android 11 device (#1950)





 
I guess you'll get the same error with v1.13 and scrcpy -m800?
 
I don't know, it's probably an encoder parameter passed by scrcpy which is not correctly supported by your hardware encoder:
 
https://github.com/Genymobile/scrcpy/blob/d6078cf20244e6651aea5832e6b78b3aa3459766/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L175-L189

**Comment by imzf** [comment]
> I guess you'll get the same error with v1.13 and `scrcpy -m800`?

**same error**
`crcpy -m800`
INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...pped. 2.1 MB/s (27694 bytes in 0.012s)
[server] INFO: Device: Xiaomi MI 6 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 455.45.01
INFO: Trilinear filtering enabled
INFO: Initial texture: 448x800
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:93)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:35)
	at com.genymobile.scrcpy.Server.main(Server.java:177)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
WARN: Device disconnected
