### ISSUE TITLE
Can't solve Exception on thread Thread[main,5,main]

### ISSUE THREAD

**Issue by RaulMerelli** [Genymobile/scrcpy#1956]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.16
 - installation method: Windows release
 - device model: Zebra ET5X
 - Android version: 6

**Describe the bug**
```
Exception on thread Thread[main,5,main]
```
I already tried to reduce the resolution with -m800 or even -m300, it still crashes. I tried changing USB ports, or even connecting via WiFi, it still crashes, always. I'm able to control and watch the screen without any problem for the firsts 30 seconds (sometimes even less, up to 10s) but then I always get the error. I think it's something related only to this Android device, or at least with the computer, because at home with my Xiaomi Mi8 Lite all worked flawlessly.
I also tried other versions of scrcpy, always getting the same error. Also tried running scrcpy with usb and then local network into a VM, same problems. The computer in the while never reports that device has been disconnected.

adb logcat after crash:

```
12-07 08:58:02.973  2970  2970 E ufoGralloc: perform(16) failed, -38/Function not implemented
12-07 08:58:02.973  2970  2970 E grallocClient: setBufferKeyFrame() failed, -38 (Function not implemented)
12-07 08:58:02.973  2970  2970 D grallocClient: with handle 0xf6e0b000
12-07 08:58:03.450  2970  2970 E ufoGralloc: perform(16) failed, -38/Function not implemented
12-07 08:58:03.450  2970  2970 E grallocClient: setBufferKeyFrame() failed, -38 (Function not implemented)
12-07 08:58:03.450  2970  2970 D grallocClient: with handle 0xf6e0b000
12-07 08:58:03.760  2970  2970 E ufoGralloc: perform(16) failed, -38/Function not implemented
12-07 08:58:03.760  2970  2970 E grallocClient: setBufferKeyFrame() failed, -38 (Function not implemented)
12-07 08:58:03.760  2970  2970 D grallocClient: with handle 0xf3c04d00
12-07 08:58:05.072  4275  4275 I wpa_supplicant: RSSI=-58, BSSID:xx:xx:xx:xx:xx:xx, FREQ=2412
12-07 08:58:06.391  3800  4544 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.symbol.screenblankingsettings/.MainActivity (has extras)} from uid 10023 on display 0
12-07 08:58:06.392  3015  3833 W AudioPort: release: Port UNUSED 2
12-07 08:58:06.393  3015  3833 D AudioIntelHal/AudioPlatformState: setParameters: key value pair android_mode=0;output_devices=0;output_flags=0;output_usecase=0
12-07 08:58:06.393  3015  3833 W AudioIntelHal/AudioPlatformState: clearKeys: Unhandled argument: output_usecase=0
12-07 08:58:06.404  3015  3833 D AudioStream: setStandby: starting output stream
12-07 08:58:06.405  3015  3833 D AudioIntelHal/AudioPlatformState: setParameters: key value pair android_mode=0;output_devices=2;output_flags=2;output_usecase=0
12-07 08:58:06.405  3015  3833 W AudioIntelHal/AudioPlatformState: clearKeys: Unhandled argument: output_usecase=0
12-07 08:58:06.405  3015  3833 D EVENT_THREAD: void CEventThread::trig(void*, uint32_t): in
12-07 08:58:06.405  3015  3833 D EVENT_THREAD: void CEventThread::trig(void*, uint32_t): out
12-07 08:58:06.406  3015  3831 D RouteManager: doReconsiderRouting: Route state:
12-07 08:58:06.406  3015  3831 D RouteManager:  -Previously Enabled Route in Input = <none>
12-07 08:58:06.406  3015  3831 D RouteManager:  -Previously Enabled Route in Output = <none>
12-07 08:58:06.406  3015  3831 D RouteManager:  -Selected Route in Input = <none>
12-07 08:58:06.406  3015  3831 D RouteManager:  -Selected Route in Output = Media|HwCodec0IA
12-07 08:58:06.410  3015  3831 W AudioIntelHal/AudioPlatformState/Pfw: Audio-Instance:         Unable to forward synchronize configurable element /Audio/REALTEK/SOUND_CARD/MIXER/ANALOG/SPEAKER_MIXER/RIGHT/DAC/1/SWITCH: Failed to open mixer control: SPK MIXR DAC R1 Switch
12-07 08:58:06.411  3015  3831 W AudioIntelHal/AudioPlatformState/Pfw: Audio-Instance:         Unable to forward synchronize configurable element /Audio/REALTEK/SOUND_CARD/MIXER/ANALOG/SPEAKER_MIXER/LEFT/DAC/1/SWITCH: Failed to open mixer control: SPK MIXL DAC L1 Switch
12-07 08:58:06.426  3015  3831 D TinyAlsaAudioDevice: open: card (bytcrrt5640, 0)
12-07 08:58:06.426  3015  3831 D TinyAlsaAudioDevice:    config (rate=48000 format=0 channels= 2).
12-07 08:58:06.426  3015  3831 D TinyAlsaAudioDevice:    RingBuffer config: periodSize=240 nbPeriod=2startTh=239 stop Th=480 silence Th=0
12-07 08:58:06.455  3800  3813 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.android.launcher3 (uid 10023)
12-07 08:58:06.481  3800  4482 I ActivityManager: Start proc 8467:com.symbol.screenblankingsettings/1001 for activity com.symbol.screenblankingsettings/.MainActivity
12-07 08:58:06.511  2970  2970 E ufoGralloc: perform(16) failed, -38/Function not implemented
12-07 08:58:06.511  2970  2970 E grallocClient: setBufferKeyFrame() failed, -38 (Function not implemented)
12-07 08:58:06.511  2970  2970 D grallocClient: with handle 0xf3c04d00
12-07 08:58:06.540  3015  3831 D AudioConversion: configure: no convertion required
12-07 08:58:06.540  3015  3831 D RouteManager: doReconsiderRouting: DONE
12-07 08:58:06.541  3015  3831 D EVENT_THREAD: void CEventThread::run() Do poll with timeout: -1
12-07 08:58:06.541  3015  3832 E TinyAlsaStream: getFramesAvailable: Unable to get available frames
12-07 08:58:06.541  3015  3832 E TinyAlsaStream: getFramesAvailable: Unable to get available frames
12-07 08:58:06.560  4605  4859 D         : Surface destroy: ANDROID_NATIVE_WINDOW_MAGIC
12-07 08:58:06.580  8467  8467 W System  : ClassLoader referenced unknown path: /system/app/ScreenBlankingSettings/lib/x86
12-07 08:58:06.700  8467  8467 E ScreenBlanking: connectToService
12-07 08:58:06.703  8467  8467 I ScreenBlanking: Service bind in progress.
12-07 08:58:06.714  6929  6929 V ScreenBlankingService: onBind called
12-07 08:58:06.721  8467  8480 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
12-07 08:58:06.726  8467  8467 E HAL client: No payload in reply
12-07 08:58:06.726  8467  8467 E HAL     : Could not find a HAL module for gralloc
12-07 08:58:06.739  8467  8467 I ufoGralloc: Hello, this is UFO GRALLOC/Intel Corporation
12-07 08:58:06.746  8467  8467 I ScreenBlanking: Service connected: ComponentInfo{com.zebra.screenblankingservice/com.zebra.screenblankingservice.ScreenBlankingService} service: com.zebra.screenblanking.IScreenBlankingService$Stub$Proxy@70067b3
12-07 08:58:06.747  6929  6950 I ScreenBlankingService: getAvailableSources: [Input 1]
12-07 08:58:06.750  8467  8467 I ScreenBlankingSettingsFragment: Refreshing screen blanking...
12-07 08:58:06.751  6929  6951 I ScreenBlankingService: getSourceConfiguration: Input 1 true 1000
12-07 08:58:06.752  6929  6950 I ScreenBlankingService: getEnabled: false
12-07 08:58:06.752  8467  8467 I ScreenBlankingSettingsFragment: Refreshing screen blanking...
12-07 08:58:06.752  6929  6951 I ScreenBlankingService: getSourceConfiguration: Input 1 true 1000
12-07 08:58:06.752  6929  6950 I ScreenBlankingService: getEnabled: false
12-07 08:58:06.780  8467  8480 E HAL client: No payload in reply
12-07 08:58:06.780  8467  8480 E HAL     : Could not find a HAL module for gralloc
12-07 08:58:06.794  8467  8480 I OpenGLRenderer: Initialized EGL, version 1.4
12-07 08:58:06.795  8467  8480 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
12-07 08:58:06.795  8467  8480 D         : droid_create_context : config id = 5 conf->NativeVisualID=1
12-07 08:58:06.795  8467  8480 D         : Pixel Format : HAL_PIXEL_FORMAT_RGBA_8888
12-07 08:58:06.795  8467  8480 I         : Requested context : GLES 2.0
12-07 08:58:06.812  8467  8480 D         : Pixel Format : HAL_PIXEL_FORMAT_RGBA_8888
12-07 08:58:06.823  8467  8480 D skuwa   : Detected device 0F31:13 family 15:9
12-07 08:58:06.825  8467  8480 D         : Pixel Format : HAL_PIXEL_FORMAT_RGBA_8888
12-07 08:58:06.826  2970  6542 E BufferQueueProducer: [com.symbol.screenblankingsettings/com.symbol.screenblankingsettings.MainActivity] connect(P): already connected (cur=1 req=1)
12-07 08:58:06.827  8467  8480 D         : Setting the FBO content dimensions for the first frame as 1920x1200 with a 0 rotation
12-07 08:58:06.848  4366  4366 I GoogleInputMethodServic: GoogleInputMethodService.onFinishInput():3308
12-07 08:58:06.848  4366  4366 I GoogleInputMethodServic: GoogleInputMethodService.onStartInput():1887
12-07 08:58:06.943  3800  3818 I ActivityManager: Displayed com.symbol.screenblankingsettings/.MainActivity: +472ms
12-07 08:58:07.768  2970  2970 E ufoGralloc: perform(16) failed, -38/Function not implemented
12-07 08:58:07.768  2970  2970 E grallocClient: setBufferKeyFrame() failed, -38 (Function not implemented)
12-07 08:58:07.768  2970  2970 D grallocClient: with handle 0xf3c04d00
12-07 08:58:08.093  4275  4275 I wpa_supplicant: RSSI=-59, BSSID:xx:xx:xx:xx:xx:xx, FREQ=2412
12-07 08:58:09.628  3015  3833 D AudioStream: setStandby: stopping output stream
12-07 08:58:09.628  3015  3833 D AudioIntelHal/AudioPlatformState: setParameters: key value pair android_mode=0;output_devices=0;output_flags=0;output_usecase=0
12-07 08:58:09.629  3015  3833 W AudioIntelHal/AudioPlatformState: clearKeys: Unhandled argument: output_usecase=0
12-07 08:58:09.629  3015  3833 D EVENT_THREAD: void CEventThread::trig(void*, uint32_t): in
12-07 08:58:09.630  3015  3833 D EVENT_THREAD: void CEventThread::trig(void*, uint32_t): out
12-07 08:58:09.630  3015  3831 D RouteManager: doReconsiderRouting: Route state:
12-07 08:58:09.630  3015  3831 D RouteManager:  -Previously Enabled Route in Input = <none>
12-07 08:58:09.630  3015  3831 D RouteManager:  -Previously Enabled Route in Output = Media|HwCodec0IA
12-07 08:58:09.630  3015  3831 D RouteManager:  -Selected Route in Input = <none>
12-07 08:58:09.630  3015  3831 D RouteManager:  -Selected Route in Output = <none>
12-07 08:58:09.632  3015  3831 D TinyAlsaAudioDevice: close
12-07 08:58:09.662  3015  3831 W AudioIntelHal/AudioPlatformState/Pfw: Audio-Instance:         Unable to forward synchronize configurable element /Audio/REALTEK/SOUND_CARD/MIXER/ANALOG/SPEAKER_MIXER/RIGHT/DAC/1/SWITCH: Failed to open mixer control: SPK MIXR DAC R1 Switch
12-07 08:58:09.662  3015  3831 W AudioIntelHal/AudioPlatformState/Pfw: Audio-Instance:         Unable to forward synchronize configurable element /Audio/REALTEK/SOUND_CARD/MIXER/ANALOG/SPEAKER_MIXER/LEFT/DAC/1/SWITCH: Failed to open mixer control: SPK MIXL DAC L1 Switch
12-07 08:58:09.666  3015  3831 D RouteManager: doReconsiderRouting: DONE
12-07 08:58:09.667  3015  3831 D EVENT_THREAD: void CEventThread::run() Do poll with timeout: -1
12-07 08:58:09.756  8467  8467 I ScreenBlankingSettingsFragment: Refreshing screen blanking...
12-07 08:58:09.756  6929  6951 I ScreenBlankingService: getSourceConfiguration: Input 1 true 1000
12-07 08:58:09.758  6929  6950 I ScreenBlankingService: getEnabled: false
12-07 08:58:10.787  3015  3833 W AudioPort: release: Port UNUSED 2
12-07 08:58:10.787  3015  3833 D AudioIntelHal/AudioPlatformState: setParameters: key value pair android_mode=0;output_devices=0;output_flags=0;output_usecase=0
12-07 08:58:10.787  3015  3833 W AudioIntelHal/AudioPlatformState: clearKeys: Unhandled argument: output_usecase=0
12-07 08:58:10.788  3800  4546 I ActivityManager: START u0 {act=com.android.systemui.recents.SHOW_RECENTS flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10038 on display 0
12-07 08:58:10.798  3015  3833 D AudioStream: setStandby: starting output stream
12-07 08:58:10.798  3015  3833 D AudioIntelHal/AudioPlatformState: setParameters: key value pair android_mode=0;output_devices=2;output_flags=2;output_usecase=0
12-07 08:58:10.798  3015  3833 W AudioIntelHal/AudioPlatformState: clearKeys: Unhandled argument: output_usecase=0
12-07 08:58:10.799  3015  3833 D EVENT_THREAD: void CEventThread::trig(void*, uint32_t): in
12-07 08:58:10.799  3015  3833 D EVENT_THREAD: void CEventThread::trig(void*, uint32_t): out
12-07 08:58:10.799  3015  3831 D RouteManager: doReconsiderRouting: Route state:
12-07 08:58:10.799  3015  3831 D RouteManager:  -Previously Enabled Route in Input = <none>
12-07 08:58:10.799  3015  3831 D RouteManager:  -Previously Enabled Route in Output = <none>
12-07 08:58:10.799  3015  3831 D RouteManager:  -Selected Route in Input = <none>
12-07 08:58:10.799  3015  3831 D RouteManager:  -Selected Route in Output = Media|HwCodec0IA
12-07 08:58:10.801  3015  3831 W AudioIntelHal/AudioPlatformState/Pfw: Audio-Instance:         Unable to forward synchronize configurable element /Audio/REALTEK/SOUND_CARD/MIXER/ANALOG/SPEAKER_MIXER/RIGHT/DAC/1/SWITCH: Failed to open mixer control: SPK MIXR DAC R1 Switch
12-07 08:58:10.801  3015  3831 W AudioIntelHal/AudioPlatformState/Pfw: Audio-Instance:         Unable to forward synchronize configurable element /Audio/REALTEK/SOUND_CARD/MIXER/ANALOG/SPEAKER_MIXER/LEFT/DAC/1/SWITCH: Failed to open mixer control: SPK MIXL DAC L1 Switch
12-07 08:58:10.805  3015  3831 D TinyAlsaAudioDevice: open: card (bytcrrt5640, 0)
12-07 08:58:10.805  3015  3831 D TinyAlsaAudioDevice:    config (rate=48000 format=0 channels= 2).
12-07 08:58:10.805  3015  3831 D TinyAlsaAudioDevice:    RingBuffer config: periodSize=240 nbPeriod=2startTh=239 stop Th=480 silence Th=0
12-07 08:58:10.836  3015  3831 D AudioConversion: configure: no convertion required
12-07 08:58:10.836  3015  3831 D RouteManager: doReconsiderRouting: DONE
12-07 08:58:10.836  3015  3831 D EVENT_THREAD: void CEventThread::run() Do poll with timeout: -1
12-07 08:58:10.837  3015  3832 E TinyAlsaStream: getFramesAvailable: Unable to get available frames
12-07 08:58:10.837  3015  3832 E TinyAlsaStream: getFramesAvailable: Unable to get available frames
12-07 08:58:10.839  4097  4097 D RecentActivity: Checking Sensor Status
12-07 08:58:10.850  8467  8480 D         : Surface destroy: ANDROID_NATIVE_WINDOW_MAGIC
12-07 08:58:10.860  4097  4352 D         : Pixel Format : HAL_PIXEL_FORMAT_RGBA_8888
12-07 08:58:10.861  2970  2985 E BufferQueueProducer: [com.android.systemui/com.android.systemui.recents.RecentsActivity] connect(P): already connected (cur=1 req=1)
12-07 08:58:10.867  4097  4352 D         : Setting the FBO content dimensions for the first frame as 1920x1200 with a 0 rotation
12-07 08:58:10.934  4366  4366 I GoogleInputMethodServic: GoogleInputMethodService.onFinishInput():3308
12-07 08:58:10.935  4366  4366 I GoogleInputMethodServic: GoogleInputMethodService.onStartInput():1887
12-07 08:58:11.114  4275  4275 I wpa_supplicant: RSSI=-62, BSSID:xx:xx:xx:xx:xx:xx, FREQ=2412
12-07 08:58:11.341  2970  2970 E ufoGralloc: perform(16) failed, -38/Function not implemented
12-07 08:58:11.341  2970  2970 E grallocClient: setBufferKeyFrame() failed, -38 (Function not implemented)
12-07 08:58:11.341  2970  2970 D grallocClient: with handle 0xf3c024b0
12-07 08:58:11.696  2970  2970 E ufoGralloc: perform(16) failed, -38/Function not implemented
12-07 08:58:11.696  2970  2970 E grallocClient: setBufferKeyFrame() failed, -38 (Function not implemented)
12-07 08:58:11.696  2970  2970 D grallocClient: with handle 0xf3c024b0
12-07 08:58:11.867  3800  4457 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.android.launcher3/.Launcher} from uid 10038 on display 0
12-07 08:58:11.875  3800  4005 I ActivityManager: Killing 8467:com.symbol.screenblankingsettings/1001 (adj 9): remove task
12-07 08:58:11.902  3800  4169 D GraphicsStats: Buffer count: 3
12-07 08:58:11.902  3800  3810 I WindowState: WIN DEATH: Window{b186b45 u0 com.symbol.screenblankingsettings/com.symbol.screenblankingsettings.MainActivity}
12-07 08:58:11.917  3800  4474 D ActivityManager: cleanUpApplicationRecord -- 8467
12-07 08:58:11.929  4097  4352 D         : Surface destroy: ANDROID_NATIVE_WINDOW_MAGIC
12-07 08:58:11.930  4605  4859 D         : Pixel Format : HAL_PIXEL_FORMAT_RGBA_8888
12-07 08:58:11.931  2970  4037 E BufferQueueProducer: [com.android.launcher3/com.android.launcher3.Launcher] connect(P): already connected (cur=1 req=1)
12-07 08:58:11.936  4605  4859 D         : Setting the FBO content dimensions for the first frame as 1920x1200 with a 0 rotation
12-07 08:58:11.940  4366  4366 I GoogleInputMethodServic: GoogleInputMethodService.onFinishInput():3308
12-07 08:58:11.940  4366  4366 I GoogleInputMethodServic: GoogleInputMethodService.onStartInput():1887
12-07 08:58:12.202  2970  2970 E ufoGralloc: perform(16) failed, -38/Function not implemented
12-07 08:58:12.202  2970  2970 E grallocClient: setBufferKeyFrame() failed, -38 (Function not implemented)
12-07 08:58:12.202  2970  2970 D grallocClient: with handle 0xf3c04c10
12-07 08:58:12.454  4605  4859 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
12-07 08:58:13.623  3015  3833 W AudioPort: release: Port UNUSED 2
12-07 08:58:13.624  3015  3833 D AudioIntelHal/AudioPlatformState: setParameters: key value pair android_mode=0;output_devices=2;output_flags=2;output_usecase=0
12-07 08:58:13.625  3015  3833 W AudioIntelHal/AudioPlatformState: clearKeys: Unhandled argument: output_usecase=0
12-07 08:58:13.643  4366  4366 I GoogleInputMethodServic: GoogleInputMethodService.onFinishInput():3308
12-07 08:58:13.644  4366  4366 I GoogleInputMethodServic: GoogleInputMethodService.onStartInput():1887
12-07 08:58:13.694  3015  8446 E CODECHAL: vpgSyncSurface: Null pSurface
12-07 08:58:13.695  3015  8445 E mediasdk_omx: mfx_omx_venc_component: AsyncThread[line 3395]: SyncOperation failed - MFX_ERR_DEVICE_FAILED
12-07 08:58:13.695  3015  8445 E mediasdk_omx: mfx_omx_venc_component: AsyncThread[line 3424]: sending ErrorEvent to OMAX client because of error in component
12-07 08:58:13.695  8429  8443 E ACodec  : [OMX.Intel.hw_ve.h264] ERROR(0x80001001)
12-07 08:58:13.695  8429  8443 E ACodec  : signalError(omxError 0x80001001, internalError -2147483648)
12-07 08:58:13.695  8429  8441 E MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
12-07 08:58:13.702  3015  8444 E CODECHAL: vpgSyncSurface: Null pSurface
12-07 08:58:13.703  3015  3015 W GraphicBufferSource: Dropped back down to Loaded without Executing
12-07 08:58:13.703  3015  3015 W GraphicBufferSource: potential buffer leak (acquired 1)
12-07 08:58:13.705  3015  8444 E CODECHAL: vpgDestroyBuffer: Null pBuf
12-07 08:58:13.705  3015  8444 E CODECHAL: vpgDestroyBuffer: Null pBuf
12-07 08:58:13.705  3015  8444 E CODECHAL: vpgDestroyBuffer: Null pBuf
12-07 08:58:13.706  3015  8444 E CODECHAL: vpgDestroyBuffer: Null pBuf
12-07 08:58:13.706  3015  8444 E CODECHAL: vpgDestroyBuffer: Null pBuf
12-07 08:58:13.706  3015  8444 E CODECHAL: vpgDestroyBuffer: Null pBuf
12-07 08:58:13.706  3015  8444 E CODECHAL: vpgDestroyBuffer: Null pBuf
12-07 08:58:13.706  3015  8444 E CODECHAL: vpgDestroyBuffer: Null pBuf
12-07 08:58:13.706  3015  8444 E CODECHAL: vpgDestroyBuffer: Null pBuf
12-07 08:58:13.706  3015  8444 E CODECHAL: vpgDestroyBuffer: Null pBuf
12-07 08:58:13.706  3015  8444 E CODECHAL: vpgDestroyBuffer: Null pBuf
12-07 08:58:13.706  3015  8444 E CODECHAL: vpgDestroyBuffer: Null pBuf
12-07 08:58:13.706  2970  2970 D         : Surface destroy: ANDROID_NATIVE_WINDOW_MAGIC
12-07 08:58:13.706  3015  8444 E CODECHAL: vpgDestroyBuffer: Null pBuf
12-07 08:58:13.725  3015  3837 I mediasdk_omx: mfx_omx_venc_component: Destroyed OMX.Intel.hw_ve.h264
12-07 08:58:13.732  8429  8429 D AndroidRuntime: Shutting down VM
12-07 08:58:13.734  8429  8429 E scrcpy  : Exception on thread Thread[main,5,main]
12-07 08:58:13.734  8429  8429 E scrcpy  : java.lang.IllegalStateException
12-07 08:58:13.734  8429  8429 E scrcpy  :      at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
12-07 08:58:13.734  8429  8429 E scrcpy  :      at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
12-07 08:58:13.734  8429  8429 E scrcpy  :      at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:91)
12-07 08:58:13.734  8429  8429 E scrcpy  :      at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:72)
12-07 08:58:13.734  8429  8429 E scrcpy  :      at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
12-07 08:58:13.734  8429  8429 E scrcpy  :      at com.genymobile.scrcpy.Server.main(Server.java:133)
12-07 08:58:13.734  8429  8429 E scrcpy  :      at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
12-07 08:58:13.734  8429  8429 E scrcpy  :      at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
12-07 08:58:14.136  4275  4275 I wpa_supplicant: RSSI=-62, BSSID:78:8a:20:67:d3:ac, FREQ=2412
12-07 08:58:16.710  3015  3833 D AudioStream: setStandby: stopping output stream
12-07 08:58:16.711  3015  3833 D AudioIntelHal/AudioPlatformState: setParameters: key value pair android_mode=0;output_devices=0;output_flags=0;output_usecase=0
12-07 08:58:16.712  3015  3833 W AudioIntelHal/AudioPlatformState: clearKeys: Unhandled argument: output_usecase=0
12-07 08:58:16.712  3015  3833 D EVENT_THREAD: void CEventThread::trig(void*, uint32_t): in
12-07 08:58:16.712  3015  3833 D EVENT_THREAD: void CEventThread::trig(void*, uint32_t): out
12-07 08:58:16.713  3015  3831 D RouteManager: doReconsiderRouting: Route state:
12-07 08:58:16.713  3015  3831 D RouteManager:  -Previously Enabled Route in Input = <none>
12-07 08:58:16.713  3015  3831 D RouteManager:  -Previously Enabled Route in Output = Media|HwCodec0IA
12-07 08:58:16.713  3015  3831 D RouteManager:  -Selected Route in Input = <none>
12-07 08:58:16.713  3015  3831 D RouteManager:  -Selected Route in Output = <none>
12-07 08:58:16.716  3015  3831 D TinyAlsaAudioDevice: close
12-07 08:58:16.748  3015  3831 W AudioIntelHal/AudioPlatformState/Pfw: Audio-Instance:         Unable to forward synchronize configurable element /Audio/REALTEK/SOUND_CARD/MIXER/ANALOG/SPEAKER_MIXER/RIGHT/DAC/1/SWITCH: Failed to open mixer control: SPK MIXR DAC R1 Switch
12-07 08:58:16.748  3015  3831 W AudioIntelHal/AudioPlatformState/Pfw: Audio-Instance:         Unable to forward synchronize configurable element /Audio/REALTEK/SOUND_CARD/MIXER/ANALOG/SPEAKER_MIXER/LEFT/DAC/1/SWITCH: Failed to open mixer control: SPK MIXL DAC L1 Switch
12-07 08:58:16.753  3015  3831 D RouteManager: doReconsiderRouting: DONE
12-07 08:58:16.753  3015  3831 D EVENT_THREAD: void CEventThread::run() Do poll with timeout: -1
```

**Comment by RaulMerelli** [comment]
After 4 hours searching for more informations I realized that this problem is linked to #1827 , so I downloaded the dev build, and changed Encoder from 'OMX.Intel.hw_ve.h264' to 'OMX.google.h264.encoder'. Now all works fine, but I suggest for all Intel Atoms Devices to start by default with another encoder if available, because the intel one seem to be "faulty".
