### ISSUE TITLE
分辨率超过1920X1080就会出现这个问题

### ISSUE THREAD

**Issue by A9080** [Genymobile/scrcpy#1974]
C:\Users\ai>adb connect 192.168.1.28:5555
already connected to 192.168.1.28:5555
C:\Users\ai>scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
D:\scrcpy-win64-v1.16\scrcpy-server: 1...pped. 3.3 MB/s (33622 bytes in 0.010s)
[server] INFO: Device: OnePlus HD1910 (Android 7.1.2)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2570)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncode
r.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:5
5)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
INFO: Renderer: direct3d
INFO: Initial texture: 2560x1080
WARN: Device disconnected
Press any key to continue...
分辨率超过1920X1080就会出现这个问题；       好像是
android代码中出现Android.os.NetworkOnMainThreadException的错误提示

原因：不允许在主线程中进行网络访问
解决办法：将网络访问的操作单独放到一个线程中new Thread(){  
   @Override  
   public void run()  
   {  
   //把网络访问的代码放在这里     
  }  
}.start(); 
我也不懂，我用的是逍遥模拟器测试的，分辨率调的2560X1080就报错
调1920X1080就没有问题，我希望彻底解决这个问题，而不是降低分辨率来解决，谢谢

**Comment by rom1v** [comment]
In English please :)

**Comment by rom1v** [comment]
>     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

> android代码中出现Android.os.NetworkOnMainThreadException的错误提示

Probably not related to scrcpy.

**Comment by A9080** [comment]
I’m very sorry, I don’t speak English. I dare not use translation software to communicate with you. I am afraid that the translation is not accurate. I sincerely hope that you can solve this problem. It feels like a problem with scrvpy-server.jar.
ERROR: Exception on thread Thread[main,5,main]          Do not allow network access in the main thread
Separate network access operations into a thread，Please take a closer look thanks you

**Comment by yume-chan** [comment]
> 分辨率超过1920X1080就会出现这个问题

This problem happens when resolution is over 1920x1080

> 我用的是逍遥模拟器测试的，分辨率调的2560X1080就报错
> 调1920X1080就没有问题，我希望彻底解决这个问题，而不是降低分辨率来解决，谢谢

I used an emulator for testing, it reports errors when resolution is 2560x1080.

This is no issue when resolution is 1920x1080. I hope you can fix this problem, not workaround by lowering resolution, thanks.

> > android代码中出现Android.os.NetworkOnMainThreadException的错误提示
>
> Probably not related to scrcpy.

I guess OP randomly googled this problem and this is one of the results.

**Comment by rom1v** [comment]
> ERROR: Exception on thread Thread[main,5,main] Do not allow network access in the main thread

NetworkOnMainThreadException is a well known exception when there is I/O on the main thread from an Android app and Strict mode is enabled.

Scrcpy server is not an Android app, there is no "UI" on the Android side, so I/O on the main thread is ok.

On all devices where I tested, this is never a problem on scrcpy. Do you really got `NetworkOnMainThreadException` in scrcpy? I doubt this is the case.

**Comment by A9080** [comment]
I don’t have a good idea. I hope you can read the ideas I wrote. Hello, programmers. Can you develop an Android app and an ipad version? Because the screen projection delay of scrcpy is really small, which is better than that of Android.  The screen is fast, and it also supports reverse operation. In this way, I can cast my mobile phone to the tablet computer and to the Android TV. This way, I will not be used to synchronize the files between the tablet computer and the mobile phone, and use the tablet computer to operate the mobile office.  It will not be stuck because the performance of the tablet is not enough, because the program runs in the mobile phone, the implementation method, the mobile phone is connected to the wireless router, the mobile phone uses the usb cable to turn on the adb wireless connection, and then starts the tablet to connect to the mobile phone to realize Android screen projection  If you cast screen to ipad, when you turn on the full screen mode, ipad becomes Android system, maybe I said it is messy, thank you

**Comment by A9080** [comment]
Then start the tablet and connect the mobile phone to realize the Android screen projection. If the screen is projected to the ipad, when the full screen mode is turned on, the ipad becomes an Android system. Maybe I said it is messy, thank you.
