### ISSUE TITLE
Why there is nothing comes up after I enter scrcpy.exe?

### ISSUE THREAD

**Issue by chengnay** [Genymobile/scrcpy#1993]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: v1.16
 - installation method: Windows release
 - device model: HTC U11
 - Android version: 10

**Describe the bug**
After I execute scrcpy, it will stop after awhile. There is no additional screen pops up. What did I do wrong?

```
E:\Tools\scrcpy-win64-v1.16>scrcpy --max-size 1024
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
E:\Tools\scrcpy-win64-v1.16\scrcpy-server: 1 file pushed, 0 skipped. 13.0 MB/s (33622 bytes in 0.002s)
[server] INFO: Device: HTC HTC_U-3u (Android 9)
```

**Comment by rom1v** [comment]
Because the encoder "blocks".

Just after you start scrcpy, check `adb logcat`.

```bash
adb logcat -c  # clear
scrcpy
adb logcat -d logcat.txt  # post this file
```

Does `screenrecord` work?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

You could test with another encoder, using this version: https://github.com/Genymobile/scrcpy/pull/1827#issuecomment-725933512

**Comment by chengnay** [comment]
@rom1v I tried adb logcat -d logcat.txt after scrcpy, it seems the console is waiting and no file is generated.
screenrecord works.

When I tried using another encoder,

```
E:\Tools\scrcpy-win64-v1.16>scrcpy.exe --encoder _
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
E:\Tools\scrcpy-win64-v1.16\scrcpy-server: 1 file pushed, 0 skipped. 19.3 MB/s (34482 bytes in 0.002s)
[server] INFO: Device: HTC HTC_U-3u (Android 9)
[server] ERROR: Exception on thread Thread[main,5,main]
com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:176)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:77)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:78)
        at com.genymobile.scrcpy.Server.main(Server.java:239)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
[server] ERROR: Try to use one of the available encoders:
[server] ERROR:     scrcpy --encoder-name 'OMX.qcom.video.encoder.avc'
[server] ERROR:     scrcpy --encoder-name 'c2.android.avc.encoder'
[server] ERROR:     scrcpy --encoder-name 'OMX.google.h264.encoder'
```

Both OMX will make the console waiting, but c2.android.avc.encoder will cause illegalArgumentException,
```
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2024)
        at android.media.MediaCodec.configure(MediaCodec.java:1952)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:232)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:78)
        at com.genymobile.scrcpy.Server.main(Server.java:239)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
```

**Comment by rom1v** [comment]
Try with a lower definition (`-m 800`).

**Comment by chengnay** [comment]
@rom1v I tested with v1.16's scrcpy.exe and also another encoder's scrcpy.exe, both did not work.
Same result as before.

**Comment by rom1v** [comment]
Does v1.13 work?

**Comment by chengnay** [comment]
@rom1v Same result as usual

**Comment by rom1v** [comment]
OK, I don't know why the encoder does not produce output then 😕 Probably some encoding parameters not correctly sypported.

> I tried adb logcat -d logcat.txt after scrcpy

Sorry, it's `adb logcat -d > logcat.txt`.

**Comment by chengnay** [comment]
@rom1v Sorry, I miss the >.
[logcat.txt](https://github.com/Genymobile/scrcpy/files/5746688/logcat.txt)

By the way, I need to ctrl+c after scrcpy in order to make adb logcat works, if not it seems the console is into another mode (maybe linked to the device?).
