### ISSUE TITLE
low quality display

### ISSUE THREAD

**Issue by AzuKaOwO** [Genymobile/scrcpy#2019]
i tried
force OpenGl,scaling behavior
none work 

with force OpenGL i get an error:

C:\Users\MY PC.DESKTOP-3N4A5O2>scrcpy --render-driver=opengl
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\Users\---------------\Desktop\Mirror\scrcpy-serve... file pushed, 0 skipped. 36.8 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: HUAWEI MAR-LX1B (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:232)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
INFO: Renderer: opengl
INFO: OpenGL version: 4.5.0 - Build 25.20.100.6444
INFO: Trilinear filtering enabled
INFO: Initial texture: 2312x1080
WARN: Device disconnected

C:\Users\------------->

**Comment by rom1v** [comment]
The error is independent of opengl or not.

> [server] ERROR: The hardware encoder is not able to encode at the given definition.
> [server] ERROR: Try with a lower definition:
> [server] ERROR: scrcpy -m 1024

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

Try to reduce the resolution until it works:
```
scrcpy -m 2048 --render-driver=opengl
```

https://github.com/Genymobile/scrcpy/issues/2016#issuecomment-754718787
