### ISSUE TITLE
Scrcpy crashed on MAC

### ISSUE THREAD

**Issue by silverwolfceh** [Genymobile/scrcpy#2066]
**Environment**
 - OS: MacOS Catalina
 - scrcpy version: 1.17
 - installation method: Brew
 - device model: Xiaomi Redmi K30 5G
 - Android version: 10

**Describe the bug**
I started and connect to adb through wireless successfully.
When I try the command: scrcpy following is output
```
tongvuu@Tongs-MacBook-Pro ~ % scrcpy
2021-01-28 19:27:20.999 scrcpy[9735:43997] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.17_1/share/...ped. 41.8 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: Xiaomi Redmi K30 5G (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe
	at android.media.MediaCodec.native_setup(Native Method)
	at android.media.MediaCodec.<init>(Unknown Source:104)
	at android.media.MediaCodec.createEncoderByType(Unknown Source:3)
	at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:179)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:77)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(Unknown Source:24)
2021-01-28 19:27:21.649 scrcpy[9735:43997] INFO: Renderer: metal
2021-01-28 19:27:21.653 scrcpy[9735:43997] INFO: Initial texture: 1080x2400
2021-01-28 19:27:22.023 scrcpy[9735:43997] WARN: Device disconnected```

**Comment by rom1v** [comment]
Try with a lower definition: `scrcpy -m800`.

**Comment by silverwolfceh** [comment]
Thanks, but it still same with more error

'''tongvuu@Tongs-MacBook-Pro ~ % adb devices 
List of devices attached
192.168.1.4:5555	device

tongvuu@Tongs-MacBook-Pro ~ % scrcpy -m800
2021-01-28 19:34:49.734 scrcpy[9804:47029] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.17_1/share/scrcpy... 0 skipped. 2.9 MB/s (34930 bytes in 0.012s
[server] INFO: Device: Xiaomi Redmi K30 5G (Android 10)
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:36)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:169)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:173)
	at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:180)
	at com.genymobile.scrcpy.Device.injectKeycode(Device.java:184)
	at com.genymobile.scrcpy.Controller.control(Controller.java:58)
	at com.genymobile.scrcpy.Server$2.run(Server.java:100)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.RuntimeException: Bad file descriptor
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Unknown Source:108)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(Unknown Source:34)
	... 9 more
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe
	at android.media.MediaCodec.native_setup(Native Method)
	at android.media.MediaCodec.<init>(Unknown Source:104)
	at android.media.MediaCodec.createEncoderByType(Unknown Source:3)
	at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:179)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:77)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(Unknown Source:24)
2021-01-28 19:34:50.318 scrcpy[9804:47029] INFO: Renderer: metal
2021-01-28 19:34:50.322 scrcpy[9804:47029] INFO: Initial texture: 360x800
2021-01-28 19:34:50.667 scrcpy[9804:47029] WARN: Device disconnected'''

**Comment by rom1v** [comment]
List the encoders and try with another encoder: https://github.com/Genymobile/scrcpy#encoder

**Comment by silverwolfceh** [comment]
I tried with h264, no more crash but device disconnected right way.
I enable the adb on my rooted phone

`scrcpy -s 192.168.1.4:1234 --encoder OMX.qcom.video.encoder.h264
2021-01-28 21:42:04.398 scrcpy[10509:82980] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.17_1/share/scrcpy...0 skipped. 58.6 MB/s (34930 bytes in 0.001s
[server] INFO: Device: Xiaomi Redmi K30 5G (Android 10)
2021-01-28 21:42:04.828 scrcpy[10509:82980] INFO: Renderer: metal
2021-01-28 21:42:04.832 scrcpy[10509:82980] INFO: Initial texture: 1080x2400
2021-01-28 21:42:05.172 scrcpy[10509:82980] WARN: Device disconnected`

**Comment by yinbohang** [comment]
> 我尝试使用 h264，不再发生崩溃，但设备以正确方式断开连接。 我在 root 后的手机上启用 adb
> 
> ```
> scrcpy -s 192.168.1.4:1234 --encoder OMX.qcom.video.encoder.h264
> 2021-01-28 21:42:04.398 scrcpy[10509:82980] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
> /usr/local/Cellar/scrcpy/1.17_1/share/scrcpy...0 skipped. 58.6 MB/s (34930 bytes in 0.001s
> [server] INFO: Device: Xiaomi Redmi K30 5G (Android 10)
> 2021-01-28 21:42:04.828 scrcpy[10509:82980] INFO: Renderer: metal
> 2021-01-28 21:42:04.832 scrcpy[10509:82980] INFO: Initial texture: 1080x2400
> 2021-01-28 21:42:05.172 scrcpy[10509:82980] WARN: Device disconnected
> ```

Did you solve it? I also encountered the same problem
