### ISSUE TITLE
ERROR: Could not open video stream

### ISSUE THREAD

**Issue by xcepo** [Genymobile/scrcpy#2068]
ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:135)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:62)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:22)
        at com.genymobile.scrcpy.Server.main(Server.java:78)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
INFO: Initial texture: 1080x2304
WARN: Cannot terminate server

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception
