### ISSUE TITLE
bug [server] ERROR: Exception on thread Thread

### ISSUE THREAD

**Issue by Leminh8686** [Genymobile/scrcpy#2070]
how to fix 
C:\Users\Admin\Downloads\scrcpy-win64-v1.15\scrcpy-server:... file pushed, 0 skipped. 24.7 MB/s (33618 bytes in 0.001s)
[server] INFO: Device: vsmart Star (Android 9)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:30)
        at com.genymobile.scrcpy.Device.<init>(Device.java:57)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:23)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:17)
        ... 5 more
Press any key to continue...

**Comment by CongAn** [comment]
我遇到一样的问题，系统是MIUI 12.0.11(Android 10)
```
➜ scrcpy   
2021-01-30 15:01:17.121 scrcpy[39801:905199] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.17_1/share...ed. 93.6 MB/s (34930 bytes in 0.000s
[server] INFO: Device: Xiaomi M2010J19SC (Android 10)
2021-01-30 15:01:17.643 scrcpy[39801:905199] INFO: Renderer: metal
2021-01-30 15:01:17.646 scrcpy[39801:905199] INFO: Initial texture: 1080x2336
2021-01-30 15:01:18.013 scrcpy[39801:905199] WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2024)
        at android.media.MediaCodec.configure(MediaCodec.java:1952)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:232)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
2021-01-30 15:01:19.016 scrcpy[39801:905199] WARN: Killing the server...
```

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/issues/932

**Comment by chenmengyi2** [comment]
how do you fix the bug?
