### ISSUE TITLE
Unable to start scrcpy on Windows 7 for Huawei Nova 3i

### ISSUE THREAD

**Issue by sixfeetoff** [Genymobile/scrcpy#2073]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 7 
 - scrcpy version: scrcpy-win32-v1.17
 - installation method: installed hi Suite for Huawei, ADB installer
 - device model: Huawei Nova 3i ( INE-LX2)
 - Android version: 9

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\Users\User\Desktop\ray2x\scrcpy-ser...ped. 31.6 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: HUAWEI INE-LX2 (Android 9)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1967)
        at android.media.MediaCodec.configure(MediaCodec.java:1896)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:232)

        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncode
r.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:6
0)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
[server] ERROR: The hardware encoder is not able to encode at the given definiti
on.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
Exit due to uncaughtException in main thread:
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
WARN: Device disconnected
Press any key to continue . . .
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception
