### ISSUE TITLE
scrcpy not working

### ISSUE THREAD

**Issue by scribbi** [Genymobile/scrcpy#2081]
**Environment**
 - OS: [windows 10]
 - scrcpy version: [e.g. 1.17]
 - installation method: [zip file]
 - device model: Umidigi A5 Pro
 - Android version: [9]

**Describe the bug**
every time I try and use scrcpy it comes up with an error message and doesn't show my screen. please help
```
C:\Users\myuser>scrcpy
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 17.3 MB/s (34930 bytes in 0.002s)
[server] INFO: Device: UMIDIGI A5_Pro (Android 9)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2280
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:113)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:94)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)`
and my device is always plugged in
```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by scribbi** [comment]
Thank you
