### ISSUE TITLE
Having an issue on screen casting my Poco M3

### ISSUE THREAD

**Issue by Drewnism** [Genymobile/scrcpy#2096]
Please help.

I am having an issue with screencasting my Poco M3. When I launch the scrcpy app, it will not run. Please help.

![Untitled](https://user-images.githubusercontent.com/77522079/107169782-acb13580-69f9-11eb-958a-05190baeb2c7.png)

**Comment by Blacklite01** [comment]
We have the same problem please help!

**Comment by rom1v** [comment]
Try with another encoder:
https://github.com/Genymobile/scrcpy#encoder

**Comment by Blacklite01** [comment]
how??

**Comment by 7wells** [comment]
I know that this is several months ago, but maybe someone stumbles over it. As @rom1v already kindly pointed out (including the link), below is what you can do (e.g. in Windows' PowerShell). The _ (underscore) after the --encoder parameter is a wrong encoder by intention. If you then look closely at the output, scrcpy is clever and tells you which encoders your device has; in the below example, 3 different ones. Try one after the other by providing its name after the --encoder parameter.
```
PS C:\Windows\system32> scrcpy --encoder _
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\ProgramData\scoop\apps\scrcpy\current\scrcpy-server: 1 file pushed, 0 skipped. 33.0 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: Xiaomi M2010J19CG (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:177)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:78)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
[server] ERROR: Try to use one of the available encoders:
[server] ERROR:     scrcpy --encoder 'OMX.qcom.video.encoder.avc'
[server] ERROR:     scrcpy --encoder 'c2.android.avc.encoder'
[server] ERROR:     scrcpy --encoder 'OMX.google.h264.encoder'
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
WARN: Device disconnected
```
HTH

**Comment by LinuxDark** [comment]
I prube with version 1.22 and still the problem for connect from Pc, Any Idea ??

**Comment by rom1v** [comment]
And wIth #2990?
