### ISSUE TITLE
android 4.0.4 exception

### ISSUE THREAD

**Issue by taba217** [Genymobile/scrcpy#2100]
Downloads\Compressed\scrcpy-win64-v1.17\scrcpy-server: 1 file pushed. 3.1 MB/s (34930 bytes in 0.011s)
adb.exe: error: closed
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
[server] INFO: Device: alps X401 (Android 4.0.4)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.ClassNotFoundException: android.hardware.display.IDisplayManager$Stub
        at com.genymobile.scrcpy.wrappers.ServiceManager.getService(ServiceManager.java:39)
        at com.genymobile.scrcpy.wrappers.ServiceManager.getDisplayManager(ServiceManager.java:52)
        at com.genymobile.scrcpy.Device.<init>(Device.java:57)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:24)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.finishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:238)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: android.hardware.display.IDisplayManager$Stub
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:217)
        at java.lang.Class.forName(Class.java:172)
        at com.genymobile.scrcpy.wrappers.ServiceManager.getService(ServiceManager.java:36)
        ... 7 more
Caused by: java.lang.NoClassDefFoundError: android/hardware/display/IDisplayManager$Stub
        ... 11 more
Caused by: java.lang.ClassNotFoundException: android.hardware.display.IDisplayManager$Stub
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
        ... 11 more

**Comment by rom1v** [comment]
Scrcpy requires Android 5.0 at least.
