### ISSUE TITLE
Could not send video packet on android tv

### ISSUE THREAD

**Issue by Matthew-Bonner** [Genymobile/scrcpy#2142]
Trying to use on my android tv and I get the following:
C:\Users\Matt\Downloads\scrcpy-win64-v1.17>scrcpy
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\Users\Matt\Downloads\scrcpy-win64-v1.17\scrcpy-server: 1 file pushed, 0 skipped. 41.1 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: Sony BRAVIA 4K GB ATV3 (Android 8.0.0)
INFO: Renderer: direct3d
INFO: Initial texture: 1920x1080
ERROR: Could not send video packet: -1094995529
ERROR: Could not process frame
WARN: Device disconnected

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/1287#issuecomment-743023526

**Comment by karlic** [comment]
Posting here as this seems to be the open issue dealing with this. I've tried `--renderer`, but I just get `scrcpy: option '--encoder' requires an argument`.

Connecting to FireTV Cube 2nd Gen Updated software today from MacBook Air (M1, 2020) Big Sur 11.2 (20D64) **via VPN**

Note that below there is a -1094995529 **AND** -22 error.

Anything else I can do to help?

adb disconnect; adb connect 10.200.200.9:5555; scrcpy -b2M -m800 --max-fps 25
disconnected everything
connected to 10.200.200.9:5555
2021-03-09 22:54:24.851 scrcpy[6478:312172] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/opt/homebrew/Cellar/scrcpy/1.17_1/sha...pped. 8.8 MB/s (34930 bytes in 0.004s)
[server] INFO: Device: Amazon AFTR (Android 9)
2021-03-09 22:54:27.333 scrcpy[6478:312172] INFO: Renderer: metal
2021-03-09 22:54:27.336 scrcpy[6478:312172] INFO: Initial texture: 800x448
2021-03-09 22:56:24.341 scrcpy[6478:312281] ERROR: Could not send video packet: -1094995529
2021-03-09 22:56:24.341 scrcpy[6478:312281] ERROR: Could not process frame
2021-03-09 22:56:24.344 scrcpy[6478:312172] WARN: Device disconnected
➜  ~ adb disconnect; adb connect 10.200.200.9:5555; scrcpy -b2M -m800 --max-fps 25
disconnected everything
connected to 10.200.200.9:5555
2021-03-09 23:06:28.664 scrcpy[6544:318209] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/opt/homebrew/Cellar/scrcpy/1.17_1/sha...pped. 8.1 MB/s (34930 bytes in 0.004s)
[server] INFO: Device: Amazon AFTR (Android 9)
2021-03-09 23:06:31.533 scrcpy[6544:318209] INFO: Renderer: metal
2021-03-09 23:06:31.535 scrcpy[6544:318209] INFO: Initial texture: 800x448
2021-03-09 23:10:02.321 scrcpy[6544:318297] ERROR: Could not send video packet: -1094995529
2021-03-09 23:10:02.321 scrcpy[6544:318297] ERROR: Could not process frame
2021-03-09 23:10:02.323 scrcpy[6544:318209] WARN: Device disconnected
➜  ~ adb disconnect; adb connect 10.200.200.9:5555; scrcpy -b2M -m800 --max-fps 25
disconnected everything
connected to 10.200.200.9:5555
2021-03-09 23:10:09.029 scrcpy[6562:319369] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/opt/homebrew/Cellar/scrcpy/1.17_1/sha...pped. 6.7 MB/s (34930 bytes in 0.005s)
[server] INFO: Device: Amazon AFTR (Android 9)
2021-03-09 23:10:11.905 scrcpy[6562:319369] INFO: Renderer: metal
2021-03-09 23:10:11.907 scrcpy[6562:319369] INFO: Initial texture: 800x448
2021-03-09 23:11:34.822 scrcpy[6562:319472] ERROR: Could not send video packet: -1094995529
2021-03-09 23:11:34.822 scrcpy[6562:319472] ERROR: Could not process frame
2021-03-09 23:11:34.848 scrcpy[6562:319369] WARN: Device disconnected
2021-03-09 23:11:35.854 scrcpy[6562:319369] WARN: Killing the server...
➜  ~ adb disconnect; adb connect 10.200.200.9:5555; scrcpy -b2M -m800 --max-fps 25
disconnected everything
connected to 10.200.200.9:5555
2021-03-09 23:12:42.723 scrcpy[6589:320524] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/opt/homebrew/Cellar/scrcpy/1.17_1/sha...pped. 8.7 MB/s (34930 bytes in 0.004s)
[server] INFO: Device: Amazon AFTR (Android 9)
2021-03-09 23:12:45.928 scrcpy[6589:320524] INFO: Renderer: metal
2021-03-09 23:12:45.931 scrcpy[6589:320524] INFO: Initial texture: 800x448
2021-03-09 23:16:24.493 scrcpy[6589:320599] ERROR: Could not send video packet: -22
2021-03-09 23:16:24.493 scrcpy[6589:320599] ERROR: Could not process frame
2021-03-09 23:16:24.494 scrcpy[6589:320524] WARN: Device disconnected
2021-03-09 23:16:25.509 scrcpy[6589:320524] WARN: Killing the server...

**Comment by rom1v** [comment]
> but I just get `scrcpy: option '--encoder' requires an argument`.

https://github.com/Genymobile/scrcpy#encoder

**Comment by karlic** [comment]
@rom1v Thank you for the suggestion, the suggested encoder appears to be working.

NOTE, though that the error message suggests `scrcpy --encoder-name 'OMX.amlogic.video.encoder.avc' `
(I believe `--encoder-name` should be `--encoder`)

```
➜  ~ scrcpy --encoder _
2021-03-12 22:19:22.679 scrcpy[2834:117796] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/opt/homebrew/Cellar/scrcpy/1.17_1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 9.4 MB/s (34930 bytes in 0.004s)
[server] INFO: Device: Amazon AFTR (Android 9)
[server] ERROR: Exception on thread Thread[main,5,main]
com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
	at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:176)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:77)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
[server] ERROR: Try to use one of the available encoders:
[server] ERROR:     scrcpy --encoder-name 'OMX.amlogic.video.encoder.avc'

```

**Comment by karlic** [comment]
Hmm, I spoke too soon:

```
➜  ~ adb disconnect; adb connect 10.200.200.9:5555; scrcpy -b2M -m800 --max-fps 25 --encoder 'OMX.amlogic.video.encoder.avc' 
disconnected everything
connected to 10.200.200.9:5555
2021-03-12 22:21:37.512 scrcpy[2873:118878] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/opt/homebrew/Cellar/scrcpy/1.17_1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 9.0 MB/s (34930 bytes in 0.004s)
[server] INFO: Device: Amazon AFTR (Android 9)
2021-03-12 22:21:40.349 scrcpy[2873:118878] INFO: Renderer: metal
2021-03-12 22:21:40.352 scrcpy[2873:118878] INFO: Initial texture: 800x448
2021-03-12 22:25:52.464 scrcpy[2873:118982] ERROR: Could not send video packet: -1094995529
2021-03-12 22:25:52.464 scrcpy[2873:118982] ERROR: Could not process frame
2021-03-12 22:25:52.465 scrcpy[2873:118878] WARN: Device disconnected
```

**Comment by rom1v** [comment]
Yes, thank you for the report, I noticed that 2 days ago, and fixed on `dev`: https://github.com/Genymobile/scrcpy/commit/429fdef04fbc40da9050f4b008a438feb56d3450
