### ISSUE TITLE
在红米note9上报错

### ISSUE THREAD

**Issue by clbDream** [Genymobile/scrcpy#2182]
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
F:\屏幕分享\scrcpy-server: 1 file pushed, 0 skipped. 1.2 MB/s (34930 bytes in 0.028s)
[server] INFO: Device: Xiaomi M2010J19SC (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2024)
        at android.media.MediaCodec.configure(MediaCodec.java:1952)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:232)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
WARN: Device disconnected
WARN: Killing the server...
请按任意键继续. . .

**Comment by rom1v** [comment]
Duplicate of #833.

Maybe you could try with another [encoder](https://github.com/Genymobile/scrcpy#encoder).
