### ISSUE TITLE
SCRCPY PROBLEM HOW TO FIX THIS

### ISSUE THREAD

**Issue by DDDSHBZ** [Genymobile/scrcpy#2198]
Microsoft Windows [Version 10.0.19042.631]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Windows\system32>scrcpy
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
c:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 52.6 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: OPPO CPH1723 (Android 7.1.1)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2160
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2583)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:113)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:94)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:402)

C:\Windows\system32>

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception
