### ISSUE TITLE
Cannot use Scrcpy with Android 12 preview

### ISSUE THREAD

**Issue by VincentTe** [Genymobile/scrcpy#2207]
Hello ! 

I don't know if it's a known issue but since I upgraded my pixel to Android12, I have this error:

2021-03-19 10:18:34.439 scrcpy[1596:28917] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.17_1/share/scrcpy/scrcpy-s... pushed, 0 skipped. 12.6 MB/s (34930 bytes in 0.003s)
[server] INFO: Device: Google Pixel 5 (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3057)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2156)
	... 9 more
2021-03-19 10:18:35.211 scrcpy[1596:28917] INFO: Renderer: metal
2021-03-19 10:18:35.214 scrcpy[1596:28917] INFO: Initial texture: 1080x2336
2021-03-19 10:18:35.561 scrcpy[1596:28917] WARN: Device disconnected
2021-03-19 10:18:36.563 scrcpy[1596:28917] WARN: Killing the server...

Even if it says "Device: Google Pixel 5 (Android 11)", it's an Android 12 device.

**Comment by bunjix** [comment]
Same issue. Its same issue either with Android 12 DP1 and DP2.

**Comment by rom1v** [comment]
Thank you for your report.

See #2129.
