### ISSUE TITLE
Scrcpy is not working

### ISSUE THREAD

**Issue by AndrejFeher09** [Genymobile/scrcpy#2221]
Environment:
 - OS: Windows 10
 - Scrcpy version: 1.17
 - Installation method: Windows release
 - Device model: C20
 - Android version: 10

Bug:

Scrcpy is not working

Cmd:

INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\Users\andre\Downloads\Android\Screen mirroring and cont... file pushed, 0 skipped. 14.1 MB/s (34930 bytes in 0.002s)
[server] INFO: Device: Foxconn C20 (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:113)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:94)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
INFO: Renderer: direct3d
INFO: Initial texture: 1200x1920
WARN: Device disconnected
Press any key to continue . . .

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception
