### ISSUE TITLE
Spacebar, arrows and enter key not working

### ISSUE THREAD

**Issue by rayfoss** [Genymobile/scrcpy#2222]
**Environment**
 - OS: ChromeOS
 - scrcpy version: app.webadb.com
 - installation method: Chrome
 - device model: Pixel 4a 5G
 - Android version: 11

**Description**
Typing space, arrow or enter are not received by android.

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
03-28 20:30:09.201 30464 30464 E AndroidRuntime: FATAL EXCEPTION: main
03-28 20:30:09.201 30464 30464 E AndroidRuntime: PID: 30464
03-28 20:30:09.201 30464 30464 E AndroidRuntime: com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
03-28 20:30:09.201 30464 30464 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:176)
03-28 20:30:09.201 30464 30464 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:77)
03-28 20:30:09.201 30464 30464 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
03-28 20:30:09.201 30464 30464 E AndroidRuntime:        at com.genymobile.scrcpy.Server.scrcpy(Server.java:78)
03-28 20:30:09.201 30464 30464 E AndroidRuntime:        at com.genymobile.scrcpy.Server.main(Server.java:239)
03-28 20:30:09.201 30464 30464 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-28 20:30:09.201 30464 30464 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
```

**Comment by rayfoss** [comment]
I built it from on a chromebook and it works fine when I'm not using the online app's version of the client... so... closing as it's an issue with the clients' implementation.

I built it on stock Termina's default Debian buster image, Penguin. The performance is really good... latency seems a little higher though. I don't have snapd, I don't think it comes with Buster, my experience with the graphics performance has been from aweful to completely broken... I completely removed it and banned snapd. I've had no issues with Flatpaks, gimp runs great on it.
