### ISSUE TITLE
wrong with GOME U9

### ISSUE THREAD

**Issue by gitthehit** [Genymobile/scrcpy#2227]
scrcpy-win64-v1.17\scrcpy-server:... file pushed, 0 skipped. 30.4 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: Techain GOME_U9 (Android 8.1.0)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2637)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:113)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:94)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2240
WARN: Device disconnected

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by gitthehit** [comment]
Thank you!The problem has been solved.
