### ISSUE TITLE
scrcpy not working on ONYX Max3

### ISSUE THREAD

**Issue by nandbert** [Genymobile/scrcpy#2234]
- [v] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [v] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 18.04.5 LTS (Bionic Beaver)
 - scrcpy version: 1.17
 - installation method: snap
 - device model: ONYX Max 3
 - Android version: 9

```
$ scrcpy -v
scrcpy 1.17

dependencies:
 - SDL 2.0.8
 - libavcodec 57.107.100
 - libavformat 57.83.100
 - libavutil 55.78.100
```

**Describe the bug**

Nothing is shown, scrcpy is not even opening a window. 

Sometimes it just hangs:

```
$ scrcpy -V debug
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
DEBUG: Using server: /usr/local/share/scrcpy/scrcpy-server
/usr/local/share/scrcpy/scrcpy-server:...shed. 3.4 MB/s (34930 bytes in 0.010s)
DEBUG: Screensaver enabled
[server] INFO: Device: ONYX Max3 (Android 9)
DEBUG: Starting stream thread
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 20.0.8
INFO: Trilinear filtering enabled
INFO: Initial texture: 1648x2200
[server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'
^CDEBUG: Server terminated
DEBUG: User requested to quit
```

Sometimes it terminates itself with an error
```
DEBUG: End of frames
DEBUG: Receiver stopped
[server] DEBUG: Device message sender stopped
[server] DEBUG: Controller stopped
DEBUG: Video stream stopped
WARN: Device disconnected
DEBUG: quit...
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:113)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:94)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
DEBUG: Server terminated
```
A logcat is here: https://gist.github.com/nandbert/3dadbf92e63d5129008bfa8ef9c8a74d

I have tried this earlier with scrcpy 1.16 and 1.12, same effect. I have also tried lower resolutions and both available encoders w/o success.

Some people reported the same issue in the comments of #1293 which is IMHO the wrong place. There was no solution and no logcat posted so far. But #1293 contains evidence that scrcpy is working on Max 2, so e-ink devices seem to be no problem in general.

**Comment by nandbert** [comment]
Update: It is working now with the latest Max3 FW version (2021-04-07_...)
