### ISSUE TITLE
Creating virtual displays (FLAG_PRESENTATION?).

### ISSUE THREAD

**Issue by twaik** [Genymobile/scrcpy#2242]
- [X] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
It looks like Android allows us to launch applications on external displays without mirroring, but it is impossible with scrcpy. It does not create any display, it copies layerstack content to PC. For this feature we need to create virtual presentation display.

**Describe the solution you'd like**
It will be very useful to use DisplayManager.createVirtualDisplay. I tried to implement it but failed. My solution used a lot of reflection and failed on non-existent methods when tried to reflect android.hardware.display.VirtualDisplayConfig's constructor. I can not implement it.

**Describe alternatives you've considered**
We can use both adb application and Android app for mirroring sound and creating fake display for mirroring it with scrcpy. I do not see another solutions.

**Additional context**
This feature will allow us to start applications directly on PC's screen and keep device's screen free.

**Comment by gaussandhisgun** [comment]
if your android device has android 10+, there are a workaround for this for now: github.com/gaussandhisgun/scrcpy-appcast (works on Linux and Cygwin)

**Comment by twaik** [comment]
@rom1v **gaussandhisgun's** workaround looks good. Can you please add this option to scrcpy?
It can be option like "--show-touches", previous value of global "overlay_display_devices" is stored during initialization, switched on while process is running and restored back on exit. Also this option can fix displayId to simulated display's one.

**Comment by twaik** [comment]
@rom1v Hi. I've seen you can get [real Androud Context](https://github.com/Genymobile/scrcpy/blob/07a85b7c94fc519c4950a12d7c992f51117b7e81/server/src/main/java/com/genymobile/scrcpy/Workarounds.java#L67) inside application. Can we try to obtain `android.hardware.display.DisplayManager` instance using constructor `DisplayManager(Context context)`? It will allow us to create virtual display with flags `VIRTUAL_DISPLAY_FLAG_PUBLIC | VIRTUAL_DISPLAY_FLAG_PRESENTATION | VIRTUAL_DISPLAY_FLAG_SECURE | VIRTUAL_DISPLAY_FLAG_CAN_SHOW_WITH_INSECURE_KEYGUARD | VIRTUAL_DISPLAY_FLAG_SHOULD_SHOW_SYSTEM_DECORATIONS | VIRTUAL_DISPLAY_FLAG_TRUSTED`. This set of flags willallow us to create Presentation display with an ability to show Android 10 desktop mode without secure content restrictions and Android framework will route external keyboard and mouse input events to this display.

**Comment by rom1v** [comment]
@twaik It's not a "real" Android context. It's an instance of `Context`, but it's very partial, and many things will fail if you use that instance.

I never managed to build a real `Context`, it seems difficult.

**Comment by twaik** [comment]
I know it is partial, but `DisplayManager` uses only following functions:
```
Context.getPackageName()
Context.getOpPackageName()
Context.getUserId()
Context.getDisplayId()
Context.getResources() //Only if displayId == Context.getDisplayId()
```

I do not think it is impossible to fill this info.

**Comment by twaik** [comment]
Ok, I tried to. It fails because package `com.android.shell` did not request `android.permission.CAPTURE_VIDEO_OUTPUT` permission. It throws this: 
```
java.lang.SecurityException: Requires CAPTURE_VIDEO_OUTPUT or CAPTURE_SECURE_VIDEO_OUTPUT permission, or an appropriate MediaProjection token in order to create a screen sharing virtual display.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
	at android.os.Parcel.createException(Parcel.java:2369)
	at android.os.Parcel.readException(Parcel.java:2352)
	at android.os.Parcel.readException(Parcel.java:2294)
	at android.hardware.display.IDisplayManager$Stub$Proxy.createVirtualDisplay(IDisplayManager.java:1843)
	at android.hardware.display.DisplayManagerGlobal.createVirtualDisplay(DisplayManagerGlobal.java:606)
	at android.hardware.display.DisplayManagerGlobal.createVirtualDisplay(DisplayManagerGlobal.java:576)
	at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:1409)
	at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:1384)
	at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:1329)
	at com.genymobile.scrcpy.Server.fillAppInfo(Server.java:362)
	at com.genymobile.scrcpy.Server.main(Server.java:260)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:403)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.display.DisplayManagerService$BinderService.createVirtualDisplay(DisplayManagerService.java:3397)
	at android.hardware.display.IDisplayManager$Stub.onTransact(IDisplayManager.java:850)
	at android.os.Binder.execTransactInternal(Binder.java:1190)
	at android.os.Binder.execTransact(Binder.java:1159)
```

Also we can not grant this permission
```
$ adb shell pm grant com.android.shell android.permission.CAPTURE_VIDEO_OUTPUT

Exception occurred while executing 'grant':
java.lang.SecurityException: Package com.android.shell has not requested permission android.permission.CAPTURE_VIDEO_OUTPUT
	at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:453)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1538)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1492)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1484)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2325)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:259)
	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
	at android.os.ShellCommand.exec(ShellCommand.java:44)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26546)
	at android.os.Binder.shellCommand(Binder.java:965)
	at android.os.Binder.onTransact(Binder.java:839)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5206)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5247)
	at android.os.Binder.execTransactInternal(Binder.java:1195)
	at android.os.Binder.execTransact(Binder.java:1159)
```
```
$ adb shell appops set com.android.shell CAPTURE_VIDEO_OUTPUT allow
Error: Unknown operation string: CAPTURE_VIDEO_OUTPUT
$ adb shell appops set com.android.shell CAPTURE_SECURE_VIDEO_OUTPUT allow
Error: Unknown operation string: CAPTURE_SECURE_VIDEO_OUTPUT
```

Also we can not pretend to be another package (that is not called "`com.android.shell`") because system services check identity using `Binder.getCallingUid()` function.
Looks like the only way is to obtain MediaProjection another way.

**Comment by twaik** [comment]
Looks like it is impossible to create virtual display or sound capture without privilegied or system app with `android.permission.MANAGE_MEDIA_PROJECTION` or `android.permission.CAPTURE[_SECURE]_[VIDEO/AUDIO]_OUTPUT`. Android Framework blocks all attempts to create projections without using public APIs. 
Issue is closed.
