### ISSUE TITLE
raise errror after touch click  display screen on pc

### ISSUE THREAD

**Issue by zhoushuoqi** [Genymobile/scrcpy#2250]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

Android 8.1.0

display screen is ok, but trying to control device from pc raise an error:

INFO: Renderer: direct3d
INFO: Initial texture: 2608x720
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: injectInputEvent [class android.view.InputEvent, int]
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getMethod(Class.java:1690)
        at com.genymobile.scrcpy.wrappers.InputManager.getInjectInputEventMethod(InputManager.java:28)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:35)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:169)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:173)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:215)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:94)
        at com.genymobile.scrcpy.Controller.control(Controller.java:71)
        at com.genymobile.scrcpy.Server$2.run(Server.java:100)
        at java.lang.Thread.run(Thread.java:764)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: injectInputEvent [class android.view.InputEvent, int]
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getMethod(Class.java:1690)
        at com.genymobile.scrcpy.wrappers.InputManager.getInjectInputEventMethod(InputManager.java:28)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:35)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:169)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:173)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:215)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:94)
        at com.genymobile.scrcpy.Controller.control(Controller.java:71)
        at com.genymobile.scrcpy.Server$2.run(Server.java:100)
        at java.lang.Thread.run(Thread.java:764)

**Comment by rom1v** [comment]
> java.lang.NoSuchMethodException: injectInputEvent [class android.view.InputEvent, int]

Which device/system? The ROM changed this function so it differs from "standard" Android (AOSP).

**Comment by thomasrebele** [comment]
I had the same problem with a Yotaphone 2 (YD201). It seems that the method has an additional parameter:
```
public boolean android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(android.view.InputEvent,int,int) throws android.os.RemoteException, 
```
I couldn't find the meaning of the additional parameter. Passing 0 seems to work fine.

Great project, it helps a lot to gain access to the phone after breaking the screen (replacing the "spider app" with a permanent black screen).

**Comment by rom1v** [comment]
Please test #3190 :)
