### ISSUE TITLE
My scrcpy application lunch and terminate automatically and display nothing and say "device disconnected"  

### ISSUE THREAD

**Issue by ramzan1813** [Genymobile/scrcpy#2273]
[server] INFO: Device: HUAWEI INE-LX1r (Android 9)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1967)
        at android.media.MediaCodec.configure(MediaCodec.java:1896)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
Exit due to uncaughtException in main thread:
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
WARN: Device disconnected

How to fix this ?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by ramzan1813** [comment]
Thanks, My error fixed ❤

**Comment by ramzan1813** [comment]
sir, I see your code and not see the .vs folder so it means you do not use vs code or visual studio so which tool you are using for development?

**Comment by rom1v** [comment]
I use `vim` as editor. and I build with meson/ninja: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md
