### ISSUE TITLE
Don't control Redmi 9 (lancelot) using mouse or keyboard

### ISSUE THREAD

**Issue by utherbone** [Genymobile/scrcpy#2284]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Xubuntu 20.04
 - scrcpy version: 1.17
 - installation method: manual build
 - device model: Redmi 9 (lancelot) M2004J19G
 - Android version: 10

**I tried the official Ubuntu repository version. Then I tried to compile and install. I followed some last release instructions in the notes. But to no avail. The remote access window does not seem to respond to commands such as click and drag, or keyboard on the computer.**

```
scrcpy --show-touches --stay-awake --forward-all-clicks -m1920
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
┌[utherbone@Utherbone-Flaming-Blade-GTI] [/dev/pts/0] [1]
└[~]> scrcpy --show-touches --stay-awake --forward-all-clicks -m1920
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
┌[utherbone@Utherbone-Flaming-Blade-GTI] [/dev/pts/0] [1]
└[~]> scrcpy --show-touches --stay-awake --forward-all-clicks -m1920
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
┌[utherbone@Utherbone-Flaming-Blade-GTI] [/dev/pts/0] [1]
└[~]> scrcpy --show-touches --stay-awake --forward-all-clicks -m1920
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 2.0 MB/s (34930 bytes in 0.017s)
[server] INFO: Device: Xiaomi M2004J19C (Android 10)
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:83)
	at com.genymobile.scrcpy.wrappers.ContentProvider.putValue(ContentProvider.java:136)
	at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:142)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:39)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
Caused by: java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at android.os.Parcel.createException(Parcel.java:2074)
	at android.os.Parcel.readException(Parcel.java:2042)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:658)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2050)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1256)
	at com.android.providers.settings.SettingsProvider.insertGlobalSetting(SettingsProvider.java:1230)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:429)
	at android.content.ContentProvider.call(ContentProvider.java:2177)

INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 21.2.0-devel (git-48d48fb 2021-04-25 focal-oibaf-ppa)
INFO: Trilinear filtering enabled
INFO: Initial texture: 888x1920
```
Without the arguments, only "scrcpy" without double quotes results in the same result

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work
