### ISSUE TITLE
Smart TV screen no longer showing up on Desktop

### ISSUE THREAD

**Issue by parimalpatel87** [Genymobile/scrcpy#2294]
- [Y] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [Y] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.17
 - installation method: Windows release
 - device model: Sony X900H Android Smart TV
 - Android version: 9

**Describe the bug**
When trying to screen copy my TV onto my Windows 10 desktop, the final command would usually open up a new window with the copied tv screen.

This no longer happens on the last command and I get this error:

```
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: start failed
```

```
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 93.2 MB/s (34930 bytes in 0.000s)
[server] INFO: Device: Sony BRAVIA VH1 (Android 9)
INFO: Renderer: direct3d
INFO: Initial texture: 1920x1080
WARN: Device disconnected
**_[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: start failed_**
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2074)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:92)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
WARN: Killing the server...
```
I have searched where others were facing a similar issue: 

android.media.MediaCodec$CodecException: **_Error 0xfffffc0e_**

And they were able to fix using ```scrcpy -m 1024``` etc... however none of the resolutions worked.

Please note that I have a Shield which works perfectly fine (connected to this TV as well).
Also, this used to work on my current TV however a week ago it stopped.

My final option is to bring the TV back to factory settings.

**Comment by rom1v** [comment]
> however none of the resolutions worked

Even `scrcpy -m400`?

And with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/README.md#encoder)?

**Comment by parimalpatel87** [comment]
Success!

I tried ```scrcpy -m400``` to no avail, same issue.

I never tried encoder because I didn't know which encoder my device used. So I tried the suggested one:

```
C:\scrcpy>scrcpy --encoder OMX.qcom.video.encoder.avc
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 84.7 MB/s (34930 bytes in 0.000s)
[server] INFO: Device: Sony BRAVIA VH1 (Android 9)
INFO: Renderer: direct3d
INFO: Initial texture: 1920x1080
[server] ERROR: Exception on thread Thread[main,5,main]
WARN: Device disconnected
com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name 'OMX.qcom.video.encoder.avc"
        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:176)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:77)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
[server] ERROR: Try to use one of the available encoders:
[server] ERROR:     scrcpy --encoder-name 'OMX.MTK.VIDEO.ENCODER.AVC'
[server] ERROR:     scrcpy --encoder-name 'OMX.google.h264.encoder'
```

That didn't work but now I saw which 2 encoders I could use and voila, one worked:

```
C:\scrcpy>scrcpy --encoder OMX.google.h264.encoder
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 74.4 MB/s (34930 bytes in 0.000s)
[server] INFO: Device: Sony BRAVIA VH1 (Android 9)
INFO: Renderer: direct3d
INFO: Initial texture: 1920x1080
```

Thank you for your help @rom1v.
