### ISSUE TITLE
Rooted device

### ISSUE THREAD

**Issue by vincespice** [Genymobile/scrcpy#2320]
Is it possible to use the program on a root device? Rooted phone device disconnected.

**Comment by rom1v** [comment]
Rooted devices should work, except some issues with copy-paste (#1606).

What is the whole console output?

**Comment by vincespice** [comment]
C:\Users\spice\Downloads\scrcpy-win64-v1.17>scrcpy
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\Users\spice\Downloads\scrcpy-win64-v1.17\scrcpy-server...file pushed, 0 skipped. 24.2 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: samsung SM-A530F (Android 9)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1811)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1777)
        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:179)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:77)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:341)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2216
WARN: Device disconnected

**Comment by vincespice** [comment]
Scrcpy works well on many phones, only not on the rooted Samsung Galaxy A8.

**Comment by rom1v** [comment]
`0xfffffffe` is the error when the device encoder is missing (or could not be used): #82 #407

It might be related to the rooted phone after all: #2066 (but it's maybe just a bug in the ROM you installed, since not all rooted devices have this problem?)

Could you post your logcat?
```bash
adb logcat -c
scrcpy
adb logcat -d > logcat.txt
```

**Comment by vincespice** [comment]
I tried 3 rooted Samsung Galaxy A8, it didn't work. My other phones were not rooted. 
[logcat.txt](https://github.com/Genymobile/scrcpy/files/6493047/logcat.txt)

**Comment by rom1v** [comment]
Hmmm, something goes very wrong:

```
I scrcpy  : Device: samsung SM-A530F (Android 9)
I app_process: Thread[1,tid=9262,Native,Thread*=0x782fe14c00,peer=0x12c02468,"main"] recursive attempt to load library "/system/lib64/libmedia_jni.so"
D MtpDeviceJNI: register_android_mtp_MtpDevice
I app_process: Thread[1,tid=9262,Native,Thread*=0x782fe14c00,peer=0x12c02468,"main"] recursive attempt to load library "/system/lib64/libmedia_jni.so"
I app_process: Thread[1,tid=9262,Native,Thread*=0x782fe14c00,peer=0x12c02468,"main"] recursive attempt to load library "/system/lib64/libmedia_jni.so"
D StagefrightPluginLoader: Failed to load library: libstagefright_ccodec.so (dlopen failed: library "libstagefright_ccodec.so" not found)
D StagefrightPluginLoader: Handle or CreateInputSurface symbol is null
D StagefrightPluginLoader: Handle or CreateBuilder symbol is null
E ServiceManagement: getService: defaultServiceManager()->get returns Status(EX_TRANSACTION_FAILED): 'FAILED_TRANSACTION: ' for android.hardware.media.omx@1.0::IOmxStore/default.
E OmxInfoBuilder: Cannot find an IOmxStore service.
W MediaCodec-JNI: try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W MediaCodec-JNI: done releasing MediaCodec from JMediaCodec::~JMediaCodec().
D AndroidRuntime: Shutting down VM
--------- beginning of crash
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: PID: 9262
E AndroidRuntime: java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe
E AndroidRuntime: 	at android.media.MediaCodec.native_setup(Native Method)
E AndroidRuntime: 	at android.media.MediaCodec.<init>(MediaCodec.java:1811)
E AndroidRuntime: 	at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1777)
E AndroidRuntime: 	at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:179)
E AndroidRuntime: 	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:77)
E AndroidRuntime: 	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
E AndroidRuntime: 	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
E AndroidRuntime: 	at com.genymobile.scrcpy.Server.main(Server.java:252)
E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:341)
```

Does `/system/lib64/libmedia_jni.so` exist on your device?

What if you start `adb` without _root_ permissions (`adb unroot`)?

**Comment by vincespice** [comment]
Yes, I found the libmedia_jni.so.

I ran before Scrcpy:
adb unroot
restarting adbd as non root

However, I made the same mistake
java.lang.IllegalArgumentException: Failed to initialize video / avc, error 0xfffffffe
device disconnected.
