### ISSUE TITLE
Crash on Android 12 Beta 1

### ISSUE THREAD

**Issue by angeloanan** [Genymobile/scrcpy#2325]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 20H2
 - scrcpy version: 1.17
 - installation method: Download from release
 - device model: Pixel 3 XL (Crosshatch)
 - Android version: Android 12 Beta 1

**Describe the bug**
scrcpy crashes on launching with the following arguments `-wSb 15M -m 1920 --max-fps 60`
The errors are as follow:
```bat
[server] INFO: Device: Google Pixel 3 XL (Android 11)
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:83)
        at com.genymobile.scrcpy.wrappers.ContentProvider.getValue(ContentProvider.java:124)
        at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:140)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:39)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.SecurityException: The authority unknown does not match the one of the contentProvider: settings
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2418)
        at android.os.Parcel.createException(Parcel.java:2402)
        at android.os.Parcel.readException(Parcel.java:2385)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
        at android.content.IContentProvider.call(IContentProvider.java:119)
        ... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
        at android.content.ContentProvider.validateIncomingAuthority(ContentProvider.java:2535)
        at android.content.ContentProvider.access$200(ContentProvider.java:108)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:505)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:295)
        at android.os.Binder.execTransactInternal(Binder.java:1179)

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:83)
        at com.genymobile.scrcpy.wrappers.ContentProvider.putValue(ContentProvider.java:136)
        at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:142)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:39)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.SecurityException: The authority unknown does not match the one of the contentProvider: settings
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2418)
        at android.os.Parcel.createException(Parcel.java:2402)
        at android.os.Parcel.readException(Parcel.java:2385)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
        at android.content.IContentProvider.call(IContentProvider.java:119)
        ... 8 more
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3126)
        at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2195)
        ... 9 more
INFO: Renderer: direct3d
INFO: Initial texture: 936x1920
WARN: Device disconnected
WARN: Killing the server...
Press any key to continue . . .
```
I'm aware that the log says its Android 11. I can confirm that in fact I am using the Android 12 Beta.
[Here is the logcat file, filtered since scrcpy has started running](https://github.com/Genymobile/scrcpy/files/6509633/logcat.log)

**Comment by rom1v** [comment]
See #2129.

**Comment by angeloanan** [comment]
Whoops, somehow that slipped under my radar. My bad!
