### ISSUE TITLE
Android 12: displayToken must not be null

### ISSUE THREAD

**Issue by jonalmeida** [Genymobile/scrcpy#2327]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Mac OS 10.15.7
 - scrcpy version: 1.17
 - installation method: brew
 - device model: Pixel 3
 - Android version: 12

**Describe the bug**
Running scrcpy with the Android 12 Beta 1, it immediately fails with the error below. Oddly enough, it also things the device is Android 11 according to the logs as well.

`adb devices` and `adb shell` works fine.

```
scrcpy
2021-05-19 12:40:33.781 scrcpy[82653:7045682] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.17_1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 13.7 MB/s (34930 bytes in 0.002s)
[server] INFO: Device: Google Pixel 3 (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3126)
        at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2195)
        ... 9 more
2021-05-19 12:40:35.145 scrcpy[82653:7045682] INFO: Renderer: metal
2021-05-19 12:40:35.149 scrcpy[82653:7045682] INFO: Initial texture: 1080x2160
2021-05-19 12:40:35.536 scrcpy[82653:7045682] WARN: Device disconnected
2021-05-19 12:40:36.583 scrcpy[82653:7045682] WARN: Killing the server...

```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
See #2129.

**Comment by chandi1988** [comment]
@rom1v 

_Sent from my SM-M013F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
