### ISSUE TITLE
Crash with Pixel 5 on Android 12 beta 1

### ISSUE THREAD

**Issue by xiprox** [Genymobile/scrcpy#2328]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS
 - scrcpy version: 1.17.1
 - installation method: brew
 - device model: Pixel 5
 - Android version:  12 beta 1 (S, build number: SPB1.210331.013)

**Describe the bug**
scrcpy crashes after updating phone to Android 12 beta 1. Used to work perfectly fine for over a year, and there was been no change on the computer end.

```
x@xmbp ~ % scrcpy     
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.17_1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 49.8 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: Google Pixel 5 (Android 11)
INFO: Renderer: metal
INFO: Initial texture: 1080x2336
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3126)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2195)
	... 9 more
WARN: Device disconnected
WARN: Killing the server...
```

**Comment by rom1v** [comment]
See #2129.

**Comment by xiprox** [comment]
Oops! Should have taken a better look. Sorry and thanks! 🙇
