### ISSUE TITLE
Scrcpy stopped working on Galaxy A11 when it's on Windows 10

### ISSUE THREAD

**Issue by RedcatPhoenix2** [Genymobile/scrcpy#2329]
**Environment**
 - OS: Windows 10 Home
 - scrcpy version: 1.12.1
 - installation method: Windows release
 - device model: Samsung Galaxy A11 (SM-A115U)
 - Android version: 10

**Describe the bug**
Scrcpy won't connect to the Galaxy A11 on Windows when it worked on Ubuntu

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
`C:\Users\mcpen\Downloads\scrcpy-win64-v1.17>scrcpy
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\Users\mcpen\Downloads\scrcpy-win64-v1.17\scrcpy-server:... file pushed, 0 skipped. 30.2 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: samsung SM-A115U (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 720x1560
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:232)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:342)
WARN: Killing the server...

C:\Users\mcpen\Downloads\scrcpy-win64-v1.17>`
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
This is a device issue, independent of the computer system. Try to reboot the device.

Ref #498
