### ISSUE TITLE
Android 12 crash

### ISSUE THREAD

**Issue by marcherdiego** [Genymobile/scrcpy#2337]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS macOS
 - scrcpy version: 1.17
 - installation method: brew
 - device model: Google Pixel 4 XL
 - Android version: Android 12

**Describe the bug**
The script crashed when trying to run the command, it seems like it didn't recognize the OS version since the log says Android 11 instead of 12

```
(base) ➜  ~ scrcpy
2021-05-24 09:44:07.388 scrcpy[61305:1058630] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.17_1/share/...ped. 29.7 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: Google Pixel 4 XL (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3126)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2195)
	... 9 more
2021-05-24 09:44:08.631 scrcpy[61305:1058630] INFO: Renderer: metal
2021-05-24 09:44:08.634 scrcpy[61305:1058630] INFO: Initial texture: 1440x3040
2021-05-24 09:44:08.961 scrcpy[61305:1058630] WARN: Device disconnected
2021-05-24 09:44:09.963 scrcpy[61305:1058630] WARN: Killing the server...
```

**Comment by rom1v** [comment]
See #2129.
