### ISSUE TITLE
Android 12 device connection doesn't work

### ISSUE THREAD

**Issue by emartynov** [Genymobile/scrcpy#2342]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...] MacOS 11.4
 - scrcpy version: [e.g. 1.12.1] 1.17.1
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...] brew
 - device model: Pixel 3XL
 - Android version: [e.g. 10] 12 beta

**Describe the bug**
Device disconnects

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
2021-05-27 15:56:39.183 scrcpy[60554:2142189] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.17_1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 30.2 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: Google Pixel 3 XL (Android 11)
2021-05-27 15:56:40.277 scrcpy[60554:2142189] INFO: Renderer: metal
2021-05-27 15:56:40.280 scrcpy[60554:2142189] INFO: Initial texture: 1440x2960
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3126)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2195)
	... 9 more
2021-05-27 15:56:40.664 scrcpy[60554:2142189] WARN: Device disconnected
2021-05-27 15:56:41.668 scrcpy[60554:2142189] WARN: Killing the server...
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
See #2129.
