### ISSUE TITLE
CRITICAL: Could not initialize SDL: directx not available

### ISSUE THREAD

**Issue by chrisblais** [Genymobile/scrcpy#2343]
- [ x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

For what it's worth, it took almost a day to install and compile--homebrew, android-platform-tools, and scrcpy---but it works on an OLD 17" 2010 macbook pro. However, it will not work on my windows machine.

**Environment**
Windows 10
scrcpy 1.17
Windows release (tried both 32-bit and 64-bit versions)
Pixel 3
Android 11 (RQ2A.210505.002)

```
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\Users\gbrewer1\Desktop\scrcpy-win32-v1.17\scrcpy-server: 1 file pushed, 0 skipped. 65.5 MB/s (34930 bytes in 0.001s)
CRITICAL: Could not initialize SDL: directx not available
[server] INFO: Device: Google Pixel 3 (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
java.io.IOException: Connection refused
        at android.net.LocalSocketImpl.connectLocal(Native Method)
        at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:262)
        at android.net.LocalSocket.connect(LocalSocket.java:148)
        at com.genymobile.scrcpy.DesktopConnection.connect(DesktopConnection.java:40)
        at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:63)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:57)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)

```
```
05-27 14:29:03.413  4029  4029 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
05-27 14:29:03.417  4029  4029 I scrcpy  : Device: Google Pixel 3 (Android 11)
05-27 14:29:03.430  4029  4029 D AndroidRuntime: Shutting down VM
05-27 14:29:03.433  4029  4029 E AndroidRuntime: FATAL EXCEPTION: main
05-27 14:29:03.433  4029  4029 E AndroidRuntime: PID: 4029
05-27 14:29:03.433  4029  4029 E AndroidRuntime: java.io.IOException: Connection refused
05-27 14:29:03.433  4029  4029 E AndroidRuntime:        at android.net.LocalSocketImpl.connectLocal(Native Method)
05-27 14:29:03.433  4029  4029 E AndroidRuntime:        at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:262)
05-27 14:29:03.433  4029  4029 E AndroidRuntime:        at android.net.LocalSocket.connect(LocalSocket.java:148)
05-27 14:29:03.433  4029  4029 E AndroidRuntime:        at com.genymobile.scrcpy.DesktopConnection.connect(DesktopConnection.java:40)
05-27 14:29:03.433  4029  4029 E AndroidRuntime:        at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:63)
05-27 14:29:03.433  4029  4029 E AndroidRuntime:        at com.genymobile.scrcpy.Server.scrcpy(Server.java:57)
05-27 14:29:03.433  4029  4029 E AndroidRuntime:        at com.genymobile.scrcpy.Server.main(Server.java:252)
05-27 14:29:03.433  4029  4029 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
05-27 14:29:03.433  4029  4029 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
05-27 14:29:03.433  4029  4029 E scrcpy  : Exception on thread Thread[main,5,main]
05-27 14:29:03.433  4029  4029 E scrcpy  : java.io.IOException: Connection refused
05-27 14:29:03.433  4029  4029 E scrcpy  :      at android.net.LocalSocketImpl.connectLocal(Native Method)
05-27 14:29:03.433  4029  4029 E scrcpy  :      at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:262)
05-27 14:29:03.433  4029  4029 E scrcpy  :      at android.net.LocalSocket.connect(LocalSocket.java:148)
05-27 14:29:03.433  4029  4029 E scrcpy  :      at com.genymobile.scrcpy.DesktopConnection.connect(DesktopConnection.java:40)
05-27 14:29:03.433  4029  4029 E scrcpy  :      at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:63)
05-27 14:29:03.433  4029  4029 E scrcpy  :      at com.genymobile.scrcpy.Server.scrcpy(Server.java:57)
05-27 14:29:03.433  4029  4029 E scrcpy  :      at com.genymobile.scrcpy.Server.main(Server.java:252)
05-27 14:29:03.433  4029  4029 E scrcpy  :      at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
05-27 14:29:03.433  4029  4029 E scrcpy  :      at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
05-27 14:29:03.551  4043  4043 W app_process: type=1400 audit(0.0:114): avc: denied { read } for name="u:object_r:device_config_runtime_native_boot_prop:s0" dev="tmpfs" ino=23397 scontext=u:r:shell:s0 tcontext=u:object_r:device_config_runtime_native_boot_prop:s0 tclass=file permissive=0 b/175106535
05-27 14:29:03.551  4043  4043 I chatty  : uid=2000(shell) app_process identical 2 lines
05-27 14:29:03.551  4043  4043 W app_process: type=1400 audit(0.0:117): avc: denied { read } for name="u:object_r:device_config_runtime_native_boot_prop:s0" dev="tmpfs" ino=23397 scontext=u:r:shell:s0 tcontext=u:object_r:device_config_runtime_native_boot_prop:s0 tclass=file permissive=0 b/175106535
05-27 14:29:03.553  4043  4043 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
05-27 14:29:03.556  4043  4043 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.profilebootclasspath"
05-27 14:29:03.556  4043  4043 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_apex_image"
05-27 14:29:03.556  4043  4043 I AndroidRuntime: Using default boot image
05-27 14:29:03.556  4043  4043 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.disable_lock_profiling"
05-27 14:29:03.556  4043  4043 I AndroidRuntime: Leaving lock profiling enabled
05-27 14:29:03.556  4043  4043 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_generational_cc"
05-27 14:29:03.636  4043  4043 D app_process: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
05-27 14:29:03.636  4043  4043 D app_process: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt66l.dat
05-27 14:29:03.675  4043  4043 W app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
05-27 14:29:03.682  4043  4043 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.CleanUp
05-27 14:29:03.906  4043  4043 I scrcpy  : Cleaning up
05-27 14:29:03.907  4043  4043 I scrcpy  : Restoring normal power mode
```

**Comment by rom1v** [comment]
Windows graphics drivers issue I guess.

**Comment by chrisblais** [comment]
That is likely: I just tried to install Steam and it only "flickers".
I'm using a 1060 GTX with the latest drivers. Very frustrating issue.
