### ISSUE TITLE
Android 12 Developer Preview

### ISSUE THREAD

**Issue by LoveBye** [Genymobile/scrcpy#2356]
Pixel 3xl with Android 12 developer preview version reports an InvocationTargeException error on line 75 of SurfaceControl.java

**Comment by LoveBye** [comment]
[server] ERROR: Exception on thread Thread[main,5,main]INFO: Initial texture: 1440x2960

java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
WARN: Device disconnected
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3067)
        at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2147)
        ... 9 more

**Comment by rom1v** [comment]
#2129
