### ISSUE TITLE
Crashing while streaming 

### ISSUE THREAD

**Issue by anzil14** [Genymobile/scrcpy#2358]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 10 pro]
 - scrcpy version: [1.17]
 - installation method: [Windows release]
 - device model:Mi Redmi Note 10 pro
 - Android version: [Android 11]

**Describe the bug**
Scrcpy closeing while streaming in some apps like [youtube,netflix,amazon prime] 

I changed resolution to lower value still crashing in this apps 
Its occur only in streaming 

.....

[server] INFO: Device: Xiaomi M2101K6P (Android 11)
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
ERROR: SDL failed to get a vertex buffer for this Direct3D 9 rendering batch!
ERROR: Dropping back to a slower method.
ERROR: This might be a brief hiccup, but if performance is bad, this is probably why.
ERROR: This error will not be logged again for this renderer.

INFO: New texture: 2400x1080
WARN: Device disconnected

[server] ERROR: Exception on thread
Thread[main,5,main]
java.lang.IllegalStateException

        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutput- Buffer(MediaCodec.java:3452)__
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:463)

**Comment by jontelov** [comment]
Same issue while streaming

**Comment by aiguofer** [comment]
same issue on OnePlus 8T... only got this so I can watch my downloaded netflix and prime videos from my phone on my laptop, but that's the only thing that doesn't work :(
