### ISSUE TITLE
Last version stable not working whitch android 12 beta preview 

### ISSUE THREAD

**Issue by victoralfonso920** [Genymobile/scrcpy#2374]
The current version in the stable channel still does not work with devices with beta 2 android 12.

**Environment**
 - OS: [ macOS 11.4]
 - scrcpy version: [1.17]
 - installation method: [brew]
 - device model: Pixel 4 XL
 - Android version: [Beta 12]

**Describe the bug**
When executing this it tries to raise the mirror of the device but immediately it closes.

Below I provide error provided by terminal or shell on mac
```
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3144)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
```
There will be a solution to this bug in the stable channel in the future ??

**Comment by rom1v** [comment]
#2129
