### ISSUE TITLE
Not working on Ubuntu with Android 12 (beta)

### ISSUE THREAD

**Issue by xtheonexuk** [Genymobile/scrcpy#2386]
Desktop OS: Ubuntu 21.04

Phone Device: Pixel 5
Phone OS: Android 12 beta 2 (Build number: SPB2.210513.007)

Worked fine on Android 11 - Only stopped working on upgrade to Android 12.

Terminal output...

```
david@david-Z390-AORUS-ULTRA:~$ scrcpy
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 5.7 MB/s (34930 bytes in 0.006s)
[server] INFO: Device: Google Pixel 5 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 460.80
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2336
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3144)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2203)
	... 9 more
WARN: Device disconnected
WARN: Killing the server...
```

**Comment by rom1v** [comment]
#2129
