### ISSUE TITLE
Not working with android 12 beta installed on pixel

### ISSUE THREAD

**Issue by krishtoautomate** [Genymobile/scrcpy#2390]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [macOS]
 - scrcpy version: [e.g. 1.17]
 - installation method: [brew.]
 - device model: pixel
 - Android version: 12 beta

**Describe the bug**
not working in pixel device with android 12 beta

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
scrcpy
2021-06-15 08:52:53.318 scrcpy[11010:2571665] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.17_1/share/...ped. 14.7 MB/s (34930 bytes in 0.002s)
[server] INFO: Device: Google Pixel 5 (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3126)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2195)
	... 9 more
2021-06-15 08:52:54.731 scrcpy[11010:2571665] INFO: Renderer: metal
2021-06-15 08:52:54.735 scrcpy[11010:2571665] INFO: Initial texture: 1080x2336
2021-06-15 08:52:55.286 scrcpy[11010:2571665] WARN: Device disconnected
2021-06-15 08:52:56.290 scrcpy[11010:2571665] WARN: Killing the server...
```

**Comment by rom1v** [comment]
#2129
