### ISSUE TITLE
scrcpy closes after opening

### ISSUE THREAD

**Issue by Yohann13** [Genymobile/scrcpy#2404]
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2216
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:232)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:339)
WARN: Killing the server...
Press any key to continue . . .

i enabled the usb tethering and tried different cables and ports but for some reason it still doesnt work

**Comment by rom1v** [comment]
> android.media.MediaCodec$CodecException: Error 0xffffec77

It's not the same error code as here https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception
But try:

```
scrcpy -m1024
```

**Comment by Yohann13** [comment]
YOO IT WORKED TYSM
