### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by dev851** [Genymobile/scrcpy#2415]
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\Users\D^\Downloads\Compressed\sndcpy-v1.0\scrpy\sc... file pushed, 0 skipped. 12.2 MB/s (37330 bytes in 0.003s)
[server] INFO: Device: asus ASUS_X01BDA (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2280
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:114)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:95)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:401)
WARN: Killing the server...
Press any key to continue . . .

C:\Users\D^\Downloads\Compressed\sndcpy-v1.0\scrpy>scrcpy --encoder OMX.qcom.video.encoder.avc
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\Users\D^\Downloads\Compressed\sndcpy-v1.0\scrpy\sc... file pushed, 0 skipped. 14.7 MB/s (37330 bytes in 0.002s)
[server] INFO: Device: asus ASUS_X01BDA (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2280
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:114)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:95)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:401)
WARN: Killing the server...

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by Flandricool** [comment]
Is cool can you pls for Phone compatelble plsss
