### ISSUE TITLE
question about file folder, and about start/stop recording

### ISSUE THREAD

**Issue by Lyzoic-bit** [Genymobile/scrcpy#2418]
Hi, I tried run on command, set smaller sizes, mirroring worked, but when I tried start recording something went wrong, I couldn't find recording from anywhere(where can I find the folder they go into?) , I tried click ctrl and C but I'm not sure if it even stopped (or started) recording, any guides? Thanks

**Comment by rom1v** [comment]
> where can I find the folder they go into?

Your current directory in the terminal when you type the command.

See https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by Lyzoic-bit** [comment]
okay thanks, I will try again tomorrow, I'm unsure if the recording ever stopped, or started  (but starting command was right I think), thanks much appreciate I try again tomorrow

**Comment by rom1v** [comment]
Note that you can pass an absolute path:

```
scrcpy --record "C:\...\file.mp4"
```

**Comment by Lyzoic-bit** [comment]
Hi, I managed to find the videos now, however I cannot watch them, it says their size is 0 as well. When I open vlc it says it cannot open the MRL-location or something cannot be opened

**Comment by rom1v** [comment]
> it says their size is 0 as well

Something is very wrong. Any error message in the scrcpy console while your record?

**Comment by Lyzoic-bit** [comment]
no it doesn't give anything, I have made myscrcpy file too

**Comment by rom1v** [comment]
Please post the whole output in the console.

**Comment by Lyzoic-bit** [comment]
PS C:\Test\platform-tools> scrcpy.exe
scrcpy.exe : The term 'scrcpy.exe' is not recognized as the name of a cmdlet, function, script file, or operable progra
m. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ scrcpy.exe
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (scrcpy.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command scrcpy.exe was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\scrcpy.exe". See "get-help about_Command_Precedence" for more details.
PS C:\Test\platform-tools> ./scrcpy.exe
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\Test\platform-tools\scrcpy-server: 1 file pushed, 0 skipped. 53.9 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: HUAWEI STK-LX1 (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
PS C:\Test\platform-tools> ./scrcpy --record file.mp4
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\Test\platform-tools\scrcpy-server: 1 file pushed, 0 skipped. 53.9 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: HUAWEI STK-LX1 (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
INFO: Recording started to mp4 file: file.mp4
ERROR: Recording failed to file.mp4
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
PS C:\Test\platform-tools> ./scrcpy --record file.mp4 -m 720 -b 5M
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\Test\platform-tools\scrcpy-server: 1 file pushed, 0 skipped. 50.5 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: HUAWEI STK-LX1 (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 336x720
INFO: Recording started to mp4 file: file.mp4
INFO: Recording complete to mp4 file: file.mp4
PS C:\Test\platform-tools>


oh now it worked, I didnt know to specify both the quality and recording on one command, since the m- 1024 error comes first I focused on fixing it and then couldnt add the other command. now it works fine, and first time I see the commands of starting and stopping record
