### ISSUE TITLE
java.lang.IllegalStateException (windows 10)

### ISSUE THREAD

**Issue by Ratbagdoo** [Genymobile/scrcpy#2429]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:  Windows 10
 - scrcpy version:  win64 1.18
 - installation method: zip file (non-Master)
 - device model: A31 
 - Android version: 11

[server] INFO: Device: samsung SM-A315G (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
INFO: Recording started to matroska file: file.mkv
ERROR: Recording failed to file.mkv
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
WARN: Device disconnected
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:114)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:95)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:409)
WARN: Killing the server...

**Comment by Ratbagdoo** [comment]
BTW: ill be needing a step to step guide to fixing this issue

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows
