### ISSUE TITLE
request to limit the max size of scrcpy as default

### ISSUE THREAD

**Issue by caseyng** [Genymobile/scrcpy#2440]
I've been using scrcpy on a couple of phones, with a mac. Today i retried running it on vivo 1819 but it kept crashing. As i was connected via cable, i decided to run it on default settings. I was going through the info and finally thought to limit the max-size to 848.

scrcpy then worked.

I realized it was due to the texture settings, or rather, my phone's default pixel size is 1080x2336. I tested many variations and found that the max texture was 2104 for my mac (which as a max display resolution of 2880x1800)

As such, I suggest that the default for the max-size be set to a limit to either 2104 (which is apparently the max), or to the max size of the display resolution.

**Comment by rom1v** [comment]
> I tested many variations and found that the max texture was 2104 for my mac
> I suggest that the default for the max-size be set to a limit to either 2104 (which is apparently the max)

It's the max on your config. On my computer (a ThinkPad) with Linux (debian), I can mirror a OnePlus 7 Pro with definition 1440x3120 without problems.

Either the limitation is on the device side (the hardware encoder is limited), either on your computer where the GPU can limit the texture size.

If you encounter some limits, just create a script which calls `scrcpy -m 2048`.

**Comment by caseyng** [comment]
Yes i understand it's a limitation on my end. What I'm suggesting is to make a smart parameter so that others won't face the same issue. As I said, initially I thought it was because scrcpy don't work on my phone.

And there was no error code, just a stacktrace with error warnings. Or maybe, instead of limiting the default size, another option would be to catch this error and report to the user to limit the size instead.

**Comment by caseyng** [comment]
here is the full console output.

2021-07-01 19:06:25.411 scrcpy[30678:2957959] INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.18/share/scrcpy/scrcpy-server:...file pushed, 0 skipped. 87.4 MB/s (37330 bytes in 0.000s)
[server] INFO: Device: vivo vivo 1819 (Android 11)
2021-07-01 19:06:26.824 scrcpy[30678:2957959] INFO: Renderer: metal
2021-07-01 19:06:26.828 scrcpy[30678:2957959] INFO: Initial texture: 1080x2336
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:114)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:95)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:255)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:433)
2021-07-01 19:06:27.179 scrcpy[30678:2957959] WARN: Device disconnected
2021-07-01 19:06:28.180 scrcpy[30678:2957959] WARN: Killing the server...

**Comment by rom1v** [comment]
OK, so this is a generic MediaCodec error (often caused by unsupported dimensions, but not always): https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by caseyng** [comment]
I see. Didn't realized it was that error.

Anyway, since the solution proposed is to try with a lower resolution, why not just append it to the end of the exception so that others may know the solution? Just my opinion.

**Comment by rom1v** [comment]
> Anyway, since the solution proposed is to try with a lower resolution, why not just append it to the end of the exception so that others may know the solution? Just my opinion.

This is done for the exception with the specific error code: 8a694a97855333849976bea5e558eaa45add0168

But this one is a generic one (even a very generic java exception, without any indication except by reading the stacktrace), so we don't really know the cause.
