### ISSUE TITLE
Redmi Android 9 java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xm

### ISSUE THREAD

**Issue by AlexanderKott** [Genymobile/scrcpy#2453]
Hello. i use ubuntu 20.04
What i got:

1 apt install scrcpy

2 root@vmi523325:~# adb devices
List of devices attached
0c53a0b59906	device

3 root@vmi523325:~# scrcpy
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 0.1 MB/s (24773 bytes in 0.221s)
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.io.FileReader.<init>(FileReader.java:58)
	at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
	at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
	at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
	at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
	at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
	at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:40)
	at android.content.res.Resources.<init>(Resources.java:267)
	at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
	at android.content.res.Resources.getSystem(Resources.java:190)
	at android.app.LoadedApk.<init>(LoadedApk.java:211)
	at android.app.ContextImpl.createSystemContext(ContextImpl.java:2331)
	at android.app.ActivityThread.getSystemContext(ActivityThread.java:2190)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)

any tips? thanks!

**Comment by rom1v** [comment]
That error message is not a problem, you can ignore it. It has been silented in later versions.

**Comment by AlexanderKott** [comment]
> That error message is not a problem, you can ignore it. It has been silented in later versions.

thank you for the answer. I am trying to run scrpy first time. and this maybe is not all.
wnen i write
root@vmi523325:~# scrcpy
INFO: scrcpy 1.12.1 https://github.com/Genymobile/scrcpy
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 0.1 MB/s (24773 bytes in 0.221s)

i don't see any windows apearing, My terminal window just does something in background, no any error messages, no loading indicator and etc. Maybe i run scrcopy wrong? Looks like this hangups. So question is: what i should see after this command:
root@vmi523325:~# scrcpy

thanks

**Comment by rom1v** [comment]
1. Do not run scrcpy as root
2. If it hangs here, please post the logcat

```bash
adb logcat -c  # clean
scrcpy  # then kill
adb logcat -d > logcat.txt
```

**Comment by AlexanderKott** [comment]
what was the problem:
error: XDG_RUNTIME_DIR not set in the environment.
CRITICAL: Could not initialize SDL: No available video device

Looks like i cannot use this tool on my VPS server :\ .. or it still possible?
