### ISSUE TITLE
It cant run on Pixel 3A

### ISSUE THREAD

**Issue by MarvL05** [Genymobile/scrcpy#2473]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.17
 - installation method: manual build
 - device model: Pixel 3A
 - Android version: 12

**Describe the bug**
Well, maybe it doesn't serve Android 12 Beta?

On errors, please provide the output of the console (and `adb logcat` if relevant).
Windows Command

```
D:\Program Files\Scrcpy_GUI>scrcpy
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
D:\Program Files\Scrcpy_GUI\scrcpy-server: 1 file pushed, 0 skipped. 31.1 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: Google Pixel 3a (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3144)
        at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2203)
        ... 9 more
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2216
WARN: Device disconnected
WARN: Killing the server...
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Use scrcpy v1.18. See #2129.
