### ISSUE TITLE
2 cases for crashing the program or "lost" try/catch.

### ISSUE THREAD

**Issue by yjh-styx** [Genymobile/scrcpy#2488]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.18
 - installation method: Windows release
 - device model: Khadas VIM3
 - Android version: 9 (Pie)

**Describe the bug**
1. Crash when launching srccpy while the device is waiting for user input.
   The application has brought up a modal MesageBox and is waiting for user input.
   If you run scrcpy at this moment, then after a short timeout (~2-3 sec.) It crashes.
The log is here:
---cit---
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:114)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:95)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
---end---

2. If you run srccpy in advance (without the --lock-video-orientation key) and the MessageBox
   output causes the screen to rotate, scrcpy crashes in the same place:
---cit---
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
INFO: Renderer: direct3d
INFO: Initial texture: 1920x1080
WARN: Device disconnected
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:114)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:95)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:255)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
---end---

N.B. If srccpy running with --lock-video-orientation=initial option before program output this MessageBox, it's work correctly

Info: Host (windows) Resolution 1600x1200

**Comment by rom1v** [comment]
It's a crash related to your device encoder: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

Try with a lower definition.

**Comment by yjh-styx** [comment]
When start srccpy with option -m 1024 (or lower) it start normally. -m 1200 (or higher) -- except.
Available encoders is OMX.amlogic.video.encoder.avc only.

May be possible call  codec.dequeueOutputBuffer in try-catch block and (if exception occured) close srccpy and show notification to user?

**Comment by yjh-styx** [comment]
Addition information - when device change orientation, option '-m' not protect from exception. Help only option '--lock-video-orientation=initial' :). But AFTER image rotated we can call scrcpy with option -m and it start normally.
