### ISSUE TITLE
Xiaomi Mi Watch

### ISSUE THREAD

**Issue by KashaMalaga** [Genymobile/scrcpy#2489]
**Environment**
 - OS: Windows
 - scrcpy version: 1.18
 - installation method: Windows release
 - device model: Xiaomi Mi Watch
 - Android version: Wear OS 2.47 (Android 9 )

INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\Users\SRAMI77\Downloads\scrcpy-win64-v1.18\scrcpy-serve... file pushed, 0 skipped. 27.7 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: Xiaomi Mi Watch (Android 9)
INFO: Renderer: direct3d
INFO: Initial texture: 368x448
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1811)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1777)
        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:180)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:78)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:353)
WARN: Killing the server...

**Comment by rom1v** [comment]
Does not work on watches, there is no H.264 hardware encoder.
