### ISSUE TITLE
Whenever I'm trying to open netflix in scrcpy in my macbook pro, scrcpy is getting force closed. Please provide any solution for this issue

### ISSUE THREAD

**Issue by Nitz1495** [Genymobile/scrcpy#2494]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by Nitz1495** [comment]
![Screenshot 2021-07-16 at 3 57 39 AM](https://user-images.githubusercontent.com/87503002/125866027-bf160c2c-6542-4749-b611-0b159a94fe94.png)

**Comment by Nitz1495** [comment]
Please resolve

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by Nitz1495** [comment]
I tried both the option suggested, changing the encoder and reducing the size. Reducing size is not working and still the same issue is observed. When I changed encoder it is not force closing but the video screen is getting stuck at loading page.

**Comment by clort81** [comment]
If you use those services, you don't control your device, they do.  Please close this issue.

**Comment by michalpl7** [comment]
Similar problem with Android + Windows and Netflix. I tried -m 800 didn't help.

INFO: Initial texture: 1080x2400
INFO: New texture: 2400x1080
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3461)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:110)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
        at com.genymobile.scrcpy.Server.main(Server.java:309)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:438)
WARN: Killing the server...

**Comment by rom1v** [comment]
> I tried -m 800 didn't help.

Could you post the output with `scrcpy -m 800`?

**Comment by michalpl7** [comment]
Here is an error with -m 800:

[server] INFO: Device: OnePlus HD1903 (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 360x800
INFO: New texture: 800x360
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3461)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:110)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
        at com.genymobile.scrcpy.Server.main(Server.java:309)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:438)
WARN: Killing the server...

Too bad it's not working. :/
