### ISSUE TITLE
Error trying start on W10

### ISSUE THREAD

**Issue by Sergio2570** [Genymobile/scrcpy#2500]
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
D:\Programas\Scrcpy - copia\scrcpy-server: 1 file pushed, 0 skipped. 56.3 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: OPPO CPH2219 (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2126)
        at android.media.MediaCodec.configure(MediaCodec.java:2042)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:232)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:419)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
WARN: Device disconnected
WARN: Killing the server...

**Comment by rom1v** [comment]
#445

**Comment by Sergio2570** [comment]
> #445

Thanks <3
