### ISSUE TITLE
I can't mirror the screen on my Sansumg a31

### ISSUE THREAD

**Issue by Doffy07** [Genymobile/scrcpy#2508]
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\Users\Usuário\Desktop\Scry\scrcpy-server: 1 file pushed, 0 skipped. 32.4 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: samsung SM-A315G (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 2400x1080
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:114)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:95)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:409)
WARN: Killing the server...

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by Doffy07** [comment]
thankyou
