### ISSUE TITLE
It just doesn't work at all, and i really don't know what i can do more

### ISSUE THREAD

**Issue by FunnyParadox** [Genymobile/scrcpy#2533]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 11]
 - scrcpy version: [e.g. 1.18]
 - installation method: [Windows release]
 - device model: Huawei P30 Lite
 - Android version: [EMUI 10 (not rooted)]

**Describe the bug**
I've activated the USB debug, and lower the resolution (because it didn't worked before, but still not now, and now even when i raise up the resolution again it don't gives me the high resolution error anymore)v

I type :
`C:\adb>adb devices`
and it gives
```
List of devices attached
L2N4C20616006897        device
emulator-5562   connecting
```

but when i type `C:\adb>scrcpy`
it gives :
```
adb: error: failed to get feature set: more than one device/emulator
ERROR: "adb push" returned with value 1
```
Even tho i've got only one device connected (or the device and the emulator is 2 different "device" but if this case how can i "close" one ?)

And when i try to make Scrcpy mirror only my phone it gives :
```
C:\adb>scrcpy -s L2N4C20616006897
scrcpy-server.jar: 1 file pushed. 0.5 MB/s (19342 bytes in 0.038s)
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
ERROR: Could not open video stream
ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:135)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:62)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:22)
        at com.genymobile.scrcpy.Server.main(Server.java:78)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
INFO: Initial texture: 1080x2312
WARN: Cannot terminate server
```
So i don't know what to do in this situation
Annnnd i can't post any logcat because
```
`C:\adb>adb logcat -d`
- waiting for device -
error: more than one device/emulator
```
(even when i do `C:\adb>adb logcat L2N4C20616006897` or `adb logcat -s L2N4C20616006897`)

**Comment by fusionneur** [comment]
Just updated ethernally script which facilitates wireless mirroring
https://github.com/fusionneur/ethernally

Let me know if you encounter any issue. Thank you

**Comment by FunnyParadox** [comment]
>  - [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
>  - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).
> 
> **Environment**
>  - OS: [Windows 11]
>  - scrcpy version: [e.g. 1.18]
>  - installation method: [Windows release]
>  - device model: Huawei P30 Lite
>  - Android version: [EMUI 10 (not rooted)]
> 
> **Describe the bug**
> I've activated the USB debug, and lower the resolution (because it didn't worked before, but still not now, and now even when i raise up the resolution again it don't gives me the high resolution error anymore)v
> 
> I type :
> `C:\adb>adb devices`
> and it gives
> ```
> List of devices attached
> L2N4C20616006897        device
> emulator-5562   connecting
> ```
> 
> but when i type `C:\adb>scrcpy`
> it gives :
> ```
> adb: error: failed to get feature set: more than one device/emulator
> ERROR: "adb push" returned with value 1
> ```
> Even tho i've got only one device connected
> (or the device and the emulator is 2 different "device" but if this case how can i "close" one of them ?)
> 
> And when i try to make Scrcpy mirror only my phone it gives :
> ```
> C:\adb>scrcpy -s L2N4C20616006897
> scrcpy-server.jar: 1 file pushed. 0.5 MB/s (19342 bytes in 0.038s)
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> ERROR: Could not open video stream
> ERROR: Exception on thread Thread[main,5,main]
> android.media.MediaCodec$CodecException: Error 0xfffffc0e
>         at android.media.MediaCodec.native_configure(Native Method)
>         at android.media.MediaCodec.configure(MediaCodec.java:2023)
>         at android.media.MediaCodec.configure(MediaCodec.java:1951)
>         at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:135)
>         at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:62)
>         at com.genymobile.scrcpy.Server.scrcpy(Server.java:22)
>         at com.genymobile.scrcpy.Server.main(Server.java:78)
>         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
>         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
> INFO: Initial texture: 1080x2312
> WARN: Cannot terminate server
> ```
> So i don't know what to do in this situation
> Annnnd i can't post any logcat because
> ```
> `C:\adb>adb logcat -d`
> - waiting for device -
> error: more than one device/emulator
> ```
> (even when i do `adb logcat L2N4C20616006897` or `adb logcat -s L2N4C20616006897`)
