### ISSUE TITLE
java.lang.NoSuchMethodException: android.view.SurfaceControl.getInternalDisplayToken []

### ISSUE THREAD

**Issue by nkligang** [Genymobile/scrcpy#2535]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Windows]
 - scrcpy version: [e.g. 1.18]
 - installation method: [e.g. manual build]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**
I create new Activity, the code is list bellow. The main function is test power off device, while I got exception of 'android.view.SurfaceControl.getInternalDisplayToken'，Can anybody tell me where the problem is?

```
public class MainActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        final Button startButton = (Button) findViewById(R.id.button_start);
        startButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                try {
                    Device.setScreenPowerMode(0);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }
}
```

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
E/scrcpy: Could not invoke method
    java.lang.NoSuchMethodException: android.view.SurfaceControl.getInternalDisplayToken []
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getMethod(Class.java:1693)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetBuiltInDisplayMethod(SurfaceControl.java:94)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getBuiltInDisplay(SurfaceControl.java:103)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:263)
        at com.genymobile.scrcpy.app.MainActivity$1.onClick(MainActivity.java:21)
        at android.view.View.performClick(View.java:7184)
        at android.view.View.performClickInternal(View.java:7157)
        at android.view.View.access$3500(View.java:821)
        at android.view.View$PerformClick.run(View.java:27660)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
You won't be able to turn screen off from an Android app.

Your problem here is accessing hidden APIs: https://stackoverflow.com/questions/55970137/bypass-androids-hidden-api-restrictions

But even if you manage to call the function, you'll probably get a SecurityException. Due tl the way it is executed, scrcpy has `shell` permissions.

**Comment by nkligang** [comment]
I see, Thank you very much
