### ISSUE TITLE
Stuck at initial texture

### ISSUE THREAD

**Issue by nflzd** [Genymobile/scrcpy#2538]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**
im trying to mirror my phone, but it stuck at INFO: Initial texture: 1080x2336, ive tried all scrcpy version from 1.10 to 1.18 and it still not working
On errors, please provide the output of the console (and `adb logcat` if relevant).

```
[server] INFO: Device: xiaomi Mi 10 Pro (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
```

**Comment by rom1v** [comment]
Does it work better with a lower definition?

```bash
scrcpy -m800
```

**Comment by nflzd** [comment]
> Does it work better with a lower definition?
> 
> ```shell
> scrcpy -m800
> ```

nope it doesnt

**Comment by nflzd** [comment]
btw sometimes it says, 
```
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2792)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:113)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:94)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:78)
        at com.genymobile.scrcpy.Server.main(Server.java:239)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
```

**Comment by rom1v** [comment]
And with another [encoder](https://github.com/Genymobile/scrcpy#encoder)?

**Comment by nflzd** [comment]
> And with another [encoder](https://github.com/Genymobile/scrcpy#encoder)?

thank you for helping, i think its caused by my custom rom, changed the rom to android 11, and its works perfectly.
