### ISSUE TITLE
Can not link to Virtual device

### ISSUE THREAD

**Issue by greenhandzdl** [Genymobile/scrcpy#2550]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:Windows10
 - scrcpy version: 1.18
 - installation method: Windows release
 - device model:Virtual device
 - Android version: Android6.0.1

**Describe the bug**
```
C:\Users\20292>scrcpy
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 62.5 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: HUAWEI NOH-AN00 (Android 6.0.1)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:114)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:95)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2160
WARN: Device disconnected

```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception ?
