### ISSUE TITLE
scrypy doest want to connect to my phone

### ISSUE THREAD

**Issue by schrundeng** [Genymobile/scrcpy#2556]
OS: Windows 10 20H2
scrcpy version: 1.18
Installation Method: Windows Release
Device Model: SAMSUNG A31/DS
Android version: Android 11

How do i fix this?

Here is the console

INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 32.2 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: samsung SM-A315G (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:114)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:95)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:409)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
WARN: Device disconnected
WARN: Killing the server...
Press any key to continue . . .

**Comment by wyongch** [comment]
原因为:手机不兼容 scrcpy 默认分辨率设置。
解决方法：
启动scrcpy时使用较低的分辨率。

scrcpy -m 1024

**Comment by schrundeng** [comment]
Thanks, but i want to use the default resolution, again thank you

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception
