### ISSUE TITLE
The hardware encoder is not able to encode at the given definition

### ISSUE THREAD

**Issue by Aiuspaktyn** [Genymobile/scrcpy#2571]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows]
 - scrcpy version: [1.18]
 - installation method: [Windows release]
 - device model: [Huawei P40 Lite]
 - Android version: [10]

**Describe the bug**

> [server] INFO: Device: HUAWEI JNY-LX1 (Android 10)
> INFO: Renderer: direct3d
> INFO: Initial texture: 1080x2304
> WARN: Device disconnected
> [server] ERROR: Exception on thread Thread[main,5,main]
> android.media.MediaCodec$CodecException: Error 0xfffffc0e
>         at android.media.MediaCodec.native_configure(Native Method)
>         at android.media.MediaCodec.configure(MediaCodec.java:2023)
>         at android.media.MediaCodec.configure(MediaCodec.java:1951)
>         at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
>         at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
>         at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
>         at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
>         at com.genymobile.scrcpy.Server.main(Server.java:255)
>         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
>         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
> [server] ERROR: The hardware encoder is not able to encode at the given definition.
> [server] ERROR: Try with a lower definition:
> [server] ERROR:     scrcpy -m 1024

**Comment by rom1v** [comment]
Yes, do what the error message suggest:

```bash
scrcpy -m 1024
```

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception
