### ISSUE TITLE
scrcpy can't connect android 12 beta 4.1

### ISSUE THREAD

**Issue by azkadev** [Genymobile/scrcpy#2608]
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...shed. 1.9 MB/s (34012 bytes in 0.017s)
[server] INFO: Device: realme Realme 5 Series (Android 12)
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 21.0.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 720x1600
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3143)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2212)
	... 9 more
WARN: Killing the server...

**Comment by rom1v** [comment]
Use v1.18.

**Comment by azkadev** [comment]
ok thanks
