### ISSUE TITLE
--stay-awake isn't working on Pixel3a (Android 11)

### ISSUE THREAD

**Issue by jpage4500** [Genymobile/scrcpy#2612]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS
 - scrcpy version: 1.17
 - installation method: brew
 - device model: Pixel 3a XL
 - Android version: 11

**Describe the bug**
--stay-awake doesn't appear to be working for me. After whatever display timeout period, the screen goes black and I can't get it to come back on again. I can however close the scrcpy window and re-open and the screen will display fine again.

I'm running a Pixel3aXL running Android 11

Here's the command I use to launch scrcpy
```
scrcpy -s $ADB_DEVICE $ADB_PORT --show-touches --stay-awake --encoder 'c2.android.avc.encoder'

using device: 04QAX0NRLM, port: -p 17947
2021-09-04 11:37:57.040 scrcpy[6943:58134413] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.17/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 55.8 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: Google AOSP on bonito (Android 11)
2021-09-04 11:37:57.467 scrcpy[6943:58134413] INFO: Renderer: metal
2021-09-04 11:37:57.470 scrcpy[6943:58134413] INFO: Initial texture: 1080x2160
```

**Comment by rom1v** [comment]
The option only works when the device is plugged in:
https://github.com/Genymobile/scrcpy#stay-awake

(this is a limitation of the Android option)

**Comment by jpage4500** [comment]
Thanks for the quick feedback!

This device is plugged-in.. direct USB

If you're looking at that -s and PORT line in my command - I have a script that will list all of the connected devices via adb and let me select which one to mirror. It does work with connected and wireless devices - but this device is usb

```
scrcpy -s $ADB_DEVICE $ADB_PORT
```

**Comment by jpage4500** [comment]
FWIW -- here's the full script I use in case it'll benefit anyone else too.. I often have several devices connected so it'll prompt me which one to mirror. Let me know if you see any issues with how I'm running scrcpy.. I'm unsure about the encoding param - don't remember what caused me to try that. I think due to some really laggy starts at one point.

screenMirror.sh
```
#################################################################################################
# mirror a device screen
#################################################################################################

// get the device ID (serial number) of connected device to use
// - sets the env variable ADB_DEVICE to the device selected
// - if multiple devices are present, also sets the env variable ADB_PORT to a random number
function selectDevice() {
    DEVICES=$(adb devices -l | grep -v "List" | grep -v "offline" | grep -v '^$' | sed 's/ device:.*//')

    NUM_DEVICES=`echo "${DEVICES}" | wc -l`

    if [ $NUM_DEVICES -eq 0 ]; then
        echo "no devices!"
        return 1
    elif [ $NUM_DEVICES -eq 1 ]; then
        echo "using device: $ADB_DEVICE"
        export ADB_DEVICE=$(echo $DEVICES | sed 's/ .*//')
        return 0
    fi

    IFS=$'\n'
    select device in $DEVICES
    do
        export ADB_DEVICE=$(echo "$device" | sed $'s/[ \t].*$//g')
        export ADB_PORT="-p $RANDOM"
        echo "using device: $ADB_DEVICE, port: $ADB_PORT"
        return 0
    done
}

#################################################################################################
# start
#################################################################################################
cd "$(dirname $0)"

selectDevice
if [ $? -eq 1 ]; then
    echo "no devices! press any key!"
    read n
    exit 1
fi

# options:
# --stay-awake
# --always-on-top 
# --encoder ['OMX.qcom.video.encoder.avc', 'c2.android.avc.encoder', 'OMX.google.h264.encoder']

scrcpy -s $ADB_DEVICE $ADB_PORT --show-touches --stay-awake --encoder 'c2.android.avc.encoder'
```

**Comment by rom1v** [comment]
The feature `--stay-awake` basically changes an Android setting. You can do it manually without scrcpy.

Read the value:

```bash
adb shell settings get global stay_on_while_plugged_in
```

Write the value:

```bash
adb shell settings put global stay_on_while_plugged_in 7  # enable
adb shell settings put global stay_on_while_plugged_in 0  # disable
```

**Comment by jpage4500** [comment]
I see.. the developer 'stay awake while charging' setting. I guess I could just call those commands before and after running scrcpy.. I'll give that a try

thanks

**Comment by rom1v** [comment]
> I guess I could just call those commands before and after running scrcpy

scrcpy call them if you pass '--stay-awake`. Check the value while scrcpy is running.

**Comment by dbareis** [comment]
--stay-awake also fails on my Oneplus 8 Pro on Android 12, if I try the ADB command from above:

`adb shell settings put global stay_on_while_plugged_in 7`

Then I get:
```
Exception occurred while executing 'put':
java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
        at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2663)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1635)
        at com.android.providers.settings.SettingsProvider.insertGlobalSetting(SettingsProvider.java:1589)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:591)
        at android.content.ContentProvider.call(ContentProvider.java:2473)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:521)
        at com.android.providers.settings.SettingsService$MyShellCommand.putForUser(SettingsService.java:382)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:278)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:50)
        at android.os.Binder.shellCommand(Binder.java:970)
        at android.os.Binder.onTransact(Binder.java:854)
        at android.os.Binder.execTransactInternal(Binder.java:1226)
        at android.os.Binder.execTransact(Binder.java:1163)
```

SCRCPY says:

```
[server] ERROR: Could not change "stay_on_while_plugged_in"
com.genymobile.scrcpy.SettingsException: Could not access settings: put global stay_on_while_plugged_in 7
        at com.genymobile.scrcpy.Settings.execSettingsPut(Settings.java:26)
        at com.genymobile.scrcpy.Settings.putValue(Settings.java:61)
        at com.genymobile.scrcpy.Settings.getAndPutValue(Settings.java:80)
        at com.genymobile.scrcpy.Server.initAndCleanUp(Server.java:37)
        at com.genymobile.scrcpy.Server.access$000(Server.java:12)
        at com.genymobile.scrcpy.Server$2.run(Server.java:121)
        at java.lang.Thread.run(Thread.java:920)
Caused by: java.io.IOException: Command [settings, put, global, stay_on_while_plugged_in, 7] returned with value 255
        at com.genymobile.scrcpy.Command.exec(Command.java:16)
        at com.genymobile.scrcpy.Settings.execSettingsPut(Settings.java:24)
        ... 6 more
```

**Comment by rom1v** [comment]
> Exception occurred while executing 'put':
> java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

https://github.com/Genymobile/gnirehtet/issues/302#issuecomment-973850470
https://github.com/Genymobile/gnirehtet/issues/5

**Comment by dbareis** [comment]
> > Exception occurred while executing 'put':
> > java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
> 
> [Genymobile/gnirehtet#302 (comment)](https://github.com/Genymobile/gnirehtet/issues/302#issuecomment-973850470) [Genymobile/gnirehtet#5](https://github.com/Genymobile/gnirehtet/issues/5)

I can confirm that screen capture is disabled for this app, interesting even my banking app doesn't do that!

@rom1v 
I think it should say this for "--stay-awake" in --help output and any other doco.

**Comment by dbareis** [comment]
Setting "Disable Permission Monitoring" (developer option) works for me on OnePlus 8 PRO on Android 12

**Comment by dbareis** [comment]
Setting "Disable Permission Monitoring" (developer option)] seems to have solved it :-)  Now the ADB shell commands no longer fail either.

**Comment by cool-delete** [comment]
> Setting "**Disable Permission Monitoring**" (developer option) works for me on OnePlus 8 PRO on Android 12.

It is effective for my OnePlus 13. After using the USB connect OnePlus debug, then disconnect the USB Connect and use it to use WiFi Connect.
