### ISSUE TITLE
SCRCPY not working on a rooted device

### ISSUE THREAD

**Issue by PaulIRL** [Genymobile/scrcpy#2625]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.18
 - installation method: Github release
 - device model: OnePlus 7 PRO GM1913
 - Android version: 10

**Describe the bug**
Cannot connect to the device (because of root probably)

```
1 file pushed, 0 skipped. 41.7 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: OnePlus GM1913 (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1876)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1833)
        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:180)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:78)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:362)
INFO: Renderer: direct3d
INFO: Initial texture: 1440x3120
WARN: Device disconnected
```

I also tried to run adb unroot and it did not help

**Comment by rom1v** [comment]
> java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe

It seems this is a video codec issue in your ROM, not the fact that it is rooted or not. Which ROM is it?

**Comment by PaulIRL** [comment]
No, I apparently a module called "ADB Root" installed and activated which "allows to adb root regardless of props settings"
Disabling it fixed the problem.
