### ISSUE TITLE
Doesn't work on Samsung Galaxy A32 but works on other Samsung devices.

### ISSUE THREAD

**Issue by robbigamer** [Genymobile/scrcpy#2669]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 Home Single Language 19043.1237
 - scrcpy version: 1.18
 - installation method: Windows release
 - device model: Samsung Galaxy A32
 - Android version: 11

**Describe the bug**
cmd window closes after opening. It works perfectly well with the Samsung Galaxy A10s and Samsung Galaxy A51.

```
[server] INFO: Device: samsung SM-A325F (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:114)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:95)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:409)
WARN: Killing the server...
Press any key to continue . . .
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception
