### ISSUE TITLE
Could not initialize SDL - No available video device 

### ISSUE THREAD

**Issue by xxxxxxH** [Genymobile/scrcpy#2673]
Environment
ubuntu 20.04
scrcpy 1.19
RedMi k20
Android 10
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 44.5 MB/s (37330 bytes in 0.001s)
error: XDG_RUNTIME_DIR not set in the environment.
CRITICAL: Could not initialize SDL: No available video device
[server] INFO: Device: Xiaomi Redmi K20 (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
java.io.IOException: Connection refused
        at android.net.LocalSocketImpl.connectLocal(Native Method)
        at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:296)
        at android.net.LocalSocket.connect(LocalSocket.java:147)
        at com.genymobile.scrcpy.DesktopConnection.connect(DesktopConnection.java:40)
        at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:63)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:57)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)

**Comment by rom1v** [comment]
```
error: XDG_RUNTIME_DIR not set in the environment.
CRITICAL: Could not initialize SDL: No available video device
```

Do you just run scrcpy locally, or over SSH or in a VM or something?

**Comment by xxxxxxH** [comment]
run in VM

**Comment by xxxxxxH** [comment]
subsystm for windows 10 ubuntu 20.04 LTS

**Comment by rom1v** [comment]
Your VM seems to not have access to accelerated video output.

**Comment by xxxxxxH** [comment]
So what should I do ths

**Comment by liukuo362573** [comment]
I meet the same question in 阿里云 arm64 Ubuntu VM , has anybody resolve this?

**Comment by liukuo362573** [comment]
> I meet the same question in 阿里云 arm64 Ubuntu VM , has anybody resolve this?

Finally, I change to other ROM version,the error disappear.

**Comment by pongpom** [comment]
> > I meet the same question in 阿里云 arm64 Ubuntu VM , has anybody resolve this?
> 
> Finally, I change to other ROM version,the error disappear.

what kind of ROM version did you running successfully? i'm using azure Ubuntu 22 VM with arm64 and face the error now.

**Comment by liukuo362573** [comment]
@pongpom other redroid version

**Comment by donkeykangwang10** [comment]
> @pongpom other redroid version

Coud I know which redroid version? I came across the same issue.
