### ISSUE TITLE
Doesn't work on Xiaomi redmi 9T but works on other Xiaomi devices.

### ISSUE THREAD

**Issue by atimofeev86** [Genymobile/scrcpy#2677]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.19
 - installation method: Windows release
 - device model: Xiaomi redmi 9T
 - Android version: 11

**Describe the bug**
Doesn't work with Xiaomi redmi 9T

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
C:\Users\user\source\repos\Facebook\bin\Debug\scrcpy>adb devices
List of devices attached
cd42edf31220    device
inhmcabeqocqpbww        device
lz5hyxc6njai6pss        offline


C:\Users\user\source\repos\Facebook\bin\Debug\scrcpy>scrcpy -s cd42edf31220
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
C:\Users\user\source\repos\Facebook\bin\Debug\scrcpy\scrcp... file pushed, 0 skipped. 72.8 MB/s (37330 bytes in 0.000s)
[server] INFO: Device: Xiaomi Redmi 9T (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2127)
        at android.media.MediaCodec.configure(MediaCodec.java:2043)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
WARN: Killing the server...

```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
See #73 #833.

**Comment by atimofeev86** [comment]
sorry. thanks
