### ISSUE TITLE
Help please it comes when i am trying to mirror my screen

### ISSUE THREAD

**Issue by aval99** [Genymobile/scrcpy#2680]
adb devices
List of devices attached
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully
873c34960121    device

C:\Mirror>scrcpy
scrcpy-server.jar: 1 file pushed.
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
ERROR: Could not open video stream
ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2024)
        at android.media.MediaCodec.configure(MediaCodec.java:1952)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:135)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:62)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:22)
        at com.genymobile.scrcpy.Server.main(Server.java:78)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
INFO: Initial texture: 1080x2336

**Comment by rom1v** [comment]
> adb server version (41) doesn't match this client (39); killing...

adb server version (41) doesn't match this client (39); killing...

> Error 0xfffffff4

See #73 #833.
