### ISSUE TITLE
Unable to run scrcpy on Nokia X20 TA-1341

### ISSUE THREAD

**Issue by HikariCalyx** [Genymobile/scrcpy#2688]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.19
 - installation method: Windows release
 - device model: Nokia X20 TA-1341
 - Android version: 11
 - Phone kernel version: 
```
 Linux localhost 5.4.61-qgki-ge493356048db #1 SMP PREEMPT Thu Apr 1 16:13:22 UTC 2021 aarch64
```
**Describe the bug**
Unable to run the scrcpy.

Console output:
```
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
C:\Users\user\Downloads\scrcpy-win64-v1.19\scrcpy-server: 1 file pushed, 0 skipped. 28.8 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: HMD Global Nokia X20 (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2127)
        at android.media.MediaCodec.configure(MediaCodec.java:2043)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
WARN: Killing the server...

```

ADB logcat relevent to scrcpy-server:
```
10-07 13:10:24.027  9582  9582 D AndroidRuntime: Shutting down VM
10-07 13:10:24.028  9582  9582 E AndroidRuntime: FATAL EXCEPTION: main
10-07 13:10:24.028  9582  9582 E AndroidRuntime: PID: 9582
10-07 13:10:24.028  9582  9582 E AndroidRuntime: java.lang.IllegalArgumentException
10-07 13:10:24.028  9582  9582 E AndroidRuntime: 	at android.media.MediaCodec.native_configure(Native Method)
10-07 13:10:24.028  9582  9582 E AndroidRuntime: 	at android.media.MediaCodec.configure(MediaCodec.java:2127)
10-07 13:10:24.028  9582  9582 E AndroidRuntime: 	at android.media.MediaCodec.configure(MediaCodec.java:2043)
10-07 13:10:24.028  9582  9582 E AndroidRuntime: 	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
10-07 13:10:24.028  9582  9582 E AndroidRuntime: 	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
10-07 13:10:24.028  9582  9582 E AndroidRuntime: 	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
10-07 13:10:24.028  9582  9582 E AndroidRuntime: 	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
10-07 13:10:24.028  9582  9582 E AndroidRuntime: 	at com.genymobile.scrcpy.Server.main(Server.java:255)
10-07 13:10:24.028  9582  9582 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-07 13:10:24.028  9582  9582 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
10-07 13:10:24.028  9582  9582 E scrcpy  : Exception on thread Thread[main,5,main]
10-07 13:10:24.028  9582  9582 E scrcpy  : java.lang.IllegalArgumentException
10-07 13:10:24.028  9582  9582 E scrcpy  : 	at android.media.MediaCodec.native_configure(Native Method)
10-07 13:10:24.028  9582  9582 E scrcpy  : 	at android.media.MediaCodec.configure(MediaCodec.java:2127)
10-07 13:10:24.028  9582  9582 E scrcpy  : 	at android.media.MediaCodec.configure(MediaCodec.java:2043)
10-07 13:10:24.028  9582  9582 E scrcpy  : 	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
10-07 13:10:24.028  9582  9582 E scrcpy  : 	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
10-07 13:10:24.028  9582  9582 E scrcpy  : 	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
10-07 13:10:24.028  9582  9582 E scrcpy  : 	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
10-07 13:10:24.028  9582  9582 E scrcpy  : 	at com.genymobile.scrcpy.Server.main(Server.java:255)
10-07 13:10:24.028  9582  9582 E scrcpy  : 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-07 13:10:24.028  9582  9582 E scrcpy  : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)

```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by HikariCalyx** [comment]
Ah, NVM this command worked out:
```
scrcpy -m 720
```
