### ISSUE TITLE
can not start the program with "--stay-awake"

### ISSUE THREAD

**Issue by x7night** [Genymobile/scrcpy#2699]
**can not start the program with "--stay-awake"**
**os: win 10
device: Oneplus LE2100 (Android 11)**

```
PS C:\Users\Desktop\scrcpy-win64-v1.19> .\scrcpy.exe --stay-awake
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
C:\Users\Desktop\scrcpy-win64-v1.19\scrcpy-server... file pushed, 0 skipped. 46.7 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: OnePlus LE2100 (Android 11)
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:108)
        at com.genymobile.scrcpy.wrappers.ContentProvider.putValue(ContentProvider.java:161)
        at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:167)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:39)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:419)
Caused by: java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
        at android.os.Parcel.createException(Parcel.java:2373)
        at android.os.Parcel.readException(Parcel.java:2356)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:733)
        ... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2368)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1413)
        at com.android.providers.settings.SettingsProvider.insertGlobalSetting(SettingsProvider.java:1367)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:501)
        at android.content.ContentProvider.call(ContentProvider.java:2448)
```

**Comment by PallavRastogi** [comment]
same issue was happening to me, i fixed it by toggling "stay-awake when charging" and rebooting. i dont know how, but it was fixed

**Comment by tomcolley1962** [comment]
I had the same problem - device not staying awake when executing scrcpy with --stay-awake option, but I solved it differently. I mention this different solution as it might be relevant to further development of scrcpy. 

I had the same line amongst the output from executing scrcpy --stay-awake:
`Caused by: java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS`

I noticed that @rom1v suggested querying and changing the relevant setting directly via adb - see [https://github.com/Genymobile/scrcpy/issues/2612#issuecomment-913036144](https://github.com/Genymobile/scrcpy/issues/2612#issuecomment-913036144). I attempted the change command:
`adb shell settings put global stay_on_while_plugged_in 7`
and got this error:
`adb shell settings put global stay_on_while_plugged_in 7 Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS`

I search this last error statement and tried the solution found [here](https://forum.xda-developers.com/t/i-cant-enable-write_secure_settings-for-an-app-over-adb.3855596/#post-79510793). i.e. On the android phone, go to Settings > Developer Options > Disable permission monitoring. Set this option to disable. Having done this, I no longer get errors when running the scrcpy or adb commands above. The terminology and menu structure that I mention here may be specific to my Android OS (Oppo ColorOS V7.1)

The question (perhaps) for developer/s is whether this setting could be adjusted by scrcpy while it runs, potentially avoiding this whole issue.

**Comment by rom1v** [comment]
> The question (perhaps) for developer/s is whether this setting could be adjusted by scrcpy while it runs, potentially avoiding this whole issue.

Probably not: if the vendor added an option to prevent writing secure settings via adb, they would not allow to disable this setting va adb.
