### ISSUE TITLE
How to solve this issue on windows 10 

### ISSUE THREAD

**Issue by afznov** [Genymobile/scrcpy#2700]
```
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
D:\Portable\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 35.5 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: Xiaomi Redmi 9T, Note 9 4G, 9 Power (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2127)INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336

        at android.media.MediaCodec.configure(MediaCodec.java:2043)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:401)
WARN: Device disconnected
WARN: Killing the server...
Press any key to continue . . .
```

 

- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by afznov** [comment]
> See #833.
none is work
