### ISSUE TITLE
scrcpy fails to start

### ISSUE THREAD

**Issue by MightyM17** [Genymobile/scrcpy#2717]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Manjaro/Arch Linux
 - scrcpy version: 1.19
 - installation method: AUR
 - device model: Samsung Galaxy Tab 2 3G
 - Android version: 8.1.0

**Describe the bug**
Scrcpy does not work at all, possibly an issue due to PowerVR GPU/TI Hardware encoder.

On errors, please provide the output of the console (and `adb logcat` if relevant).

scrcpy
```
scrcpy                                                                                                   
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 104.1 MB/s (37330 bytes in 0.000s)
[server] INFO: Device: Samsung Galaxy Tab 2 3G (Android 8.1.0)
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 21.2.3
INFO: Trilinear filtering enabled
INFO: Initial texture: 600x1024
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1943)
        at android.media.MediaCodec.configure(MediaCodec.java:1872)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
WARN: Killing the server...
```
scrcpy -m 1024
```
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 190.7 MB/s (37330 bytes in 0.000s)
[server] INFO: Device: Samsung Galaxy Tab 2 3G (Android 8.1.0)
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 21.2.3
INFO: Trilinear filtering enabled
INFO: Initial texture: 600x1024
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1943)
        at android.media.MediaCodec.configure(MediaCodec.java:1872)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
WARN: Killing the server...
```
logcat
```
10-19 23:38:06.146   477   477 I com.android.phone: Looking for service android.hardware.radio@1.0::IRadio/slot1
10-19 23:38:06.147   125   125 W /system/bin/hwservicemanager: getTransport: Cannot find entry android.hardware.radio@1.0::IRadio/slot1 in either framework or device manifest.
10-19 23:38:06.149   477   477 I com.android.phone: Looking for service android.hardware.radio.deprecated@1.0::IOemHook/slot1
10-19 23:38:06.150   125   125 W /system/bin/hwservicemanager: getTransport: Cannot find entry android.hardware.radio.deprecated@1.0::IOemHook/slot1 in either framework or device manifest.
10-19 23:38:06.381  1959  1959 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
10-19 23:38:06.400  1959  1959 W app_process: Could not reserve sentinel fault page
10-19 23:38:06.705  1959  1959 W app_process: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
10-19 23:38:06.713  1959  1959 I app_process: The ClassLoaderContext is a special shared library.
10-19 23:38:06.803  1959  1959 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
10-19 23:38:06.807  1959  1959 I scrcpy  : Device: Samsung Galaxy Tab 2 3G (Android 8.1.0)
10-19 23:38:06.849  1959  1959 I app_process: Thread[1,tid=1959,Native,Thread*=0xa821d000,peer=0x12c01d10,"main"] recursive attempt to load library "/system/lib/libmedia_jni.so"
10-19 23:38:06.850  1959  1959 D MtpDeviceJNI: register_android_mtp_MtpDevice
10-19 23:38:06.851  1959  1959 I app_process: Thread[1,tid=1959,Native,Thread*=0xa821d000,peer=0x12c01d10,"main"] recursive attempt to load library "/system/lib/libmedia_jni.so"
10-19 23:38:06.851  1959  1959 I app_process: Thread[1,tid=1959,Native,Thread*=0xa821d000,peer=0x12c01d10,"main"] recursive attempt to load library "/system/lib/libmedia_jni.so"
10-19 23:38:06.864   181   181 I OMXMaster: makeComponentInstance(OMX.TI.DUCATI1.VIDEO.H264E) in android.hardwar process
10-19 23:38:06.917   181   427 D DOMX    : hardware/ti/omap4/domx/domx/omx_proxy_common/src/omx_proxy_common.c:1959     PROXY_GetExtensionIndex()
10-19 23:38:06.917   181   427 D DOMX    : ERROR: failed check:(eError == OMX_ErrorNone) || (eError == OMX_ErrorNoMore) - returning error: 0x8000101a - Error returned from OMX API in ducati
10-19 23:38:06.923   181   427 D DOMX    : hardware/ti/omap4/domx/domx/omx_proxy_common/src/omx_proxy_common.c:1959     PROXY_GetExtensionIndex()
10-19 23:38:06.923   181   427 D DOMX    : ERROR: failed check:(eError == OMX_ErrorNone) || (eError == OMX_ErrorNoMore) - returning error: 0x8000101a - Error returned from OMX API in ducati
10-19 23:38:06.925   181   434 D DOMX    : hardware/ti/omap4/domx/domx/omx_proxy_common/src/omx_proxy_common.c:1959     PROXY_GetExtensionIndex()
10-19 23:38:06.926   181   434 D DOMX    : ERROR: failed check:(eError == OMX_ErrorNone) || (eError == OMX_ErrorNoMore) - returning error: 0x8000101a - Error returned from OMX API in ducati
10-19 23:38:06.927   181   187 D DOMX    : hardware/ti/omap4/domx/domx/omx_proxy_common/src/omx_proxy_common.c:1959     PROXY_GetExtensionIndex()
10-19 23:38:06.927   181   187 D DOMX    : ERROR: failed check:(eError == OMX_ErrorNone) || (eError == OMX_ErrorNoMore) - returning error: 0x8000101a - Error returned from OMX API in ducati
10-19 23:38:06.930   181   181 D DOMX    : hardware/ti/omap4/domx/domx/omx_proxy_common/src/omx_proxy_common.c:1959     PROXY_GetExtensionIndex()
10-19 23:38:06.930   181   181 D DOMX    : ERROR: failed check:(eError == OMX_ErrorNone) || (eError == OMX_ErrorNoMore) - returning error: 0x8000101a - Error returned from OMX API in ducati
10-19 23:38:06.938   181   434 D DOMX    : hardware/ti/omap4/domx/domx/omx_proxy_common/src/omx_proxy_common.c:1959     PROXY_GetExtensionIndex()
10-19 23:38:06.938   181   434 D DOMX    : ERROR: failed check:(eError == OMX_ErrorNone) || (eError == OMX_ErrorNoMore) - returning error: 0x8000101a - Error returned from OMX API in ducati
10-19 23:38:06.939  1959  1974 W OMXUtils: do not know color format 0x7f000789 = 2130708361
10-19 23:38:06.939   181   187 D vndksupport: Loading /vendor/lib/hw/gralloc.omap4.so from current namespace instead of sphal namespace.
10-19 23:38:06.943   181   181 D vndksupport: Loading /vendor/lib/hw/gralloc.omap4.so from current namespace instead of sphal namespace.
10-19 23:38:06.945   181   181 D DOMX    : hardware/ti/omap4/domx/domx/omx_proxy_common/src/omx_proxy_common.c:1410     __PROXY_SetParameter()
10-19 23:38:06.945   181   181 D DOMX    : ERROR: failed check:(eError == OMX_ErrorNone) || (eError == OMX_ErrorNoMore) - returning error: 0x80001019 - Error returned from OMX API in ducati
10-19 23:38:06.945   181   181 D DOMX    : hardware/ti/omap4/domx/omx_proxy_component/omx_video_enc/src/omx_h264_enc/src/omx_proxy_h264enc.c:638      LOCAL_PROXY_H264E_SetParameter()
10-19 23:38:06.945   181   181 D DOMX    : ERROR: failed check:eError == OMX_ErrorNone - returning error: 0x80001019 -  Error in Proxy SetParameter
10-19 23:38:06.945   181   181 E OMXNodeInstance: setParameter(0xafd187e0:TI.DUCATI1.H264E, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
10-19 23:38:06.946  1959  1974 E ACodec  : [OMX.TI.DUCATI1.VIDEO.H264E] failed to set input port definition parameters.
10-19 23:38:06.946  1959  1974 E ACodec  : [OMX.TI.DUCATI1.VIDEO.H264E] configureCodec returning error -1010
10-19 23:38:06.946  1959  1974 E ACodec  : signalError(omxError 0x80001001, internalError -1010)
10-19 23:38:06.946  1959  1973 E MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3
10-19 23:38:06.947  1959  1959 E MediaCodec: configure failed with err 0xfffffc0e, resetting...
10-19 23:38:06.958   181   434 I OMXMaster: makeComponentInstance(OMX.TI.DUCATI1.VIDEO.H264E) in android.hardwar process
10-19 23:38:06.981  1959  1959 D AndroidRuntime: Shutting down VM
10-19 23:38:06.984  1959  1959 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
10-19 23:38:06.984  1959  1959 E AndroidRuntime: android.media.MediaCodec$CodecException: Error 0xfffffc0e
10-19 23:38:06.984  1959  1959 E AndroidRuntime:        at android.media.MediaCodec.native_configure(Native Method)
10-19 23:38:06.984  1959  1959 E AndroidRuntime:        at android.media.MediaCodec.configure(MediaCodec.java:1943)
10-19 23:38:06.984  1959  1959 E AndroidRuntime:        at android.media.MediaCodec.configure(MediaCodec.java:1872)
10-19 23:38:06.984  1959  1959 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
10-19 23:38:06.984  1959  1959 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
10-19 23:38:06.984  1959  1959 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
10-19 23:38:06.984  1959  1959 E AndroidRuntime:        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
10-19 23:38:06.984  1959  1959 E AndroidRuntime:        at com.genymobile.scrcpy.Server.main(Server.java:255)
10-19 23:38:06.984  1959  1959 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-19 23:38:06.984  1959  1959 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
10-19 23:38:06.985  1959  1959 E scrcpy  : Exception on thread Thread[main,5,main]
10-19 23:38:06.985  1959  1959 E scrcpy  : android.media.MediaCodec$CodecException: Error 0xfffffc0e
10-19 23:38:06.985  1959  1959 E scrcpy  :      at android.media.MediaCodec.native_configure(Native Method)
10-19 23:38:06.985  1959  1959 E scrcpy  :      at android.media.MediaCodec.configure(MediaCodec.java:1943)
10-19 23:38:06.985  1959  1959 E scrcpy  :      at android.media.MediaCodec.configure(MediaCodec.java:1872)
10-19 23:38:06.985  1959  1959 E scrcpy  :      at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
10-19 23:38:06.985  1959  1959 E scrcpy  :      at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
10-19 23:38:06.985  1959  1959 E scrcpy  :      at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
10-19 23:38:06.985  1959  1959 E scrcpy  :      at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
10-19 23:38:06.985  1959  1959 E scrcpy  :      at com.genymobile.scrcpy.Server.main(Server.java:255)
10-19 23:38:06.985  1959  1959 E scrcpy  :      at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-19 23:38:06.985  1959  1959 E scrcpy  :      at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
10-19 23:38:07.005  1959  1959 E scrcpy  : The hardware encoder is not able to encode at the given definition.
10-19 23:38:07.006  1959  1959 E scrcpy  : Try with a lower definition:
10-19 23:38:07.007  1959  1959 E scrcpy  :     scrcpy -m 1024
10-19 23:38:07.726  1969  1969 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
10-19 23:38:07.744  1969  1969 W app_process: Could not reserve sentinel fault page
10-19 23:38:08.002   181   181 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
10-19 23:38:08.059  1969  1969 W app_process: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
10-19 23:38:08.067  1969  1969 I app_process: The ClassLoaderContext is a special shared library.
10-19 23:38:08.180  1969  1969 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.CleanUp
10-19 23:38:08.183  1969  1969 I scrcpy  : Cleaning up
10-19 23:38:08.190  1969  1969 I scrcpy  : Restoring normal power mode
10-19 23:38:08.195   165   165 D SurfaceFlinger: Set power mode=2, type=0 flinger=0xb4236000
10-19 23:38:08.195   165   165 D SurfaceFlinger: Screen type=0 is already mode=2
10-19 23:38:08.197  1969  1969 D AndroidRuntime: Shutting down VM
```

**Comment by MightyM17** [comment]
Needed to change the encoder `scrcpy --encoder 'OMX.google.h264.encoder'` writing here for future reference
