### ISSUE TITLE
scrcpy not working on android 12

### ISSUE THREAD

**Issue by Frazzle1** [Genymobile/scrcpy#2720]
I was using scrcpy with my phone running android 11 and had no problems displaying the phone on my computer screen. Since upgrading to android 12 on my phone the screen mirroring application no longer works. Any suggestions regarding compatibility with android 12 and what I might need to do to get it working again?

**Comment by rom1v** [comment]
> far to quick to read anything on the screen

Run `scrcpy-console.bat`.

**Comment by CyferBoy** [comment]
![Screenshot (24)](https://user-images.githubusercontent.com/70091085/160523148-e5ce1924-7a48-4c73-b9c5-6efd904aae5d.png)

**Comment by rom1v** [comment]
#3051

**Comment by saif822** [comment]
Anyone found any solution to run the scrcpy in MI redmi10 ,A12??

**Comment by freefire1203** [comment]
Can't mirror the protected contents in the new version

**Comment by freefire1203** [comment]
> 

@rom1v Is there any solution for this

**Comment by rom1v** [comment]
@freefire1203 No, it's expected: #2129

**Comment by theappideasankit** [comment]
How can i solve this error android 12
linux - ubuntu

INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 103.7 MB/s (24773 bytes in 0.000s)
INFO: Initial texture: 1080x2336
[server] ERROR: Exception on thread Thread[main,5,main]
WARN: Device disconnected
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:178)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:70)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
        at com.genymobile.scrcpy.Server.main(Server.java:163)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 6 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3241)
        at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2301)
        ... 8 more

**Comment by rom1v** [comment]
Android 12 requires scrcpy >= 1.18.

**Comment by theappideasankit** [comment]
i m using ubuntu 

> Android 12 requires scrcpy >= 1.18.

**Comment by rom1v** [comment]
Ubuntu 20.04 probably (which ships the old 1.12.1 version).

You could uninstall the package, and install the app manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple
