### ISSUE TITLE
Error when trying to use Screen Mirroring after a few seconds

### ISSUE THREAD

**Issue by AnaxMorden** [Genymobile/scrcpy#2739]
**Environment**
 - OS: Manjaro Linux x86_64 ( Arch Linux )
 - scrcpy version: scrcpy 1.19
 - installation method: AUR ( with pamac )
 - device model: M2101K6G ( Redmi Note 10 Pro )
 - Android version: 12 ( AOSP )
 - ADB method: ADB over Wifi

**Describe the bug**
After seeing the device screen for 5 seconds the window closes and an error appears in the console: 

`WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:114)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:95)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:255)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:357)`

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception
