### ISSUE TITLE
CRITICAL: Could not initialize SDL: windib not available

### ISSUE THREAD

**Issue by TerraTech** [Genymobile/scrcpy#2742]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 Pro N  [20H2] [19042.1320]
 - scrcpy version: 1.19
 - installation method: Chocolatey
 - device model: Google Pixel 6 Pro
 - Android version: 12

**Describe the bug**
Upon starting `scrcpy`, the following error occurred:
`CRITICAL: Could not initialize SDL: windib not available`

Both `scrcpy` and `adb` were installed via `choco`

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
F:\>scrcpy
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
C:\ProgramData\chocolatey\lib\scrcpy\tools\scrcpy-server: 1 file pushed, 0 skipped. 33.8 MB/s (37330 bytes in 0.001s)
CRITICAL: Could not initialize SDL: windib not available
[server] INFO: Device: Google Pixel 6 Pro (Android 12)
[server] ERROR: Exception on thread Thread[main,5,main]
java.io.IOException: Connection refused
        at android.net.LocalSocketImpl.connectLocal(Native Method)
        at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:259)
        at android.net.LocalSocket.connect(LocalSocket.java:148)
        at com.genymobile.scrcpy.DesktopConnection.connect(DesktopConnection.java:40)
        at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:63)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:57)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

**Comment by rom1v** [comment]
Try with another SDL version (replace `SDL2.dll` with one from the release archive of an older scrcpy version).

**Comment by TerraTech** [comment]
I'm not sure if that would help because I think the underlying issue may be that my Windows 10 system is using DirectX 12 - which I don't believe SDL fully supports yet.  I think the max supported right now is DirectX 11.

Can anyone confirm this suspicion?

@rom1v What SDL (_or scrcpy version_) would you recommend?
