### ISSUE TITLE
scrpy only works with a specific decoder

### ISSUE THREAD

**Issue by iamagoogler** [Genymobile/scrcpy#2761]
Hi, I am just wondering. 
Is there any way we could fix this on the Android Side? 

scrcpy works on 2336X1080 using the AVC encoder. I can't figure out what is the default encoder used. 
Maybe you know something like editing the xml's on it?
[Debug Log+](https://pastebin.com/hKwRjMct)

**Comment by rom1v** [comment]
Without root, I guess you can't change the default encoder.

**Comment by iamagoogler** [comment]
I do have root actually, it's been bugging me for days. I wonder If you how to do it? the error on the recorder shows like this exactly here:

```
10-24 03:57:39.811 24987 24987 W System.err: java.lang.IllegalArgumentException: unsupported size

10-24 03:57:39.811 24987 24987 W System.err: at android.media.MediaCodecInfo$VideoCapabilities.getSupportedFrameRatesFor(MediaCodecInfo.java:1676)

10-24 03:57:39.811 24987 24987 W System.err: at com.android.systemui.screenrecord.ScreenMediaRecorder.getSupportedSize(ScreenMediaRecorder.java:254)
```
I can't find any tutorial or guide somewhere to be honest.

**Comment by rom1v** [comment]
> java.lang.IllegalArgumentException: unsupported size

What is the device size reported by scrcpy? (`New texture: ` in the console)

**Comment by iamagoogler** [comment]
It was 1080X2336 using AVC, OMX doesn't work as well

**Comment by rom1v** [comment]
Even with a lower definition? (`scrcpy -m 1024`)

**Comment by iamagoogler** [comment]
yep, the same error
