### ISSUE TITLE
Cannot import sound with sndcpy

### ISSUE THREAD

**Issue by AqilJaafree** [Genymobile/scrcpy#2765]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: window 10 [e.g. Debian, Windows, macOS...]
 - scrcpy version:  1.19 [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model: poco x3 pro
 - Android version:  android 11 [e.g. 10]

**Describe the bug**
I installed the sndcpy in the phone, when I tried to run the app at the PC, Suddenly the app deleted by itself
scrcpy just working fine.
On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```Waiting for device...
Performing Streamed Install
adb: failed to install sndcpy.apk:
Exception occurred while executing 'install':
java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
        at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:612)
        at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:485)
        at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCUninstalling existing version first...
Success
Performing Streamed Install
adb: failed to install sndcpy.apk:
Exception occurred while executing 'install':
java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
        at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:612)
        at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:485)
        at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCFailed with error #1.
Press any key to continue . . .



Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
https://github.com/rom1v/sndcpy/issues/39
