### ISSUE TITLE
How to set scrcpy release media codec instance?

### ISSUE THREAD

**Issue by LaurenLong** [Genymobile/scrcpy#2766]
I'm using scrcpy for record phone screen as video, every time I use command to kill scrcpy.exe to stop recording, but it seems scrcpy did not release media codec instance in android, max media codec instance reached and start failed.

11-04 15:46:36.988  7774  7774 E AndroidRuntime: FATAL EXCEPTION: main
11-04 15:46:36.988  7774  7774 E AndroidRuntime: PID: 7774
11-04 15:46:36.988  7774  7774 E AndroidRuntime: android.media.MediaCodec$CodecException: start failed
11-04 15:46:36.988  7774  7774 E AndroidRuntime: 	at android.media.MediaCodec.native_start(Native Method)
11-04 15:46:36.988  7774  7774 E AndroidRuntime: 	at android.media.MediaCodec.start(MediaCodec.java:2234)
11-04 15:46:36.988  7774  7774 E AndroidRuntime: 	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:93)
11-04 15:46:36.988  7774  7774 E AndroidRuntime: 	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
11-04 15:46:36.988  7774  7774 E AndroidRuntime: 	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
11-04 15:46:36.988  7774  7774 E AndroidRuntime: 	at com.genymobile.scrcpy.Server.main(Server.java:255)
11-04 15:46:36.988  7774  7774 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-04 15:46:36.988  7774  7774 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:419)
11-04 15:46:36.988  7774  7774 E scrcpy  : Exception on thread Thread[main,5,main]
11-04 15:46:36.988  7774  7774 E scrcpy  : android.media.MediaCodec$CodecException: start failed
11-04 15:46:36.988  7774  7774 E scrcpy  : 	at android.media.MediaCodec.native_start(Native Method)
11-04 15:46:36.988  7774  7774 E scrcpy  : 	at android.media.MediaCodec.start(MediaCodec.java:2234)
11-04 15:46:36.988  7774  7774 E scrcpy  : 	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:93)
11-04 15:46:36.988  7774  7774 E scrcpy  : 	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
11-04 15:46:36.988  7774  7774 E scrcpy  : 	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
11-04 15:46:36.988  7774  7774 E scrcpy  : 	at com.genymobile.scrcpy.Server.main(Server.java:255)
11-04 15:46:36.988  7774  7774 E scrcpy  : 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-04 15:46:36.988  7774  7774 E scrcpy  : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:419)

**Comment by rom1v** [comment]
> every time I use command to kill scrcpy.exe to stop recording

What command do you use?

**Comment by LaurenLong** [comment]
start record command:
scrcpy.exe -s cafaeec3 --no-display --record E:\1636690472092.mp4

get pid:
wmic process where commandline="adb -s cafaeec3 shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.18 info 0 8000000 0 -1 false - true true 0 false false - - false" get handle

then:
taskkill /f /pid [pid]

**Comment by rom1v** [comment]
If you kill the server process, all resources should be released. If it is not the case, it's probably a bug in your ROM :/

**Comment by LaurenLong** [comment]
Thank you so much for your kindly reply!

**Comment by rom1v** [comment]
Instead, you could try to close the video socket, so the server will terminate normally (without being killed).

**Comment by LaurenLong** [comment]
What command should I use to close the video socket? Thanks.
