### ISSUE TITLE
[server] ERROR: Exception on thread Thread[main,5,main]

### ISSUE THREAD

**Issue by dsivasuthan** [Genymobile/scrcpy#2768]
Hello. Thanks for this awesome software. I have run into an issue shown below. It works on Windows flawlessly but on Pop OS. Any help is appreciated. Thanks.

PC
Pop OS 21.04 (stock Bash)
Linux 5.13.0-7620

Phone:
Android 12

Things I tried:

- Tried a different cable
- Tried different port
- Restarted PC
- Tried `scrcpy -m 1080` and `scrcpy -m 1024`

```
INFO: Initial texture: 1080x2160
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:357)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3145)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2214)
	... 9 more
WARN: Killing the server...
```

**Comment by rom1v** [comment]
You need scrcpy >= 1.18 for Android 12. See #2129.

**Comment by dsivasuthan** [comment]
Thank you for the quick update. I wasn't using the snap version which has the latest version.

Installed snap and it fixed the issue. Thanks.
