### ISSUE TITLE
rooted Android: java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe

### ISSUE THREAD

**Issue by sg552** [Genymobile/scrcpy#2769]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 18
 - scrcpy version: 1.19
 - installation method: manually build, and snap
 - device model: Xiaomi M2003J15SC (Android 10) ( Rooted )
 - Android version: [10]

**Describe the bug**

when I start `scrcpy`, it complains : `Failed to initialize video/avc, error 0xfffffffe`

I don't have any clue. 

```
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
DEBUG: Using server: /usr/local/share/scrcpy/scrcpy-server
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 105.7 MB/s (37330 bytes in 0.000s)
DEBUG: Screensaver enabled
[server] INFO: Device: Xiaomi M2003J15SC (Android 10)
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 19.2.8
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2336
DEBUG: Starting stream thread
DEBUG: End of frames
[server] DEBUG: Device message sender stopped
[server] DEBUG: Controller stopped
DEBUG: Receiver stopped
DEBUG: Video stream stopped
WARN: Device disconnected
DEBUG: quit...
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe
	at android.media.MediaCodec.native_setup(Native Method)
	at android.media.MediaCodec.<init>(MediaCodec.java:1864)
	at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1827)
	at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:180)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:78)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:255)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
DEBUG: Server terminated

```

**Comment by rom1v** [comment]
#2320

**Comment by BV9800** [comment]
I  have the same issue 

.....
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
....
....device disconnected



scrpy installed by 'sudo apt-get install scrcpy,' on a Kubuntu 21.10,  with packs like adb amd64 1.10 and scrcpy ...1.17 

The android 9 phone is a BV9800Pro from blackview,  not rooted, debug mode enabled, , USB connexion can be seen connected with 'adb devices' command 

but 'scrcpy,' command give the same problem after initiating opengl display on a java thread , just after disconnecting warning

i don't understand why the connexion is stopped 

I have tried other specific opengl options  on  the developpers parameters of the phone but the result is the same

**Comment by rom1v** [comment]
Any error in `adb logcat` when you run scrcpy?
