### ISSUE TITLE
can't see drm content

### ISSUE THREAD

**Issue by luvs01** [Genymobile/scrcpy#2809]
- [V] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [V] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...] windows 10
 - scrcpy version: [e.g. 1.12.1] 1.20
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...] windows release
 - device model: galaxy s20 plus
 - Android version: [e.g. 10] 12

**Describe the bug**
Almost all functions work normally, but DRM content is not displayed. Appears normally in Android version 11.

INFO: scrcpy 1.20 <https://github.com/Genymobile/scrcpy>
C:\Users\Administrator\Documents\scrcpy-win64\scrcpy-serve... file pushed, 0 skipped. 47.4 MB/s (37139 bytes in 0.001s)
[server] INFO: Device: samsung SM-G986N (Android 12)
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:108)
        at com.genymobile.scrcpy.wrappers.ContentProvider.getValue(ContentProvider.java:149)
        at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:165)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:39)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:370)
Caused by: java.lang.SecurityException: Calling uid: 2000 doesn't match source uid: 0
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
        at android.os.Parcel.createException(Parcel.java:2421)
        at android.os.Parcel.readException(Parcel.java:2404)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
        ... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
        at android.content.AttributionSource.enforceCallingUid(AttributionSource.java:239)
        at android.content.AttributionSource.<init>(AttributionSource.java:158)
        at android.content.AttributionSource$1.createFromParcel(AttributionSource.java:454)
        at android.content.AttributionSource$1.createFromParcel(AttributionSource.java:446)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:289)

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:108)
        at com.genymobile.scrcpy.wrappers.ContentProvider.putValue(ContentProvider.java:161)
        at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:167)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:39)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:370)
Caused by: java.lang.SecurityException: Calling uid: 2000 doesn't match source uid: 0
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
        at android.os.Parcel.createException(Parcel.java:2421)
        at android.os.Parcel.readException(Parcel.java:2404)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
        ... 8 more
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
[server] INFO: Device screen turned off

**Comment by rom1v** [comment]
The error in the console is not related to DRM content, and is fixed by #2802 on development branch.

It is expected that DRM content is not mirrored. See #2129.
