### ISSUE TITLE
[Question] scrcpy and waydroid

### ISSUE THREAD

**Issue by mizzunet** [Genymobile/scrcpy#2826]
I'm following error when I try to `scrcpy` for [waydroid](https://github.com/waydroid/waydroid)
```
~ scrcpy
INFO: scrcpy 1.20 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file...pped. 36.9 MB/s (37139 bytes in 0.001s)
[server] INFO: Device: Waydroid WayDroid x86_64 Device (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 21.2.5
INFO: Trilinear filtering enabled
INFO: Initial texture: 440x744
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2792)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:110)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:255)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
```
adb has connected
```
~  adb devices
List of devices attached
192.168.250.112:5555	device
```
But I cannot access `adb shell` I have `error: fork failed: No such device adb`

But shell can be accessed by via `waydroid shell`. 
No `waydroid pull` though

In this case, by any chance, can I make `scrcpy` working?

Thank you very much

**Comment by rom1v** [comment]
> But I cannot access adb shell

It seems you have, at least to execute a command non-interactively, since the server is executing.

Try:

```bash
adb shell echo hello
```

> ```
> INFO: Initial texture: 440x744
> …
> [server] ERROR: Exception on thread Thread[main,5,main]
> java.lang.IllegalStateException
>	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
```

Probably no hardware encoder available to encode the screen surface.

Btw, you could try to list the [encoders](https://github.com/Genymobile/scrcpy#encoder).

**Comment by mizzunet** [comment]
> adb shell echo hello

Great, it executes

**Comment by mizzunet** [comment]
> Btw, you could try to list the [encoders](https://github.com/Genymobile/scrcpy#encoder).
```
 ~  scrcpy --encoder _
INFO: scrcpy 1.20 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-...s (37139 bytes in 0.001s)
[server] INFO: Device: Waydroid WayDroid x86_64 Device (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 21.2.5
INFO: Trilinear filtering enabled
INFO: Initial texture: 440x744
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
	at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:173)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:74)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:255)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
[server] ERROR: Try to use one of the available encoders:
[server] ERROR:     scrcpy --encoder 'OMX.google.h264.encoder'
```
Then
```
 scrcpy --encoder OMX.google.h264.encoder
INFO: scrcpy 1.20 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-...s (37139 bytes in 0.001s)
[server] INFO: Device: Waydroid WayDroid x86_64 Device (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 21.2.5
INFO: Trilinear filtering enabled
INFO: Initial texture: 440x744
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2792)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:110)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:255)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
```
Fails

**Comment by mizzunet** [comment]
```
~  sudo waydroid shell
/system/bin/sh: No controlling tty: open /dev/tty: No such file or directory
/system/bin/sh: warning: won't have full job control
```
I have these two warning, that might be why `adb shell` fails

**Comment by mizzunet** [comment]
`adb push` fails as well
```
~ adb push test /sdcard
test: 1 file pushed, 0 skipped.
adb: error: failed to copy 'test' to '/sdcard/test': remote fchown failed: Operation not permitted
```

**Comment by mibofra** [comment]
Hi @mizzunet ! I think I can answer your issue. Probably you are working as described here: https://docs.waydro.id/faq/get-waydroid-to-work-through-a-vm . Simply, the encoder on the android side doesn't work with that.

I didn't try directly on bare metal (as I've a nvidia gpu), but with the default base.prop (so not following gudelines for nvidia/vm), but using it in vm, using a virtio-gpu (with accel enabled an properly setup), it works without issues :)

```
test@testvm:~$ scrcpy 
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 49.6 MB/s (34012 bytes in 0.001s)
[server] INFO: Device: Google Android SDK built for x86_64 (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 3.1 Mesa 21.2.2
INFO: Trilinear filtering enabled
INFO: Initial texture: 1848x952
WARN: Killing the server...
```
So at least with waydroid 1.2.0 from the official debian package from the official repo.

Feedbacks are welcome!

**Comment by gaussandhisgun** [comment]
Yo, any updates on this situation? I got Waydroid installed and working recently, and I get a slightly different log from scrcpy:
```
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 18.3 MB/s (41123 bytes in 0.002s)
[server] INFO: Device: Waydroid WayDroid x86 Device (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 3.3.0 NVIDIA 340.108
INFO: Trilinear filtering enabled
INFO: Initial texture: 1280x688
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0x80000000
[server] INFO: Retrying with -m1024...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0x80000000
[server] INFO: Retrying with -m800...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0x80000000
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0x80000000
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2026)
        at android.media.MediaCodec.configure(MediaCodec.java:1954)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:282)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:97)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:331)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
```
I use LOS 17.1 as 18.1 is still in development.

**Comment by assiless** [comment]
i have the same issue with latest [2022-07-23 waydroid 10 LOS 17.1](https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/)
```
$ scrcpy -s 192.168.240.112:5555
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 23.8 MB/s (39473 bytes in 0.002s)
[server] INFO: Device: Waydroid WayDroid x86_64 Device (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 3.1 Mesa 22.0.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 1320x736
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2792)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:110)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
```

> Some user have reported scrpy got working on LOS 18.1

you're right i tested [2021-12-13 waydroid 11 LOS 18.1](https://sourceforge.net/projects/blissos-dev/files/waydroid/lineage/lineage-18.1/) and it's working BUT `2021-12-13` IT'S TOO OLD and i can't use it because scrolling inverted

**Comment by gasacchi** [comment]
any update for this?

**Comment by jaysonwcs** [comment]
I think this is not priority =(

**Comment by AndnixSH** [comment]
Getting different issue on Linux mint 21.1 with Waydroid gapps

```
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...ed. 122.6 MB/s (39473 bytes in 0.000s)
[server] INFO: Device: Waydroid WayDroid x86_64 Device (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 470.199.02
INFO: Trilinear filtering enabled
INFO: Initial texture: 1024x568
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0x80000000
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2127)
	at android.media.MediaCodec.configure(MediaCodec.java:2043)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
WARN: Killing the server...

```

**Comment by DieALot36T9** [comment]
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.240.112:5555            device  WayDroid_x86_64_Device
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 72.6 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [Waydroid] waydroid WayDroid x86_64 Device (Android 11)
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0x80000000
[server] INFO: Retrying with -m1024...
[server] INFO: Retrying...
[server] ERROR: Could not create default audio encoder for opus
List of audio encoders:
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
    --audio-codec=flac --audio-encoder='OMX.google.flac.encoder'
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe
	at android.media.MediaCodec.native_setup(Native Method)
	at android.media.MediaCodec.<init>(MediaCodec.java:1912)
	at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1875)
	at com.genymobile.scrcpy.AudioEncoder.createMediaCodec(AudioEncoder.java:289)
	at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:181)
	at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:121)
	at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0x80000000
[server] INFO: Retrying with -m800...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0x80000000
[server] ERROR: Exception on thread Thread[video,5,main]
android.media.MediaCodec$CodecException: Error 0x80000000
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2127)
	at android.media.MediaCodec.configure(MediaCodec.java:2043)
	at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:69)
	at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
	at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 24.0.7-arch1.3
INFO: Trilinear filtering enabled
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1280x720
WARN: Device disconnected




same here

**Comment by rom1v** [comment]
> java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe

You device has no opus encoder. Use `scrcpy --audio-codec=aac`.

**Comment by DieALot36T9** [comment]
> > java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe
> 
> You device has no opus encoder. Use `scrcpy --audio-codec=aac`.

[diealot@archmachine ~]$ scrcpy --audio-codec=aac
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.240.112:5555            device  WayDroid_x86_64_Device
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 27.9 MB/s (69007 bytes in 0.002s)
[server] INFO: Device: [Waydroid] waydroid WayDroid x86_64 Device (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 24.0.7-arch1.3
INFO: Trilinear filtering enabled
INFO: Texture: 1280x720
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1024...
[server] INFO: Retrying...
[server] ERROR: Exception on thread Thread[audio-in,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_queueInputBuffer(Native Method)
	at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2559)
	at com.genymobile.scrcpy.AudioEncoder.inputThread(AudioEncoder.java:98)
	at com.genymobile.scrcpy.AudioEncoder.lambda$encode$1$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:195)
	at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_stop(Native Method)
	at android.media.MediaCodec.stop(MediaCodec.java:2251)
	at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:264)
	at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:121)
	at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)
[server] INFO: Retrying with -m800...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
	at com.genymobile.scrcpy.SurfaceEncoder.encode(SurfaceEncoder.java:157)
	at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:76)
	at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
	at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)
WARN: Device disconnected

and
.
.[diealot@archmachine ~]$ scrcpy --no-audio 
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.240.112:5555            device  WayDroid_x86_64_Device
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 18.6 MB/s (69007 bytes in 0.004s)
[server] INFO: Device: [Waydroid] waydroid WayDroid x86_64 Device (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 24.0.7-arch1.3
INFO: Trilinear filtering enabled
INFO: Texture: 1280x720
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1024...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m800...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
	at com.genymobile.scrcpy.SurfaceEncoder.encode(SurfaceEncoder.java:157)
	at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:76)
	at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
	at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)

.



also im on waydroid
