### ISSUE TITLE
ScrCpy not working on shell changed wm size to 2560x1080 (ultrawide) (21:9)

### ISSUE THREAD

**Issue by angelparaskov** [Genymobile/scrcpy#2893]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 Pro
 - scrcpy version: 1.16, 1.21
 - installation method: Windows release, via command prompt, adb version:
 C:\Programs\scrcpy>adb version
Android Debug Bridge version 1.0.41
Version 31.0.3-7562133
Installed as C:\Programs\scrcpy\adb.exe
 - device model: MX4 (RT-165) /Rockchip Rk3229
 - Android version: 5.1.1 - S.W.A.T.

**Describe the bug**
I was using scrcpy without any problem with MX4 (RT-165) in 1920x1080 for years.
Now it is connected to ultrawide monitor and I have found this article - https://www.reddit.com/r/fireTV/comments/geywyf/change_resolution_to_2560x1080_on_ultrawide/
So I did change it for my MX4 (RT-165) adb shell wm size 2560x1080 and it is working almost ok(sometimes you need to double start google play, youtube and few others, but they load the second time)
Unfortunately scrcpy do not and exits with Java error

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
`C:\Programs\scrcpy>scrcpy.exe
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
C:\Programs\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 4.9 MB/s (33622 bytes in 0.007s)
adb.exe: error: more than one device and emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
27183
[server] INFO: Device: rockchip RT-165 (Android 5.1.1)
INFO: Renderer: direct3d
INFO: Initial texture: 2560x1080
[server] ERROR: Exception on thread Thread[main,5,main]
WARN: Device disconnected
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
Press any key to continue...



C:\Programs\scrcpy>scrcpy.exe
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
C:\Programs\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 12.0 MB/s (40067 bytes in 0.003s)
adb.exe: error: more than one device and emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
[server] INFO: Device: rockchip RT-165 (Android 5.1.1)
INFO: Renderer: direct3d
INFO: Initial texture: 2560x1080
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:110)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
        at com.genymobile.scrcpy.Server.main(Server.java:309)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)`
```

Extra checks to provide(as have seen, when looking for "similar" bugs):
C:\Programs\scrcpy>adb shell echo hello
hello

C:\Programs\scrcpy>adb unroot
adb: unable to connect for unroot: closed

adb logcat file(quite big)
[output.zip](https://github.com/Genymobile/scrcpy/files/7750946/output.zip)

For any other questions, please ask, I'm Java developer myself(but not Android) and can assist

**Comment by rom1v** [comment]
The device hardware encoder is not able to encode at the given definition:
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by angelparaskov** [comment]
> The device hardware encoder is not able to encode at the given definition: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

Worked like a charm!
Thank you so much, I do not need the full resolution, just to control it :)
Enjoy holidays!
Thanks again
