### ISSUE TITLE
write failed: EPIPE (ubuntu 16.04 -> Galaxy S4 - 5.0.1)

### ISSUE THREAD

**Issue by clmwith** [Genymobile/scrcpy#290]
Hi,

I've installed scrcpy as described but scrcpy hang without opening any window :
 
```
with@hp-clm:/tmp$ git clone https://github.com/Genymobile/scrcpy
Clonage dans 'scrcpy'...
remote: Enumerating objects: 125, done.
remote: Counting objects: 100% (125/125), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 2566 (delta 44), reused 106 (delta 32), pack-reused 2441
Réception d'objets: 100% (2566/2566), 586.51 KiB | 0 bytes/s, fait.
Résolution des deltas: 100% (1461/1461), fait.
Vérification de la connectivité... fait.
with@hp-clm:/tmp$ cd scrcpy/
with@hp-clm:/tmp/scrcpy$ meson x --buildtype release --strip -Db_lto=true -Dprebuilt_server=/tmp/scrcpy-server-v1.4.jar 
The Meson build system
Version: 0.40.1
Source dir: /tmp/scrcpy
Build dir: /tmp/scrcpy/x
Build type: native build
Project name: scrcpy
Native c compiler: ccache cc (gcc 5.4.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libavformat found: YES 56.40.101
Native dependency libavcodec found: YES 56.60.100
Native dependency libavutil found: YES 54.31.100
Native dependency sdl2 found: YES 2.0.4
Configuring config.h using configuration
Build targets in project: 6
with@hp-clm:/tmp/scrcpy$ cd x
with@hp-clm:/tmp/scrcpy/x$ ninja
[17/31] Compiling c object 'app/scrcpy@exe/src_sys_unix_command.c.o'
../app/src/sys/unix/command.c: In function ‘cmd_terminate’:
../app/src/sys/unix/command.c:78:12: warning: implicit declaration of function ‘kill’ [-Wimplicit-function-declaration]
     return kill(pid, SIGTERM) != -1;
            ^
[31/31] Linking target app/scrcpy
with@hp-clm:/tmp/scrcpy/x$ ninja install
[0/1] Installing files.
Installing app/scrcpy to /usr/local/bin/scrcpy
Stripping target 'app/scrcpy'
Installing server/scrcpy-server.jar to /usr/local/share/scrcpy/scrcpy-server.jar
with@hp-clm:/tmp/scrcpy$ scrcpy 2>&1 
365 KB/s (18802 bytes in 0.050s)
INFO: Initial texture: 1080x1920
Assertion len >= s->orig_buffer_size failed at libavformat/aviobuf.c:479
Abandon
ERROR: Exception on thread Thread[main,5,main]
java.io.IOException: android.system.ErrnoException: write failed: EPIPE (Broken pipe)
	at com.genymobile.scrcpy.IO.writeFully(IO.java:22)
	at com.genymobile.scrcpy.IO.writeFully(IO.java:29)
	at com.genymobile.scrcpy.DesktopConnection.send(DesktopConnection.java:81)
	at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:58)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:16)
	at com.genymobile.scrcpy.Server.main(Server.java:102)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:255)
Caused by: android.system.ErrnoException: write failed: EPIPE (Broken pipe)
	at libcore.io.Posix.writeBytes(Native Method)
	at libcore.io.Posix.write(Posix.java:218)
	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:308)
	at android.system.Os.write(Os.java:528)
	at com.genymobile.scrcpy.IO.writeFully(IO.java:19)
	... 7 more
```

(it was compiled with meson_0.40.1 and ninja-build_1.7.1-1 from ubuntu backport)

What could be wrong please ?

Regards,

**Comment by rom1v** [comment]
> ```
> Assertion len >= s->orig_buffer_size failed at libavformat/aviobuf.c:479
> ```

A bug in libavformat. You should upgrade it to a newer version.

**Comment by clmwith** [comment]
Thanks for the answer.

No more chance with backported ffmpeg_3.4.4 (from 18.01 sources) :
337 KB/s (18802 bytes in 0.054s)
INFO: Initial texture: 1080x1920
ERROR: Could not open video stream

trying native 18.04 ...

**Comment by rom1v** [comment]
Since your device is 5.0.1, it may not be related to FFmpeg. Maybe #291 fixes your issue.

**Comment by clmwith** [comment]
Same thing with a freshen install of a 18.04.
It work well with a Galaxy A8 2018.


I used the scrcpy-server-test4 as described in th thread.
The result (PC side) :
3481 KB/s (47656 bytes in 0.013s)
INFO: Initial texture: 1080x1920
ERROR: Could not open video stream
DEBUG: Event controller stopped
ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:577)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:126)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:62)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:24)
	at com.genymobile.scrcpy.Server.main(Server.java:102)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:255)
with@hp-clm:~/tmp/scrcpy$ SCRCPY_SERVER_PATH=/tmp/scrcpy-server-test4.jar x/app/scrcpy
4115 KB/s (47656 bytes in 0.011s)
INFO: Initial texture: 1080x1920
ERROR: Exception on thread Thread[main,5,main]ERROR: Could not open video stream

DEBUG: Event controller stopped
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:577)
with@hp-clm:/tmp/scrcpy$ SCRCPY_SERVER_PATH=/tmp/scrcpy-server-test4.jar x/app/scrcpy
1976 KB/s (47656 bytes in 0.023s)

INFO: Initial texture: 1080x1920
ERROR: Exception on thread Thread[main,5,main]ERROR: Could not open video stream

DEBUG: Event controller stopped
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:577)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:126)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:62)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:24)


When i get output of /data/local/tmp/scrcpy-server-test4.jar (without -test4 in the name) with netcat it just print : GT-I95058�

**Comment by rom1v** [comment]
OK, so this is not the same error.

What if you decrease the definition?

    scrcpy -m 800

**Comment by clmwith** [comment]
scrcpy-server-test4.jar works until (including) -m 1365

with@comp:~/scrcpy$ ./run x -m 1365
[100%] /data/local/tmp/scrcpy-server.jar
INFO: Initial texture: 768x1360

Hangs after :
with@comp:~/scrcpy$ ./run x -m 1370
[100%] /data/local/tmp/scrcpy-server.jar
INFO: Initial texture: 768x1368
ERROR: Could not open video stream
DEBUG: Event controller stopped
ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:577)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:126)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:62)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:24)
	at com.genymobile.scrcpy.Server.main(Server.java:102)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:255)

on native ubuntu 18.04 64bits (not tested on 16.04 yet)

Thanks for the help and for the app !!
Regards,

**Comment by rom1v** [comment]
Ok, so your device does not support encoding at a higher definition.

**Comment by cleversboy** [comment]
same:
Assertion len >= s->orig_buffer_size failed at libavformat/aviobuf.c:518
