### ISSUE TITLE
[Win11][Android 10] Exception in main thread when attempting to connect

### ISSUE THREAD

**Issue by SHA-NDY** [Genymobile/scrcpy#2906]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 1.21
 - installation method: Windows release from GitHub
 - device model: Volla Phone
 - Android version: 10
 - Additional Info: De-Googled Android 10

**Describe the bug**
After executing the "scrcpy" command in the windows console it pushes the server-file and then throws an exception in the main thread.

I read about the "device disconnected" issues but neither another USB port worked nor another cable did the trick.

```
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
D:\WindowsData\Downloads\Scrcpy_win64\scrcpy-server: 1 file pushed, 0 skipped. 25.1 MB/s (40067 bytes in 0.002s)
[server] INFO: Device: alps Volla Phone (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:110)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
        at com.genymobile.scrcpy.Server.main(Server.java:309)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by SHA-NDY** [comment]
Thanks, I didn't read carefully enough. My mistake...
