### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by sobrinho** [Genymobile/scrcpy#2907]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS
 - scrcpy version: 1.21
 - installation method: brew
 - device model: Radxa Zero (building LineageOS from scratch, using this: https://gist.github.com/Stricted/ba08de125ddc8840dc7abdf489cb7222)
 - Android version: 11

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
/opt/homebrew/Cellar/scrcpy/1.21/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 38.1 MB/s (40067 bytes in 0.001s)
[server] INFO: Device: radxa Radxa Zero (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:30)
        at com.genymobile.scrcpy.Device.<init>(Device.java:64)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:63)
        at com.genymobile.scrcpy.Server.main(Server.java:309)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:17)
        ... 5 more
```

Please do not post screenshots of your terminal, just post the content as text instead.

There is a open issue since October, 2020 which does not solve the issue, seems to be the same.

**Comment by sobrinho** [comment]
https://github.com/Genymobile/scrcpy/issues/1818

**Comment by sobrinho** [comment]
Looks like my device is broken, nevermind, it is hanging on the boot animation.
