### ISSUE TITLE
Scrcpy Galaxy Tab a7

### ISSUE THREAD

**Issue by godofclash** [Genymobile/scrcpy#2913]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model: 
 - Android version: [e.g. 10]

**Describe the bug**
Everytime, i want to open the Program, it does show off this screen:
![image](https://user-images.githubusercontent.com/96917091/147828878-3af45649-6371-4f14-b636-323238be8e5c.png)
and the programm closes after some seconds
When i try it with my Galaxy Tab A, it actually does work

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Duplicate of #833.

(and please do not post a screenshot of text, post the text content instead between ```)

**Comment by godofclash** [comment]
it actually isnt a duplicate, the thing is, i cannot write in the program so i cant even fix the problem

**Comment by rom1v** [comment]
> i cannot write in the program so i cant even fix the problem

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by godofclash** [comment]
wich file do i have to plug in there, the whole file on scrcpy?

**Comment by godofclash** [comment]
@rom1v 
but how do i even write in the command section, everytime i want to write in there after opened the file on the command program, it does open a new section where i have to write another file name

**Comment by rom1v** [comment]
> but how do i even write in the command section, everytime i want to write in there after opened the file on the command program,

Follow the exacts steps here: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

At which step do you encounter a problem?

**Comment by godofclash** [comment]
@rom1v i did open it, but after i want to write in there, but it does want to open a new file

**Comment by rom1v** [comment]
Open a new file? What do you mean?

Copy the whole terminal content here (or post a screenshot if it involves more windows).

**Comment by godofclash** [comment]
@rom1v i actually did open it yesterday, but today i cant do so, because i dont know how i have to write down the path, could you may help me? the path is D: then Scrcpy and then scrcpy-server

**Comment by jian-x-li** [comment]
scrcpy-win64-v1.21\scrcpy-... file pushed, 0 skipped. 44.6 MB/s (40067 bytes in 0.001s)
[server] INFO: Device: samsung SM-T500 (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2127)
        at android.media.MediaCodec.configure(MediaCodec.java:2043)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
        at com.genymobile.scrcpy.Server.main(Server.java:309)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:409)
INFO: Renderer: direct3d
INFO: Initial texture: 1200x2000
WARN: Device disconnected
WARN: Killing the server...

**Comment by godofclash** [comment]
exactly this one came out there

**Comment by godofclash** [comment]
@rom1v
