### ISSUE TITLE
Failed to connect using TCP/IP

### ISSUE THREAD

**Issue by Nyakode** [Genymobile/scrcpy#2917]
**Environment**
 - OS: [Windows]
 - scrcpy version: [e.g. 1.21]
 - installation method: [Windows release...]
 - device model: samsung SM-J415F
 - Android version: [9]

**Describe the bug**
Trying to connect using TCP/IP failed.
On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.

C:\Users\user>scrcpy --tcpip=192.168.254.110
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
INFO: Connected to 192.168.254.110:5555
C:\Users\user\scrcpy-server: 1 file pus...pped. 34.4 MB/s (40067 bytes in 0.001s)
[server] INFO: Device: samsung SM-J415F (Android 9)
INFO: Renderer: direct3d
INFO: Initial texture: 720x1480
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1960)
        at android.media.MediaCodec.configure(MediaCodec.java:1889)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
        at com.genymobile.scrcpy.Server.main(Server.java:309)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:341)
WARN: Killing the server...
Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by Nyakode** [comment]
I was restarting the adb tcpip port again, and it works again. Guess those programmer quotes were true "Have you tried turning it off and on again?"
