### ISSUE TITLE
adb: error: closed ERROR: "adb reverse" returned with value 1

### ISSUE THREAD

**Issue by Dieldore** [Genymobile/scrcpy#2926]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:arch linux
 - scrcpy version: 1.21
 - installation method: pacman
 - device model:HTC HTC Explorer A310e
 - Android version: 2.3.5

**Describe the bug**
I run the program and nothing works! My phone screen is broken

```
[root@arch androidscreencast-0.1]# scrcpy 
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushe... 0 skipped. 96.7 MB/s (40067 bytes in 0.000s)
adb: error: closed
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
[server] INFO: Device: HTC HTC Explorer A310e (Android 2.3.5)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.ClassNotFoundException: android.hardware.display.IDisplayManager$Stub
	at com.genymobile.scrcpy.wrappers.ServiceManager.getService(ServiceManager.java:39)
	at com.genymobile.scrcpy.wrappers.ServiceManager.getDisplayManager(ServiceManager.java:52)
	at com.genymobile.scrcpy.Device.<init>(Device.java:64)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:63)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.finishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:257)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: android.hardware.display.IDisplayManager$Stub
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:234)
	at java.lang.Class.forName(Class.java:181)
	at com.genymobile.scrcpy.wrappers.ServiceManager.getService(ServiceManager.java:36)
	... 7 more
Caused by: java.lang.NoClassDefFoundError: android.hardware.display.IDisplayManager$Stub
	... 11 more
Caused by: java.lang.ClassNotFoundException: android.hardware.display.IDisplayManager$Stub in loader dalvik.system.PathClassLoader[/data/local/tmp/scrcpy-server.jar]
	at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:240)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:551)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	... 11 more
ERROR: Server connection failed
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
> INFO: Device: HTC HTC Explorer A310e (Android 2.3.5)

scrcpy requires Android >= 5.
