### ISSUE TITLE
failed to get tv camera

### ISSUE THREAD

**Issue by zuo-chao** [Genymobile/scrcpy#2942]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [ Windows]
 - scrcpy version: [1.18]
 - installation method: [ Windows release]
 - device model:HUAWEI THAL-560
 - Android version: [10]

**Describe the bug**
In cmd console, I inputed scrcpy.exe -Nr test.mp4, it failed. And I also used scrcpy version 1.21, it returned with the same error message.

scrcpy-win64-v1.21>scrcpy.exe -Nr test.mp4
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
scrcpy-win64-v1.21\scrcpy-serve... file pushed, 0 skipped. 13.0 MB/s (40067 bytes in 0.003s)
[server] INFO: Device: HUAWEI THAL-560 (Android 10)
INFO: Recording started to mp4 file: test.mp4
ERROR: Recording failed to test.mp4
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2131)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
        at com.genymobile.scrcpy.Server.main(Server.java:309)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

**Comment by zuo-chao** [comment]
it is ok after use scrcpy -m 1920

**Comment by rom1v** [comment]
Could you test this version please: https://github.com/Genymobile/scrcpy/pull/2947 (without any additional parameter like `-m1024`)

Does it work correctly? What is the full console output?
