### ISSUE TITLE
Seeing error after upgrading to OneUI 4.0 on Samsung device

### ISSUE THREAD

**Issue by ravichandranalam** [Genymobile/scrcpy#2967]
Seeing this error and scrcpy is not launching after upgrading to OneUI 4.0:2022-01-24 12:08:00.287 scrcpy[32323:1053593] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.17_1/share/...ped. 23.7 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: samsung SM-G985F (Android 12)
2022-01-24 12:08:01.196 scrcpy[32323:1053593] INFO: Renderer: metal
2022-01-24 12:08:01.200 scrcpy[32323:1053593] INFO: Initial texture: 1080x2400
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:374)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3372)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2346)
	... 9 more
2022-01-24 12:08:01.568 scrcpy[32323:1053593] WARN: Device disconnected
2022-01-24 12:08:02.572 scrcpy[32323:1053593] WARN: Killing the server...

**Comment by rom1v** [comment]
Use the latest version. Android 12 may not work before v1.18. #2129
