### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by DeadVice** [Genymobile/scrcpy#2972]
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 29.3 MB/s (40067 bytes in 0.001s)
[server] INFO: Device: HUAWEI JSN-L21 (Android 9)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0eWARN: Device disconnected

        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1967)
        at android.media.MediaCodec.configure(MediaCodec.java:1896)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
        at com.genymobile.scrcpy.Server.main(Server.java:309)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
Exit due to uncaughtException in main thread:

**Comment by rom1v** [comment]
See #2947.
