### ISSUE TITLE
custom android 12 root not working

### ISSUE THREAD

**Issue by Fitertom** [Genymobile/scrcpy#2988]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

 - OS: Windows 11
 - scrcpy version: 1.22
 - installation method: Windows release
 - device model:
 - Android version: 12

i use android 12 i really need a script on it but it doesn't work i looked at similar threads on this topic but didn't find anything

```
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
C:\Program Files\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 76.1 MB/s (40955 bytes in 0.001s)
[server] INFO: Device: Xiaomi Redmi Note 8 Pro (Android 12)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2284)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:97)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:326)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:357)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
WARN: Device disconnected
WARN: Killing the server...

**Comment by rom1v** [comment]
Oh, I think I missed to catch some errors to retry in #2947.

Could you please replace this file in v1.22, and post the whole console output?

 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2988/1/scrcpy-server) _sha256:2eef221b9ab37c6391a8a5324b5c8a9f9b7e45756b25f8b075ea9de21e0c7d52_

Thank you

**Comment by Fitertom** [comment]
> 

[server] INFO: Device: Xiaomi Redmi Note 8 Pro (Android 12)
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] INFO: Retrying with -m1920...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] INFO: Retrying with -m1600...
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] INFO: Retrying with -m1280...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] INFO: Retrying with -m1024...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] INFO: Retrying with -m800...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2284)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:99)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:326)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:357)

**Comment by rom1v** [comment]
OK, great, the retry mechanism now works in your case. But it seems your device can't encode the screen at any definition.

You could try with a different encoder: https://github.com/Genymobile/scrcpy#encoder

Also, does `screenrecord` work?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

**Comment by Fitertom** [comment]
> OK, great, the retry mechanism now works in your case. But it seems your device can't encode the screen at any definition.
> 
> You could try with a different encoder: https://github.com/Genymobile/scrcpy#encoder
> 
> Also, does `screenrecord` work?
> 
> ```
> adb shell screenrecord /sdcard/file.mp4
> adb pull /sdcard/file.mp4
> ```

C:\Users\Fitertomus\Downloads\Новая папка (2)>adb shell screenrecord /sdcard/file.mp4
ERROR: unable to start codec (err=-12)
WARNING: failed at 1080x2340, retrying at 720x1280
ERROR: unable to start codec (err=-12)
adb shell screenrecord /sdcard/file.mp4 - DONT WORK

C:\Users\Fitertomus\Downloads\Новая папка (2)>adb pull /sdcard/file.mp4
adb: error: failed to stat remote object '/sdcard/file.mp4': No such file or directory
adb pull /sdcard/file.mp4 - DONT WORK

C:\Users\Fitertomus\Downloads\Новая папка (2)>scrcpy --encoder 'OMX.google.h264.encoder'
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
C:\Users\Fitertomus\Downloads\Новая папка (2)\sc...file pushed, 0 skipped. 143.5 MB/s (96899 bytes in 0.001s)
[server] INFO: Device: Xiaomi Redmi Note 8 Pro (Android 12)
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] INFO: Retrying with -m1920...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1600...
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1280...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1024...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m800...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:151)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:101)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:326)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:357)
WARN: Killing the server...

C:\Users\Fitertomus\Downloads\Новая папка (2)>scrcpy --encoder 'OMX.MTK.VIDEO.ENCODER.AVC'
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
C:\Users\Fitertomus\Downloads\Новая папка (2)\sc...file pushed, 0 skipped. 146.1 MB/s (96899 bytes in 0.001s)
[server] INFO: Device: Xiaomi Redmi Note 8 Pro (Android 12)
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] INFO: Retrying with -m1920...
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1600...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1280...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1024...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m800...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:151)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:101)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:326)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:357)
WARN: Killing the server...

**Comment by Fitertom** [comment]
if anything on the official firmware miui 12.5 scrcpy worked without problems

**Comment by rom1v** [comment]
OK, if screenrecord does not work, then there's definitely a bug in the ROM.

**Comment by Fitertom** [comment]
> OK, if screenrecord does not work, then there's definitely a bug in the ROM.

I have a built-in screen recording on my phone and from the very beginning it doesn’t work, maybe it’s somehow related, but third-party recording applications asked for access to broadcast / screen recording, it’s possible and it’s somehow connected with this, maybe the protection of android 12 does not allow third-party programs to record screen without permission and these applications simply do not request it

**Comment by aa755** [comment]
I was getting the same error. once I started screen recording on android just once and stopped, scrcpy also started working.
