### ISSUE TITLE
phone screen closes instantly

### ISSUE THREAD

**Issue by manhek** [Genymobile/scrcpy#2998]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - Windows
 - scrcpy version: 1.22
 - installation method: idk windows?
 - device model: Smasung Galaxy S7 Edge
 - Android version: 8.0.0

**Describe the bug**
When opening the files "scrcpy.exe" and "scrcpy-noconsole.vbs" the phone screen should come up. When I do it the screen appears fo a millisecond and closes immediately. It says that the device disconnected. I tried changing the USB cable and the port already but none of it works fixing the issue.

**Comment by rom1v** [comment]
Please open `scrcpy-console.bat`, and post the whole output (as text, not a screenshot).

**Comment by akashksiju** [comment]
> Please open `scrcpy-console.bat`, and post the whole output (as text, not a screenshot).

I also have the same issue.. I am using POCO M3 Device. It does not work with this device but, I tried using my other phone and it works pretty well..

Posting the output....

scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
F:\Downloads\scrcpy-win64-v1.22\scrcpy-server: 1 file pushed, 0 skipped. 20.8 MB/s (40955 bytes in 0.002s)
[server] INFO: Device: Xiaomi M2010J19CI (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2127)
        at android.media.MediaCodec.configure(MediaCodec.java:2043)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:274)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:94)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:326)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:463)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
WARN: Device disconnected
WARN: Killing the server...
Press any key to continue . . .

**Comment by rom1v** [comment]
Try #2990.

**Comment by akashksiju** [comment]
> Try #2990.

Ohh now it started working... Thanks a lot...

**Comment by cds5296** [comment]
Environment

Windows 10
scrcpy version: 1.22
installation method: Windows download (zip)
device model: Google Pixel 6
Android version: 12

I to am having the same issue. I've replaced "scrcpy-server" per #2990 and it still does the same quick open and instant close. No meaningful info is displayed when running "scrcpy-console.bat"

[server] INFO: Device: Google Pixel 6 (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 2400x1080
WARN: Device disconnected
Press any key to continue . . .
