### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by Trimanat** [Genymobile/scrcpy#3002]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

 - OS: Windows
 - scrcpy version: scrcpy v.1.22+Replaced scrcpy-server from the post https://github.com/Genymobile/scrcpy/pull/2990
 - installation method: Windows
 - device model: PC, Celeron n5105, BlissOs x86
 - Android version: 11
 
`scrcpy-win64-v1.22>scrcpy.exe --tcpip=192.168.88.90:5555
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
INFO: Connected to 192.168.88.90:5555
C:\Users\Adminko\Downloads\scrcpy-win64-v1.22\scrcpy-serve... file pushed, 0 skipped. 64.0 MB/s (96899 bytes in 0.001s)
[server] INFO: Device: unknown Generic Android-x86_64 (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1920x1080
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1600...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1280...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1024...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m800...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:151)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:101)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:326)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)`

there is a very large logcat, I don’t know how correct it will be to publish it here

**Comment by rom1v** [comment]
If you run `scrcpy -m1024` manually, do you get the same error?

**Comment by rom1v** [comment]
You could also try with another encoder: https://github.com/Genymobile/scrcpy/blob/master/README.md#encoder

Does it work with `screenrecord`?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard.file.mp4
```

**Comment by Trimanat** [comment]
Sorry. Until the night I tried everything, I forgot to insert it.
Yes I tried
`scrcpy-win64-v1.22>scrcpy -m1024
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
C:\Users\Adminko\Downloads\scrcpy-win64-v1.22\scrcpy-serve... file pushed, 0 skipped. 52.5 MB/s (96899 bytes in 0.002s)
[server] INFO: Device: unknown Generic Android-x86_64 (Android 11)
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m800...
INFO: Renderer: direct3d
INFO: Initial texture: 1024x576
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:151)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:101)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:326)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)`
`\scrcpy-win64-v1.22>adb shell screenrecord /sdcard/file.mp4
Encoder failed (err=-38)`
`scrcpy-win64-v1.22>adb pull /sdcard.file.mp4
adb: error: failed to stat remote object '/sdcard.file.mp4': No such file or directory`

**Comment by rom1v** [comment]
> ```
> scrcpy-win64-v1.22>adb shell screenrecord /sdcard/file.mp4
> Encoder failed (err=-38)
> ```

OK, if even `screenrecord` does not work, it's a problem with your device/rom.

**Comment by Trimanat** [comment]
Got it, thanks for the info.
But was there any experience of testing on android x86 assemblies?

**Comment by hmtheboy154** [comment]
![image](https://github.com/Genymobile/scrcpy/assets/39849246/a75fba54-e559-4d90-b1a2-8d4d4b0ad395)

I'm thinking that maybe we can close this, this is BlissOS 16.9.4 on an ASUS T100TA. The encoder is Google's one
