### ISSUE TITLE
A bug on TV in Android

### ISSUE THREAD

**Issue by Xionghaizi001** [Genymobile/scrcpy#3021]
- [√] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [√] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Android
 - scrcpy version: 1.22
 - installation method: Windows release
 - device model: Skyworth TV 8H57
 - Android version: 5.1.1

**Describe the bug**
The program can be send and run(?) in TV, but traced back the following errors and disconncet itself.
The OS is not Android TV by Google, instead of a customized system made by OEM.
For more information or logs, please contact with me.

**Posts in terminal**
```
[server] INFO: Device: Skyworth 8H57_H5 (Android 5.1.1)
INFO: Renderer: direct3d
INFO: Initial texture: 1920x1080
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:612)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:92)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
WARN: Killing the server...
```

**Comment by rom1v** [comment]
Please test #2990.

**Comment by Xionghaizi001** [comment]
> Please test #2990.

Thanks, it's work :D
