### ISSUE TITLE
Not able to launch scrcpy, keep getting error 5

### ISSUE THREAD

**Issue by Cyberdroid1** [Genymobile/scrcpy#3037]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 21H2 19044.1526
 - scrcpy version: 1.22
 - installation method: precompiled zip from github releases
 - device model: Samsung Galaxy A10s
 - Android version: 11

**Describe the bug**
When trying to launch scrcpy from terminal, I consistently get the error `CreateProcessW() error 5`. I have tried removing, adding the environment variable towards the platform-tools folder. I have tried both over a USB cable and over wireless debugging.

```
C:\Users\Pro\Downloads\scrcpy-win64-v1.22>scrcpy
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW() error 5
ERROR: Failed to execute: [D:\platform-tools], [get-serialno]
ERROR: Could not execute "adb get-serialno"
ERROR: Could not get device serial
ERROR: Server connection failed
```

**Comment by rom1v** [comment]
> Failed to execute: [D:\platform-tools], [get-serialno]

You set the `ADB` environment variable to a wrong vzlue: it must not point to the directory, but to the executable file (`D:\platform-tools\adb.exe` probably).

But it is probably better to just not set this variable and just use the adb included if it does not conflict.

**Comment by Cyberdroid1** [comment]
I found out that I had added a wrong line in the environment variables. Deleting that fixed the issue for me. 
Sorry for not seeing that earlier 😅

I will close this issue now.

**Comment by Feriawal** [comment]
C:\Users\Administrator\Downloads\Compressed\scrcpy-win64-v2.5\scrcpy-win64-v2.5>scrcpy
scrcpy 2.5 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.42.129:5555             device  SM_G950F
C:\Users\Administrator\Downloads\Compressed\scrcpy-win64-v...file pushed, 0 skipped. 143.9 MB/s (69624 bytes in 0.000s)
[server] INFO: Device: [samsung] samsung SM-G950F (Android 9)
[server] WARN: Audio disabled: it is not supported before Android 11
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.RuntimeException: cannot get MediaCodecList
        at android.media.MediaCodecList.native_getCodecCount(Native Method)
        at android.media.MediaCodecList.initCodecList(MediaCodecList.java:82)
        at android.media.MediaCodecList.<init>(MediaCodecList.java:170)
        at com.genymobile.scrcpy.CodecUtils.listVideoEncoders(CodecUtils.java:59)
        at com.genymobile.scrcpy.LogUtils.buildVideoEncoderListMessage(LogUtils.java:26)
        at com.genymobile.scrcpy.SurfaceEncoder.createMediaCodec(SurfaceEncoder.java:212)
        at com.genymobile.scrcpy.SurfaceEncoder.streamCapture(SurfaceEncoder.java:53)
        at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:257)
        at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:764)
ERROR: Could not retrieve device information
ERROR: Server connection failed


**please help me solve this problem, what's wrong with it**
