### ISSUE TITLE
scrcpy just closed when I open it

### ISSUE THREAD

**Issue by BaselCS** [Genymobile/scrcpy#3041]
- OS: [win 10]
 - scrcpy version: [1.22]
 - installation method: [ Windows zip file]
 - device model:Huawei p30 lite
 - Android version: [android10 ]

**Describe the bug**
Whenever I open Scrcpy if my screen close it flash and Scrcpy closed if it's not Scrcpy just Closed
I don't think there is any problem in SDK because I am programming in Flutter and there isn't any problem

**Comment by rom1v** [comment]
Run `scrcpy-console.bat` to see the error.

**Comment by BaselCS** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/93922382/154839711-9f8d8a68-da44-4550-b056-2a1a8b48a3de.png)

**Comment by rom1v** [comment]
Did you install the 64 bit version while you have a 32 bit system?

**Comment by BaselCS** [comment]
No, I'm 64 bit

**Comment by rom1v** [comment]
Double-click on `open_a_terminal_here.bat` and type `scrcpy`.

If it does not work, what about `.\scrcpy.exe`? Otherwise, try the 32 bit version.

**Comment by BaselCS** [comment]
When I tried `scrcpy` I got:

`scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
C:\****************\scrcpy-win64-v1.22 - 1\scrcpy-server: 1 file pushed, 0 skipped. 46.4 MB/s (40955 bytes in 0.001s)
[server] INFO: Device: HUAWEI MAR-LX1M (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2312
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:274)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:94)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:326)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)`

**Comment by rom1v** [comment]
See #2990

**Comment by BaselCS** [comment]
Thx it works very well.
But I found the screen goes black whenever I open a thing that needs a password, and I can not write except in English.
These aren't big problems for me I don't need Scrcpy to do it now but I would see it in the future.
thx 4 ur hard work.

**Comment by rom1v** [comment]
It's expected if you use Android 12. See #2129.
