### ISSUE TITLE
my first try in scrcpy is it already working but after i adjust the bitrate and the max size ive been encountered a problem like encoding error -m800,-m1280,-m1600

### ISSUE THREAD

**Issue by saidesande** [Genymobile/scrcpy#3046]
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
C:\scrcpy-win64-v1.22\scrcpy-server: 1...ped. 37.5 MB/s (40955 bytes in 0.001s)
[server] INFO: Device: zte K3DX-V5G (Android 5.1.1)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xffff
fffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:489)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:459)
        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:21
7)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncode
r.java:82)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:7
3)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:326)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
Press any key to continue . . .

**Comment by saidesande** [comment]
my first try in scrcpy is it already working but after i adjust the bitrate and the max size ive been encountered a problem like encoding error -m800,-m1280,-m1600.but ive been find a solution of that by killing server but right now this is the problem appeared when i click the scrcpy.exe what i have to do to get solution of these kind of problem?
