### ISSUE TITLE
[server] ERROR: Exception on thread Thread[main,5,main]

### ISSUE THREAD

**Issue by martinericksonn** [Genymobile/scrcpy#3053]
**Environment**
 - OS: Ubuntu Zorin OS 16
 - scrcpy version: 1.12.1
 - installation method: apt
 - device model: Realme 5
 - Android version: Android 12

**Describe the bug**

```
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 2.1 MB/s (24773 bytes in 0.011s)
INFO: Initial texture: 720x1600
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:178)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:70)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 6 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3145)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2214)
	... 8 more

```
How do I update scrcpy to latest in terminal? if that is the error I'm having

**Comment by rom1v** [comment]
Either upgrade your distrib (cf versions: https://repology.org/project/scrcpy/versions)

Or uninstall the one from the distrib and install the latest version manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple
