### ISSUE TITLE
android.media.MediaCodec$CodecException: Error 0xffffffc3

### ISSUE THREAD

**Issue by startrainee** [Genymobile/scrcpy#3079]
I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).

I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

I have Plug an Android device, but execute 'scrcpy' in windows, 
it show:

```

android.media.MediaCodec$CodecException: Error 0xffffffc3

        at android.media.MediaCodec.native_configure(Native Method)

        at android.media.MediaCodec.configure(MediaCodec.java:1960)

        at android.media.MediaCodec.configure(MediaCodec.java:1889)

        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)

        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)

        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)

        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)

        at com.genymobile.scrcpy.Server.main(Server.java:225)

        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)

        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)

[server] ERROR: Exception on thread Thread[main,5,main]

android.media.MediaCodec$CodecException: Error 0xffffffc3

        at android.media.MediaCodec.native_configure(Native Method)

        at android.media.MediaCodec.configure(MediaCodec.java:1960)

        at android.media.MediaCodec.configure(MediaCodec.java:1889)

        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)

        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)

        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)

        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)

        at com.genymobile.scrcpy.Server.main(Server.java:225)

        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)

        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)

ERROR: Could not retrieve device information

```
i try to find what "Error 0xffffffc3" mean, but i failed.

**Comment by rom1v** [comment]
Do you use the latest version (v1.23)? (it should retry automatically with a lower definition)

Otherwise, #73.

**Comment by startrainee** [comment]
I try to use the lastest version v1.23, but it doesn't work.

I used  "scrcpy -b2M -m800",it still doesn't work.
My screen size is 2608x720.

**Comment by bogdannedelcu** [comment]
Hi @startrainee , did you find a solution? I get this error in when using ffmpeg on some Android devices, not all of them though. I want to understand the cause.

**Comment by bogdannedelcu** [comment]
A workaround when default mediacodec fails on Android is to retry using libx264. A bit slower bot does the job.
