### ISSUE TITLE
scrcpy crashes after a second - dequeueOutputBuffer error

### ISSUE THREAD

**Issue by vielavlrs** [Genymobile/scrcpy#3084]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Win10]
 - scrcpy version: [1.19]
 - installation method: [Windows release zip extract]
 - device model: Xiaomi M2101K6G
 - Android version: Android 12

**Describe the bug**
The mirror screen opens for a second but crashes. Sometimes it aborts instead. 
Things I have tried:

- restart adb (kill-server)
- run in lower resolutions (-m 1024 etc)
- change encoder 
   'OMX.google.h264.encoder' - shows a frame then hangs
   'c2.android.avc.encoder' - shows a frame then hangs
- tried adb screenrecording - works

`C:\scrcpy-win64-v1.19>scrcpy -m 1024
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
C:\scrcpy-win64-v1.19\scrcpy-server: 1 file pushed, 0 skipped. 24.6 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: Xiaomi M2101K6G (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 464x1024
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:114)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:95)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)`

If the phone screen is off, the mirror doesnt crash. But once I unlock screen/wake the screen, it crashes right away.
I hope you can me on this one

**Comment by vielavlrs** [comment]
duplicate of/related to [#3051](https://github.com/Genymobile/scrcpy/issues/3051)
