### ISSUE TITLE
SCRCPY load failure

### ISSUE THREAD

**Issue by Phelnacra** [Genymobile/scrcpy#3095]
- [x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Debian
 - scrcpy version: 1.17
 - installation method: PiKiss Snap Install
 - device model: samsung galaxy 21+ ultra
 - Android version: 12

Upon a fresh install of Pi OS and factory resetting my Samsung Galaxy S21+ ultra, I cannot get SCRCPY to load at all. I've tried through both PiKiss and the Snap install, and both fail. 
The following block of text is what I get when loading SCRCPY when plugging my phone in. The Pi does recognize the phone being plugged in and yes, the phone settings are set the way they should, in developer mode with USB debugging on, 

```
pi@raspberrypi:~ $ scrcpy
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...shed. 2.5 MB/s (34015 bytes in 0.013s)
[server] INFO: Device: samsung SM-G998U (Android 12)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:370)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3357)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2346)
	... 9 more
INFO: Renderer: opengl
INFO: OpenGL version: 2.1 Mesa 20.3.5
WARN: Trilinear filtering disabled (OpenGL 3.0+ or ES


 2.0+ required)
INFO: Initial texture: 2400x1080
WARN: Device disconnected
WARN: Killing the server...
```

the following is the original video i had found to using PiKiss and scrcpy

https://www.youtube.com/watch?v=ciMx7hWYJE4

Thanks

Edit: im absolutely willing to change OS if thats the easier route. First Pi project and this is turning out to be a real uphill battle

**Comment by rom1v** [comment]
Android 12 requires scrcpy >= 1.18 (see #2129).

You can install the latest version manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

(uninstall the scrcpy package from the distribution)
