### ISSUE TITLE
 Encoding error

### ISSUE THREAD

**Issue by BasselRaafat** [Genymobile/scrcpy#3100]
**Environment**
 - OS: Windows
 - scrcpy version: 1.23
 - installation method: Windows release
 - device model: Xiaomi M2101K6G
 - Android version: 12

**Describe the bug**
it works for a second and it shows this error

[server] INFO: Device: Xiaomi M2101K6G (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:331)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)

**Comment by rom1v** [comment]
Duplicate of #3051. It seems there is a bug in MIUI13 (many reports from users after the upgrade).

**Comment by BasselRaafat** [comment]
It was happening before I upgrade to MIUI13
