### ISSUE TITLE
Scrcpy stopped working after updating to Android 12

### ISSUE THREAD

**Issue by Reggho** [Genymobile/scrcpy#3115]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.23
 - installation method: Windows
 - device model: Redmi Note 10 Pro
 - Android version: 12 SKQ1.210908.001

**Describe the bug**
After updating my phone to MIUI 13.0.3 (Android 12), the Scrcpy shutted down everytime i tried to start it. It was working all good and already used the -m resize command. 

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
[server] INFO: Device: Xiaomi M2101K6G (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:331)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
That's a problem specific to the update on Redmi Note 10 apparently: #3051.

Probably have to wait for the vendor to fix it in a new upgrade.

(closing as duplicate)
