### ISSUE TITLE
disconnect xiaomi10 pro

### ISSUE THREAD

**Issue by cx-github** [Genymobile/scrcpy#3123]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]   macOS  12.3
 - scrcpy version: [e.g. 1.12.1]   1.17
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]  brew 
 - device model:  xiaomi10 pr0
 - Android version: [e.g. 10]   android 12

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.


2022-03-17 18:42:17.863 scrcpy[27753:7020462] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.17_1/share/scrcpy/scrcpy-...pushed, 0 skipped. 23.0 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: Xiaomi Mi 10 Pro (Android 12)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3237)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2256)
	... 9 more
2022-03-17 18:42:18.515 scrcpy[27753:7020462] INFO: Renderer: metal
2022-03-17 18:42:18.522 scrcpy[27753:7020462] INFO: Initial texture: 2336x1080
2022-03-17 18:42:18.855 scrcpy[27753:7020462] WARN: Device disconnected
2022-03-17 18:42:19.857 scrcpy[27753:7020462] WARN: Killing the server...
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
You need at least scrcpy v1.18 for Android 12. #2129

**Comment by cx-github** [comment]
3Q
