### ISSUE TITLE
scrcpy 1.21 & 1.23 // debian testing Bookworm // Exception on thread

### ISSUE THREAD

**Issue by jorge-vitrubio** [Genymobile/scrcpy#3130]
**Environment**
 - OS: Debian testing Bookworm
 - scrcpy version: 1.21 & 1.23
 - installation method: apt install scrcpy
 - device model: Mi A1 Lineage tissot 18
 - Android version: 11

**Describe the bug**
Since march 02 `scrcpy` shuts down with this error message. 
This is hapenning with versions 1.21 and 1.23
Prior to that date would work properly.

```
$ scrcpy -Vdebug
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
DEBUG: ADB device found:
DEBUG:     -->   (usb)  43xxxxxxxx05                    device  Mi_A1
DEBUG: Device serial: 43xxxxxxxx05
DEBUG: Using server: /usr/share/scrcpy/scrcpy-server
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 4.2 MB/s (40614 bytes in 0.009s)
[server] INFO: Device: Xiaomi Mi A1 (Android 11)
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 21.3.7
INFO: Trilinear filtering enabled
DEBUG: Using icon: /usr/share/icons/hicolor/256x256/apps/scrcpy.png
INFO: Initial texture: 1080x1920
DEBUG: Starting demuxer thread
[server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1600...
[server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1280...
[server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1024...
[server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m800...
[server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] DEBUG: Device message sender stoppedDEBUG: End of frames
DEBUG: Receiver stopped

WARN: Device disconnected
DEBUG: quit...
[server] DEBUG: Controller stopped
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
	at com.genymobile.scrcpy.Server.main(Server.java:331)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
WARN: Killing the server...
DEBUG: Server disconnected
DEBUG: Server terminated
```

device is seen by Debian OS
```
$ adb devices -l
List of devices attached
43xxxxxxxx05           device usb:2-1 product:lineage_tissot model:Mi_A1 device:tissot transport_id:1
```
and in deed I can `adb shell` into it

**Comment by rom1v** [comment]
Looks like a device/ROM encoder issue.

Does it work with `screenrecord`?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

Also try another encoder: https://github.com/Genymobile/scrcpy#encoder

**Comment by jorge-vitrubio** [comment]
I believe it was an issue with the upgrade of my debian system, it did work back on upgrade.
