### ISSUE TITLE
App don't run

### ISSUE THREAD

**Issue by juliorosetim** [Genymobile/scrcpy#3134]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 20.04
 - scrcpy version: 1.12.1
 - installation method: apt
 - device model: Sansung galaxy s21
 - Android version: Android 12

**Describe the bug**
command scrcpy don't run de app, the following error occurs, 

```
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 3.7 MB/s (24773 bytes in 0.006s)
INFO: Initial texture: 1080x2400
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:178)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:70)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:370)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 6 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3357)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2346)
	... 8 more
WARN: Device disconnected


```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
You need at least scrcpy >= 1.18 for android 12.

Uninstall the version from your distribution, and install the latest manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

**Comment by Gui8th** [comment]
Hello, I did the scrcpy settings processes, and it doesn't start the smartphone screen, I use an lg q6 android 7.1.1.

![20d548ee-3f5a-4a25-b5d6-1039782d8169](https://user-images.githubusercontent.com/103602500/163252926-e5fcd69a-1583-447c-a63b-1571bb2114ba.jpg)

![ecc48746-8bae-427c-9241-41844d46577c](https://user-images.githubusercontent.com/103602500/163253000-7b7e8e90-5d7a-4df3-801a-f5a1d325e1ff.jpg)

**Comment by rom1v** [comment]
Try with a lower resolution: `scrcpy -m1024`

or with another encoder: https://github.com/Genymobile/scrcpy#encoder

**Comment by Gui8th** [comment]
Hi, thank you very much, 
   it worked! mine before was giving an error when accessing the terminal and I couldn't give commands, 
    I solved it I changed the resolution as advised and it worked, 
      thank you very much!

**Comment by netrikoplc** [comment]
> You need at least scrcpy >= 1.18 for android 12.
> 
> Uninstall the version from your distribution, and install the latest manually: [`master`/BUILD.md#simple](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md?rgh-link-date=2022-03-21T17%3A17%3A48Z#simple)

Worked for me, thanks.
