### ISSUE TITLE
Crash after rotation during playback video

### ISSUE THREAD

**Issue by Xgamerz** [Genymobile/scrcpy#3158]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS Big Sure 11.6.5 
 - scrcpy version: 1.20
 - installation method: brew
 - device model: Samsung Galaxy S5
 - Android version: 6.0.1

**Describe the bug**
active device rotation during playback video

```
`aymane@Aymanes-MacBook-Pro ~ % scrcpy -s 226cd598          
2022-03-29 15:04:04.055 scrcpy[1045:27535] INFO: scrcpy 1.20 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.20/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 19.9 MB/s (37139 bytes in 0.002s)
[server] INFO: Device: samsung SM-G900F (Android 6.0.1)
2022-03-29 15:04:06.114 scrcpy[1045:27535] INFO: Renderer: metal
2022-03-29 15:04:06.132 scrcpy[1045:27535] INFO: Initial texture: 1080x1920
2022-03-29 15:04:15.290 scrcpy[1045:27535] INFO: New texture: 1920x1080
2022-03-29 15:11:12.542 scrcpy[1045:27535] INFO: New texture: 1080x1920
2022-03-29 15:12:17.394 scrcpy[1045:27535] INFO: New texture: 1920x1080
2022-03-29 15:12:20.318 scrcpy[1045:27535] INFO: New texture: 1080x1920
2022-03-29 15:31:51.156 scrcpy[1045:27535] INFO: New texture: 1920x1080
2022-03-29 15:31:54.974 scrcpy[1045:27535] INFO: New texture: 1080x1920
2022-03-29 15:33:05.626 scrcpy[1045:27535] INFO: Display rotation set to 3
2022-03-29 15:33:11.342 scrcpy[1045:27535] INFO: Display rotation set to 0
2022-03-29 15:33:18.836 scrcpy[1045:27535] INFO: New texture: 1920x1080
2022-03-29 15:34:23.456 scrcpy[1045:27535] WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:110)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:255)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:257)`
```

**Comment by rom1v** [comment]
Device encoder issue.

Try with a lower definition: `scrcpy -m1024` for example.
