### ISSUE TITLE
[server] ERROR: Exception on thread Thread[main,5,main]

### ISSUE THREAD

**Issue by Rishikeshcubeyguy** [Genymobile/scrcpy#3187]
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...shed. 0.5 MB/s (24773 bytes in 0.045s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:178)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:70)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:370)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 6 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3357)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2346)
	... 8 more
INFO: Initial texture: 2400x1080
WARN: Device disconnected

This is the error message i am getting. New to Linux so hope somebody can help.

**Comment by rom1v** [comment]
For Android 12, you need scrcpy >= 1.18.

If your distrib packages an old version, uninstall it, and install the latest manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

**Comment by k1941996** [comment]
Using android 12 ( oneplus 9 pro ) still facing this issue :
![image](https://user-images.githubusercontent.com/24502716/164374941-89087834-7082-49b5-94ce-e0c051471127.png)

**Comment by rom1v** [comment]
> For Android 12, you need scrcpy >= 1.18.
