### ISSUE TITLE
[server] ERROR: Encoding error: java.lang.IllegalStateException: null android 12 xiaomi

### ISSUE THREAD

**Issue by ngominhtrungit** [Genymobile/scrcpy#3199]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: window64 v1.23
 - installation method: Windows release.
 - device model: Xiaomi Redmi Note 10
 - Android version: android 12

**Describe the bug**
INFO: Renderer: direct3d
INFO: Initial texture: 488x1080
[server] ERROR: Encoding error: java.lang.IllegalStateException: null

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
[server] INFO: Device: Xiaomi M2101K7AG (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 488x1080
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:331)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
WARN: Device disconnected
```

Pls help me, thank you.

**Comment by rom1v** [comment]
#3051

**Comment by ngominhtrungit** [comment]
Hi, it doesn't solve my problem. please help.
I use v1.24
macOs 12.4
devices Xiaomi Redmi Miui 13

<img width="572" alt="Screen Shot 2022-06-10 at 09 11 20" src="https://user-images.githubusercontent.com/45173480/172977825-5acade0e-5669-4618-96be-a044bddd211f.png">

**Comment by rom1v** [comment]
> It doesn't solve my problem

But it's a duplicate of #3051. It's a ROM issue.
