### ISSUE TITLE
Android 10 Can't paste text

### ISSUE THREAD

**Issue by QAQQL** [Genymobile/scrcpy#3201]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: scrcpy 1.23
 - installation method: Windows release
 - device model: Xiaomi MI 4LTE
 - Android version:  Android 10

**Describe the bug**
I get an error when I fetch text from my Android device

There is no error when pasting text into Android

!!!!Magisk+Lsposed for Android devices!!!!! 

```
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getPrimaryClip(ClipboardManager.java:49)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:64)
        at com.genymobile.scrcpy.Device.getClipboardText(Device.java:251)
        at com.genymobile.scrcpy.Device$2.dispatchPrimaryClipChanged(Device.java:112)
        at android.content.IOnPrimaryClipChangedListener$Stub.onTransact(IOnPrimaryClipChangedListener.java:82)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
Caused by: java.lang.SecurityException: Calling uid 0 does not own package com.android.shell
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:333)
        ... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.clipboard.ClipboardService.addActiveOwnerLocked(ClipboardService.java:688)
        at com.android.server.clipboard.ClipboardService.access$700(ClipboardService.java:157)
        at com.android.server.clipboard.ClipboardService$ClipboardImpl.getPrimaryClip(ClipboardService.java:391)
        at android.content.IClipboard$Stub.onTransact(IClipboard.java:173)
        at com.android.server.clipboard.ClipboardService$ClipboardImpl.onTransact(ClipboardService.java:341)

```

![图片](https://user-images.githubusercontent.com/51136763/164381312-6e487839-ef1c-4a38-8e90-c2ffabb07b6a.png)

**Comment by rom1v** [comment]
This happens because you are root. See #1606.
