### ISSUE TITLE
DEBUGGING NOT WORKING

### ISSUE THREAD

**Issue by Harikiran2903** [Genymobile/scrcpy#3211]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:  Windows
 - scrcpy version: 1.18
 - installation method: Manual
 - device model: Redmi note 10 pro  max
 - Android version: 12

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).
 ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:114)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:95)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
```
Please paste terminal output in a code block.
Scrcpy

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
#3051

**Comment by Harikiran2903** [comment]
> #3051

[server] INFO: Device: Xiaomi M2101K6I (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: downsizeOnError=true; firstFrameSent=false
[server] INFO: Retrying with -m1920...
[server] INFO: FIRST FRAME SENT
INFO: New texture: 864x1920
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: downsizeOnError=true; firstFrameSent=true
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:153)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:331)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
same issue

**Comment by rom1v** [comment]
Closing as duplicate.
