### ISSUE TITLE
ERROR: Exception on thread Thread[main,5,main] (pop OS Linux)

### ISSUE THREAD

**Issue by marianomontiel** [Genymobile/scrcpy#3226]
Hi. I'm experiencing this problem on a laptop that is currently running pop os. I initially though it had to do something with android 12 but after testing on a windows computer it worked just fine!

I looked on issues but couldn't find a similar problem. (not very familiar with github though..)

Thank you in advance <3 this is GREAT software

___________________________________-

INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 3.2 MB/s (34012 bytes in 0.010s)
[server] INFO: Device: samsung SM-A525M (Android 12)
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 21.3.5
INFO: Trilinear filtering enabled
INFO: Initial texture: 864x1920
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:374)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3370)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2344)
	... 9 more
WARN: Killing the server...

**Comment by rom1v** [comment]
> INFO: scrcpy 1.17 https://github.com/Genymobile/scrcpy

You need scrcpy >= 1.18 for Android 12. You can install the latest on linux by following these instructions: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

**Comment by marianomontiel** [comment]
Woah, thanks a LOT! <3
