### ISSUE TITLE
INFO: Initial texture: 1080x2408

### ISSUE THREAD

**Issue by nishankjain09** [Genymobile/scrcpy#3239]
Could someone please help out to fix this issue ? 
**Device: VIVO T1 5G 
Android Version 12 
USB debugging on and File Transfer Mode**

Whenever I hit the scrcpy on the UBUNTU terminal, I get the following message 
NFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 1.0 MB/s (24773 bytes in 0.023s)
INFO: Initial texture: 1080x2408
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2207)
	at android.media.MediaCodec.configure(MediaCodec.java:2123)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:167)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:68)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:389)
WARN: Device disconnected

I have tried the following commands to fix the issue 
scrcpy -m1080 , scrcpy -m1024

Any help would be really appreciated?

**Comment by rom1v** [comment]
> INFO: scrcpy 1.12.1

First, try with the latest version. Uninstall the package from your distrib, then install manually:
https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

**Comment by nishankjain09** [comment]
Hey Uninstalled the package and then installed using the snap package. 
sudo snap install scrcpy. 

Works perfectly now. 

Thank you
