### ISSUE TITLE
I CANT START SCRCPY IN ANDROID 12 !!!

### ISSUE THREAD

**Issue by ali23012** [Genymobile/scrcpy#3245]
Hello! I own a s20 fe 4g and i have got issues with scrcpy recently.
When i try typing `scrcpy` i get this:
`INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy... (34015 bytes in 0.031s)
[server] INFO: Device: samsung SM-G780G (Android 12)
INFO: Renderer: opengl
INFO: OpenGL version: 3.1 Mesa 20.3.5
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2400
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:374)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3372)
        at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2346)
        ... 9 more
WARN: Killing the server...`

**Comment by rom1v** [comment]
There's no need to shout.

You need Android >= v1.18 for Android 12.

#2129

**Comment by rom1v** [comment]
Uninstall the package, and install the latest version manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

**Comment by ali23012** [comment]
Thanks! Ive figured it out because i had to add a repository to install scrcpy 1.23

**Comment by rom1v** [comment]
Which repository?
