### ISSUE TITLE
Blank Mirroring on MOST of ONE Applications, OK for other Apps

### ISSUE THREAD

**Issue by dbareis** [Genymobile/scrcpy#3269]
**Describe the bug**
I have never seen this on any other application, on the "[Woolworths Money](https://play.google.com/store/apps/details?id=com.woolworths.money)" app most of the screens are blank/black.  After searching for a similar issue I found one that asked if that shows up in the recording, it does (attached).

Also for the last few releases (and pretty sure also Windows 10), I get error re: "stay_on_while_plugged_in" in below debug

https://user-images.githubusercontent.com/295230/168697693-17561aa8-71b7-43fd-96c9-f4db23e05686.mp4

**Command Line & Windows Console Debug for the above video**
```
D:\...\ScrCpy\$DB$> ..\scrcpy.exe --verbosity debug --show-touches --window-title "[ANDROID PHONE] - STARTED:  8:36:42.90 on Tue 17/05/2022" --disable-screensaver --stay-awake --prefer-text --push-target "/sdcard/Download/" --window-x -1918 --window-y 35 --record file.mp4
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
DEBUG: ADB device found:
DEBUG:     -->   (usb)              e11d3a74            device  IN2025
DEBUG: Device serial: e11d3a74
DEBUG: Using server (portable): D:\DBAREIS\TOOLS\[Portable]\$Android Smartphone\ScrCpy\scrcpy-server
D:\DBAREIS\TOOLS\[Portable]\$Android S...ped. 42.4 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: OnePlus IN2025 (Android 12)
[server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
[server] ERROR: Could not change "stay_on_while_plugged_in"
com.genymobile.scrcpy.SettingsException: Could not access settings: put global stay_on_while_plugged_in 7
        at com.genymobile.scrcpy.Settings.execSettingsPut(Settings.java:26)
        at com.genymobile.scrcpy.Settings.putValue(Settings.java:61)
        at com.genymobile.scrcpy.Settings.getAndPutValue(Settings.java:80)
        at com.genymobile.scrcpy.Server.initAndCleanUp(Server.java:37)
        at com.genymobile.scrcpy.Server.access$000(Server.java:12)
        at com.genymobile.scrcpy.Server$2.run(Server.java:121)
        at java.lang.Thread.run(Thread.java:920)
Caused by: java.io.IOException: Command [settings, put, global, stay_on_while_plugged_in, 7] returned with value 255
        at com.genymobile.scrcpy.Command.exec(Command.java:16)
        at com.genymobile.scrcpy.Settings.execSettingsPut(Settings.java:24)
        ... 6 more
INFO: Renderer: direct3d
DEBUG: Trilinear filtering disabled (not an OpenGL renderer)
DEBUG: Using icon (portable): D:\DBAREIS\TOOLS\[Portable]\$Android Smartphone\ScrCpy\icon.png
INFO: Initial texture: 1080x2376
DEBUG: Starting demuxer thread
DEBUG: Starting recorder thread
INFO: Recording started to mp4 file: file.mp4
DEBUG: User requested to quit
DEBUG: quit...
DEBUG: End of frames
DEBUG: Receiver stopped
INFO: Recording complete to mp4 file: file.mp4
DEBUG: Recorder thread ended
[server] DEBUG: Controller stopped
WARN: Killing the server...
DEBUG: Server disconnected
DEBUG: Server terminated
```

**Environment**
Device: OnePlus IN2025 (Android 12)
Windows 11
01/05/2022  02:09 PM           725,704 scrcpy.exe
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
Dependencies (compiled / linked):
 - SDL: 2.0.22 / 2.0.22
 - libavcodec: 59.18.100 / 59.18.100
 - libavformat: 59.16.100 / 59.16.100
 - libavutil: 57.17.100 / 57.17.100
 - libusb: - / 1.0.26

**Comment by rom1v** [comment]
For the blank/black screen, the app requested the "secure flag" to prevent mirroring (#36) and this is enforced even for shell since Android 12 (#2129).

For the settings error, the command on the device fails for some reason:

```
adb shell settings get global stay_on_while_plugged_in
adb shell settings put global stay_on_while_plugged_in 7
```

**Comment by rom1v** [comment]
Refs https://github.com/Genymobile/scrcpy/issues/2612#issuecomment-1128422386

**Comment by dbareis** [comment]
I can confirm that screen capture is disabled for this app, interesting even my banking app doesn't do that!

@rom1v
I think it should say this for "--stay-awake" in --help output and any other doco. Also in the console output if it can tell.

**Comment by Sentonta-Cyber** [comment]
Use smalipatcher to patch your secure flag and should be fine, ive not tested all apps but the ones i was having problems with are worked round this way

**Comment by dbareis** [comment]
> Use smalipatcher to patch your secure flag and should be fine, ive not tested all apps but the ones i was having problems with are worked round this way

Thanks, I don't care much for that app but will keep that in mind if it effects and important app :-)
