### ISSUE TITLE
The application fails on Android 12

### ISSUE THREAD

**Issue by nightadmin** [Genymobile/scrcpy#3291]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: MX Linux (based on Debian)
 - scrcpy version: 1.17 (latest)
 - installation method: apt
 - device model: tissot (Xiaomi Mi A1)
 - Android version: 12

**Describe the bug**
It fails with this code:
```bash
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 7.0 MB/s (34015 bytes in 0.005s)
error: XDG_RUNTIME_DIR not set in the environment.
[server] INFO: Device: Xiaomi Mi A1 (Android 12)
INFO: Renderer: opengl
INFO: OpenGL version: 1.4 Mesa 20.3.5
WARN: Trilinear filtering disabled (OpenGL 3.0+ or ES 2.0+ required)
INFO: Initial texture: 1080x1920
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:357)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3240)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2300)
	... 9 more
WARN: Killing the server...
```
ADB Logcat response:
```bash
05-23 20:52:07.745   861 20973 W OMXNodeInstance: [0xed24c1c4:qcom.encoder.avc] component does not support metadata mode; using fallback
05-23 20:52:07.746 21042 21061 W OMXUtils: do not know color format 0x7fa30c04 = 2141391876
05-23 20:52:07.746 21042 21061 W OMXUtils: do not know color format 0x7f000789 = 2130708361
05-23 20:52:07.755 21042 21061 I ACodec  : setupAVCEncoderParameters with [profile: Baseline] [level: Level42]
05-23 20:52:07.757 21042 21061 I ACodec  : [OMX.qcom.video.encoder.avc] cannot encode HDR static metadata. Ignoring.
05-23 20:52:07.757 21042 21061 I ACodec  : setupVideoEncoder succeeded
05-23 20:52:07.758 21042 21061 W OMXUtils: do not know color format 0x7f000789 = 2130708361
05-23 20:52:07.758   861 20973 E OMXNodeInstance: getConfig(0xed24c1c4:qcom.encoder.avc, ConfigLatency(0x6f800005)) ERROR: UnsupportedIndex(0x8000101a)
05-23 20:52:07.761   861 20973 E OMXNodeInstance: getConfig(0xed24c1c4:qcom.encoder.avc, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
05-23 20:52:07.762   861 20973 E OMXNodeInstance: getParameter(0xed24c1c4:qcom.encoder.avc, ParamConsumerUsageBits(0x6f800004)) ERROR: UnsupportedIndex(0x8000101a)
05-23 20:52:07.763   861 20973 D GraphicBufferSource: setting dataspace: 0x104, acquired=0
05-23 20:52:07.763   861 20973 E OMXNodeInstance: getParameter(0xed24c1c4:qcom.encoder.avc, ParamConsumerUsageBits(0x6f800004)) ERROR: UnsupportedIndex(0x8000101a)
05-23 20:52:07.763   861 20973 D GraphicBufferSource: requesting color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M))
05-23 20:52:07.768 21042 21042 D AndroidRuntime: Shutting down VM
05-23 20:52:07.769 21042 21042 E AndroidRuntime: FATAL EXCEPTION: main
05-23 20:52:07.769 21042 21042 E AndroidRuntime: PID: 21042
05-23 20:52:07.769 21042 21042 E AndroidRuntime: java.lang.AssertionError: java.lang.reflect.InvocationTargetException
05-23 20:52:07.769 21042 21042 E AndroidRuntime: 	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
05-23 20:52:07.769 21042 21042 E AndroidRuntime: 	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
05-23 20:52:07.769 21042 21042 E AndroidRuntime: 	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
05-23 20:52:07.769 21042 21042 E AndroidRuntime: 	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
05-23 20:52:07.769 21042 21042 E AndroidRuntime: 	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
05-23 20:52:07.769 21042 21042 E AndroidRuntime: 	at com.genymobile.scrcpy.Server.main(Server.java:252)
05-23 20:52:07.769 21042 21042 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
05-23 20:52:07.769 21042 21042 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:357)
05-23 20:52:07.769 21042 21042 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
05-23 20:52:07.769 21042 21042 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-23 20:52:07.769 21042 21042 E AndroidRuntime: 	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
05-23 20:52:07.769 21042 21042 E AndroidRuntime: 	... 7 more
05-23 20:52:07.769 21042 21042 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: displayToken must not be null
05-23 20:52:07.769 21042 21042 E AndroidRuntime: 	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3240)
05-23 20:52:07.769 21042 21042 E AndroidRuntime: 	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2300)
05-23 20:52:07.769 21042 21042 E AndroidRuntime: 	... 9 more
05-23 20:52:07.769 21042 21042 E scrcpy  : Exception on thread Thread[main,5,main]
05-23 20:52:07.769 21042 21042 E scrcpy  : java.lang.AssertionError: java.lang.reflect.InvocationTargetException
05-23 20:52:07.769 21042 21042 E scrcpy  : 	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
05-23 20:52:07.769 21042 21042 E scrcpy  : 	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
05-23 20:52:07.769 21042 21042 E scrcpy  : 	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
05-23 20:52:07.769 21042 21042 E scrcpy  : 	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
05-23 20:52:07.769 21042 21042 E scrcpy  : 	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
05-23 20:52:07.769 21042 21042 E scrcpy  : 	at com.genymobile.scrcpy.Server.main(Server.java:252)
05-23 20:52:07.769 21042 21042 E scrcpy  : 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
05-23 20:52:07.769 21042 21042 E scrcpy  : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:357)
05-23 20:52:07.769 21042 21042 E scrcpy  : Caused by: java.lang.reflect.InvocationTargetException
05-23 20:52:07.769 21042 21042 E scrcpy  : 	at java.lang.reflect.Method.invoke(Native Method)
05-23 20:52:07.769 21042 21042 E scrcpy  : 	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
05-23 20:52:07.769 21042 21042 E scrcpy  : 	... 7 more
05-23 20:52:07.769 21042 21042 E scrcpy  : Caused by: java.lang.IllegalArgumentException: displayToken must not be null
05-23 20:52:07.769 21042 21042 E scrcpy  : 	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3240)
05-23 20:52:07.769 21042 21042 E scrcpy  : 	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2300)

```

**Comment by rom1v** [comment]
You need scrcpy >= 1.18 for Android 12.

**Comment by nightadmin** [comment]
Yes, I have just view this (https://github.com/Genymobile/scrcpy/issues/3245) issue, but it is not a solution. I`ve installed scrcpy from sources and now command "scrcpy" does not exist, and binary file /usr/local/share/scrcpy/scrcpy-server crashes without any specified messages.

**Comment by nightadmin** [comment]
Okay, it looks like simple re-login to root fixes this problem. I gonna close this issue, but what about notice in the README file A12-specific instructions?

**Comment by rom1v** [comment]
> but what about notice in the README file A12-specific instructions?

It's mentioned in the FAQ:
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#crashes
