### ISSUE TITLE
ERROR: server connection failed

### ISSUE THREAD

**Issue by lolcakes69** [Genymobile/scrcpy#3303]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows
 - scrcpy version: 1.24
 - installation method: windows release
 - device model: samsung s21
 - Android version: 12

**Describe the bug**
it doesn't connect. when i run the command my phone lights up but it fails in the end. i did just install a new pfsense router, still learning about it. not sure if any ports need to be allowed/forwarded

```
C:\Users\VALKYRIE>scrcpy
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 52.5 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: samsung SM-G991U (Android 12)
ERROR: Server connection failed

C:\Users\VALKYRIE>scrcpy -Vdebug
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
DEBUG: ADB device found:
DEBUG:     -->   (usb)           R5CR30Y092J            device  SM_G991U
DEBUG: Device serial: R5CR30Y092J
DEBUG: Using server (portable): C:\scrcpy\scrcpy-server
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 72.1 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: samsung SM-G991U (Android 12)
[server] DEBUG: Controller stopped
[server] DEBUG: Using encoder: 'c2.qti.avc.encoder'
[server] DEBUG: Screen streaming stopped
[server] DEBUG: Device message sender stopped
DEBUG: Interrupting socket
DEBUG: Server disconnected
DEBUG: Server terminated
ERROR: Server connection failed
```

**Comment by rom1v** [comment]
Try with another encoder: https://github.com/Genymobile/scrcpy#encoder

**Comment by lolcakes69** [comment]
tried with all available encoders. Windows release is literally just extract the folder and then running it from that path right?

```
C:\Users\VALKYRIE>scrcpy
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 22.5 MB/s (41159 bytes in 0.002s)
[server] INFO: Device: samsung SM-G991U (Android 12)
ERROR: Server connection failed

C:\Users\VALKYRIE>scrcpy --encoder OMX.qcom.video.encoder.avc
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 53.6 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: samsung SM-G991U (Android 12)
ERROR: Server connection failed

C:\Users\VALKYRIE>scrcpy --encoder _
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 52.5 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: samsung SM-G991U (Android 12)
[server] ERROR: Exception on thread Thread[main,5,main]
com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:222)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:83)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:378)
[server] ERROR: Try to use one of the available encoders:
[server] ERROR:     scrcpy --encoder 'c2.qti.avc.encoder'
[server] ERROR:     scrcpy --encoder 'OMX.qcom.video.encoder.avc'
[server] ERROR:     scrcpy --encoder 'c2.android.avc.encoder'
[server] ERROR:     scrcpy --encoder 'OMX.google.h264.encoder'
ERROR: Server connection failed

C:\Users\VALKYRIE>scrcpy --encoder 'c2.qti.avc.encoder'
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 47.7 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: samsung SM-G991U (Android 12)
ERROR: Server connection failed

C:\Users\VALKYRIE>scrcpy --encoder 'c2.android.avc.encoder'
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 45.8 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: samsung SM-G991U (Android 12)
ERROR: Server connection failed

C:\Users\VALKYRIE>scrcpy --encoder 'OMX.google.h264.encoder'
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 38.5 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: samsung SM-G991U (Android 12)
ERROR: Server connection failed
```

**Comment by rom1v** [comment]
> i did just install a new pfsense router, still learning about it. not sure if any ports need to be allowed/forwarded

scrcpy creates a tunnel between TCP localhost:27183 (by default, see `--port`) and unix socket "scrcpy" on the device.
If `adb reverse` works, it creates a reverse tunnel (so the computer listens on localhost:27183 for connections from the device), otherwise (or if `--force-adb-forward` is passed) it creates a forward tunnel (so the computer connects to localhost:27183 to reach the unix socket on the device).

**Comment by lolcakes69** [comment]
moment i allowed port 27183 it came up, thanks. i did a find for "port" but stopped when i saw the connection section that talks about port 5555

**Comment by 1160300414** [comment]
I have just met the same problem and I want to ask the method that you allowed port 27183. Thanks a lot.
