### ISSUE TITLE
Mirror Google Glass XE1

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [Genymobile/scrcpy#3306]
**Environment**
 - OS: Linux 5.17
 - scrcpy version: 1.23
 - installation method: AUR
 - device model: Google Glass XE1 `glass`
 - Android version: 4.4

**Describe the bug**

`scrcpy` refuses to connect to my Android 4.4 device. I am unsure whether this is cased by the old hardware or some missing APIs in Android 4.4 for GDK.

At least, for the Google Glass EE2, `scrcpy` is officially recommended for screen mirroring.

```
 scrcpy --verbosity=verbose
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
DEBUG: ADB device found:
DEBUG:     -->   (usb)  0168376B03014021                device  Glass_1
DEBUG: Device serial: 0168376B03014021
DEBUG: Using server: /usr/share/scrcpy/scrcpy-server
/usr/share/scrcpy/scrcpy-server: 1 fil...ped. 44.0 MB/s (41123 bytes in 0.001s)
adb: error: closed
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
DEBUG: Remaining connection attempts: 100
DEBUG: Remaining connection attempts: 99
DEBUG: Remaining connection attempts: 98
DEBUG: Remaining connection attempts: 97
DEBUG: Remaining connection attempts: 96
DEBUG: Remaining connection attempts: 95
DEBUG: Remaining connection attempts: 94
DEBUG: Remaining connection attempts: 93
Aborted 
DEBUG: Server disconnected
DEBUG: Server terminated
DEBUG: Remaining connection attempts: 92
ERROR: Server connection failed
```

```
D/skia    ( 8133): SkGraphics::Init() - BLTsville (CPU) dlopen success
D/AndroidRuntime( 8133): 
D/AndroidRuntime( 8133): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 8133): CheckJNI is OFF
D/dalvikvm( 8133): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 8133): Added shared lib libjavacore.so 0x0
D/dalvikvm( 8133): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 8133): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 8133): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
E/dalvikvm( 8133): Dex cache directory isn't writable: /data/dalvik-cache
I/dalvikvm( 8133): Unable to open or create cache for /data/local/tmp/scrcpy-server.jar (/data/dalvik-cache/data@local@tmp@scrcpy-server.jar@classes.dex)
E/appproc ( 8133): ERROR: could not find class 'com.genymobile.scrcpy.Server'
E/dalvikvm( 8133): JNI posting fatal error: Native registration unable to find class 'android/debug/JNITest'; aborting...
I/dalvikvm( 8133): "main" prio=5 tid=1 NATIVE
I/dalvikvm( 8133):   | group="main" sCount=0 dsCount=0 obj=0x41b80cd8 self=0x41b6c4b0
I/dalvikvm( 8133):   | sysTid=8133 nice=0 sched=0/0 cgrp=default handle=1074868564
I/dalvikvm( 8133):   | state=R schedstat=( 466217048 25238030 190 ) utm=33 stm=12 core=1
I/dalvikvm( 8133):   #00  pc 000013ae  /system/lib/libcorkscrew.so (unwind_backtrace_thread+29)
I/dalvikvm( 8133):   #01  pc 000613a6  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+33)
I/dalvikvm( 8133):   #02  pc 00055394  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+395)
I/dalvikvm( 8133):   #03  pc 00055402  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+25)
I/dalvikvm( 8133):   #04  pc 00049e20  /system/lib/libdvm.so
I/dalvikvm( 8133):   #05  pc 00001fa8  /system/lib/libnativehelper.so (jniRegisterNativeMethods+39)
I/dalvikvm( 8133):   #06  pc 0004d99e  /system/lib/libandroid_runtime.so
I/dalvikvm( 8133):   #07  pc 0004dc8c  /system/lib/libandroid_runtime.so (android::AndroidRuntime::startReg(_JNIEnv*)+23)
I/dalvikvm( 8133):   #08  pc 0004e6e4  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, char const*, bool)+187)
I/dalvikvm( 8133):   #09  pc 00001062  /system/bin/app_process
I/dalvikvm( 8133):   #10  pc 0000e580  /system/lib/libc.so (__libc_init+47)
I/dalvikvm( 8133):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm( 8133):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm( 8133): 
E/dalvikvm( 8133): VM aborting
F/libc    ( 8133): Fatal signal 6 (SIGABRT) at 0x00001fc5 (code=-6), thread 8133 (app_process)
I/DEBUG   (  124): BOOM: pid=8133 uid=2000 gid=2000 tid=8133
I/DEBUG   (  124): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  124): Build fingerprint: 'Google/glass_1/glass-1:4.4.4/XRH35/5585826:user/release-keys'
I/DEBUG   (  124): Revision: '5'
I/DEBUG   (  124): pid: 8133, tid: 8133, name: app_process  >>> app_process <<<
I/DEBUG   (  124): pid: 8133, tid: 8133, name: app_process  >>> app_process <<<
I/DEBUG   (  124): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
W/NativeCrashListener(  500): Couldn't find ProcessRecord for pid 8133
I/DEBUG   (  124):     r0 00000000  r1 00001fc5  r2 00000006  r3 00000000
I/DEBUG   (  124): AM write failure (32 / Broken pipe)
I/DEBUG   (  124):     r4 00000006  r5 0000000d  r6 00001fc5  r7 0000010c
I/DEBUG   (  124):     r8 00000006  r9 00000000  sl bec6dace  fp bec6dac0
I/DEBUG   (  124):     ip 402a5530  sp bec6d550  lr 4013df6d  pc 4014cf88  cpsr 000f0010
I/DEBUG   (  124):     d0  74726f6261204d56  d1  0a29646f6874654d
I/DEBUG   (  124):     d2  65747379732f2020  d3  696c2f62696c2f6d
I/DEBUG   (  124):     d4  64696f72646e6162  d5  656d69746e75725f
I/DEBUG   (  124):     d6  646e6128206f732e  d7  6e413a3a64696f72
I/DEBUG   (  124):     d8  0000000000000000  d9  0000000000000000
I/DEBUG   (  124):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   (  124):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   (  124):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   (  124):     d16 3fe8000000000000  d17 3fb999999999999a
I/DEBUG   (  124):     d18 41c428b2bd800000  d19 0000000000000000
I/DEBUG   (  124):     d20 0000000000000000  d21 0000000000000000
I/DEBUG   (  124):     d22 0000000000000000  d23 0000000000000000
I/DEBUG   (  124):     d24 0000000000000000  d25 0000000000000000
I/DEBUG   (  124):     d26 0000000000000000  d27 0000000000000000
I/DEBUG   (  124):     d28 0000000000000000  d29 0000000000000000
I/DEBUG   (  124):     d30 0000000000000000  d31 0000000000000000
I/DEBUG   (  124):     scr 60000010
I/DEBUG   (  124): 
I/DEBUG   (  124): backtrace:
I/DEBUG   (  124):     #00  pc 00022f88  /system/lib/libc.so
I/DEBUG   (  124):     #01  pc 00013f69  /system/lib/libc.so
I/DEBUG   (  124):     #02  pc 0001417d  /system/lib/libc.so
I/DEBUG   (  124):     #03  pc 00012eb3  /system/lib/libc.so
I/DEBUG   (  124):     #04  pc 0002283c  /system/lib/libc.so
I/DEBUG   (  124):     #05  pc 00046a27  /system/lib/libdvm.so
I/DEBUG   (  124):     #06  pc 00001fab  /system/lib/libnativehelper.so
I/DEBUG   (  124):     #07  pc 0004d9a1  /system/lib/libandroid_runtime.so
I/DEBUG   (  124):     #08  pc 0004dc8d  /system/lib/libandroid_runtime.so
I/DEBUG   (  124):     #09  pc 0004e6e5  /system/lib/libandroid_runtime.so
I/DEBUG   (  124):     #10  pc 00001063  /system/bin/app_process
I/DEBUG   (  124):     #11  pc 0000e583  /system/lib/libc.so
I/DEBUG   (  124):     #12  pc 00000d80  /system/bin/app_process
I/DEBUG   (  124): 
I/DEBUG   (  124): stack:
I/DEBUG   (  124):          bec6d510  40298136  /system/lib/libandroid_runtime.so
I/DEBUG   (  124):          bec6d514  00000002  
I/DEBUG   (  124):          bec6d518  402a5530  /system/lib/libandroid_runtime.so
I/DEBUG   (  124):          bec6d51c  00000006  
I/DEBUG   (  124):          bec6d520  00000000  
I/DEBUG   (  124):          bec6d524  bec6dace  [stack]
I/DEBUG   (  124):          bec6d528  bec6dac0  [stack]
I/DEBUG   (  124):          bec6d52c  40151441  /system/lib/libc.so
I/DEBUG   (  124):          bec6d530  30353730  
I/DEBUG   (  124):          bec6d534  32323839  
I/DEBUG   (  124):          bec6d538  bec6d5ac  [stack]
I/DEBUG   (  124):          bec6d53c  00000000  
I/DEBUG   (  124):          bec6d540  00000000  
I/DEBUG   (  124):          bec6d544  36333138  
I/DEBUG   (  124):          bec6d548  00004000  
I/DEBUG   (  124):          bec6d54c  bec6d5ba  [stack]
I/DEBUG   (  124):     #00  bec6d550  00000006  
I/DEBUG   (  124):          bec6d554  0000000d  
I/DEBUG   (  124):          bec6d558  00001fc5  
I/DEBUG   (  124):          bec6d55c  402a5530  /system/lib/libandroid_runtime.so
I/DEBUG   (  124):          bec6d560  402a5530  /system/lib/libandroid_runtime.so
I/DEBUG   (  124):          bec6d564  4013df6d  /system/lib/libc.so
I/DEBUG   (  124):     #01  bec6d568  00000006  
I/DEBUG   (  124):          bec6d56c  00000000  
I/DEBUG   (  124):          bec6d570  00000002  
I/DEBUG   (  124):          bec6d574  4013e181  /system/lib/libc.so
I/DEBUG   (  124):     #02  bec6d578  bec6d584  [stack]
I/DEBUG   (  124):          bec6d57c  4013ceb7  /system/lib/libc.so
I/DEBUG   (  124): 
I/DEBUG   (  124): memory near r1:
I/DEBUG   (  124):     00001fa4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00001fb4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00001fc4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00001fd4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00001fe4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00001ff4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002004 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002014 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002024 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002034 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002044 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002054 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002064 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002074 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002084 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002094 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124): 
I/DEBUG   (  124): memory near r6:
I/DEBUG   (  124):     00001fa4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00001fb4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00001fc4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00001fd4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00001fe4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00001ff4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002004 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002014 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002024 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002034 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002044 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002054 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002064 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002074 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002084 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124):     00002094 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  124): 
I/DEBUG   (  124): memory near sl:
I/DEBUG   (  124):     bec6daac b2a672c2 aec49e75 c08b7577 311fcc27  
I/DEBUG   (  124):     bec6dabc 006c3776 5f707061 636f7270 00737365  
I/DEBUG   (  124):     bec6dacc 6f63002f 65672e6d 6f6d796e 656c6962  
I/DEBUG   (  124):     bec6dadc 7263732e 2e797063 76726553 31007265  
I/DEBUG   (  124):     bec6daec 0033322e 5f676f6c 6576656c 65763d6c  
I/DEBUG   (  124):     bec6dafc 736f6272 69620065 61725f74 383d6574  
I/DEBUG   (  124):     bec6db0c 30303030 74003030 656e6e75 6f665f6c  
I/DEBUG   (  124):     bec6db1c 72617772 72743d64 43006575 5353414c  
I/DEBUG   (  124):     bec6db2c 48544150 61642f3d 6c2f6174 6c61636f  
I/DEBUG   (  124):     bec6db3c 706d742f 7263732f 2d797063 76726573  
I/DEBUG   (  124):     bec6db4c 6a2e7265 5f007261 79732f3d 6d657473  
I/DEBUG   (  124):     bec6db5c 6e69622f 7070612f 6f72705f 73736563  
I/DEBUG   (  124):     bec6db6c 554d4500 4554414c 54535f44 4741524f  
I/DEBUG   (  124):     bec6db7c 4f535f45 45435255 6e6d2f3d 68732f74  
I/DEBUG   (  124):     bec6db8c 2f6c6c65 6c756d65 64657461 5f444c00  
I/DEBUG   (  124):     bec6db9c 5242494c 5f595241 48544150 65762f3d  
I/DEBUG   (  124): 
I/DEBUG   (  124): memory near fp:
I/DEBUG   (  124):     bec6daa0 bec6dabc 00000000 00000000 b2a672c2  
I/DEBUG   (  124):     bec6dab0 aec49e75 c08b7577 311fcc27 006c3776  
I/DEBUG   (  124):     bec6dac0 5f707061 636f7270 00737365 6f63002f  
I/DEBUG   (  124):     bec6dad0 65672e6d 6f6d796e 656c6962 7263732e  
I/DEBUG   (  124):     bec6dae0 2e797063 76726553 31007265 0033322e  
I/DEBUG   (  124):     bec6daf0 5f676f6c 6576656c 65763d6c 736f6272  
I/DEBUG   (  124):     bec6db00 69620065 61725f74 383d6574 30303030  
I/DEBUG   (  124):     bec6db10 74003030 656e6e75 6f665f6c 72617772  
I/DEBUG   (  124):     bec6db20 72743d64 43006575 5353414c 48544150  
I/DEBUG   (  124):     bec6db30 61642f3d 6c2f6174 6c61636f 706d742f  
I/DEBUG   (  124):     bec6db40 7263732f 2d797063 76726573 6a2e7265  
I/DEBUG   (  124):     bec6db50 5f007261 79732f3d 6d657473 6e69622f  
I/DEBUG   (  124):     bec6db60 7070612f 6f72705f 73736563 554d4500  
I/DEBUG   (  124):     bec6db70 4554414c 54535f44 4741524f 4f535f45  
I/DEBUG   (  124):     bec6db80 45435255 6e6d2f3d 68732f74 2f6c6c65  
I/DEBUG   (  124):     bec6db90 6c756d65 64657461 5f444c00 5242494c  
I/DEBUG   (  124): 
I/DEBUG   (  124): memory near ip:
I/DEBUG   (  124):     402a5510 40298029 40278ec1 40298044 4028581f  
I/DEBUG   (  124):     402a5520 40278e89 4029805a 4028545b 40278e55  
I/DEBUG   (  124):     402a5530 4029814c 40298152 40279159 4029816c  
I/DEBUG   (  124):     402a5540 4028d866 402790f9 4029066d 4028581f  
I/DEBUG   (  124):     402a5550 40279291 40298247 40285285 40279295  
I/DEBUG   (  124):     402a5560 4029824f 4029028a 40279255 4029825d  
I/DEBUG   (  124):     402a5570 40285dad 4027924d 402982cb 4028e5a1  
I/DEBUG   (  124):     402a5580 4027941d 402982de 4028e671 40279469  
I/DEBUG   (  124):     402a5590 402982f3 4028a578 40279405 40298308  
I/DEBUG   (  124):     402a55a0 4028a578 402793ed 4029849f 40297de2  
I/DEBUG   (  124):     402a55b0 40279779 402984da 4028a578 40279893  
I/DEBUG   (  124):     402a55c0 402984e3 4028a578 40279879 402984ec  
I/DEBUG   (  124):     402a55d0 4028a578 4027985f 402984f4 402858f9  
I/DEBUG   (  124):     402a55e0 4027997d 402984fc 40298508 402798ad  
I/DEBUG   (  124):     402a55f0 40298554 4028e644 40279ad1 40298563  
I/DEBUG   (  124):     402a5600 4028d4b7 40279939 40298573 40298582  
I/DEBUG   (  124): 
I/DEBUG   (  124): memory near sp:
I/DEBUG   (  124):     bec6d530 30353730 32323839 bec6d5ac 00000000  
I/DEBUG   (  124):     bec6d540 00000000 36333138 00004000 bec6d5ba  
I/DEBUG   (  124):     bec6d550 00000006 0000000d 00001fc5 402a5530  
I/DEBUG   (  124):     bec6d560 402a5530 4013df6d 00000006 00000000  
I/DEBUG   (  124):     bec6d570 00000002 4013e181 bec6d584 4013ceb7  
I/DEBUG   (  124):     bec6d580 00000000 ffffffdf 401752e0 40175244  
I/DEBUG   (  124):     bec6d590 00000000 4013fa97 416931f0 416931f0  
I/DEBUG   (  124):     bec6d5a0 40298136 4014c840 00000000 41628a2b  
I/DEBUG   (  124):     bec6d5b0 40183344 6c756e28 0000296c 00000000  
I/DEBUG   (  124):     bec6d5c0 00000000 00000000 00000000 00000000  
I/DEBUG   (  124):     bec6d5d0 00000000 00000000 00000000 00000000  
I/DEBUG   (  124):     bec6d5e0 00000000 00000000 00000000 00000000  
I/DEBUG   (  124):     bec6d5f0 00000000 00000000 00000000 00000000  
I/DEBUG   (  124):     bec6d600 00000000 00000000 00000000 00000000  
I/DEBUG   (  124):     bec6d610 00000000 00000000 00000000 00000000  
I/DEBUG   (  124):     bec6d620 00000000 00000000 00000000 00000000  
I/DEBUG   (  124): 
I/DEBUG   (  124): code around pc:
I/DEBUG   (  124):     4014cf68 e8bd00f0 e3700a01 912fff1e e2600000  
I/DEBUG   (  124):     4014cf78 ea006e51 e92d50f0 e3a07f43 ef000000  
I/DEBUG   (  124):     4014cf88 e8bd50f0 e3700a01 912fff1e e2600000  
I/DEBUG   (  124):     4014cf98 ea006e49 e92d50f0 e3a070ee ef000000  
I/DEBUG   (  124):     4014cfa8 e8bd50f0 e3700a01 912fff1e e2600000  
I/DEBUG   (  124):     4014cfb8 ea006e41 f200429a bf0080cf f000f891  
I/DEBUG   (  124):     4014cfc8 4001e92d f040f891 d3532a10 0301ea80  
I/DEBUG   (  124):     4014cfd8 0303f013 806ef000 d3262ae0 0300f1c0  
I/DEBUG   (  124):     4014cfe8 030ff013 eba2d021 ea5f0203 bf447cc3  
I/DEBUG   (  124):     4014cff8 eb01f811 eb01f800 f811bf21 f811cb01  
I/DEBUG   (  124):     4014d008 f800eb01 f800cb01 ea5feb01 da037c43  
I/DEBUG   (  124):     4014d018 080df9a1 083df980 f921d303 f900070d  
I/DEBUG   (  124):     4014d028 f891071d f891f000 3a40f040 f891d30f  
I/DEBUG   (  124):     4014d038 f891f080 f921f0c0 f921020d f891420d  
I/DEBUG   (  124):     4014d048 3a40f0c0 020df900 420df900 f102d2f3  
I/DEBUG   (  124):     4014d058 3a200240 f921d305 3a20020d 020df900  
I/DEBUG   (  124): 
I/DEBUG   (  124): code around lr:
I/DEBUG   (  124):     4013df4c 447b4b13 42b3e010 6a1ed10e 44784811  
I/DEBUG   (  124):     4013df5c eddcf7fa ea1ef00d 46224631 e808f00f  
I/DEBUG   (  124):     4013df6c d00a3001 e00b2400 2b00681b 480ad1eb  
I/DEBUG   (  124):     4013df7c 44782403 edcaf7fa f001e002 6804fa33  
I/DEBUG   (  124):     4013df8c fa30f001 46206005 bf00bd70 0003b47a  
I/DEBUG   (  124):     4013df9c 0003b46e 0003b466 0003b442 bf7ef7ff  
I/DEBUG   (  124):     4013dfac 4a3e4b3d e92d447b b08b43f0 4606589c  
I/DEBUG   (  124):     4013dfbc 6823460d 930946a1 fa14f001 8000f8d0  
I/DEBUG   (  124):     4013dfcc d0482d00 f00f4628 280ffec9 d8444604  
I/DEBUG   (  124):     4013dfdc ffe4f7ff d1064286 4629200f e8e8f00d  
I/DEBUG   (  124):     4013dfec d03c2800 482ee02e f7fa4478 482ded0e  
I/DEBUG   (  124):     4013dffc e0154478 d11342b0 482b6a06 f7fa4478  
I/DEBUG   (  124):     4013e00c 4a2aed86 46332120 a801447a f9eaf013  
I/DEBUG   (  124):     4013e01c a8012101 fd08f01a 46061c42 e011d104  
I/DEBUG   (  124):     4013e02c 28006800 e02cd1e6 46294630 f00d4622  
I/DEBUG   (  124):     4013e03c 1c43e924 d11e4607 f9d4f001 29046801  
I/DEBUG   (  124): pid: 8133, tid: 8134, name: ReferenceQueueD
I/DEBUG   (  124): pid: 8133, tid: 8135, name: FinalizerDaemon
I/DEBUG   (  124): pid: 8133, tid: 8136, name: FinalizerWatchd
I/DEBUG   (  124): pid: 8133, tid: 8137, name: GC
I/DEBUG   (  124): pid: 8133, tid: 8138, name: Signal Catcher
I/BootReceiver(  500): Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
D/dalvikvm(  500): GC_FOR_ALLOC freed 431K, 13% free 10834K/12312K, paused 58ms, total 58ms
I/ServiceConnection(  710): Received response: +CIEV :: [Ljava.lang.Object;@41c98ec0



```

**Comment by rom1v** [comment]
> Android version: 4.4

Could not work. scrcpy requires Android 5.
