### ISSUE TITLE
ERROR: Exception on thread Thread[main,5,main]

### ISSUE THREAD

**Issue by anny-debug** [Genymobile/scrcpy#3318]
I have this message and then nothing happens.
I'm running v1.8 scrcpy
I'm using Android 12

[server] INFO: Device: asus ASUS_I002D (Android 12)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:216)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3148)
INFO: Renderer: direct3d
INFO: Initial texture: 488x1080
WARN: Device disconnected
Press any key to continue...

**Comment by rom1v** [comment]
You need scrcpy >= v1.18 for Android 12. Use the latest version (currently v1.24).
