### ISSUE TITLE
Problem when starting SCRCPY in Xiaomi

### ISSUE THREAD

**Issue by xpeqex** [Genymobile/scrcpy#3333]
- OS: Windows 10
 - scrcpy version: 1.24
 - installation method: Windows Release
 - device model: Xiaomi Remi Note 10 Pro (sweet)
 - Android version: 12

When im trying to open SCRCPY the command window open as usual, then the screen of my android is shown but closes immediately and get an error code: 

`[server] ERROR: Encoding error: java.lang.IllegalStateException: null
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)`

**Comment by rom1v** [comment]
#3051
