### ISSUE TITLE
ERROR: Exception on thread Thread

### ISSUE THREAD

**Issue by mrfoxie** [Genymobile/scrcpy#3342]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Zorin OS
 - scrcpy version: 1.12.1
 - installation method: apt
 - device model: Samsung M42 5G
 - Android version: 12

**Describe the bug**
1. I connected my phone using a data cable.
2. From the setting I turned on Developer Options and USB debugging
3. Opened up a terminal and installed necessary tools by following commands.
```
sudo apt update
sudo apt full-upgrade -y
sudo apt install adb android-tools-adb scrcpy -y
```
4. after that I got auth from my device for ADB debugging
5. Then used `adb devices` command to check connected devices
```
List of devices attached
ABCDEFGHIJ	device
```
6. My device was successfully connected to my laptop
7. After that I ran `scrcpy` command bellow is the error log.

```
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...shed. 2.7 MB/s (24773 bytes in 0.009s)
INFO: Initial texture: 720x1600
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:178)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:70)
WARN: Device disconnected
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:374)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 6 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3370)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2344)
	... 8 more

```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Android 12 resuires scrcpy >= 1.18. Use the latest version.

**Comment by mrfoxie** [comment]
> Android 12 resuires scrcpy >= 1.18. Use the latest version.

can you give me instruction to upgrade it on linux

**Comment by mrfoxie** [comment]
thank you
