### ISSUE TITLE
Scrcpy Disconnecting before it starts

### ISSUE THREAD

**Issue by PearKing05** [Genymobile/scrcpy#3349]
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 1.7 MB/s (34015 bytes in 0.019s)
[server] INFO: Device: samsung SM-A515W (Android 12)
INFO: Renderer: opengl
INFO: OpenGL version: 3.1 Mesa 20.3.5
INFO: Trilinear filtering enabled
INFO: Initial texture: 328x720
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:374)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3370)
        at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2344)
        ... 9 more
WARN: Killing the server...

OS: ChromeOS Running Linux with ADB enabled and USB access also enabled.

**Comment by rom1v** [comment]
Android 12 requires scrcpy >= 1.18. Use the latest version.
