### ISSUE TITLE
Gettin' Rekt On My Note 10+. Totally works on my SM-T150 So I Feel Confident I Know How To Use It

### ISSUE THREAD

**Issue by Jaladhjin** [Genymobile/scrcpy#3364]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Android 12
 - scrcpy version: 1.16
 - installation method: Uhm I'm sorry I'm not sure I just grabbed it from here on GH
 - device model: Note 10+
 - Android version: 12

**Describe the bug**
connected to 192.168.1.172:34649
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
C:\Users\Andrew\Downloads\SM-T510\platform-tools\scrcpy-se... file pushed, 0 skipped. 16.2 MB/s (33622 bytes in 0.002s)
adb.exe: error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27183, retrying on 27184
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27184, retrying on 27185
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27185, retrying on 27186
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27186, retrying on 27187
27187
[server] INFO: Device: samsung SM-N975U (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2280
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:216)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)Press any key to continue...

connected to 192.168.1.172:34649
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
C:\Users\Andrew\Downloads\SM-T510\platform-tools\scrcpy-se... file pushed, 0 skipped. 16.2 MB/s (33622 bytes in 0.002s)
adb.exe: error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27183, retrying on 27184
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27184, retrying on 27185
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27185, retrying on 27186
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27186, retrying on 27187
27187
[server] INFO: Device: samsung SM-N975U (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2280
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:216)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)Press any key to continue...

INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
C:\Users\Andrew\Downloads\SM-T510\platform-tools\scrcpy-se...1 file pushed, 0 skipped. 8.9 MB/s (33622 bytes in 0.004s)
[server] INFO: Device: samsung SM-N975U (Android 12)
adb.exe: error: more than one device/emulator
ERROR: "adb reverse --remove" returned with value 1
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:216)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:374)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3370)
        at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2344)
        ... 9 more
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2280
WARN: Device disconnected
Press any key to continue...

**Comment by rom1v** [comment]
Android 12 requires scrcpy >= 1.18. Just upgrade.
