### ISSUE TITLE
Exception on thread Thread

### ISSUE THREAD

**Issue by Samir-OP** [Genymobile/scrcpy#3373]
**Environment**
 - OS: Ubuntu 22.04
 - scrcpy version: 1.21-1
 - installation method: apt
 - device model:CPH2381
 - Android version: 12

**Describe the bug**
I was just trying the tool, but i have having error.

```
➜  Desktop scrcpy                            
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
/usr/share/scrcpy/scrcpy-server: 1 fil...shed. 3.5 MB/s (39473 bytes in 0.011s)
[server] INFO: Device: OnePlus CPH2381 (Android 12)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.0.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2408
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2176)
	at android.media.MediaCodec.configure(MediaCodec.java:2092)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:391)
WARN: Killing the server...
```

**Comment by rom1v** [comment]
Reduce the definition (`scrcpy -m1024`), or upgrade (newer versions automatically downsize on error).

**Comment by dibowz** [comment]
Hi @rom1v, I have the same issue as the OP, and already did what you asked but the result is still the same. Here's the console log.

- OS: Windows 10 Home 21H2 x64
- Scrcpy version: scrcpy-win64-v1.24
- Installation method: zip
- Device model: M2101K6G
- Android version: 12 SKQ1.210908.001

```
D:\scrcpy-win64-v1.24>scrcpy -m1024
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
D:\scrcpy-win64-... file pushed, 0 skipped. 95.5 MB/s (41159 bytes in 0.000s)
[server] INFO: Device: Xiaomi M2101K6G (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 464x1024
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)WARN: Device disconnected

        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
```

**Comment by H1-N1** [comment]
Same here

OS: Windows 7
Scrcpy version: scrcpy-win32-v1.24
Installation method: zip
Device model: M2101K6G
Android version: 12 

```
C:\Users\W\Desktop\scrcpy-win32-v1.24>scrcpy -m1024
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\Users\W\Desktop\scrcpy-win32-v1.24\...ped. 11.9 MB/s (41159 bytes in 0.003s)
[server] INFO: Device: Xiaomi M2101K6G (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 464x1024
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncode
r.java:102)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:7
4)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)

C:\Users\W\Desktop\scrcpy-win32-v1.24>scrcpy.exe -s e9c63615
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\Users\W\Desktop\scrcpy-win32-v1.24\...ped. 13.7 MB/s (41159 bytes in 0.003s)
Aborted
ERROR: Server connection failed

C:\Users\W\Desktop\scrcpy-win32-v1.24>pause
Appuyez sur une touche pour continuer...
```

**Comment by rom1v** [comment]
#3051
