### ISSUE TITLE
The server version (1.23) does not match the client (1.24)

### ISSUE THREAD

**Issue by megadrifter** [Genymobile/scrcpy#3421]
Hi. I have downloaded the latest 1.24 version tar.gz. Then unpack, then run installation script and it ended successfully.

Then I try to run application and get:

```
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 4.0 MB/s (41123 bytes in 0.010s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: The server version (1.23) does not match the client (1.24)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:167)
	at com.genymobile.scrcpy.Server.main(Server.java:327)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
ERROR: Server connection failed
```
If I download 1.23 package, the same situation, it shows server version 1.22.

**Comment by rom1v** [comment]
You probably installed v1.23 in `/usr/local/share/scrcpy/scrcpy-server`.

**Comment by rom1v** [comment]
Oh, no, ok, the installation script is updated AFTER the tag when I make a release (because it depends on the binary to be built to know the checksum), so if you checkout the tag, you get the old "simple" installation script.

If you want to use the ["simple" installation script](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple), you should checkout `master` (or one commit after the release tag, e.g. https://github.com/Genymobile/scrcpy/commit/3a99e129e628911dde73f486aece1ca3ebe06ead).

**Comment by poti225** [comment]
Just had the same issue and here's a quick fix:
-get the source code
-open install-release.sh in a text editor
-edit the two "1.23" at the 5th line and replace with "1.24"
-comment out the sha256 check in the 11th line
-run the script

**Comment by rom1v** [comment]
Of course. But you could just take the commit which has the change.

**Comment by kajdjh** [comment]
> Of course. But you could just take the commit which has the change.

> Just had the same issue and here's a quick fix: -get the source code -open install-release.sh in a text editor -edit the two "1.23" at the 5th line and replace with "1.24" (or the latest version) -comment out the sha256 check in the 11th line -run the script

i'm noob windows user here, any detailed step by step to do it because i face same problem, need help please...

**Comment by rom1v** [comment]
One Windows, just download the latest release.
