### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AndreyRGW** [Genymobile/scrcpy#3426]
I use scrcpy wirelessly, but when I try to connect - I see the phone screen for a second and then I get an error.

```
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\ADB_AppControl\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 66.1 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: Xiaomi M2101K9AG (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
```

Edit 1: c2.android.avc.encoder doesn't crash, but the picture freezes.

**Comment by rom1v** [comment]
See #3051.
