### ISSUE TITLE
immediate disconnection with java exception

### ISSUE THREAD

**Issue by njamescouk** [Genymobile/scrcpy#3432]
I'm seeing this, not sure what's wrong here
 
 $ scrcpy
  INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
  /usr/share/scrcpy/scrcpy-server: 1 fil...shed. 7.1 MB/s (24773 bytes in 0.003s)
  INFO: Initial texture: 1080x2160
  [server] ERROR: Exception on thread Thread[main,5,main]WARN: Device disconnected
  
  java.lang.IllegalStateException
	  at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	  at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2849)
	  at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:92)
	  at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
	  at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	  at com.genymobile.scrcpy.Server.main(Server.java:163)
	  at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	  at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)

**Comment by rom1v** [comment]
Try with a lower resolution: `scrcpy -m1024`.

Also, 1.12.1 is very very old. You should install the latest version manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple (and uninstall the package from your distro).

**Comment by njamescouk** [comment]
downloaded  and compiled flawlessly, now in full working order.
