### ISSUE TITLE
Crash on startup Windows 10

### ISSUE THREAD

**Issue by Kobi-Hadad** [Genymobile/scrcpy#3439]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:  Windows
 - scrcpy version: v1.24
 - installation method: Windows release
 - device model: Xiaomi redmi note 10 pro
 - Android version: 12

**Describe the bug**
A second or two after executing scrcpy.exe it shows my android screen for a split second before it closes.

```
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\Users\Kob\Desktop\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 48.6 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: Xiaomi M2101K6G (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
```

**Comment by rom1v** [comment]
#3051
