### ISSUE TITLE
Huawei Matepad Paper connect failed

### ISSUE THREAD

**Issue by hotbak1** [Genymobile/scrcpy#3452]
- [+] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [+] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Arch Linux
 - scrcpy version: 1.24
 - installation method: pacman
 - device model: Huawei Matepad Paper
 - Android version: HarmonyOS 2.1.0.156

**Describe the bug**
Connection failed. I'm using it with huawei's matepad paper and matepad pro. It works well with matepad pro, but mistake pops out when it meet matepad paper(an eink tablet) .

```
❯ adb devices
List of devices attached
MVGYD22226200544        device

❯ scrcpy
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 540.9 MB/s (41159 bytes in 0.000s)
[server] INFO: Device: HUAWEI HMW-W09 (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.1.6
INFO: Trilinear filtering enabled
INFO: Initial texture: 1400x1872
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] INFO: Retrying with -m1600...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] INFO: Retrying with -m1280...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] INFO: Retrying with -m1024...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] INFO: Retrying with -m800...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2131)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:100)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```

**Comment by rom1v** [comment]
The device encoder fails at any resolution.

You might try another encoder if there are any others: https://github.com/Genymobile/scrcpy#encoder

**Comment by hotbak1** [comment]
> 

Thank you, problem solved

**Comment by igotcha** [comment]
能否提供一下您是如何解决的? 这样给其他人也有帮忙 ?

> > 设备编码器在任何分辨率下都会失败。
> > 如果有其他编码器，您可以尝试其他编码器：[https ://github.com/Genymobile/scrcpy#encoder](https://github.com/Genymobile/scrcpy#encoder)
> 
> 谢谢，问题解决了

**Comment by solody** [comment]
When using scrcpy 1.x on Ubuntu, use the follow command:
`scrcpy --encoder=OMX.google.h264.encoder`

This works for me.
