### ISSUE TITLE
scrcpy not working

### ISSUE THREAD

**Issue by amirhossein-fzl** [Genymobile/scrcpy#3459]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Debian 11
 - scrcpy version: 1.17
 - installation method: apt
 - device model: Samsung Galaxy A71
 - Android version: 12

I wan't to use scrcpy. but I get the following error:

```INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 f...d. 39.7 MB/s (34015 bytes in 0.001s)
[server] INFO: Device: samsung SM-A715F (Android 12)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:374)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 7 moreINFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 20.3.5
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2400
WARN: Device disconnected

Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3370)
        at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2344)
        ... 9 more
WARN: Killing the server...
```

**Comment by rom1v** [comment]
Android 12 requires scrcpy >= 1.18. #2129

**Comment by konstin** [comment]
would it be possible to show some kind of warning about incompatible android versions? I followed the `apt install scrcpy` instruction from the readme on ubuntu 20.04 and ran directly into this

**Comment by rom1v** [comment]
> would it be possible to show some kind of warning about incompatible android versions?

No, because these incompatibility are not known at the time a release is out. They are fixed or worked around in a future version, so an old version can't know. (And scrcpy does not communicate with any server, it's unnecessary and it's better for privacy).
