### ISSUE TITLE
ACodec  : [OMX.google.h264.encoder] ERROR(0x80001001)

### ISSUE THREAD

**Issue by sbeh** [Genymobile/scrcpy#349]
Sorry guys for just dumping that here, but I've no clue what to look for. I guess my devices doesn't have hardware acceleration when it comes to video encoding:

```
C:\scrcpy-win64-v1.5\scrcpy-win64>scrcpy.exe
scrcpy-server.jar: 1 file pushed. 1.5 MB/s (19178 bytes in 0.012s)
ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:1901)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:75)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:25)
        at com.genymobile.scrcpy.Server.main(Server.java:109)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:256)
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
ERROR: Could not open video stream
INFO: Initial texture: 480x800
Press any key to continue...
```

```
11-20 17:03:03.885 10176 10176 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
11-20 17:03:03.896 10176 10176 D AndroidRuntime: CheckJNI is OFF
11-20 17:03:03.896 10176 10176 E cutils-trace: Error opening trace file: No such file or directory (2)
11-20 17:03:03.918 10176 10176 W art     : 
  [...stripped...]
11-20 17:03:04.030 10176 10176 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
11-20 17:03:04.215 10176 10176 I Radio-JNI: register_android_hardware_Radio DONE
11-20 17:03:04.291 10176 10176 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
11-20 17:03:04.355 10176 10176 I art     : Thread[1,tid=10176,Native,Thread*=0x1a66e50,peer=0x12c2b1c0,"main"] recursive attempt to load library "/system/lib/libmedia_jni.so"
11-20 17:03:04.356 10176 10176 D MtpDeviceJNI: register_android_mtp_MtpDevice
11-20 17:03:04.357 10176 10176 I art     : Thread[1,tid=10176,Native,Thread*=0x1a66e50,peer=0x12c2b1c0,"main"] recursive attempt to load library "/system/lib/libmedia_jni.so"
11-20 17:03:04.358 10176 10176 I art     : Thread[1,tid=10176,Native,Thread*=0x1a66e50,peer=0x12c2b1c0,"main"] recursive attempt to load library "/system/lib/libmedia_jni.so"
11-20 17:03:04.371 10176 10189 I OMXClient: Using client-side OMX mux.
11-20 17:03:04.430 10176 10189 W ACodec  : do not know color format 0x7f000789 = 2130708361
11-20 17:03:04.430 10176 10189 I ACodec  : setupVideoEncoder succeeded
11-20 17:03:04.430 10176 10189 W ACodec  : do not know color format 0x7f000789 = 2130708361
11-20 17:03:04.460 10176 10194 D SoftAVCEnc: Params width 480 height 800 level 41 colorFormat 0
11-20 17:03:04.514 10176 10194 E SoftVideoEncoderOMXComponent: Unsupported pixel format 0x2
11-20 17:03:04.514 10176 10194 E SoftAVCEnc: Error in extractGraphicBuffer
11-20 17:03:04.514 10176 10189 E ACodec  : [OMX.google.h264.encoder] ERROR(0x80001001)
11-20 17:03:04.514 10176 10189 E ACodec  : signalError(omxError 0x80001001, internalError -2147483648)
11-20 17:03:04.514 10176 10189 E ACodec  : [OMX.google.h264.encoder] ERROR(0x80001001)
11-20 17:03:04.514 10176 10189 E ACodec  : signalError(omxError 0x80001001, internalError -2147483648)
11-20 17:03:04.514 10176 10188 E MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
11-20 17:03:04.516 10176 10188 E MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 0
11-20 17:03:04.517 10176 10176 D AndroidRuntime: Shutting down VM
11-20 17:03:04.521 10176 10176 E scrcpy  : Exception on thread Thread[main,5,main]
11-20 17:03:04.521 10176 10176 E scrcpy  : java.lang.IllegalStateException
11-20 17:03:04.521 10176 10176 E scrcpy  :      at android.media.MediaCodec.native_stop(Native Method)
11-20 17:03:04.521 10176 10176 E scrcpy  :      at android.media.MediaCodec.stop(MediaCodec.java:1901)
11-20 17:03:04.521 10176 10176 E scrcpy  :      at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:75)
11-20 17:03:04.521 10176 10176 E scrcpy  :      at com.genymobile.scrcpy.Server.scrcpy(Server.java:25)
11-20 17:03:04.521 10176 10176 E scrcpy  :      at com.genymobile.scrcpy.Server.main(Server.java:109)
11-20 17:03:04.521 10176 10176 E scrcpy  :      at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-20 17:03:04.521 10176 10176 E scrcpy  :      at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:256)
11-20 17:03:04.760  1386  1386 W libEGL  : EGLNativeWindowType 0x629610 disconnect failed
```

**Comment by rom1v** [comment]
Which Android version?

**Comment by NixonNelson** [comment]
Hey ,I had this similar problem but it was caused due to  the  permission for usb debugging  not set correctly. i  just revoke the USB debugging authorization
and turned off the developer options and then turned it on again 
turned the usb debugging on, the restarted  scrcpy
and it worked for me !

**Comment by sbeh** [comment]
@rom1v 6.0.1
@NixonNelson thanks, didn't help, also unplugged USB and tried Wifi, same error

**Comment by rom1v** [comment]
@sbeh 
Could you try:

    adb shell screenrecord /sdcard/file.mp4
    adb pull /sdcard/file.mp4

Does it work?

**Comment by sbeh** [comment]
Nope, doesn't work:

```
C:\> adb shell
root@:/ # screenrecord /sdcard/file.mp4
Encoder failed (err=-38)
root@:/ # logcat
11-21 10:37:53.562  7377  7382 I OMXClient: Using client-side OMX mux.
11-21 10:37:53.600  7377  7382 W ACodec  : do not know color format 0x7f000789 = 2130708361
11-21 10:37:53.600  7377  7382 I ACodec  : setupVideoEncoder succeeded
11-21 10:37:53.600  7377  7382 W ACodec  : do not know color format 0x7f000789 = 2130708361
11-21 10:37:53.617  7377  7382 E cutils-trace: Error opening trace file: No such file or directory (2)
11-21 10:37:53.623  7377  7384 D SoftAVCEnc: Params width 1280 height 720 level 41 colorFormat 0
11-21 10:37:53.678  7377  7377 I MPEG4Writer: limits: 4294967295/0 bytes/us, bit rate: -1 bps and the estimated moov size 3195 bytes
11-21 10:37:53.701  7377  7384 E SoftVideoEncoderOMXComponent: Unsupported pixel format 0x2
11-21 10:37:53.701  7377  7384 E SoftAVCEnc: Error in extractGraphicBuffer
11-21 10:37:53.701  7377  7382 E ACodec  : [OMX.google.h264.encoder] ERROR(0x80001001)
11-21 10:37:53.701  7377  7382 E ACodec  : signalError(omxError 0x80001001, internalError -2147483648)
11-21 10:37:53.701  7377  7382 E ACodec  : [OMX.google.h264.encoder] ERROR(0x80001001)
11-21 10:37:53.701  7377  7382 E ACodec  : signalError(omxError 0x80001001, internalError -2147483648)
11-21 10:37:53.702  7377  7381 E MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
11-21 10:37:53.702  7377  7377 W ScreenRecord: dequeueOutputBuffer returned INVALID_OPERATION
11-21 10:37:53.704  7377  7381 E MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 0
11-21 10:37:53.704  7377  7377 D MPEG4Writer: Video track stopping
11-21 10:37:53.704  7377  7377 D MPEG4Writer: Video track source stopping
11-21 10:37:53.704  7377  7377 D MPEG4Writer: Video track source stopped
11-21 10:37:53.705  7377  7388 E MPEG4Writer: The number of recorded samples is 0
11-21 10:37:53.705  7377  7388 W MPEG4Writer: 0-duration samples found: 1
11-21 10:37:53.705  7377  7388 W MPEG4Writer: 0-duration samples found: 1
11-21 10:37:53.705  7377  7388 I MPEG4Writer: Received total/0-length (0/0) buffers and encoded 0 frames. - Video
11-21 10:37:53.705  7377  7377 D MPEG4Writer: Video track stopped
11-21 10:37:53.705  7377  7377 D MPEG4Writer: Stopping writer thread
11-21 10:37:53.705  7377  7387 D MPEG4Writer: 0 chunks are written in the last batch
11-21 10:37:53.705  7377  7377 D MPEG4Writer: Writer thread stopped
11-21 10:37:53.706  7377  7382 W GraphicBufferSource: Dropped back down to Loaded without Executing
11-21 10:37:53.712  7377  7377 D MPEG4Writer: Video track stopping
11-21 10:37:53.714  7377  7377 D ScreenRecord: failed
11-21 10:37:53.769  4959  4995 W ProcessCpuTracker: Skipping unknown process pid 7377
```

**Comment by rom1v** [comment]
OK, so yes your device have a problem to encode :) It's surprising for an Android 6 device. Which is it?

**Comment by sbeh** [comment]
Don't worry, it's some cheapass ASUS tablet ;)

**Comment by lpf-l** [comment]
I encountered the same mistake. Is it a version problem?

**Comment by shjman** [comment]
i encounter this mistake on emulator api 21.  and don't know how to fix it

**Comment by rom1v** [comment]
I'm closing, since the problem also occurs with `adb screenrecord` (so it is not related to scrcpy).
