### ISSUE TITLE
some thing wrong with my miui or scrcpy

### ISSUE THREAD

**Issue by ThinhGia2012** [Genymobile/scrcpy#3519]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 10]
 - scrcpy version: [Lastest]
 - installation method: [de internek]
 - device model:Redmi 10C
 - Android version: {12]

This error keep pop up that is might from java or some program in my Windows can make this issue, the screen mirror can just pop up and disappear for 0.1 second
This is the issue error code: [server] ERROR: Encoding error: java.lang.IllegalStateException: null  (this guy pop up for 2 times in terminal) and [server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363) 
help me pls

**Comment by rom1v** [comment]
See #3051.
