### ISSUE TITLE
Only open in a second

### ISSUE THREAD

**Issue by azaarskasda** [Genymobile/scrcpy#3538]
- [✓] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [✓] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 11]
 - scrcpy version: [1.24]
 - installation method: [Windows]
 - device model: Redmi Note 10 Pro
 - Android version: [MIUI 13.0.4]

**Describe the bug**

It only appears in a split of a second and then it closes. I have tried to use different USB cables and plug it in a different port but still it can't be opened.

C:\WINDOWS\system32>scrcpy >= 1.18
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
WARN: Device disconnected
java.lang.IllegalStateException

        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
``

**Comment by rom1v** [comment]
In #3051:

> EDIT2: to fix the problem, [upgrade to MIUI 13.0.12](https://github.com/Genymobile/scrcpy/issues/3051#issuecomment-1220515152).

What is your version?

**Comment by azaarskasda** [comment]
I've written it its MIUI 13.0.14

**Comment by rom1v** [comment]
> I've written it its MIUI 13.0.4. And even i have updated it to 13.0.6 its still not working

Apparently, it's fixed in MIUI 13.0.12, so you must wait for an update from Xiaomi… (13.0.12 > 13.0.4)

**Comment by Thiasap** [comment]
try
    `--encoder 'c2.android.avc.encoder'`
or
    `--encoder 'OMX.google.h264.encoder' `

**Comment by IzumiCypherX** [comment]
> try `--encoder 'c2.android.avc.encoder'` or `--encoder 'OMX.google.h264.encoder' `

It is resulting in 1) a very bad quality output, 2) A still image, of the frame when scrcpy was launched.

P.S: I'm using same model as OP of this issue and have tried all the fixes suggested henceforth.
