### ISSUE TITLE
WARN: Device disconnected WARN: Killing the server...

### ISSUE THREAD

**Issue by xiaoxiaoxiaoxiaowu** [Genymobile/scrcpy#3564]
E:\\scrcpy-server: 1 file pushed, 0 skipped. 46.1 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: Xiaomi 2201123C (Android 12)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3238)
        at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2257)
        ... 9 more
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
WARN: Device disconnected
WARN: Killing the server...

**Comment by rom1v** [comment]
Android 12 requires scrcpy >= 1.18. Use the latest version.

**Comment by Ashish-Pahal** [comment]
using v2.0.. still the same error. Any suggestions ?

**Comment by rom1v** [comment]
> using v2.0.. still the same error.

Probably not exactly the same. Please copy-paste your terminal output.

**Comment by Ashish-Pahal** [comment]
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
D:\Softwares\Scrcpy + Adb\scrcpy-win64-v2.0\scrcpy-win64-v...1 file pushed, 0 skipped. 8.7 MB/s (52867 bytes in 0.006s)
[server] INFO: Device: samsung SM-M317F (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
WARN: Device disconnected
Press any key to continue . . .

**Comment by rom1v** [comment]
OK, so this is different, here you just lose the adb connection without exception. Is it immediately (you never see the mirroring window) or after few seconds?

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-disconnected

**Comment by Ashish-Pahal** [comment]
scrcpy --no-audio

D:\Softwares\Scrcpy + Adb\scrcpy-win64-v2.0\scrcpy-win64-v2.0>scrcpy --no-audio
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
D:\Softwares\Scrcpy + Adb\scrcpy-win64-v2.0\scrcpy-win64-v...file pushed, 0 skipped. 169.9 MB/s (52867 bytes in 0.000s)
[server] INFO: Device: samsung SM-M317F (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
WARN: Device disconnected

scrcpy -m1024

D:\Softwares\Scrcpy + Adb\scrcpy-win64-v2.0\scrcpy-win64-v2.0>scrcpy -m1024
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
D:\Softwares\Scrcpy + Adb\scrcpy-win64-v2.0\scrcpy-win64-v...file pushed, 0 skipped. 259.6 MB/s (52867 bytes in 0.000s)
[server] INFO: Device: samsung SM-M317F (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 464x1024
WARN: Device disconnected

both worked for a few seconds then disconnected/closed.

**Comment by Ashish-Pahal** [comment]
Hi, Thankyou for the support! it worked when I plugged in another port.
