### ISSUE TITLE
cmd start error

### ISSUE THREAD

**Issue by l511809934** [Genymobile/scrcpy#3581]
C:\Users\Gientech>adb shell CLASSPATH=/data/local/tmp/scrcpy-server-v1.24 app_process / com.genymobile.scrcpy.Server 1.24 -L
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Invalid key=value pair: "-L"
        at com.genymobile.scrcpy.Server.createOptions(Server.java:177)
        at com.genymobile.scrcpy.Server.main(Server.java:331)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)

C:\Users\Gientech>adb shell CLASSPATH=/data/local/tmp/scrcpy-server-v1.24 app_process / com.genymobile.scrcpy.Server 1.24
[server] INFO: Device: Xiaomi Redmi K30 5G (Android 12)
[server] ERROR: Exception on thread Thread[main,5,main]
java.io.IOException: Connection refused
        at android.net.LocalSocketImpl.connectLocal(Native Method)
        at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:259)
        at android.net.LocalSocket.connect(LocalSocket.java:148)
        at com.genymobile.scrcpy.DesktopConnection.connect(DesktopConnection.java:45)
        at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:72)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:74)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)

C:\Users\Gientech>

**Comment by rom1v** [comment]
What are you trying to do?

**Comment by markosc** [comment]
I run the command scrcpy.exe and I can't open
I don't know if it's because android was updated or it's something else

**Comment by l511809934** [comment]
I am trying to display the screen in a web page.there are 3 steps I try to do:
1.push the scrcpy's server file into android device and start it by adb command.
2.connect to the scrcpy's server using a Java socket to get the stream data.
3.using stream data to show the screen on a web page.
this is the start commmad :
`adb shell CLASSPATH=/data/local/tmp/scrcpy-server-v1.24 app_process / com.genymobile.scrcpy.Server 1.24 log_level=info bit_rate=8000000 tunnel_forward=true max_fps=15 control=true display_id=0 stay_awake=true`
runs ok now.
but I do not know how to connet the server now.
Can you give me some advice on how to connect  scrcpy's server with Java sockets? What are the IP address and port number of 1.24 .
Thanks.

**Comment by rom1v** [comment]
Check https://code.videolan.org/rom1v/vlc/-/merge_requests/20 for an example.

**Comment by rom1v** [comment]
@markosc What's the error message (run `scrcpy-console.bat`)?
Note that you asked your question on an "issue" which is not related to your problem.

**Comment by l511809934** [comment]
thanks lot sir.moreover ,does scrcpy surport multi-screen?not mutil-device.you know ,based on vehicle-mounted system. there are several screens on the android system.if not surport, Can you give me some advice.

**Comment by rom1v** [comment]
Please read the README: https://github.com/Genymobile/scrcpy#display

**Comment by l511809934** [comment]
awesome, appreciate it.

**Comment by 916881120** [comment]
大佬你是搞类似云端群控的吗  能留个QQ吗或者V 请教点问题 不白票

**Comment by l511809934** [comment]
> 大佬你是搞类似云端群控的吗  能留个QQ吗或者V 请教点问题 不白票

主页有邮箱，您可以联系我
