### ISSUE TITLE
[server] WARN: Unknown event type: 56

### ISSUE THREAD

**Issue by feuerdrachenatem** [Genymobile/scrcpy#3629]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 Version 21H2 (OS Build 19044.2364)
 - scrcpy version: 1,24
 - installation method: Windows release
 - device model: Google Pixel 7
 - Android version: 13 TQ1A.221205.011 (December update)

**Describe the bug**
I had the same issue as [#3628](https://github.com/Genymobile/scrcpy/issues/3628) and have tried the solution described in [#3497 (comment)](https://github.com/Genymobile/scrcpy/issues/3497#issuecomment-1359094255), however I have found a new bug in that scrcpy-server binary. Tested and confirmed, it's only after I try to scroll with my mouse's scroll wheel (scroll wheel worked fine with binary included in 1.24 Windows release). Every subsequent input (mouse or keyboard) gives the warning. I have left out the _looooong_ list of **all** the warnings to keep this report short. 

```
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
C:\Users\jakef\platform-tools\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 2.5 MB/s (41159 bytes in 0.016s)
[server] INFO: Device: Google Pixel 7 (Android 13)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
        at java.lang.Class.getMethod(Class.java:2103)
        at java.lang.Class.getMethod(Class.java:1724)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
        at com.genymobile.scrcpy.Device.<init>(Device.java:103)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:65)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
[server] WARN: Unknown event type: 56
...
[server] WARN: Unknown event type: 56
```

**Comment by rom1v** [comment]
Oh, I mistakenly wrote the patch on `dev` branch, which is incompatible with the 1.24 client.

I edited the server binary in the comment: https://github.com/Genymobile/scrcpy/issues/3497#issuecomment-1359094255

 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/3497/5/scrcpy-server) <sub>`SHA-256: f5e633584164bbd1105e58dedfd7bb1262e6a8a75553ec674737b8e7315dd2b2`</sub>

Please confirm that you don't have "Unknown event type" warnings anymore.

**Comment by feuerdrachenatem** [comment]
Wow, that was fast. Apologies for my slow response.

Downloaded the proper server binary, can confirm that there are no more warnings. **Thank you!**
