### ISSUE TITLE
[server] ERROR: Exception on thread Thread[main,5,main]

### ISSUE THREAD

**Issue by Gipors** [Genymobile/scrcpy#3636]
Windows 10 Pro 22H2, x64

scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
D:\Portable\scrcpy-win64-v1.25\scrcpy-server: 1 file pushed, 0 skipped. 32.9 MB/s (42151 bytes in 0.001s)
[server] INFO: Device: skyworth 7T855_A5P (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
        at android.media.MediaCodec.getCurProcessName(MediaCodec.java:1913)
        at android.media.MediaCodec.setSkyMediaStatus(MediaCodec.java:1927)
        at android.media.MediaCodec.release(MediaCodec.java:1949)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:124)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:334)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
INFO: Renderer: direct3d
INFO: Initial texture: 1920x1080
WARN: Device disconnected
WARN: Killing the server...

I have tried [ scrcpy -m 800] / [ scrcpy --encoder=OMX.google.h264.encoder ]. Nothing happend

**Comment by krrishdholakia** [comment]
What device are you trying to connect with scrcpy? - [Clerkie](https://calendly.com/kdholakia/clerkie-customer-discovery-call)

**Comment by Mogez** [comment]
```
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
D:\protools\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 75.4 MB/s (42151 bytes in 0.001s)
[server] INFO: Device: Skyworth 8H57_H5 (Android 5.1.1)
INFO: Renderer: direct3d
INFO: Initial texture: 1280x720
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
        at android.media.MediaCodec.getCurProcessName(MediaCodec.java:527)
        at android.media.MediaCodec.setSkyMediaStatus(MediaCodec.java:547)
        at android.media.MediaCodec.release(MediaCodec.java:565)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:124)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:334)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
WARN: Killing the server...
```

I got the similar issue.  But everything works fine now, after I downgraded to **scrcpy v1.19**.
