### ISSUE TITLE
After Mi 11 Ultra is upgraded to Android 13, the connection is successful, but it can only be viewed but not controlled

### ISSUE THREAD

**Issue by DustinWin** [Genymobile/scrcpy#3698]
Scrcpy version: v2.1.2
Model: Mi 11 Ultra
System: MIUI14 (Android 13)
Problem: After a successful wired connection, Scrcpy can only view the screen of the mobile phone, but cannot control the screen of the mobile phone. The error message is as follows:
```
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:916)
        at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:617)
        at android.os.Binder.execTransactInternal(Binder.java:1285)
        at android.os.Binder.execTransact(Binder.java:1249)

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:35)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:196)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:231)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:102)
        at com.genymobile.scrcpy.Controller.control(Controller.java:79)
        at com.genymobile.scrcpy.Server$3.run(Server.java:132)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 9 more
```

**Comment by rom1v** [comment]
Does it work if you enable Security Settings: https://github.com/appium/appium/issues/13802#issuecomment-587802222

**Comment by DustinWin** [comment]
> Does it work if you enable Security Settings: [appium/appium#13802 (comment)](https://github.com/appium/appium/issues/13802#issuecomment-587802222) ?

That was the reason, thank you very much!
