### ISSUE TITLE
Manual build not working.

### ISSUE THREAD

**Issue by abalta-mobven** [Genymobile/scrcpy#3711]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [macOS]
 - scrcpy version: [1.25]
 - installation method: [manual build]
 - device model: Google Pixel 7 Pro
 - Android version: [13]

**Describe the bug**
I followed BUILD.md, firstly I configure meson then build with ninja. After that, I copied x/server/scrcpy-server on device data /local/tmp

Then fun adb sheel command below. Without manual build, scrcpy works. Manual build does not work.

```
adb shell CLASSPATH=/data/local/tmp/scrcpy-server app_process / com.genymobile.scrcpy.Server 1.25
[server] INFO: Device: Google Pixel 7 Pro (Android 13)
[server] ERROR: Exception on thread Thread[Thread-2,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.ServiceManager.getService(ServiceManager.java:45)
	at com.genymobile.scrcpy.wrappers.ServiceManager.getPowerManager(ServiceManager.java:85)
	at com.genymobile.scrcpy.Device.isScreenOn(Device.java:220)
	at com.genymobile.scrcpy.Controller.control(Controller.java:73)
	at com.genymobile.scrcpy.Server$2.run(Server.java:127)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ServiceManager.getService(ServiceManager.java:41)
	... 5 more
Caused by: java.lang.RuntimeException: Bad file descriptor
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:421)
	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
	at android.os.ServiceManager.rawGetService(ServiceManager.java:372)
	at android.os.ServiceManager.getService(ServiceManager.java:147)
	... 7 more
```

**Comment by rom1v** [comment]
If you build manually but use the scrcpy client normally, does it work?

**Comment by abalta-mobven** [comment]
I try to run with "scrcpy" command. It stuck with following.

/opt/homebrew/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 90.2 MB/s (42151 bytes in 0.000s)
2023-02-01 13:43:36.962 scrcpy[80565:47540112] INFO: Server debugger waiting for a client on device port 5005...

By the way, I want to develop my own client, I want to figure out how server works. So, I remove some codes on source code. When, I try to run as usual application. Some method requires INJECT_PERMISSION. I think pure java application does not need this permissions.

**Comment by rom1v** [comment]
> /opt/homebrew/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 90.2 MB/s (42151 bytes in 0.000s)
> 2023-02-01 13:43:36.962 scrcpy[80565:47540112] INFO: Server debugger waiting for a client on device port 5005...

Apparently you enabled the `server_debugger` options.

What exact commands did you execute for `meson`?

> So, I remove some codes on source code.

First, please test without removing source code and make sure it works with the original version :)

**Comment by abalta-mobven** [comment]
I use following command: meson setup x --buildtype=release --strip -Db_lto=true

I revert server code, then run app_process again. It waits here, I think it runs well. Is there any difference about meson/ninja build or gradle build? I think meson output file is jar, gradle output is apk. Right?

[server] INFO: Device: Google Pixel 7 Pro (Android 13)
[server] DEBUG: Using encoder: 'c2.exynos.h264.encoder'

**Comment by rom1v** [comment]
>  Is there any difference about meson/ninja build or gradle build?

meson/ninja builds the client code, and calls gradle for building the server (cf `server/meson.build`).
