### ISSUE TITLE
screen content hidden problem 

### ISSUE THREAD

**Issue by hosamasd** [Genymobile/scrcpy#3718]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [ Windows or linux]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [ snap, andWindows ...]
 - device model:cubot x50  
 - Android version: 13 

**Describe the bug**
i install 13 android gsi from this li

https://user-images.githubusercontent.com/34996617/216806634-f4773d3f-d85d-4bab-baad-90b779b70d98.mp4

nk
https://github.com/TrebleDroid/treble_experimentations/releases
but when start scrcpy 
the conent not appear
i root my device using magisk
pls help

**Comment by rom1v** [comment]
Looks like an encoder issue.

Try with another encoder: https://github.com/Genymobile/scrcpy#encoder

**Comment by hosamasd** [comment]
> Looks like an encoder issue.
> 
> Try with another encoder: https://github.com/Genymobile/scrcpy#encoder

not work 

scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 6.7 MB/s (42151 bytes in 0.006s)
[server] INFO: Device: CUBOT X50 (Android 13)
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 20.0.8
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2400
[server] ERROR: Exception on thread Thread[main,5,main]
com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name 'OMX.qcom.video.encoder.avc"
	at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:222)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:83)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
	at com.genymobile.scrcpy.Server.main(Server.java:334)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
[server] ERROR: Try to use one of the available encoders:
[server] ERROR:     scrcpy --encoder 'OMX.MTK.VIDEO.ENCODER.AVC'
[server] ERROR:     scrcpy --encoder 'c2.android.avc.encoder'
[server] ERROR:     scrcpy --encoder 'OMX.google.h264.encoder'
WARN: Device disconnected
