### ISSUE TITLE
ERROR: Could not open video stream - do not know color format (Nexus 7 - 6.0.1)

### ISSUE THREAD

**Issue by RaiMan** [Genymobile/scrcpy#372]
... and I am getting some startup errors related to version 1.4 like

> ERROR: Could not open video stream

**Comment by RaiMan** [comment]
thanks for the unexpected ;-) immediate reply.

I am the developer of SikuliX (https://github.com/RaiMan/SikuliX1), which has an experimental access to Android devices (via https://github.com/vidstige/jadb). It uses the ``shell screencap`` to get a screenshot from the device. 

A user of SikuliX pointed me to your project, saying that it works much faster and smoother. So I started my experiences while admitting, that I am by far not an Android expert.

My device is a Nexus 7 running Android 6.0.1 attached via USB and USB-Debugging activated.
Display 1200 x 1920.

```
adb devices -l
List of devices attached
094da986               device usb:337641472X product:razor model:Nexus_7 device:flo transport_id:2
```

My main dev environment is on Mac, but I will now try on my Windows 10 as well.

If you can get me on the road - much appreciated.

If i can do more to get nearer, we might as well open another issue, with a more meaningful heading. 

I guess this is the relevant part from the log 

```
12-08 11:44:46.640 15705 15705 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
12-08 11:44:46.646 15705 15705 D AndroidRuntime: CheckJNI is OFF
12-08 11:44:46.706 15705 15705 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
12-08 11:44:46.765 15710 15710 E dex2oat : Failed to create oat file: /data/dalvik-cache/arm/data@local@tmp@scrcpy-server.jar@classes.dex: Permission denied
12-08 11:44:46.765 15710 15710 I dex2oat : dex2oat took 762.939us (threads: 4) 
12-08 11:44:46.768 15705 15705 W art     : Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg /data/local/tmp/scrcpy-server.jar --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/local/tmp/scrcpy-server.jar --oat-file=/data/dalvik-cache/arm/data@local@tmp@scrcpy-server.jar@classes.dex) because non-0 exit status
12-08 11:44:46.813 15705 15705 I Radio-JNI: register_android_hardware_Radio DONE
12-08 11:44:46.844 15705 15705 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
12-08 11:44:46.882 15705 15705 I art     : Thread[1,tid=15705,Native,Thread*=0xb4cf6500,peer=0x12c2b160,"main"] recursive attempt to load library "/system/lib/libmedia_jni.so"
12-08 11:44:46.883 15705 15705 D MtpDeviceJNI: register_android_mtp_MtpDevice
12-08 11:44:46.884 15705 15705 I art     : Thread[1,tid=15705,Native,Thread*=0xb4cf6500,peer=0x12c2b160,"main"] recursive attempt to load library "/system/lib/libmedia_jni.so"
12-08 11:44:46.885 15705 15705 I art     : Thread[1,tid=15705,Native,Thread*=0xb4cf6500,peer=0x12c2b160,"main"] recursive attempt to load library "/system/lib/libmedia_jni.so"
12-08 11:44:46.896 15705 15727 I OMXClient: Using client-side OMX mux.
12-08 11:44:46.899   196   927 E OMX-VENC-720p: 
12-08 11:44:46.899   196   927 E OMX-VENC-720p:  Is component secure 0
12-08 11:44:46.922   196   636 E OMX-VENC-720p: set_parameter: metamode is valid for input port only
12-08 11:44:46.922   196   636 E OMXNodeInstance: setParameter(30:qcom.encoder.avc, OMX.google.android.index.storeMetaDataInBuffers(0x7f00001c): Output:1 en=0 type=1) ERROR: UnsupportedSetting(0x80001019)
12-08 11:44:46.922 15705 15727 E ACodec  : [OMX.qcom.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -1010
12-08 11:44:46.923 15705 15727 W ACodec  : do not know color format 0x7f000789 = 2130708361
12-08 11:44:46.923   196   196 E OMX-VENC-720p: 
12-08 11:44:46.923   196   196 E OMX-VENC-720p: WARNING: Unsupported Color format [2130708361]
12-08 11:44:46.923   196   196 E OMX-VENC-720p: 
12-08 11:44:46.923   196   196 E OMX-VENC-720p: C2D init is successful
12-08 11:44:46.924   196   636 E OMX-VENC-720p: 
12-08 11:44:46.924   196   636 E OMX-VENC-720p: WARNING: Unsupported Color format [2130708361]
12-08 11:44:46.924   196   636 E OMX-VENC-720p: 
12-08 11:44:46.924   196   636 E OMX-VENC-720p: ERROR: Request for setting base config failed
12-08 11:44:46.924   196   636 E OMX-VENC-720p: 
12-08 11:44:46.924   196   636 E OMX-VENC-720p: ERROR: venc_set_param input failed
12-08 11:44:46.924   196   636 E OMXNodeInstance: setParameter(30:qcom.encoder.avc, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
12-08 11:44:46.924 15705 15727 E ACodec  : [OMX.qcom.video.encoder.avc] failed to set input port definition parameters.
12-08 11:44:46.924 15705 15727 E ACodec  : [OMX.qcom.video.encoder.avc] configureCodec returning error -1010
12-08 11:44:46.924 15705 15727 E ACodec  : signalError(omxError 0x80001001, internalError -1010)
12-08 11:44:46.925 15705 15726 E MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3
12-08 11:44:46.925 15705 15705 E MediaCodec: configure failed with err 0xfffffc0e, resetting...
12-08 11:44:46.944   196 15730 E OMX-VENC-720p: 
12-08 11:44:46.944   196 15730 E OMX-VENC-720p: ioctl VEN_IOCTL_CMD_READ_NEXT_MSG failed
12-08 11:44:46.944   196   927 E OMX-VENC-720p: 
12-08 11:44:46.944   196   927 E OMX-VENC-720p:  Destroy C2D instance
12-08 11:44:46.946 15705 15727 I OMXClient: Using client-side OMX mux.
12-08 11:44:46.948   196   928 E OMX-VENC-720p: 
12-08 11:44:46.948   196   928 E OMX-VENC-720p:  Is component secure 0
12-08 11:44:46.969 15705 15705 D AndroidRuntime: Shutting down VM
12-08 11:44:46.971 15705 15705 E scrcpy  : Exception on thread Thread[main,5,main]
12-08 11:44:46.971 15705 15705 E scrcpy  : android.media.MediaCodec$CodecException: Error 0xfffffc0e
12-08 11:44:46.971 15705 15705 E scrcpy  : 	at android.media.MediaCodec.native_configure(Native Method)
12-08 11:44:46.971 15705 15705 E scrcpy  : 	at android.media.MediaCodec.configure(MediaCodec.java:1778)
12-08 11:44:46.971 15705 15705 E scrcpy  : 	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:158)
12-08 11:44:46.971 15705 15705 E scrcpy  : 	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:68)
12-08 11:44:46.971 15705 15705 E scrcpy  : 	at com.genymobile.scrcpy.Server.scrcpy(Server.java:25)
12-08 11:44:46.971 15705 15705 E scrcpy  : 	at com.genymobile.scrcpy.Server.main(Server.java:109)
12-08 11:44:46.971 15705 15705 E scrcpy  : 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
12-08 11:44:46.971 15705 15705 E scrcpy  : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
12-08 11:44:47.032   196   636 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
12-08 11:44:47.051   196 15733 E OMX-VENC-720p: 
12-08 11:44:47.051   196 15733 E OMX-VENC-720p: ioctl VEN_IOCTL_CMD_READ_NEXT_MSG failed
12-08 11:44:47.052   196   636 E OMX-VENC-720p: 
12-08 11:44:47.052   196   636 E OMX-VENC-720p:  Destroy C2D instance
```

**Comment by RaiMan** [comment]
same problem on Windows 10

**Comment by rom1v** [comment]
>     do not know color format 0x7f000789 = 2130708361
>     android.media.MediaCodec$CodecException: Error 0xfffffc0e

This is a problem on the device. This is weird.

Does `adb shell screenrecord /sdcard/file.mp4` correctly record the screen?

> same problem on Windows 10

(this confirms this is a problem on the device)

> I am the developer of SikuliX (https://github.com/RaiMan/SikuliX1), which has an experimental access to Android devices

If I may, I think you should explain what the project does in the README, because at first glance, I just found the changes and enhancements, things that have been fixed, but nothing which gives a high-level overview (the purpose, etc.). (I finally found http://sikulix.com/, which is what I looked for, the _What is SikuliX?_ section is perfect.)

**Comment by wafflecomposite** [comment]
> Does it work with a lower definition (`scrcpy -m 800`)?

YES. Yes it is. Thank you. Got same 0xfffffc0e error on my N7 2013 6.0.1. Up to 1280x800, it's working

**Comment by myself248** [comment]
Likewise here. Not working:

```
~/scrcpy/x$ scrcpy
/usr/local/share/scrcpy/scrcpy-server.jar: 1 file pushed. 1.6 MB/s (19734 bytes in 0.012s)
INFO: Initial texture: 1080x1920
ERROR: Could not open video stream

```
Working:

```
scrcpy -m 800
/usr/local/share/scrcpy/scrcpy-server.jar: 1 file pushed. 1.2 MB/s (19734 bytes in 0.016s)
INFO: Initial texture: 448x800

```
device info from adb:
device usb:1-3 product:jgedlteue model:SPH_L720 device:jfltespr transport_id:2

**Comment by rom1v** [comment]
`0xfffffc0e` happens when the encoder… may not encode.

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

Sorry that it does not work even at `-m800` (or maybe lower, `-m200`?).

Anyway, there is probably nothing we can do.
