### ISSUE TITLE
Scrcpy not opening on Oneplus 9

### ISSUE THREAD

**Issue by HerdarDdy** [Genymobile/scrcpy#3760]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
- [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

 - OS: Windows
 - scrcpy version: 1.17
 - installation method: NA
 - device model: LE2115 (Oneplus 9)
 - Android version: 13

**Describe the bug**
Whenever i try to connect to my Oneplus 9, it simply gives out the block i've attached. Works fine with Oneplus 5T and my tablet,

```
E:\scrcpy-win64-v1.17>scrcpy
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
E:\scrcpy-win64-v1.17\scrcpy-server: 1 file pushed, 0 skipped. 39.1 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: OnePlus LE2115 (Android 13)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:391)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3636)
        at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2446)
        ... 9 more
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 528.49
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2400
WARN: Device disconnected
WARN: Killing the server...
```

**Comment by rom1v** [comment]
Android 12 requires scrcpy >= 1.18.
