### ISSUE TITLE
Xiaomi 13 Pro Mouse and keyboard do not work with scrcpy

### ISSUE THREAD

**Issue by Wangzhe00** [Genymobile/scrcpy#3764]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 20.04
 - scrcpy version: 1.25
 - installation method: manual build
 - device model: Xiaomi 13 Pro
 - Android version: 13

**Describe the bug**

Using Xiaomi 13Pro/Android 13 , scrcpy cannot control the screen, and the USB debugging mode is enabled on the phone, the following error message is displayed:

```
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:35)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:196)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:231)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:102)
	at com.genymobile.scrcpy.Controller.control(Controller.java:79)
	at com.genymobile.scrcpy.Server$3.run(Server.java:132)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:916)
	at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:617)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1249)

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:35)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:196)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:231)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:102)
	at com.genymobile.scrcpy.Controller.control(Controller.java:79)
	at com.genymobile.scrcpy.Server$3.run(Server.java:132)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
	... 9 more

```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by Wangzhe00** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work
USB debugging mode is enabled  :(

**Comment by rom1v** [comment]
Not "USB debugging", but "USB debugging (Security Settings)".

**Comment by Wangzhe00** [comment]
> Not "USB debugging", but "USB debugging (Security Settings)" (it's another item).

As you said,  After "USB debugging (Security Settings)" is enabled, scrcpy works. thx :)

**Comment by Ra-Wo** [comment]
If "USB Debugging (Security Settings)" is enabled on your Redmi Note 13 but isn't working, try restarting your phone after enabling it, then attempt again.

**Comment by arouwa** [comment]
no it doesnt work
