### ISSUE TITLE
Doesnt not run only on my Samsung S20 Fe 

### ISSUE THREAD

**Issue by jdportillo** [Genymobile/scrcpy#3766]
jd@HP:~$ scrcpy -m 720
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 f...ed. 5.0 MB/s (34015 bytes in 0.007s)
[server] INFO: Device: samsung SM-G780G (Android 13)INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 20.3.5
INFO: Trilinear filtering enabled
INFO: Initial texture: 328x720

WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:378)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3693)
        at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2489)
        ... 9 more
WARN: Killing the server..

----------------------------------------------------------------------------------------------------------------

Doesnt not run only on my Samsung S20 Fe (my only device with androird 13)
yet does work on huawei y9 S 2019 if run by  scrcpy -m 1024, 
yet on my my Mate pad 10 with harmony os just go by  scrcpy without issue just like my samsung tab 8 with s pen.

Operating System: Debian GNU/Linux 11
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.0-21-amd64
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-3230M CPU @ 2.60GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000

thats some information just in case it can help somehow

**Comment by rom1v** [comment]
You need scrcpy >= 1.18 for android 12+.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

**Comment by jdportillo** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

does give a 404 error when I try to acces the page

**Comment by rom1v** [comment]
Documentation has been reworked: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by jdportillo** [comment]
Awesome, thanks for the helo, now it surely run and open with no issue whatsoever

**Comment by jdportillo** [comment]
> Documentation has been reworked: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

awesome, thanks so much for the hlep it's working now,
