### ISSUE TITLE
WSA streaming audio not working

### ISSUE THREAD

**Issue by bropines** [Genymobile/scrcpy#3797]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: v2
 - installation method: Windows release
 - device model: WSA Pixel 6 pro
 - Android version: 13

**Describe the bug**
Crashes when forced to turn on audio

```
Programs\scrcpy-win64-v2.0> .\scrcpy-console.bat -e --require-audio
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
C:\Users\bropi\Programs\scrcpy-win64-v2.0\scrcpy-server: 1 file pushed, 0 skipped. 93.6 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: Google Pixel 6 Pro (Android 13)
[server] ERROR: Exception on thread Thread[Thread-4,5,main]
java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe (NAME_NOT_FOUND)
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:2000)
        at android.media.MediaCodec.<init>(MediaCodec.java:1978)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1933)
        at com.genymobile.scrcpy.AudioEncoder.createMediaCodec(AudioEncoder.java:278)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:174)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:120)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:1012)
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Initial texture: 1920x1080
ERROR: Demuxer error
WARN: Killing the server...
```

**Comment by bropines** [comment]
Fixed by the `--audio-codec=aac` parameter. Apparently Microsoft removed unnecessary codecs from their version of android
