### ISSUE TITLE
Connecting to Nvidia Shield - error with scrcpy 2.0

### ISSUE THREAD

**Issue by cpo-ux** [Genymobile/scrcpy#3801]
Environment:
OS: Win 10 Pro x64 22H2
scrcpy version: 2.0
Installation method: Windows release
device model: NVIDIA SHIELD Model P2897 year: 2017
Android version: 11

Hi,

Version 1.25 works fine so I'll stay with it for now however I thought I'd try the latest version of scrcpy 2.0 and it doesn't work; I get the following, below. 

C:\MorePrograms1\scrcpy-win64_2.0>scrcpy
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
C:\MorePrograms1\scrcpy-win64_2.0\scrcpy-server: 1 file pushed, 0 skipped. 42.6 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: NVIDIA SHIELD Android TV (Android 11)
[server] ERROR: Exception on thread Thread[Thread-4,5,main]
java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:2117)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:2042)
        at com.genymobile.scrcpy.AudioEncoder.createMediaCodec(AudioEncoder.java:278)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:174)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:120)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:923)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.createPackageContext(java.lang.String, int)' on a null object reference
        at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:927)
        at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:927)
        at android.media.MediaCodec.isSupported(MediaCodec.java:1892)
        at android.media.MediaCodec.checkAppForAutoFrc(MediaCodec.java:1922)
        at android.media.MediaCodec.configureCodecParams(MediaCodec.java:2084)
        at android.media.MediaCodec.<init>(MediaCodec.java:2118)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:2042)
        at com.genymobile.scrcpy.ScreenEncoder.createMediaCodec(ScreenEncoder.java:209)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:64)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:133)
        at com.genymobile.scrcpy.Server.main(Server.java:381)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
INFO: Renderer: direct3d
ERROR: Demuxer 'audio': stream disabled due to connection error
ERROR: Demuxer 'video': stream disabled due to connection error
ERROR: Demuxer error
WARN: Killing the server...

===================
I also tried different codecs and encoders with the instructions  from [here](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#codec) but no luck and got this error because there's something wrong with the command for the encoder:

C:\MorePrograms1\scrcpy-win64_2.0>scrcpy --list-encoders
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
C:\MorePrograms1\scrcpy-win64_2.0\scrcpy-server: 1 file pushed, 0 skipped. 34.9 MB/s (52867 bytes in 0.001s)
[server] INFO: List of video encoders:
    --video-codec=h264 --video-encoder='OMX.Nvidia.h264.encoder'
    --video-codec=h264 --video-encoder='OMX.google.h264.encoder'
    --video-codec=h265 --video-encoder='OMX.Nvidia.h265.encoder'
[server] INFO: List of audio encoders:
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'

C:\MorePrograms1\scrcpy-win64_2.0>scrcpy --video-codec=h265 --video-encoder='OMX.Nvidia.h265.encoder'
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
C:\MorePrograms1\scrcpy-win64_2.0\scrcpy-server: 1 file pushed, 0 skipped. 38.8 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: NVIDIA SHIELD Android TV (Android 11)
[server] ERROR: Audio encoding error
java.io.IOException: android.system.ErrnoException: write failed: EBADF (Bad file descriptor)
        at com.genymobile.scrcpy.IO.writeFully(IO.java:33)
        at com.genymobile.scrcpy.IO.writeFully(IO.java:40)
        at com.genymobile.scrcpy.Streamer.writeDisableStream(Streamer.java:61)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:224)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:120)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:923)
Caused by: android.system.ErrnoException: write failed: EBADF (Bad file descriptor)
        at libcore.io.Linux.writeBytes(Native Method)
        at libcore.io.Linux.write(Linux.java:285)
        at libcore.io.ForwardingOs.write(ForwardingOs.java:239)
        at libcore.io.BlockGuardOs.write(BlockGuardOs.java:412)
        at android.system.Os.write(Os.java:727)
        at com.genymobile.scrcpy.IO.writeFully(IO.java:25)
        ... 6 more
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.createPackageContext(java.lang.String, int)' on a null object reference
        at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:927)
        at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:927)
        at android.media.MediaCodec.isSupported(MediaCodec.java:1892)
        at android.media.MediaCodec.checkForSecureDecoder(MediaCodec.java:1936)
        at android.media.MediaCodec.createByCodecName(MediaCodec.java:2058)
        at com.genymobile.scrcpy.ScreenEncoder.createMediaCodec(ScreenEncoder.java:203)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:64)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:133)
        at com.genymobile.scrcpy.Server.main(Server.java:381)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
INFO: Renderer: direct3d
ERROR: Demuxer 'audio': stream disabled due to connection error
ERROR: Demuxer 'video': stream disabled due to connection error
ERROR: Demuxer error

============
Not sure what else to try...

**Comment by cpo-ux** [comment]
Hi rom1v, 

That works, thanks :)

scrcpy --no-audio

**Comment by rom1v** [comment]
OK so the FakeContext to make audio works seems to break your video. (cc @yume-chan for information)

**Comment by jkr4m3r** [comment]
Came to post about this issue, can verify on My Shield Pro 2019 also.

**Comment by yume-chan** [comment]
> [server] INFO: List of audio encoders:
> --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'

There is no opus encoder, can you try `scrcpy --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'`?

Also what will happen if you run `scrcpy --no-audio --video-codec=h265 --video-encoder='OMX.Nvidia.h265.encoder'`?

I imagine if there was no `Context` by default it will throw the same error?

**Comment by cpo-ux** [comment]
scrcpy --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
above results in no go, see details below

scrcpy --no-audio --video-codec=h265 --video-encoder='OMX.Nvidia.h265.encoder'
above works fine, see details below.

"I imagine if there was no Context by default it will throw the same error?"
Do you mean just running scrcpy by itself?  If that's what you mean, then see below.

See details below.



C:\MorePrograms1\scrcpy-win64>scrcpy --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
C:\MorePrograms1\scrcpy-win64\scrcpy-server: 1 file pushed, 0 skipped. 58.6 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: NVIDIA SHIELD Android TV (Android 11)
[server] ERROR: Exception on thread Thread[Thread-4,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.createPackageContext(java.lang.String, int)' on a null object reference
        at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:927)
        at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:927)
        at android.media.MediaCodec.isSupported(MediaCodec.java:1892)
        at android.media.MediaCodec.checkForSecureDecoder(MediaCodec.java:1936)
        at android.media.MediaCodec.createByCodecName(MediaCodec.java:2058)
        at com.genymobile.scrcpy.AudioEncoder.createMediaCodec(AudioEncoder.java:272)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:174)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:120)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:923)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.createPackageContext(java.lang.String, int)' on a null object reference
        at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:927)
        at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:927)
        at android.media.MediaCodec.isSupported(MediaCodec.java:1892)
        at android.media.MediaCodec.checkAppForAutoFrc(MediaCodec.java:1922)
        at android.media.MediaCodec.configureCodecParams(MediaCodec.java:2084)
        at android.media.MediaCodec.<init>(MediaCodec.java:2118)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:2042)
        at com.genymobile.scrcpy.ScreenEncoder.createMediaCodec(ScreenEncoder.java:209)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:64)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:133)
        at com.genymobile.scrcpy.Server.main(Server.java:381)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
ERROR: Demuxer 'video': stream disabled due to connection error
ERROR: Demuxer error
WARN: Killing the server...
===========================
C:\MorePrograms1\scrcpy-win64>scrcpy --no-audio --video-codec=h265 --video-encoder='OMX.Nvidia.h265.encoder'
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
C:\MorePrograms1\scrcpy-win64\scrcpy-server: 1 file pushed, 0 skipped. 59.2 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: NVIDIA SHIELD Android TV (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1920x1080
WARN: Killing the server...
==========================
C:\MorePrograms1\scrcpy-win64>scrcpy
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
C:\MorePrograms1\scrcpy-win64\scrcpy-server: 1 file pushed, 0 skipped. 62.1 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: NVIDIA SHIELD Android TV (Android 11)
[server] ERROR: Exception on thread Thread[Thread-4,5,main]
java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:2117)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:2042)
        at com.genymobile.scrcpy.AudioEncoder.createMediaCodec(AudioEncoder.java:278)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:174)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:120)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:923)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.createPackageContext(java.lang.String, int)' on a null object reference
        at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:927)
        at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:927)
        at android.media.MediaCodec.isSupported(MediaCodec.java:1892)
        at android.media.MediaCodec.checkAppForAutoFrc(MediaCodec.java:1922)
        at android.media.MediaCodec.configureCodecParams(MediaCodec.java:2084)
        at android.media.MediaCodec.<init>(MediaCodec.java:2118)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:2042)
        at com.genymobile.scrcpy.ScreenEncoder.createMediaCodec(ScreenEncoder.java:209)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:64)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:133)
        at com.genymobile.scrcpy.Server.main(Server.java:381)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
INFO: Renderer: direct3d
ERROR: Demuxer 'video': stream disabled due to connection error
WARN: Demuxer 'audio': stream explicitly disabled by the device
ERROR: Demuxer error
WARN: Killing the server...
============================

**Comment by yume-chan** [comment]
@rom1v Scrcpy server process doesn't have any associated `Application` or `Context` instances before `fillAppInfo()`, right? I think the code added by Nvidia guarded against empty `Context`, so it works before.

Without knowing exactly what the code is doing, it's impossible to know which methods need to be patched. @cpo-ux can you pull out the `/system/framework/framework.jar` file from your system and upload here?

**Comment by cpo-ux** [comment]
@yume-chan Was my first time doing this so took me a while to figure out...  In the end I gave up on ADB shell stuff and used:  [https://github.com/Alex4SSB/ADB-Explorer](url)  I am assuming there's no personal info in this file I'm uploading :)    File is at google drive link here: [https://drive.google.com/file/d/1YPcyASPUFspoayYGoUNQQo63fQmUmk0V/view?usp=sharing](url)

**Comment by yume-chan** [comment]
> Was my first time doing this so took me a while to figure out

```sh
adb pull /system/framework/framework.jar /path/on/your/pc
```

> I am assuming there's no personal info

This is the Java part of your Android system.

![image](https://user-images.githubusercontent.com/1330321/225047264-cda2b378-9bc7-4ab7-9aee-af45e4826c2b.png)

I was right that it guarded against empty Context, but when Context exists, it invokes multiple methods including `createPackageContext`, `getApplicationContext`, `getSystemService`. These definitely requires a real App Context, I don't think it's possible to emulate them in FakeContext.

Maybe I need to check how App Context was initialized... Or try to hook the framework API calls...

**Comment by farmerbb** [comment]
Also running into this issue on my Nvidia Shield running Android 11, and can report that `scrcpy --no-audio` works just fine to resolve the error.

**Comment by rom1v** [comment]
Audio requires an app context, but it seems that the workarounds which makes Nvidia Shield fail are unrelated workarounds for Meizu phones. So let's try to split them: 3582592d2c50304146338606678ea58f05a7674f

Please test (replace this binary in the v2.0 release):

- [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/3801/1/scrcpy-server) <sub>`SHA-256: 4f40f140ddf14f62c0ff47c47071471a4d3adef827126388b5cd064c7b919d8d`</sub>

**Comment by farmerbb** [comment]
> Audio requires an app context, but it seems that the workarounds which makes Nvidia Shield fail are unrelated workarounds for Meizu phones. So let's try to split them: [3582592](https://github.com/Genymobile/scrcpy/commit/3582592d2c50304146338606678ea58f05a7674f)
> 
> Please test (replace this binary in the v2.0 release):
> 
> * [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/3801/1/scrcpy-server) `SHA-256: 4f40f140ddf14f62c0ff47c47071471a4d3adef827126388b5cd064c7b919d8d`

That scrcpy-server binary works.  I still get the `Failed to initialize audio/opus, error 0xfffffffe` error (which is expected) but video streaming works now on my Shield without using the `--no-audio` argument.

**Comment by farmerbb** [comment]
> ```
> scrcpy --list-encoders
> scrcpy --audio-codec=aac
> ```

Thanks! Audio streaming works now on the Shield using the AAC codec.

**Comment by rom1v** [comment]
:ok_hand: Merged into `dev`.

**Comment by jkr4m3r** [comment]
FWIW, 

> Audio requires an app context, but it seems that the workarounds which makes Nvidia Shield fail are unrelated workarounds for Meizu phones. So let's try to split them: [3582592](https://github.com/Genymobile/scrcpy/commit/3582592d2c50304146338606678ea58f05a7674f)
> 
> Please test (replace this binary in the v2.0 release):
> 
>     * [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/3801/1/scrcpy-server) `SHA-256: 4f40f140ddf14f62c0ff47c47071471a4d3adef827126388b5cd064c7b919d8d`

This works for me on my Shield Pro, many thanks!

**Comment by Anatoly-Vinnikov** [comment]
> Audio requires an app context, but it seems that the workarounds which makes Nvidia Shield fail are unrelated workarounds for Meizu phones. So let's try to split them: [3582592](https://github.com/Genymobile/scrcpy/commit/3582592d2c50304146338606678ea58f05a7674f)
> 
> Please test (replace this binary in the v2.0 release):
> 
> * [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/3801/1/scrcpy-server) `SHA-256: 4f40f140ddf14f62c0ff47c47071471a4d3adef827126388b5cd064c7b919d8d`

This also works on my meizu m3 note. Thanks a lot!

**Comment by Alistair1231** [comment]
will this change be merged into the next release, or will this always stay as a manual fix?

> Audio requires an app context, but it seems that the workarounds which makes Nvidia Shield fail are unrelated workarounds for Meizu phones. So let's try to split them: [3582592](https://github.com/Genymobile/scrcpy/commit/3582592d2c50304146338606678ea58f05a7674f)
> 
> Please test (replace this binary in the v2.0 release):
> 
>     * [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/3801/1/scrcpy-server) `SHA-256: 4f40f140ddf14f62c0ff47c47071471a4d3adef827126388b5cd064c7b919d8d`

This works, but in case someone else is wondering why it doesn't work, no Bluetooth headset can be connected.

**Comment by rom1v** [comment]
> will this change be merged into the next release, or will this always stay as a manual fix?

It is already merged into the `dev` branch (6ba99a62ff51c0ce209db78a9ed17f1633170027), so it will be in the next release.

**Comment by Alistair1231** [comment]
perfect, thanks!
