### ISSUE TITLE
error while trying to connect to my phone with a broken screen

### ISSUE THREAD

**Issue by bogdan141** [Genymobile/scrcpy#3806]
C:\Users\bogdan\Desktop\scrcpy-win64-v2.0>scrcpy
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
C:\Users\bogdan\Desktop\scrcpy-win64-v2.0\scrcpy-server: 1 file pushed, 0 skipped. 67.3 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: Xiaomi M2012K11AG (Android 13)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:86)
        at com.genymobile.scrcpy.Device.<init>(Device.java:66)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
        at com.genymobile.scrcpy.Server.main(Server.java:381)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:72)
        ... 5 more
ERROR: Server connection failed

**Comment by bogdan141** [comment]
got it to work somehow by rebooting
