### ISSUE TITLE
Hi guys, even after enabling security settings mouse not working. MIUI 14, Android 13 Xiaomi Note 10 Pro.

### ISSUE THREAD

**Issue by Pete11** [Genymobile/scrcpy#3824]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
And keyboard? What is the full console output?

**Comment by Pete11** [comment]
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 10 more

**Comment by rom1v** [comment]
OK, that's the permission error which is removed by enabling `Security Settings` in the Xiaomi dev options. If it's enabled, then it's not taken into account by your system (this is a bug). Try to reboot your device.

**Comment by Pete11** [comment]
After reboot everything work as it should. Thank you for your fast answer and have a beautiful day!
I'll close the threat.
