### ISSUE TITLE
Meizu MX6 cannot screen on scrcpy2.0.

### ISSUE THREAD

**Issue by Helaer** [Genymobile/scrcpy#3833]
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
C:\Program Files (x86)\Androidscreen\Resources\scrcpy-serv...file pushed, 0 skipped. 106.7 MB/s (52867 bytes in 0.000s)
[server] INFO: Device: Meizu MX6 (Android 7.1.1)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
        at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java:151)
        at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java:151)
        at com.android.server.NetworkManagementSocketTagger.getApplicationInfo(NetworkManagementSocketTagger.java:262)
        at com.android.server.NetworkManagementSocketTagger.getProcessInfo(NetworkManagementSocketTagger.java:292)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:139)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:47)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:288)
        at android.system.Os.socket(Os.java:491)
        at android.net.LocalSocketImpl.create(LocalSocketImpl.java:256)
        at android.net.LocalSocket.implCreateIfNeeded(LocalSocket.java:107)
        at android.net.LocalSocket.connect(LocalSocket.java:130)
        at com.genymobile.scrcpy.DesktopConnection.connect(DesktopConnection.java:50)
        at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:85)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:97)
        at com.genymobile.scrcpy.Server.main(Server.java:381)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:308)
ERROR: Server connection failed

**Comment by rom1v** [comment]
What is the value of `Build.BRAND`?

https://github.com/Genymobile/scrcpy/blob/45717733a10b8e73ae70b25722b2ddf5922c1c07/server/src/main/java/com/genymobile/scrcpy/Server.java#L84

**Comment by Helaer** [comment]
It works fine on scrcpy1.24.

**Comment by Helaer** [comment]
> 这个版本有效吗：[#3801（评论）](https://github.com/Genymobile/scrcpy/issues/3801#issuecomment-1468902114)？

Ok, I'll test it now.

**Comment by Helaer** [comment]
> 这个版本有效吗：[#3801（评论）](https://github.com/Genymobile/scrcpy/issues/3801#issuecomment-1468902114)？

It works fine. Would you consider releasing a fix?

**Comment by rom1v** [comment]
> It works fine.

That's very strange, this version is not supposed to fix a problem with Meizu devices :confused:

> Would you consider releasing a fix?

It will be in the next minor release, I don't know when (there is no rush).

**Comment by Helaer** [comment]
> And does this version work: [#3801 (comment)](https://github.com/Genymobile/scrcpy/issues/3801#issuecomment-1468902114) ?

Ok, scrcpy-server is big. Is that normal?

**Comment by rom1v** [comment]
127Kb is not big.

**Comment by rom1v** [comment]
Oh, it's because it has been build from my debug builddir (so with `gradle assembleDebug`) while the release is built in release mode (`gradle assembleRelease`).

**Comment by Helaer** [comment]
> 哦，这是因为它是从我的调试构建器构建的（所以使用 ），而版本是在发布模式下构建的（）。`gradle assembleDebug``gradle assembleRelease`

I see. Thank you.
