### ISSUE TITLE
Android 5.1.1 java.lang.IllegalStateException

### ISSUE THREAD

**Issue by MedievalSteel** [Genymobile/scrcpy#3888]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows Version 10.0.19045.2728 & Arch Linux
 - scrcpy version: v2.0 & v1.25 
 - installation method: unzip releases zip & pacman
 - device model: LGE LG-F260S
 - Android version: Android 5.1.1

**Describe the bug**
scrcpy -d --list-encoders
`````
[server] INFO: List of video encoders:
    --video-codec=h264 --video-encoder='OMX.qcom.video.encoder.avc'
[server] INFO: List of audio encoders:
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
`````
scrcpy -m800 -d --video-codec=h264 --video-encoder='OMX.qcom.video.encoder.avc' --no-audio
`````
scrcpy-server: 1 file pushed, 0 skipped. 43.8 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: LGE LG-F260S (Android 5.1.1)
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: newMaxSize = 0
INFO: Renderer: direct3d
INFO: Initial texture: 448x800
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1036)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:169)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:95)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:133)
        at com.genymobile.scrcpy.Server.main(Server.java:381)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
`````

**Comment by rom1v** [comment]
This is an encoder issue on the device.

**Comment by rom1v** [comment]
Does `screenrecord` work?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

**Comment by lucas093** [comment]
You can correct this error by specifying the maximum screen size as follows `scrcpy -m 1024`
