### ISSUE TITLE
after execute magisk resetprop ro.debuggable 1, scrcpy DisplayManager.getDisplayInfo failed

### ISSUE THREAD

**Issue by djerryz** [Genymobile/scrcpy#3890]
- [v ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [v ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:  Windows
 - scrcpy version:  2.0
 - installation method: Windows release
 - device model: OnePlus ONEPLUS A3000 (Android 9)
 - Android version: 9

**Describe the bug**
execute scrcpy.exe directly , everything is fine!
but after execute:
```
adb shell
su
magisk resetprop ro.debuggable 1
stop;start;
```
and then execute scrcpy.exe, it will get this error:
```
[server] INFO: Device: OnePlus ONEPLUS A3000 (Android 9)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:86)
        at com.genymobile.scrcpy.Device.<init>(Device.java:66)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
        at com.genymobile.scrcpy.Server.main(Server.java:381)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:384)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:72)
        ... 5 more
ERROR: Server connection failed
```

**Comment by djerryz** [comment]
Why i set `magisk resetprop ro.debuggable 1` , cause when i execute `adb root` , i get `adbd cannot run as root in production builds` , and i  find a solution, it tell me set `magisk resetprop ro.debuggable 1` will help, yes .
But the problem with this solution is that scrcpy cannot obtaining `dumpsys` information as mentioned above.
A solution that can solve both the problem of `adb root` being unable to execute and the problem of scrcpy obtaining `dumpsys` information: https://github.com/topjohnwu/Magisk/issues/425#issuecomment-1454987481
```
su

resetprop ro.debuggable 1
resetprop service.adb.root 1
magiskpolicy --live 'allow adbd adbd process setcurrent'
magiskpolicy --live 'allow adbd su process dyntransition'"
magiskpolicy --live 'permissive { su }'
kill -9 ps -A | grep adbd | awk '{print $2}' 

stop;start;
```
