### ISSUE TITLE
the audio doesn't work :(

### ISSUE THREAD

**Issue by EviLorD69** [Genymobile/scrcpy#3904]
mine passes the image perfectly but the audio gives this gigantic error there, does anyone know how to fix it? using the old sndcpy I can pass the normal audio, but I wanted to use only scrcpy 2.0... 

C:\Users\Administrator\Desktop\New folder (5)\scrcpy-win64-v2.0>scrcpy --video-codec=h264 -b 20m --max-fps=120
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
C:\Users\Administrator\Desktop\New Folder (5)\scrcpy-win64... file pushed, 0 skipped. 83.8 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: vivo V2231A (Android 13)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
WARN: Demuxer 'audio': stream explicitly disabled by the device
[server] ERROR: Exception on thread Thread[Thread-4,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getOpPackageName()' on a null object reference
         at android.media.VivoAudioRecordImpl.isSupportSubMixRecording(VivoAudioRecordImpl.java:133)
         at android.media.AudioRecord.<init>(AudioRecord.java:493)
         at android.media.AudioRecord.<init>(Unknown Source:0)
         at android.media.AudioRecord$Builder.build(AudioRecord.java:999)
         at com.genymobile.scrcpy.AudioCapture.createAudioRecord(AudioCapture.java:58)
         at com.genymobile.scrcpy.AudioCapture.start(AudioCapture.java:90)
         at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:183)
         at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:120)
         at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda0.run(Unknown Source:2)
         at java.lang.Thread.run(Thread.java:1015)

**Comment by rom1v** [comment]
This is specific to Vivo phones. See #3805 #3862.
