### ISSUE TITLE
Keyboard and mouse control do not work even with USB debugging (Security Settings) turned on.

### ISSUE THREAD

**Issue by Makuu001** [Genymobile/scrcpy#3905]
- [Y] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [M] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows]
 - scrcpy version: [2.0]
 - installation method: [Windows release]
 - device model: POCO F3
 - Android version: [13]

Controlling with mouse and keyboard does not work even though I enabled the USB debugging (Security Settings), I already tried revoking authorizations but to no avail.

```
`[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:196)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:320)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:134)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:90)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Unknown Source:7)
        at android.os.Parcel.createException(Unknown Source:0)
        at android.os.Parcel.readException(Unknown Source:11)
        at android.os.Parcel.readException(Unknown Source:10)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(Unknown Source:31)
        at android.hardware.input.InputManager.injectInputEvent(Unknown Source:21)
        at android.hardware.input.InputManager.injectInputEvent(Unknown Source:1)`
```
![Screenshot_2023-04-10-00-51-53-549_com android settings](https://user-images.githubusercontent.com/130305567/230785724-6632a577-ed6b-4d5c-bee0-19fc7e712f88.jpg)

**Comment by rom1v** [comment]
Did you reboot your device after enabling security settings?

**Comment by Makuu001** [comment]
> Did you reboot your device after enabling security settings?

didnt reboot it but it works now!
