### ISSUE TITLE
Screen streaming stopped

### ISSUE THREAD

**Issue by nfh994** [Genymobile/scrcpy#3912]
This is a question about how to use the server.
I execute commands through cmd:
adb push scrcpy-server /data/local/tmp/
adb shell CLASSPATH=/data/local/tmp/scrcpy-server app_process / com.genymobile.scrcpy.Server 2.0
The result obtained is:
[server] INFO: Device: samsung SM-G977N (Android 12)
[server] DEBUG: Screen streaming stopped
[server] ERROR: Exception on thread Thread[main,5,main]
java.io.IOException: Connection refused
        at android.net.LocalSocketImpl.connectLocal(Native Method)
        at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:259)
        at android.net.LocalSocket.connect(LocalSocket.java:148)
        at com.genymobile.scrcpy.DesktopConnection.connect(DesktopConnection.java:50)
        at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:85)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:97)
        at com.genymobile.scrcpy.Server.main(Server.java:381)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:378)

What should I do to manually start the server?
I'm sorry, this is a foolish question. I didn't see the relevant content in the document

**Comment by rom1v** [comment]
Did you call `adb forward` or `adb reverse`?

Check https://code.videolan.org/rom1v/vlc/-/merge_requests/20 for an example (based on scrcpy 1.25).

**Comment by nfh994** [comment]
I understand. I need a tunnel_ Forward is true, test 1.25 is valid, but 2.0 is not. Thank you

**Comment by unofficialdev** [comment]
> Did you call `adb forward` or `adb reverse`?
> 
> Check https://code.videolan.org/rom1v/vlc/-/merge_requests/20 for an example (based on scrcpy 1.25).

I'm having the same problem
