### ISSUE TITLE
Demuxer 'audio': stream explicitly disabled by the device

### ISSUE THREAD

**Issue by hannesa2** [Genymobile/scrcpy#3934]
When I start scrcpy all works fine, expect audio

```
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
/opt/homebrew/Cellar/scrcpy/2.0/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 36.1 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: idc23 for arm64 (Android 12)
INFO: Renderer: metal
INFO: Initial texture: 1920x960
WARN: Demuxer 'audio': stream explicitly disabled by the device
[server] ERROR: Exception on thread Thread[Thread-4,5,main]
java.lang.UnsupportedOperationException: Cannot create AudioRecord
	at android.media.AudioRecord$Builder.build(AudioRecord.java:913)
	at com.genymobile.scrcpy.AudioCapture.createAudioRecord(AudioCapture.java:58)
	at com.genymobile.scrcpy.AudioCapture.start(AudioCapture.java:90)
	at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:183)
	at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:120)
	at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:920)
	WARN: Killing the server...
```

`Demuxer 'audio': stream explicitly disabled by the device` does someone knows how to enable it. It's an own build of AOSP

Btw, thank you for this cool tool !

**Comment by rom1v** [comment]
[AudioRecord.Builder.build()`](https://github.com/Genymobile/scrcpy/blob/8f0b38cc4f503ea16dd57c705ae0ede81efc8630/server/src/main/java/com/genymobile/scrcpy/AudioCapture.java#L42) throws an `UnsupportedOperationException`.

It is expected on Android 11 when the shell application is not foreground when you start, but not on Android 12.

Just in case, unlock your device, execute:

```
adb shell am start -n com.android.shell/.HeapDumpActivity
```

It should open a popup. While the popup is visible, start scrcpy. Does it solve the problem?

**Comment by hannesa2** [comment]
I see this dialog
<img width="743" alt="image" src="https://user-images.githubusercontent.com/3314607/233396618-d63fbb3f-044d-4c50-9557-5f1efbb79333.png">

means "_**Share heap dump?**
The memory limit of 0.00 was exceeded for the process "null". A heap dump is available to share with the developer. However, it is important to note that the heap dump may contain personal information about you that the app can access_."

Unfortunately , `scrcpy` still shows the same error

```
[server] ERROR: Exception on thread Thread[Thread-4,5,main]
java.lang.UnsupportedOperationException: Cannot create AudioRecord
	at android.media.AudioRecord$Builder.build(AudioRecord.java:913)
	at com.genymobile.scrcpy.AudioCapture.createAudioRecord(AudioCapture.java:58)
	at com.genymobile.scrcpy.AudioCapture.start(AudioCapture.java:90)
	at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:183)
	at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:120)
	at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:920)
INFO: Renderer: metal
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Initial texture: 1920x960
```

**Comment by rom1v** [comment]
> [UnsupportedOperationException](https://developer.android.com/reference/java/lang/UnsupportedOperationException) 	if the parameters set on the Builder were incompatible, if the parameters are not supported by the device, if the caller does not hold the appropriate permissions, or if the device was not available.

https://developer.android.com/reference/android/media/AudioRecord.Builder#build()

**Comment by hyunkwak** [comment]
Hello @hannesa2, I am experiencing the same issue with my own build of AOSP and I was wondering if you managed to resolve it in the end? Thanks 🙂

**Comment by hannesa2** [comment]
Sorry, no
