### ISSUE TITLE
Scrcpy does not work on F1 VM

### ISSUE THREAD

**Issue by Galaxy0Gamer** [Genymobile/scrcpy#3952]
**Environment**
 - OS: windows
 - scrcpy version: 2.0
 - installation method: Windows release
 - Android version: 7.1.0

**bug description**
it simply does not work on my F1 VM app, basically emulating android on android, but it works on other multiple normal phones i have, his bug occurs only on F1 VM.

> C:\Users\galax\OneDrive\Desktop\ScreenCpy\scrcpy-server: 1 file pushed, 0 skipped. 1.4 MB/s (52867 bytes in 0.037s)
> [server] INFO: Device: Google Pixel XL (Android 7.1.2)
> [server] WARN: Audio disabled: it is not supported before Android 11
> [server] ERROR: Encoding error: java.lang.IllegalStateException: null
> [server] INFO: newMaxSize = 1920
> [server] INFO: Retrying with -m1920...
> [server] INFO: Retrying...
> INFO: Renderer: direct3d
> WARN: Demuxer 'audio': stream explicitly disabled by the device
> INFO: Initial texture: 1080x2312
> [server] INFO: newMaxSize = 1600
> [server] ERROR: Encoding error: java.lang.IllegalStateException: null
> [server] INFO: Retrying with -m1600...
> [server] INFO: Retrying...
> [server] ERROR: Exception on thread Thread[main,10,main]
> android.media.MediaCodec$CodecException: Error 0x80000000
> WARN: Device disconnected
>         at android.media.MediaCodec.native_reset(Native Method)
>         at android.media.MediaCodec.reset(MediaCodec.java:1796)
>         at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:106)
>         at com.genymobile.scrcpy.Server.scrcpy(Server.java:133)
>         at com.genymobile.scrcpy.Server.main(Server.java:381)
>         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
>         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
> 

and there is another one, this happens when i first boot F1 VM, the second time i try i get:

> C:\Users\galax\OneDrive\Desktop\ScreenCpy\scrcpy-server: 1 file pushed, 0 skipped. 10.7 MB/s (52867 bytes in 0.005s)
> Bad system call
> ERROR: Server connection failed

I disconnect and reconnect and I get the same first error

yea I'm sorry I don't know how to make special squares where I put code

**Comment by rom1v** [comment]
Because there is no hardware encoder? (check `scrcpy --list-encoders`)

**Comment by Galaxy0Gamer** [comment]
I get "Bad System Call" @rom1v
