### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by adamxss** [Genymobile/scrcpy#3965]
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
D:\scrcpy-win64-v2.0\scrcpy-win64-v2.0\scrcpy-server: 1 file pushed, 0 skipped. 27.7 MB/s (52867 bytes in 0.002s)
[server] INFO: Device: OnePlus IN2023 (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
[server] INFO: newMaxSize = 1920
[server] INFO: Retrying with -m1920...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: newMaxSize = 1600
[server] INFO: Retrying with -m1600...
[server] INFO: Retrying...
[server] INFO: newMaxSize = 1280
[server] INFO: Retrying with -m1280...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: newMaxSize = 1024
[server] INFO: Retrying with -m1024...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: newMaxSize = 800
[server] INFO: Retrying with -m800...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: newMaxSize = 0
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:169)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:95)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:133)
        at com.genymobile.scrcpy.Server.main(Server.java:381)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:357)
WARN: Killing the server...

**Comment by rom1v** [comment]
Does `adb shell screenrecord /sdcard/file.mp4` work?

**Comment by innocentvoice** [comment]
> Does `adb shell screenrecord /sdcard/file.mp4` work?

I got the same problem with this people, and the adb shell screenrecord command works for me.

**Comment by rom1v** [comment]
You could try with another encoder (check `scrcpy --list-encoders`).

**Comment by adamxss** [comment]
> Does `adb shell screenrecord /sdcard/file.mp4` work?

it says encoder failed (err=-38) when try this

**Comment by innocentvoice** [comment]
> You could try with another encoder (check `scrcpy --list-encoders`).

![image](https://user-images.githubusercontent.com/81401361/236677695-030fa4b9-34b4-423f-b83e-533b67e7cc98.png)

**Comment by rom1v** [comment]
```
scrcpy --version
```

?

https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#codec

**Comment by adamxss** [comment]
> > You could try with another encoder (check `scrcpy --list-encoders`).
> 
> ![image](https://user-images.githubusercontent.com/81401361/236677695-030fa4b9-34b4-423f-b83e-533b67e7cc98.png)

how do i change the encoder? please teach me, thanks.

**Comment by rom1v** [comment]
You need scrcpy 2.0 to call `--list-encoders`.

**Comment by innocentvoice** [comment]
> ```
> scrcpy --version
> ```
> 
> ?
> 
> `--list-encoders` was added in scrcpy 2.0.
> 
> https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#codec

Oh, my mistake, the scrcpy in the apt is only 1.7, that's why it's not working for a12. Now it's working!

**Comment by adamxss** [comment]
> You need scrcpy 2.0 to call `--list-encoders`.

still not working, been trying scrcpy --<other-encoder> (just example).

**Comment by adamxss** [comment]
> > ```
> > scrcpy --version
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ?
> > `--list-encoders` was added in scrcpy 2.0.
> > https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#codec
> 
> Oh, my mistake, the scrcpy in the apt is only 1.7, that's why it's not working for a12. Now it's working!

how? im on A12 too, please tell me. thanks.

**Comment by innocentvoice** [comment]
> > > ```
> > > scrcpy --version
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ?
> > > `--list-encoders` was added in scrcpy 2.0.
> > > https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#codec
> > 
> > 
> > Oh, my mistake, the scrcpy in the apt is only 1.7, that's why it's not working for a12. Now it's working!
> 
> how? im on A12 too, please tell me. thanks.

Oh are you using linux? If yes just upgrade your scrcpy to 2.0!

**Comment by innocentvoice** [comment]
> > > ```
> > > scrcpy --version
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ?
> > > `--list-encoders` was added in scrcpy 2.0.
> > > https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#codec
> > 
> > 
> > Oh, my mistake, the scrcpy in the apt is only 1.7, that's why it's not working for a12. Now it's working!
> 
> how? im on A12 too, please tell me. thanks.

Oh are you using linux? If yes just upgrade your scrcpy to 2.0!
