### ISSUE TITLE
android.media.MediaCodec$CodecException: Error 0xfffffc0e

### ISSUE THREAD

**Issue by cuishao23** [Genymobile/scrcpy#3973]
我使用咱们的scrcpy-server 1.2，然后自己用python写了个client，抛出下面异常，我尝试Just try with a lower definition，还是不行,我的环境是window，手机是谷歌Pixel 2，android11

 
Found h264 decoder
Could not open video stream
ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
at android.media.MediaCodec.native_configure(Native Method)
at android.media.MediaCodec.configure(MediaCodec.java:2127)
at android.media.MediaCodec.configure(MediaCodec.java:2043)
at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:158)
at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:68)
at com.genymobile.scrcpy.Server.scrcpy(Server.java:28)
at com.genymobile.scrcpy.Server.main(Server.java:110)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399

**Comment by rom1v** [comment]
Does it work with scrcpy 2.0?

**Comment by cuishao23** [comment]
我把bit_rate降低，解决了这个问题
