### ISSUE TITLE
Mouse clicks are not getting forwarded and when I click it shows console error pasted below

### ISSUE THREAD

**Issue by iMansoorAliKhan** [Genymobile/scrcpy#3975]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...] windows 10 Pro 21h2 19044
 - scrcpy version: 2.0
 - installation method: was working 2 day before this and now its not
 - device model:  Xiaomi M2101K6G (Android 13)
 - Android version: 13

**Describe the bug**
Now mouse clicks are not gettin forwarded: I read FAQ and tried the settings to enable to extra option but I dont see that in my adnroid version

05-06 09:34:39.962  1787  3857 D CoreBackPreview: Window{8df0735 u0 com.twitter.android/com.twitter.app.main.MainActivity}: Setting back callback null
05-06 09:34:39.979  1787  6479 D WindowManager: wms.Input focus has changed to Window{ce5e7ed u0 com.twitter.android/com.twitter.app.main.MainActivity} display=0 updateInputWindows = true
05-06 09:34:40.019  1787  1787 W DevicePolicyManager: Unknown user type: UserInfo{999:XSpace:801010}
05-06 09:34:40.019  1787  1787 W DevicePolicyManager: Unknown user type: UserInfo{999:XSpace:801010}
05-06 09:34:40.020  1787  1787 W NotificationManagerServiceImpl: checkInterceptListenerForXiaomiInternal pkg:com.android.mtplistener:com.android.systemui/com.android.systemui.statusbar.notification.MiuiNotificationListener
05-06 09:34:40.020  1787  1787 D NotificationListeners: is mask intercept: com.android.systemui notification packagename: com.android.mtp
05-06 09:34:40.049 26818 26818 W Activity: PerfMonitor: Slow Operation: Activity com.twitter.android/com.twitter.app.main.MainActivity onDestroy took 110ms
05-06 09:34:40.050  1787  5578 D CoreBackPreview: Window{ce5e7ed u0 com.twitter.android/com.twitter.app.main.MainActivity}: Setting back callback null
05-06 09:34:40.063  1787  3857 D WindowManager: wms.Input focus has changed to null display=0 updateInputWindows = true
05-06 09:34:40.075  1787  2843 I SmartPower.com.google.android.inputmethod.latin/10200(5059): background->idle(3001ms) R(broadcast start Intent { act=android.intent.action.SCREEN_ON flg=0x50200010 }) adj=100.
05-06 09:34:40.075  1787  2843 I SmartPower: com.google.android.inputmethod.latin/10200 state=inactive adj=100 proc size=1 move to idle broadcast start Intent { act=android.intent.action.SCREEN_ON flg=0x50200010 }
05-06 09:34:40.156  1787  3857 D ActivityTaskManager:  setRequestedOrientationFreeForm: requestedOrientation= -1 task=Task{f910d79 #5966 type=standard A=10465:com.twitter.android U=0 visible=true visibleRequested=true mode=fullscreen translucent=false sz=1} MiuiFreeformServicesUtils.getFreeformIgnoreRequestOrientationList()= [com.miui.player, com.sqw.setdl.mi, air.tv.douyu.android, com.youku.phone, com.tencent.gamehelper.smoba, com.taobao.litetao, com.live.shuoqiudi, com.baidu.homework, com.tencent.qqmusic, cn.xiaochuankeji.zuiyouLite, com.facebook.orca, com.android.browser, com.alibaba.android.rimet]packageName= com.twitter.android
05-06 09:34:40.167  1787  2843 I SmartPower.com.miui.analytics/99910115(17652): background->idle(3000ms) R(broadcast start Intent { act=android.intent.action.SCREEN_ON flg=0x50200010 }) adj=925.
05-06 09:34:40.168  1787  2843 I SmartPower: com.miui.analytics/99910115 state=inactive adj=925 proc size=1 move to idle broadcast start Intent { act=android.intent.action.SCREEN_ON flg=0x50200010 }
05-06 09:34:40.228  1787  2843 I SmartPower.com.android.camera/10112(18310): background->idle(3003ms) R(broadcast start Intent { act=android.intent.action.SCREEN_ON flg=0x50200010 }) adj=925.
05-06 09:34:40.228  1787  2843 I SmartPower: com.android.camera/10112 state=inactive adj=925 proc size=1 move to idle broadcast start Intent { act=android.intent.action.SCREEN_ON flg=0x50200010 }
05-06 09:34:40.397 26818 26818 I ForceDarkHelperStubImpl: setViewRootImplForceDark: false for com.twitter.app.main.MainActivity@3ec1977, reason: DarkModeEnabled
05-06 09:34:40.402  1787  3857 D WindowManager: wms.Input focus has changed to Window{8e567bb u0 com.twitter.android/com.twitter.app.main.MainActivity} display=0 updateInputWindows = false
05-06 09:34:40.406 26818 26818 W Activity: PerfMonitor: Slow Operation: Activity com.twitter.android/com.twitter.app.main.MainActivity onStart took 275ms
05-06 09:34:40.407  1787  2139 D WindowManager: wms.Focus not requested for window=Window{8e567bb u0 com.twitter.android/com.twitter.app.main.MainActivity} because it has no surface or is not focusable.
05-06 09:34:40.407  1787  3857 D CoreBackPreview: Window{8e567bb u0 com.twitter.android/com.twitter.app.main.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@478c497, mPriority=0}
05-06 09:34:40.422 26818 26818 I ForceDarkHelperStubImpl: setViewRootImplForceDark: false for com.twitter.app.main.MainActivity@3ec1977, reason: DarkModeEnabled
05-06 09:34:40.426  1787  2139 D WindowManager: wms.Focus not requested for window=Window{8e567bb u0 com.twitter.android/com.twitter.app.main.MainActivity} because it has no surface or is not focusable.
05-06 09:34:40.428  1787  3857 D CoreBackPreview: Window{5358e6d u0 com.twitter.android/com.twitter.app.main.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@97b1333, mPriority=0}
05-06 09:34:40.447  1787  2139 D WindowManager: wms.Update InputWindowHandle: 8e567bb com.twitter.android/com.twitter.app.main.MainActivity, frame=[0,0,0,0], touchableRegion=SkRegion((0,-93,1080,2307)), scaleFactor=1.0, transform=null, windowToken=android.os.BinderProxy@5553c4a, isClone=false, visibal=true, focusable=true, changed=true
05-06 09:34:40.448 26818 26818 I ForceDarkHelperStubImpl: setViewRootImplForceDark: false for com.twitter.app.main.MainActivity@3ec1977, reason: DarkModeEnabled
05-06 09:34:40.519  1787  3857 D ActivityTaskManager:  setRequestedOrientationFreeForm: requestedOrientation= -1 task=Task{f910d79 #5966 type=standard A=10465:com.twitter.android U=0 visible=true visibleRequested=true mode=fullscreen translucent=false sz=1} MiuiFreeformServicesUtils.getFreeformIgnoreRequestOrientationList()= [com.miui.player, com.sqw.setdl.mi, air.tv.douyu.android, com.youku.phone, com.tencent.gamehelper.smoba, com.taobao.litetao, com.live.shuoqiudi, com.baidu.homework, com.tencent.qqmusic, cn.xiaochuankeji.zuiyouLite, com.facebook.orca, com.android.browser, com.alibaba.android.rimet]packageName= com.twitter.android
05-06 09:34:40.610  1787  3857 I WindowManager: finishDrawing of relaunch: Window{5358e6d u0 com.twitter.android/com.twitter.app.main.MainActivity} 1391ms
05-06 09:34:40.610  1787  3857 D WindowManager: wms.finishDrawingLocked: mDrawState=COMMIT_DRAW_PENDING Window{5358e6d u0 com.twitter.android/com.twitter.app.main.MainActivity} in Surface(name=com.twitter.android/com.twitter.app.main.MainActivity)/@0xd092eee
05-06 09:34:40.610  1787  3857 D MiuiFreeFormGesturePointerEventListener: finishDrawingWindow: topFullScreenWindow= Window{5358e6d u0 com.twitter.android/com.twitter.app.main.MainActivity}
05-06 09:34:40.615  1787  5578 D WindowManager: wms.finishDrawingLocked: mDrawState=COMMIT_DRAW_PENDING Window{8e567bb u0 com.twitter.android/com.twitter.app.main.MainActivity} in Surface(name=com.twitter.android/com.twitter.app.main.MainActivity)/@0x349af8f
05-06 09:34:40.622  1787  2139 I WindowManager: wms.showSurfaceRobustly mWin:Window{5358e6d u0 com.twitter.android/com.twitter.app.main.MainActivity}
05-06 09:34:40.627  1787  2139 I WindowManager: wms.showSurfaceRobustly mWin:Window{8e567bb u0 com.twitter.android/com.twitter.app.main.MainActivity}
05-06 09:34:40.636  1787  2139 I WindowManager: Screen frozen for +1s474ms due to Window{8e567bb u0 com.twitter.android/com.twitter.app.main.MainActivity}
05-06 09:34:40.679  1787  2139 D MiuiFreeFormSwitchAppHelper: startSwitchAppFourStep mSwitchingApp=false
05-06 09:34:40.751  1787  3857 D ActivityTaskManager:  setRequestedOrientationFreeForm: requestedOrientation= -1 task=Task{f910d79 #5966 type=standard A=10465:com.twitter.android U=0 visible=true visibleRequested=true mode=fullscreen translucent=false sz=1} MiuiFreeformServicesUtils.getFreeformIgnoreRequestOrientationList()= [com.miui.player, com.sqw.setdl.mi, air.tv.douyu.android, com.youku.phone, com.tencent.gamehelper.smoba, com.taobao.litetao, com.live.shuoqiudi, com.baidu.homework, com.tencent.qqmusic, cn.xiaochuankeji.zuiyouLite, com.facebook.orca, com.android.browser, com.alibaba.android.rimet]packageName= com.twitter.android
05-06 09:34:40.752  1787  6479 D CompatibilityChangeReporter: Compat change id reported: 149924527; UID 10088; state: ENABLED
05-06 09:34:40.754  1787  3461 D CompatibilityChangeReporter: Compat change id reported: 132649864; UID 10088; state: DISABLED
05-06 09:34:40.760  1787  6479 D CompatibilityChangeReporter: Compat change id reported: 151105954; UID 10191; state: ENABLED
05-06 09:34:40.760  1787  6479 E AppOps  : attributionTag location_history not declared in manifest of com.google.android.gms.location.history
05-06 09:34:40.761  1787  6479 E AppOps  : attributionTag location_history not declared in manifest of com.google.android.gms.location.history
05-06 09:34:40.761  1787  6479 W AppOps  : Noting op not finished: uid 10193 pkg com.google.android.gms.location.history code 79 startTime of in progress event=1683283772051
05-06 09:34:40.871  1787  3461 D PackageManager: set app  component=ComponentInfo{com.twitter.android/androidx.work.impl.background.systemalarm.RescheduleReceiver} enabled state: 1 from null,uid=10465,pid=26818
05-06 09:34:40.906  1787  2411 D DualSensorPolicy: updateDualSensorPolicy: update ambient lux using main light sensor, mMainFastAmbientLux: 44.170437, mMainSlowAmbientLux: 32.50509, mainBrighteningThreshold: 23.917553, mainDarkeningThreshold: 6.958777
05-06 09:34:40.906  1787  2411 D AutomaticBrightnessController: setAmbientLux: handle main light sensor event, needUpdateLux: true, needUpdateBrightness: true, needSuppressDarkening: false, mAmbientLux: 44.170437, mPreThresholdLux: 13.917554
05-06 09:34:40.906  1787  2411 I AutomaticBrightnessController: updateAutoBrightness: mScreenAutoBrightness=0.1612865, newScreenAutoBrightness=0.18033583 (checkedAutoBrightness=370), mAmbientLux=44.170437, mUseDaemonSensorInProgress=false
05-06 09:34:40.906  1787  2411 D DualSensorPolicy: updateDualSensorPolicy: next brightening threshold of main light sensor: 74.17044, next darkening threshold of main light sensor: 22.085218
05-06 09:34:40.906  1787  2411 D DisplayPowerControllerImpl: updateBrightnessChangeStatus: animating: true, displayState: 2, slowChange: true, appliedDimming: false, appliedLowPower: false, currentBrightness: 0.15867001, currentSdrBrightness: 0.15864214, targetBrightness: 0.18033583, targetSdrBrightness: 0.18033583
05-06 09:34:40.906  1787  2411 I DisplayPowerControllerImpl: Animating brightness rate: 0.23228346, outRate: 0.23228346, reason: no_changed
05-06 09:34:40.907  1787  2411 I DisplayPowerController[0]: BrightnessEvent: disp=0, brt=0.18033583, rcmdBrt=0.18033583, preBrt=0.1612865, lux=44.170437, preLux=13.917554, hbmMax=1.0, hbmMode=off, thrmMax=1.0, flags=, reason=automatic
05-06 09:34:40.907  1787  2411 D DisplayPowerControllerImpl: updateBrightnessChangeStatus: animating: true, displayState: 2, slowChange: true, appliedDimming: false, appliedLowPower: false, currentBrightness: 0.15867001, currentSdrBrightness: 0.15864214, targetBrightness: 0.18033583, targetSdrBrightness: 0.18033583
05-06 09:34:40.907  1787  2411 I DisplayPowerControllerImpl: Animating brightness rate: 0.23228346, outRate: 0.23228346, reason: no_changed
05-06 09:34:40.911  1787  1787 I BrightnessSynchronizer: [969] New Update 0.18033583(f) set brightness values:  47(i)
05-06 09:34:40.911  1787  1787 I BrightnessSynchronizer: New PendingUpdate: {[970] 0.18033583(f), mUpdatedTypes=0, mConfirmedTypes=0, mTimeUpdated=0}, prev=null
05-06 09:34:40.914  1787  1787 W SettingsProvider: Failed to notify for 999: content://settings/system/screen_brightness
05-06 09:34:40.914  1787  1787 W SettingsProvider: java.lang.SecurityException: Failed to find provider settings for user 999; expected to find a valid ContentProvider for this authority
05-06 09:34:40.914  1787  1787 W SettingsProvider:      at com.android.server.content.ContentService.notifyChange(ContentService.java:451)
05-06 09:34:40.914  1787  1787 W SettingsProvider:      at android.content.ContentResolver.notifyChange(ContentResolver.java:2916)
05-06 09:34:40.914  1787  1787 W SettingsProvider:      at android.content.ContentResolver.notifyChange(ContentResolver.java:2905)
05-06 09:34:40.914  1787  1787 W SettingsProvider:      at android.content.ContentResolver.notifyChange(ContentResolver.java:2899)
05-06 09:34:40.914  1787  1787 W SettingsProvider:      at com.android.providers.settings.SettingsProvider$SettingsRegistry$MyHandler.handleMessage(SettingsProvider.java:3717)
05-06 09:34:40.914  1787  1787 W SettingsProvider:      at android.os.Handler.dispatchMessage(Handler.java:106)
05-06 09:34:40.914  1787  1787 W SettingsProvider:      at android.os.Looper.loopOnce(Looper.java:211)
05-06 09:34:40.914  1787  1787 W SettingsProvider:      at android.os.Looper.loop(Looper.java:300)
05-06 09:34:40.914  1787  1787 W SettingsProvider:      at com.android.server.SystemServer.run(SystemServer.java:1030)
05-06 09:34:40.914  1787  1787 W SettingsProvider:      at com.android.server.SystemServer.main(SystemServer.java:708)
05-06 09:34:40.914  1787  1787 W SettingsProvider:      at java.lang.reflect.Method.invoke(Native Method)
05-06 09:34:40.914  1787  1787 W SettingsProvider:      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
05-06 09:34:40.914  1787  1787 W SettingsProvider:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
05-06 09:34:40.915  1787  1787 I BrightnessSynchronizer: Swallowing update of 47(i) by update: {[969] 0.18033583(f), mUpdatedTypes=1, mConfirmedTypes=1, mTimeUpdated=39289277}
05-06 09:34:40.915  1787  1787 I BrightnessSynchronizer: Completed Update: {[969] 0.18033583(f), mUpdatedTypes=1, mConfirmedTypes=1, mTimeUpdated=39289277}
05-06 09:34:41.049  3504  3504 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1960 android.content.ContextWrapper.bindService:863 com.miui.miplay.audio.a.g.a:58 com.miui.miplay.audio.a.g.o:1 com.miui.miplay.audio.a.g.c:7
05-06 09:34:41.051  1787  3857 W ActivityManager: Unable to start service Intent { pkg=com.milink.service cmp=com.milink.service/com.miui.miplay.audio.service.CoreService (has extras) } U=0: not found
05-06 09:34:41.075  1787  6479 D WindowManager: wms.Input focus has changed to Window{44df985 u0 control_center} display=0 updateInputWindows = true
05-06 09:34:41.080  1787  2139 D WindowManager: wms.Update InputWindowHandle: 44df985 control_center, frame=[0,0,0,0], touchableRegion=SkRegion((0,0,1080,2400)), scaleFactor=1.0, transform=null, windowToken=android.os.BinderProxy@4a083ef, isClone=false, visibal=true, focusable=true, changed=true
05-06 09:34:41.099  1787  1787 W AccessibilityManagerService:  wait for adding window timeout: 914
05-06 09:34:41.102  1787  6198 D WindowManager: wms.finishDrawingLocked: mDrawState=COMMIT_DRAW_PENDING Window{44df985 u0 control_center} in Surface(name=control_center)/@0x60e0726
05-06 09:34:41.109  1787  2139 I WindowManager: wms.showSurfaceRobustly mWin:Window{44df985 u0 control_center}
05-06 09:34:41.121  1787  6198 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10318; state: DISABLED
05-06 09:34:41.121  1787  6198 D CompatibilityChangeReporter: Compat change id reported: 177438394; UID 10318; state: DISABLED
05-06 09:34:41.125  1787  6198 D CompatibilityChangeReporter: Compat change id reported: 135772972; UID 10318; state: DISABLED
05-06 09:34:41.126  1787  6198 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10318; state: ENABLED
05-06 09:34:41.126  1787  2230 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10318; state: ENABLED
05-06 09:34:41.184  1787  5578 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10135; state: DISABLED
05-06 09:34:41.184  1787  5578 D CompatibilityChangeReporter: Compat change id reported: 177438394; UID 10135; state: DISABLED
05-06 09:34:41.186  1787  5578 D CompatibilityChangeReporter: Compat change id reported: 135772972; UID 10135; state: DISABLED
05-06 09:34:41.186  1787  5578 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10135; state: ENABLED
05-06 09:34:41.198  1787  2230 D Boost   : hostingType=service, hostingName={videoeditor.videorecorder.screenrecorder/com.inshot.screenrecorder.services.QuickScreenRecordSettingService}, callerPackage=com.android.systemui, isSystem=true, isBoostNeeded=false.
05-06 09:34:41.198  1787  2230 W ActivityManager: Slow operation: 77ms so far, now at startProcess: returned from zygote!
05-06 09:34:41.198  1787  2230 W ActivityManager: Slow operation: 77ms so far, now at startProcess: done updating battery stats
05-06 09:34:41.201  1787  2230 W ActivityManager: Slow operation: 80ms so far, now at startProcess: building log message
05-06 09:34:41.204  1787  2230 I ActivityManager: Start proc 20467:videoeditor.videorecorder.screenrecorder/u0a318 for service {videoeditor.videorecorder.screenrecorder/com.inshot.screenrecorder.services.QuickScreenRecordSettingService} caller=com.android.systemui
05-06 09:34:41.204  1787  2230 W ActivityManager: Slow operation: 83ms so far, now at startProcess: starting to update pids map
05-06 09:34:41.207  1787  2230 W ActivityManager: Slow operation: 86ms so far, now at startProcess: done updating pids map
05-06 09:34:41.207  1787  2230 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10135; state: ENABLED
05-06 09:34:41.252  1787  2230 D Boost   : hostingType=service, hostingName={com.milink.service/com.milink.ui.service.MiLinkTileService}, callerPackage=com.android.systemui, isSystem=true, isBoostNeeded=false.
05-06 09:34:41.252  1787  2230 W ActivityManager: Slow operation: 70ms so far, now at startProcess: returned from zygote!
05-06 09:34:41.252  1787  2230 W ActivityManager: Slow operation: 70ms so far, now at startProcess: done updating battery stats
05-06 09:34:41.257  1787  2230 W ActivityManager: Slow operation: 75ms so far, now at startProcess: building log message
^C

```
[server] INFO: Device: Xiaomi M2101K6G (Android 13)
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
        at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:203)
        at com.genymobile.scrcpy.Device.pressReleaseKeycode(Device.java:211)
        at com.genymobile.scrcpy.Device.pressReleaseKeycode(Device.java:216)
        at com.genymobile.scrcpy.Controller.control(Controller.java:70)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:90)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 10 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:916)
        at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:617)
        at android.os.Binder.execTransactInternal(Binder.java:1285)
        at android.os.Binder.execTransact(Binder.java:1249)

INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:196)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:320)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:134)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:90)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 10 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:916)
        at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:617)
        at android.os.Binder.execTransactInternal(Binder.java:1285)
        at android.os.Binder.execTransact(Binder.java:1249)

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:196)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:320)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:134)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:90)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 10 more
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Is `USB debugging (Security Settings)` enabled? (you must reboot after enabling this option): https://github.com/Genymobile/scrcpy#prerequisites

**Comment by toby-developer** [comment]
Hey!
I have the same issue. I ensured USB debugging was enabled and rebooted my smartphone.
This is the output I got when I clicked once on the screen that was displaying.
Device: [Xiaomi] POCO 2201116PG (Android 13)
App version: scrcpy 2.1.1.

```

scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)          17b9082eaff2            device  2201116PG
C:\Users\Toby\Documents\scrcpy-win64-v2.1.1\scrcpy-win64-v... file pushed, 0 skipped. 56.0 MB/s (56995 bytes in 0.001s)
[server] INFO: Device: [Xiaomi] POCO 2201116PG (Android 13)
INFO: Renderer: direct3d
INFO: Texture: 1080x2400
[server] ERROR: Encoding error: java.lang.IllegalArgumentException: null
[server] INFO: Retrying with -m1920...
[server] INFO: Retrying...
INFO: Texture: 864x1920
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:225)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:229)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:324)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:138)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 10 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:912)
        at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:617)
        at android.os.Binder.execTransactInternal(Binder.java:1285)
        at android.os.Binder.execTransact(Binder.java:1249)

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:225)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:229)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:324)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:138)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 10 more

```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work
