### ISSUE TITLE
Java InvocationTargetException

### ISSUE THREAD

**Issue by robertosw** [Genymobile/scrcpy#3991]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).
 Only found #1788, which did not help.

**Environment**
 - OS: Ubuntu
 - scrcpy version: 1.12.1
 - installation method: apt
 - device model: Samsung S21 Ultra
 - Android version: 13

**Describe the bug**
I dont even know.. Terminal output below:
```
user@pcname:~$ scrcpy
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 0.8 MB/s (24773 bytes in 0.028s)
INFO: Initial texture: 1080x2400
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:178)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:70)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:378)
Caused by: java.lang.reflect.InvocationTargetException
```
On the same device, same cable, same usb port, `adb devices` and `adb shell` works perfectly without ever disconnecting.

Logcat:
```
--------- beginning of main
05-11 16:15:47.451  1404  3400 D SemWifiUsabilityStatsMonitor: onWifiUsabilityStats - seqNum 706, isSameBssidAndFreq true
05-11 16:15:47.451  1404  1768 I SemWifiLinkQualityMonitor: Link Qos Query: 0,074 ms / 107,752 Mbps (130 / 0,013 / 1,000)
--------- beginning of system
05-11 16:15:48.290   673   673 D io_stats: !@   8,0 r 191031 7093632 w 111517 1215128 d 41435 1206600 f 0 0 iot 158560 0 th 0 0 0 pt 0 inp 0 0 3966.306
05-11 16:15:48.290   673   673 D io_stats: !@ Write_top(KB): kworker/u16:14(7166) 8
--------- switch to main
05-11 16:15:48.487  1025  1193 I EDEN    : [Exynos][EDEN][v1.6.20][SERVICE] processAliveMointorMain:190: Try to check pid=(968)...
05-11 16:15:50.396   929   929 I android.hardware.health@2.1-service-samsung: updateLrpSysfs: write: 307
05-11 16:15:50.555  1404  3400 D SemWifiUsabilityStatsMonitor: onWifiUsabilityStats - seqNum 707, isSameBssidAndFreq true
05-11 16:15:50.559  1404  1768 I SemWifiLinkQualityMonitor: Link Qos Query: 0,079 ms / 101,275 Mbps (130 / 0,017 / 1,000)
--------- switch to system
05-11 16:15:53.265  2151  2151 I wpa_supplicant: Heartbeat 396
--------- switch to main
05-11 16:15:53.490  1025  1193 I EDEN    : [Exynos][EDEN][v1.6.20][SERVICE] processAliveMointorMain:190: Try to check pid=(968)...
05-11 16:15:53.654  1404  3400 D SemWifiUsabilityStatsMonitor: onWifiUsabilityStats - seqNum 708, isSameBssidAndFreq true
05-11 16:15:53.654  1404  1768 I SemWifiLinkQualityMonitor: Link Qos Query: 0,075 ms / 106,122 Mbps (130 / 0,014 / 1,000)
05-11 16:15:54.221  4486 15512 E it.FitbitMobile: Error message: Peripheral device threw error waiting for ready state: C1:DA:FB:91:21:FF cause java.util.concurrent.TimeoutException: The source did not signal an event for 60 seconds and has been terminated.
05-11 16:15:54.222  4486 15512 W ScanningHandler: Cannot start scan as precondition not met with reason: cGm@583fda7
--------- switch to system
05-11 16:15:54.295   673   673 D io_stats: !@   8,0 r 191031 7093632 w 111519 1215136 d 41435 1206600 f 0 0 iot 158568 0 th 0 0 0 pt 0 inp 0 0 3972.311
--------- switch to main
05-11 16:15:54.384  4486 15514 E it.FitbitMobile: Error message: Peripheral device threw error waiting for ready state: C1:DA:FB:91:21:FF cause java.util.concurrent.TimeoutException: The source did not signal an event for 60 seconds and has been terminated.
05-11 16:15:54.385  4486 15514 W ScanningHandler: Cannot start scan as precondition not met with reason: cGm@583fda7
05-11 16:15:54.429   933   933 I Sensors : batch(19) - light_cct_sensor try to batching with 200000000
05-11 16:15:54.433   933   933 I Sensors : LightCCT_Sensor old sensor_state 16896, new sensor_state : 1585517242106368 en : 1
05-11 16:15:54.437   933   933 I Sensors : enable:: light_cct_sensor(19)
05-11 16:15:54.439  1404  2123 D SensorManager: registerListener :: 33, TMD4912 Light CCT, 200000, 0, com.samsung.android.displaysolution.EyeComfortSolutionService$2@8049bb8
05-11 16:15:54.478   933  1592 I Sensors : lux = 32, CCT = 0, r = 1002, g = 210, b = 997, c = 214, atime = 2060, again = 2048, lux_raw = 32, brightness = 12, time = 4260952586419
05-11 16:15:54.481  1404  2123 D SensorService: Calling activate off 33
05-11 16:15:54.483   933   933 I Sensors : LightCCT_Sensor old sensor_state 16896, new sensor_state : 1585512947139072 en : 0
05-11 16:15:54.486   933   933 I Sensors : disable:: light_cct_sensor(19)
05-11 16:15:54.488  1404  2123 D SensorManager: unregisterListener :: com.samsung.android.displaysolution.EyeComfortSolutionService$2@8049bb8
--------- switch to system
05-11 16:15:56.296   673   673 D io_stats: !@ Write_top(KB): kworker/u16:5(7145) 8
--------- switch to main
05-11 16:15:56.748  1404  3400 D SemWifiUsabilityStatsMonitor: onWifiUsabilityStats - seqNum 709, isSameBssidAndFreq true
05-11 16:15:56.749  1404  1768 I SemWifiLinkQualityMonitor: Link Qos Query: 0,077 ms / 103,331 Mbps (130 / 0,016 / 1,000)
05-11 16:15:57.139 15326 15326 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
05-11 16:15:57.142 15326 15326 I AndroidRuntime: Using default boot image
05-11 16:15:57.142 15326 15326 I AndroidRuntime: Leaving lock profiling enabled
05-11 16:15:57.143 15326 15326 D SecNativeFeatureCppIf: encoded
05-11 16:15:57.143 15326 15326 D SecNativeFeatureCppIf: decoding and unzip finish
05-11 16:15:57.143 15326 15326 D SecNativeFeatureCppIf: use unCompDataBuff. encoded
05-11 16:15:57.143 15326 15326 D SecNativeFeatureCppIf: Free unCompDataBuff
05-11 16:15:57.143 15326 15326 D AndroidRuntime: addProductProperty: pBrand1 is not null
05-11 16:15:57.143 15326 15326 D AndroidRuntime: addProductProperty: not brand or 7
05-11 16:15:57.145 15326 15326 I app_process: Using CollectorTypeCC GC.
05-11 16:15:57.211 15326 15326 D app_process: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
05-11 16:15:57.211 15326 15326 D app_process: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt70l.dat
05-11 16:15:57.215 15326 15326 W ziparchive: Unable to open '/data/local/tmp/scrcpy-server.dm': No such file or directory
05-11 16:15:57.224 15326 15326 E SemDvfsManager_JNI: SemDvfsManager: registerfunction enter
05-11 16:15:57.224 15326 15326 E SemAffinityControl: SemAffinityControl: registerfunction enter
05-11 16:15:57.228 15326 15326 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
05-11 16:15:57.233 15326 15326 D SemCscFeature: Encoded
05-11 16:15:57.256 15326 15326 W app_process: unable to execute idmap2: Permission denied
05-11 16:15:57.256 15326 15326 W OverlayConfig: 'idmap2 create-multiple' failed: no mutable="false" overlays targeting "android" will be loaded
05-11 16:15:57.256   886   886 E audit   : type=1400 audit(1683814557.253:884): avc:  denied  { execute } for  pid=15326 comm="main" name="idmap2" dev="dm-4" ino=648 scontext=u:r:shell:s0 tcontext=u:object_r:idmap_exec:s0 tclass=file permissive=0 SEPF_SM-G998B_12_0001 audit_filtered
05-11 16:15:57.256   886   886 E audit   : type=1300 audit(1683814557.253:884): arch=c00000b7 syscall=48 success=no exit=-13 a0=ffffff9c a1=7eafb03ae2 a2=1 a3=0 items=1 ppid=15324 pid=15326 auid=4294967295 uid=2000 gid=2000 euid=2000 suid=2000 fsuid=2000 egid=2000 sgid=2000 fsgid=2000 tty=(none) ses=4294967295 comm="main" exe="/system/bin/app_process64" subj=u:r:shell:s0 key=(null)
05-11 16:15:57.256   886   886 E audit   : type=1302 audit(1683814557.253:884): item=0 name="/system/bin/idmap2" inode=648 dev=fd:04 mode=0100755 ouid=0 ogid=2000 rdev=00:00 obj=u:object_r:idmap_exec:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
05-11 16:15:57.256   886   886 E audit   : type=1327 audit(1683814557.253:884): proctitle=6170705F70726F63657373002F00636F6D2E67656E796D6F62696C652E7363726370792E53657276657200312E31322E310030003830303030303000300066616C7365002D00747275650074727565
05-11 16:15:57.257 15326 15326 I SemTelecomManager: hasSamsungTelecomSystemFeature : true
05-11 16:15:57.258 15326 15326 E SystemServiceRegistry: systemservice inputdev:true
05-11 16:15:57.261 15326 15326 D SecIpmManagerFrameworkInitializer:  initial
05-11 16:15:57.269 15326 15326 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
05-11 16:15:57.269 15326 15326 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
05-11 16:15:57.270 15326 15326 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
05-11 16:15:57.271 15326 15342 I CCodec  : state->set(ALLOCATING)
05-11 16:15:57.271 15326 15343 I CCodec  : allocate(c2.exynos.h264.encoder)
05-11 16:15:57.273 15326 15343 I Codec2Client: Available Codec2 services: "default" "default0" "software"
05-11 16:15:57.274 15326 15343 I CCodec  : setting up 'default' as default (vendor) store
05-11 16:15:57.276   965  1456 W ColorUtils: expected specified color aspects (0:0:0:0)
05-11 16:15:57.276   965  1456 I samsung.hardware.media.c2@1.0-service: missing struct descriptor #Param::CoreIndex(--004) for field values of struct #Param::CoreIndex(F-12004)
05-11 16:15:57.278 15326 15343 I CCodec  : Created component [c2.exynos.h264.encoder]
05-11 16:15:57.278 15326 15343 I CCodec  : [c2.exynos.h264.encoder] state->set(ALLOCATED)
05-11 16:15:57.278 15326 15343 D CCodecConfig: read media type: video/avc
05-11 16:15:57.279 15326 15343 D ReflectedParamUpdater: extent() != 1 for single value type: output.subscribed-indices.values
05-11 16:15:57.279 15326 15343 D ReflectedParamUpdater: extent() != 1 for single value type: input.buffers.allocator-ids.values
05-11 16:15:57.279 15326 15343 D ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.allocator-ids.values
05-11 16:15:57.279 15326 15343 D ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.pool-ids.values
05-11 16:15:57.282 15326 15343 D ReflectedParamUpdater: ignored struct field coding.gop.values
05-11 16:15:57.283 15326 15343 D CCodecConfig: ignoring local param raw.color (0xc2001809) as it is already supported
05-11 16:15:57.283 15326 15343 I CCodecConfig: query failed after returning 19 values (BAD_INDEX)
05-11 16:15:57.283 15326 15343 D CCodecConfig: c2 config diff is Dict {
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::u32 algo.bitrate-mode.value = 3
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::i32 algo.priority.value = 0
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::float algo.rate.value = 0
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::i32 coded.average-qp.value = 0
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::u32 coded.bitrate-mode.value = 1
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::u32 coded.bitrate.value = 64000
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::float coded.frame-rate.value = 15
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::u32 coded.pl.level = 20480
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::u32 coded.pl.profile = 20484
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::u32 coding.intra-refresh.mode = 0
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::float coding.intra-refresh.period = 0
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::u32 coding.request-sync-frame.value = 0
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::i64 coding.sync-frame-interval.value = 1000000
05-11 16:15:57.283 15326 15343 D CCodecConfig:   Buffer coding.temporal-layering = {
05-11 16:15:57.283 15326 15343 D CCodecConfig:     00000000:  10 00 00 00 07 20 01 52  00 00 00 00 00 00 00 00  ..... .R........
05-11 16:15:57.283 15326 15343 D CCodecConfig:   }
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::u32 input.delay.value = 0
05-11 16:15:57.283 15326 15343 D CCodecConfig:   string input.media-type.value = "video/raw"
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::u32 output.buffers.prepend-header.value = 0
05-11 16:15:57.283 15326 15343 D CCodecConfig:   string output.media-type.value = "video/avc"
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::u32 raw.color.matrix = 0
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::u32 raw.color.primaries = 0
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::u32 raw.color.range = 0
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::u32 raw.color.transfer = 0
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::u32 raw.data-space.value = 0
05-11 16:15:57.283 15326 15343 D CCodecConfig:   c2::u32 raw.pixel-format.
05-11 16:15:57.285  1047  1092 E SurfaceFlinger: Only privileged processes can create a secure display
05-11 16:15:57.288 15326 15326 D CodecSeeding: Seed: codec c2.exynos.h264.encoder, mediatype video/avc, overrideable 1
05-11 16:15:57.288 15326 15326 D CodecProperties: setTuningValue(vq-target-bpp,0)
05-11 16:15:57.288 15326 15326 D CodecProperties: setTuningValue(vq-target-bpp-1080p,1.90)
05-11 16:15:57.288 15326 15326 D CodecProperties: setTuningValue(vq-target-bpp-720p,2.25)
05-11 16:15:57.288 15326 15326 D CodecProperties: setTuningValue(vq-target-bpp-540p,2.65)
05-11 16:15:57.288 15326 15326 D CodecProperties: setTuningValue(vq-target-bpp-480p,3.00)
05-11 16:15:57.288 15326 15326 D CodecProperties: setTuningValue(vq-target-bpp-320x240,0)
05-11 16:15:57.288 15326 15326 D CodecProperties: setTuningValue(vq-target-qpmax,-1)
05-11 16:15:57.288 15326 15326 D CodecProperties: setTuningValue(vq-target-qpmax-1080p,45)
05-11 16:15:57.288 15326 15326 D CodecProperties: setTuningValue(vq-target-qpmax-720p,43)
05-11 16:15:57.288 15326 15326 D CodecProperties: setTuningValue(vq-target-qpmax-540p,42)
05-11 16:15:57.288 15326 15326 D CodecProperties: setTuningValue(vq-target-qpmax-480p,38)
05-11 16:15:57.288 15326 15326 D CodecProperties: setTuningValue(vq-bitrate-phaseout,1.75)
05-11 16:15:57.288 15326 15326 D CodecProperties: setTuningValue(vq-boost-missing-qp,0.20)
05-11 16:15:57.288 15326 15326 D CodecProperties: setFeatureValue(can-swap-width-height,1)
05-11 16:15:57.288 15326 15326 D CodecProperties: setFeatureValue(_vq_eligible.device,1)
05-11 16:15:57.288 15326 15326 D CodecProperties: setFeatureValue(_quality.target,1)
05-11 16:15:57.288 15326 15326 D CodecSeeding: Seed: codec c2.exynos.h264.encoder, mediatype video/avc, overrideable 0
05-11 16:15:57.288 15326 15326 D VQApply : minquality: 1080x2400 outside of shaping range
05-11 16:15:57.288 15326 15326 D MediaCodec: shapeMediaFormat: deltas(1): AMessage(what = 0x00000000) = {
05-11 16:15:57.288 15326 15326 D MediaCodec:     int32_t android._encoding-quality-level = 0
05-11 16:15:57.288 15326 15326 D MediaCodec:   }
05-11 16:15:57.288 15326 15342 D MediaCodec: flushMediametrics
05-11 16:15:57.288 15326 15343 D CCodec  : [c2.exynos.h264.encoder] buffers are bound to CCodec for this session
05-11 16:15:57.288 15326 15343 I CCodec  : appPid(15326) width(1080) height(2400)
05-11 16:15:57.288 15326 15343 I CCodec  : setup(exynos2100) : (10000001)
05-11 16:15:57.288 15326 15343 D CCodecConfig: no c2 equivalents for color-format
05-11 16:15:57.288 15326 15343 D CCodecConfig: no c2 equivalents for repeat-previous-frame-after
05-11 16:15:57.288 15326 15343 D CCodecConfig: no c2 equivalents for flags
05-11 16:15:57.288 15326 15343 D CCodecConfig: no c2 equivalents for encoder
05-11 16:15:57.289 15326 15343 D CCodecConfig: no c2 equivalents for color-standard
05-11 16:15:57.289 15326 15343 D CCodecConfig: c2 config diff is   c2::u32 coded.bitrate.value = 8000000
05-11 16:15:57.289 15326 15343 D CCodecConfig:   c2::float coded.frame-rate.value = 60
05-11 16:15:57.289 15326 15343 D CCodecConfig:   c2::i64 coding.sync-frame-interval.value = 10000000
05-11 16:15:57.289 15326 15343 D CCodecConfig:   c2::u32 raw.color.matrix = 1
05-11 16:15:57.289 15326 15343 D CCodecConfig:   c2::u32 raw.color.primaries = 1
05-11 16:15:57.289 15326 15343 D CCodecConfig:   c2::u32 raw.color.range = 2
05-11 16:15:57.289 15326 15343 D CCodecConfig:   c2::u32 raw.color.transfer = 3
05-11 16:15:57.289 15326 15343 D CCodecConfig:   c2::u32 raw.size.height = 2400
05-11 16:15:57.289 15326 15343 D CCodecConfig:   c2::u32 raw.size.width = 1080
05-11 16:15:57.289 15326 15343 W Codec2Client: query -- param skipped: index = 3254781982.
05-11 16:15:57.289 15326 15343 D CCodec  : Setting encoder options for disabling wrapping
05-11 16:15:57.289 15326 15343 D CCodec  : encoding statistics level = 0
05-11 16:15:57.290 15326 15343 D CCodec  : setup formats input: AMessage(what = 0x00000000) = {
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t android._color-format = 2130708361
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t android._dataspace = 0
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t bitrate-mode = 1
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t frame-rate = 60
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t height = 2400
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t intra-refresh-period = 0
05-11 16:15:57.290 15326 15343 D CCodec  :   string mime = "video/raw"
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t prepend-sps-pps-to-idr-frames = 0
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t priority = 0
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t video-qp-average = 0
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t width = 1080
05-11 16:15:57.290 15326 15343 D CCodec  :   Rect crop(0, 0, 1079, 2399)
05-11 16:15:57.290 15326 15343 D CCodec  :   int64_t android._C2MemoryUsage = 65536
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t color-format = 2130708361
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t bytebuffer-wrapping-disable = 1
05-11 16:15:57.290 15326 15343 D CCodec  : }
05-11 16:15:57.290 15326 15343 D CCodec  : setup formats output: AMessage(what = 0x00000000) = {
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t bitrate = 8000000
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t bitrate-mode = 1
05-11 16:15:57.290 15326 15343 D CCodec  :   Rect crop(0, 0, 1079, 2399)
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t width = 1080
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t color-standard = 1
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t color-range = 2
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t color-transfer = 3
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t frame-rate = 60
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t height = 2400
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t intra-refresh-period = 0
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t level = 1
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t max-bitrate = 8000000
05-11 16:15:57.290 15326 15343 D CCodec  :   string mime = "video/avc"
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t prepend-sps-pps-to-idr-frames = 0
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t priority = 0
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t profile = 8
05-11 16:15:57.290 15326 15343 D CCodec  :   int32_t video-qp-average = 0
05-11 16:15:57.290 15326 15343 D CCodec  : }
05-11 16:15:57.290 15326 15343 I CCodecConfig: query failed after returning 19 values (BAD_INDEX)
05-11 16:15:57.290 15326 15343 D CCodecConfig: c2 config diff is   c2::u32 coded.pl.level = 20495
05-11 16:15:57.290   627   700 I servicemanager: Found vendor.samsung.frameworks.codecsolution.ISehCodecSolution/default in framework VINTF manifest.
05-11 16:15:57.291  1404  5252 D SehCodecSolutionService: updateMediaStatisticsData: (action=1@1986621044;category=1@1986621044;label=1936222260@1986621044)
05-11 16:15:57.292  1404  5252 D CodecSolution_MediaStatisticsData: MediaStatisticsData: action=1@1986621044;category=1@1986621044;label=1936222260@1986621044
05-11 16:15:57.292  1404  5252 D CodecSolution_MediaStatisticsData: Category.valueOf: 1
05-11 16:15:57.292  1404  5252 D CodecSolution_MediaStatisticsData: Action.valueOf: 1
05-11 16:15:57.292  1404  5252 D CodecSolution_MediaStatisticsData: Label.valueOf: 0x73686834
05-11 16:15:57.292  1404  5252 D CodecSolution_MediaStatisticsData: category: VENC
05-11 16:15:57.292  1404  5252 D CodecSolution_MediaStatisticsData: action: INSTANTIATE
05-11 16:15:57.292  1404  5252 D CodecSolution_MediaStatisticsData: label: SEC_HW_H264
05-11 16:15:57.292  1404  1404 D SehCodecSolutionService: handleMessage : 900
05-11 16:15:57.292  1404  1404 D SehCodecSolutionService: event : VENC
05-11 16:15:57.292  1404  1404 D CodecSolution_Logging: dma : true, feature: VENC, extra: SEC_HW_H264, value: -1
05-11 16:15:57.292  1404  1404 D CodecSolution_Logging: insert diagmon log
05-11 16:15:57.292  1404  1404 D CodecSolution_Logging: permission granted
--------- switch to system
05-11 16:15:57.293  1404  1404 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1252 vendor.samsung.frameworks.codecsolution.Logging.insertDiagmonLog:78 vendor.samsung.frameworks.codecsolution.Logging.insertLog:54 vendor.samsung.frameworks.codecsolution.Logging.insertLog:46 vendor.samsung.frameworks.codecsolution.SehCodecSolutionService$1.handleMessage:210 
--------- switch to main
05-11 16:15:57.294 15326 15343 D CCodecConfig: set default color aspects for surface (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M))
05-11 16:15:57.294 15326 15343 D CCodec  : input format changed to AMessage(what = 0x00000000) = {
05-11 16:15:57.294 15326 15343 D CCodec  :   int32_t android._color-format = 2130708361
05-11 16:15:57.294 15326 15343 D CCodec  :   int32_t android._dataspace = 260
05-11 16:15:57.294 15326 15343 D CCodec  :   int32_t bitrate-mode = 1
05-11 16:15:57.294 15326 15343 D CCodec  :   int32_t frame-rate = 60
05-11 16:15:57.294 15326 15343 D CCodec  :   int32_t height = 2400
05-11 16:15:57.294 15326 15343 D CCodec  :   int32_t intra-refresh-period = 0
05-11 16:15:57.294 15326 15343 D CCodec  :   string mime = "video/raw"
05-11 16:15:57.294 15326 15343 D CCodec  :   int32_t prepend-sps-pps-to-idr-frames = 0
05-11 16:15:57.294 15326 15343 D CCodec  :   int32_t priority = 0
05-11 16:15:57.294 15326 15343 D CCodec  :   int32_t video-qp-average = 0
05-11 16:15:57.294 15326 15343 D CCodec  :   int32_t width = 1080
05-11 16:15:57.294 15326 15343 D CCodec  :   Rect crop(0, 0, 1079, 2399)
05-11 16:15:57.294 15326 15343 D CCodec  :   int64_t android._C2MemoryUsage = 65536
05-11 16:15:57.294 15326 15343 D CCodec  :   int32_t color-format = 2130708361
05-11 16:15:57.294 15326 15343 D CCodec  :   int32_t bytebuffer-wrapping-disable = 1
05-11 16:15:57.294 15326 15343 D CCodec  :   int32_t color-range = 2
05-11 16:15:57.294 15326 15343 D CCodec  :   int32_t color-standard = 1
05-11 16:15:57.294 15326 15343 D CCodec  :   int32_t color-transfer = 3
05-11 16:15:57.294 15326 15343 D CCodec  : }
--------- switch to system
05-11 16:15:57.294  4014  4014 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1926 android.content.ContextWrapper.startService:834 android.content.ContextWrapper.startService:834 com.sec.android.diagmonagent.sa.receiver.CFLogReceiver.a:4 com.sec.android.diagmonagent.sa.receiver.CFLogReceiver.onReceive:4 
--------- switch to main
05-11 16:15:57.295 15326 15343 W Codec2Client: query -- param skipped: index = 1610614798.
05-11 16:15:57.295 15326 15343 D C2OMXNode: actual buffer count(4), input delay(0), pipeline delay(0)
05-11 16:15:57.295  1245  1347 D GraphicBufferSource: setting dataspace: 0x104, acquired=0
05-11 16:15:57.296 15326 15343 D CCodec  : ISConfig minFps=10 => repeatDelayUs=100000
05-11 16:15:57.297 15326 15326 D AndroidRuntime: Shutting down VM
--------- beginning of crash
05-11 16:15:57.297 15326 15326 E AndroidRuntime: FATAL EXCEPTION: main
05-11 16:15:57.297 15326 15326 E AndroidRuntime: PID: 15326
05-11 16:15:57.297 15326 15326 E AndroidRuntime: java.lang.AssertionError: java.lang.reflect.InvocationTargetException
05-11 16:15:57.297 15326 15326 E AndroidRuntime: 	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
05-11 16:15:57.297 15326 15326 E AndroidRuntime: 	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:178)
05-11 16:15:57.297 15326 15326 E AndroidRuntime: 	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:70)
05-11 16:15:57.297 15326 15326 E AndroidRuntime: 	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
05-11 16:15:57.297 15326 15326 E AndroidRuntime: 	at com.genymobile.scrcpy.Server.main(Server.java:163)
05-11 16:15:57.297 15326 15326 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
05-11 16:15:57.297 15326 15326 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:378)
05-11 16:15:57.297 15326 15326 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
05-11 16:15:57.297 15326 15326 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-11 16:15:57.297 15326 15326 E AndroidRuntime: 	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
05-11 16:15:57.297 15326 15326 E AndroidRuntime: 	... 6 more
05-11 16:15:57.297 15326 15326 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: displayToken must not be null
05-11 16:15:57.297 15326 15326 E AndroidRuntime: 	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3693)
05-11 16:15:57.297 15326 15326 E AndroidRuntime: 	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2489)
05-11 16:15:57.297 15326 15326 E AndroidRuntime: 	... 8 more
--------- switch to main
05-11 16:15:57.298 15326 15326 E scrcpy  : Exception on thread Thread[main,5,main]
05-11 16:15:57.298 15326 15326 E scrcpy  : java.lang.AssertionError: java.lang.reflect.InvocationTargetException
05-11 16:15:57.298 15326 15326 E scrcpy  : 	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
05-11 16:15:57.298 15326 15326 E scrcpy  : 	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:178)
05-11 16:15:57.298 15326 15326 E scrcpy  : 	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:70)
05-11 16:15:57.298 15326 15326 E scrcpy  : 	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
05-11 16:15:57.298 15326 15326 E scrcpy  : 	at com.genymobile.scrcpy.Server.main(Server.java:163)
05-11 16:15:57.298 15326 15326 E scrcpy  : 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
05-11 16:15:57.298 15326 15326 E scrcpy  : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:378)
05-11 16:15:57.298 15326 15326 E scrcpy  : Caused by: java.lang.reflect.InvocationTargetException
05-11 16:15:57.298 15326 15326 E scrcpy  : 	at java.lang.reflect.Method.invoke(Native Method)
05-11 16:15:57.298 15326 15326 E scrcpy  : 	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
05-11 16:15:57.298 15326 15326 E scrcpy  : 	... 6 more
05-11 16:15:57.298 15326 15326 E scrcpy  : Caused by: java.lang.IllegalArgumentException: displayToken must not be null
05-11 16:15:57.298 15326 15326 E scrcpy  : 	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3693)
05-11 16:15:57.298 15326 15326 E scrcpy  : 	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2489)
05-11 16:15:57.298 15326 15326 E scrcpy  : 	... 8 more
05-11 16:15:57.333  1238 12321 E mediaserver: unlinkToDeath: removed reference to death recipient but unlink failed.
05-11 16:15:57.334  1238 12321 E IPCThreadState: attemptIncStrongHandle(5): Not supported
05-11 16:15:57.335   965  1456 I ExynosC2H264EncComponent: [release] component is released
```

**Comment by robertosw** [comment]
Additional Info:
- I got the S21U exynos version, since Im in europe
- Tools like flutter have no problem with the cable - phone - usb port - laptop combo

**Comment by rom1v** [comment]
> scrcpy version: 1.12.1
> Android version: 13

Android >= 12 requires scrcpy >= 1.18 (#2129). Upgrade to the [latest version](https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version).
