### ISSUE TITLE
Demuxer 'audio': stream explicitly disabled by the device

### ISSUE THREAD

**Issue by elf-world** [Genymobile/scrcpy#3992]
[server] INFO: Device: vivo V2055A (Android 13)
[server] ERROR: Exception on thread Thread[Thread-4,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getOpPackageName()' on a null object reference
        at android.media.VivoAudioRecordImpl.isSupportSubMixRecording(VivoAudioRecordImpl.java:133)
        at android.media.AudioRecord.<init>(AudioRecord.java:493)
        at android.media.AudioRecord.<init>(Unknown Source:0)
        at android.media.AudioRecord$Builder.build(AudioRecord.java:999)
        at com.genymobile.scrcpy.AudioCapture.createAudioRecord(AudioCapture.java:58)
        at com.genymobile.scrcpy.AudioCapture.start(AudioCapture.java:90)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:183)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:120)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:1015)
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device

**Comment by rom1v** [comment]
This is a problem specific to Vivo devices. See #3805.

PR #3862 provides a workaround, which will be merged before thebscrcpy v2.1 release.

I'm closing as duplicate.

**Comment by elf-world** [comment]
> 

thank you！
