### ISSUE TITLE
Error on Redmi 7 Android 11 LineageOS

### ISSUE THREAD

**Issue by nickleby** [Genymobile/scrcpy#4000]
**Environment**
 - OS: Windows 10
 - scrcpy version: latest
 - device model: Redmi 7
 - Android version: Android 11 (LineageOS)

**Describe the bug**
I tried using scrcpy on my Redmi 7 but I'm receiving this error:

```
[server] INFO: Device: Xiaomi Redmi 7 (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 720x1520
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1280...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1024...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m800...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:334)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
WARN: Killing the server...
```

**Comment by wbwue** [comment]
I have the same error on a z2play (albus) running LineageOS 18.1 (Android 11), both scrcpy 2.0 and 2.1, from MacOS 13.4.1

**Comment by nickleby** [comment]
> See #4144.

Hi!
I've got this list:
```
[server] INFO: List of video encoders:
    --video-codec=h264 --video-encoder='OMX.qcom.video.encoder.avc'
    --video-codec=h264 --video-encoder='c2.android.avc.encoder'
    --video-codec=h264 --video-encoder='OMX.google.h264.encoder'
    --video-codec=h265 --video-encoder='OMX.qcom.video.encoder.hevc'
    --video-codec=h265 --video-encoder='c2.android.hevc.encoder'
[server] INFO: List of audio encoders:
    --audio-codec=opus --audio-encoder='c2.android.opus.encoder'
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
    --audio-codec=aac --audio-encoder='c2.android.aac.encoder'
```
But it gets stuck when trying some of them...:
```
[server] INFO: Device: [Xiaomi] Xiaomi Redmi 7 (Android 11)
INFO: Renderer: direct3d
INFO: Texture: 720x1520
```
It stays forever on that message...
