### ISSUE TITLE
scrcpy could not open mobile screen on PC

### ISSUE THREAD

**Issue by jbxxs** [Genymobile/scrcpy#4019]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 2.0
 - installation method: manual build
 - device model: Meizu M6 Note
 - Android version: 7.1.2

**Describe the bug**
when run scrcpy could not open mobile screen on PC.

```
D:\Scrcpy2.0\scrcpy-win64-v2.0>scrcpy
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
D:\Scrcpy2.0\scrcpy-win64-v2.0\scrcpy-server: 1 file pushed, 0 skipped. 52.0 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: Meizu M6 Note (Android 7.1.2)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
        at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java:151)
        at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java:151)
        at com.android.server.NetworkManagementSocketTagger.getApplicationInfo(NetworkManagementSocketTagger.java:262)
        at com.android.server.NetworkManagementSocketTagger.getProcessInfo(NetworkManagementSocketTagger.java:292)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:139)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:47)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:288)
        at android.system.Os.socket(Os.java:491)
        at android.net.LocalSocketImpl.create(LocalSocketImpl.java:256)
        at android.net.LocalSocket.implCreateIfNeeded(LocalSocket.java:107)
        at android.net.LocalSocket.connect(LocalSocket.java:130)
        at com.genymobile.scrcpy.DesktopConnection.connect(DesktopConnection.java:50)
        at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:85)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:97)
        at com.genymobile.scrcpy.Server.main(Server.java:381)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:281)
ERROR: Server connection failed
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Should be already fixed on `dev`. Please test https://github.com/Genymobile/scrcpy/issues/3801#issuecomment-1468897171
