### ISSUE TITLE
--stay-awake erroring out on console

### ISSUE THREAD

**Issue by EPinci** [Genymobile/scrcpy#4021]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 2.0
 - installation method: Windows release
 - device model: Oneplus KB2003
 - Android version: 13

**Describe the bug**
The `--stay-awake` options errors out.

```
[server] INFO: Device: OnePlus KB2003 (Android 13)
[server] ERROR: Could not change "stay_on_while_plugged_in"
com.genymobile.scrcpy.SettingsException: Could not access settings: put global stay_on_while_plugged_in 7
        at com.genymobile.scrcpy.Settings.execSettingsPut(Settings.java:24)
        at com.genymobile.scrcpy.Settings.putValue(Settings.java:59)
        at com.genymobile.scrcpy.Settings.getAndPutValue(Settings.java:78)
        at com.genymobile.scrcpy.Server.initAndCleanUp(Server.java:36)
        at com.genymobile.scrcpy.Server.lambda$startInitThread$1(Server.java:159)
        at com.genymobile.scrcpy.Server$$ExternalSyntheticLambda2.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.IOException: Command [settings, put, global, stay_on_while_plugged_in, 7] returned with value 255
        at com.genymobile.scrcpy.Command.exec(Command.java:16)
        at com.genymobile.scrcpy.Settings.execSettingsPut(Settings.java:22)
        ... 6 more
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Try: Developer Options > Apps > Disable permission monitoring

Refs https://github.com/Genymobile/gnirehtet/issues/5#issuecomment-1445340014

**Comment by rom1v** [comment]
What is the result of:

```
adb shell put global stay_on_while_plugged_in 7
```

?

**Comment by EPinci** [comment]
Result is:
```
D:\>adb shell put global stay_on_while_plugged_in 7
/system/bin/sh: put: inaccessible or not found
```

Enabling "Disable permission monitoring" effectively makes it work.
Wonder if there's a way to allow this only for scrcpy instead of everything.

**Comment by rom1v** [comment]
> Wonder if there's a way to allow this only for scrcpy instead of everything

Nope. This option does not exist on Android (AOSP), it's a vendor addition.
