### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by anhnhoktvn** [Genymobile/scrcpy#4042]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu
 - scrcpy version: 2.0
 - installation method: git clone
 - device model: Device: Sony SO-04J (Android 9)
 - Android version: 9

**Describe the bug**

It's not working
```
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 324.1 MB/s (52867 bytes in 0.000s)
[server] INFO: Device: Sony SO-04J (Android 9)
[server] WARN: Audio disabled: it is not supported before Android 11
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.2.5
INFO: Trilinear filtering enabled
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Initial texture: 1080x1920
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.destroyDisplay(SurfaceControl.java:174)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:115)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:133)
	at com.genymobile.scrcpy.Server.main(Server.java:381)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.destroyDisplay(SurfaceControl.java:172)
	... 5 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl.destroyDisplay(SurfaceControl.java:1185)
	... 7 more

```

**Comment by rom1v** [comment]
So it seems your device does not have `SurfaceControl.destroyDisplay()` with the expected signature. Please post your `framework.jar`:

```
adb pull /system/framework/framework.jar
```

But this only explains why you have a stacktrace at the end, this does not explain why it does not work.

Does it work with `scrcpy --no-audio`?

Does screenrecord work?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

?

**Comment by anhnhoktvn** [comment]
[framework.jar.zip](https://github.com/Genymobile/scrcpy/files/11593097/framework.jar.zip)
> Does it work with scrcpy --no-audio?

No, it doesn't

>Does screenrecord work?

No, I just got an empty file

**Comment by rom1v** [comment]
OK, so it's a problem on your device/rom.

**Comment by hienyimba** [comment]
Try the [Duplica (scrcpy ui)](https://pcmac.download/duplica-emulator) app.

You might lose some features as it's a bit old but it works.

**Comment by umanda** [comment]
I have run `scrcpy -b2M -m800`

Works for me

I use Ubuntu too
