### ISSUE TITLE
Wear OS (Fossil Q Control)

### ISSUE THREAD

**Issue by Rawsted** [Genymobile/scrcpy#407]
```
scrcpy-server.jar: 1 file pushed. 1.5 MB/s (19346 bytes in 0.012s)
ERROR: Could not open video stream
ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1786)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1752)
        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:138)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:63)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:28)
        at com.genymobile.scrcpy.Server.main(Server.java:110)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)
INFO: Initial texture: 448x448
WARN: Cannot terminate server
Press any key to continue...
```

**Comment by rom1v** [comment]
The device has probably no hardware encoder.
