### ISSUE TITLE
Scrcpy is unable to control screen on Android U version 

### ISSUE THREAD

**Issue by mujahed121** [Genymobile/scrcpy#4085]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]  Debian
 - scrcpy version: [e.g. 1.12.1]  scrcpy 1.25
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...] sudo apt install adb ffmpeg libsdl2-2.0-0 scrcpy

 - device model: Pixel 7A
 - Android version: [e.g. 10]  UP1A.230606.001.X

**Describe the bug**
A clear and concise description of what the bug is. I am trying to control the devices using the mouse but scrcpy is trowing error

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
$ scrcpy
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 4.2 MB/s (42151 bytes in 0.010s)
[server] INFO: Device: Google Pixel 7a (Android 14)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 20.0.8
INFO: Trilinear filtering enabled
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:128)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:138)
	at com.genymobile.scrcpy.Device.<init>(Device.java:100)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
	at com.genymobile.scrcpy.Server.main(Server.java:334)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
INFO: Initial texture: 1080x2400
../src/intel/isl/isl.c:1988: FINISHME: ../src/intel/isl/isl.c:isl_surf_get_ccs_surf: CCS for 8BPP textures with 3+ miplevels is disabled, but support for more levels is possible.
[server] ERROR: Exception on thread Thread[Thread-2,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:75)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:196)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:231)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:102)
	at com.genymobile.scrcpy.Controller.control(Controller.java:79)
	at com.genymobile.scrcpy.Server$3.run(Server.java:132)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:72)
	... 7 more
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:207)
	at android.hardware.input.InputManager.getInstance(InputManager.java:271)
	... 9 more
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
It works with the current `dev` branch (#3784, #4074, #4075).

**Comment by mujahed121** [comment]
Can you share me installation steps from dev branch for Linux deb ?
