### ISSUE TITLE
Exception on main Thread

### ISSUE THREAD

**Issue by FaixyX** [Genymobile/scrcpy#4106]
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:110)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)

**Comment by rom1v** [comment]
Which device? (Please post the whole console output, including the lines before the exception)

Try with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#codec) (see `--list-encoders`).

Does `screenrecord` work?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

**Comment by FaixyX** [comment]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Debian
 - scrcpy version: 1.21
 - installation method: apt
 - device model: samsung SM-N950F
 - Android version: 9

**Describe the bug**
A clear and concise description of what the bug is.

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...shed. 2.8 MB/s (39473 bytes in 0.013s)
[server] INFO: Device: samsung SM-N950F (Android 9)
INFO: Renderer: opengl
INFO: OpenGL version: 4.2 (Compatibility Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2216
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:110)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
```

**Comment by rom1v** [comment]
> scrcpy 1.21

Try a newer version (v2.1 for example), it will downscale automatically on error.

On your version, you can probably just reduce the resolution: `scrcpy -m1024` for example.

**Comment by FaixyX** [comment]
on the v1.21, when I am running the command "scrcpy -m1024", it starts showing screen but the whole screen is green. Also same on scrcpy -m720 too

**Comment by FaixyX** [comment]
Everything worked fine until I downloaded the scrcpy on my Windows and connected my mobile there. When I come back on my Ubuntu, it's not working.

**Comment by FaixyX** [comment]
Also, my mobile screen got hung when the green screen on the laptop showed.

**Comment by rom1v** [comment]
Try with another encoder (as suggested in my previous comment).

**Comment by FaixyX** [comment]
I have tried many encoders but still not working
