### ISSUE TITLE
nvidia Shield Android TV - Audio error in console

### ISSUE THREAD

**Issue by wazerstar** [Genymobile/scrcpy#4110]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - Desktop Windows 10 Pro x64
 - scrcpy version: 2.1
 - Windows release
 - device model: nVidia Shield Pro 2017
 - Android **TV** version: 11
 - Nvidia Software version 9.1.1(33.2.0.157)

**Describe the bug**
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
D:\programmer\scrcpy-win64\2.1>scrcpy --tcpip=192.168.1.26:5555 --window-title nVidia_Shield -m1280 --max-fps 60 --kill-adb-on-close
scrcpy 2.1 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
INFO: Connecting to 192.168.1.26:5555...
INFO: Connected to 192.168.1.26:5555
D:\programmer\scrcpy-win64\2.1\scrcpy-server: 1 file pushed, 0 skipped. 245.9 MB/s (56955 bytes in 0.000s)
[server] INFO: Device: [NVIDIA] NVIDIA SHIELD Android TV (Android 11)
[server] ERROR: Could not create default audio encoder for opus
List of audio encoders:
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:2117)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:2042)
        at com.genymobile.scrcpy.AudioEncoder.createMediaCodec(AudioEncoder.java:292)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:184)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:124)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:923)
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1280x720

```

**Comment by wazerstar** [comment]
Adding `--audio-codec=aac` works, gives audio and no error output in console

**Comment by rom1v** [comment]
> Adding `--audio-codec=aac` works, gives audio and no error output in console

:+1: (Your device does not have any opus encoder)
