### ISSUE TITLE
System crash if no audio device is enabled

### ISSUE THREAD

**Issue by mkmonkey** [Genymobile/scrcpy#4111]
Hi !

As a audiophile I have a USB DAC for enhance my audio experience .
However , the device is turned off if I'm not listening to music .
And , once I have turned off the DAC , the computer do not have any other available audio device .

I've noticed that if I didn't turn the audio device on , the program will crash after a few second .
And , in the control panel , there will be a "Demuxer Error" show up before the program crash .

** Update **
Sometimes the SCRCPY will work even the DAC is off .
According to my observation , if the DAC has been turned on at least one time , 
even though the DAC turned off afterward , SCRCPY will works

So I would like to request a feature to prevent the program crash if there is no audio device is available in the system .

Thanks very much !

Best regards,
Kurz

Environment
Windows 10 Pro
Asus ZenFone 6 (Android 11)
Fiio USB DAC

** Terminal Output / working with warning **
scrcpy 2.1 <https://github.com/Genymobile/scrcpy>
C:\Users\Kurz\Desktop\scrcpy-win64-v1.24\scrcpy-server: 1 file pushed, 0 skipped. 89.5 MB/s (56955 bytes in 0.001s)
[server] INFO: Device: [asus] asus ASUS_I01WD (Android 11)
INFO: Renderer: direct3d
INFO: Texture: 1080x2336
[server] ERROR: Failed to start audio capture
[server] ERROR: On Android 11, audio capture must be started in the foreground, make sure that the device is unlocked when starting scrcpy.
WARN: Demuxer 'audio': stream explicitly disabled by the device
[server] INFO: Device screen turned off
[server] INFO: Device clipboard set

** Terminal Output / not working **
![Capture](https://github.com/Genymobile/scrcpy/assets/17672407/97434037-2a44-4ddc-86a5-c8f228675314)
(So sorry I only have the screen capture at this moment)

**Comment by rom1v** [comment]
> System crash

Does it crash? Or just the audio is not played?

> ERROR: Could not open audio device: WASAPI can't find requested audio endpoint: Element not found.

Double-click on `open_a_terminal_here.bat`, and type:

```bash
set SDL_AUDIODRIVER=directsound
scrcpy
```

Does it work?

> I've noticed that if I didn't turn the audio device on , the program will crash after a few second .
>
>  there will be a "Demuxer Error" show up before the program crash.

What's the error in the console when it "crash"? (run from `open_a_terminal_here.bat` or `scrcpy-console.bat` so that it does not close the terminal on error)

**Comment by mkmonkey** [comment]
Hi !

For the "System Crash" , both terminal and the mirror image box disappear .
Just got the situation and have the terminal record as below :

** Terminal Output / not working **
scrcpy 2.1 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
C:\Users\Kurz\Desktop\scrcpy-win64-v1.24\scrcpy-server: 1 file pushed, 0 skipped. 5.4 MB/s (56955 bytes in 0.010s)
[server] INFO: Device: [asus] asus ASUS_I01WD (Android 11)
INFO: Renderer: direct3d
INFO: Texture: 1080x2336
ERROR: Could not open audio device: WASAPI can't find requested audio endpoint: Element not found.
ERROR: Demuxer error
Press any key to continue . . .
** End of output **

I have tried "set SDL_AUDIODRIVER=directsound" , **sometimes it will work and sometimes doesn't .**
If it doesn't work , the error screen will be the same as the above . 
If it works , the error screen will be like that  :
** Terminal Output / Working but no sound **
scrcpy 2.1 https://github.com/Genymobile/scrcpy
C:\Users\Kurz\Desktop\scrcpy-win64-v1.24\scrcpy-server: 1 file pushed, 0 skipped. 89.5 MB/s (56955 bytes in 0.001s)
[server] INFO: Device: [asus] asus ASUS_I01WD (Android 11)
INFO: Renderer: direct3d
INFO: Texture: 1080x2336
[server] ERROR: Failed to start audio capture
[server] ERROR: On Android 11, audio capture must be started in the foreground, make sure that the device is unlocked when starting scrcpy.
WARN: Demuxer 'audio': stream explicitly disabled by the device
** End of output **

And , after a few try , I also notice there is another possible error output , which the program won't even startup:
** Terminal Output / not working **
C:\Users\Kurz\Desktop\scrcpy-win64-v1.24>scrcpy.exe --stay-awake
scrcpy 2.1 <https://github.com/Genymobile/scrcpy>
C:\Users\Kurz\Desktop\scrcpy-win64-v1.24\scrcpy-server: 1 file pushed, 0 skipped. 98.7 MB/s (56955 bytes in 0.001s)
[server] INFO: Device: [asus] asus ASUS_I01WD (Android 11)
INFO: Renderer: direct3d
INFO: Texture: 1080x2336
ERROR: Could not open audio device: DirectSoundCreate8: No audio device found (0x88780078)
ERROR: Demuxer error
[server] ERROR: Audio capture error
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2042)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2076)
        at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:387)
        at com.genymobile.scrcpy.AudioEncoder.inputThread(AudioEncoder.java:94)
        at com.genymobile.scrcpy.AudioEncoder.lambda$encode$1$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:198)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:923)
** End of output **

Thanks very much !

**Comment by rom1v** [comment]
> I have tried "set SDL_AUDIODRIVER=directsound" , sometimes it will work and sometimes doesn't .

> [server] ERROR: On Android 11, audio capture must be started in the foreground, make sure that the device is unlocked when starting scrcpy.

For Android 11, you must start scrcpy when your screen is unlocked. See the [audio documentation](https://github.com/Genymobile/scrcpy/blob/master/doc/audio.md).
