### ISSUE TITLE
Have Error Start Srccyp

### ISSUE THREAD

**Issue by selltool** [Genymobile/scrcpy#4144]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 2.1
 - installation method: Windows release
 - device model: Xiaomi Redmi Note 9
 - Android version: 13

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
scrcpy 2.1 <https://github.com/Genymobile/scrcpy>
C:\Users\admin\Desktop\scrcpy-win64-v2.1\scrcpy-server: 1 file pushed, 0 skipped. 142.7 MB/s (56955 bytes in 0.000s)
[server] INFO: Device: [Xiaomi] Redmi 23021RAAEG (Android 13)
INFO: Renderer: direct3d
INFO: Texture: 1080x2400
[server] INFO: newMaxSize = 1920
[server] INFO: Retrying with -m1920...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalArgumentException: null
[server] INFO: newMaxSize = 1600
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] INFO: Retrying with -m1600...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] INFO: newMaxSize = 1280
[server] INFO: Retrying with -m1280...
[server] INFO: Retrying...
[server] INFO: newMaxSize = 1024
[server] INFO: Retrying with -m1024...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] INFO: newMaxSize = 800
[server] INFO: Retrying with -m800...
[server] INFO: Retrying...
[server] INFO: newMaxSize = 0
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: start failed
[server] ERROR: Exception on thread Thread[video,5,main]
android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2322)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:102)
        at com.genymobile.scrcpy.ScreenEncoder.lambda$start$0$com-genymobile-scrcpy-ScreenEncoder(ScreenEncoder.java:290)
        at com.genymobile.scrcpy.ScreenEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
```

**Comment by rom1v** [comment]
It's an encoder issue on the device.

You could try with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#codec) (if any), see `scrcpy --list-encoders`.

**Comment by selltool** [comment]
> It's an encoder issue on the device.
> 
> You could try with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#codec) (if any), see `scrcpy --list-encoders`.

here
```
C:\Users\admin\Desktop\scrcpy-win64-v2.1>scrcpy --list-encoders
scrcpy 2.1 <https://github.com/Genymobile/scrcpy>
C:\Users\admin\Desktop\scrcpy-win64-v2.1\scrcpy-server: 1 file pushed, 0 skipped. 68.3 MB/s (56955 bytes in 0.001s)
[server] INFO: List of video encoders:
    --video-codec=h264 --video-encoder='c2.qti.avc.encoder'
    --video-codec=h264 --video-encoder='OMX.qcom.video.encoder.avc'
    --video-codec=h264 --video-encoder='c2.android.avc.encoder'
    --video-codec=h264 --video-encoder='OMX.google.h264.encoder'
    --video-codec=h265 --video-encoder='c2.qti.hevc.encoder'
    --video-codec=h265 --video-encoder='OMX.qcom.video.encoder.hevc'
    --video-codec=h265 --video-encoder='c2.qti.hevc.encoder.cq'
    --video-codec=h265 --video-encoder='OMX.qcom.video.encoder.hevc.cq'
    --video-codec=h265 --video-encoder='c2.android.hevc.encoder'
[server] INFO: List of audio encoders:
    --audio-codec=opus --audio-encoder='c2.android.opus.encoder'
    --audio-codec=aac --audio-encoder='c2.android.aac.encoder'
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
```

**Comment by rom1v** [comment]
Then try all these commands:

```
scrcpy --video-codec=h264 --video-encoder='c2.qti.avc.encoder'
scrcpy --video-codec=h264 --video-encoder='OMX.qcom.video.encoder.avc'
scrcpy --video-codec=h264 --video-encoder='c2.android.avc.encoder'
scrcpy --video-codec=h264 --video-encoder='OMX.google.h264.encoder'
scrcpy --video-codec=h265 --video-encoder='c2.qti.hevc.encoder'
scrcpy --video-codec=h265 --video-encoder='OMX.qcom.video.encoder.hevc'
scrcpy --video-codec=h265 --video-encoder='c2.qti.hevc.encoder.cq'
scrcpy --video-codec=h265 --video-encoder='OMX.qcom.video.encoder.hevc.cq'
scrcpy --video-codec=h265 --video-encoder='c2.android.hevc.encoder'
```

**Comment by selltool** [comment]
> 

It work, thank you

**Comment by munendra-kondeti** [comment]
thanks now working on my lineageOS Android 6 .
