### ISSUE TITLE
Error of failed request:  BadValue (integer parameter out of range for operation)

### ISSUE THREAD

**Issue by gstalnaker** [Genymobile/scrcpy#4155]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...] - MXLinux 21.3 Wildflower, Debian GNU/Linux 11, KDE Plasma 5.20.5, QT 5.15.2 kernel 5.10.0-23-amd64
 - scrcpy version: [e.g. 1.12.1] 2.1 (newly installed, was 1.25 had same issue)
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...] manual build from gh repo clone/git pull
 - device model: Samsung Galaxy S21g Ultra
 - Android version: [e.g. 10] 13

**Describe the bug**

scrcpy v1.25 worked yesterday. Today on first attempt a few minutes ago, scrcpy reported a BadValue error and fails to load. I have, to my knowledge, not updated any system software today on either desktop or Samsung. It's baffling that it worked yesterday but not today. In fact, it's been working for nearly three years with two different Samsung phones and two Linus distros.

### What I've done:

- On phone revoked the USB deb authorizations to force them to be redone
- I ran 'git pull' to get current version from repo and installed it. Same error, though v 2.1 gives a lot more error output, see below.

command saved in zsh alias as:
desktopSamsung='/usr/local/bin/scrcpy --serial R5CR92Z9AVT --display 0 -m 1100 --window-title "Galaxy S21g Ultra" --turn-screen-off --stay-awake &'

```
√ ~ > desktopSamsung [see above for what this alias contains]
[1] 46712
√ ~ > scrcpy 2.1 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 5.2 MB/s (56955 bytes in 0.010s)
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  99
  Current serial number in output stream:  100

[1]  + exit 1     /usr/local/bin/scrcpy --serial R5CR92Z9AVT --display 0 -m 1100 --window-title
√ ~ > [server] INFO: Device: [samsung] samsung SM-G998U (Android 13)
java.nio.channels.ClosedByInterruptException
java.nio.channels.ClosedByInterruptException
[server] ERROR: Exception on thread Thread[init-cleanup,5,main]
java.lang.ExceptionInInitializerError
        at libcore.icu.DecimalFormatData.getInstance(DecimalFormatData.java:95)
        at java.text.NumberFormat.getInstance(NumberFormat.java:888)
        at java.text.NumberFormat.getNumberInstance(NumberFormat.java:507)
        at java.util.Scanner.useLocale(Scanner.java:1203)
        at java.util.Scanner.<init>(Scanner.java:549)
        at java.util.Scanner.<init>(Scanner.java:572)
        at com.genymobile.scrcpy.Command.execReadLine(Command.java:23)
        at com.genymobile.scrcpy.Settings.execSettingsGet(Settings.java:30)
        at com.genymobile.scrcpy.Settings.getValue(Settings.java:46)
        at com.genymobile.scrcpy.Settings.getAndPutValue(Settings.java:76)
        at com.genymobile.scrcpy.Server.initAndCleanUp(Server.java:63)
        at com.genymobile.scrcpy.Server.lambda$startInitThread$2(Server.java:168)
        at com.genymobile.scrcpy.Server$$ExternalSyntheticLambda3.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.util.MissingResourceException: Could not find the bundle android/icu/impl/data/icudt70b/
        at android.icu.impl.ResourceBundleWrapper.getBundleInstance(ResourceBundleWrapper.java:136)
        at android.icu.util.UResourceBundle.instantiateBundle(UResourceBundle.java:375)
        at android.icu.util.UResourceBundle.getBundleInstance(UResourceBundle.java:147)
        at android.icu.util.UResourceBundle.getBundleInstance(UResourceBundle.java:226)
        at android.icu.text.DateFormatSymbols.initializeData(DateFormatSymbols.java:1960)
        at android.icu.text.DateFormatSymbols.<init>(DateFormatSymbols.java:1934)
        at android.icu.text.DateFormatSymbols.<init>(Unknown Source:0)
        at android.icu.text.DateFormatSymbols$AospExtendedDateFormatSymbols.<init>(DateFormatSymbols.java:1621)
        at android.icu.text.DateFormatSymbols$AospExtendedDateFormatSymbols.<init>(Unknown Source:0)
        at android.icu.text.DateFormatSymbols$1.createInstance(DateFormatSymbols.java:1526)
        at android.icu.text.DateFormatSymbols$1.createInstance(DateFormatSymbols.java:1511)
        at android.icu.impl.SoftCache.getInstance(SoftCache.java:71)
        at android.icu.text.DateFormatSymbols.getExtendedInstance(DateFormatSymbols.java:1555)
        at android.icu.text.DateFormatSymbols.initializeData(DateFormatSymbols.java:1541)
        at android.icu.text.DateFormatSymbols.<init>(DateFormatSymbols.java:2316)
        at android.icu.text.DateFormatSymbols.<init>(DateFormatSymbols.java:2293)
        at libcore.icu.LocaleData.initializeDateFormatData(LocaleData.java:223)
        at libcore.icu.LocaleData.initLocaleData(LocaleData.java:216)
        at libcore.icu.LocaleData.get(LocaleData.java:195)
        at libcore.icu.LocaleData.<clinit>(LocaleData.java:88)
        ... 14 more
```

adb logcat > adb_logcat.out generates a 34Mb file, and growing. Unsure how to get "relevant" information from it. I have not restarted my system.

**Comment by rom1v** [comment]
It's an error related ti your X server on the computer: https://github.com/Genymobile/scrcpy/issues/584

**Comment by gstalnaker** [comment]
Welp. Thanks for the pointer to 584 - I didn't scroll through three years of Issues to find it, and the search for BadValue returned no issues. C'est la vie. And as with that 2019 submit, restarting cleared up whatever it was. A bit disconcerting that something like this can happen with, so far as I know, no changes to the system. Suppose somehow something got corrupted in a cache? Any way, closing as it was cleared by the restart.
