### ISSUE TITLE
Phone reboots when trying to run

### ISSUE THREAD

**Issue by eabery** [Genymobile/scrcpy#4166]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 11]
 - scrcpy version: [2.1]
 - installation method: [Windows release]
 - device model: Alcatel idol4
 - Android version: [9]

Restarts phone when trying to run scrcpy

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:220)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:224)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:324)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:138)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: android.os.DeadSystemException
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:882)
        ... 10 more
Caused by: android.os.DeadSystemException
        ... 11 more

**Comment by rom1v** [comment]
The system crashes, it looks like a bug in the system ROM.

**Comment by sevensevenmi** [comment]
[server] INFO: Device: [Xiaomi] Xiaomi M2011K2C (Android 13)
INFO: Renderer: direct3d
INFO: Texture: 1080x2400
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:225)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:229)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:324)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:138)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.DeadSystemRuntimeException: android.os.DeadSystemException
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1155)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 10 more
Caused by: android.os.DeadSystemException
        ... 12 more
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:225)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:229)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:324)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:138)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.DeadSystemRuntimeException: android.os.DeadSystemException
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1155)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 10 more
Caused by: android.os.DeadSystemException
        ... 12 more

**Comment by rom1v** [comment]
Your device system crashes.

Did you enable "Security settings"? https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by sevensevenmi** [comment]
I think it's a bug in my system ROM, and I did  Brushing, which seems to have solved the problem
