### ISSUE TITLE
Text input context does not respond to _valueForTIProperty

### ISSUE THREAD

**Issue by yinbohang** [Genymobile/scrcpy#4167]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. macOS 10.15.7]
 - scrcpy version: [e.g. 2.1.1]
 - installation method: [e.g. brew]
 - device model: 
 - Android version: [e.g. 9]

**Describe the bug**
use sudo scrcpy --no-audio -m 1920 error 
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>

Dependencies (compiled / linked):
 - SDL: 2.28.1 / 2.28.1
 - libavcodec: 60.3.100 / 60.3.100
 - libavformat: 60.3.100 / 60.3.100
 - libavutil: 58.2.100 / 58.2.100
 - libusb: - / 1.0.26

```
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  CSXDU17C29002316                device  STF_AL10
/usr/local/Cellar/scrcpy/2.1.1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 147.3 MB/s (56995 bytes in 0.000s)
[server] INFO: Device: [HUAWEI] HONOR STF-AL10 (Android 9)
2023-07-17 14:06:44.583 scrcpy[86800:4430389] imkxpc_getApplicationProperty:reply: called with incorrect property value 4, bailing.
2023-07-17 14:06:44.583 scrcpy[86800:4430389] Text input context does not respond to _valueForTIProperty:
2023-07-17 14:06:44.584 scrcpy[86800:4430389] imkxpc_getApplicationProperty:reply: called with incorrect property value 4, bailing.
2023-07-17 14:06:44.584 scrcpy[86800:4430389] Text input context does not respond to _valueForTIProperty:
INFO: Renderer: metal
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.RuntimeException: cannot get MediaCodecList
	at android.media.MediaCodecList.native_getCodecCount(Native Method)
	at android.media.MediaCodecList.initCodecList(MediaCodecList.java:82)
	at android.media.MediaCodecList.<init>(MediaCodecList.java:170)
	at com.genymobile.scrcpy.CodecUtils.listVideoEncoders(CodecUtils.java:59)
	at com.genymobile.scrcpy.LogUtils.buildVideoEncoderListMessage(LogUtils.java:16)
	at com.genymobile.scrcpy.ScreenEncoder.createMediaCodec(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
	at com.genymobile.scrcpy.ScreenEncoder.lambda$start$0$com-genymobile-scrcpy-ScreenEncoder(ScreenEncoder.java:294)
	at com.genymobile.scrcpy.ScreenEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:784)
2023-07-17 14:07:16.270 scrcpy[86800:4430389] imkxpc_getApplicationProperty:reply: called with incorrect property value 4, bailing.
2023-07-17 14:07:16.270 scrcpy[86800:4430389] Text input context does not respond to _valueForTIProperty:
^CERROR: Demuxer 'video': stream disabled due to connection error
```

**Comment by rom1v** [comment]
Which device is it? (the vendor modified the method from AOSP)

Please post your `framework.jar`:

```
adb pull /system/frameworm/framework.jar
```

and post the file.
