### ISSUE TITLE
No input from keyboard or mouse

### ISSUE THREAD

**Issue by ags1234** [Genymobile/scrcpy#4199]
**Environment**
 - OS: Windows
 - scrcpy version: scrcpy-win64-v2.1.1.zip
 - installation method: Windows release
 - device model: Xiaomi 13
 - Android version: 13

I see the phone on the computer screen, but I have no input from keyboard or mouse.
I also activated this option and then rebooted:
``` 
USB debugging (Security settings)
    Allow granting permissions and simulating input via USB debugging
```

At any keystroke or mouse click I get this in the console:
```[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:225)
        at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:236)
        at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:240)
        at com.genymobile.scrcpy.Controller.injectKeycode(Controller.java:188)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:128)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 11 more
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:225)
        at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:236)
        at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:240)
        at com.genymobile.scrcpy.Controller.injectKeycode(Controller.java:188)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:128)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 11 more```

**Comment by rom1v** [comment]
> I also activated this option and then rebooted:
> USB debugging (Security settings)
>    Allow granting permissions and simulating input via USB debugging

This should be sufficient to make it work on Xiaomi phones. This is a Xiaomi-specific restriction.

**Comment by Riko01010** [comment]
I had same problem with my Xioami. I've activated "Usb debugging (Security setting)" in the Developer options and it is okay right now.

**Comment by ags1234** [comment]
@Riko01010 Following your reply, I just looked at "Usb debugging (Security setting)"
and saw it is disabled. When I try to open it, it says "Sign in with your Mi Account".
This is lame from Xiaomi :(
