### ISSUE TITLE
Device Disconnected

### ISSUE THREAD

**Issue by FinnyJokes** [Genymobile/scrcpy#4222]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 22.04.2 LTS
 - scrcpy version: 2.1.1 - installation method: $ sudo apt install scrcpy
 - device model: Nokia 100X TA-1399
 - Android version: Android 11 04US_1_650

**Describe the bug**
Returning "ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException.

I'm not sure of what this exactly means, but I will paste the terminal output.

On errors, please provide the output of the console (and `adb logcat` if relevant).

I type scrcpy, and I receive this:

```
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
/usr/share/scrcpy/scrcpy-server: 1 fil...shed. 2.6 MB/s (39473 bytes in 0.014s)
[server] INFO: Device: HMD Global Nokia X100 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2400
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2127)
	at android.media.MediaCodec.configure(MediaCodec.java:2043)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
WARN: Killing the server...
```
I have gone ahead and done adb kill-server and tried again. I have verified/reinstalled the program. I just updated my phone, nothing is working fully.
If anyone knows anything about this, please let me know. I'm probably doing something wrong, but who knows... I have tried everything!

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
> scrcpy 1.21

Uninstall the package from your distribution so that you use 2.1.1.
