### ISSUE TITLE
Connect Android14 occure [Pending dequeue output buffer request cancelled]

### ISSUE THREAD

**Issue by jacksonhou** [Genymobile/scrcpy#4265]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 2.1.1
 - installation method: Windows release.
 - device model: scrcpy
 - Android version: 14

**Describe the bug**
when i connect a android 14 device , it occure the error message,[Pending dequeue output buffer request cancelled]

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.
![image](https://github.com/Genymobile/scrcpy/assets/4811022/90b1a7ff-b793-40b4-9bd3-3d3a8db89a77)

**Comment by danyanp** [comment]
I think you and I have the same problem on `Android 14`，I get server debug log on  `Android 14` 
```
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  abd247fad010dd11                device  XXXXX
DEBUG: Device serial: abd247fad010dd11
DEBUG: Using server: /usr/local/share/scrcpy/scrcpy-server
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 8.4 MB/s (56995 bytes in 0.006s)
[server] INFO: Device: [XXXXX] XXXXX XXXXX (Android 14)
[server] DEBUG: Using audio encoder: 'c2.android.opus.encoder'
[server] DEBUG: Using video encoder: 'c2.mtk.avc.encoder'
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: opengl
INFO: OpenGL version: 3.3 (Compatibility Profile) Mesa 20.0.8
INFO: Trilinear filtering enabled
DEBUG: Using icon: /usr/local/share/icons/hicolor/256x256/apps/scrcpy.png
DEBUG: Demuxer 'video': starting thread
DEBUG: Demuxer 'audio': starting thread
INFO: Texture: 720x1608
DEBUG: Could not set thread priority: setpriority() failed
DEBUG: Could not set thread priority: setpriority() failed
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
[server] ERROR: Encoding error: java.lang.IllegalStateException: Pending dequeue output buffer request cancelled

[server] INFO: Retrying with -m1600...
[server] INFO: Retrying...
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
[server] ERROR: Encoding error: java.lang.IllegalStateException: Pending dequeue output buffer request cancelled

[server] INFO: Retrying with -m1280...
[server] INFO: Retrying...
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
[server] ERROR: Encoding error: java.lang.IllegalStateException: 
[server] INFO: Retrying with -m1024...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: Pending dequeue output buffer request cancelled

[server] INFO: Retrying with -m800...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: Pending dequeue output buffer request cancelled

[server] DEBUG: Screen streaming stopped
[server] DEBUG: Device message sender stopped
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.IllegalStateException: Pending dequeue output buffer request cancelled

	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3741)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:184)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:105)
	at com.genymobile.scrcpy.ScreenEncoder.lambda$start$0$com-genymobile-scrcpy-ScreenEncoder(ScreenEncoder.java:294)
	at com.genymobile.scrcpy.ScreenEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
[server] DEBUG: Audio encoder stopped
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples
^CDEBUG: Server disconnected
DEBUG: Server terminated
DEBUG: User requested to quit
DEBUG: quit...
DEBUG: Demuxer 'video': end of frames
DEBUG: Demuxer 'audio': end of frames
DEBUG: Receiver stopped
```

**Comment by rom1v** [comment]
Which device?

**Comment by danyanp** [comment]
> Which device?

Hello, this MTK development board based on Android14

**Comment by danyanp** [comment]
Burning new verison Software to the machine，have solved the problem

**Comment by I-hate-2FA** [comment]
i also have same issue, device is lineage21 GSI version (android14)

**Comment by truebit** [comment]
Moto G04S Android 14 got the same issue。I found the solution, which should work for all :

```bash
### list encoders and find the `hw` encoder:
scrcpy  --list-encoders
### use hw video encoder to play
scrcpy --video-codec=h265 --video-encoder=OMX.MTK.VIDEO.ENCODER.HEVC --no-audio
```
