### ISSUE TITLE
Android 14 - NoSuchMethodException android.content.IClipboard.addPrimaryClipChangedListener

### ISSUE THREAD

**Issue by AlexBurdu** [Genymobile/scrcpy#4285]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:  Ubuntu 22.04.3 LTS (6.2.0-26-generic)
 - scrcpy version: 1.24
 - installation method: manual build
 - device model: Pixel 6
 - Android version: 14

**Describe the bug**
Updated OS to Android 14 and the following errors are showing up after starting scrcpy. I can no longer interact with the device.

Linux output:
```
╰─➤  scrcpy                                                                                                                        130 ↵
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 254.6 MB/s (41159 bytes in 0.000s)
[server] INFO: Device: Google Pixel 6 (Android 14)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.3.0-devel
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2400
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
	at com.genymobile.scrcpy.Device.<init>(Device.java:103)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:65)
	at com.genymobile.scrcpy.Server.main(Server.java:335)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: Exception on thread Thread[Thread-2,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:65)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
	at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:206)
	at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:210)
	at com.genymobile.scrcpy.Controller.pressBackOrTurnScreenOn(Controller.java:264)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:108)
	at com.genymobile.scrcpy.Controller.control(Controller.java:75)
	at com.genymobile.scrcpy.Server$3.run(Server.java:133)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:62)
	... 8 more
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:207)
	at android.hardware.input.InputManager.getInstance(InputManager.java:271)
	... 10 more

```

Logcat output:

```
2023-09-09 10:32:51.390 32728-32728 ziparchive              app_process                          W  Unable to open '/data/local/tmp/scrcpy-server.dm': No such file or directory
2023-09-09 10:32:51.419 32728-32728 AndroidRuntime          app_process                          D  Calling main entry com.genymobile.scrcpy.Server
2023-09-09 10:32:51.420 32728-32728 scrcpy                  app_process                          I  Device: Google Pixel 6 (Android 14)
2023-09-09 10:32:51.427 32728-32728 scrcpy                  app_process                          E  Could not invoke method
                                                                                                    java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
                                                                                                    	at java.lang.Class.getMethod(Class.java:2937)
                                                                                                    	at java.lang.Class.getMethod(Class.java:2449)
                                                                                                    	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
                                                                                                    	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
                                                                                                    	at com.genymobile.scrcpy.Device.<init>(Device.java:103)
                                                                                                    	at com.genymobile.scrcpy.Server.scrcpy(Server.java:65)
                                                                                                    	at com.genymobile.scrcpy.Server.main(Server.java:335)
                                                                                                    	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

**Comment by rom1v** [comment]
> scrcpy version: 1.24

Use the latest version (currently v2.1.1). See #3784.

**Comment by AlexBurdu** [comment]
Apologies, I thought I had it updated. Issue is fixed on latest.
