### ISSUE TITLE
Iam getting the following error using windows 10 with USB huawei nova 3i, please help

### ISSUE THREAD

**Issue by Farman2019** [Genymobile/scrcpy#429]
```
scrcpy-server.jar: 1 file pushed. 1.2 MB/s (19346 bytes in 0.016s)
ERROR: Could not open video stream
ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1956)
        at android.media.MediaCodec.configure(MediaCodec.java:1885)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:158)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:68)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:28)
        at com.genymobile.scrcpy.Server.main(Server.java:110)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:316)
Exit due to uncaughtException in main thread:
INFO: Initial texture: 1080x2336
Press any key to continue...
```

**Comment by rom1v** [comment]
Does it work better with a lower definition?

    scrcpy -m1024

**Comment by Farman2019** [comment]
Very good Idea! It started but how to start it in full screen , bcz this is the big deference that you will find in SCRCPY i want to mirror through full PC screen

> Does it work better with a lower definition?
> 
> ```
> scrcpy -m1024
> ```
Very good Idea! It started but how to start it in full screen , bcz this is the big deference that you will find in SCRCPY i want to mirror through full PC screen

**Comment by rom1v** [comment]
First, you should find the highest definition your device supports. Try increasing the value passed to `-m` until it fails.

Then, you can start in fullscreen with `-f`:

    scrcpy -m1200 -f

Alternatively (or in addition), you can switch fullscreen mode with Ctrl+f.

**Comment by Farman2019** [comment]
many thanks for quick replay, really i want to mirror in expanded screen I mean full screen of my Pc which is 1366 *768 so I can play games and screen record over wide screen of my phone how to do that ?

**Comment by DamianWalkerStrauss** [comment]
> Does it work better with a lower definition?
> 
> ```
> scrcpy -m1024
> ```

Sorry, I don't know how to change that values.... I just double clicked scrcpy.exe on Windows 10.

**Comment by rom1v** [comment]
@DamianWalkerStrauss #385
