### ISSUE TITLE
[Android 14_Google_Pixel] Can't control the device screen

### ISSUE THREAD

**Issue by Raghavendra617** [Genymobile/scrcpy#4342]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: v2.0
 - installation method: Manual
 - device model: Google Pixel 7a
 - Android version: 14

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
> scrcpy version: v2.0

Use 2.1.1.

**Comment by David-Gurevich** [comment]
#3927 This is a known issue. 
Version 2.1.1 does not address this sadly.

**Comment by rom1v** [comment]
No, it's possible to control the device with keyboard and mouse in Android 14 with scrcpy 2.1.1. What does not work is "turn screen off".

**Comment by hooligeek** [comment]
I can confirm after updating to android 14 today on my pixel 5, the screen no longer turns off and I have a new error in the terminal.

```
C:\scrcpy>myscrcpy.bat
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)        0C101FDD4003AV            device  Pixel_5
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 80.5 MB/s (56995 bytes in 0.001s)
[server] INFO: Device: [Google] google Pixel 5 (Android 14)
INFO: Renderer: direct3d
INFO: Texture: 108[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getPhysicalDisplayIds []
0       at java.lang.Class.getMethod(Class.java:2937)
x2336
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetPhysicalDisplayIdsMethod(SurfaceControl.java:137)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getPhysicalDisplayIds(SurfaceControl.java:144)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:319)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:169)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Could not get physical display ids
```

**Comment by That1GuyTy** [comment]
> I can confirm after updating to android 14 today on my pixel 5, the screen no longer turns off and I have a new error in the terminal.
> 
> `C:\scrcpy\scrcpy --window-title=hooligeek --turn-screen-off --stay-awake --window-x=1 --window-y=31 --window-height=1008`
> 
> ```
> C:\scrcpy>myscrcpy.bat
> scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
> INFO: ADB device found:
> INFO:     -->   (usb)        0C101FDD4003AV            device  Pixel_5
> C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 80.5 MB/s (56995 bytes in 0.001s)
> [server] INFO: Device: [Google] google Pixel 5 (Android 14)
> INFO: Renderer: direct3d
> INFO: Texture: 108[server] ERROR: Could not invoke method
> java.lang.NoSuchMethodException: android.view.SurfaceControl.getPhysicalDisplayIds []
> 0       at java.lang.Class.getMethod(Class.java:2937)
> x2336
>         at java.lang.Class.getMethod(Class.java:2449)
>         at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetPhysicalDisplayIdsMethod(SurfaceControl.java:137)
>         at com.genymobile.scrcpy.wrappers.SurfaceControl.getPhysicalDisplayIds(SurfaceControl.java:144)
>         at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:319)
>         at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:169)
>         at com.genymobile.scrcpy.Controller.control(Controller.java:83)
>         at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
>         at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
>         at java.lang.Thread.run(Thread.java:1012)
> [server] ERROR: Could not get physical display ids
> ```
> 
> Terminal output prior to OS update
> 
> ```
> C:\scrcpy>myscrcpy.bat
> scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
> INFO: ADB device found:
> INFO:     -->   (usb)        0C101FDD4003AV            device  Pixel_5
> C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 80.7 MB/s (56995 bytes in 0.001s)
> [server] INFO: Device: [Google] google Pixel 5 (Android 13)
> INFO: Renderer: direct3d
> INFO: Texture: 1080x2336
> [server] INFO: Device screen turned off
> ```

I get the same error in console when trying to turn the screen off on my pixel 7 pro with Android 14

**Comment by Lpptrex** [comment]
Can confirm that controlling the device with mouse and keyboard does not work on Pixel 8 pro with android 14

**Comment by rom1v** [comment]
Which scrcpy version?

**Comment by Lpptrex** [comment]
2.0
