### ISSUE TITLE
Screen no longer shuts off on Pixel 6 Android 14.

### ISSUE THREAD

**Issue by AlexS2412** [Genymobile/scrcpy#4398]
- [X ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [windows 11]
 - scrcpy version: [2.2]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model: Pixel 6 (oriole)
 - Android version: 14

**Describe the bug**
For some strange reason the lock screen is black on android 14 as well as the screen no longer being able to shut off.

```
[server] INFO: Device: [Google] google Pixel 6 (Android 14)
INFO: Renderer: direct3d
INFO: Textu[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getPhysicalDisplayIds []
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
r       at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetPhysicalDisplayIdsMethod(SurfaceControl.java:137)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getPhysicalDisplayIds(SurfaceControl.java:144)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:319)
e: 1    at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:169)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Could not get physical display ids
080x2400
```

**Comment by rom1v** [comment]
#3927
