### ISSUE TITLE
v4l2 with camera doesn't work

### ISSUE THREAD

**Issue by pi-maaster77** [Genymobile/scrcpy#4400]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Debian 12]
 - scrcpy version: [v2.2]
 - installation method: [build]
 - device model: SM-A045M
 - Android version: [13]

**Description**
I don't know if this is a bug, but it feels like it is. Basically when i try to transmit the video from the camera to the virtual webcam doesn't work.
if this isn't a bug, it will be grate to have this option in the program because opens doors to don't need to use propietary software to do this things

```
$ scrcpy --v4l2-sink=/dev/video0 --video-source=camera
scrcpy v2.2 <https://github.com/Genymobile/scrcpy>
INFO: Video orientation is locked for v4l2 sink. See --lock-video-orientation.
INFO: Camera video source: control disabled
INFO: Camera video source: microphone audio source selected
INFO: ADB device found:
INFO:     -->   (usb)  R9MW7012V5M                     device  SM_A045M
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 7.5 MB/s (64363 bytes in 0.008s)
[server] INFO: Device: [samsung] samsung SM-A045M (Android 13)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.3.6
INFO: Trilinear filtering enabled
[server] INFO: Using camera '0'
INFO: v4l2 sink started to device: /dev/video0
INFO: Texture: 4096x3072
[server] ERROR: Encoding error: java.lang.IllegalArgumentException: null
[server] ERROR: Exception on thread Thread[video,5,main]
WARN: Device disconnected
java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2214)
	at android.media.MediaCodec.configure(MediaCodec.java:2130)
	at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:69)
	at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
	at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)

```

thanks for the read and congrats for the release.

**Comment by rom1v** [comment]
> 4096x3072

Maybe your device encoder does not support this resolution. Try with a lower resolution.

**Comment by pi-maaster77** [comment]
yep, was that. thankes
