### ISSUE TITLE
ERROR: Exception on thread Thread[main,5,main]

### ISSUE THREAD

**Issue by DamianWalkerStrauss** [Genymobile/scrcpy#445]
I have this message and then nothing happens.
I'm running v1.7 both 32 and 64 bits. 
I'm using Android 8.1

```
scrcpy-server.jar: 1 file pushed. 2.7 MB/s (19346 bytes in 0.007s)
ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1956)
        at android.media.MediaCodec.configure(MediaCodec.java:1885)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:158)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:68)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:28)
        at com.genymobile.scrcpy.Server.main(Server.java:110)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:316)
Exit due to uncaughtException in main thread:
ERROR: Could not open video stream
INFO: Initial texture: 1080x2336
WARN: Cannot terminate server
Press any key to continue...
```

**Comment by DamianWalkerStrauss** [comment]
OK, Solved, don't worry.
Just went in the CMD to the folder where scrcpy is unziped, then use this:
scrcpy -m 1080
and it works!!!

**Comment by ImAlipay** [comment]
very good!it works

**Comment by Labohkip81** [comment]
Thanks much you saved on me. It works perfect.

**Comment by jimmyalvarezcalderon** [comment]
Why it happened?

**Comment by rom1v** [comment]
@jimmyalvarezcalderon https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream

**Comment by drbeco** [comment]
Thanks to @DamianWalkerStrauss 's answer, I was able to make this last error of a series of errors go away.

IMHO this issue should not be closed just based on the readme note, since when we google we end up here.

The server error is not clear.

```
% scrcpy
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 0.6 MB/s (24773 bytes in 0.037s)
INFO: Initial texture: 1080x2160
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
WARN: Device disconnected
```

This doesn't give much clues and we end up googling the error and reading the answer here.

Maybe a simple message like:

```
% scrcpy
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 0.6 MB/s (24773 bytes in 0.037s)
INFO: Initial texture: 1080x2160
INFO: If this screen don't work, try with '-m 1080' or another lower resolution
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
WARN: Device disconnected
```

Just that would prevent a lot of frustration. 

Thanks for this great software. Really enjoy it now after days of builds and apts and snaps and deb packages until I got it working.

**Comment by rom1v** [comment]
> This doesn't give much clues and we end up googling the error and reading the answer here.
>
> Maybe a simple message like:
> …

This is already what scrcpy does: https://github.com/Genymobile/scrcpy/commit/8a694a97855333849976bea5e558eaa45add0168

This problem is that the error code can only be read since API 23 (Android 6), and I guess your device is API 21 (Android 5), so it can't know which exact error it is.

**Comment by RyzenPRO** [comment]
> 
> 
> OK, Solved, don't worry.
> Just went in the CMD to the folder where scrcpy is unziped, then use this:
> scrcpy -m 1080
> and it works!!!

what did you just do??? howd you apply the scrcpy -m1080??? i want to set mine in 720p 60fps

**Comment by LuffysMan** [comment]
Thanks, it works. My enviroment is ubuntu18.04, redmi note9. I installed scrcpy by command ```sudo snap install scrcpy```

**Comment by RashadTanjim** [comment]
Go to settings of Android Studio -> ADB Wi-Fi -> then in Command-line flags Write: `--max-size 1080 --always-on-top --show-touches`

**Comment by Shaunak54323** [comment]
How do i increase the quality of mirroring ?

**Comment by RashadTanjim** [comment]
--max-size 1080...change 1080 to your desired value

**Comment by iseplutpinur** [comment]
scrcpy -m 1920

**Comment by rnzbndcto** [comment]
[server] INFO: Device: Xiaomi M2101K7AG (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:114)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:95)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)






help me pls

**Comment by rom1v** [comment]
1. use the latest scrcpy version
2. if it still happens, it's #3051

**Comment by thydudes** [comment]
scrcpy
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 3.3 MB/s (24773 bytes in 0.007s)
INFO: Initial texture: 1080x2400
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:178)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:70)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:378)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 6 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3370)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2344)
	... 8 more
someone pls hlp

**Comment by rom1v** [comment]
Android 12 resuires scrcpy >= 1.18.

**Comment by thydudes** [comment]
> Android 12 resuires scrcpy >= 1.18.

How to upgrade?

**Comment by rom1v** [comment]
I guess you are using an old version of Ubuntu.

In that case, uninstall the package from the distribution, and install manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple
(you might need to use a newer version of meson than the one from the distro too, so `sudo pip3 install meson`)

**Comment by thydudes** [comment]
> I guess you are using an old version of Ubuntu.
> 
> In that case, uninstall the package from the distribution, and install manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple
> (you might need to use a newer version of meson than the one from the distro too, so `sudo pip3 install meson`)

I have the latest version, tried to put the command andit didn't worked says its unknown command, I had read about this command and it's not my case I got the Ubuntu lince 20.04.4 LTS

**Comment by rom1v** [comment]
> tried to put the command andit didn't worked

Which command? `pip3`? You might need to install it (`sudo apt install python3-pip`).

> I have the latest version

> 20.04.4 LTS

That's very old :wink:

**Comment by thydudes** [comment]
Updated with sudo do-release-upgrade -d and then installed pip3

**Comment by pramodchhillar** [comment]
root@ubuntu:~/scrcpy-1.13# scrcpy -m 1080
INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: more than one device/emulator
ERROR: "adb push" returned with value 1

**Comment by rom1v** [comment]
First of all, v1.13 is very old. Use the latest version.

**Comment by rom1v** [comment]
What's the error in the console with scrcpy v1.24?

**Comment by rnzbndcto** [comment]
My phone is disconnecting to the scrcpy.

**Comment by rom1v** [comment]
What is the error message in the console?

**Comment by javierxio** [comment]
@rnzbndcto @rom1v @thydudes 

try to open scrcpy with a different encoder:

`scrcpy -m 1024 --encoder=OMX.google.h264.encoder`

**Comment by Gismii** [comment]
TKS 2023!

**Comment by fatemeh-mohseni-AI** [comment]
first turn usb debugging on , on your phone . 
then connect your phone to the pc with cable.  
then run scrcpy .
i had same problem on ubuntu20 with scrcpy version  2.3.1 . 
i fixed it as I described
