### ISSUE TITLE
Could not list ADB devices

### ISSUE THREAD

**Issue by gstudios2** [Genymobile/scrcpy#4453]
- [ V] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ V] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows Version 10.0.22631 build 22631

 - scrcpy version: many: 2.0 , 2.1.1 , 2.2 
 - installation method: direct download and unzipping
 - device model: 2 devices: Samsung SM-X900, Honor lld-l31
 - Android version: 2 versions: Android 13 (On samsung) , Android 9 (on Honor)

**Describe the bug**
(Only one of the 2 devices connected, never at the same time)
When I try to start scrcpy , the following message appear:
```
* daemon started successfully
ERROR: "adb devices -l" returned with value 1
ERROR: Could not list ADB devices
ERROR: Server connection failed
Premere un tasto per continuare . . .
```
It worked perfectly since 2 weeks ago. I tried with anoter laptop, and scrcpy work perfectly with both devices. Hence, I'm 99% sure that the problem comes with my Windows machine. But I have no idea on how to make further investigation. Tried to install proper device drivers, and nothing changed  

```
Please paste terminal output in a code block.
```

**Comment by rom1v** [comment]
What is the result of `adb devices -l` if you run it manually?

**Comment by gstudios2** [comment]
If you mean to just open the cmd prompt, and writing `adb devices -l`, the output is:

`"adb"in` not recognized as internal or external command ... ``

**Comment by rom1v** [comment]
Double click on `open_a_terminal_here.bat` in the scrcpy folder, and try again (the `adb.exe` executable is there).

**Comment by gstudios2** [comment]
ok, thanks for your help: 

The output is:
`
adb server version (40) doesn't match this client (41); killing...
* daemon started successfully
List of devices attached
R52T101X9YE            device product:gts8uwifieea model:SM_X900 device:gts8uwifi transport_id:1`

`

**Comment by rom1v** [comment]
> adb server version (40) doesn't match this client (41); killing...

That's the problem, you have a program on your computer running another adb version.

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#conflicts-between-adb-versions

**Comment by gstudios2** [comment]
How can I check which program is?

**Comment by Dtrieb** [comment]
Same here:

```
INFO:     -->   (usb)        xxx            device  Pixel_7_Pro
C:\Program Files\Scrcpy-Launcher\bin\scrcpy\scrcpy-server:... file pushed, 0 skipped. 35.2 MB/s (52867 bytes in 0.001s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: The server version (2.0) does not match the client (2.3)
        at com.genymobile.scrcpy.Server.createOptions(Server.java:172)
        at com.genymobile.scrcpy.Server.main(Server.java:360)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
ERROR: Server connection failed
```

Try to:

`set ADB=C:\Program Files\Scrcpy-Launcher\bin\scrcpy\adb.exe`

but didn't work.

**Comment by rom1v** [comment]
Remove your ADB variable completely if you use the Windows release.
