### ISSUE TITLE
Server version different

### ISSUE THREAD

**Issue by Dtrieb** [Genymobile/scrcpy#4470]
Same here:

```
INFO:     -->   (usb)        xxx            device  Pixel_7_Pro
C:\Program Files\Scrcpy-Launcher\bin\scrcpy\scrcpy-server:... file pushed, 0 skipped. 35.2 MB/s (52867 bytes in 0.001s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: The server version (2.0) does not match the client (2.3)
        at com.genymobile.scrcpy.Server.createOptions(Server.java:172)
        at com.genymobile.scrcpy.Server.main(Server.java:360)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
ERROR: Server connection failed
```

Try to:

`set ADB=C:\Program Files\Scrcpy-Launcher\bin\scrcpy\adb.exe`

but didn't work.

_Originally posted by @Dtrieb in https://github.com/Genymobile/scrcpy/issues/4453#issuecomment-1827492522_

**Comment by rom1v** [comment]
Remove your ADB variable completely if you use the Windows release.

**Comment by Dtrieb** [comment]
> Remove your ADB variable completely if you use the Windows release.

Yes I do it under Windows, but did't work for me.

**Comment by rom1v** [comment]
Extract the zip, then double-click on `scrcpy-console.bat`, what happens?

**Comment by Dtrieb** [comment]
```
scrcpy 2.3 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)        xxx            device  Pixel_7_Pro
C:\Program Files\Scrcpy-Launcher\bin\scrcpy\scrcpy-server:... file pushed, 0 skipped. 57.6 MB/s (52867 bytes in 0.001s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: The server version (2.0) does not match the client (2.3)
        at com.genymobile.scrcpy.Server.createOptions(Server.java:172)
        at com.genymobile.scrcpy.Server.main(Server.java:360)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
ERROR: Server connection failed
Press Enter to continue...
```

**Comment by Dtrieb** [comment]
![SystemPropertiesAdvanced_2023-11-27_11-08-08](https://github.com/Genymobile/scrcpy/assets/3650284/67927976-c3cc-4656-bc31-227ee8017df3)

**Comment by rom1v** [comment]
Double-click on `open_a_terminal_here.bat`, type `echo %ADB%`.

**Comment by Dtrieb** [comment]
Microsoft Windows [Version 10.0.19045.3693]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>echo %ADB%
%ADB%

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>

**Comment by rom1v** [comment]
From there, what is the result of:

```
certUtil -hashfile scrcpy-server SHA256
```

**Comment by Dtrieb** [comment]
```
C:\Program Files\Scrcpy-Launcher\bin\scrcpy>certUtil -hashfile scrcpy-server SHA256
SHA256-Hash von scrcpy-server:
8daed514d7796fca6987dc973e201bd15ba51d0f7258973dec92d9ded00dbd5f
CertUtil: -hashfile-Befehl wurde erfolgreich ausgeführt.

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>
```

**Comment by rom1v** [comment]
Plug your device, and execute:

```
adb shell ls -l /data/local/tmp
adb shell sha256sum /data/local/tmp/scrcpy-server.jar
```

**Comment by Dtrieb** [comment]
```
C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell ls -l /data/local/tmp
adb shell sha256sum /data/local/tmp/scrcpy-server.jartotal 52
-rw-rw-rw- 1 shell shell 52867 2023-03-12 02:13 scrcpy-server.jar

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>
```

**Comment by rom1v** [comment]
(in two separate commands)

**Comment by Dtrieb** [comment]
```
C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell ls -l /data/local/tmp
total 52
-rw-rw-rw- 1 shell shell 52867 2023-03-12 02:13 scrcpy-server.jar

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell sha256sum /data/local/tmp/scrcpy-server.jar
9e241615f578cd690bb43311000debdecf6a9c50a7082b001952f18f6f21ddc2  /data/local/tmp/scrcpy-server.jar

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>
```

**Comment by Dtrieb** [comment]
```
C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb push scrcpy-server /data/local/tmp/scrcpy-server.jar
scrcpy-server: 1 file pushed, 0 skipped. 45.2 MB/s (52867 bytes in 0.001s)

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell ls -l /data/local/tmp
total 52
-rw-rw-rw- 1 shell shell 52867 2023-03-12 02:13 scrcpy-server.jar

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell sha256sum /data/local/tmp/scrcpy-server.jar
9e241615f578cd690bb43311000debdecf6a9c50a7082b001952f18f6f21ddc2  /data/local/tmp/scrcpy-server.jar

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>
```

**Comment by rom1v** [comment]
OK so there is a bug with `adb push`, it should overwrte the file.

Could you test with scrcpy v2.2, please?

**Comment by Dtrieb** [comment]
```
C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb push scrcpy-server /data/local/tmp/scrcpy-server.jar
scrcpy-server: 1 file pushed, 0 skipped. 61.5 MB/s (52867 bytes in 0.001s)

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell ls -l /data/local/tmp
total 52
-rw-rw-rw- 1 shell shell 52867 2023-03-12 02:13 scrcpy-server.jar

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell sha256sum /data/local/tmp/scrcpy-server.jar
9e241615f578cd690bb43311000debdecf6a9c50a7082b001952f18f6f21ddc2  /data/local/tmp/scrcpy-server.jar

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>
```

Windows 10 Home

**Comment by rom1v** [comment]
OK, I can't explain why it does not replace your file.

What are the permissions on `data/local/tmp`?

```
adb shell ls -ld /data/local/tmp
```

Move the file on the device (do not delete it, that will allow to make more tests later) and retry scrcpy:

```
adb shell mv /data/local/tmp/scrcpy-server.jar /data/local/tmp/scrcpy-server.jar.bak
```

**Comment by Dtrieb** [comment]
```
C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell ls -ld /data/local/tmp
drwxrwx--x 2 shell shell 3452 2023-11-27 11:34 /data/local/tmp

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>
```

```
C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell mv /data/local/tmp/scrcpy-server.jar /data/local/tmp/scrcpy-server.jar.bak

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>
```

**Comment by rom1v** [comment]
Now run scrcpy 2.3.

**Comment by Dtrieb** [comment]
```
scrcpy 2.3 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
INFO: ADB device found:
INFO:     -->   (usb)        29221FDH3003LT            device  Pixel_7_Pro
C:\Program Files\Scrcpy-Launcher\bin\scrcpy\scrcpy-server:... file pushed, 0 skipped. 61.2 MB/s (52867 bytes in 0.001s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: The server version (2.0) does not match the client (2.3)
        at com.genymobile.scrcpy.Server.createOptions(Server.java:172)
        at com.genymobile.scrcpy.Server.main(Server.java:360)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
ERROR: Server connection failed
Press Enter to continue...
```

**Comment by rom1v** [comment]
Has your file been renamed on the device?

```
adb shell ls -l /data/local/tmp
```

**Comment by Dtrieb** [comment]
```
C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell ls -l /data/local/tmp
total 104
-rw-rw-rw- 1 shell shell 52867 2023-03-12 02:13 scrcpy-server.jar
-rw-rw-rw- 1 shell shell 52867 2023-03-12 02:13 scrcpy-server.jar.bak

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>
```

**Comment by rom1v** [comment]
Let's try to remove it, repush, and check everything at each step (one command per line):
```
adb shell rm /data/local/tmp/scrcpy-server.jar
adb shell ls -l /data/local/tmp
certUtil -hashfile scrcpy-server SHA256
adb push scrcpy-server /data/local/tmp/scrcpy-server.jar
adb shell ls -l /data/local/tmp
adb shell sha256sum /data/local/tmp/scrcpy-server.jar
```

**Comment by Dtrieb** [comment]
```
C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell ls -l /data/local/tmp
total 104
-rw-rw-rw- 1 shell shell 52867 2023-03-12 02:13 scrcpy-server.jar
-rw-rw-rw- 1 shell shell 52867 2023-03-12 02:13 scrcpy-server.jar.bak

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell ls -l /data/local/tmp
* daemon not running; starting now at tcp:5037
* daemon started successfully
total 104
-rw-rw-rw- 1 shell shell 52867 2023-03-12 02:13 scrcpy-server.jar
-rw-rw-rw- 1 shell shell 52867 2023-03-12 02:13 scrcpy-server.jar.bak

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell rm /data/local/tmp/scrcpy-server.jar

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell ls -l /data/local/tmp
total 52
-rw-rw-rw- 1 shell shell 52867 2023-03-12 02:13 scrcpy-server.jar.bak

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>certUtil -hashfile scrcpy-server SHA256
SHA256-Hash von scrcpy-server:
8daed514d7796fca6987dc973e201bd15ba51d0f7258973dec92d9ded00dbd5f
CertUtil: -hashfile-Befehl wurde erfolgreich ausgeführt.

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb push scrcpy-server /data/local/tmp/scrcpy-server.jar
scrcpy-server: 1 file pushed, 0 skipped. 44.2 MB/s (52867 bytes in 0.001s)

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell ls -l /data/local/tmp
total 104
-rw-rw-rw- 1 shell shell 52867 2023-03-12 02:13 scrcpy-server.jar
-rw-rw-rw- 1 shell shell 52867 2023-03-12 02:13 scrcpy-server.jar.bak

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>adb shell sha256sum /data/local/tmp/scrcpy-server.jar
9e241615f578cd690bb43311000debdecf6a9c50a7082b001952f18f6f21ddc2  /data/local/tmp/scrcpy-server.jar

C:\Program Files\Scrcpy-Launcher\bin\scrcpy>
```

**Comment by Dtrieb** [comment]
(Any possibily that you look remote? or write per chat?)

**Comment by rom1v** [comment]
The behavior is very strange:
 - you have a local file, `scrcpy-server`, which is the one from scrcpy 2.3
 - you `adb push` it
 - on your device, it writes the `scrcpy-server` from scrcpy 2.0 (where does it come from?)

It makes no sense. :thinking:

**Comment by rom1v** [comment]
```
adb push scrcpy-server /data/local/tmp/abc
adb shell ls -l /data/local/tmp
adb shell sha256sum /data/local/tmp/abc
```

**Comment by Dtrieb** [comment]
I install my Programm "[Scrcpy-Launcher](https://schlapa.net/downloads/scrcpy-launcher/)" on other Folder (without **-** ) and now it works.

**Comment by lorefield** [comment]
I had this same issue but on Linux.. however I seem to have found the cause (which likely is what happens on Windows as well)! The install_release.sh in the scrcyp-2.3 source code package has a line "PREBUILT_SERVER_URL=https://github.com/Genymobile/scrcpy/releases/download/v2.2/scrcpy-server-v2.2" (Trying to change the numbers in the script failed of course.. the SHA256 hash in the script is for scrcpy-server-v2.2 not scrcpy-server-v2.3)

![scrcpy](https://github.com/Genymobile/scrcpy/assets/18152829/618a1bfc-066d-4e30-a8ab-f68aeb873faf)

**Comment by rom1v** [comment]
@lorefield https://github.com/Genymobile/scrcpy/issues/4098#issuecomment-1600332180
