### ISSUE TITLE
scrcpy not working after updating to v2.3

### ISSUE THREAD

**Issue by moe7863** [Genymobile/scrcpy#4474]
- OS: Windows
 - scrcpy version: v2.3
 - installation method: Windows release
 - device model: Samsung 23+ (SM_S916B)
 - Android version: 14

Presented with error when attempting to run scrcpy. Worked fine with v2.2 and previous versions. 

```
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:85)
        at com.genymobile.scrcpy.ScreenCapture.createDisplay(ScreenCapture.java:77)
        at com.genymobile.scrcpy.ScreenCapture.start(ScreenCapture.java:38)
        at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:72)
        at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
        at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
        ... 6 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.app.ConfigurationController.getConfiguration()' on a null object reference
        at android.app.ActivityThread.getConfiguration(ActivityThread.java:3899)
        at android.hardware.display.DisplayManagerGlobal.getDisplayInfoLocked(DisplayManagerGlobal.java:260)
        at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:234)
        at android.hardware.display.DisplayManagerGlobal.getCompatibleDisplay(DisplayManagerGlobal.java:364)
        at android.hardware.display.DisplayManagerGlobal.getRealDisplay(DisplayManagerGlobal.java:397)
        at android.hardware.display.DisplayManagerGlobal.createVirtualDisplayWrapper(DisplayManagerGlobal.java:779)
        at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:2088)
        at android.view.SurfaceControl.createDisplay(SurfaceControl.java:2480)
        ... 8 more
INFO: Renderer: direct3d
ERROR: Demuxer 'audio': stream disabled due to connection error
INFO: Texture: 1080x2336
WARN: Device disconnected
```

**Comment by rom1v** [comment]
Thank you for your report. See #4467.
