### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by ags1234** [Genymobile/scrcpy#4483]
**Environment**
 - OS: Windows
 - scrcpy version: 2.3
 - installation method: unpacked from scrcpy-win64-v2.3.zip
 - device model: Samsung Galaxy S32  SM-S911W
 - Android version: 14

I changed my phone from OnePlus 5 (which worked perfectly) to S23 and now I have the error below. USB Debugging is correctly set and active.

Output from scrcpy-console.bat:
scrcpy 2.3 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)           ############            device  SM_S911W
c:\tmp\scrcpy-win64-v2.3\scrcpy-server: 1 file pushed, 0 skipped. 68.9 MB/s (65851 bytes in 0.001s)
[server] INFO: Device: [samsung] samsung SM-S911W (Android 14)
INFO: Renderer: direct3d
INFO: Texture: 1080x2336
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:85)
        at com.genymobile.scrcpy.ScreenCapture.createDisplay(ScreenCapture.java:77)
        at com.genymobile.scrcpy.ScreenCapture.start(ScreenCapture.java:38)
        at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:72)
        at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
        at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
        ... 6 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.app.ConfigurationController.getConfiguration()' on a null object reference
        at android.app.ActivityThread.getConfiguration(ActivityThread.java:3899)
        at android.hardware.display.DisplayManagerGlobal.getDisplayInfoLocked(DisplayManagerGlobal.java:260)
        at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:234)
        at android.hardware.display.DisplayManagerGlobal.getCompatibleDisplay(DisplayManagerGlobal.java:364)
        at android.hardware.display.DisplayManagerGlobal.getRealDisplay(DisplayManagerGlobal.java:397)
        at android.hardware.display.DisplayManagerGlobal.createVirtualDisplayWrapper(DisplayManagerGlobal.java:779)
        at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:2088)
        at android.view.SurfaceControl.createDisplay(SurfaceControl.java:2480)
        ... 8 more
WARN: Device disconnected
ERROR: Demuxer 'audio': stream disabled due to connection error
Press Enter to continue...

**Comment by rom1v** [comment]
See #4467 for the fix.
