### ISSUE TITLE
Audio and clipboard not working on IQOO 11 FuntouchOS 14

### ISSUE THREAD

**Issue by Najihh** [Genymobile/scrcpy#4492]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 64Bit
 - scrcpy version: 2.3.1
 - installation method: Windows release
 - device model: IQOO 11
 - Android version: 14

**Describe the bug**
After Updating IQOO Firmware to FuntouchOS 14, audio and clipboard not working

```
[server] ERROR: Failed to invoke AudioRecord.<init>.
java.lang.NoSuchMethodException: android.media.AudioRecord.native_setup [class java.lang.Object, class java.lang.Object, class [I, int, int, int, int, class [I, class android.os.Parcel, long, int]
W       at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getDeclaredMethod(Class.java:2914)
        at com.genymobile.scrcpy.Workarounds.createAudioRecord(Workarounds.java:293)
        at com.genymobile.scrcpy.AudioCapture.startRecording(AudioCapture.java:116)
A       at com.genymobile.scrcpy.AudioCapture.start(AudioCapture.java:130)
RN: Demuxer 'audio': stream explicitly disabled by the device
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:190)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:121)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.RuntimeException: Cannot create AudioRecord
        at com.genymobile.scrcpy.Workarounds.createAudioRecord(Workarounds.java:324)
        at com.genymobile.scrcpy.AudioCapture.startRecording(AudioCapture.java:116)
        at com.genymobile.scrcpy.AudioCapture.start(AudioCapture.java:130)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:190)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:121)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
```

**Comment by rom1v** [comment]
Please post your framework.jar:

```
adb pull /system/framework/framework.jar
```

**Comment by Najihh** [comment]
Here: 
[framework.zip](https://github.com/Genymobile/scrcpy/files/13539561/framework.zip)

**Comment by rom1v** [comment]
Please test with this fix: 3001f8a2d581a921920d18c088d42e0cd747bf41

Here is a binary to replace in your scrcpy 2.3.1 folder:

- [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/4492/1/scrcpy-server) <sub>`SHA-256: 8aff824b45979f5d964c20b9bd63eefe3d7f24681d485648c064ca9d68ebba3`</sub>

**Comment by Najihh** [comment]
now audio is working with this, but for the clipboard still error 

here error logs
```
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.getPrimaryClip [class java.lang.String, int, class java.lang.String]
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getGetPrimaryClipMethod(ClipboardManager.java:44)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:117)
        at com.genymobile.scrcpy.Device.getClipboardText(Device.java:286)
        at com.genymobile.scrcpy.Device$3.dispatchPrimaryClipChanged(Device.java:143)
        at android.content.IOnPrimaryClipChangedListener$Stub.onTransact(IOnPrimaryClipChangedListener.java:84)
        at android.os.Binder.execTransactInternal(Binder.java:1410)
        at android.os.Binder.execTransact(Binder.java:1341)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.getPrimaryClip [class java.lang.String, int, class java.lang.String]
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getGetPrimaryClipMethod(ClipboardManager.java:44)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:117)
        at com.genymobile.scrcpy.Device.getClipboardText(Device.java:286)
        at com.genymobile.scrcpy.Device$3.dispatchPrimaryClipChanged(Device.java:143)
        at android.content.IOnPrimaryClipChangedListener$Stub.onTransact(IOnPrimaryClipChangedListener.java:84)
        at android.os.Binder.execTransactInternal(Binder.java:1410)
        at android.os.Binder.execTransact(Binder.java:1341)
```

**Comment by rom1v** [comment]
I don't understand this one…

In `IClipboard.java`, you have:

```java
ClipData getPrimaryClip(String str, String str2, int i, int i2) throws RemoteException;
```

It should have matched https://github.com/Genymobile/scrcpy/blob/c6ff78f4147ad5505b45cce8f1d6f44c8585a9b5/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java#L41 :thinking:

**Comment by Najihh** [comment]
its working, whether true or false for that 'userOperate'
