### ISSUE TITLE
New Samsung OneUI Update 6.0 allows mirroring, but not controlling anymore

### ISSUE THREAD

**Issue by WuMaKu84** [Genymobile/scrcpy#4526]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: W10x64
 - scrcpy version: lastest
 - installation method: Windows Release
 - device model: Samsung Galaxy S22 - OneUI 6.0
 - Android version: 14

**Describe the bug**
I am able to see the screen, but trying to control it, throws the Error (see below). Mirroring still possible, I can see changes when I control the phone directly

```
[server] ERROR: Exception on thread Thread[Thread-2,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:72)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:196)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:320)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:134)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:90)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:69)
        ... 8 more
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:207)
        at android.hardware.input.InputManager.getInstance(InputManager.java:401)
        ... 10 more
```

**Comment by rom1v** [comment]
> scrcpy version: lastest

Which one precisely?

There were errors like this fixed in recent versions for Android 14.

**Comment by WuMaKu84** [comment]
Sorry -> downloaded the last available from here https://scrcpy.net/download/
https://scrcpy.net/start-download/?id=2
from which file can I see the version?

**Comment by WuMaKu84** [comment]
sorry for the noob mistake :(
downloaded the latest from GIT and works perfectly... just delete this post so noone ever has to see crap like this from me -.-

**Comment by rom1v** [comment]
> Sorry -> downloaded the last available from here > https://scrcpy.net/download/

This website is not related to the project. The only official source for scrcpy is this github.
