### ISSUE TITLE
SurfaceControl setDisplayPowerMode failed

### ISSUE THREAD

**Issue by FIX-2** [Genymobile/scrcpy#4530]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Android
 - scrcpy version: 2.3.1
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model: GOOGLE-PIXEL 5
 - Android version: 14

**Describe the bug**
2023-12-13 11:11:10,868 ERROR [scrcpy] Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getInternalDisplayToken []
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at d.b.a.g.f.d(Unknown Source:33)
	at d.b.a.g.f.c(Unknown Source:1)
	at d.c.a.a.f.b(:2)
	at d.c.a.a.n$a.run(:31)
2023-12-13 11:11:10,872 ERROR [scrcpy] Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at d.b.a.g.f.g(Unknown Source:18)
	at d.c.a.a.f.b(:2)
	at d.c.a.a.n$a.run(:31)
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:1813)
	... 4 [more](url)
[system-framework-framework.jar-SurfaceControl.txt](https://github.com/Genymobile/scrcpy/files/13668098/system-framework-framework.jar-SurfaceControl.txt)

**Comment by rom1v** [comment]
> scrcpy version: 2.3.1

Are you sure?

**Comment by FIX-2** [comment]
Sorry, I made a mistake!

**Comment by FIX-2** [comment]
> > scrcpy version: 2.3.1
> 
> Are you sure?

Sorry, I made a mistake!
