### ISSUE TITLE
scrcpy --turn-screen-off doesnst seem to work on Android 14:(

### ISSUE THREAD

**Issue by Muffinmaker2** [Genymobile/scrcpy#4534]
**Environment**
 - OS: Linux Mint Cinnamon
 - scrcpy version: newest version (1.21-1)
 - installation method: apt install scrcpy
 - device model: Samsung Galaxy s23 plus SM-S916B
 - Android version: Android 14

**Describe the bug**
So if I try starting a mirroring with my screen turned off via scrcpy --turn-screen-off. The Session starts but my Phone screen isnt turning off. I did a little searchy search in the Issue page and found a similar issue here #3927, but it was somehow fixed but its still broken i guess :(

```
$ scrcpy --turn-screen-off
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 4.3 MB/s (39473 bytes in 0.009s)
[server] INFO: Device: samsung SM-S916B (Android 14)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 2336x1080
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
	at com.genymobile.scrcpy.Device.<init>(Device.java:93)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:63)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:415)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getInternalDisplayToken []
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetBuiltInDisplayMethod(SurfaceControl.java:94)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getBuiltInDisplay(SurfaceControl.java:103)
	at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:268)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:127)
	at com.genymobile.scrcpy.Controller.control(Controller.java:73)
	at com.genymobile.scrcpy.Server$3.run(Server.java:125)
	at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Could not get built-in display
```

**Comment by rom1v** [comment]
> scrcpy version: [e.g. 1.12.1] 2.3.1

Nope:

> scrcpy 1.21 <https://github.com/Genymobile/scrcpy>

Use the latest version.

**Comment by Muffinmaker2** [comment]
> > scrcpy version: [e.g. 1.12.1] 2.3.1
> 
> Nope:
> 
> > scrcpy 1.21 https://github.com/Genymobile/scrcpy
> 
> Use the latest version.

yea i did a upsie i wrote it wrong

**Comment by rom1v** [comment]
Yes you must uninstall your package and install it as explained in: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md

**Comment by Muffinmaker2** [comment]
ok i did a fresh install, removed the version i had and now did this:
```
$ apt install scrcpy
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-5.15.0-88 linux-headers-5.15.0-88-generic linux-image-5.15.0-88-generic linux-modules-5.15.0-88-generic linux-modules-extra-5.15.0-88-generic
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  scrcpy
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 62,1 kB of archives.
After this operation, 155 kB of additional disk space will be used.
Get:1 http://ftp.halifax.rwth-aachen.de/ubuntu jammy/universe amd64 scrcpy amd64 1.21-1 [62,1 kB]
Fetched 62,1 kB in 0s (192 kB/s)  
Selecting previously unselected package scrcpy.
(Reading database ... 651399 files and directories currently installed.)
Preparing to unpack .../scrcpy_1.21-1_amd64.deb ...
Unpacking scrcpy (1.21-1) ...
Setting up scrcpy (1.21-1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) 
```
And now i have tried running the command:
```
$ scrcpy --turn-screen-off
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 6.1 MB/s (39473 bytes in 0.006s)
[server] INFO: Device: samsung SM-S916B (Android 14)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 2336x1080
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
	at com.genymobile.scrcpy.Device.<init>(Device.java:93)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:63)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:415)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getInternalDisplayToken []
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetBuiltInDisplayMethod(SurfaceControl.java:94)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getBuiltInDisplay(SurfaceControl.java:103)
	at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:268)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:127)
	at com.genymobile.scrcpy.Controller.control(Controller.java:73)
	at com.genymobile.scrcpy.Server$3.run(Server.java:125)
	at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Could not get built-in display

```

But sadly it seems to still not work:(

**Comment by rom1v** [comment]
You just reinstalled the package from your distribution. You must remove it instead:

```
adb remove scrcpy
```

Then install the latest version following these steps: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by Muffinmaker2** [comment]
> You just reinstalled the package from your distribution. You must remove it instead:
> 
> ```
> adb remove scrcpy
> ```
> 
> Then install the latest version following these steps: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

It worked :O. Turn off screen isnt broken in Android 14 and i will close this issue. Thanks for the help :)
