### ISSUE TITLE
scrcpy not working

### ISSUE THREAD

**Issue by sullian56** [Genymobile/scrcpy#4552]
- [ x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: linux mint
 - scrcpy version: 1.21
 - installation method: logitheque
 - device model: xiami redmi note 11 pro 
 - Android version: 13

**Describe the bug**
hello, 
i am a new user and not familiar at all with linux. I would like to view image/video from my phone on the computer screen.
Thanks in advance for the assistance
BR
Sullian

SCRCPY not working

```
:~$ scrcpy
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...shed. 4.4 MB/s (39473 bytes in 0.009s)
[server] INFO: Device: Xiaomi 2201116SG (Android 13)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2214)
	at android.media.MediaCodec.configure(MediaCodec.java:2130)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:366)
INFO: Renderer: opengl
INFO: OpenGL version: 4.5 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2400
WARN: Device disconnected
WARN: Killing the server...
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Your version is too old.

Uninstall the package and install the latest version manually: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by sullian56** [comment]
Thanks for the answer

Sincerely
Sullian


Le ven. 29 déc. 2023, 21:44, Romain Vimont ***@***.***> a
écrit :
