### ISSUE TITLE
Doesn't work well on redmi 13c

### ISSUE THREAD

**Issue by Kmilogr** [Genymobile/scrcpy#4561]
I used this software on my y9Prime, and it worked correctly, now that I have changed phones I want to continue using it on my Redmi 13c, but it only shares the screen, I can't use the mouse to move on the phone.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#prerequisites
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by Kmilogr** [comment]
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)      OBE6PVR4NZGUXK6P            device  23100RN82L
C:\Users\JUAN\Desktop\scrcpy-win64-v2.1.1\scrcpy-server: 1 file pushed, 0 skipped. 2.1 MB/s (56995 bytes in 0.026s)
[server] INFO: Device: [Xiaomi] Redmi 23100RN82L (Android 13)
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:225)
        at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:236)
        at com.genymobile.scrcpy.Device.pressReleaseKeycode(Device.java:244)
        at com.genymobile.scrcpy.Device.pressReleaseKeycode(Device.java:249)
        at com.genymobile.scrcpy.Controller.control(Controller.java:70)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 10 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:908)
        at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:617)
        at android.os.Binder.execTransactInternal(Binder.java:1285)
        at android.os.Binder.execTransact(Binder.java:1249)

INFO: Renderer: direct3d
INFO: Texture: 720x1600
This is the terminal, the error is Could not invoke method and I don't see the solution in the response.

**Comment by rom1v** [comment]
Did you follow the instructions I posted here: https://github.com/Genymobile/scrcpy/issues/4561#issuecomment-1876013231 ?

**Comment by Kmilogr** [comment]
If you already try it, mostly the mouse and keyboard part do not work, but it does not solve it. I updated the ADB in 3 different ways, changed the cable and used GPT chat, but I haven't found a solution, I tried with a Redmi 10, and it has the same problem, I checked my pc with a motoe20, and it works normally, something I can say is that the audio if transmitted through the PC. Since I am not a programmer, I do not know how to use cmd commands well. If you have any solution, I would greatly appreciate it.

**Comment by PyHubs** [comment]
Might be a compability issue, works on my Mi 8 perfecrly well

**Comment by Kmilogr** [comment]
It was fixed, of course. but it was fixed.
