### ISSUE TITLE
Vivo no audio forwarding WARN: Demuxer 'audio': stream explicitly disabled by the device

### ISSUE THREAD

**Issue by Lirikana** [Genymobile/scrcpy#4582]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11 22H2
 - scrcpy version: 2.3.1
 - installation method: Windows Release
 - device model: Vivo X90 Pro+
 - Android version: 14

**Describe the bug**
No audio being forwarded from the phone after the latest OS update on the phone.

```
[server] INFO: Device: [vivo] vivo V2227A (Android 14)
[server] ERROR: Failed to invoke AudioRecord.<init>.
java.lang.NoSuchMethodException: android.media.AudioRecord.native_setup [class java.lang.Object, class java.lang.Object, class [I, int, int, int, int, class [I, class android.os.Parcel, long, int]
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getDeclaredMethod(Class.java:2914)
        at com.genymobile.scrcpy.Workarounds.createAudioRecord(Workarounds.java:293)
        at com.genymobile.scrcpy.AudioCapture.startRecording(AudioCapture.java:116)
        at com.genymobile.scrcpy.AudioCapture.start(AudioCapture.java:130)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:190)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:121)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1042)
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.RuntimeException: Cannot create AudioRecord
        at com.genymobile.scrcpy.Workarounds.createAudioRecord(Workarounds.java:324)
        at com.genymobile.scrcpy.AudioCapture.startRecording(AudioCapture.java:116)
        at com.genymobile.scrcpy.AudioCapture.start(AudioCapture.java:130)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:190)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:121)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1042)
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1080x2400
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by Lirikana** [comment]
The first fix was effective for the audio issues.

**Comment by rom1v** [comment]
Could you please test if audio still works with https://github.com/Genymobile/scrcpy/pull/5154?

I would like to avoid a regression for Vivo devices with that change.
