### ISSUE TITLE
Can't use my mouse

### ISSUE THREAD

**Issue by PranaKill** [Genymobile/scrcpy#4586]
I cannot use my PC to operate the cell phone, I can only see it, but not use the Mouse.
It is a Xiaomi 11T
Someone help me?

**Comment by DARK7BEA5T** [comment]
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:226)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:230)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:323)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:138)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        
        
        
        getting error like this right?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#prerequisites
