### ISSUE TITLE
WARN: Demuxer 'audio': stream explicitly disabled by the device

### ISSUE THREAD

**Issue by DARK7BEA5T** [Genymobile/scrcpy#4588]
WARN: Demuxer 'audio': stream explicitly disabled by the device
how to fix?

**Comment by rom1v** [comment]
Which Android version? Any error message before that line?

**Comment by DARK7BEA5T** [comment]
android 14,
i just fixed it, somewhere someone told me,(at github comment) myaudio format is not woring, use acc, andthen it worked.

**Comment by dororo003** [comment]
can you explain more specifically bro, I got this problem after the update OS

**Comment by rom1v** [comment]
@dororo003 The problem that @DARK7BEA5T had was that its device does not have any OPUS encoder (the default audio format, so he had to call `scrcpy --audio-codec=aac`;

Since you got a similar problem after a system upgrade, your problem is probably not the same. What scrcpy version do you use? You should upgrade to the latest version (currently 2.3.1).

**Comment by dororo003** [comment]
@rom1v My problem has been resolved, I saw your comment on the same topic. Thank you friend

**Comment by Jasonkwong1234** [comment]
When using scrcpy --new-display=1920x1080  and  Demuxer 'audio': stream disabled due to connection error  and how to fix it android 15  on windows

**Comment by rom1v** [comment]
What's the full output in the console?

**Comment by Jasonkwong1234** [comment]
Is a pixel device

**Comment by rom1v** [comment]
Paste the whole console output here.

**Comment by Jasonkwong1234** [comment]
[server] ERROR: Could not create display
java.lang.SecurityException: Requires ADD_TRUSTED_DISPLAY permission to create a trusted virtual display.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3261)
        at android.os.Parcel.createException(Parcel.java:3245)
        at android.os.Parcel.readException(Parcel.java:3228)
        at android.os.Parcel.readException(Parcel.java:3170)
        at android.hardware.display.IDisplayManager$Stub$Proxy.createVirtualDisplay(IDisplayManager.java:1603)
        at android.hardware.display.DisplayManagerGlobal.createVirtualDisplay(DisplayManagerGlobal.java:824)
        at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:1261)
        at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:1221)
        at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:1169)
        at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:1108)
        at com.genymobile.scrcpy.wrappers.DisplayManager.createNewVirtualDisplay(DisplayManager.java:164)
        at com.genymobile.scrcpy.video.NewDisplayCapture.startNew(NewDisplayCapture.java:190)
        at com.genymobile.scrcpy.video.NewDisplayCapture.start(NewDisplayCapture.java:211)
        at com.genymobile.scrcpy.video.SurfaceEncoder.streamCapture(SurfaceEncoder.java:95)
        at com.genymobile.scrcpy.video.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-video-SurfaceEncoder(SurfaceEncoder.java:296)
        at com.genymobile.scrcpy.video.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.display.DisplayManagerService.createVirtualDisplayInternal(DisplayManagerService.java:1889)
        at com.android.server.display.DisplayManagerService.-$$Nest$mcreateVirtualDisplayInternal(DisplayManagerService.java:0)
        at com.android.server.display.DisplayManagerService$BinderService.createVirtualDisplay(DisplayManagerService.java:4758)
        at android.hardware.display.IDisplayManager$Stub.onTransact(IDisplayManager.java:819)
        at android.os.Binder.execTransactInternal(Binder.java:1406)

[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.AssertionError: Could not create display
        at com.genymobile.scrcpy.video.NewDisplayCapture.startNew(NewDisplayCapture.java:197)
        at com.genymobile.scrcpy.video.NewDisplayCapture.start(NewDisplayCapture.java:211)
        at com.genymobile.scrcpy.video.SurfaceEncoder.streamCapture(SurfaceEncoder.java:95)
        at com.genymobile.scrcpy.video.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-video-SurfaceEncoder(SurfaceEncoder.java:296)
        at com.genymobile.scrcpy.video.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
INFO: Renderer: direct3d
WARN: Device disconnected
ERROR: Demuxer 'audio': stream disabled due to connection error

**Comment by Jasonkwong1234** [comment]
only mirroring works

**Comment by rom1v** [comment]
> java.lang.SecurityException: Requires ADD_TRUSTED_DISPLAY permission to create a trusted virtual display.

This is your main error (nothing to do with audio). See #5523.

**Comment by Jasonkwong1234** [comment]
> > java.lang.SecurityException: Requires ADD_TRUSTED_DISPLAY permission to create a trusted virtual display.
> 
> This is your main error (nothing to do with audio). See [#5523](https://github.com/Genymobile/scrcpy/issues/5523).

Then  how to fix it

**Comment by rom1v** [comment]
Read the thread, it's fixed in an Android upgrade.
