### ISSUE TITLE
Audio not working on Vivo V2105 (Android 14)

### ISSUE THREAD

**Issue by Wintkoay** [Genymobile/scrcpy#4602]
**Environment**
 - OS: Windows 11
 - scrcpy version: 2.3.1
 - installation method: Windows release
 - device model: Vivo X70 (V2105)
 - Android version: 14 (newly updated)

**Describe the bug**
Audio doesn't work when mirroring

```
Please paste terminal output in a code block.
```
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)       1566414306000YS            device  V2105
C:\scrcpy-win64-v2.3.1\scrcpy-server: 1 file pushed, 0 skipped. 4.7 MB/s (66007 bytes in 0.013s)
[server] INFO: Device: [vivo] vivo V2105 (Android 14)
INFO: Renderer: direct3d
INFO: Texture: 1080x2376
[server] ERROR: Failed to invoke AudioRecord.<init>.
java.lang.NoSuchMethodException: android.media.AudioRecord.native_setup [class java.lang.Object, class java.lang.Object, class [I, int, int, int, int, class [I, class android.os.Parcel, long, int]
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getDeclaredMethod(Class.java:2914)
        at com.genymobile.scrcpy.Workarounds.createAudioRecord(Workarounds.java:293)
        at com.genymobile.scrcpy.AudioCapture.startRecording(AudioCapture.java:116)
        at com.genymobile.scrcpy.AudioCapture.start(AudioCapture.java:130)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:190)
W       at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:121)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
ARN: Demuxer 'audio': stream explicitly disabled by the device
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.RuntimeException: Cannot create AudioRecord
        at com.genymobile.scrcpy.Workarounds.createAudioRecord(Workarounds.java:324)
        at com.genymobile.scrcpy.AudioCapture.startRecording(AudioCapture.java:116)
        at com.genymobile.scrcpy.AudioCapture.start(AudioCapture.java:130)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:190)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:121)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by Wintkoay** [comment]
In addition, the audio is completely fine in android 13, but it has failed since upgrading to 14.

**Comment by rom1v** [comment]
Thank you for your report.

Was already fixed on `dev` branch by #4492.
