### ISSUE TITLE
No Control over S22+ Android 14, Jan. 24 update

### ISSUE THREAD

**Issue by tommessb** [Genymobile/scrcpy#4603]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Ubuntu 23.10]
 - scrcpy version: [1.2.5]
 - installation method: [apt]
 - device model: SM-S906B (Samsung S22+)
 - Android version: [14, Security Patch 1.1.2024]

**Describe the bug**
Screen Mirroring works, but can't control the device with mouse or laptop touchscreen

Terminal output:

scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 129.5 MB/s (41650 bytes in 0.000s)
[server] INFO: Device: samsung SM-S906B (Android 14)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:128)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:138)
	at com.genymobile.scrcpy.Device.<init>(Device.java:100)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
	at com.genymobile.scrcpy.Server.main(Server.java:334)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:415)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2336
INFO: New texture: 2336x1080
[server] ERROR: Exception on thread Thread[Thread-2,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:75)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:196)
	at com.genymobile.scrcpy.Controller.injectScroll(Controller.java:254)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:107)
	at com.genymobile.scrcpy.Controller.control(Controller.java:79)
	at com.genymobile.scrcpy.Server$3.run(Server.java:132)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:72)
	... 7 more
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:207)
	at android.hardware.input.InputManager.getInstance(InputManager.java:401)
	... 9 more

**Comment by tommessb** [comment]
Another Smasung device (A51) with Android 13 works fine

**Comment by rom1v** [comment]
> scrcpy 1.25

Too old.

Upgrade to the latest version manually: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by tommessb** [comment]
thanks

**Comment by stoefln** [comment]
Can someone tell me which PR fixed the Android 14 issues?

**Comment by rom1v** [comment]
Many, but maybe #4075.

**Comment by stoefln** [comment]
@rom1v thanks a lot!
