### ISSUE TITLE
Blank screen when connected to Android ATD virtual device

### ISSUE THREAD

**Issue by technoir42** [Genymobile/scrcpy#4609]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS
 - scrcpy version: 2.3.1
 - installation method: brew
 - device model: Pixel 5 virtual device
 - Android version: Android 13 ATD with Google APIs

**Describe the bug**
scrcpy shows a blank black screen when connected to [ATD](https://developer.android.com/studio/test/gradle-managed-devices#gmd-atd) virtual device. When running a test, the screen flashes for fraction of a second, but the app doesn't seem to get rendered properly. Apps launched via adb shell manually aren't displayed either.

To reproduce, configure [Gradle-managed device](https://developer.android.com/studio/test/gradle-managed-devices) as follows:
```gradle
android {
  testOptions {
    managedDevices {
      localDevices {
        pixel5 {
          device = "Pixel 5"
          apiLevel = 33
          systemImageSource = "google-atd"
        }
      }
    }
  }
}
```

Run instrumented tests on the Gradle-managed device as follows:
```
./gradlew pixel5DebugAndroidTest
```

Terminal output:
```
$ scrcpy -n -s emulator-5554 --no-audio --render-driver=software
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  emulator-5554                   device  Android_ATD_built_for_arm64
/opt/homebrew/Cellar/scrcpy/2.3.1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 109.1 MB/s (66007 bytes in 0.001s)
[server] INFO: Device: [Google] google Android ATD built for arm64 (Android 13)
INFO: Renderer: software
INFO: Texture: 1080x2336
```

If I change to regular, non-ATD device, display output gets forwarded properly.

**Comment by rom1v** [comment]
On those ATD device, can you capture using `adb shell screenrecord /sdcard/file.mp4`?

**Comment by Jaz-z** [comment]
Similar Black screen issue for Murena 2 phone running e/OS

Murena Two e/OS version: 1.19.1-t-20240109372021-stable two android version: 13 
Screen Share problem: Black screen
It is not possible to share Murena 2 Screen with desktop on Linux (Kubuntu 22.04) using scrcpy. The resulting share on desktop shows a fuzzy black screen for the android.

Using scrcpy produced the following error

scrcpy 1.25 https://github.com/Genymobile/scrcpy
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 1.4 MB/s (42151 bytes in 0.028s)
[server] INFO: Device: Murena Murena Two (Android 13)
INFO: Renderer: opengl
INFO: OpenGL version: 3.1 Mesa 20.0.8
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2400
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1920…
INFO: New texture: 864x1920

After making some updates and changes for scrcpy the following error is shown when running scrcpy on desktop

scrcpy
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 1.5 MB/s (39473 bytes in 0.025s)
[server] INFO: Device: Murena Murena Two (Android 13)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
        at java.lang.Class.getMethod(Class.java:2103)
        at java.lang.Class.getMethod(Class.java:1724)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
        at com.genymobile.scrcpy.Device.<init>(Device.java:93)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:63)
        at com.genymobile.scrcpy.Server.main(Server.java:309)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3572)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:110)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
        at com.genymobile.scrcpy.Server.main(Server.java:309)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
INFO: Renderer: opengl
INFO: OpenGL version: 4.5 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2400
WARN: Device disconnected
WARN: Killing the server...


scrcpy 1.25 on the same desktop correctly shares android display for Galaxy J3 running android 5.1.1

Murena 2:
https://murena.com/shop/smartphones/brand-new/murena-2/
e/Os: 
https://gitlab.e.foundation/e/backlog/-/issues/7732

![blank screen](https://github.com/Genymobile/scrcpy/assets/73505939/81c7a5cc-cb81-4c17-8649-3cb7a7db5935)
