### ISSUE TITLE
Using server standalone

### ISSUE THREAD

**Issue by chrapkowski** [Genymobile/scrcpy#4611]
Hi folks, this is more like a question than a feature request. I'm trying to figure out how to use `scrcpy-server` standalone. I'm following the instruction and executing the following commands.

```
adb push /usr/local/share/scrcpy/scrcpy-server /data/local/tmp/scrcpy-server.jar
adb forward tcp:27182 localabstract:scrcpy
adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 2.3.1
```

The last command fails

```
[server] ERROR: Connection refused
java.io.IOException: Connection refused
	at android.net.LocalSocketImpl.connectLocal(Native Method)
	at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:259)
	at android.net.LocalSocket.connect(LocalSocket.java:162)
	at com.genymobile.scrcpy.DesktopConnection.connect(DesktopConnection.java:51)
	at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:101)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:121)
	at com.genymobile.scrcpy.Server.internalMain(Server.java:249)
	at com.genymobile.scrcpy.Server.main(Server.java:204)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:415)
```

When I use `scrcpy` command all works just fine. What am I missing here?

Here I found something similar: https://github.com/Genymobile/scrcpy/issues/3486

**Comment by chrapkowski** [comment]
How does this work in case of `scrcpy` client, it does not seem to use `adb forward` at all?

**Comment by chrapkowski** [comment]
Got it, many thanks!
