### ISSUE TITLE
Failed to invoke AudioRecord

### ISSUE THREAD

**Issue by brynathn** [Genymobile/scrcpy#4612]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: v2.3.1
 - installation method: Manual Build
 - device model: IQOO Z7 5G
 - Android version: 14

**Describe the bug**
My screen mirrored perfectly fine but there is problem with the audio, it keeps error when i start it.

scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)       10DD730ATL000CH            device  I2213
C:\Mirroring Pack\scrcpy-win64-v2.3.1\scrcpy-server: 1 file pushed, 0 skipped. 54.1 MB/s (66007 bytes in 0.001s)
[server] INFO: Device: [vivo] iQOO I2213 (Android 14)
INFO: Renderer: direct3d
INFO: Texture: 1080x2384
[server] ERROR: Failed to invoke AudioRecord.<init>.
java.lang.NoSuchMethodException: android.media.AudioRecord.native_setup [class java.lang.Object, class java.lang.Object, class [I, int, int, int, int, class [I, class android.os.Parcel, long, int]
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getDeclaredMethod(Class.java:2914)
        at com.genymobile.scrcpy.Workarounds.createAudioRecord(Workarounds.java:293)
W       at com.genymobile.scrcpy.AudioCapture.startRecording(AudioCapture.java:116)
        at com.genymobile.scrcpy.AudioCapture.start(AudioCapture.java:130)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:190)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:121)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
A[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.RuntimeException: Cannot create AudioRecord
        at com.genymobile.scrcpy.Workarounds.createAudioRecord(Workarounds.java:324)
        at com.genymobile.scrcpy.AudioCapture.startRecording(AudioCapture.java:116)
        at com.genymobile.scrcpy.AudioCapture.start(AudioCapture.java:130)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:190)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:121)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda1.run(Unknown Source:4)
R       at java.lang.Thread.run(Thread.java:1012)
N: Demuxer 'audio': stream explicitly disabled by the device

**Comment by rom1v** [comment]
Probably already fixed on `dev` branch.

Please test this binary: https://github.com/Genymobile/scrcpy/issues/4589#issuecomment-1894243698

**Comment by brynathn** [comment]
yup, it workss thankyouu
