### ISSUE TITLE
Please help me solve this problem.

### ISSUE THREAD

**Issue by moyya11** [Genymobile/scrcpy#4641]
I use a Poco F3 smartphone, MIUI 14, Macbook Pro Mid 2012 OS Catalina. Scrcpy v. 1.17

I can't get scrcpy to work
This is the output after I run scrcpy

2024-02-03 15:47:34.971 scrcpy[3995:31250] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.17_1/share/...ped. 63.5 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: Xiaomi M2012K11AG (Android 13)
2024-02-03 15:47:35.316 scrcpy[3995:31250] INFO: Renderer: metal
2024-02-03 15:47:35.320 scrcpy[3995:31250] INFO: Initial texture: 1080x2400
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:366)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3559)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2460)
	... 9 more
2024-02-03 15:47:35.701 scrcpy[3995:31250] WARN: Device disconnected
2024-02-03 15:47:36.705 scrcpy[3995:31250] WARN: Killing the server...

**Comment by rom1v** [comment]
> scrcpy 1.17

Way too old. Upgrade to the latest version.

**Comment by moyya11** [comment]
> > scrcpy 1.17
> 
> Way too old. Upgrade to the latest version.

how to upgrade the version?.
I have tried to upgrade in terminal

**Comment by rom1v** [comment]
How did you install it initially?

**Comment by moyya11** [comment]
I installed scrcpy using homebrew

**Comment by moyya11** [comment]
Okay. Thanks for helping. Later, if there are any more problems, maybe I will ask again.

**Comment by rom1v** [comment]
I think the command is `brew update`.

**Comment by moyya11** [comment]
Thank you for the information provided, this really helps me
