### ISSUE TITLE
java.lang.nullpointerexecption

### ISSUE THREAD

**Issue by 1cmf** [Genymobile/scrcpy#4674]
I don't know if this is an issue or not I just am trying to solve the problem of why my mouse will not function while using SCR CPY some of the suggestions that I have found have been about the security in the developer options and all of that none of that exists on my device which is an A52 5G Samsung device and I can't seem to find any other clues other than this one and maybe it's not a clue and maybe I'm lost and I should just go home i'm sorry to bother anybody I just am trying to solve this problem as all

**Environment**
 This is windows 11 on a Lenovo Legion 5 And I have my ADB and fastboot is all installed with chocolatey and so is SCRCPY just today trying to solve the problem so I did a fresh install of everything

```
[server] ERROR: Exception on thread Thread[Thread-2,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:72)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:196)
        at com.genymobile.scrcpy.Controller.injectScroll(Controller.java:343)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:139)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:90)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:69)
        ... 8 more
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:207)
        at android.hardware.input.InputManager.getInstance(InputManager.java:401)
        ... 10 more
```

**Comment by rom1v** [comment]
which scrcpy version?

**Comment by rom1v** [comment]
OK if you were using an old version, this is expected. Scrcpy regularly adapts to changes in Android system (and custom ROMs).
