### ISSUE TITLE
Scrcpy does not start due to Audio stream disabled.

### ISSUE THREAD

**Issue by haskayneharry** [Genymobile/scrcpy#4676]
- [ ✓ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ✓ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Arch Linux x86_64
 - scrcpy version: 2.3.1
 - installation method: Arch Package Repository (pacman -S scrcpy) 
 - device model: Google Pixel 7 (panther)
 - Android version: Android 14 QPR3 Beta

**Describe the bug**
Scrcpy doesn't seem to start due to some audio issues. Tried potential fixes from previous bug reports but couldn't manage to get any success.

Console Output:
```
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  35181FDH2000M0                  device  Pixel_7
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 77.8 MB/s (66007 bytes in 0.001s)
[server] INFO: Device: [Google] google Pixel 7 (Android 14)
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:85)
	at com.genymobile.scrcpy.ScreenCapture.createDisplay(ScreenCapture.java:77)
	at com.genymobile.scrcpy.ScreenCapture.start(ScreenCapture.java:38)
	at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:72)
	at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
	at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
	... 6 more
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 23.3.5-arch1.1
INFO: Trilinear filtering enabled
ERROR: Demuxer 'audio': stream disabled due to connection error
ERROR: Demuxer error
```

ADB Logcat Output
```
02-17 15:22:40.282 24488 24488 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-17 15:22:40.282 24488 24488 F DEBUG   : Build fingerprint: 'google/panther_beta/panther:14/AP21.240119.009/11395453:user/release-keys'
02-17 15:22:40.282 24488 24488 F DEBUG   : Revision: 'MP1.0'
02-17 15:22:40.282 24488 24488 F DEBUG   : ABI: 'arm64'
02-17 15:22:40.282 24488 24488 F DEBUG   : Timestamp: 2024-02-17 15:22:40.175290046-0700
02-17 15:22:40.282 24488 24488 F DEBUG   : Process uptime: 2s
02-17 15:22:40.282 24488 24488 F DEBUG   : Cmdline: app_process / com.genymobile.scrcpy.CleanUp AAAAAP////8CAAAA
02-17 15:22:40.282 24488 24488 F DEBUG   : pid: 24433, tid: 24433, name: Shutdown thread  >>> app_process <<<
02-17 15:22:40.282 24488 24488 F DEBUG   : uid: 2000
02-17 15:22:40.282 24488 24488 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
02-17 15:22:40.282 24488 24488 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000007721bad250
02-17 15:22:40.282 24488 24488 F DEBUG   :     x0  0000007a91cf4c18  x1  0000000000001000  x2  0000000000000001  x3  0000007fdfd8f248
02-17 15:22:40.282 24488 24488 F DEBUG   :     x4  0000000000000058  x5  000000790597dbbc  x6  0000000000000001  x7  0000007885a70000
02-17 15:22:40.282 24488 24488 F DEBUG   :     x8  0000007721bad254  x9  0000000000000001  x10 0000000000000002  x11 0000007a8a9cd000
02-17 15:22:40.282 24488 24488 F DEBUG   :     x12 0000000000001bc9  x13 0000007a8a57c5d0  x14 0000000000001ba2  x15 0000000000000018
02-17 15:22:40.282 24488 24488 F DEBUG   :     x16 0000007a8a571ed0  x17 0000007a8a564fe0  x18 0000007aaf578000  x19 0000000000000000
02-17 15:22:40.282 24488 24488 F DEBUG   :     x20 0000007a8a9cd7e4  x21 0000007a91cf4c18  x22 0000000000001000  x23 0000007aac99cbd0
02-17 15:22:40.282 24488 24488 F DEBUG   :     x24 0000007a8a9cd000  x25 00000000000040f8  x26 00000000000006b4  x27 00000000000002b5
02-17 15:22:40.282 24488 24488 F DEBUG   :     x28 0000000000004000  x29 0000007fdfd8f2b0
02-17 15:22:40.282 24488 24488 F DEBUG   :     lr  0000007a8a567584  sp  0000007fdfd8f280  pc  0000007aac99cbd4  pst 0000000080001000
02-17 15:22:40.282 24488 24488 F DEBUG   : 4 total frames
02-17 15:22:40.282 24488 24488 F DEBUG   : backtrace:
02-17 15:22:40.282 24488 24488 F DEBUG   :       #00 pc 0000000000017bd4  /system/lib64/libutils.so (android::String16::~String16()+4) (BuildId: b435fc6f98b9d06e4e7e6649a3d36650)
02-17 15:22:40.282 24488 24488 F DEBUG   :       #01 pc 00000000000cf580  /apex/com.android.runtime/lib64/bionic/libc.so (__cxa_finalize+144) (BuildId: 3d7a1c7687593f77c7dd00e73a7b7109)
02-17 15:22:40.282 24488 24488 F DEBUG   :       #02 pc 00000000000c1838  /apex/com.android.runtime/lib64/bionic/libc.so (exit+24) (BuildId: 3d7a1c7687593f77c7dd00e73a7b7109)
02-17 15:22:40.282 24488 24488 F DEBUG   :       #03 pc 0000000000056e3c  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: 3d7a1c7687593f77c7dd00e73a7b7109)
02-17 15:22:40.287  1456  2219 W NativeCrashListener: Couldn't find ProcessRecord for pid 24433
02-17 15:22:40.287 24488 24488 E crash_dump64: AM data write failed: Broken pipe
02-17 15:22:40.290   698   698 E tombstoned: Tombstone written to: tombstone_24
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: failed to open /data/tombstones/tombstone_24.pb
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: 	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:351)
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:230)
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: 	at com.android.server.os.NativeTombstoneManager.handleProtoTombstone(NativeTombstoneManager.java:168)
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: 	at com.android.server.os.NativeTombstoneManager.handleTombstone(NativeTombstoneManager.java:137)
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: 	at com.android.server.os.NativeTombstoneManager.-$$Nest$mhandleTombstone(NativeTombstoneManager.java:0)
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: 	at com.android.server.os.NativeTombstoneManager$TombstoneWatcher.lambda$onEvent$0(NativeTombstoneManager.java:589)
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: 	at com.android.server.os.NativeTombstoneManager$TombstoneWatcher.$r8$lambda$A74hOANgR204PBre_Brq7oIduOU(NativeTombstoneManager.java:0)
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: 	at com.android.server.os.NativeTombstoneManager$TombstoneWatcher$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: 	at android.os.Handler.handleCallback(Handler.java:959)
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: 	at android.os.Looper.loopOnce(Looper.java:232)
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: 	at android.os.Looper.loop(Looper.java:317)
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: 	at android.os.HandlerThread.run(HandlerThread.java:68)
02-17 15:22:40.291  1456  1891 W NativeTombstoneManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
02-17 15:22:40.298  1456  1891 I BootReceiver: Copying /data/tombstones/tombstone_24 to DropBox (SYSTEM_TOMBSTONE)

```

**Comment by rom1v** [comment]
See #4656 #4657
