### ISSUE TITLE
Cant control the device ( samsung s23 ultra)

### ISSUE THREAD

**Issue by Masterwe** [Genymobile/scrcpy#4677]
- OS: [Windows 10]
 - scrcpy version: [2.3.1]
 - installation method: [Windows release]
 - device model: sm_s948b samsung s23 ultra
 - Android version: [14]

**Describe the bug**
Cant control the device (samsung s23 ultra), mouse and keyboard not work, only see the screen, other device (Note 8, s7, works perfectly)

This is the cmd code:

```
D:\Program Files\scrcpy-win64-v2.3.1>"D:\Program Files\scrcpy-win64\scrcpy.exe" -S --turn-screen-off --stay-awake --show-touches --serial ********

D:\Program Files\scrcpy-win64-v1....75.6 MB/s (42151 bytes in 0.001s)
[server] INFO: Device: samsung SM-S918B (Android 14)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, class java.lang.String, int]
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:128)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:138)
        at com.genymobile.scrcpy.Device.<init>(Device.java:100)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
        at com.genymobile.scrcpy.Server.main(Server.java:334)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:415)
[server] ERROR: Exception on thread Thread[Thread-2,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:75)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
        at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:203)
        at com.genymobile.scrcpy.Device.pressReleaseKeycode(Device.java:211)
        at com.genymobile.scrcpy.Device.pressReleaseKeycode(Device.java:216)
        at com.genymobile.scrcpy.Controller.control(Controller.java:66)
        at com.genymobile.scrcpy.Server$3.run(Server.java:132)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:72)
        ... 7 more
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:207)
        at android.hardware.input.InputManager.getInstance(InputManager.java:401)
        ... 9 more
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2312
```

**Comment by rom1v** [comment]
Please test https://github.com/Genymobile/scrcpy/issues/4589#issuecomment-1894243698

If it does not work, please post your framework.jar:

```
adb pull /system/framework/framework.jar
```

**Comment by Masterwe** [comment]
D:\Program Files\scrcpy-win64-v2.3.1>adb pull /system/framework/framework.jar
/system/framework/framework.jar: ...3 MB/s (51074415 bytes in 1.305s)

D:\Program Files\scrcpy-win64-v2.3.1>

**Comment by rom1v** [comment]
Yes, now the file is on your computer. Please send it here so that I can investigate 😉

**Comment by Masterwe** [comment]
[framework.zip](https://github.com/Genymobile/scrcpy/files/14322581/framework.zip)

**Comment by rom1v** [comment]
I am very confused by your issue.

The console output is not complete. For example the first line with the version does not appear. Your folder name suggests that it is 2.3.1, but: 
 - the stacktrace does not match v2.3.1
 - this exact error should never happen in v2.3.1
 - the method in your `framework.jar` is already handled in v2.3.1

So my hypothesis is that you did not run the latest version.

**Comment by Masterwe** [comment]
Thanks for the support, I read your comment and decided to delete all scrcpy files and folders and then install the latest version again in a different directory, and not use the --turn-screen-off command (which I use with note 8 and s7) and it already works correctly with the s23..
Thanks for everything
