### ISSUE TITLE
Android 15 DP1 failed to run

### ISSUE THREAD

**Issue by tiann** [Genymobile/scrcpy#4678]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Android 15
 - scrcpy version: 2.3.1
 - installation method: brew
 - device model: Pixel 6 
 - Android version: Android 15 DP1

**Describe the bug**

scrcpy failed to launch

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
❯ scrcpy
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  24031FDF6002QB                  device  Pixel_6
/usr/local/Cellar/scrcpy/2.3.1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 38.2 MB/s (66007 bytes in 0.002s)
[server] INFO: Device: [Google] google Pixel 6 (Android 14)
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:85)
	at com.genymobile.scrcpy.ScreenCapture.createDisplay(ScreenCapture.java:77)
	at com.genymobile.scrcpy.ScreenCapture.start(ScreenCapture.java:38)
	at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:72)
	at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
	at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at java.lang.Class.getMethod(Class.java:2950)
	at java.lang.Class.getMethod(Class.java:2450)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
	... 6 more
INFO: Renderer: metal
ERROR: Demuxer 'audio': stream disabled due to connection error
ERROR: Demuxer error
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by tiann** [comment]
can confirm it works, thank you!
