### ISSUE TITLE
App misteriously stopped working at all 

### ISSUE THREAD

**Issue by BletaJonatan** [Genymobile/scrcpy#4699]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 10 on last version released]
 - scrcpy version: [2.3.1]
 - installation method: [Windows release x64]
 - device model: Redmi Note 8 Pro 
 - Android version: [android 11, MIUI flavour since it's xiaomi]

My adb logcat is borderline unusable, tons of stuff on it and i wouldn't have any idea how to find what i need.

My brother broke is phone and ripped the flat ribbon cable that connects the display so now the phone is display-less.
Since it has usb debugging enabled i decided to use your app to see the screen and do stuff on it but after a few tries on connecting the app straight up stopped showing the screen, so recap at first it worked now no matter if i reboot or do anything i can't see the screen.
All i see is either a green screen:

![immagine](https://github.com/Genymobile/scrcpy/assets/65558045/8c828003-ac8d-4ee2-b433-96320f5c25b0)

or a full black screen.

Sometimes i get this random error when trying to click on the Scrcpy

```
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:226)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:230)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:323)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:138)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.RuntimeException: android.os.DeadSystemException
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:909)
        ... 10 more
Caused by: android.os.DeadSystemException
        ... 11 more
```

what i need is just for the screen mirroring to go back to work so i can blindly connect the usb, see the screen, disconnect, connect a mouse, go to the settings and so forth until i can see the usb debugging input and enable it, then i'm set.

**Comment by BletaJonatan** [comment]
extra info: i managed to remove the pin code with adb and also apparently my phone appears to have it's display always on no matter if i press the power button?
This is the command i used to check.
```
./adb.exe -s 9575ljbepriffmlr shell dumpsys power | .\grep.exe "Display Power"
```

**Comment by BletaJonatan** [comment]
Does anybody have any info? I tried recording and using the 1024 -m something command but nothing worked.
Are there any other debug steps I can take to find the root of the problem?

**Comment by rom1v** [comment]
> Caused by: android.os.DeadSystemException

Your system is completely crashed.
