### ISSUE TITLE
getPrimaryClip and setPrimaryClip not work

### ISSUE THREAD

**Issue by vimuxx** [Genymobile/scrcpy#4703]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Debian 12
 - scrcpy version: v2.3.1
 - installation method: manual build, with install_release.sh
 - device model: IQOO Neo 8
 - Android version: 14 [PD2301_A_14.19.11.W10.V000L1]

**Describe the bug**

1. ```getPrimaryClip``` and ```setPrimaryClip``` not work on git commit 5a6b8310:

```
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.getPrimaryClip [class java.lang.String, int, class java.lang.String]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getGetPrimaryClipMethod(ClipboardManager.java:44)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:117)
	at com.genymobile.scrcpy.Device.getClipboardText(Device.java:286)
	at com.genymobile.scrcpy.Device.setClipboardText(Device.java:299)
	at com.genymobile.scrcpy.Controller.setClipboard(Controller.java:396)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:164)
	at com.genymobile.scrcpy.Controller.control(Controller.java:83)
	at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
	at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1042)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.setPrimaryClip [class android.content.ClipData, class java.lang.String, class java.lang.String, int, int]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getSetPrimaryClipMethod(ClipboardManager.java:68)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.setText(ClipboardManager.java:131)
	at com.genymobile.scrcpy.Device.setClipboardText(Device.java:309)
	at com.genymobile.scrcpy.Controller.setClipboard(Controller.java:396)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:164)
	at com.genymobile.scrcpy.Controller.control(Controller.java:83)
	at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
	at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1042)

```
2. Tried ```scrcpy-server``` from [`scrcpy-win64-fix4589.zip`](https://tmp.rom1v.com/scrcpy/4589/1/scrcpy-win64-fix4589.zip) and the ```getPrimaryClip``` fixed but not ```setPrimaryClip```:

```
INFO: Device clipboard copied
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.setPrimaryClip [class android.content.ClipData, class java.lang.String, class java.lang.String, int, int]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getSetPrimaryClipMethod(ClipboardManager.java:81)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.setText(ClipboardManager.java:149)
	at com.genymobile.scrcpy.Device.setClipboardText(Device.java:309)
	at com.genymobile.scrcpy.Controller.setClipboard(Controller.java:396)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:164)
	at com.genymobile.scrcpy.Controller.control(Controller.java:83)
	at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
	at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1042)
```

Seems that we forgot ```setPrimaryClip```?

**Comment by rom1v** [comment]
Thank you for your report.

Please test 746eaea55683e8e97ba7763bc0fa567227004c5d. Here is a binary:

- [`scrcpy-win64-fix4703.zip`](https://tmp.rom1v.com/scrcpy/4703/1/scrcpy-win64-fix4703.zip) <sub>`SHA-256: 70056bd08943d9bed5fa552d70a0f4e8cd7061d5d89a7ade502c0467a26e21a`</sub>

**Comment by vimuxx** [comment]
it works!

**Comment by rom1v** [comment]
Merged into `dev` :tada:
