### ISSUE TITLE
get an error InvocationTargetException when run too long time

### ISSUE THREAD

**Issue by hytTony** [Genymobile/scrcpy#4723]
It run correct commonly, but after long time, sometimes will get the error java.lang.reflect.InvocationTargetException on PowerManager.isScreenOn. Just sometimes, not always.

**Comment by rom1v** [comment]
Please post the whole console output.

**Comment by hytTony** [comment]
Could not invoke method
java.lang.reflect.InvocationTargetException
   at java.lang.reflect.Method.invoke(Native Method)
   at com.genymobile.scrcpy.wrappers.PowerManager.isScreenOn(PowerManager.java:32)
   at com.genymobile.scrcpy.Device.isScreenOn(Device.java:253)
   at com.genymobile.scrcpy.Controller.pressBackOrTurnScreenOn(Controller.java:361)
   at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:148)
   at com.genymobile.scrcpy.Controller.control(Controller.java:83)
   at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
   at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
   at java.lang.Thread.run(Thread.java:1012)

**Comment by hytTony** [comment]
OK, i test it. But i don't know when will report this error again, in the past 6 months, the error just happened 2 times.
