### ISSUE TITLE
connect error with Google Pixel6

### ISSUE THREAD

**Issue by FantomasTsang** [Genymobile/scrcpy#4731]
hello，i got connect problem with google pixel6. when i start console and just input "scrcpy", it can't connect success. Days ago, just before i upgrade android version,  it can be connected.

**Environment**
 - OS: [ Windows]
 - scrcpy version: [v2.2]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:Google pixel6
 - Android version: [Android14   AP21.240119.009]

full output in the console：

scrcpy v2.2 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)        24261FDF600AT7            device  Pixel_6
E:\scrcpy\scrcpy-win64-v2.2\scrcpy-server: 1 file pushed, 0 skipped. 3.6 MB/s (64363 bytes in 0.017s)
[server] INFO: Device: [Google] google Pixel 6 (Android 14)
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:85)
        at com.genymobile.scrcpy.ScreenCapture.createDisplay(ScreenCapture.java:71)
        at com.genymobile.scrcpy.ScreenCapture.init(ScreenCapture.java:21)
        at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:55)
        at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
        at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
        ... 6 more
ERROR: Could not retrieve device information
ERROR: Server connection failed

**Comment by rom1v** [comment]
> scrcpy version: [v2.2]

Update to the latest version (2.4).

**Comment by FantomasTsang** [comment]
thanks a lot
