### ISSUE TITLE
error threat

### ISSUE THREAD

**Issue by SarahCary** [Genymobile/scrcpy#4742]
Hello,
I got this error after trying to authorise my phone on my computer every time before it worked fine:

`scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
C:\Users\wi\scoop\apps\scrcpy\current\scrcpy-server: 1 file pushed, 0 skipped. 25.8 MB/s (42151 bytes in 0.002s)
[server] INFO: Device: samsung SM-T590 (Android 10)
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffec77
[server] INFO: Retrying with -m1600...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffec77
[server] INFO: Retrying with -m1280...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffec77
[server] INFO: Retrying with -m1024...
INFO: Renderer: direct3d
INFO: Initial texture: 1200x1920
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffec77
[server] INFO: Retrying with -m800...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffec77
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:282)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:97)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:334)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:342)`

can you help please ?

**Comment by rom1v** [comment]
> scrcpy 1.25

Way too old. Install the latest version.

**Comment by SarahCary** [comment]
do I have to uninstall the version I already have? because I've done :
`>winget install scrcpy
La source 'msstore' nécessite que vous consultiez les contrats suivants avant de l’utiliser.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
La source nécessite que la région géographique à 2 lettres de l’ordinateur actuel soit envoyée au service principal pour fonctionner correctement (par exemple, « ÉTATS-UNIS »).

Acceptez-vous toutes les conditions des contrats sources ?
[Y] Oui  [N] Non: y
Trouvé scrcpy [Genymobile.scrcpy] Version 2.3.1
La licence d’utilisation de cette application vous est octroyée par son propriétaire.
Microsoft n’est pas responsable des paquets tiers et n’accorde pas de licences à ceux-ci.
Téléchargement en cours https://github.com/Genymobile/scrcpy/releases/download/v2.3.1/scrcpy-win64-v2.3.1.zip
  ██████████████████████████████  5.76 MB / 5.76 MB
Le code de hachage de l’installation a été vérifié avec succès
Extraction des archives...
Extraction de l’archive réussie
Démarrage du package d’installation... Merci de patienter.
Variable d’environnement de chemin modifiée ; redémarrez votre interpréteur de commandes pour utiliser la nouvelle valeur.
Alias de ligne de commande ajouté : "scrcpy"`
but it didn't update to the new version

**Comment by rom1v** [comment]
This is winget stuff, I am not familiar with winget.

You can download the official release v2.4.

**Comment by SarahCary** [comment]
I used this, because when I run the executable it opens and closes the window directly.

**Comment by rom1v** [comment]
> I used this, because when I run the executable it opens and closes the window directly.

Please read [this](https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run). What is the error in the console?

**Comment by SarahCary** [comment]
I can't see any mistake, the window closes so quickly

**Comment by rom1v** [comment]
> I can't see any mistake, the window closes so quickly

Because you haven't read [this](https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run).

**Comment by SarahCary** [comment]
it works thank you
