### ISSUE TITLE
[server] ERROR: Encoding error: java.lang.IllegalStateException: null

### ISSUE THREAD

**Issue by AzuraChannel** [Genymobile/scrcpy#4754]
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1280...
[server] INFO: Retrying...
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 391.35
INFO: Trilinear filtering disabled
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1600x720
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1024...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m800...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
WARN: Device di[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2792)
        at com.genymobile.scrcpy.SurfaceEncoder.encode(SurfaceEncoder.java:157)
        at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:76)
        at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
        at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)s
        at java.lang.Thread.run(Thread.java:919)c
onnected

Device: Realme C3(previously worked)

**Comment by rom1v** [comment]
Which scrcpy version?

**Comment by AzuraChannel** [comment]
> Which scrcpy version?

2.4

**Comment by rom1v** [comment]
Try with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder).

**Comment by AzuraChannel** [comment]
> Try with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder).

Still the same

**Comment by AzuraChannel** [comment]
> Try with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder).

[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2792)
        at com.genymobile.scrcpy.SurfaceEncoder.encode(SurfaceEncoder.java:157)
        at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:76)
        at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
        at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:919)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 391.35
INFO: Trilinear filtering disabled
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 720x1600
WARN: Device disconnected

**Comment by AzuraChannel** [comment]
> `adb` must be executed from the computer.
> 
> From the device, directly call `screenrecord /sdcard/file.mp4` with shell rights.

it work with screenrecord
