### ISSUE TITLE
Unable to control the Xiaomi 14 mouse or keyboard

### ISSUE THREAD

**Issue by MathiasDrapier** [Genymobile/scrcpy#4795]
Hello, 

Here is the stacktrace when I try to click on the screen in my new Xaiomi14.

I have follow all the prerequisites, and have already read the other issues concerning this problem, nothing fixes it.

Thanks in advance

```
C:\Users\Mathias\Desktop\scrcpy-win64-v2.4>scrcpy --tcpip=192.168.1.39:39531
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: Connecting to 192.168.1.39:39531...
INFO: Connected to 192.168.1.39:39531
C:\Users\Mathias\Desktop\scrcpy-win64-v2.4\scrcpy-server: 1 file pushed, 0 skipped. 82.9 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [Xiaomi] Xiaomi 23127PN0CG (Android 14)
INFO: Renderer: direct3d
INFO: Texture: 1200x2664
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:230)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:234)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:362)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:162)
        at com.genymobile.scrcpy.Controller.control(Controller.java:97)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:105)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
        at android.os.Parcel.createException(Parcel.java:3041)
        at android.os.Parcel.readException(Parcel.java:3024)
        at android.os.Parcel.readException(Parcel.java:2966)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1575)
        at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
        at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
        ... 10 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:911)
        at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:744)
        at android.os.Binder.execTransactInternal(Binder.java:1346)
        at android.os.Binder.execTransact(Binder.java:1282)
```

**Comment by MathiasDrapier** [comment]
I found the solution, for all recent Xiaomi users, you must connect to a Mi account to be able to activate the necessary authorization

**Comment by ji4ozhu** [comment]
开发者选项-USB调试(安全设置)  打开
