### ISSUE TITLE
Controller error "java.io.IOException: android.system.ErrnoException: open failed: EACCES (Permission denied)"

### ISSUE THREAD

**Issue by Unihedro** [Genymobile/scrcpy#4811]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: win64-v2.4
 - installation method: release x64
 - device model: SM_G9550
 - Android version: 9

**Describe the bug**
Several attempts to initialize the connection to the phone (through different commands) has failed. Phone detection and debug authorization worked properly (hopefully) but some googling on the error says that android may have just refused file access for being a new android version. Searching through other issues there are lots of other issues that includes "stream disabled due to connection error" but none were relevant. Included is the log for posting the recommended command listed in the project homepage:

```
C:\Users\user\Downloads\scrcpy-win64-v2.4\scrcpy-win64-v2.4>.\scrcpy --video-codec=h265 --max-size=1920 --max-fps=60 --no-audio --keyboard=uhid
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  9889143043364e3655              device  SM_G9550
C:\Users\user\Downloads\scrcpy-win64-v2.4\scrcpy-win64-v2.... file pushed, 0 skipped. 66.9 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [samsung] samsung SM-G9550 (Android 8.0.0)
[server] ERROR: Controller error
java.io.IOException: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at com.genymobile.scrcpy.UhidManager.open(UhidManager.java:66)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:208)
        at com.genymobile.scrcpy.Controller.control(Controller.java:97)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:105)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:764)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:207)
        at android.system.Os.open(Os.java:354)
        at com.genymobile.scrcpy.UhidManager.open(UhidManager.java:49)
        ... 5 more
INFO: Renderer: direct3d
ERROR: Demuxer 'video': stream disabled due to connection error
ERROR: Demuxer error
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
On old Android versions, `--keyboard=uhid` cannot work due to permissions errors (like you get).

https://github.com/Genymobile/scrcpy/pull/4473#issuecomment-1963004171
https://github.com/Genymobile/scrcpy/pull/4473#issuecomment-1975133226

**Comment by Unihedro** [comment]
Thanks for the quick response! Removing --keyboard has made it work :)

**Comment by rom1v** [comment]
What exact error do you have? (post the whole console output)

**Comment by EnderAvaritia** [comment]
> What exact error do you get? (post the whole console output)

when i used -K
```
scrcpy -K --tcpip=localhost:5555
scrcpy 3.1 <https://github.com/Genymobile/scrcpy>
INFO: Connecting to localhost:5555...
INFO: Connected to localhost:5555
D:\Program\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 102.5 MB/s (90640 bytes in 0.001s)
[server] INFO: Device: [redroid] redroid redroid15_x86_64 (Android 15)
[server] ERROR: Could not create default audio encoder for opus
List of audio encoders:
    --audio-codec=aac --audio-encoder=OMX.google.aac.encoder          (hybrid)
    --audio-codec=flac --audio-encoder=OMX.google.flac.encoder        (hybrid)
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe (NAME_NOT_FOUND)
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:2154)
        at android.media.MediaCodec.<init>(MediaCodec.java:2132)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:2087)
        at com.genymobile.scrcpy.audio.AudioEncoder.createMediaCodec(AudioEncoder.java:309)
        at com.genymobile.scrcpy.audio.AudioEncoder.encode(AudioEncoder.java:195)
        at com.genymobile.scrcpy.audio.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:133)
        at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Controller error
java.io.IOException: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at com.genymobile.scrcpy.control.UhidManager.open(UhidManager.java:70)
        at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:293)
        at com.genymobile.scrcpy.control.Controller.control(Controller.java:195)
        at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:203)
        at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
        at android.system.Os.open(Os.java:494)
        at com.genymobile.scrcpy.control.UhidManager.open(UhidManager.java:53)
        ... 5 more
INFO: Renderer: direct3d
WARN: Device disconnected
WARN: Demuxer 'audio': stream explicitly disabled by the device
```
when i dont use

![Image](https://github.com/user-attachments/assets/82e9c0ee-bc34-45c1-8d5b-992c9f37633c)
