### ISSUE TITLE
version android error

### ISSUE THREAD

**Issue by SarahCary** [Genymobile/scrcpy#4827]
Hello,

I have this error which says that the versions before android 11 are not compatible, whereas it worked yesterday. so I do not know what to do here is the error that I have:

`scrcpy-win64-v2.4\scrcpy-wi... file pushed, 0 skipped. 49.9 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [samsung] samsung SM-T590 (Android 10)
[server] WARN: Audio disabled: it is not supported before Android 11
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffec77
[server] INFO: Retrying with -m1600...
[server] INFO: Retrying...
[server] INFO: Retrying with -m1280...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffec77
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1200x1920
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffec77
[server] INFO: Retrying with -m1024...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffec77
[server] INFO: Retrying with -m800...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffec77
WA[server] ERROR: Exception on thread Thread[video,5,main]
android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:69)
        at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)`

the version I was using is 2.4
Thanks

**Comment by rom1v** [comment]
> WARN: Audio disabled: it is not supported before Android 11

This is just a warning saying that audio is disabled.

Your error is related to the video encoder. It automatically tried lower resolutions, which also failed.

If it used to work, reboot your device, something temporarily causes your encoder to fail.
Otherwise, try with another encoder: https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder
