### ISSUE TITLE
Huawei  Scrcpy 2.4 UHID keyboard and mouse  Error

### ISSUE THREAD

**Issue by ji4ozhu** [Genymobile/scrcpy#4835]
- [* ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [* ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 10]
 - scrcpy version: [2.4]
 - installation method: [Original Download Scrcpy 2.4 x64]
 - device model:Huawei P9 Plus (VIE-AL 10)
 - Android version: [Android 8.0.0]

C:\Users\Wanli\Desktop\scrcpy-win64-v2.4>scrcpy -K
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  8FS7N16A19001893                device  VIE_AL10
C:\Users\Wanli\Desktop\scrcpy-win64-v2.4\scrcpy-server: 1 file pushed, 0 skipped. 185.6 MB/s (69007 bytes in 0.000s)
[server] INFO: Device: [HUAWEI] HUAWEI VIE-AL10 (Android 8.0.0)
[server] WARN: Audio disabled: it is not supported before Android 11
[server] ERROR: Controller error
java.io.IOException: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at com.genymobile.scrcpy.UhidManager.open(UhidManager.java:66)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:208)
        at com.genymobile.scrcpy.Controller.control(Controller.java:97)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:105)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:784)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:207)
        at android.system.Os.open(Os.java:354)
        at com.genymobile.scrcpy.UhidManager.open(UhidManager.java:49)
        ... 5 more
INFO: Renderer: direct3d
ERROR: Demuxer 'video': stream disabled due to connection error
WARN: Demuxer 'audio': stream explicitly disabled by the device
ERROR: Demuxer error

C:\Users\Wanli\Desktop\scrcpy-win64-v2.4>
![huawei](https://github.com/Genymobile/scrcpy/assets/28642463/646fc958-45a9-4194-94a2-0f0ecc464fb6)

If the -K parameter is not used, it starts normally.

**Comment by rom1v** [comment]
Yes, UHID does not work on old Android versions:
 - https://github.com/Genymobile/scrcpy/pull/4473#issuecomment-1963004171
 - https://github.com/Genymobile/scrcpy/issues/4811

Apparently (according to reported issues) UHID works for Android >= 10 (but I'm not sure, it might depend on vendors).

**Comment by ji4ozhu** [comment]
thanks @rom1v
