### ISSUE TITLE
scrcpy on Nothing 2a / macOS works, but with weird errors

### ISSUE THREAD

**Issue by freebrowser1** [Genymobile/scrcpy#4878]
**Environment**
 - OS: macOS 14.4 Sonoma
 - scrcpy version: 2.4
 - installation method: `brew install strcpy` and later `brew upgrade strcpy`
 - device model: Nothing phone 2a
 - Android version: 14

**Describe the bug**
When I connect my Nothing 2a with scrcpy, it does show the screen on the computer and does accept 'normal' keystrokes and mouse actions.
I was using scrcpy over wifi and it was not connected via USB to the computer.
But <cmd> / <option> + letter do not work.
This is what happerns at a fresh start of scrcpy on macOS. 

````
mymac:~/scratch % scrcpy -S -s 192.168.1.9 -m 1024 -K
scrcpy v2.2 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.1.9:5555                device  A142
/usr/local/bin/homebrew/Cellar/scrcpy/2.2/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 43.7 MB/s (64363 bytes in 0.001s)
[server] INFO: Device: [Nothing] Nothing A142 (Android 14)
ERROR: Could not find USB device 192.168.1.9:5555
ERROR:         8204C660           (046d:0825)  (null) C270 HD WEBCAM
ERROR:         0000000000000001   (2109:0100)  VIA Technologies Inc.          USB 2.0 BILLBOARD             
ERROR:         000001             (0bda:8153)  Realtek USB 10/100/1000 LAN
ERROR: Fallback to default keyboard injection method (-K/--hid-keyboard ignored)
INFO: Renderer: metal
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getPhysicalDisplayIds []
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetPhysicalDisplayIdsMethod(SurfaceControl.java:137)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getPhysicalDisplayIds(SurfaceControl.java:144)
	at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:319)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:169)
	at com.genymobile.scrcpy.Controller.control(Controller.java:83)
	at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
	at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Could not get physical display ids
INFO: Texture: 1024x456
````

**Comment by rom1v** [comment]
> scrcpy v2.2 <https://github.com/Genymobile/scrcpy>

Upgrade to the latest version (currently 2.4).

**Comment by freebrowser1** [comment]
Indeed, you are right, before I did this I called `brew upgrade scrcpy`, but presumably it did not update.
On another Mac (a Macbook Pro M1) the app worked flawlessly with the same device.
