### ISSUE TITLE
SCRCPY not working after last Android 15 beta update (AP31.240322.023, 15 beta 1.1)

### ISSUE THREAD

**Issue by Lpptrex** [Genymobile/scrcpy#4879]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 2.4
 - installation method: Windows release 64 bit
 - device model: Pixel 8 Pro
 - Android version: 15 Beta 1.1

SCRCPY fails to initialize. The console closes automatically after showing the first line. This issue presents itself similarly as that that already happened with the first Android 15 beta.

**Comment by Lpptrex** [comment]
After re-downloading the app, it seems to work. I had already tried twice, but without success. Oh well 🤷🏻‍♂️thanks!

**Comment by Lpptrex** [comment]
After re-downloading the app, it seems to work. I had already tried twice, but without success. Oh well 🤷🏻‍♂️thanks!

**Comment by akai277** [comment]
My Xiaomi 14 just upgrade to HyperOS 2.0,The Android 15,so It could not  stream audio to PC,so I use SndCpy,that is good  solution

**Comment by saifurrdev** [comment]
saifur@saifurr:~$ adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
ec015b69	device

saifur@saifurr:~$ scrcpy --turn-screen-off --stay-awake
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 254.5 MB/s (41650 bytes in 0.000s)
[server] INFO: Device: Xiaomi 23129RAA4G (Android 15)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2940)
	at java.lang.Class.getMethod(Class.java:2440)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:128)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:138)
	at com.genymobile.scrcpy.Device.<init>(Device.java:100)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
	at com.genymobile.scrcpy.Server.main(Server.java:334)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:382)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getInternalDisplayToken []
	at java.lang.Class.getMethod(Class.java:2940)
	at java.lang.Class.getMethod(Class.java:2440)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetBuiltInDisplayMethod(SurfaceControl.java:94)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getBuiltInDisplay(SurfaceControl.java:103)
	at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:280)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:133)
	at com.genymobile.scrcpy.Controller.control(Controller.java:79)
	at com.genymobile.scrcpy.Server$3.run(Server.java:132)
	at java.lang.Thread.run(Thread.java:1119)
[server] ERROR: Could not get built-in display
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
	at com.genymobile.scrcpy.ScreenEncoder.createDisplay(ScreenEncoder.java:278)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
	at com.genymobile.scrcpy.Server.main(Server.java:334)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:382)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at java.lang.Class.getMethod(Class.java:2940)
	at java.lang.Class.getMethod(Class.java:2440)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:81)
	... 7 more
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 25.0.7-0ubuntu0.24.04.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2400
WARN: Device disconnected
WARN: Killing the server...
saifur@saifurr:~$ scrcpy --stay-awake
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 246.1 MB/s (41650 bytes in 0.000s)
[server] INFO: Device: Xiaomi 23129RAA4G (Android 15)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2940)
	at java.lang.Class.getMethod(Class.java:2440)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:128)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:138)
	at com.genymobile.scrcpy.Device.<init>(Device.java:100)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
	at com.genymobile.scrcpy.Server.main(Server.java:334)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:382)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 25.0.7-0ubuntu0.24.04.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2400
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
	at com.genymobile.scrcpy.ScreenEncoder.createDisplay(ScreenEncoder.java:278)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
	at com.genymobile.scrcpy.Server.main(Server.java:334)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:382)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at java.lang.Class.getMethod(Class.java:2940)
	at java.lang.Class.getMethod(Class.java:2440)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:81)
	... 7 more
WARN: Killing the server...
saifur@saifurr:~$ adb devices
List of devices attached

saifur@saifurr:~$ adb pair 192.168.0.100:38109
Enter pairing code: 792580
Successfully paired to 192.168.0.100:38109 [guid=adb-ec015b69-Pg8nvL]
saifur@saifurr:~$ adb devices
List of devices attached

saifur@saifurr:~$ adb cunnect 192.168.0.100:37499
adb: unknown command cunnect
saifur@saifurr:~$ adb connect 192.168.0.100:37499
connected to 192.168.0.100:37499
saifur@saifurr:~$ adb devices
List of devices attached
192.168.0.100:37499	device

saifur@saifurr:~$ ls
Desktop  Documents  Downloads  Music  Pictures  Public  Templates  Videos
saifur@saifurr:~$ scrcpy --bit-rate 8M --max-fps 60
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 50.0 MB/s (41650 bytes in 0.001s)
[server] INFO: Device: Xiaomi 23129RAA4G (Android 15)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2940)
	at java.lang.Class.getMethod(Class.java:2440)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:128)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:138)
	at com.genymobile.scrcpy.Device.<init>(Device.java:100)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
	at com.genymobile.scrcpy.Server.main(Server.java:334)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:382)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 25.0.7-0ubuntu0.24.04.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2400
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
	at com.genymobile.scrcpy.ScreenEncoder.createDisplay(ScreenEncoder.java:278)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
	at com.genymobile.scrcpy.Server.main(Server.java:334)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:382)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at java.lang.Class.getMethod(Class.java:2940)
	at java.lang.Class.getMethod(Class.java:2440)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:81)
	... 7 more
WARN: Killing the server...

**Comment by rom1v** [comment]
> scrcpy 1.25

Ultra-old. Install the latest version.
