### ISSUE TITLE
scrcpy killing itself for no reason

### ISSUE THREAD

**Issue by cralllllis** [Genymobile/scrcpy#4895]
> [server] INFO: Device: Google Pixel 7 Pro (Android 14)
> [server] ERROR: Could not invoke method
> java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
>         at java.lang.Class.getMethod(Class.java:2950)
>         at java.lang.Class.getMethod(Class.java:2450)
>         at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
>         at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
>         at com.genymobile.scrcpy.Device.<init>(Device.java:103)
>         at com.genymobile.scrcpy.Server.scrcpy(Server.java:65)
>         at com.genymobile.scrcpy.Server.main(Server.java:335)
>         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
>         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
> [server] ERROR: Exception on thread Thread[main,5,main]
> java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
>         at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
>         at com.genymobile.scrcpy.ScreenEncoder.createDisplay(ScreenEncoder.java:278)
>         at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
>         at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
>         at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
>         at com.genymobile.scrcpy.Server.main(Server.java:335)
>         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
>         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
> Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
>         at java.lang.Class.getMethod(Class.java:2950)
>         at java.lang.Class.getMethod(Class.java:2450)
>         at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:81)
>         ... 7 more
> INFO: Renderer: direct3d
> INFO: Initial texture: 1440x3120
> WARN: Device disconnected
> WARN: Killing the server...

transfering files is on, usb debug is also on
currently using a15 beta, could it be a problem?
any command such as `scrcpy -m1024` or `scrcpy -b2M -m800` is not really helpful and problem is the same

**Comment by rom1v** [comment]
Upgrade to the latest version of scrcpy (currently 2.4).

**Comment by cralllllis** [comment]
using github firs

> Upgrade to the latest version of scrcpy (currently 2.4).
already

**Comment by rom1v** [comment]
Please post the FULL console output,.
