### ISSUE TITLE
server version

### ISSUE THREAD

**Issue by 1bharath-yadav** [Genymobile/scrcpy#4920]
arch linux

  scrcpy --list-cameras

scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  Q8JR4DUCLJIRKVPZ                device  2201117PI
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 70.9 MB/s (65851 bytes in 0.001s)
[server] ERROR: The server version (2.3) does not match the client (2.3.1)
java.lang.IllegalArgumentException: The server version (2.3) does not match the client (2.3.1)
        at com.genymobile.scrcpy.Options.parse(Options.java:237)
        at com.genymobile.scrcpy.Server.internalMain(Server.java:216)
        at com.genymobile.scrcpy.Server.main(Server.java:199)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:389)

**Comment by rom1v** [comment]
Your sever (in /usr/local/share/scrcpy/scrcpy-server) does not match the client. How did you install scrcpy?

Btw, the latest version is 2.4 currently.

**Comment by 1bharath-yadav** [comment]
Sorry
Actually I first install 2.3.1 from source code later I installed from Pacman without deleting the 2.3.1 configurations.
Solved by. sudo Pacman -Rns scrcpy && sudo Pacman -S scrcpy.
