### ISSUE TITLE
ERROR: Exception on thread Thread[video,5,main]

### ISSUE THREAD

**Issue by Kimi1860** [Genymobile/scrcpy#4922]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS Ventura 13.6
 - scrcpy version: 2.4
 - installation method: brew
 

**Describe the bug**
<img width="865" alt="image" src="https://github.com/Genymobile/scrcpy/assets/26540651/747bd7cc-bfea-40d9-83bd-4773531d26dd">

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
The vendor rom calls an internal "Sky-something", which fails.

Could you please post your framework.jar?

```
adb pull /system/framework/framework.jar
```

**Comment by Kimi1860** [comment]
[framework.jar.zip](https://github.com/Genymobile/scrcpy/files/15315153/framework.jar.zip)
Here's the framework.jar

Thanks

**Comment by Kimi1860** [comment]
Hi, I've post the framework.jar. Just wonder if there's any chance that my devices could be available to connect with this.

**Comment by rom1v** [comment]
It's weird, your framework.jar is almost empty, it doesn't contains the expected classes.

**Comment by Kimi1860** [comment]
The OS provider is called Coocaa, maybe they did some tricks reconstructed the framework

**Comment by xtbbbbdx** [comment]
Same issue. Also happen at Skyworth TV, Looks like it's common issue on Skyworth TV

**Comment by HinsCoder** [comment]
My Skyworth Coocaa TV is the same issue.I tried to downgrade to **scrcpy v1.19** and resolved the issue.But its maximum resolution can only be set to 1920 x 1080, and its HDMI channel is black screen (appears to have DRM protection?)

**Comment by rom1v** [comment]
> I tried to downgrade to scrcpy v1.19 and resolved the issue.

With the latest version, does it work if you disable audio (`scrcpy --no-audio`)? What is the exact error you get (the full console output)?

**Comment by HinsCoder** [comment]
> > I tried to downgrade to scrcpy v1.19 and resolved the issue.
> 
> With the latest version, does it work if you disable audio (`scrcpy --no-audio`)? What is the exact error you get (the full console output)?


I just tried, but this error still persists.

```
C:\Users\Hins\Downloads\scrcpy-win64-v2.5>scrcpy --no-audio
scrcpy 2.5 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.31.22:5555              device  7T872_P60P
C:\Users\Hins\Downloads\scrcpy-win64-v2.5\scrcpy...ed, 0 skipped. 86.8 MB/s (69624 bytes in 0.001s)
[server] INFO: Device: [skyworth] Coocaa 7T872_P60P (Android 10)
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
        at android.media.MediaCodec.getCurProcessName(MediaCodec.java:1913)
        at android.media.MediaCodec.setSkyMediaStatus(MediaCodec.java:1927)
        at android.media.MediaCodec.release(MediaCodec.java:1949)
        at com.genymobile.scrcpy.SurfaceEncoder.streamCapture(SurfaceEncoder.java:95)
        at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:257)
        at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:919)
INFO: Renderer: direct3d
ERROR: Controller error
```

**Comment by DancingDolphins** [comment]
same here and my 
[framework.jar.zip](https://github.com/user-attachments/files/16125657/framework.jar.zip)

**Comment by rom1v** [comment]
Between 1.19 and 1.20, this is probably due to this commit 8df42cec82cb5856e6c10a4089e6b2953310da6e.

Let's try with this quick&dirty change:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/Workarounds.java b/server/src/main/java/com/genymobile/scrcpy/Workarounds.java
index 448e7099f..db0d72789 100644
--- a/server/src/main/java/com/genymobile/scrcpy/Workarounds.java
+++ b/server/src/main/java/com/genymobile/scrcpy/Workarounds.java
@@ -74,6 +74,9 @@ public final class Workarounds {
             mustFillAppContext = true;
         }
 
+        mustFillAppInfo = true;
+        mustFillAppContext = true;
+
         if (audio && Build.VERSION.SDK_INT == Build.VERSION_CODES.R) {
             // Before Android 11, audio is not supported.
             // Since Android 12, we can properly set a context on the AudioRecord.
```

Replace this file in your v2.5 release:

- [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/4922/1/scrcpy-server) <sub>`SHA-256: 55926d71d45aef83d989bf0fcd25801f8886307efe933eb8d4200807890080a`</sub>

**Comment by HinsCoder** [comment]
> Replace this file in your v2.5 release:
> 
> * [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/4922/1/scrcpy-server) `SHA-256: 55926d71d45aef83d989bf0fcd25801f8886307efe933eb8d4200807890080a`

This is an effective modification, thank you very much!

![image](https://github.com/Genymobile/scrcpy/assets/99468376/9855236e-d7fd-4b22-ac45-8c61fecf76d5)

**Comment by rom1v** [comment]
Oh great!

Could you then test this new one and confirm that it works:


```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/Workarounds.java b/server/src/main/java/com/genymobile/scrcpy/Workarounds.java
index 448e7099f..3f86f892b 100644
--- a/server/src/main/java/com/genymobile/scrcpy/Workarounds.java
+++ b/server/src/main/java/com/genymobile/scrcpy/Workarounds.java
@@ -63,7 +63,7 @@ public final class Workarounds {
             //  - <https://github.com/Genymobile/scrcpy/issues/940>
             //  - <https://github.com/Genymobile/scrcpy/issues/994>
             mustFillAppInfo = true;
-        } else if (Build.BRAND.equalsIgnoreCase("honor")) {
+        } else if (Build.BRAND.equalsIgnoreCase("honor") || Build.BRAND.equalsIgnoreCase("skyworth")) {
             // More workarounds must be applied for Honor devices:
             //  - <https://github.com/Genymobile/scrcpy/issues/4015>
             //
```

**Comment by HinsCoder** [comment]
> Could you then test this new one and confirm that it works:
> 
> * [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/4922/2/scrcpy-server) `SHA-256: 7cb3bc939c91e23788ed3f2801f71b9cc8f258e85bed7b60fc98ece9721bbe1`

Oh no, the NullPointerException error has occurred again.

```
C:\Users\Hins\Downloads\scrcpy-win64-v2.5>scrcpy
scrcpy 2.5 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.31.22:5555              device  7T872_P60P
C:\Users\Hins\Downloads\scrcpy-win64-v2.5\scrcpy-server: 1...ile pushed, 0 skipped. 111.2 MB/s (164344 bytes in 0.001s)
[server] INFO: Device: [skyworth] Coocaa 7T872_P60P (Android 10)
[server] WARN: Audio disabled: it is not supported before Android 11
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1920x1080
ERROR: Controller error
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
        at android.media.MediaCodec.getCurProcessName(MediaCodec.java:1913)
        at android.media.MediaCodec.setSkyMediaStatus(MediaCodec.java:1927)
        at android.media.MediaCodec.release(MediaCodec.java:1949)
        at com.genymobile.scrcpy.SurfaceEncoder.streamCapture(SurfaceEncoder.java:95)
        at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:257)
        at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by HinsCoder** [comment]
> Oh in your case, the manufacturer is still `skyworth,` but the brand is `Coocaa`. Let's test the manufacturer instead:

Congratulate, it works successful again.

**Comment by rom1v** [comment]
:+1:

Merged into `dev`: b50f9eb41d1bd7b75a77e2c388b0144365e3cd5f :rocket:
