### ISSUE TITLE
HyperOS 1.0.1.0 mouse controls stopped working

### ISSUE THREAD

**Issue by Koatohee** [Genymobile/scrcpy#4937]
**Environment**
 - OS: Android
 - scrcpy version: 2.4
 - installation method: Windows release
 - device model:  Poco X4 GT
 - Android version: 14

**Describe the bug**

Previously I've had MIUI installed on my phone, and navigating my phone with a mouse by launching scrcpy-noconsole.vbs worked like a charm, but after I updated to HyperOS 1.0.1.0 yesterday I can mirror my phone to my PC, but can't control it with a mouse anymore.

**Comment by zyl-hub** [comment]
I have the same issue, do you know how to solve it

**Comment by Koatohee** [comment]
> I have the same issue, this is caused by the USB debugging (Security settings) in android 14, you can follow this link to fix it
> 
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

that didnt help. that feature was enabled already and fixes nothing

**Comment by zyl-hub** [comment]
> > I have the same issue, this is caused by the USB debugging (Security settings) in android 14, you can follow this link to fix it
> > https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work
> 
> that didnt help. that feature was enabled already and fixes nothing

you need to reboot your phone after you enabled this feature

**Comment by Koatohee** [comment]
> > > I have the same issue, this is caused by the USB debugging (Security settings) in android 14, you can follow this link to fix it
> > > https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work
> > 
> > 
> > that didnt help. that feature was enabled already and fixes nothing
> 
> you need to reboot your phone after you enabled this feature

done that, doesnt work

**Comment by testhowtest** [comment]
Similar to #282, both issues describe the situation where mouse control suddenly stops working. However, they occur in different operating systems and software versions. They may be caused by different reasons and require debugging and fixing to resolve the problem of mouse control cessation.

**Comment by testhowtest** [comment]
Similar to https://github.com/Genymobile/scrcpy/issues/282

**Comment by testhowtest** [comment]
I found that there seems to be some connection between this issue and another one (#282 ). both issues describe the situation where mouse control suddenly stops working. Is that right?

**Comment by sinnren** [comment]
$ input keyevent KEYCODE_HOME

Exception occurred while executing 'keyevent':
java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:911)
        at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
        at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
        at com.android.server.input.InputShellCommand.injectKeyEvent(InputShellCommand.java:124)
        at com.android.server.input.InputShellCommand.sendKeyEvent(InputShellCommand.java:377)
        at com.android.server.input.InputShellCommand.runKeyEvent(InputShellCommand.java:365)
        at com.android.server.input.InputShellCommand.onCommand(InputShellCommand.java:253)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.input.InputManagerService.onShellCommand(InputManagerService.java:3438)
        at android.os.Binder.shellCommand(Binder.java:1075)
        at android.os.Binder.onTransact(Binder.java:895)
        at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:1357)
        at android.os.Binder.execTransactInternal(Binder.java:1351)
        at android.os.Binder.execTransact(Binder.java:1282)


**Injecting input events requires the caller have the INJECT_EVENTS permission**

**Comment by rom1v** [comment]
> Injecting input events requires the caller have the INJECT_EVENTS permission

https://github.com/Genymobile/scrcpy#prerequisites

**Comment by sinnren** [comment]
> > Injecting input events requires the caller have the INJECT_EVENTS permission
> 
> https://github.com/Genymobile/scrcpy#prerequisites

copy that.thx.
