### ISSUE TITLE
Random fails on Samsung Android 14

### ISSUE THREAD

**Issue by krishtoautomate** [Genymobile/scrcpy#5003]
**Environment**
 - OS: [macOS]
 - scrcpy version: [2.4]
 - installation method: [brew]
 - device model: samsung S22+
 - Android version: [14]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
06-19 13:30:42.023 27460 27460 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
06-19 13:30:42.024 27460 27460 I scrcpy  : Device: [samsung] samsung SM-S906W (Android 14)
06-19 13:30:42.087 11070 11374 I SurfaceFlinger: createDisplay:scrcpy
06-19 13:30:42.087 11458 12076 I DisplayDeviceRepository: Display device added: DisplayDeviceInfo{"scrcpy": uniqueId="virtual:com.android.shell,2000,scrcpy,2", 1 x 1, modeId 26, renderFrameRate 60.0, defaultModeId 26, supportedModes [{id=26, width=1, height=1, fps=60.0, alternativeRefreshRates=[], supportedHdrTypes=[]}], colorMode 0, supportedColorModes [0], hdrCapabilities null, allmSupported false, gameContentTypeSupported false, density 1, 1.0 x 1.0 dpi, appVsyncOff 0, presDeadline 16666666, touch NONE, rotation 0, type VIRTUAL, deviceProductInfo null, state OFF, committedState UNKNOWN, owner com.android.shell (uid 2000), frameRateOverride , brightnessMinimum 0.0, brightnessMaximum 0.0, brightnessDefault 0.0, hdrSdrRatio NaN, FLAG_PRIVATE, installOrientation 0, displayShape DisplayShape{ spec=-1569981477 displayWidth=1 displayHeight=1 physicalPixelDisplaySizeRatio=1.0 rotation=0 offsetX=0 offsetY=0 scale=1.0}}
06-19 13:30:42.091 11458 12076 I LogicalDisplayMapper: Adding new display: 16: DisplayInfo{"scrcpy", displayId 16, displayGroupId 0, FLAG_PRIVATE, real 1 x 1, largest app 1 x 1, smallest app 1 x 1, appVsyncOff 0, presDeadline 16666666, mode 2660.0, defaultMode 26, REFRESH_RATE_MODE_NORMAL, modes [{id=26, width=1, height=1, fps=60.0, alternativeRefreshRates=[], supportedHdrTypes=[]}], hdrCapabilities null, userDisabledHdrTypes [], minimalPostProcessingSupported false, rotation 0, state OFF, committedState UNKNOWN, type VIRTUAL, uniqueId "virtual:com.android.shell,2000,scrcpy,2", app 1 x 1, density 1 (1.0 x 1.0) dpi, layerStack 16, colorMode 0, supportedColorModes [0], deviceProductInfo null, owner com.android.shell (uid 2000), removeMode 1, refreshRateOverride 0.0, brightnessMinimum 0.0, brightnessMaximum 0.0, brightnessDefault 0.0, installOrientation ROTATION_0, layoutLimitedRefreshRate null, hdrSdrRatio not_available, thermalRefreshRateThrottling {}, thermalBrightnessThrottlingDataId default}
06-19 13:30:42.119 11070 11374 I SurfaceFlinger: id=1075 createSurf, flag=84404, Display 16 name="scrcpy"#1075
06-19 13:30:42.131 11458 11625 I DisplayPowerController2[16]: BrightnessEvent: disp=16, physDisp=virtual:com.android.shell,2000,scrcpy,2, brt=0.0, initBrt=NaN, rcmdBrt=NaN, preBrt=NaN, lux=0.0, preLux=0.0, hbmMax=2.4, hbmMode=off, rbcStrength=-1, thrmMax=1.0, powerFactor=1.0, wasShortTermModelActive=false, flags=, reason=manual, autoBrightness=true, strategy=InvalidBrightnessStrategy
06-19 13:30:42.192 27474 27474 W ziparchive: Unable to open '/data/local/tmp/scrcpy-server.dm': No such file or directory
06-19 13:30:42.208 27474 27474 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.CleanUp

```

```
/opt/homebrew/Cellar/scrcpy/2.4_1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 96.6 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [samsung] samsung SM-S906W (Android 14)
[server] ERROR: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:89)
	at com.genymobile.scrcpy.Device.<init>(Device.java:73)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:121)
	at com.genymobile.scrcpy.Server.internalMain(Server.java:259)
	at com.genymobile.scrcpy.Server.main(Server.java:214)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:385)
```

```
/opt/homebrew/Cellar/scrcpy/2.4_1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 266.5 MB/s (69007 bytes in 0.000s)
[server] INFO: Device: [samsung] samsung SM-S906W (Android 14)
[server] ERROR: java.lang.reflect.InvocationTargetException
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:103)
	at com.genymobile.scrcpy.Device.<init>(Device.java:73)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:121)
	at com.genymobile.scrcpy.Server.internalMain(Server.java:259)
	at com.genymobile.scrcpy.Server.main(Server.java:214)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:385)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:89)
	... 6 more
Caused by: android.os.DeadSystemRuntimeException: android.os.DeadSystemException
	at android.hardware.display.DisplayManagerGlobal$1.recompute(DisplayManagerGlobal.java:200)
	at android.hardware.display.DisplayManagerGlobal$1.recompute(DisplayManagerGlobal.java:194)
	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:999)
	at android.hardware.display.DisplayManagerGlobal.getDisplayInfoLocked(DisplayManagerGlobal.java:245)
	at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:234)
	... 8 more
Caused by: android.os.DeadSystemException
	... 13 more
```

**Comment by krishtoautomate** [comment]
```
06-19 13:32:38.430 28821 28821 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.CleanUp
06-19 13:32:52.896 28806 28806 E scrcpy  : java.lang.reflect.InvocationTargetException
06-19 13:32:52.896 28806 28806 E scrcpy  : DeadSystemException: The system died; earlier logs will point to the root cause
06-19 13:32:52.935 28821 28821 I scrcpy  : Cleaning up
06-19 13:32:52.939 28821 28821 E AndroidRuntime: 	at com.genymobile.scrcpy.wrappers.PowerManager.getIsScreenOnMethod(PowerManager.java:28)
06-19 13:32:52.939 28821 28821 E AndroidRuntime: 	at com.genymobile.scrcpy.wrappers.PowerManager.isScreenOn(PowerManager.java:35)
06-19 13:32:52.939 28821 28821 E AndroidRuntime: 	at com.genymobile.scrcpy.Device.isScreenOn(Device.java:258)
06-19 13:32:52.939 28821 28821 E AndroidRuntime: 	at com.genymobile.scrcpy.CleanUp.main(CleanUp.java:135)
06-19 13:33:06.639 31803 31803 W ziparchive: Unable to open '/data/local/tmp/scrcpy-server.dm': No such file or directory
06-19 13:33:06.668 31803 31803 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
```
