### ISSUE TITLE
Install Script: Server Version mismatch Client Version

### ISSUE THREAD

**Issue by WAYutong** [Genymobile/scrcpy#5033]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Fedora 40.]
 - scrcpy version: [2.4 and 2.3.1]
 - installation method: [ manual build]

**Describe the bug**
Download serv version is error install_realease.sh

**Comment by rom1v** [comment]
Don't execute `install_release.sh` from a tag, but one commit after: https://github.com/Genymobile/scrcpy/issues/4098#issuecomment-1600332180

**Comment by ju-sh** [comment]
I got the same problem. But I downloaded v3.3.4 release. Built with ninja.

But when running getting this error:

```
user@host:~/scrcpy-master$ ./build-auto/app/scrcpy

scrcpy 3.3.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  P3TX205P7WR                     device  SM_M132E
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 72.0 MB/s (90164 bytes in 0.001s)
[server] ERROR: The server version (3.3.3) does not match the client (3.3.4)
java.lang.IllegalArgumentException: The server version (3.3.3) does not match the client (3.3.4)
        at com.genymobile.scrcpy.Options.parse(Options.java:299)
        at com.genymobile.scrcpy.Server.internalMain(Server.java:234)
        at com.genymobile.scrcpy.Server.main(Server.java:215)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:415)
ERROR: Server connection failed
```

I have previously used an older version of scrcpy. Is remains of it still there? 

Any pointers for fixing this anyone?

Thanks.

**Comment by ju-sh** [comment]
Never mind, I deleted the old server and it works!
