### ISSUE TITLE
Turn Device Screen Off (Keep Mirroring) does not work

### ISSUE THREAD

**Issue by zhousec** [Genymobile/scrcpy#5059]
Android13，OnePlus Ace3pro

[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getPhysicalDisplayIds []
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetPhysicalDisplayIdsMethod(SurfaceControl.java:137)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getPhysicalDisplayIds(SurfaceControl.java:144)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:319)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:169)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Could not get physical display ids

**Comment by rom1v** [comment]
Which scrcpy version?

**Comment by zhousec** [comment]
> Which scrcpy version?
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>

Dependencies (compiled / linked):
 - SDL: 2.28.0 / 2.28.0
 - libavcodec: 60.3.100 / 60.3.100
 - libavformat: 60.3.100 / 60.3.100
 - libavutil: 58.2.100 / 58.2.100
 - libusb: - / 1.0.26

**Comment by zhousec** [comment]
> Which scrcpy version?

Is it because the phone has a password

**Comment by rom1v** [comment]
> scrcpy 2.1.1

Try the latest version (currently 2.5).

**Comment by zhousec** [comment]
> > scrcpy 2.1.1
> 
> Try the latest version (currently 2.5).

Version 2.5 solves this problem, thanks
