### ISSUE TITLE
Input thread errors when certain functions don't exist like expandNotificationsPanel

### ISSUE THREAD

**Issue by MatthewScholefield** [Genymobile/scrcpy#506]
It appears my phone (Oneplus 3) doesn't have an `expandNotificationsPanel` function so when I press `ctrl+n` I get:
```
java.lang.AssertionError: java.lang.NoSuchMethodException: expandNotificationsPanel []
	at com.genymobile.scrcpy.wrappers.StatusBarManager.<init>(StatusBarManager.java:20)
	at com.genymobile.scrcpy.wrappers.ServiceManager.getStatusBarManager(ServiceManager.java:67)
	at com.genymobile.scrcpy.Device.collapsePanels(Device.java:140)
	at com.genymobile.scrcpy.EventController.executeCommand(EventController.java:179)
	at com.genymobile.scrcpy.EventController.handleEvent(EventController.java:81)
	at com.genymobile.scrcpy.EventController.control(EventController.java:61)
	at com.genymobile.scrcpy.Server$1.run(Server.java:40)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoSuchMethodException: expandNotificationsPanel []
	at java.lang.Class.getMethod(Class.java:2068)
	at java.lang.Class.getMethod(Class.java:1690)
	at com.genymobile.scrcpy.wrappers.StatusBarManager.<init>(StatusBarManager.java:17)
	... 7 more
```
Afterwards, input no longer works. Perhaps this should be caught and ignored (or outputted as a message to the console)?

**Comment by rom1v** [comment]
Thank you for the report.

**Comment by rom1v** [comment]
Fixed on `dev`.
