### ISSUE TITLE
小米14链接出现问题，无法从电脑操作手机

### ISSUE THREAD

**Issue by ggforlove** [Genymobile/scrcpy#5080]
INFO: ADB device found:
INFO:     -->   (usb)  3ee8f4b0                        device  23116PN5BC
C:\Users\admin\AppData\Local\Temp\MicrosoftEdgeDownloads\8... file pushed, 0 skipped. 64.2 MB/s (69624 bytes in 0.001s)
[server] INFO: Device: [Xiaomi] Xiaomi 23116PN5BC (Android 14)
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:230)
        at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:241)
        at com.genymobile.scrcpy.Device.pressReleaseKeycode(Device.java:249)
        at com.genymobile.scrcpy.Device.pressReleaseKeycode(Device.java:254)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:105)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
        at android.os.Parcel.createException(Parcel.java:3041)
        at android.os.Parcel.readException(Parcel.java:3024)
        at android.os.Parcel.readException(Parcel.java:2966)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1575)
        at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
        at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
        ... 10 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:911)
        at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:744)
        at android.os.Binder.execTransactInternal(Binder.java:1346)
        at android.os.Binder.execTransact(Binder.java:1282)

INFO: Renderer: direct3d
INFO: Texture: 1080x2400

**Comment by q947721485** [comment]
找到开发者选项->USB调试（安全设置）允许通过USB调试修修改权限或者模拟点击

**Comment by ggforlove** [comment]
谢谢
