### ISSUE TITLE
Android 14 audio forwarding did not work as expected

### ISSUE THREAD

**Issue by wrtppp** [Genymobile/scrcpy#5138]
## Environment

 - **OS:   windows10
 - **Scrcpy version:   2.5
 - **Installation method:   manual build
 - **Device model:   xiaomi8se
 - **Android version:   13

## Describe the bug
I'm sorry, I'm not proficient in English, the following is a machine translation
Hello developers.

The problem I have is that after starting scrcpy without adding any parameters, the computer side does not receive the content of the audio forwarding (no sound from the phone), the phone speaker is working properly, how can I fix it

##errors

[server] ERROR: Exception on thread Thread[audio-encoder,5,main]

```
Please paste terminal output in a code block.
```
F:\scrcpy-win64-v2.5\scrcpy-server: 1 file pushed, 0 skipped. 28.2 MB/s (69624 bytes in 0.002s)
[server] INFO: Device: [Xiaomi] Xiaomi MI 8 SE (Android 13)
INFO: Renderer: direct3d
INFO: Texture: 1080x2240
WARN: Demuxer 'audio': stream explicitly disabled by the device
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.UnsupportedOperationException: Cannot create AudioRecord
        at android.media.AudioRecord$Builder.build(AudioRecord.java:982)
        at com.genymobile.scrcpy.FakeContext$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
        at com.genymobile.scrcpy.AudioCapture.createAudioRecord(AudioCapture.java:68)
        at com.genymobile.scrcpy.AudioCapture.startRecording(AudioCapture.java:111)
        at com.genymobile.scrcpy.AudioCapture.start(AudioCapture.java:130)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:190)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:121)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
[server] INFO: Device screen turned off

**Comment by rom1v** [comment]
Hmmm, `createAudioRecord()` was modified on your vendor rom, it does not behave like AOSP.

Out of curiosity, could you test the new playback capture method in #5102?

**Comment by wrtppp** [comment]
> 嗯，在您的供应商 rom 上进行了修改，它的行为不像 AOSP。`createAudioRecord()`
> 
> 出于好奇，您可以测试[一下 #5102](https://github.com/Genymobile/scrcpy/pull/5102) 中的新播放捕获方法吗？
Hello, I downloaded and used scrcpy-win64-v2.5-34-gb417c5441, and set the parameter playback, scrcpy still has no audio forwarding.

##error
[server] ERROR: Could not capture audio playback
Wjava.lang.RuntimeException: registerAudioPolicy() returned -1ARN: Demu
x       at com.genymobile.scrcpy.audio.AudioPlaybackCapture.createAudioRecord(AudioPlaybackCapture.java:97)e
r 'au   at com.genymobile.scrcpy.audio.AudioPlaybackCapture.start(AudioPlaybackCapture.java:119)d
        at com.genymobile.scrcpy.audio.AudioEncoder.encode(AudioEncoder.java:202)i
o       at com.genymobile.scrcpy.audio.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:131)
'       at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012):
 stream explicitly disabled by the device

**Comment by wrtppp** [comment]
Hello, I changed to an Android 11 ROM, scrcpy can run normally, it is true that the previous ROM has a problem that causes it to not work normally
