### ISSUE TITLE
Android 14 cannot be operated using a mouse.

### ISSUE THREAD

**Issue by ikool-cn** [Genymobile/scrcpy#5159]
## Environment

 - **OS:** ubuntu 22
 - **Scrcpy version:** 1.24
 - **Installation method:** 
 - **Device model:** 
 - **Android version:** 14

## Describe the bug

Android 14 cannot be operated using a mouse.

```
scrcpy
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 6.2 MB/s (40689 bytes in 0.006s)
[server] INFO: Device: Xiaomi 2211133C (Android 14)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
        at com.genymobile.scrcpy.Device.<init>(Device.java:103)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:65)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:368)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.2.5
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2400
[server] ERROR: Exception on thread Thread[Thread-2,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:65)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:199)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:223)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:98)
        at com.genymobile.scrcpy.Controller.control(Controller.java:75)
        at com.genymobile.scrcpy.Server$3.run(Server.java:133)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:62)
        ... 7 more
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:207)
        at android.hardware.input.InputManager.getInstance(InputManager.java:271)
        ... 9 more

```

**Comment by rom1v** [comment]
> Scrcpy version: 1.24

Obsolete version. Use the latest one.
