### ISSUE TITLE
Scrcpy 2.6 cannot use mouse operation on Android 14.

### ISSUE THREAD

**Issue by ikool-cn** [Genymobile/scrcpy#5161]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** Ubuntu 22.04
 - **Scrcpy version:** 2.6
 - **Installation method:** github source
 - **Device model:** XiaoMi13
 - **Android version:** 14

## Describe the bug

scrcpy 2.6 cannot use mouse operation on Android 14.

```
scrcpy --no-clipboard-autosync
scrcpy 2.6 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  470affa2                        device  2211133C
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 154.9 MB/s (71084 bytes in 0.000s)
[server] INFO: Device: [Xiaomi] Xiaomi 2211133C (Android 14)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.2.5
INFO: Trilinear filtering enabled
INFO: Texture: 1080x2400
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:234)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:238)
	at com.genymobile.scrcpy.control.Controller.injectTouch(Controller.java:367)
	at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:167)
	at com.genymobile.scrcpy.control.Controller.control(Controller.java:102)
	at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:110)
	at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1590)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
	... 10 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:911)
	at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:752)
	at android.os.Binder.execTransactInternal(Binder.java:1346)
	at android.os.Binder.execTransact(Binder.java:1282)

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:234)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:238)
	at com.genymobile.scrcpy.control.Controller.injectTouch(Controller.java:367)
	at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:167)
	at com.genymobile.scrcpy.control.Controller.control(Controller.java:102)
	at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:110)
	at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1590)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
	... 10 more
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:234)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:238)
	at com.genymobile.scrcpy.control.Controller.injectTouch(Controller.java:367)
	at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:167)
	at com.genymobile.scrcpy.control.Controller.control(Controller.java:102)
	at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:110)
	at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1590)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
	... 10 more
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:234)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:238)
	at com.genymobile.scrcpy.control.Controller.injectTouch(Controller.java:367)
	at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:167)
	at com.genymobile.scrcpy.control.Controller.control(Controller.java:102)
	at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:110)
	at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1590)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
	... 10 more
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:234)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:238)
	at com.genymobile.scrcpy.control.Controller.injectTouch(Controller.java:367)
	at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:167)
	at com.genymobile.scrcpy.control.Controller.control(Controller.java:102)
	at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:110)
	at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1590)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
	... 10 more
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:234)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:238)
	at com.genymobile.scrcpy.control.Controller.injectTouch(Controller.java:367)
	at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:167)
	at com.genymobile.scrcpy.control.Controller.control(Controller.java:102)
	at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:110)
	at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1590)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
	... 10 more
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:234)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:238)
	at com.genymobile.scrcpy.control.Controller.injectTouch(Controller.java:367)
	at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:167)
	at com.genymobile.scrcpy.control.Controller.control(Controller.java:102)
	at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:110)
	at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1590)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
	... 10 more
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:234)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:238)
	at com.genymobile.scrcpy.control.Controller.injectTouch(Controller.java:367)
	at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:167)
	at com.genymobile.scrcpy.control.Controller.control(Controller.java:102)
	at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:110)
	at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1590)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
	... 10 more
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:234)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:238)
	at com.genymobile.scrcpy.control.Controller.injectTouch(Controller.java:367)
	at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:167)
	at com.genymobile.scrcpy.control.Controller.control(Controller.java:102)
	at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:110)
	at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1590)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
	... 10 more
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:234)
	at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:238)
	at com.genymobile.scrcpy.control.Controller.injectTouch(Controller.java:367)
	at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:167)
	at com.genymobile.scrcpy.control.Controller.control(Controller.java:102)
	at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:110)
	at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1590)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
	... 10 more
```

**Comment by rom1v** [comment]
Read https://github.com/Genymobile/scrcpy#prerequisites

**Comment by ikool-cn** [comment]
@rom1v Works fine for me! Thank you.
