### ISSUE TITLE
scrcpy 2.6 crash (error code provided)

### ISSUE THREAD

**Issue by Shashlik1337** [Genymobile/scrcpy#5164]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS: Windows 11 23H2** [e.g. Debian, Windows, macOS...]
 - **Scrcpy version: 2.6** [e.g. 2.5]
 - **Installation method: Windows release** [e.g. manual build, apt, snap, brew, Windows release...]
 - **Device model: Xiaomi POCO X6 Pro (2311drk48g)**
 - **Android version: 14** [e.g. 14]

## Describe the bug
Some time after the launch "scrcpy.exe " the window closes without notification. There is a code in the terminal that I provided below. With other launch methods, the situation is similar

On errors, please provide the output of the console (and `adb logcat` if relevant).
```
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
        at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:234)
        at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:238)
        at com.genymobile.scrcpy.control.Controller.injectTouch(Controller.java:367)
        at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:167)
        at com.genymobile.scrcpy.control.Controller.control(Controller.java:102)
        at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:110)
        at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
        at android.os.Parcel.createException(Parcel.java:3041)
        at android.os.Parcel.readException(Parcel.java:3024)
        at android.os.Parcel.readException(Parcel.java:2966)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1590)
        at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
        at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
        ... 10 more

```
```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
> Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.

Please read https://github.com/Genymobile/scrcpy#prerequisites
