### ISSUE TITLE
Unable to utilize -S parameter to turn screen off, alt+o also does not work. 

### ISSUE THREAD

**Issue by Haunter** [Genymobile/scrcpy#5179]
I have run scrpy with screen off without issue until Android 14.

## Environment

 - **OS:**Windows 11
 - **Scrcpy version:** 2.6.1
 - **Installation method:** Windows standalone (x64 zip)
 - **Device model:** Onpelus Open
 - **Android version:** 14

## Describe the bug

When launching scrpy with the -S parameter or attempting to use alt+o the screen does not stay off. 

Here is what the commandline spits out in powershell:

[server] INFO: Device: [OnePlus] OnePlus CPH2551 (Android 14)
INFO: Renderer: direct3d
INFO: Texture: 648x1440
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getPhysicalDisplayIds []
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetPhysicalDisplayIdsMethod(SurfaceControl.java:137)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getPhysicalDisplayIds(SurfaceControl.java:144)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:319)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:169)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Could not get physical display ids

**Comment by rom1v** [comment]
> Scrcpy version: 2.6.1

That does not match the stack trace. Please test with 2.6.1.

**Comment by Haunter** [comment]
Whoops, I forgot to CD into the newly download zip. Sorry about that. thank you!
