### ISSUE TITLE
 execute adb shell app_process error

### ISSUE THREAD

**Issue by Bretterman** [Genymobile/scrcpy#5191]
this is the problem I encountered when I wanted to use javaweb as the client and deploy the server according to the documentation
command is : 

C:\Users\a1\Desktop\a>adb -s c0b43151 shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 2.6.1

[server] INFO: Device: [Xiaomi] Xiaomi MI 8 Lite (Android 10)
[server] ERROR: Connection refused
java.io.IOException: Connection refused
        at android.net.LocalSocketImpl.connectLocal(Native Method)
        at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:296)
        at android.net.LocalSocket.connect(LocalSocket.java:147)
        at com.genymobile.scrcpy.device.DesktopConnection.connect(DesktopConnection.java:43)
        at com.genymobile.scrcpy.device.DesktopConnection.open(DesktopConnection.java:93)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:151)
        at com.genymobile.scrcpy.Server.internalMain(Server.java:290)
        at com.genymobile.scrcpy.Server.main(Server.java:245)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
        

1.  Is there something wrong with the operation?

**Comment by Bretterman** [comment]
and after executing this command, the pushed jar package will be automatically deleted

**Comment by rom1v** [comment]
> [server] ERROR: Connection refused

Did you `adb forward` or `adb reverse` before executing? See https://github.com/Genymobile/scrcpy/blob/master/doc/develop.md#standalone-server

> and after executing this command, the pushed jar package will be automatically deleted

That's expected, scrcpy does not leave anything on the device.

You can add `cleanup=false` as a server parameter (or `--no-cleanup` in the scrcpy client) to avoid that.

**Comment by Bretterman** [comment]
Thank you for your reply. I will try again

**Comment by Bretterman** [comment]
Already solved
