### ISSUE TITLE
ERROR: Could not invoke method...

### ISSUE THREAD

**Issue by Marietto2008** [Genymobile/scrcpy#5213]
Hello to everyone

I'm trying to connect scrcpy via wi-fi because I want to share and control Android (14,installed on the Raspberry Pi 4) through my PC (where I have installed Ubuntu 24.04). The internal IP number of Android is 192.168.1.6. Android is connected to the Internet via ethernet. Ubuntu 24.04 is connected also via Ethernet. This is what I did :

On Ubuntu 24.04 : 

```
# adb connect 192.168.1.6:5555

connected to 192.168.1.6:5555

# adb devices

List of devices attached
192.168.1.6:5555        device

# scrcpy --tcpip=192.168.1.6:5555

scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 501.7 MB/s (41650 bytes in 0.000s)
[server] INFO: Device: Raspberry Raspberry Pi 4 (Android 14)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, class java.lang.String, int]
        at java.lang.Class.getMethod(Class.java:2950)
        at java.lang.Class.getMethod(Class.java:2450)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:128)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:138)
        at com.genymobile.scrcpy.Device.<init>(Device.java:100)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
        at com.genymobile.scrcpy.Server.main(Server.java:334)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
        at com.genymobile.scrcpy.ScreenEncoder.createDisplay(ScreenEncoder.java:278)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:334)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
        at java.lang.Class.getMethod(Class.java:2950)
        at java.lang.Class.getMethod(Class.java:2450)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:81)
        ... 7 more
INFO: Renderer: opengl
INFO: OpenGL version: 4.3 (Compatibility Profile) Mesa 24.0.9-0ubuntu0.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 1920x1080
WARN: Device disconnected
WARN: Killing the server...
```

On Android I have enabled the USB and the WIFI Debug on the Developer options....

**Comment by rom1v** [comment]
> scrcpy 1.25

Too old and obsolete version.

Install the latest (currently 2.6.1): https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by Marietto2008** [comment]
```
ziomario@Z390-AORUS-PRO-DEST:~/Scrivania$ sudo apt install ffmpeg libsdl2-2.0-0 adb wget \

                 gcc git pkg-config meson ninja-build libsdl2-dev \
                 libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev \
                 libswresample-dev libusb-1.0-0 libusb-1.0-0-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:6.1.1-3ubuntu5).
libsdl2-2.0-0 is already the newest version (2.30.0+dfsg-1build3).
adb is already the newest version (1:34.0.4-1build3).
wget is already the newest version (1.21.4-1ubuntu4.1).
gcc is already the newest version (4:13.2.0-7ubuntu1).
git is already the newest version (1:2.43.0-1ubuntu7.1).
pkg-config is already the newest version (1.8.1-2build1).
meson is already the newest version (1.3.2-1ubuntu1).
ninja-build is already the newest version (1.11.1-2).
libsdl2-dev is already the newest version (2.30.0+dfsg-1build3).
libavutil-dev is already the newest version (7:6.1.1-3ubuntu5).
libswresample-dev is already the newest version (7:6.1.1-3ubuntu5).
libusb-1.0-0 is already the newest version (2:1.0.27-1).
libusb-1.0-0-dev is already the newest version (2:1.0.27-1).
The following additional packages will be installed:
  libavfilter-dev libpostproc-dev libswscale-dev
The following NEW packages will be installed:
  libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libpostproc-dev libswscale-dev
0 upgraded, 6 newly installed, 0 to remove and 2 not upgraded.
Need to get 10,5 MB of archives.
After this operation, 40,4 MB of additional disk space will be used.
Do you want to continue? [S/n] s
Get:1 http://it.archive.ubuntu.com/ubuntu noble/universe amd64 libavcodec-dev amd64 7:6.1.1-3ubuntu5 [6.504 kB]
Get:2 http://it.archive.ubuntu.com/ubuntu noble/universe amd64 libavformat-dev amd64 7:6.1.1-3ubuntu5 [1.398 kB]
Get:3 http://it.archive.ubuntu.com/ubuntu noble/universe amd64 libpostproc-dev amd64 7:6.1.1-3ubuntu5 [50,3 kB]
Get:4 http://it.archive.ubuntu.com/ubuntu noble/universe amd64 libswscale-dev amd64 7:6.1.1-3ubuntu5 [224 kB]
Get:5 http://it.archive.ubuntu.com/ubuntu noble/universe amd64 libavfilter-dev amd64 7:6.1.1-3ubuntu5 [2.265 kB]
Get:6 http://it.archive.ubuntu.com/ubuntu noble/universe amd64 libavdevice-dev amd64 7:6.1.1-3ubuntu5 [94,6 kB]
Fetched 10,5 MB in 2s (4.975 kB/s)        
Selecting previously unselected package libavcodec-dev:amd64.
(Reading database ... 1075563 files and directories currently installed.)
Preparing to unpack .../0-libavcodec-dev_7%3a6.1.1-3ubuntu5_amd64.deb ...
Unpacking libavcodec-dev:amd64 (7:6.1.1-3ubuntu5) ...
Selecting previously unselected package libavformat-dev:amd64.
Preparing to unpack .../1-libavformat-dev_7%3a6.1.1-3ubuntu5_amd64.deb ...
Unpacking libavformat-dev:amd64 (7:6.1.1-3ubuntu5) ...
Selecting previously unselected package libpostproc-dev:amd64.
Preparing to unpack .../2-libpostproc-dev_7%3a6.1.1-3ubuntu5_amd64.deb ...
Unpacking libpostproc-dev:amd64 (7:6.1.1-3ubuntu5) ...
Selecting previously unselected package libswscale-dev:amd64.
Preparing to unpack .../3-libswscale-dev_7%3a6.1.1-3ubuntu5_amd64.deb ...
Unpacking libswscale-dev:amd64 (7:6.1.1-3ubuntu5) ...
Selecting previously unselected package libavfilter-dev:amd64.
Preparing to unpack .../4-libavfilter-dev_7%3a6.1.1-3ubuntu5_amd64.deb ...
Unpacking libavfilter-dev:amd64 (7:6.1.1-3ubuntu5) ...
Selecting previously unselected package libavdevice-dev:amd64.
Preparing to unpack .../5-libavdevice-dev_7%3a6.1.1-3ubuntu5_amd64.deb ...
Unpacking libavdevice-dev:amd64 (7:6.1.1-3ubuntu5) ...
Setting up libavcodec-dev:amd64 (7:6.1.1-3ubuntu5) ...
Setting up libpostproc-dev:amd64 (7:6.1.1-3ubuntu5) ...
Setting up libavformat-dev:amd64 (7:6.1.1-3ubuntu5) ...
Setting up libswscale-dev:amd64 (7:6.1.1-3ubuntu5) ...
Setting up libavfilter-dev:amd64 (7:6.1.1-3ubuntu5) ...
Setting up libavdevice-dev:amd64 (7:6.1.1-3ubuntu5) ...

ziomario@Z390-AORUS-PRO-DEST:~/Scaricati$ git clone https://github.com/Genymobile/scrcpy

Cloning into 'scrcpy'...
remote: Enumerating objects: 33566, done.
remote: Counting objects: 100% (732/732), done.
remote: Compressing objects: 100% (295/295), done.
remote: Total 33566 (delta 388), reused 575 (delta 339), pack-reused 32834 (from 1)
Receiving objects: 100% (33566/33566), 6.44 MiB | 9.23 MiB/s, done.
Resolving deltas: 100% (21709/21709), done.

ziomario@Z390-AORUS-PRO-DEST:~/Scaricati$ cd scrcpy

ziomario@Z390-AORUS-PRO-DEST:~/Scaricati/scrcpy$ ./install_release.sh

[scrcpy] Downloading prebuilt server...
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/ziomario/.wget-hsts'. HSTS will be disabled.
--2024-08-17 22:42:36--  https://github.com/Genymobile/scrcpy/releases/download/v2.6.1/scrcpy-server-v2.6.1
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/111583593/4dbb38d6-abfd-40ed-884e-b0cfcfda0f47?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240817%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240817T204236Z&X-Amz-Expires=300&X-Amz-Signature=1005a537ca6951faaddf95f67d3ba27a0a8c2c458868ddd4733d478a9b5f1893&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=111583593&response-content-disposition=attachment%3B%20filename%3Dscrcpy-server-v2.6.1&response-content-type=application%2Foctet-stream [following]
--2024-08-17 22:42:36--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/111583593/4dbb38d6-abfd-40ed-884e-b0cfcfda0f47?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240817%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240817T204236Z&X-Amz-Expires=300&X-Amz-Signature=1005a537ca6951faaddf95f67d3ba27a0a8c2c458868ddd4733d478a9b5f1893&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=111583593&response-content-disposition=attachment%3B%20filename%3Dscrcpy-server-v2.6.1&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 71112 (69K) [application/octet-stream]
Saving to: ‘scrcpy-server’

scrcpy-server                     100%[============================================================>]  69,45K  --.-KB/s    in 0,04s   

2024-08-17 22:42:37 (1,82 MB/s) - ‘scrcpy-server’ saved [71112/71112]

[scrcpy] Verifying prebuilt server...
scrcpy-server: OK
[scrcpy] Building client...
The Meson build system
Version: 1.3.2
Source dir: /home/ziomario/Scaricati/scrcpy
Build dir: /home/ziomario/Scaricati/scrcpy/build-auto
Build type: native build
Project name: scrcpy
Project version: 2.6.1
C compiler for the host machine: cc (gcc 13.2.0 "cc (Ubuntu 13.2.0-23ubuntu4) 13.2.0")
C linker for the host machine: cc ld.bfd 2.42
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (/usr/bin/pkg-config) 1.8.1
Run-time dependency libavformat found: YES 60.16.100
Run-time dependency libavcodec found: YES 60.31.102
Run-time dependency libavutil found: YES 58.29.100
Run-time dependency libswresample found: YES 4.12.100
Run-time dependency sdl2 found: YES 2.30.0
Run-time dependency libavdevice found: YES 60.3.100
Run-time dependency libusb-1.0 found: YES 1.0.27
Checking for function "strdup" : YES 
Checking for function "asprintf" : YES 
Checking for function "vasprintf" : YES 
Checking for function "nrand48" : YES 
Checking for function "jrand48" : YES 
Checking for function "reallocarray" : YES 
Header "sys/socket.h" has symbol "SOCK_CLOEXEC" : YES 
Configuring config.h using configuration
Build targets in project: 2

scrcpy 2.6.1

  User defined options
    buildtype      : release
    strip          : true
    b_lto          : true
    prebuilt_server: scrcpy-server

Found ninja-1.11.1 at /usr/bin/ninja
[69/69] Linking target app/scrcpy
[scrcpy] Installing (sudo)...
[0/1] Installing files.
Installing app/scrcpy to /usr/local/bin
Stripping target 'app/scrcpy'.
Installing server/scrcpy-server to /usr/local/share/scrcpy
Installing /home/ziomario/Scaricati/scrcpy/app/scrcpy.1 to /usr/local/share/man/man1
Installing /home/ziomario/Scaricati/scrcpy/app/data/icon.png to /usr/local/share/icons/hicolor/256x256/apps
Installing /home/ziomario/Scaricati/scrcpy/app/data/zsh-completion/_scrcpy to /usr/local/share/zsh/site-functions
Installing /home/ziomario/Scaricati/scrcpy/app/data/bash-completion/scrcpy to /usr/local/share/bash-completion/completions
Installing /home/ziomario/Scaricati/scrcpy/app/data/scrcpy.desktop to /usr/local/share/applications
Installing /home/ziomario/Scaricati/scrcpy/app/data/scrcpy-console.desktop to /usr/local/share/applications
ziomario@Z390-AORUS-PRO-DEST:~/Scaricati/scrcpy$ scrcpy --version
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>

Dependencies (compiled / linked):
 - SDL: 2.28.2 / 2.30.0
 - libavcodec: 60.3.100 / 60.31.102
 - libavformat: 60.3.100 / 60.16.100
 - libavutil: 58.2.100 / 58.29.100
 - libavdevice: 60.1.100 / 60.3.100
 - libusb: - / 1.0.27

ziomario@Z390-AORUS-PRO-DEST:~/Scaricati/scrcpy$ scrcpy --tcpip=192.168.1.6:5555

scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
INFO: Connecting to 192.168.1.6:5555...
INFO: Connected to 192.168.1.6:5555
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 472.5 MB/s (41650 bytes in 0.000s)
[server] INFO: Device: Raspberry Raspberry Pi 4 (Android 14)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, class java.lang.String, int]
        at java.lang.Class.getMethod(Class.java:2950)
        at java.lang.Class.getMethod(Class.java:2450)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:128)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:138)
        at com.genymobile.scrcpy.Device.<init>(Device.java:100)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
        at com.genymobile.scrcpy.Server.main(Server.java:334)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
        at com.genymobile.scrcpy.ScreenEncoder.createDisplay(ScreenEncoder.java:278)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:334)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
        at java.lang.Class.getMethod(Class.java:2950)
        at java.lang.Class.getMethod(Class.java:2450)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:81)
        ... 7 more
INFO: Renderer: opengl
INFO: OpenGL version: 4.3 (Compatibility Profile) Mesa 24.0.9-0ubuntu0.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 1920x1080
WARN: Device disconnected
WARN: Killing the server...
```
