### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by lzb-libra** [Genymobile/scrcpy#5228]
## Environment

 - **OS:** Windows
 - **Scrcpy version: 2.6.1
 - **Installation method: Windows release
 - **Device model:**
 - **Android version: 13

## Describe the bug
Start up error, although it doesn't affect usage, it still doesn't look good.

scrcpy 2.6.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  8c3b4548                        device  parrot_for_arm64
D:\Program\ADB-scrcpy\scrcpy-win64-v2.6.1\scrcpy-server: 1 file pushed, 0 skipped. 79.9 MB/s (71112 bytes in 0.001s)
[server] INFO: Device: [QUALCOMM] qti parrot for arm64 (Android 13)
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.IllegalArgumentException: Invalid buffer size -16
        at android.media.AudioRecord$Builder.setBufferSizeInBytes(AudioRecord.java:691)
        at com.genymobile.scrcpy.FakeContext$$ExternalSyntheticApiModelOutline0.m$1(D8$$SyntheticClass:0)
        at com.genymobile.scrcpy.audio.AudioDirectCapture.createAudioRecord(AudioDirectCapture.java:60)
        at com.genymobile.scrcpy.audio.AudioDirectCapture.startRecording(AudioDirectCapture.java:104)
        at com.genymobile.scrcpy.audio.AudioDirectCapture.start(AudioDirectCapture.java:133)
        at com.genymobile.scrcpy.audio.AudioEncoder.encode(AudioEncoder.java:202)
        at com.genymobile.scrcpy.audio.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:131)
        at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 240x320

**Comment by rom1v** [comment]
Thank you for your report.

Apparently, the method `AudioRecord.getMinBufferSize()` returns an error.

Please try with this change to ignore the min buffer size in that case:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/audio/AudioDirectCapture.java b/server/src/main/java/com/genymobile/scrcpy/audio/AudioDirectCapture.java
index 361c7baca..8d4a4c2de 100644
--- a/server/src/main/java/com/genymobile/scrcpy/audio/AudioDirectCapture.java
+++ b/server/src/main/java/com/genymobile/scrcpy/audio/AudioDirectCapture.java
@@ -56,8 +56,11 @@ public class AudioDirectCapture implements AudioCapture {
         builder.setAudioSource(audioSource);
         builder.setAudioFormat(AudioConfig.createAudioFormat());
         int minBufferSize = AudioRecord.getMinBufferSize(SAMPLE_RATE, CHANNEL_CONFIG, ENCODING);
-        // This buffer size does not impact latency
-        builder.setBufferSizeInBytes(8 * minBufferSize);
+        if (minBufferSize > 0) {
+            // This buffer size does not impact latency
+            builder.setBufferSizeInBytes(8 * minBufferSize);
+        }
+
         return builder.build();
     }
 
```

Here is a binary (to replace in your scrcpy 2.6.1 release folder):

- [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/5228/1/scrcpy-server) <sub>`SHA-256: 957df8dad56fc54f3930d819be849d0d50196f0a703b068672e5fc31555e056`</sub>

**Comment by rom1v** [comment]
Could you please confirm that it fixes your problem?

**Comment by lzb-libra** [comment]
> Could you please confirm that it fixes your problem?

May I ask if it is necessary to modify the source code and regenerate the executable program? If so, how can I turn it into an. exe executable program?

**Comment by rom1v** [comment]
At the end of this comment, I provided a binary (the server only) to replace in your scrcpy 2.6.1 folder: https://github.com/Genymobile/scrcpy/issues/5228#issuecomment-2306617375

**Comment by lzb-libra** [comment]
I replaced the file you provided and encountered a new issue after running it.

[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.UnsupportedOperationException: Cannot create AudioRecord
        at android.media.AudioRecord$Builder.build(AudioRecord.java:977)
        at com.genymobile.scrcpy.FakeContext$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
        at com.genymobile.scrcpy.audio.AudioDirectCapture.createAudioRecord(AudioDirectCapture.java:64)
        at com.genymobile.scrcpy.audio.AudioDirectCapture.startRecording(AudioDirectCapture.java:107)
        at com.genymobile.scrcpy.audio.AudioDirectCapture.start(AudioDirectCapture.java:136)
        at com.genymobile.scrcpy.audio.AudioEncoder.encode(AudioEncoder.java:202)
        at com.genymobile.scrcpy.audio.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:131)
        at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)

**Comment by rom1v** [comment]
OK, so it fails a bit later. This device does not allow to create an AudioRecord.

But even with that new version, video still works, right?
