### ISSUE TITLE
demux connection error

### ISSUE THREAD

**Issue by JWA44** [Genymobile/scrcpy#5268]
I have 2 phones which display similar errors when trying to run them. couple of other phones work perfectly with no issue, infact the pixel worked perfectly till today

demux error can't run

this is a work machine I am trying to get fixed, these both work flawlessly at home, before posting I used winget to uninstall and reinstall scrpy.  I have tried all the encoders after doing a list encoders and matched them with right h264 etc.  have tried the "-m1024"

this is for the pixel pro 6 runing android 14

* daemon not running; starting now at tcp:5037
* daemon started successfully
restarting in TCP mode port: 5555
connected to 192.168.1.22:5555
scrcpy v2.2 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)     192.168.1.22:5555            device  Pixel_6_Pro
C:\Users\Mark\scoop\apps\scrcpy\current\scrcpy-server: 1 file pushed, 0 skipped. 150.3 MB/s (64363 bytes in 0.000s)
[server] INFO: Device: [Google] google Pixel 6 Pro (Android 14)
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:85)
        at com.genymobile.scrcpy.ScreenCapture.createDisplay(ScreenCapture.java:71)
        at com.genymobile.scrcpy.ScreenCapture.init(ScreenCapture.java:21)
        at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:55)
        at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
        at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
        at java.lang.Class.getMethod(Class.java:2950)
        at java.lang.Class.getMethod(Class.java:2450)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
        ... 6 more
[server] ERROR: Could not change "stay_on_while_plugged_in"
com.genymobile.scrcpy.SettingsException: Could not access settings: get global stay_on_while_plugged_in
        at com.genymobile.scrcpy.Settings.execSettingsGet(Settings.java:32)
        at com.genymobile.scrcpy.Settings.getValue(Settings.java:46)
        at com.genymobile.scrcpy.Settings.getAndPutValue(Settings.java:76)
        at com.genymobile.scrcpy.Server.initAndCleanUp(Server.java:63)
        at com.genymobile.scrcpy.Server.lambda$startInitThread$2(Server.java:182)
        at com.genymobile.scrcpy.Server$$ExternalSyntheticLambda3.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:405)
        at java.lang.Object.wait(Object.java:543)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:208)
        at com.genymobile.scrcpy.Command.execReadLine(Command.java:27)
        at com.genymobile.scrcpy.Settings.execSettingsGet(Settings.java:30)
        ... 6 more
INFO: Renderer: direct3d
ERROR: Demuxer 'video': stream disabled due to connection error
ERROR: Demuxer 'audio': stream disabled due to connection error
ERROR: Demuxer error

This is for the Samsung s10 5g.  This ones been going a while and I always dismissed it as a weirdness of using lienage on it until it started with the stock google.  this issue is one reason I got the pixel so I could use it at work.

INFO: Connecting to 192.168.1.11:5555...
INFO: Connected to 192.168.1.11:5555
C:\Users\Mark\scoop\apps\scrcpy\current\scrcpy-server: 1 file pushed, 0 skipped. 149.3 MB/s (64363 bytes in 0.000s)
[server] INFO: Device: [samsung] samsung SM-G977B (Android 14)
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:85)
        at com.genymobile.scrcpy.ScreenCapture.createDisplay(ScreenCapture.java:71)
        at com.genymobile.scrcpy.ScreenCapture.init(ScreenCapture.java:21)
        at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:55)
        at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
        at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
        at java.lang.Class.getMethod(Class.java:2950)
        at java.lang.Class.getMethod(Class.java:2450)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
        ... 6 more
INFO: Renderer: direct3d
ERROR: Demuxer 'video': stream disabled due to connection error
ERROR: Demuxer error
Press any key to continue . . .

I am lost, have googled but everything I find say to play with the encoders which comes with the same error no matter which is used

**Comment by rom1v** [comment]
> scrcpy v2.2

Use the latest version (currently 2.6.1).
