### ISSUE TITLE
scrcpy Clipboard Access Issue

### ISSUE THREAD

**Issue by Are-16** [Genymobile/scrcpy#5275]
The user encountered an issue with accessing the clipboard while using the scrcpy tool for screen mirroring via adb. The logs indicate errors related to SecurityException and InvocationTargetException.

Error Log:[server] INFO: Device clipboard set
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getPrimaryClip(ClipboardManager.java:141)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:188)
        at com.genymobile.scrcpy.device.Device.getClipboardText(Device.java:294)
        at com.genymobile.scrcpy.device.Device.setClipboardText(Device.java:307)
        at com.genymobile.scrcpy.control.Controller.setClipboard(Controller.java:442)
        at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:193)
        at com.genymobile.scrcpy.control.Controller.control(Controller.java:102)
        at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:110)
        at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.SecurityException: Calling uid 0 does not own package com.android.shell
        at android.os.Parcel.readException(Parcel.java:2013)
        at android.os.Parcel.readException(Parcel.java:1959)
        at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:187)
        ... 11 more
[server] INFO: Device clipboard set
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getPrimaryClip(ClipboardManager.java:141)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:188)
        at com.genymobile.scrcpy.device.Device.getClipboardText(Device.java:294)
        at com.genymobile.scrcpy.device.Device$3.dispatchPrimaryClipChanged(Device.java:147)
        at android.content.IOnPrimaryClipChangedListener$Stub.onTransact(IOnPrimaryClipChangedListener.java:51)
        at android.os.Binder.execTransact(Binder.java:697)
Caused by: java.lang.SecurityException: Calling uid 0 does not own package com.android.shell
        at android.os.Parcel.readException(Parcel.java:2013)
        at android.os.Parcel.readException(Parcel.java:1959)
        at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:187)
        ... 7 more

**Comment by rom1v** [comment]
> Caused by: java.lang.SecurityException: Calling uid 0 does not own package com.android.shell

Is your device rooted?

Try to run it as non-root if it is the case (`adb unroot`).

**Comment by Are-16** [comment]
The issue has been resolved, thank you

**Comment by Are-16** [comment]
> > 原因：java.lang.SecurityException：调用 uid 0 不拥有 com.android.shell 包
> 
> 您的设备是否已获得 root 权限？
> 
> 如果是这种情况，请尝试以非 root 身份运行它 （）。`adb unroot`

The issue has been resolved, thank you
