### ISSUE TITLE
latest version doesn't start on Linux

### ISSUE THREAD

**Issue by LeOS-GSI** [Genymobile/scrcpy#5295]
scrcpy doesn't work anymore. I'm using PoP!OS. See terminal output:

`/usr/share/scrcpy/scrcpy-server: 1 fil...ed. 255.0 MB/s (39473 bytes in 0.000s)
[server] INFO: Device: unknown LeOS-A14 (Android 14)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2950)
	at java.lang.Class.getMethod(Class.java:2450)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
	at com.genymobile.scrcpy.Device.<init>(Device.java:93)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:63)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
	at com.genymobile.scrcpy.ScreenEncoder.createDisplay(ScreenEncoder.java:229)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at java.lang.Class.getMethod(Class.java:2950)
	at java.lang.Class.getMethod(Class.java:2450)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:81)
	... 7 more
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 555.58.02
INFO: Trilinear filtering enabled
INFO: Initial texture: 1600x2560
WARN: Device disconnected
WARN: Killing the server...
`

**Comment by rom1v** [comment]
This looks like an old version. Which version is it?

**Comment by LeOS-GSI** [comment]
> This looks like an old version. Which version is it?

as I have written in headline. Latest - 2.7

**Comment by rom1v** [comment]
> Latest - 2.7

Not possible, the stacktrace does not match. It's definitely an older version.

In your first post, you dropped the first lines where the version is printed (the first line after you execute your command)..

Or just execute `scrcpy -v`.

**Comment by LeOS-GSI** [comment]
> > Latest - 2.7
> 
> Not possible, the stacktrace does not match. It's definitely an older version.
> 
> In your first post, you dropped the first lines where the version is printed (the first line after you execute your command)..
> 
> Or just execute `scrcpy -v`.

I don't understand. I have clone your repo / branch master. Why Is it version 1.21 and not latest ??  the last commit on master was '[Update links to 2.7](https://github.com/Genymobile/scrcpy/commit/665ccb32f5306ebd866dc0d99f4d08ed2aeb91c3)'

**Comment by LeOS-GSI** [comment]
> Then what did you do?
I have done `git clone https://github.com/Genymobile/scrcpy.git
`
the running `scrcpy`  from scrcpy/app/data/bash-completion

but now nothing happens anymore

**Comment by rom1v** [comment]
> the running scrcpy from scrcpy/app/data/bash-completion

:question: :thinking: 

Please follow the instructions here: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by LeOS-GSI** [comment]
Oh, thx for the link. Seems there where missing dependencies. Now it's working. Thanks for your good work
