### ISSUE TITLE
How to I setup this to run in wireless mode?

### ISSUE THREAD

**Issue by rthfhgyhy567** [Genymobile/scrcpy#5363]
I have already enabled wireless ADB and confirmed mirroring works over USB.  Now I want to set it up wirelessly. The instructions state use these options to connect to the device but doesn't explain where to put them.  Not everyone in this world is a programmer or a master geek.  Some more detailed instructions as to where to put this code would be nice.  I tried pasting them into the "scrcpy-console.bat" (and changing the IP to the actual one) but it just says connection failed when I try to launch scrpy.  Also what is with such a gibberish name?  Makes it hard to recommend something when I can't even pronounce the name.  Please make the name less autistic too.

scrcpy --tcpip=192.168.1.1       # default port is 5555
scrcpy --tcpip=192.168.1.1:5555

**Comment by rom1v** [comment]
>  Some more detailed instructions as to where to put this code would be nice. 

https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run

>  Also what is with such a gibberish name?

Says rthfhgyhy567 😄

**Comment by kmizmal** [comment]
just run it ,
but in me using ,always meet some bug by wireless ADB.
like [server] INFO: Device screen turned off
WARN: Device disconnected
this make break link

and [server] INFO: Device: [OnePlus] OnePlus PJE110 (Android 14)
[server] ERROR: Could not change "stay_on_while_plugged_in"
com.genymobile.scrcpy.util.SettingsException: Could not access settings: put global stay_on_while_plugged_in 7
        at com.genymobile.scrcpy.util.Settings.execSettingsPut(Settings.java:24)
        at com.genymobile.scrcpy.util.Settings.putValue(Settings.java:59)
        at com.genymobile.scrcpy.util.Settings.getAndPutValue(Settings.java:78)
        at com.genymobile.scrcpy.Server.initAndCleanUp(Server.java:99)
        at com.genymobile.scrcpy.Server.lambda$startInitThread$2(Server.java:237)
        at com.genymobile.scrcpy.Server$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.IOException: Command [settings, put, global, stay_on_while_plugged_in, 7] returned with value 255
        at com.genymobile.scrcpy.util.Command.exec(Command.java:16)
        at com.genymobile.scrcpy.util.Settings.execSettingsPut(Settings.java:22)
        ... 6 more
INFO: Renderer: direct3d
INFO: Texture: 1080x2376
this via

**Comment by erzurum2525** [comment]
Enable wireless debugging, click on wireless debugging. click pair via code and open a terminal at your PC. first start adb services by typing "adb devices" after the daemon successfully starts, type adb pair ip adress:port. your IP adress and port is at the pairing page on your phone. should look something like this: 192.xxx.xx.xx:321941. it will ask for pairing code, enter your pairing code. now type adb devices again to see if its connected then run scrcpy

**Comment by SangonomiyaRen** [comment]
first step you must be pairing your device to pc with same network, now open developer setting > wireless debugging and tap "pair with code"

next, on pc type `adb pair HOST[:PORT] [PAIRING CODE]` 
   example : `adb pair 192.168.xxx.xxx:xxxxx xxxxxx`
if paired, you can continue using `adb connect HOST[:PORT]` 
   example : `adb connect 192.168.xxx.xxx:xxxxx`

now last step please check using `adb devices` on terminal, if you see ip address you successfull connect your phone to pc using wireless adb, if not, try again

after connected, you can run scrcpy-console.bat file

**Comment by promeneur** [comment]
Once the phone is paired to the PC with a code; if I turn off my PC one night and then the next day I start it and then run "scrcpy--tcpip". Are the phone and PC still paired with the code?
