### ISSUE TITLE
[Bug] Set Window Size At Start Up

### ISSUE THREAD

**Issue by MrTeeXD** [Genymobile/scrcpy#537]
Hello, apparently when you try to use the -w command for scrcpy to start up with, it comes with this error : 

```
ERROR: Exception on thread Thread[main,5,main]
java.lang.NumberFormatException: For input string: "width"
        at java.lang.Integer.parseInt(Integer.java:608)
        at java.lang.Integer.parseInt(Integer.java:643)
        at com.genymobile.scrcpy.Server.parseCrop(Server.java:85)
        at com.genymobile.scrcpy.Server.createOptions(Server.java:67)
        at com.genymobile.scrcpy.Server.main(Server.java:109)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:315)
Exit due to uncaughtException in main thread:
```

**Comment by rom1v** [comment]
> apparently when you try to use the -w command for scrcpy to start up with

There is no `-w` command.

Here, it seems you used the `--crop` (or `-c`) command, but passed the string `"width"` as value, while you must pass 4 values separated by `:`.

For example:

    scrcpy --crop 400:400:100:200

**Comment by MrTeeXD** [comment]
Ahh i see what i did wrong there
