### ISSUE TITLE
ERROR: Exception on thread Thread[audio-encoder,5,main]

### ISSUE THREAD

**Issue by SangonomiyaRen** [Genymobile/scrcpy#5376]
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  14b5551c                        device  M2101K6G
D:\Program Files\scrcpy-win64-v2.7\scrcpy-server: 1 file pushed, 0 skipped. 22.7 MB/s (71200 bytes in 0.003s)
[server] INFO: Device: [Xiaomi] Redmi M2101K6G (Android 13)
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.UnsupportedOperationException: Cannot create AudioRecord
        at android.media.AudioRecord$Builder.build(AudioRecord.java:982)
        at com.genymobile.scrcpy.FakeContext$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
        at com.genymobile.scrcpy.audio.AudioDirectCapture.createAudioRecord(AudioDirectCapture.java:64)
        at com.genymobile.scrcpy.audio.AudioDirectCapture.startRecording(AudioDirectCapture.java:107)
        at com.genymobile.scrcpy.audio.AudioDirectCapture.start(AudioDirectCapture.java:136)
        at com.genymobile.scrcpy.audio.AudioEncoder.encode(AudioEncoder.java:202)
        at com.genymobile.scrcpy.audio.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:131)
        at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
INFO: Renderer: direct3d
INFO: Texture: 1080x2400
WARN: Demuxer 'audio': stream explicitly disabled by the device

**Comment by rom1v** [comment]
#5138

**Comment by rom1v** [comment]
Run with `--no-audio` if you don't need audio.
