### ISSUE TITLE
Camera mirroring does not work at resolutions greater than 2K (Xiaomi Redmi Note 12 Pro)

### ISSUE THREAD

**Issue by Yuri-Il** [Genymobile/scrcpy#5382]
## Environment

 - OS: Windows 10
 - Scrcpy version: 2.7
 - Installation method: Windows release
 - Device model: Xiaomi Redmi Note 12 Pro (2209116AG)
 - Android version: 13

## Describe the bug

Thanks for the great app! I wanted to use it to turn my phone into a 4K webcam (because my phone has a 4K camera), but I ran into a bug.

INFO: List of cameras:
    --camera-id=0    (back, 4000x3000, fps=[15, 30])
        - 4000x3000
        - 4000x2252
        - 3840x2160
        - 3280x2464
        - 2592x1944
        - 3264x2448
        - 2400x1080
        - 2304x1728
        - 1920x1080
   ...
Unfortunately, 2560x1440 is the maximum at which the picture is streamed. When I set the resolution higher than that, it crashes with an error:

```
.\scrcpy --video-source=camera --camera-size=3840x2160 --video-codec=h264
...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] WARN: Camera capture failed: frame 11
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3573)
        at com.genymobile.scrcpy.video.SurfaceEncoder.encode(SurfaceEncoder.java:169)
        at com.genymobile.scrcpy.video.SurfaceEncoder.streamCapture(SurfaceEncoder.java:88)
        at com.genymobile.scrcpy.video.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-video-SurfaceEncoder(SurfaceEncoder.java:268)
        at com.genymobile.scrcpy.video.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
```
Is there any way to fix it? In general, for my task 2K resolution will be fine, but only with the ability to zoom in, but such a function, as far as I read, is not in your plans. I would be very grateful if you could suggest ways to solve the problem!

**Comment by rom1v** [comment]
The encoder cannot encode at the requested resolution.

Try another encoder: https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder
