### ISSUE TITLE
[UnhandledException]: IOException `android.system.ErrnoException` open failed: `ENOENT` (No such file or directory)

### ISSUE THREAD

**Issue by ryuujo1573** [Genymobile/scrcpy#5410]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** Windows
 - **Scrcpy version:** 2.7
 - **Installation method:** Assets zip
 - **Device model:** AITO M7
 - **Android version:** 12 Equivalent

## Describe the bug

Execute `scrcpy --no-video --audio-buffer=200`

```log
[server] INFO: Device: [HUAWEI] HUAWEI ICSA-F1 (Android 12)
[server] ERROR: Controller error
java.io.IOException: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at com.genymobile.scrcpy.control.UhidManager.open(UhidManager.java:69)
        at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:213)
        at com.genymobile.scrcpy.control.Controller.control(Controller.java:102)
        at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:110)
        at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:933)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
        at android.system.Os.open(Os.java:501)
        at com.genymobile.scrcpy.control.UhidManager.open(UhidManager.java:52)
        ... 5 more
INFO: Renderer: direct3d
ERROR: Demuxer 'audio': stream disabled due to connection error
WARN: Device disconnected
```

Any clue?

**Comment by rom1v** [comment]
By default, video, audio and control are enabled in scrcpy.

Since you pass `--no-video`, it remains audio and control.

But without video, it makes no sense to use absolute mouse events (you can't know where you click), so it aumatically swktched the mouse to UHID.

But your device does not support UHID.

If you just want audio, run:

```bash
scrcpy --no-video --no-control --audio-buffer=200
```

**Comment by ryuujo1573** [comment]
> By default, video, audio and control are enabled in scrcpy.
> 
> Since you pass `--no-video`, it remains audio and control.
> 
> But without video, it makes no sense to use absolute mouse events (you can't know where you click), so it aumatically swktched the mouse to UHID.
> 
> But your device does not support UHID.
> 
> If you just want audio, run:
> 
> ```shell
> scrcpy --no-video --no-control --audio-buffer=200
> ```

This works! Thank you.

**Comment by rom1v** [comment]
I changed the default behavior not to use UHID mode when video playback is disabled: 2c25fd7a8082307da19645a690c31403903fbb1e
