### ISSUE TITLE
Can no longer control mirrored device with mouse and keyboard Ubuntu 24.04, Samsung S22

### ISSUE THREAD

**Issue by JannisErhard** [Genymobile/scrcpy#5437]
## Environment

Device: Samsung Galaxy S21
Android OS: 14
Ubuntu 24.04.1 LTS
Scrcpy 1.25
Installation method: sudo apt install scrcpy

## Describe the bug

I can mirror the phone screen but mouse and keyboard inputs are not accepted. 

```
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 388.5 MB/s (41650 bytes in 0.000s)
[server] INFO: Device: samsung SM-S901B (Android 14)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2950)
	at java.lang.Class.getMethod(Class.java:2450)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:128)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:138)
	at com.genymobile.scrcpy.Device.<init>(Device.java:100)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
	at com.genymobile.scrcpy.Server.main(Server.java:334)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:385)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 24.0.9-0ubuntu0.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2336
[server] ERROR: Exception on thread Thread[Thread-2,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:75)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:196)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:231)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:102)
	at com.genymobile.scrcpy.Controller.control(Controller.java:79)
	at com.genymobile.scrcpy.Server$3.run(Server.java:132)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:72)
	... 7 more
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:207)
	at android.hardware.input.InputManager.getInstance(InputManager.java:401)
	... 9 more

```

**Comment by rom1v** [comment]
> Scrcpy 1.25

Ultra old, you need a recent version.

https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by JannisErhard** [comment]
building scrcpy, form scratch, ./install_release.sh meson picks up on one of my aliases, and tries to treat the alias target as a compiler, alas it is not. I  think the line in the shell script that starts with `meson setup ` would need to be modified.

This is where install.sh crashes:
`meson.build:1:0: ERROR: Unknown compiler(s): [['user@server.org']]
The following exception(s) were encountered:
Running `user@server.org --version` gave "[Errno 2] No such file or directory: 'user@server.org'"`
