### ISSUE TITLE
"The Xiaomi 15 encountered an error during audio encoding, running on the Surge 2.0 system, based on Android 15."

### ISSUE THREAD

**Issue by hybdzk** [Genymobile/scrcpy#5452]
java.lang.SecurityException: Given calling package android does not match caller's uid 2000
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3256)
        at android.os.Parcel.createException(Parcel.java:3240)
        at android.os.Parcel.readException(Parcel.java:3223)
        at android.os.Parcel.readException(Parcel.java:3165)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6670)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:8670)
        at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:3804)
        at android.content.ContentResolver.acquireProvider(ContentResolver.java:2529)
        at android.provider.Settings$ContentProviderHolder.getProvider(Settings.java:3317)
        at android.provider.Settings$NameValueCache.getStringsForPrefixStripPrefix(Settings.java:3760)
        at android.provider.Settings$NameValueCache.-$$Nest$mgetStringsForPrefixStripPrefix(Unknown Source:0)
        at android.provider.Settings$Config.getStrings(Settings.java:20437)
        at android.provider.Settings$Config.getStrings(Settings.java:20388)
        at android.provider.SettingsConfigDataStore.getProperties(SettingsConfigDataStore.java:48)
        at android.provider.DeviceConfig.getPropertiesWithoutOverrides(DeviceConfig.java:1125)
        at android.provider.DeviceConfig.getProperties(DeviceConfig.java:1115)
        at android.media.codec.FeatureFlagsImpl.load_overrides_codec_fwk(FeatureFlagsImpl.java:19)
        at android.media.codec.FeatureFlagsImpl.setCallbackStall(FeatureFlagsImpl.java:146)
        at android.media.codec.Flags.setCallbackStall(Flags.java:109)
        at android.media.MediaCodec.setCallback(MediaCodec.java:5280)
        at com.genymobile.scrcpy.FakeContext$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
        at com.genymobile.scrcpy.audio.AudioEncoder.encode(AudioEncoder.java:199)
        at com.genymobile.scrcpy.audio.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:131)
        at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:147)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7736)
        at android.app.IActivityManager$Stub.onTransact$getContentProvider$(IActivityManager.java:13030)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3422)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3041)

INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1200x2664

  public void setCallback(Callback paramCallback, Handler paramHandler) {
    if (paramCallback != null) {
      synchronized (this.mListenerLock) {
        paramHandler = getEventHandlerOn(paramHandler, this.mCallbackHandler);
        if (paramHandler != this.mCallbackHandler) {
          if (Flags.setCallbackStall()) {
            MediaCodec$$ExternalSyntheticLambda2 mediaCodec$$ExternalSyntheticLambda2 = new MediaCodec$$ExternalSyntheticLambda2();
            this(this);
            logAndRun("[new handler] removeMessages(SET_CALLBACK)", mediaCodec$$ExternalSyntheticLambda2);
            MediaCodec$$ExternalSyntheticLambda3 mediaCodec$$ExternalSyntheticLambda3 = new MediaCodec$$ExternalSyntheticLambda3();
            this(this);
            logAndRun("[new handler] removeMessages(CALLBACK)", mediaCodec$$ExternalSyntheticLambda3);
          } else {
            this.mCallbackHandler.removeMessages(2);
            this.mCallbackHandler.removeMessages(1);
          } 
          this.mCallbackHandler = (EventHandler)paramHandler;
        } 
      } 
    } else if (this.mCallbackHandler != null) {
      if (Flags.setCallbackStall()) {
        logAndRun("[null handler] removeMessages(SET_CALLBACK)", new MediaCodec$$ExternalSyntheticLambda4(this));
        logAndRun("[null handler] removeMessages(CALLBACK)", new MediaCodec$$ExternalSyntheticLambda5(this));
      } else {
        this.mCallbackHandler.removeMessages(2);
        this.mCallbackHandler.removeMessages(1);
      } 
    } 
    if (this.mCallbackHandler != null) {
      Message message = this.mCallbackHandler.obtainMessage(2, 0, 0, paramCallback);
      this.mCallbackHandler.sendMessage(message);
      native_setCallback(paramCallback);
    } 
  }

 public boolean setCallbackStall() {
    if (!codec_fwk_is_cached)
      load_overrides_codec_fwk(); 
    return setCallbackStall;
  }

  private void load_overrides_codec_fwk() {
    try {
      DeviceConfig.Properties properties = DeviceConfig.getProperties("codec_fwk", new String[0]);
      aidlHalInputSurface = properties.getBoolean("android.media.codec.aidl_hal_input_surface", false);
      inProcessSwAudioCodec = properties.getBoolean("android.media.codec.in_process_sw_audio_codec", false);
      inProcessSwAudioCodecSupport = properties.getBoolean("android.media.codec.in_process_sw_audio_codec_support", false);
      nativeCapabilites = properties.getBoolean("android.media.codec.native_capabilites", false);
      setCallbackStall = properties.getBoolean("android.media.codec.set_callback_stall", false);
      teamfood = properties.getBoolean("android.media.codec.teamfood", false);
      codec_fwk_is_cached = true;
      return;
    } catch (NullPointerException nullPointerException) {
      throw new RuntimeException("Cannot read value from namespace codec_fwk from DeviceConfig. It could be that the code using flag executed before SettingsProvider initialization. Please use fixed read-only flag by adding is_fixed_read_only: true in flag declaration.", nullPointerException);
    } 
  }

[media.zip](https://github.com/user-attachments/files/17625955/media.zip)

**Comment by hybdzk** [comment]
In the mediaCodec setCallback method, the line Flags.setCallbackStall() is throwing an exception. The error message is "Cannot read value from namespace codec_fwk from DeviceConfig. It could be that the code using flag executed before SettingsProvider initialization. Please use fixed read-only flag by adding is_fixed_read_only: true in flag declaration."

**Comment by gaussyoung** [comment]
The same problem on my Xiaomi Pad 7 Pro, Android 15, HyperOS 2

**Comment by rom1v** [comment]
#4639

**Comment by yume-chan** [comment]
Please try the prebuilt server binary in https://github.com/Genymobile/scrcpy/issues/4639#issuecomment-2466081589

**Comment by fumui** [comment]
Hello, I also got this error

```
personal\scrcpy-win64-v3.2> scrcpy --video-codec=h265 --max-size=1920 --max-fps=60 --video-bit-rate=30M --require-audio
scrcpy 2.6.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  c943c462                        device  2312DRA50G
C:\Program Files\scrcpy-win64-v2.6.1\scrcpy-server: 1 file pushed, 0 skipped. 69.8 MB/s (71112 bytes in 0.001s)
[server] INFO: Device: [Xiaomi] Redmi 2312DRA50G (Android 15)
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.SecurityException: Given calling package android does not match caller's uid 2000
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3256)
        at android.os.Parcel.createException(Parcel.java:3240)
        at android.os.Parcel.readException(Parcel.java:3223)
        at android.os.Parcel.readException(Parcel.java:3165)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6723)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:8702)
        at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:3804)
        at android.content.ContentResolver.acquireProvider(ContentResolver.java:2529)
        at android.provider.Settings$ContentProviderHolder.getProvider(Settings.java:3317)
        at android.provider.Settings$NameValueCache.getStringsForPrefixStripPrefix(Settings.java:3760)
        at android.provider.Settings$NameValueCache.-$$Nest$mgetStringsForPrefixStripPrefix(Unknown Source:0)
        at android.provider.Settings$Config.getStrings(Settings.java:20448)
        at android.provider.Settings$Config.getStrings(Settings.java:20399)
        at android.provider.SettingsConfigDataStore.getProperties(SettingsConfigDataStore.java:48)
        at android.provider.DeviceConfig.getPropertiesWithoutOverrides(DeviceConfig.java:1125)
        at android.provider.DeviceConfig.getProperties(DeviceConfig.java:1115)
        at android.media.codec.FeatureFlagsImpl.load_overrides_codec_fwk(FeatureFlagsImpl.java:19)
        at android.media.codec.FeatureFlagsImpl.setCallbackStall(FeatureFlagsImpl.java:146)
        at android.media.codec.Flags.setCallbackStall(Flags.java:109)
        at android.media.MediaCodec.setCallback(MediaCodec.java:5280)
        at com.genymobile.scrcpy.FakeContext$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
        at com.genymobile.scrcpy.audio.AudioEncoder.encode(AudioEncoder.java:199)
        at com.genymobile.scrcpy.audio.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:131)
        at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:147)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7793)
        at android.app.IActivityManager$Stub.onTransact$getContentProvider$(IActivityManager.java:13179)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3454)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3093)

INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 864x1920
ERROR: Demuxer error
```
here's the framework.jar if needed
[framework.zip](https://github.com/user-attachments/files/20454339/framework.zip)

**Comment by rom1v** [comment]
> scrcpy 2.6.1

You're not using the latest version (even if your directory is called 3.2).

**Comment by fumui** [comment]
originally I was using scrcpy-server from the release tag.
But I was trying a few other scrcpy-server from other simmiliar issues like this
https://github.com/Genymobile/scrcpy/issues/5960#issuecomment-2816608015

and I found 2 other scrcpy-server files that was suggested in another issue (I cant find the link anymore)

All of them got identical errors
