### ISSUE TITLE
after I upgraded to A15, the audio forwarding function can not work

### ISSUE THREAD

**Issue by shiqianwei0508** [Genymobile/scrcpy#5469]
## Environment

 - **OS:** [Windows 10 LTSC]
 - **Scrcpy version:** [2.7]
 - **Installation method:** [Windows Portable release]
 - **Device model:** [Xiaomi 2304FPN6DC]
 - **Android version:** [15]

## Describe the bug

```
Active code page: 65001
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  ab42f0a9                        device  2304FPN6DC
D:\PortableSoft\scrcpy-win64\scrcpy-server: 1 file pushed, 0 skipped. 32.9 MB/s (71200 bytes in 0.002s)
[server] INFO: Device: [Xiaomi] Xiaomi 2304FPN6DC (Android 15)
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.SecurityException: Given calling package android does not match caller's uid 2000
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3256)
        at android.os.Parcel.createException(Parcel.java:3240)
        at android.os.Parcel.readException(Parcel.java:3223)
        at android.os.Parcel.readException(Parcel.java:3165)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6670)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:8670)
        at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:3804)
        at android.content.ContentResolver.acquireProvider(ContentResolver.java:2529)
        at android.provider.Settings$ContentProviderHolder.getProvider(Settings.java:3317)
        at android.provider.Settings$NameValueCache.getStringsForPrefixStripPrefix(Settings.java:3760)
        at android.provider.Settings$NameValueCache.-$$Nest$mgetStringsForPrefixStripPrefix(Unknown Source:0)
        at android.provider.Settings$Config.getStrings(Settings.java:20437)
        at android.provider.Settings$Config.getStrings(Settings.java:20388)
        at android.provider.SettingsConfigDataStore.getProperties(SettingsConfigDataStore.java:48)
        at android.provider.DeviceConfig.getPropertiesWithoutOverrides(DeviceConfig.java:1125)
        at android.provider.DeviceConfig.getProperties(DeviceConfig.java:1115)
        at android.media.codec.FeatureFlagsImpl.load_overrides_codec_fwk(FeatureFlagsImpl.java:19)
        at android.media.codec.FeatureFlagsImpl.setCallbackStall(FeatureFlagsImpl.java:146)
        at android.media.codec.Flags.setCallbackStall(Flags.java:109)
        at android.media.MediaCodec.setCallback(MediaCodec.java:5280)
        at com.genymobile.scrcpy.FakeContext$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
        at com.genymobile.scrcpy.audio.AudioEncoder.encode(AudioEncoder.java:199)
        at com.genymobile.scrcpy.audio.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:131)
        at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:147)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7736)
        at android.app.IActivityManager$Stub.onTransact$getContentProvider$(IActivityManager.java:13030)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3422)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3041)

INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1080x2400
[server] INFO: Device screen turned off
```

**Comment by rom1v** [comment]
#4639

**Comment by rom1v** [comment]
Please test #5476, and tell us if it fixes the issue.

**Comment by shiqianwei0508** [comment]
> Please test #5476, and tell us if it fixes the issue.

**New Error**

```
Active code page: 65001
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
WARN: --display-buffer is deprecated, use --video-buffer instead.
* daemon not running; starting now at tcp:5037
* daemon started successfully
INFO: ADB device found:
INFO:     -->   (usb)  ab42f0a9                        device  2304FPN6DC
D:\PortableSoft\scrcpy-win64\scrcpy-server: 1 file pushed, 0 skipped. 38.7 MB/s (79364 bytes in 0.002s)
[server] INFO: Device: [Xiaomi] Xiaomi 2304FPN6DC (Android 15)
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.RuntimeException: Cannot read value from namespace codec_fwk from DeviceConfig. It could be that the code using flag executed before SettingsProvider initialization. Please use fixed read-only flag by adding is_fixed_read_only: true in flag declaration.
        at android.media.codec.FeatureFlagsImpl.load_overrides_codec_fwk(FeatureFlagsImpl.java:33)
        at android.media.codec.FeatureFlagsImpl.setCallbackStall(FeatureFlagsImpl.java:146)
        at android.media.codec.Flags.setCallbackStall(Flags.java:109)
        at android.media.MediaCodec.setCallback(MediaCodec.java:5280)
        at com.genymobile.scrcpy.FakeContext$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
        at com.genymobile.scrcpy.audio.AudioEncoder.encode(AudioEncoder.java:200)
        at com.genymobile.scrcpy.audio.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:132)
        at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle android.content.IContentProvider.call(android.content.AttributionSource, java.lang.String, java.lang.String, java.lang.String, android.os.Bundle)' on a null object reference
        at android.provider.Settings$NameValueCache.getStringsForPrefixStripPrefix(Settings.java:3788)
        at android.provider.Settings$NameValueCache.-$$Nest$mgetStringsForPrefixStripPrefix(Unknown Source:0)
        at android.provider.Settings$Config.getStrings(Settings.java:20437)
        at android.provider.Settings$Config.getStrings(Settings.java:20388)
        at android.provider.SettingsConfigDataStore.getProperties(SettingsConfigDataStore.java:48)
        at android.provider.DeviceConfig.getPropertiesWithoutOverrides(DeviceConfig.java:1125)
        at android.provider.DeviceConfig.getProperties(DeviceConfig.java:1115)
        at android.media.codec.FeatureFlagsImpl.load_overrides_codec_fwk(FeatureFlagsImpl.java:19)
        ... 8 more
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1080x2400
[server] INFO: Device display turned off
```

**Comment by rom1v** [comment]
Please post your framework.jar:

```
adb pull /system/framework/framework.jar
```

**Comment by yume-chan** [comment]
> java.lang.RuntimeException: Cannot read value from namespace codec_fwk from DeviceConfig. It could be that the code using flag executed before SettingsProvider initialization. Please use fixed read-only flag by adding is_fixed_read_only: true in flag declaration.

There was a bug in older versions of Android 15:

https://cs.android.com/android/_/android/platform/frameworks/base/+/55a7e60183fae644feccf6d9144d12eed5a3321a

https://cs.android.com/android/_/android/platform/frameworks/base/+/6a4bef0f90e822e19866e53a98b85029bff04ea0

But still not sure why `acquireProvider` would return `null`

**Comment by shiqianwei0508** [comment]
> Please post your framework.jar:
> 
> ```
> adb pull /system/framework/framework.jar
> ```
[framework.zip](https://github.com/user-attachments/files/17743734/framework.zip)

**Comment by rom1v** [comment]
> But still not sure why acquireProvider would return null

Oh, sorry, in #5476 I committed by mistake a wrong version which returned `null` for `acquireProvider`  :facepalm: 

I updated the PR and provided a new binary.

@shiqianwei0508 Could you please download the new binary and re-test?

**Comment by shiqianwei0508** [comment]
> > But still not sure why acquireProvider would return null
> 
> Oh, sorry, in #5476 I committed by mistake a wrong version which returned `null` for `acquireProvider` 🤦
> 
> I updated the PR and provided a new binary.
> 
> @shiqianwei0508 Could you please download the new binary and re-test?

The audio forwarding is worked  !
![image](https://github.com/user-attachments/assets/0582dfee-96d4-478f-9959-a2c0c11c48ce)

Great Work ! Thanks !
