### ISSUE TITLE
can't control the mobile from the window screen 

### ISSUE THREAD

**Issue by mitnick2012** [Genymobile/scrcpy#5474]
## Environment

 - **OS:**  Windows 10
 - **Scrcpy version:** 2.7
 - **Installation method:**Windows release
 - **Device model: Xiaomi  Redmi 22101316UG :Redmi 12 Pro 5G
 - **Android version:** Android 14

## Describe the bug

console output : 
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
        at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:234)
        at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:238)
        at com.genymobile.scrcpy.control.Controller.injectTouch(Controller.java:371)
        at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:167)
        at com.genymobile.scrcpy.control.Controller.control(Controller.java:102)
        at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:110)
        at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
        at android.os.Parcel.createException(Parcel.java:3041)
        at android.os.Parcel.readException(Parcel.java:3024)
        at android.os.Parcel.readException(Parcel.java:2966)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1590)
        at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
        at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
        ... 10 more

**Comment by rom1v** [comment]
> Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.

https://github.com/Genymobile/scrcpy#prerequisites

**Comment by mitnick2012** [comment]
I enabled USB debugging (Security Settings) and reboot the phone and it's worked
