### ISSUE TITLE
Scrcpy 3.0 is not detecting some cameras in Android 12.

### ISSUE THREAD

**Issue by xM0DI** [Genymobile/scrcpy#5539]
## Environment

 - **OS: Windows 11**
 - **Scrcpy version: 3.0**
 - **Installation method:** Windows Release x64
 - **Device model: Samsung M31**
 - **Android version:12**

## Describe the bug

When using scrcpy --video-source=camera --camera-id=0, it gives error. same happens with id=2 (back). 
Above command is working for other ids like 1 and 3 (front camera) etc.
This is only happening in device running android 12.
I have tested same command on Android 14 and it works as intended.
```
scrcpy 3.0 <https://github.com/Genymobile/scrcpy>
INFO: Camera video source: control disabled
INFO: Camera video source: microphone audio source selected
INFO: ADB device found:
INFO:     -->   (usb)  RZ8N814HZNZ                     device  SM_M315F
D:\Downloads\scrcpy-win64-v3.0\scrcpy-server: 1 file pushed, 0 skipped. 69.5 MB/s (90224 bytes in 0.001s)
[server] INFO: Device: [samsung] samsung SM-M315F (Android 12)
[server] INFO: Using camera '0'
INFO: Renderer: direct3d
INFO: Texture: 4624x3472
[server] ERROR: Video encoding error
Wjava.io.IOException: android.hardware.camera2.CameraAccessException: The camera device is currently in the error state; no further calls to it will succeed.
A       at com.genymobile.scrcpy.video.CameraCapture.start(CameraCapture.java:270)
        at com.genymobile.scrcpy.video.SurfaceEncoder.streamCapture(SurfaceEncoder.java:95)
        at com.genymobile.scrcpy.video.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-video-SurfaceEncoder(SurfaceEncoder.java:292)
        at com.genymobile.scrcpy.video.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: android.hardware.camera2.CameraAccessException: The camera device is currently in the error state; no further calls to it will succeed.
        at com.genymobile.scrcpy.video.CameraCapture$2.onConfigureFailed(CameraCapture.java:370)
        at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigureFailed$1$CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:64)
        at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy$$ExternalSyntheticLambda3.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
RN: Device disconnected
```

**Comment by rom1v** [comment]
Is the camera app working on that device?

Try rebooting your device.

**Comment by xM0DI** [comment]
Yes I am able to use camera app in device. 
Tried reboot also but it didn't work. 
This is working in Scrcpy 2.7.

**Comment by rom1v** [comment]
If you know how to build, could you find the culprit commit with `git rebase`?

Does it work with a lower resolution `-m 1024`? (even if it works, there's a bug, it should not fail without it but retry automatically)

**Comment by xM0DI** [comment]
Yes it works with -m1024, more over if we specifically provide size (which we get using list sizes) it works. So I am guessing it is not retrying smaller resolution as it used to do in 2.7. 
```
scrcpy-win64-v2.7
[server] INFO: Device: [samsung] samsung SM-M315F (Android 12)
[server] INFO: Using camera '0'
INFO: Renderer: direct3d
INFO: Texture: 4624x3468
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m2560...
[server] INFO: Retrying...
[server] WARN: Camera capture failed: frame 10
INFO: Texture: 2336x1080
```

**Comment by rom1v** [comment]
On tablet where the encoder cannot support the camera resolution, it fails and retry:

```
INFO: Texture: 3264x2448
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: 
[server] INFO: Retrying with -m2560...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: 
[server] INFO: Retrying with -m1920...
```

So it behaves differently on your device.

Do you know how to build and use `git rebase` to find which change introduce the problem on your device?

**Comment by rom1v** [comment]
Forget `git bisect` if it's too much, but the test on v2.7 with the modified server would help.

I'd like to fix that for 3.0.1.

**Comment by xM0DI** [comment]
Hey, so sorry for delay.
I tried to replace above server file and below is error that I am currently getting.
```
D:\Downloads\scrcpy-win64-v2.7 (1)\scrcpy-win64-v2.7>scrcpy --video-source=camera --camera-id=0
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: Camera video source: control disabled
INFO: Camera video source: microphone audio source selected
* daemon not running; starting now at tcp:5037
* daemon started successfully
INFO: ADB device found:
INFO:     -->   (usb)  RZ8N814HZNZ                     device  SM_M315F
D:\Downloads\scrcpy-win64-v2.7 (1)\scrcpy-win64-v2.7\scrcp... file pushed, 0 skipped. 19.7 MB/s (71152 bytes in 0.003s)
[server] INFO: Device: [samsung] samsung SM-M315F (Android 12)
[server] INFO: Using camera '0'
INFO: Renderer: direct3d
INFO: Texture: 4624x3468
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] WARN: Camera capture failed: frame 8
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.video.SurfaceEncoder.encode(SurfaceEncoder.java:169)
        at com.genymobile.scrcpy.video.SurfaceEncoder.streamCapture(SurfaceEncoder.java:88)
        at com.genymobile.scrcpy.video.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-video-SurfaceEncoder(SurfaceEncoder.java:268)
        at com.genymobile.scrcpy.video.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012) 
```

**Comment by rom1v** [comment]
Thank you very much.

I still don't get why configuring the camera does not fail on 2.7 (it fails later when encoding, which is captured by the retry), but fails on 3.0.

But maybe this is sufficient to make the retry work:

```diff
diff --git server/src/main/java/com/genymobile/scrcpy/video/SurfaceEncoder.java server/src/main/java/com/genymobile/scrcpy/video/SurfaceEncoder.java
index bc120107b..4831d7815 100644
--- server/src/main/java/com/genymobile/scrcpy/video/SurfaceEncoder.java
+++ server/src/main/java/com/genymobile/scrcpy/video/SurfaceEncoder.java
@@ -112,7 +112,7 @@ public class SurfaceEncoder implements AsyncProcessor {
                         // The capture might have been closed internally (for example if the camera is disconnected)
                         alive = !stopped.get() && !capture.isClosed();
                     }
-                } catch (IllegalStateException | IllegalArgumentException e) {
+                } catch (IllegalStateException | IllegalArgumentException | IOException e) {
                     Ln.e("Encoding error: " + e.getClass().getName() + ": " + e.getMessage());
                     if (!prepareRetry(size)) {
                         throw e;
```

Here is a binary for 3.0:

- [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/5539/1/scrcpy-server) <sub>`SHA-256: 3aab6a4c9998b8e8ddefedb377f2330afcde0fec11d6237b164c2249b448936`</sub>

**Comment by xM0DI** [comment]
Yesss! this works!!! Thank you so much!

**Comment by rom1v** [comment]
Merged into `dev` :rocket:
