### ISSUE TITLE
XiaoMi 14 ultra screen off bug after upgrade to 3.0

### ISSUE THREAD

**Issue by lppforsci** [Genymobile/scrcpy#5553]
## Environment

 - **OS:MacOS 15.1.1 (24B2091)
 - **Scrcpy version:3.0
 - **Installation method:brew
 - **Device model:XiaoMi 14 Ultra HyperOS(2.0.6)
 - **Android version:15

## Describe the bug

yesterday I upgraded scrcpy version 3.0 via brew update on my mac

no error display on terminal

then the bug appear:

everything is ok if the screen is on,but 

**I could not turn off my xiaomi 14 ultra screen with mirror ,**

if I turn off my screen with cmd+o short key,the screen turn off then turn on again 

if I  turn off the screen with physical button on phone,i can't swipe the screen on scrcpy window,everything goes freeze,i can't do anything ,it seems the services pause with screen off

**I recover scrcpy version 2.7 from another Mac,and bug disappear**

everthing is ok, and the terminal displays as:

% ./scrcpy
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  84e51c37                        device  24031PN0DC
/opt/homebrew/Cellar/scrcpy/2.7/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 60.1 MB/s (71200 bytes in 0.001s)
[server] INFO: Device: [Xiaomi] Xiaomi 24031PN0DC (Android 15)
INFO: Renderer: metal
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1440x3200
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.SecurityException: Given calling package android does not match caller's uid 2000
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3256)
	at android.os.Parcel.createException(Parcel.java:3240)
	at android.os.Parcel.readException(Parcel.java:3223)
	at android.os.Parcel.readException(Parcel.java:3165)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6695)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:8670)
	at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:3804)
	at android.content.ContentResolver.acquireProvider(ContentResolver.java:2529)
	at android.provider.Settings$ContentProviderHolder.getProvider(Settings.java:3317)
	at android.provider.Settings$NameValueCache.getStringsForPrefixStripPrefix(Settings.java:3760)
	at android.provider.Settings$NameValueCache.-$$Nest$mgetStringsForPrefixStripPrefix(Unknown Source:0)
	at android.provider.Settings$Config.getStrings(Settings.java:20437)
	at android.provider.Settings$Config.getStrings(Settings.java:20388)
	at android.provider.SettingsConfigDataStore.getProperties(SettingsConfigDataStore.java:48)
	at android.provider.DeviceConfig.getPropertiesWithoutOverrides(DeviceConfig.java:1125)
	at android.provider.DeviceConfig.getProperties(DeviceConfig.java:1115)
	at android.media.codec.FeatureFlagsImpl.load_overrides_codec_fwk(FeatureFlagsImpl.java:19)
	at android.media.codec.FeatureFlagsImpl.setCallbackStall(FeatureFlagsImpl.java:146)
	at android.media.codec.Flags.setCallbackStall(Flags.java:109)
	at android.media.MediaCodec.setCallback(MediaCodec.java:5280)
	at com.genymobile.scrcpy.FakeContext$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
	at com.genymobile.scrcpy.audio.AudioEncoder.encode(AudioEncoder.java:199)
	at com.genymobile.scrcpy.audio.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:131)
	at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:147)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7710)
	at android.app.IActivityManager$Stub.onTransact$getContentProvider$(IActivityManager.java:13102)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3429)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3027)

2024-11-28 08:39:45.729 scrcpy[41902:428062] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-28 08:39:53.507 scrcpy[41902:428062] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit

is something change on 3.0 version cause the screen off bug?

hope to resolve

I like scrcpy very much

a fans from china 
```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
#5530 3d1f036c04412e17a694e6a0b857b7f9e9217ab3
