### ISSUE TITLE
Problema en POCO X6 PRO

### ISSUE THREAD

**Issue by MemphisVercetti** [Genymobile/scrcpy#5599]
No se que hacer, simplemente no funciona, ya intente muchas cosas, ¿Que puedo hacer? AYUDAAAAAA.

ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
        at java.lang.Class.getMethod(Class.java:2950)
        at java.lang.Class.getMethod(Class.java:2450)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
        at com.genymobile.scrcpy.Device.<init>(Device.java:86)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:24)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:372)
INFO: Renderer: direct3d
INFO: Initial texture: 1216x2712
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:36)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:169)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:173)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:215)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:94)
        at com.genymobile.scrcpy.Controller.control(Controller.java:71)
        at com.genymobile.scrcpy.Server$2.run(Server.java:100)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
        at android.os.Parcel.createException(Parcel.java:3041)
        at android.os.Parcel.readException(Parcel.java:3024)
        at android.os.Parcel.readException(Parcel.java:2966)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:1567)
        ... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:912)
        at com.android.server.input.InputManagerService.injectInputEvent(InputManagerService.java:900)
        at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:738)
        at android.os.Binder.execTransactInternal(Binder.java:1346)
        at android.os.Binder.execTransact(Binder.java:1282)

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:36)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:169)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:173)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:215)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:94)
        at com.genymobile.scrcpy.Controller.control(Controller.java:71)
        at com.genymobile.scrcpy.Server$2.run(Server.java:100)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
        at android.os.Parcel.createException(Parcel.java:3041)
        at android.os.Parcel.readException(Parcel.java:3024)
        at android.os.Parcel.readException(Parcel.java:2966)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:1567)
        ... 9 more
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:36)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:169)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:173)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:215)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:94)
        at com.genymobile.scrcpy.Controller.control(Controller.java:71)
        at com.genymobile.scrcpy.Server$2.run(Server.java:100)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
        at android.os.Parcel.createException(Parcel.java:3041)
        at android.os.Parcel.readException(Parcel.java:3024)
        at android.os.Parcel.readException(Parcel.java:2966)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:1567)
        ... 9 more
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:36)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:169)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:173)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:215)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:94)
        at com.genymobile.scrcpy.Controller.control(Controller.java:71)
        at com.genymobile.scrcpy.Server$2.run(Server.java:100)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
        at android.os.Parcel.createException(Parcel.java:3041)
        at android.os.Parcel.readException(Parcel.java:3024)
        at android.os.Parcel.readException(Parcel.java:2966)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:1567)
        ... 9 more
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:36)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:169)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:173)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:215)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:94)
        at com.genymobile.scrcpy.Controller.control(Controller.java:71)
        at com.genymobile.scrcpy.Server$2.run(Server.java:100)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
        at android.os.Parcel.createException(Parcel.java:3041)
        at android.os.Parcel.readException(Parcel.java:3024)
        at android.os.Parcel.readException(Parcel.java:2966)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:1567)
        ... 9 more
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:36)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:169)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:173)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:215)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:94)
        at com.genymobile.scrcpy.Controller.control(Controller.java:71)
        at com.genymobile.scrcpy.Server$2.run(Server.java:100)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
        at android.os.Parcel.createException(Parcel.java:3041)
        at android.os.Parcel.readException(Parcel.java:3024)
        at android.os.Parcel.readException(Parcel.java:2966)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:1567)
        ... 9 more
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:36)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:169)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:173)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:215)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:94)
        at com.genymobile.scrcpy.Controller.control(Controller.java:71)
        at com.genymobile.scrcpy.Server$2.run(Server.java:100)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
        at android.os.Parcel.createException(Parcel.java:3041)
        at android.os.Parcel.readException(Parcel.java:3024)
        at android.os.Parcel.readException(Parcel.java:2966)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:1567)
        ... 9 more

**Comment by rom1v** [comment]
> Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.

Read https://github.com/Genymobile/scrcpy#prerequisites

**Comment by MemphisVercetti** [comment]
Funcionó perfecto, gracias por la ayuda!
