### ISSUE TITLE
Failed to create //.cache for shader cache (Read-only file system)---disabling.

### ISSUE THREAD

**Issue by veryraregaming** [Genymobile/scrcpy#5618]
Any idea how i can resolve this ?

```scrcpy 3.0.2 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.1.169:5555              device  Raspberry_Pi_5
C:\platform-tools\scrcpy-server: 1 file pushed, 0 skipped. 107.4 MB/s (90396 bytes in 0.001s)
[server] INFO: Device: [Raspberry] Raspberry Raspberry Pi 5 (Android 14)
Failed to create //.cache for shader cache (Read-only file system)---disabling.
INFO: Renderer: direct3d
INFO: Texture: 1920x1080
[server] ERROR: Exception on thread Thread[audio-in,5,main]
android.media.MediaCodec$CodecException: 
        at android.media.MediaCodec.native_queueInputBuffer(Native Method)
        at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2910)
        at com.genymobile.scrcpy.audio.AudioEncoder.inputThread(AudioEncoder.java:110)
        at com.genymobile.scrcpy.audio.AudioEncoder.lambda$encode$1$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:209)
        at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Capture/encoding error: java.lang.IllegalStateException: Pending dequeue output buffer request cancelled

[server] INFO: Retrying with -m1600...
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.IllegalStateException: 
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2531)
        at com.genymobile.scrcpy.audio.AudioEncoder.encode(AudioEncoder.java:278)
        at com.genymobile.scrcpy.audio.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:133)
        at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Capture/encoding error: java.lang.IllegalStateException: Pending dequeue output buffer request cancelled

[server] INFO: Retrying with -m1280...
[server] ERROR: Capture/encoding error: java.lang.IllegalStateException: 
[server] INFO: Retrying with -m1024...
[server] ERROR: Capture/encoding error: java.lang.IllegalStateException: 
[server] INFO: Retrying with -m800...
[server] ERROR: Capture/encoding error: java.lang.IllegalStateException: Pending dequeue output buffer request cancelled

WARN: Devic[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.IllegalStateException: Pending dequeue output buffer request cancelled

        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:4009)
        at com.genymobile.scrcpy.video.SurfaceEncoder.encode(SurfaceEncoder.java:202)
        at com.genymobile.scrcpy.video.SurfaceEncoder.streamCapture(SurfaceEncoder.java:110)
        at com.genymobile.scrcpy.video.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-video-SurfaceEncoder(SurfaceEncoder.java:296)
        at com.genymobile.scrcpy.video.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
e disconnected```

**Comment by rom1v** [comment]
Try with another encoder (see `--list-encoders`).

**Comment by rom1v** [comment]
Also try without audio (`--no-audio`).
