### ISSUE TITLE
no audio 

### ISSUE THREAD

**Issue by toto6976** [Genymobile/scrcpy#5642]
Good afternoon,

When i do scrcpy -b1M --video-source=camera --camera-id=1 --tcpip=192.168.x.xx:5555, i have no audio !

What is wrong ?

```
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: Camera video source: control disabled
INFO: Camera video source: microphone audio source selected
INFO: Connecting to 192.168.1.xxxxxxx
INFO: Connected to 192.168.1.xxxxxxx
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 0.2 MB/s (71200 bytes in 0.299s)
[server] INFO: Device: [LGE] lge LG-H870 (Android 14)
[server] ERROR: Could not create default audio encoder for opus
List of audio encoders:
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
    --audio-codec=flac --audio-encoder='OMX.google.flac.encoder'
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe (NAME_NOT_FOUND)
	at android.media.MediaCodec.native_setup(Native Method)
	at android.media.MediaCodec.<init>(MediaCodec.java:2094)
	at android.media.MediaCodec.<init>(MediaCodec.java:2072)
	at android.media.MediaCodec.createEncoderByType(MediaCodec.java:2027)
	at com.genymobile.scrcpy.audio.AudioEncoder.createMediaCodec(AudioEncoder.java:301)
	at com.genymobile.scrcpy.audio.AudioEncoder.encode(AudioEncoder.java:193)
	at com.genymobile.scrcpy.audio.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:131)
	at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
[server] INFO: Using camera '1'
INFO: Renderer: opengl
INFO: OpenGL version: 2.1 Mesa 23.2.1-1ubuntu3.1~22.04.2
WARN: Trilinear filtering disabled (OpenGL 3.0+ or ES 2.0+ required)
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 2560x1920
```

**Comment by toto6976** [comment]
> What's the full output in the console?

I completed the message at the top

**Comment by rom1v** [comment]
> Failed to initialize audio/opus, error 0xfffffffe

Your device has no OPUS encoder.

Add `--audio-codec=aac` to switch to AAC.

**Comment by rom1v** [comment]
No, it's a missing encoder on your device, and scrcpy uses opus by default.

**Comment by toto6976** [comment]
ok. So I have something to install on the smartphone?

**Comment by rom1v** [comment]
No, just always pass the flag.

Add an alias to always pass the flag automatically in your `./bash_aliases`:

```bash
alias scrcpy='scrcpy --audio-codec=aac`
```
