### ISSUE TITLE
[server] ERROR: MediaCodec error on phone reboot - FAQ does not fix

### ISSUE THREAD

**Issue by webenhanced** [Genymobile/scrcpy#5646]
This is a heads up on an un-caught exception that occurs when I reboot the phone while connected. It doesn't impact my use of the great program you've made.

_Please read the [prerequisites] to run scrcpy._
Using rpm from copr:copr.fedorainfracloud.org:zeno:scrcpy

_Also read the [FAQ] and check if your [issue][issues] already exists._
Done

Checked issues and not found.

## Environment

 - **OS:** Fedora 40 x86_64
 - **Scrcpy version:** 3.0.2
 - **Installation method:** dnf from copr:copr.fedorainfracloud.org:zeno:scrcpy
 - **Device model:** Pixel 7
 - **Android version:** CalyxOS Android 15

## Describe the bug
scrcpy exits with an uncaught exception if the phone is rebooted.

Terminal output follows including session start
````
graham@gm-ws1:~$ scrcpy
scrcpy 3.0.2 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  xxxxxxxxxxxx                  device  Pixel_7
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 148.4 MB/s (90396 bytes in 0.001s)
[server] INFO: Device: [Google] google Pixel 7 (Android 15)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 24.1.7
INFO: Trilinear filtering enabled
INFO: Texture: 1080x2400
[server] ERROR: MediaCodec error
android.media.MediaCodec$CodecException: Error 0xffffffe0
[server] ERROR: Exception on thread Thread[audio-in,5,main]
java.lang.IllegalStateException: queueInputBuffer() is valid only at Executing states; currently at Released state

	at android.media.MediaCodec.native_queueInputBuffer(Native Method)
	at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2958)
	at com.genymobile.scrcpy.audio.AudioEncoder.inputThread(AudioEncoder.java:110)
	at com.genymobile.scrcpy.audio.AudioEncoder.lambda$encode$1$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:209)
	at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.IllegalStateException: 
	at android.media.MediaCodec.native_stop(Native Method)
	at android.media.MediaCodec.stop(MediaCodec.java:2579)
	at com.genymobile.scrcpy.audio.AudioEncoder.encode(AudioEncoder.java:278)
	at com.genymobile.scrcpy.audio.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:133)
	at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Capture/encoding error: java.lang.IllegalStateException: Pending dequeue output buffer request cancelled

WARN: Device disconnected

````
I have tried changing the audio codecs as per the FAQ as follows:-
```
[server] INFO: List of video encoders:
    --video-codec=h264 --video-encoder=c2.exynos.h264.encoder         (hw) [vendor]
    --video-codec=h264 --video-encoder=c2.android.avc.encoder         (sw)
    --video-codec=h264 --video-encoder=OMX.google.h264.encoder        (sw) (alias for c2.android.avc.encoder)
    --video-codec=h265 --video-encoder=c2.exynos.hevc.encoder         (hw) [vendor]
    --video-codec=h265 --video-encoder=c2.android.hevc.encoder        (sw)
    --video-codec=av1 --video-encoder=c2.android.av1.encoder          (sw)
[server] INFO: List of audio encoders:
    --audio-codec=opus --audio-encoder=c2.android.opus.encoder        (sw)
    --audio-codec=aac --audio-encoder=c2.android.aac.encoder          (sw)
    --audio-codec=aac --audio-encoder=OMX.google.aac.encoder          (sw) (alias for c2.android.aac.encoder)
    --audio-codec=flac --audio-encoder=c2.android.flac.encoder        (sw)
    --audio-codec=flac --audio-encoder=OMX.google.flac.encoder        (sw) (alias for c2.android.flac.encoder)

```
```
graham@gm-ws1:~$ scrcpy --audio-codec=opus --audio-encoder=c2.android.opus.encoder
INFO: Texture: 1080x2400
[server] ERROR: Exception on thread Thread[audio-in,5,main]
android.media.MediaCodec$CodecException: 
	at android.media.MediaCodec.native_queueInputBuffer(Native Method)
	at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2958)
	at com.genymobile.scrcpy.audio.AudioEncoder.inputThread(AudioEncoder.java:110)
	at com.genymobile.scrcpy.audio.AudioEncoder.lambda$encode$1$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:209)
	at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.IllegalStateException: 
	at android.media.MediaCodec.native_stop(Native Method)
	at android.media.MediaCodec.stop(MediaCodec.java:2579)
	at com.genymobile.scrcpy.audio.AudioEncoder.encode(AudioEncoder.java:278)
	at com.genymobile.scrcpy.audio.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:133)
	at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Capture/encoding error: java.lang.IllegalStateException: Pending dequeue output buffer request cancelled

WARN: Device disconnected
```
Same error when using the other two software audio encoders.

Hope this helps. Let me know if you'd like any more info.

**Comment by rom1v** [comment]
So `--audio-codec=aac` does not work either?

**Comment by webenhanced** [comment]
> So `--audio-codec=aac` does not work either?

No it didn't. I tried all c2.android.*.encoder ones. Same result.

**Comment by webenhanced** [comment]
> Can you reproduce on an older version? (scrcpy 2.7)

Not from the copr repo. But they do have the new 3.1-1 version available now. That wasn't there when I posted this bug.
Would you like me to try that?
Otherwise I'll have to find another way of installing the 2.7 version.

**Comment by webenhanced** [comment]
Same result with v3.1

```
graham@gm-ws1:~$ scrcpy --audio-codec=aac --audio-encoder=c2.android.aac.encoder
scrcpy 3.1 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
INFO: ADB device found:
INFO:     -->   (usb)  xxxxxxxxxxxxxxxxx                  device  Pixel_7
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 151.4 MB/s (90640 bytes in 0.001s)
[server] INFO: Device: [Google] google Pixel 7 (Android 15)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 24.1.7
INFO: Trilinear filtering enabled
INFO: Texture: 1080x2400
[server] ERROR: MediaCodec error
[server] ERROR: Exception on thread Thread[audio-in,5,main]
android.media.MediaCodec$CodecException: 
	at android.media.MediaCodec.native_queueInputBuffer(Native Method)
	at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2958)
	at com.genymobile.scrcpy.audio.AudioEncoder.inputThread(AudioEncoder.java:110)
	at com.genymobile.scrcpy.audio.AudioEncoder.lambda$encode$1$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:209)
	at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
android.media.MediaCodec$CodecException: Error 0xffffffe0
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.IllegalStateException: 
	at android.media.MediaCodec.native_stop(Native Method)
	at android.media.MediaCodec.stop(MediaCodec.java:2579)
	at com.genymobile.scrcpy.audio.AudioEncoder.encode(AudioEncoder.java:278)
	at com.genymobile.scrcpy.audio.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-audio-AudioEncoder(AudioEncoder.java:133)
	at com.genymobile.scrcpy.audio.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Capture/encoding error: java.lang.IllegalStateException: Pending dequeue output buffer request cancelled

WARN: Device disconnected
```
I haven't tried with v2.7 yet.
