### ISSUE TITLE
[server] ERROR: Could not invoke method

### ISSUE THREAD

**Issue by rekinxd** [Genymobile/scrcpy#5652]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** [Windows]
 - **Scrcpy version:** [3.1]
 - **Installation method:** [manual build]
 - **Device model:**
 - **Android version:** [14]

## Describe the bug

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
        at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:69)
        at com.genymobile.scrcpy.control.Controller.injectTouch(Controller.java:492)
        at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:256)
        at com.genymobile.scrcpy.control.Controller.control(Controller.java:195)
        at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:203)
        at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1312)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 9 more
[server] ERROR: Could not invoke method

```
,
Please do not post screenshots of your terminal, just post the content as text instead.
sorry i dont know english and i dont know how to fix thid problem, please help

**Comment by rom1v** [comment]
> Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.

https://github.com/Genymobile/scrcpy#prerequisites
