### ISSUE TITLE
Help me pls

### ISSUE THREAD

**Issue by Macqs314** [Genymobile/scrcpy#5710]
when I connected my poco m5s, everything worked for me, the screen appeared, but when I tried to move the mouse, I got these errors
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
        at com.genymobile.scrcpy.device.Device.injectEvent(Device.java:69)
        at com.genymobile.scrcpy.control.Controller.injectTouch(Controller.java:492)
        at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:256)
        at com.genymobile.scrcpy.control.Controller.control(Controller.java:195)
        at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:203)
        at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 9 more

**Comment by Macqs314** [comment]
I have enabled additional usb debugging (security) but still this error

**Comment by rom1v** [comment]
Did you reboot your device after you enabled the option?

**Comment by Macqs314** [comment]
yes

**Comment by Macqs314** [comment]
stop

**Comment by Macqs314** [comment]
I noticed that he was asking me to log in to my MI account

**Comment by Macqs314** [comment]
What do I need to do?

**Comment by Macqs314** [comment]
I created a Mi account, enabled usb deferral (security), but it still doesn't work.
![Uploading 2024-12-28_17-50-51.png…]()

**Comment by cutebunnygaming10** [comment]
delete the scrcpy and make sure your device is unlocked and if it asks you to trust the computer trust it (gotta be your own computer if it's a friends computer

and what is the MI account?

**Comment by rom1v** [comment]
You must reboot once the option is enabled.

**Comment by Macqs314** [comment]
I turned this option on again, it didn't turn on the first time. I'm restarting my phone

**Comment by cutebunnygaming10** [comment]
and also reboot the computer

**Comment by Macqs314** [comment]
Everything worked. Thanks!!!

**Comment by cutebunnygaming10** [comment]
good
:)

**Comment by Macqs314** [comment]
Can I turn on my phone through this app somehow if the phone is turned off?

**Comment by cutebunnygaming10** [comment]
i don't think so

**Comment by Macqs314** [comment]
understood. Thanks again!
