### ISSUE TITLE
scrcpy not working with Vollaphone X23

### ISSUE THREAD

**Issue by franco-bez** [Genymobile/scrcpy#5711]
there are several reports that scrcpy is not working on the Vollaphone X23, at least VOS 14 (AOSP 14 based) is affected, maybe older versions as well.
Other devices like the Vollaphone22 and the Vollaphone Quintus are not affected, it seems to be a X23 only problem.

The ticket was first reported to Volla ( https://github.com/HelloVolla/volla-os-beta-test/issues/199 ) but they closed it and told me to report it here.

```
scrcpy 3.0.2 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  GX4VCTR                   device  Volla_Phone_X23
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 150.3 MB/s (90396 bytes in 0.001s)
[server] INFO: Device: [Volla] volla Volla Phone X23 (Android 14)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 24.0.9-0ubuntu0.2
INFO: Trilinear filtering enabled
INFO: Texture: 720x1560
[server] ERROR: Capture/encoding error: java.lang.IllegalArgumentException: 
[server] INFO: Retrying with -m1280...
[server] ERROR: Capture/encoding error: java.lang.IllegalArgumentException: 
[server] INFO: Retrying with -m1024...
[server] ERROR: Capture/encoding error: java.lang.IllegalArgumentException: 
[server] INFO: Retrying with -m800...
[server] ERROR: Capture/encoding error: java.lang.IllegalArgumentException: 
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.IllegalArgumentException: 
 at android.media.MediaCodec.native_configure(Native Method)
 at android.media.MediaCodec.configure(MediaCodec.java:2386)
 at android.media.MediaCodec.configure(MediaCodec.java:2302)
 at com.genymobile.scrcpy.video.SurfaceEncoder.streamCapture(SurfaceEncoder.java:92)
 at com.genymobile.scrcpy.video.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-video-SurfaceEncoder(SurfaceEncoder.java:296)
 at com.genymobile.scrcpy.video.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
 at java.lang.Thread.run(Thread.java:1012)
``` 

see also the TG groups
https://t.me/c/1289127708/4896
https://t.me/hello_volla/129136

**Comment by rachyandco** [comment]
i confirm same issue. it was working fine on Android 13. but fails on 14 with the same error as above

**Comment by franco-bez** [comment]
fixed in latest VollaOS 14 Release

**Comment by rachyandco** [comment]
I confirm it works with version March 2, 2025 Android 14 VollaOS (14-20250302-STABLE-vidofnir)
