### ISSUE TITLE
adb devices is OK but scrcpy not work

### ISSUE THREAD

**Issue by fancyhugo** [Genymobile/scrcpy#5718]
## Environment

 - **OS:** [e.g. Debian, Windows, macOS...]
 - ubuntu 18.0.4.6
 - **Scrcpy version:** 1.25

## Describe the bug
it works all fine for me previously，but sudden have some errors
adb devices can display the devices
and scrcpy errors like this
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:86)
	at com.genymobile.scrcpy.Device.<init>(Device.java:66)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
	at com.genymobile.scrcpy.Server.main(Server.java:334)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:72)
	... 5 more
ERROR: Server connection failed

reboot the android device and computer still have this error

**Comment by rom1v** [comment]
> Scrcpy version: 1.25

Outdated version. Install the last one (currently 3.1).

**Comment by fancyhugo** [comment]
hi，guys ,it seems  the rom bugs
“adb shell service list” commands not display the "display" process,so I Reinstall the system image，and it work fine
so close the issus

**Comment by rom1v** [comment]
Ok, but you should still update to 3.1.
