### ISSUE TITLE
screen not update randomly on osx

### ISSUE THREAD

**Issue by catinred2** [Genymobile/scrcpy#576]
screen just not update after some time, and would restore randomly, too. and keyboard / mouse event still works.

**Comment by rom1v** [comment]
Over USB or wirelessly?

Does it happen when you are resizing, or even when you do nothing special?

When the screen is not updated on the computer, is the screen content changing on the device?

**Comment by catinred2** [comment]
> Over USB or wirelessly?
>
> Does it happen when you are resizing, or even when you do nothing special?
> 
> When the screen is not updated on the computer, is the screen content changing on the device?

It is connected over USB, and it happens when I run my ui automator test,  nothing special. The screen content changes on the device.

**Comment by rom1v** [comment]
If you record with scrcpy, then play the video (with VLC or whatever), is the content updated correctly?

    scrcpy --record file.mkv

If it isn't, is it better with `screenrecord`?

    adb shell screenrecord /sdcard/file.mp4
    adb pull /sdcard/file.mp4

**Comment by catinred2** [comment]
It seems the video is ok, content  updated correctly.

**Comment by rom1v** [comment]
Oh, so it might be the known issue with SDL 2.0.9 (see #425), although it had always been reported for Windows only.

To get your SDL version:

    scrcpy --version

Could you downgrade to 2.0.8 and test?

**Comment by catinred2** [comment]
quite tricky to downgrade sdl2 to 2.0.8 with HomeBrew. is there any convenient way to do that ?

**Comment by rom1v** [comment]
Sorry, I have no idea ¯\_(ツ)_/¯

**Comment by rom1v** [comment]
Maybe you could try this patch instead: https://github.com/Genymobile/scrcpy/issues/425#issuecomment-472588709

**Comment by catinred2** [comment]
@rom1v that does not work for me.

**Comment by rom1v** [comment]
Does it still happen?

**Comment by DrMurx** [comment]
I've quite the same issue on MacOS. 

Screen capture is stopped out of a sudden, but mouse and keyboard works. Changing the device orientation helps to restore the screen capture.

```
$ scrcpy --version
scrcpy 1.16

dependencies:
 - SDL 2.0.12
 - libavcodec 58.91.100
 - libavformat 58.45.100
 - libavutil 56.51.100
 ```

**Comment by rom1v** [comment]
If you record (`scrcpy --record file.mkv`), does the recorded file suffer from the same issue?

**Comment by rom1v** [comment]
Also, does it help if you apply this patch and rebuild?

```diff
diff --git a/app/src/scrcpy.c b/app/src/scrcpy.c
index 4c502ff6..b4d2a317 100644
--- a/app/src/scrcpy.c
+++ b/app/src/scrcpy.c
@@ -134,10 +134,6 @@ sdl_init_and_configure(bool display, const char *render_driver,
 }
 
 
-#if defined(__APPLE__) || defined(__WINDOWS__)
-# define CONTINUOUS_RESIZING_WORKAROUND
-#endif
-
 #ifdef CONTINUOUS_RESIZING_WORKAROUND
 // On Windows and MacOS, resizing blocks the event loop, so resizing events are
 // not triggered. As a workaround, handle them in an event handler.
```

**Comment by Meryjolie** [comment]
Grazie, I hope to use it rightly. /\
-- 
 Inviato in modo sicuro con Tutanota. Ottieni la tua casella di posta elettronica crittografata e senza pubblicità: 
 https://tutanota.com


2 gen 2021, 21:01 da notifications@github.com:

**Comment by DrMurx** [comment]
> If you record (`scrcpy --record file.mkv`), does the recorded file suffer from the same issue?

Crashes with this exception:

```
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2570)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:108)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#crashes
