### ISSUE TITLE
ADB problem

### ISSUE THREAD

**Issue by mazzod** [Genymobile/scrcpy#582]
Hello, 
is there a way to fix this problem? I'm on Android 9 on Umidigi F1.
Thanks
![2019-06-11_13-57-26](https://user-images.githubusercontent.com/20927620/59270204-34590680-8c51-11e9-9f99-c4477477d34d.jpg)

**Comment by rom1v** [comment]
(please copy-paste text instead of screenshot, so it's searchable)

You have a software installed on your computer that executes `adb` commands with an old version of adb (31). Since this is not the same version, the adb daemons just kill each other.

Find this software and make it use the same version of `adb` as _scrcpy_ (version 31 is very old).

**Comment by mazzod** [comment]
Thanks for the hint, now the adb version error disappeared but I'm still having the others:

ERROR: Could not open video stream
ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2084)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:75)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:28)
        at com.genymobile.scrcpy.Server.main(Server.java:110)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
INFO: Initial texture: 1080x2336
Press any key to continue...

What am I missing?

**Comment by rom1v** [comment]
Your hardware encoder is probably not able to encode at this definition/resolution.

Try to reduce the definition:

    scrcpy -m 1024

**Comment by mazzod** [comment]
That was the problem, with - m 1024 I can mirror my device on pc. Thanks for the support!
