### ISSUE TITLE
v1.9 does not work on Linux, getting "X Error of failed request:  BadValue"

### ISSUE THREAD

**Issue by logix2** [Genymobile/scrcpy#584]
Trying to use scrcpy 1.9 on Ubuntu 19.04, I get this error:

```
logix@logix-desktop:~$ scrcpy -p 12341
/usr/local/bin/scrcpy-server.jar: 1 file pushed. 5.5 MB/s (22470 bytes in 0.004s)
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  105
  Current serial number in output stream:  106
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xffffec77
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1882)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:157)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:67)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
	at com.genymobile.scrcpy.Server.main(Server.java:133)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:316)
```
The phone is a Samsung Galaxy S6 running Android 7.0 (also encountered the same error on a Samsung Galaxy S8).

Version 1.8 was working fine.

**Comment by rom1v** [comment]
If you `git checkout v1.8` now and rebuild, does it work?

Before further investigations, could you `git pull` (to get fix for https://github.com/Genymobile/scrcpy/pull/583).
Do you use the prebuilt_server? (if yes, you need to use the v1.9 of the prebuilt_server now).

**Comment by logix2** [comment]
It looks like I had some X updates (I probably had some upgraded, but not all). After upgrading all packages on my system, and a system restart, it works now. Sorry for the inconvenience!

**Comment by rom1v** [comment]
Try to run `glxgears`. Do you have the same error?
