### ISSUE TITLE
IllegalArgumentException: Expecting 5 parameters

### ISSUE THREAD

**Issue by jimmyferiawan** [Genymobile/scrcpy#630]
i got this error after compiling from source in my debian 9
```bash
[100%] /data/local/tmp/scrcpy-server.jar
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Expecting 5 parameters
	at com.genymobile.scrcpy.Server.createOptions(Server.java:71)
	at com.genymobile.scrcpy.Server.main(Server.java:132)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:289)
```
my build command
```bash
jimmyferiawan@senju:~/Downloads/scrcpy-master$ meson x --buildtype release --strip -Db_lto=true -Dprebuilt_server=/home/jimmyferiawan/Downloads/scrcpy-server-v1.9.jar
The Meson build system
Version: 0.37.1
Source dir: /home/jimmyferiawan/Downloads/scrcpy-master
Build dir: /home/jimmyferiawan/Downloads/scrcpy-master/x
Build type: native build
Project name: scrcpy
Native c compiler: cc (gcc 6.3.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29)
Native dependency libavformat found: YES 57.56.101
Native dependency libavcodec found: YES 57.64.101
Native dependency libavutil found: YES 55.34.101
Native dependency sdl2 found: YES 2.0.5
Build targets in project: 6

```

**Comment by rom1v** [comment]
The client and server version don't match.

If you use server v1.9 as your command suggests, then your `master` is probably not up to date.

    git pull

**Comment by jimmyferiawan** [comment]
it works, thank you
