### ISSUE TITLE
MacOS Input not working and crashing touch input

### ISSUE THREAD

**Issue by Empty2k12** [Genymobile/scrcpy#69]
I was typing "You going home 2day?" on MacOS. Key input does not work at all, touch input works. One of the characters must have triggered the crash. After the crash happened touch input didn't work, either.

```
WARN: Unknown event type: -128
WARN: Unknown event type: -128
WARN: Unknown event type: -128
WARN: Unknown event type: -128
WARN: Unknown event type: -128
WARN: Unknown event type: -128
WARN: Unknown event type: -128
WARN: Unknown event type: -128
WARN: Unknown event type: -128
ERROR: Exception on thread Thread[Thread-1,5,main]
java.lang.IllegalStateException: Buffer full, call next() to consume
        at com.genymobile.scrcpy.ControlEventReader.readFrom(ControlEventReader.java:34)
        at com.genymobile.scrcpy.DesktopConnection.receiveControlEvent(DesktopConnection.java:74)
        at com.genymobile.scrcpy.EventController.handleEvent(EventController.java:70)
        at com.genymobile.scrcpy.EventController.control(EventController.java:65)
        at com.genymobile.scrcpy.Server$1.run(Server.java:34)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by rom1v** [comment]
What version are you compiling?

```
git rev-parse -1 HEAD
```

Did you use the prebuilt server? (v1.1 if you are compiling `master`)

**Comment by Empty2k12** [comment]
@rom1v Cloned 10 minutes ago (latest ref) and using prebuilt server (`v1.0`). Should I replace the server with 1.1?

**Comment by Empty2k12** [comment]
Latest server (`v1.1`) fixes the input issue.
