### ISSUE TITLE
Can't connect to FireTV over WiFi

### ISSUE THREAD

**Issue by brandoFS** [Genymobile/scrcpy#724]
I don't know if scrcpy is supposed to support this or not but I'm unable to connect to a FireTV device. I use adb to connect via Wifi for logging and loading builds through Android studio so I would assume that scrcpy could work but maybe there's something from Amazon blocking it 

```
$ scrcpy
2019-08-14 15:39:39.104 scrcpy[38345:8250078] INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.10/share/scrcpy/scrcpy-server.jar: 1 file pushed. 0.3 MB/s (22662 bytes in 0.065s)
adb: error: more than one device and emulator
2019-08-14 15:39:39.219 scrcpy[38345:8250078] ERROR: "adb reverse" returned with value 1
2019-08-14 15:39:39.219 scrcpy[38345:8250078] WARN: 'adb reverse' failed, fallback to 'adb forward'
27183
2019-08-14 15:39:39.919 scrcpy[38345:8250078] INFO: Initial texture: 1920x1080
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:599)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:157)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:67)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
	at com.genymobile.scrcpy.Server.main(Server.java:133)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:256)
```

my normal adb commands 

```
$ adb devices
List of devices attached
172.17.9.47:5555	device
```

**Comment by rom1v** [comment]
Try with a lower definition ([FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream)):

    scrcpy -m1024

**Comment by brandoFS** [comment]
@rom1v thank you!

**Comment by rom1v** [comment]
And over wifi, I suggest to reduce the bitrate:

    scrcpy -m1024 -b2M

(you can also try to increase the definition if you want)
