### ISSUE TITLE
Error on a x86 Asus tablet

### ISSUE THREAD

**Issue by porfirioribeiro** [Genymobile/scrcpy#73]
I don't know if the issue is the ABI (x86) or the OS version (Marshmallow) but i cant get scrcpy to work on my Asus Zenpad Z580CA.

I get this error:
```
/usr/share/scrcpy/scrcpy-server.jar: 1 file pushed. 1.3 MB/s (19334 bytes in 0.014s)
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
ERROR: Could not open video stream
ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1778)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:135)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:62)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:22)
        at com.genymobile.scrcpy.Server.main(Server.java:78)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
INFO: Initial texture: 2048x1536
```

I guess it is a codec issue, maybe we can try other codec?

**Comment by rom1v** [comment]
Yes, it's a codec issue, but difficult to know why.

Could you test with a lower resolution/bitrate?

    scrcpy -b2M -m 800

**Comment by porfirioribeiro** [comment]
It works!
I forgot to mention it is a 2K screen with 2048x1536

The max res i could get it work was: `scrcpy -m 1664`
`INFO: Initial texture: 1664x1248`

Thank's

**Comment by innerspacepilot** [comment]
> Yes, it's a codec issue, but difficult to know why.
> 
> Could you test with a lower resolution/bitrate?
> 
> ```
> scrcpy -b2M -m800
> ```

Would you please add this instruction to scrcpy-server.jar  error text.
Thanks
