### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by luneice** [Genymobile/scrcpy#734]
It got wrong in Ubuntu 18.04 when i execute ```ninja```. The detail as follows:
```
[0/1] Generating scrcpy-server with a custom command.
[1/1] Generating scrcpy-server with a custom command.
FAILED: server/scrcpy-server.jar 
/luneice/scrcpy/server/./scripts/build-wrapper.sh /luneice/scrcpy/server server/scrcpy-server.jar release
Downloading https://services.gradle.org/distributions/gradle-5.1.1-all.zip

Exception in thread "main" java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2061)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:67)
	at org.gradle.wrapper.Download.download(Download.java:52)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
ninja: build stopped: subcommand failed.
```
The enviroments in my computer as follows:

```
java -version

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

```
meson configure x

Core properties:
  Source dir /luneice/scrcpy
  Build dir  /luneice/scrcpy/x

Core options:
  Option          Current Value Possible Values                                  Description
  ------          ------------- ---------------                                  -----------
  buildtype       release       [plain, debug, debugoptimized, release, minsize] Build type to use.
  warning_level   1             [1, 2, 3]                                        Compiler warning level to use.
  werror          false         [true, false]                                    Treat warnings as errors.
  strip           true          [true, false]                                    Strip targets on install.
  unity           off           [on, off, subprojects]                           Unity build.
  default_library shared        [shared, static]                                 Default library type.

  Option            Current Value Description
  ------            ------------- -----------
  backend_max_links 0             Maximum number of linker processes to run or 0 for no limit

Base options:
  Option      Current Value Possible Values                                               Description
  ------      ------------- ---------------                                               -----------
  b_asneeded  true          [true, false]                                                 Use -Wl,--as-needed when linking
  b_colorout  always        [auto, always, never]                                         Use colored output
  b_coverage  false         [true, false]                                                 Enable coverage tracking.
  b_lto       true          [true, false]                                                 Use link time optimization
  b_lundef    true          [true, false]                                                 Use -Wl,--no-undefined when linking
  b_ndebug    false         [true, false, if-release]                                     Disable asserts
  b_pch       true          [true, false]                                                 Use precompiled headers
  b_pgo       off           [off, generate, use]                                          Use profile guided optimization
  b_sanitize  none          [none, address, thread, undefined, memory, address,undefined] Code sanitizer to use
  b_staticpic true          [true, false]                                                 Build static libraries as position independent

Compiler arguments:
  c_args []

Linker args:
  c_link_args []

Compiler options:
  Option Current Value Description
  ------ ------------- -----------
  c_std  c11           C language standard to use

Directories:
  Option         Current Value        Description
  ------         -------------        -----------
  prefix         /usr/local           Installation prefix.
  libdir         lib/x86_64-linux-gnu Library directory.
  libexecdir     libexec              Library executable directory.
  bindir         bin                  Executable directory.
  sbindir        sbin                 System executable directory.
  includedir     include              Header file directory.
  datadir        share                Data file directory.
  mandir         share/man            Manual page directory.
  infodir        share/info           Info page directory.
  localedir      share/locale         Locale data directory.
  sysconfdir     etc                  Sysconf data directory.
  localstatedir  /var/local           Localstate data directory.
  sharedstatedir /var/local/lib       Architecture-independent data directory.

Project options:
  Option             Current Value Possible Values Description
  ------             ------------- --------------- -----------
  compile_app        true          [True, False]   Build the client
  compile_server     true          [True, False]   Build the server
  crossbuild_windows false         [True, False]   Build for Windows from Linux
  hidpi_support      true          [True, False]   Enable High DPI support
  portable           false         [True, False]   Use scrcpy-server.jar from the same directory as the scrcpy executable
  prebuilt_server                                  Path of the prebuilt server
  windows_noconsole  false         [True, False]   Disable console on Windows (pass -mwindows flag)

Testing options:
  Option    Current Value Possible Values Description
  ------    ------------- --------------- -----------
  stdsplit  true          [true, false]   Split stdout and stderr in test logs.
  errorlogs true          [true, false]   Whether to print the logs from failing tests.
```

**Comment by rom1v** [comment]
It seems it failed to download gradle to build the server, so probably a connection issue.

**Comment by luneice** [comment]
> It seems it failed to download gradle to build the server, so probably a connection issue.

but when i run ```wget https://services.gradle.org/distributions/gradle-5.5.1-all.zip``` it working.

**Comment by luneice** [comment]
@rom1v but when i run ```wget https://services.gradle.org/distributions/gradle-5.5.1-all.zip it working.```
