### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by sajjadjaved01** [Genymobile/scrcpy#761]
Device Version: 4.4 (Android TV Box)

adb.exe: error: closed
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
27183
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.VerifyError: com/genymobile/scrcpy/IO
        at com.genymobile.scrcpy.DesktopConnection.send(DesktopConnection.java:100)
        at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:19)
        at com.genymobile.scrcpy.Server.main(Server.java:133)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:243)
        at dalvik.system.NativeStart.main(Native Method)
ERROR: Could not retrieve device information
WARN: Cannot terminate server
Press any key to continue...

**Comment by rom1v** [comment]
> Device Version: 4.4 (Android TV Box)

https://github.com/Genymobile/scrcpy/blob/master/README.md#requirements

> The Android device requires at least API 21 (Android 5.0).

and #98.
