### ISSUE TITLE
opening report errors

### ISSUE THREAD

**Issue by qiuqingpo** [Genymobile/scrcpy#763]
```
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
D:\soft\huawei\scrcpy\scrcpy-server.jar: 1 file pushed. 0.3 MB/s (22546 bytes in 0.084s)
INFO: Initial texture: 720x1280
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1055)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:72)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
        at com.genymobile.scrcpy.Server.main(Server.java:133)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
Press any key to continue...
```

**Comment by rom1v** [comment]
Every time?

#465

**Comment by xMumion** [comment]
I have a simliar error with a slightly different stack trace on my Mate 20 Lite device. Here is the Stacktrace please tell me what else I can provide to support.
```
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
C:\Users\bendan5l\Downloads\scrcpy-win64-v1.10\scrcpy-server.jar: 1 file pushed. 1.6 MB/s (22546 bytes in 0.014s)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1967)
        at android.media.MediaCodec.configure(MediaCodec.java:1896)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:157)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:67)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
        at com.genymobile.scrcpy.Server.main(Server.java:133)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:
INFO: Initial texture: 1080x2336
WARN: Could not terminate server
Press any key to continue...
```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream

**Comment by dedosmedia** [comment]
I am also having the same issue on Huawei P8 Lite.
The weird thing is that it was working till 4 days ago...  Now I always receive this error.
adb.exe: error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
27183
INFO: Initial texture: 184x320
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2406)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:72)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
        at com.genymobile.scrcpy.Server.main(Server.java:133)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
Press any key to continue...


I have tried with -m 800, 400, etc
And it always fails with the same issue.

**Comment by rom1v** [comment]
Does it work with `screenrecord`?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

**Comment by dedosmedia** [comment]
Thanks @rom1v on my case, I noticed rebooting the device it works again, so I am not sure what was.
