### ISSUE TITLE
Turn device screen off (keep mirroring) not working with Android 10

### ISSUE THREAD

**Issue by WesleyM77** [Genymobile/scrcpy#788]
I've pressed ctrl+o and it doesn't turn off the screen on my device. Recently updated to Android 10 on Pixel 2 XL.

**Comment by rom1v** [comment]
What about:

    scrcpy --turn-screen-off

?

**Comment by WesleyM77** [comment]
Nope.

Got this call stack though:

`Exception on thread Thread[Thread-1,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.getBuiltInDisplay [int]
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getBuiltInDisplay(SurfaceControl.java:82)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:164)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:113)
        at com.genymobile.scrcpy.Controller.control(Controller.java:73)
        at com.genymobile.scrcpy.Server$1.run(Server.java:45)
        at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.getBuiltInDisplay [int]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getMethod(Class.java:1693)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getBuiltInDisplay(SurfaceControl.java:80)
        ... 5 more`

**Comment by rom1v** [comment]
scrcpy --version

#586 #587

**Comment by WesleyM77** [comment]
Oof, I was on 1.9. Thought I updated... my bad. Thanks for the extremely quick help!

**Comment by agsola** [comment]
I'm on Android 10 and, despite trying to work, and not crashing, the screen doesn't turn off. Instead it shows a weird colorful (like old tv with no image) static image.

I can provide a photo is desired or logs.

**Comment by agsola** [comment]
After restarting and updating it does not happens anymore...
