### ISSUE TITLE
Copying and pasting to device on Android 10 crashes server

### ISSUE THREAD

**Issue by pierlon** [Genymobile/scrcpy#796]
In Android 10, clipboard data access is limited to the app that currently has focus, or is the default method editor (IME) ([see privacy changes][changes]).

Also, the methods `getPrimaryClip` and `setPrimaryClip` now require a user ID for the [calling package](https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-10.0.0_r2/core/java/android/content/IClipboard.aidl).

[changes]: https://developer.android.com/about/versions/10/privacy/changes#clipboard-data

Logs if needed:
- <details>
    <summary>Copying from device</summary>

     ```
    java.lang.AssertionError: java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.getPrimaryClip [class java.lang.String]
        at com.genymobile.scrcpy.wrappers.ClipboardManager.<init>(ClipboardManager.java:20)
        at com.genymobile.scrcpy.wrappers.ServiceManager.getClipboardManager(ServiceManager.java:75)
        at com.genymobile.scrcpy.Device.getClipboardText(Device.java:148)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:106)
        at com.genymobile.scrcpy.Controller.control(Controller.java:73)
        at com.genymobile.scrcpy.Server$1.run(Server.java:45)
        at java.lang.Thread.run(Thread.java:919)
    Caused by: java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.getPrimaryClip [class java.lang.String]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getMethod(Class.java:1693)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.<init>(ClipboardManager.java:17)
    ```
  </details>

- <details>
    <summary>Copying to device</summary>

     ```
    java.lang.IllegalStateException: Buffer full, call next() to consume
    	at com.genymobile.scrcpy.ControlMessageReader.readFrom(ControlMessageReader.java:35)
    	at com.genymobile.scrcpy.DesktopConnection.receiveControlMessage(DesktopConnection.java:110)
    	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:82)
    	at com.genymobile.scrcpy.Controller.control(Controller.java:73)
    	at com.genymobile.scrcpy.Server$1.run(Server.java:45)
    	at java.lang.Thread.run(Thread.java:919)
    ```
  </details>

**Comment by rom1v** [comment]
My device just received the Android 10 upgrade tonight, so I fixed the issue: 8b33c6c1087a183c7e8a7d45445eb0673b50e458

**Comment by yogurtearl** [comment]
@rom1v Can we get a release with this fix? :)

**Comment by rom1v** [comment]
@yogurtearl Done, v1.11 is released.
