### ISSUE TITLE
crashes on click

### ISSUE THREAD

**Issue by 0xC1A551C** [Genymobile/scrcpy#808]
my android tv crashes the moment i click anywhere within scrcpy on my t95s1 box.

It causes the whole box to reboot and i get this error:

```
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server....shed. 0.2 MB/s (22546 bytes in 0.089s)
INFO: Initial texture: 1280x720
[server] ERROR: Exception on thread Thread[Thread-1,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:31)
	at com.genymobile.scrcpy.Device.injectInputEvent(Device.java:124)
	at com.genymobile.scrcpy.Controller.injectEvent(Controller.java:194)
	at com.genymobile.scrcpy.Controller.injectMouse(Controller.java:164)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:91)
	at com.genymobile.scrcpy.Controller.control(Controller.java:73)
	at com.genymobile.scrcpy.Server$1.run(Server.java:45)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:29)
	... 7 more
Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:615)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:536)
	... 9 more


```

**Comment by rom1v** [comment]
Does it still happen with the latest version?
