### ISSUE TITLE
Error on turning device screen off

### ISSUE THREAD

**Issue by Ace081** [Genymobile/scrcpy#909]
My device: OnePlus 7T, Android 10, OOS 10.0.4

When I try to turn the device screen off, regardless if by -S or by Ctrl-o, I am getting the following error message:
[server] ERROR: Exception on thread Thread[Thread-1,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:96)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:165)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:113)
        at com.genymobile.scrcpy.Controller.control(Controller.java:73)
        at com.genymobile.scrcpy.Server$1.run(Server.java:45)
        at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:94)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:1523)
        ... 7 more

**Comment by rom1v** [comment]
It's fixed on `dev` branch (the next release will have the fix). See #835
