### ISSUE TITLE
Error while installing (Ubuntu 19.10)

### ISSUE THREAD

**Issue by NusryNizam** [Genymobile/scrcpy#929]
This is the output I get when installing. Cannot understand the problem. Any help is appreciated. Thanks.

 **$ sudo ninja -Cx install**
```
ninja: Entering directory `x'
[0/1] Installing files.
Installing app/scrcpy to /usr/local/bin
Stripping target 'app/scrcpy'
Installing server/scrcpy-server.jar to /usr/local/share/scrcpy
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 127, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 514, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 343, in do_install
    self.install_targets(d)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 492, in install_targets
    install_name_mappings, verbose=False)
  File "/usr/lib/python3/dist-packages/mesonbuild/scripts/depfixer.py", line 440, in fix_rpath
    fix_jar(fname)
  File "/usr/lib/python3/dist-packages/mesonbuild/scripts/depfixer.py", line 421, in fix_jar
    subprocess.check_call(['jar', 'xfv', fname, 'META-INF/MANIFEST.MF'])
  File "/usr/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'jar': 'jar'
FAILED: meson-install 
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

**Comment by rom1v** [comment]
It's because meson attempts to modify the jar: https://github.com/Genymobile/scrcpy/issues/404#issuecomment-456070408

You must install the OpenJDK.

Alternatively, you could build the `dev` branch instead of `master`, which includes this commit: https://github.com/Genymobile/scrcpy/commit/3da95b52bd21ae0f4d81ee933caea63b78191deb
