### ISSUE TITLE
 Exception on thread Thread

### ISSUE THREAD

**Issue by taozhuIT** [Genymobile/scrcpy#937]
```
D:\scrscy\scrcpy-win64-v1.10\scrcpy-server.jar: 1 file pushed. 2.6 MB/s (22546 bytes in 0.008s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
        at android.media.MediaCodec.configure(MediaCodec.java:1918)
        at android.media.MediaCodec.configure(MediaCodec.java:1873)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:157)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:67)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
        at com.genymobile.scrcpy.Server.main(Server.java:133)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
INFO: Initial texture: 400x800
Press any key to continue...
```

**Comment by rom1v** [comment]
Meizu device, I guess?

See https://github.com/Genymobile/scrcpy/issues/365, it's fixed on `dev`.

**Comment by taozhuIT** [comment]
yes Meizu device    thank you

**Comment by taozhuIT** [comment]
> 魅族设备，我猜呢？
> 
> 请参阅[＃365](https://github.com/Genymobile/scrcpy/issues/365)，它已固定在上`dev`。

yes Meizu device thank you
