### ISSUE TITLE
Exception on thread Thread[main,5,main]

### ISSUE THREAD

**Issue by Foahh** [Genymobile/scrcpy#947]
Model: MiPad4 Plus
OS: LineageOS 17.0 based on Android 10.0

```
INFO:scrcpy 1.11 <https://github.com/Genymobile/scrcpy>
C:\******\scrcpy-win64-v1.11\scrcpy-server: 1 file pushed. 3.9 MB/s (25454 bytes in 0.006s)
INFO: Initial texture: 1920x1200
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:92)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
        at com.genymobile.scrcpy.Server.main(Server.java:146)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
WARN: Device disconnected
Press any key to continue...
```

**Comment by rom1v** [comment]
Thank you for the report.

This is a duplicate of #465 so I'm closing this one.

**Comment by Foahh** [comment]
> Thank you for the report.
> 
> This is a duplicate of #465 so I'm closing this one.
Thanks.

**Comment by Foahh** [comment]
Thanks.
