### ISSUE TITLE
Having trouble connecting my phone

### ISSUE THREAD

**Issue by Sth32** [Genymobile/scrcpy#968]
honor 9x, EMUI: 9.1.1
adb connected
log of scrcpy
```
INFO: scrcpy 1.11 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 4.9 MB/s (25454 bytes in 0.005s)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1967)
        at android.media.MediaCodec.configure(MediaCodec.java:1896)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:167)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:68)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
        at com.genymobile.scrcpy.Server.main(Server.java:146)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:
INFO: Initial texture: 1080x2336
WARN: Device disconnected
```

adb logca *:E
```
11-30 16:04:30.171  3948  3948 E Zygote  : register_com_android_internal_os_Zygote num = 0
11-30 16:04:30.178  3948  3948 E libc    : Access denied finding property "ro.config.vol_steps"
11-30 16:04:30.226  3948  3948 E libc    : Access denied finding property "ro.kirin.product.platform"
11-30 16:04:30.226  3948  3948 E HwExtendedCodec: mime: video/avc matching compontent failed!
11-30 16:04:30.241   799 31768 E OMXNodeInstance: setConfig(0xebb29020:hisi.encoder.avc, ??(0x6f700006)) ERROR: BadParameter(0x80001005)
11-30 16:04:30.247   799 31768 E VENC    : [SetPortDefinition] : [5228] nFrameWidth:1080 nFrameHeight:2336 should between [176 X 144] [1920 X 1088]
11-30 16:04:30.247   799 31768 E OMXNodeInstance: setParameter(0xebb29020:hisi.encoder.avc, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
11-30 16:04:30.247  3948  3963 E ACodec  : [OMX.hisi.video.encoder.avc] failed to set input port definition parameters.
11-30 16:04:30.247  3948  3963 E ACodec  : [OMX.hisi.video.encoder.avc] configureCodec returning error -1010
11-30 16:04:30.247  3948  3963 E ACodec  : signalError(omxError 0x80001001, internalError -1010)
11-30 16:04:30.247  3948  3962 E MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3
11-30 16:04:30.248  3948  3948 E MediaCodec: configure failed with err 0xfffffc0e, resetting...
11-30 16:04:30.268  3948  3948 E QarthLog: [PatchStore] current thread application info is null
11-30 16:04:30.270  3948  3948 E AndroidRuntime: Error reporting crash
11-30 16:04:30.270  3948  3948 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:1149)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:125)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at android.os.ServiceManager.rawGetService(ServiceManager.java:253)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:124)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:4163)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:4160)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at android.app.ActivityManager.getService(ActivityManager.java:4156)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$LoggingHandler.uncaughtException(RuntimeInit.java:111)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:1970)
11-30 16:04:30.270  3948  3948 E AndroidRuntime: FATAL EXCEPTION: main
11-30 16:04:30.270  3948  3948 E AndroidRuntime: PID: 3948
11-30 16:04:30.270  3948  3948 E AndroidRuntime: android.media.MediaCodec$CodecException: Error 0xfffffc0e
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at android.media.MediaCodec.native_configure(Native Method)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at android.media.MediaCodec.configure(MediaCodec.java:1967)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at android.media.MediaCodec.configure(MediaCodec.java:1896)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:167)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:68)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at com.genymobile.scrcpy.Server.main(Server.java:146)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-30 16:04:30.270  3948  3948 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
11-30 16:04:30.270  3948  3948 E scrcpy  : Exception on thread Thread[main,5,main]
11-30 16:04:30.270  3948  3948 E scrcpy  : android.media.MediaCodec$CodecException: Error 0xfffffc0e
11-30 16:04:30.270  3948  3948 E scrcpy  :      at android.media.MediaCodec.native_configure(Native Method)
11-30 16:04:30.270  3948  3948 E scrcpy  :      at android.media.MediaCodec.configure(MediaCodec.java:1967)
11-30 16:04:30.270  3948  3948 E scrcpy  :      at android.media.MediaCodec.configure(MediaCodec.java:1896)
11-30 16:04:30.270  3948  3948 E scrcpy  :      at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:167)
11-30 16:04:30.270  3948  3948 E scrcpy  :      at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:68)
11-30 16:04:30.270  3948  3948 E scrcpy  :      at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
11-30 16:04:30.270  3948  3948 E scrcpy  :      at com.genymobile.scrcpy.Server.main(Server.java:146)
11-30 16:04:30.270  3948  3948 E scrcpy  :      at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-30 16:04:30.270  3948  3948 E scrcpy  :      at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream

**Comment by Sth32** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream

FAQ solved my problem, thanks

**Comment by rom1v** [comment]
Too many people encounter this problem without knowing how to fix it, so I added a suggestion directly in the console: 8a694a97855333849976bea5e558eaa45add0168.
