### ISSUE TITLE
Xiaomi MiUI: java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml

### ISSUE THREAD

**Issue by siddharths2710** [Genymobile/scrcpy#994]
**OS**: Ubuntu 16.04
**Android**: Version 5.0.2
**Mode of running**: [Run scrcpy without installation](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#run)

On running the program without installation, the bottom keys are missing from the display (Please zoom in the image):

![scrcpy_issue1-min](https://user-images.githubusercontent.com/13200018/70490166-ba340c80-1b23-11ea-99c5-7863ee987758.png)

Please check the log that appears after executing `./run x`

```
INFO: scrcpy 1.12 <https://github.com/Genymobile/scrcpy>
551 KB/s (26234 bytes in 0.046s)
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at java.io.FileInputStream.<init>(FileInputStream.java:103)
	at java.io.FileReader.<init>(FileReader.java:66)
	at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
	at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
	at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
	at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
	at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
	at android.content.res.MiuiResources.<clinit>(MiuiResources.java:29)
	at android.content.res.Resources.getSystem(Resources.java:259)
	at android.app.LoadedApk.<init>(LoadedApk.java:197)
	at android.app.ContextImpl.createSystemContext(ContextImpl.java:2214)
	at android.app.ActivityThread.getSystemContext(ActivityThread.java:1812)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:329)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:442)
	... 21 more
INFO: Initial texture: 1080x1920
```

**Comment by siddharths2710** [comment]
Upon trying `adb shell ls /data/`, it says `opendir failed, Permission denied`. Could this be the issue?
Unfortunately I'm not able to execute `adb root` for the device :(

**Comment by hafizidev** [comment]
I ran into same error message. But mine use full screen gesture, so mine never shows bottom navigation bar. Seems like Xiaomi's MiUI related issue?

OS: Windows 10
Android: Version 10.0
Android Device: Xiaomi Mi 9T

```
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
C:\Users\User\scrcpy\scrcpy-server: 1 file pushed. 4.3 MB/s (26202 bytes in 0.006s)
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:40)
        at android.content.res.Resources.<init>(Resources.java:283)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
        at android.content.res.Resources.getSystem(Resources.java:204)
        at android.app.LoadedApk.<init>(LoadedApk.java:235)
        at android.app.ContextImpl.createSystemContext(ContextImpl.java:2430)
        at android.app.ActivityThread.getSystemContext(ActivityThread.java:2427)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
        at com.genymobile.scrcpy.Server.main(Server.java:163)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        ... 22 more
INFO: Initial texture: 1080x2336
```

**Comment by siddharths2710** [comment]
@hafizidev Yeah should be. In any case, we can depend on the [shortcuts](https://github.com/Genymobile/scrcpy#shortcuts) as an alternative.

**Comment by rom1v** [comment]
> On running the program without installation, the bottom keys are missing from the display (Please zoom in the image):

That's expected. If they don't appear on the device, they won't be mirrored. See #7.

IIUC, there is an exception, but mirroring still works?

To investigate the issue, could you test with 1.11 and 1.10, please (which changed things where the exception occurs)?

**Comment by hafizidev** [comment]
> > On running the program without installation, the bottom keys are missing from the display (Please zoom in the image):
> 
> That's expected. If they don't appear on the device, they won't be mirrored. See #7.
> 
> IIUC, there is an exception, but mirroring still works?
> 
> To investigate the issue, could you test with 1.11 and 1.10, please (which changed things where the exception occurs)?

Yes mirroring still works, just there is exception in the console while starting the app.

I ran both version 1.10 and 1.11 and this exception doesn't occur in both versions.

**Comment by rom1v** [comment]
OK, so this is harmless. It's just a workaround which is applied to make some devices work.

When the workaround fails for some reason it just log the stacktrace in the console.

**Comment by Xplouder** [comment]
Looks like I have the same/similar error. However the cast works but i can not control de device.
```
INFO: scrcpy 1.12 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 3.0 MB/s (26196 bytes in 0.008s)
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.io.FileReader.<init>(FileReader.java:58)
	at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
	at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
	at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
	at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
	at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
	at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:40)
	at android.content.res.Resources.<init>(Resources.java:267)
	at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
	at android.content.res.Resources.getSystem(Resources.java:190)
	at android.app.LoadedApk.<init>(LoadedApk.java:211)
	at android.app.ContextImpl.createSystemContext(ContextImpl.java:2331)
	at android.app.ActivityThread.getSystemContext(ActivityThread.java:2190)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)
INFO: Initial texture: 1080x2336
```

**Comment by rom1v** [comment]
@Xplouder https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-can-only-mirror-i-cannot-interact-with-the-device

**Comment by vncastanheira** [comment]
This happens with my Xiaomi phone as well and I'm also using fullscreen gestures. 
At least it doesn't crash the application.

Btw, awesome app.

**Comment by acai2046** [comment]
`C:\Users\Administrator>adb shell
chiron:/ $ ls /data/
ls: /data/: Permission denied
1|chiron:/ $ ls /
ls: //vndservice_contexts: Permission denied
ls: //verity_key: Permission denied
ls: //vendor_service_contexts: Permission denied
ls: //vendor_hwservice_contexts: Permission denied
ls: //ueventd.rc: Permission denied
ls: //plat_hwservice_contexts: Permission denied
ls: //init.zygote64_32.rc: Permission denied
ls: //init.zygote32.rc: Permission denied
ls: //init.usb.rc: Permission denied
ls: //init.usb.configfs.rc: Permission denied
ls: //init.recovery.qcom.rc: Permission denied
ls: //init.recovery.hardware.rc: Permission denied
ls: //init.rc: Permission denied
ls: //init.miui.rc: Permission denied
ls: //init.miui.post_boot.sh: Permission denied
ls: //init.miui.nativedebug.rc: Permission denied
ls: //init.miui.google_revenue_share_v2.rc: Permission denied
ls: //init.miui.google_revenue_share.rc: Permission denied
ls: //init.miui.early_boot.sh: Permission denied
ls: //init.miui.cust.rc: Permission denied
ls: //init.environ.rc: Permission denied
ls: //init.batteryd.rc: Permission denied
ls: //init: Permission denied
ls: //default.prop: Permission denied
ls: //cn.prop: Permission denied
acct        data     plat_file_contexts     sdcard
bin         dev      plat_property_contexts sepolicy
bt_firmware dsp      plat_seapp_contexts    storage
bugreports  etc      plat_service_contexts  sys
cache       firmware proc                   system
charger     mnt      product                vendor
config      odm      res                    vendor_file_contexts
cust        oem      root                   vendor_property_contexts
d           persist  sbin                   vendor_seapp_contexts`

**Comment by acai2046** [comment]
/storage/emulated/0/data/目录，和/data/目录不是同一个目录吧？

**Comment by rom1v** [comment]
Since this is harmless (https://github.com/Genymobile/scrcpy/issues/994#issuecomment-564418009), I disabled the error report: 96bd2c974d0fb9765dc4d2978688bb0bbd65cc9f

**Comment by rom1v** [comment]
In fact, the error is still printed: #1336 :confused:

**Comment by rom1v** [comment]
The failing statement is here:

https://github.com/Genymobile/scrcpy/blob/4e9e712312c9726824d28bed4fc85721e3a2b203/server/src/main/java/com/genymobile/scrcpy/Workarounds.java#L66

The whole thing is in a try-catch-Throwable block, which logs only in debug mode. (and the message `Could not fill app info:` does not appear, so in fact this specific log is not printed).

So I guess some method in the callstack catch the exception and call `printStackTrace()` before rethrowing… :disappointed:

**Comment by rom1v** [comment]
Could you please take scrcpy v1.13 and replace this file:

[`scrcpy-server`](https://tmp.rom1v.com/scrcpy/issue994/1/scrcpy-server)
_SHA256: b64e6672eeb2b7c00c6f83673783bd8839ba65ea2ac7edcdeeca44676047328b_

and confirm that it works without the error message.

Thank you.

**Comment by flynncowell** [comment]
This issue isn't allowing me to do anything, apart from see my interactions with the phone itself. 

Love this tool though

**Comment by hafizidev** [comment]
> 
> 
> Could you please take scrcpy v1.13 and replace this file:
> 
> [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/issue994/1/scrcpy-server)
> _SHA256: b64e6672eeb2b7c00c6f83673783bd8839ba65ea2ac7edcdeeca44676047328b_
> 
> and confirm that it works without the error message.
> 
> Thank you.

Yeah, no more error displays after I replaced with yours

**Comment by rom1v** [comment]
@hafizidev Thank you for your feedback :+1:

**Comment by hafizidev** [comment]
> 
> 
> @hafizidev Thank you for your feedback 👍

My pleasure. But I just noticed, I got a warning

```
[server] INFO: Device: Xiaomi MI 9T (Android 10.0)
INFO: Renderer: direct3d
WARN: Trilinear filtering disabled (not an OpenGL renderer)
INFO: Initial texture: 1080x2336
```

**Comment by rom1v** [comment]
Yes, that's expected. Check §"Downscaling quality" here: https://github.com/Genymobile/scrcpy/releases/tag/v1.13

(`scrcpy --render-driver=opengl` should remove the warning, and you'll get trilinear filtering)

**Comment by azhenglianxi** [comment]
棒棒哒~ 我想问这是什么语音开发的 小白 看着啥都想 但是感觉啥都不是 混合语言吗

**Comment by Sanmejie** [comment]
`C:\Users\Administrator>scrcpy
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
F:\Scoop\apps\scrcpy\current\scrcpy-server: 1 file pushed. 2.9 MB/s (37330 bytes in 0.012s)
[server] INFO: Device: Xiaomi MI PAD 2 (Android 5.1)
INFO: Renderer: direct3d
INFO: Initial texture: 2048x1536
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:114)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:95)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:329)
`

**Comment by B4O9** [comment]
Hello, I am having this issue.
`INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 9.5 MB/s (24773 bytes in 0.002s)
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)INFO: Initial texture: 1080x2400

	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at java.io.FileReader.<init>(FileReader.java:60)
	at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
	at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
	at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
	at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
	at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
	at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
	at android.content.res.MiuiResources.<init>(MiuiResources.java:58)
	at android.content.res.IMiuiResourceImpl.createResources(IMiuiResourceImpl.java:13)
	at android.content.res.ThemeManagerStub.createMiuiResources(ThemeManagerStub.java:56)
	at android.content.res.Resources.getSystem(Resources.java:235)
	at android.app.LoadedApk.<init>(LoadedApk.java:243)
	at android.app.ContextImpl.createSystemContext(ContextImpl.java:2980)
	at android.app.ActivityThread.getSystemContext(ActivityThread.java:2722)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:383)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 23 more
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:178)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:70)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:383)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
WARN: Device disconnected
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 6 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3215)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2254)
	... 8 more
`

**Comment by rom1v** [comment]
Use a newer version.

> Caused by: java.lang.IllegalArgumentException: displayToken must not be null

Android 12 requires at least scrcpy v1.18. Just use the latest (1.25 currently).
